<a href="https://colab.research.google.com/github/sun219361/Public-Data-Driven-Urban-Parking-Violation-Analysis/blob/main/ML_project_DININGCODE_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

다이닝 코드 음식장소 추천

In [ ]:
# ChromeDriver 설치
!apt-get update
!apt-get install -y chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

!pip install webdriver_manager
!pip install --upgrade webdriver_manager
!pip install threadpoolctl==3.1.0

# Selenium 설치
!pip install selenium
!pip install --upgrade selenium

In [ ]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from urllib.request import urlopen
from selenium import webdriver
import re
import time
import urllib
import requests
from selenium import webdriver
from selenium.webdriver.chrome.options import Options


# Chrome 옵션 설정
chrome_options = Options()
chrome_options.add_argument('--headless')  # 브라우저를 표시하지 않고 실행할 경우

chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

구별로 링크 가져오기

https://www.diningcode.com/?region=

https://www.diningcode.com/profile.php?rid=

In [ ]:
#서울시 구 정의 : 총 24개의 구
gu_list = ["강남구","강동구","강북구","강서구","관악구","광진구","구로구","금천구",
          "노원구","도봉구","동대문구","동작구","마포구","서대문구","서초구","성북구",
           "송파구","양천구","영등포구","용산구","은평구","종로구","중구", "중랑구"]

In [ ]:
# 다이닝 코드에서 식당 링크 가져오기
def get_links_DiningCode(gu):
    # Chrome 옵션 설정
    chrome_options = Options()
    chrome_options.add_argument('--headless')  # 브라우저를 표시하지 않고 실행할 경우
    chrome_options.add_argument('--no-sandbox')
    chrome_options.add_argument('--disable-dev-shm-usage')

    # Chrome 드라이버 초기화
    driver = webdriver.Chrome(options=chrome_options)

    # 올바른 도시 코드 및 인코딩을 사용하여 URL 수정
    encoded_gu = urllib.parse.quote(gu)  # 한글 문자를 URL에 사용하기 위해 인코딩
    url = f"https://www.diningcode.com/list.php?query=서울%20{encoded_gu}"

    print("접근 중인 URL:", url)  # 이 줄을 추가하여 접근 중인 URL을 출력

    # 사용자 에이전트 헤더 설정
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
    }

    # HTTP GET 요청 보내기
    response = requests.get(url, headers=headers)

    # 로딩된 후 모든 링크 찾기
    link_elements = driver.find_elements(By.TAG_NAME, "a")
    res_links_raw = [link.get_attribute('href') for link in link_elements]

    res_links = [link for link in res_links_raw if 'profile' in link]
    res_links = list(set(res_links))
    Diningcode_links.extend(res_links)
    print(f'{gu}에서 {len(res_links)}곳 찾음')

    # 데이터가 충분하지 않은 경우
    if len(res_links) < 80:
        retry.append(gu)

    driver.close()

Diningcode_links = []
retry = []

for gu in gu_list:
    get_links_DiningCode(gu)

for gu in retry:
    get_links_DiningCode(gu)

len(Diningcode_links)

In [ ]:
Diningcode_links = list(set(Diningcode_links))

# save into text
with open("/content/drive/MyDrive/ML_data/restaurants_DiningCode.txt","w") as f:
    f.write('\n'.join(Diningcode_links))

크롤링
리뷰 & 가게

In [ ]:
D_restaurants_df = pd.DataFrame(columns=['name', 'address', 'category', 'main_mn', 'price', 'opng_tm', 'rating', 'rvw_cnt', 'tags'])
D_review_df = pd.DataFrame(columns=['res_name', 'user_name', 'rating', 'review'])

with open("/content/drive/MyDrive/ML_data/restaurants_DiningCode.txt", "r") as f:
    text = f.read()
urls = text.split()
urls

['https://www.diningcode.com/profile.php?rid=gymPpxy0wqyW',
 'https://www.diningcode.com/profile.php?rid=oFt7VQgJPD1x',
 'https://www.diningcode.com/profile.php?rid=rBGa94tjOhim',
 'https://www.diningcode.com/profile.php?rid=BIEVntjGgPBR',
 'https://www.diningcode.com/profile.php?rid=qYdn9yfYsqqR',
 'https://www.diningcode.com/profile.php?rid=ZbmKyMjf8LyV',
 'https://www.diningcode.com/profile.php?rid=X1677Q73zrTn',
 'https://www.diningcode.com/profile.php?rid=3m2pRph0pdjc',
 'https://www.diningcode.com/profile.php?rid=4pdt1C6gTjcU',
 'https://www.diningcode.com/profile.php?rid=xqY9zju9W4iZ',
 'https://www.diningcode.com/profile.php?rid=moKeujGlfTTW',
 'https://www.diningcode.com/profile.php?rid=GcNxur2JKeiv',
 'https://www.diningcode.com/profile.php?rid=WEh6gjz1tVd6',
 'https://www.diningcode.com/profile.php?rid=WIw4lV7nuN5O',
 'https://www.diningcode.com/profile.php?rid=9TUCHgdvAGHI',
 'https://www.diningcode.com/profile.php?rid=RPQbcSFyplWY',
 'https://www.diningcode.com/profile.php?rid=foUrck3UkUZk',
 'https://www.diningcode.com/profile.php?rid=eWIWSHIwPoBB',
 'https://www.diningcode.com/profile.php?rid=t1m9OnLGqECO',
 'https://www.diningcode.com/profile.php?rid=atcvTfGn6qIx',
 'https://www.diningcode.com/profile.php?rid=KEVMfOpDAXzi',
 'https://www.diningcode.com/profile.php?rid=ru8n9lMcj0hB',
 'https://www.diningcode.com/profile.php?rid=6DsENuiNssXH',
 'https://www.diningcode.com/profile.php?rid=MQnIbmFWmZvI',
 'https://www.diningcode.com/profile.php?rid=1ZNPuxDn1rzy',
 'https://www.diningcode.com/profile.php?rid=u02g4at7sOo6',
 'https://www.diningcode.com/profile.php?rid=qdCjoDngig4x',
 'https://www.diningcode.com/profile.php?rid=ws8hFbpJ68kE',
 'https://www.diningcode.com/profile.php?rid=e3FwOVbot8Vc',
 'https://www.diningcode.com/profile.php?rid=ZidlKeh2NLqt',
 'https://www.diningcode.com/profile.php?rid=H1Irb11tYjvA',
 'https://www.diningcode.com/profile.php?rid=BcLJLcueCTE5',
 'https://www.diningcode.com/profile.php?rid=uoKOdrPEIDUz',
 'https://www.diningcode.com/profile.php?rid=p1QQHlieCVX1',
 'https://www.diningcode.com/profile.php?rid=IvoPi3MlRchB',
 'https://www.diningcode.com/profile.php?rid=U4fdgy4Z4HDd',
 'https://www.diningcode.com/profile.php?rid=HgqXiiGwONim',
 'https://www.diningcode.com/profile.php?rid=x25o01ofbL4I',
 'https://www.diningcode.com/profile.php?rid=AqioENAGyNsc',
 'https://www.diningcode.com/profile.php?rid=idF33aRz3mqm',
 'https://www.diningcode.com/profile.php?rid=Dr9p9LjEo4ne',
 'https://www.diningcode.com/profile.php?rid=i8espQyHL8Kp',
 'https://www.diningcode.com/profile.php?rid=ZE7zLkCJhA0j',
 'https://www.diningcode.com/profile.php?rid=Hw5XteFa0B0t',
 'https://www.diningcode.com/profile.php?rid=9K2oiBv3P90r',
 'https://www.diningcode.com/profile.php?rid=OKFDnhQQ5UEP',
 'https://www.diningcode.com/profile.php?rid=Zzhf3ujhD9C9',
 'https://www.diningcode.com/profile.php?rid=f01Vpe4DtVM5',
 'https://www.diningcode.com/profile.php?rid=VQKX8e1OMo0w',
 'https://www.diningcode.com/profile.php?rid=k14pzHqkN3Ji',
 'https://www.diningcode.com/profile.php?rid=OH1twfaoRjeZ',
 'https://www.diningcode.com/profile.php?rid=G07HI9rMbCLQ',
 'https://www.diningcode.com/profile.php?rid=ux4IeOtoFbYQ',
 'https://www.diningcode.com/profile.php?rid=2RAovsKqJOn0',
 'https://www.diningcode.com/profile.php?rid=YV1SYxGA5n6e',
 'https://www.diningcode.com/profile.php?rid=sVpNDxWcc38o',
 'https://www.diningcode.com/profile.php?rid=PNU4Mh9gDlzH',
 'https://www.diningcode.com/profile.php?rid=xNrWF75lvWR2',
 'https://www.diningcode.com/profile.php?rid=fvjwH25Y4hUI',
 'https://www.diningcode.com/profile.php?rid=lUf5zeJ5jBKE',
 'https://www.diningcode.com/profile.php?rid=RZyGsyojiYKt',
 'https://www.diningcode.com/profile.php?rid=PU0Ws3ol4BtF',
 'https://www.diningcode.com/profile.php?rid=0gIlffHMqTu8',
 'https://www.diningcode.com/profile.php?rid=8mipQVEAhUyD',
 'https://www.diningcode.com/profile.php?rid=nP9Vedlabe9n',
 'https://www.diningcode.com/profile.php?rid=2EdNQBlp1u3D',
 'https://www.diningcode.com/profile.php?rid=AETlCmjsYBTe',
 'https://www.diningcode.com/profile.php?rid=rRH1W3eoaN9Z',
 'https://www.diningcode.com/profile.php?rid=3BYJrP3Ev9wz',
 'https://www.diningcode.com/profile.php?rid=NZOkZHLUaITz',
 'https://www.diningcode.com/profile.php?rid=Wu1FcYCb9wit',
 'https://www.diningcode.com/profile.php?rid=WdpWXhiFYykY',
 'https://www.diningcode.com/profile.php?rid=NY0RRQz4pRuo',
 'https://www.diningcode.com/profile.php?rid=NH6pLOypMdmP',
 'https://www.diningcode.com/profile.php?rid=YFFFNeor6w9Q',
 'https://www.diningcode.com/profile.php?rid=eHAv6t6vmGs1',
 'https://www.diningcode.com/profile.php?rid=2Cq4UeHELQJO',
 'https://www.diningcode.com/profile.php?rid=pklcSEXDXYTj',
 'https://www.diningcode.com/profile.php?rid=BJBY5ywlshP1',
 'https://www.diningcode.com/profile.php?rid=liXYLXsPvfLp',
 'https://www.diningcode.com/profile.php?rid=849BrcFboabg',
 'https://www.diningcode.com/profile.php?rid=f6S6qUTw8trB',
 'https://www.diningcode.com/profile.php?rid=K24tbUJIf7eW',
 'https://www.diningcode.com/profile.php?rid=KQ5zWfaxuyt6',
 'https://www.diningcode.com/profile.php?rid=OUfWYifdm6nL',
 'https://www.diningcode.com/profile.php?rid=RaG5omstHyme',
 'https://www.diningcode.com/profile.php?rid=Px5rlUqZmKed',
 'https://www.diningcode.com/profile.php?rid=B2IlyErIsLn8',
 'https://www.diningcode.com/profile.php?rid=n6OwxIGJdkmL',
 'https://www.diningcode.com/profile.php?rid=DUI5cf43Uk5x',
 'https://www.diningcode.com/profile.php?rid=6LDmwY3t06Kc',
 'https://www.diningcode.com/profile.php?rid=fnwQCOZFgIFZ',
 'https://www.diningcode.com/profile.php?rid=CexKfHLT3oiX',
 'https://www.diningcode.com/profile.php?rid=NQr0pngXyXEo',
 'https://www.diningcode.com/profile.php?rid=LMPRnmFAch1z',
 'https://www.diningcode.com/profile.php?rid=NhjemKIyeEAt',
 'https://www.diningcode.com/profile.php?rid=ZFQ6b45PblF2',
 'https://www.diningcode.com/profile.php?rid=r3Qoxoqd52oh',
 'https://www.diningcode.com/profile.php?rid=7rmpP52W7ikR',
 'https://www.diningcode.com/profile.php?rid=xziE4ZyECLXA',
 'https://www.diningcode.com/profile.php?rid=EzYhGxeuetqI',
 'https://www.diningcode.com/profile.php?rid=pWbYrJrEFpoq',
 'https://www.diningcode.com/profile.php?rid=pFWTyH0WOm3l',
 'https://www.diningcode.com/profile.php?rid=jq2dnrx2yFhh',
 'https://www.diningcode.com/profile.php?rid=SFDRGLItjNeP',
 'https://www.diningcode.com/profile.php?rid=a0SZ2hymgiZz',
 'https://www.diningcode.com/profile.php?rid=Rh51jN0G5yBV',
 'https://www.diningcode.com/profile.php?rid=WEeqhRFIPtvi',
 'https://www.diningcode.com/profile.php?rid=5CI4Y2chbsbV',
 'https://www.diningcode.com/profile.php?rid=IdBHbiPVIbWn',
 'https://www.diningcode.com/profile.php?rid=ox8OfFUidqmj',
 'https://www.diningcode.com/profile.php?rid=X84OlQP5MUME',
 'https://www.diningcode.com/profile.php?rid=yLGuFof7qy4G',
 'https://www.diningcode.com/profile.php?rid=6uQ49fmivB8t',
 'https://www.diningcode.com/profile.php?rid=5cvwp9voD3bk',
 'https://www.diningcode.com/profile.php?rid=9hBEgxtjBFth',
 'https://www.diningcode.com/profile.php?rid=RkIkgWwNPS4w',
 'https://www.diningcode.com/profile.php?rid=ECKWlXPgaH2X',
 'https://www.diningcode.com/profile.php?rid=1Yq7wWcoo9lC',
 'https://www.diningcode.com/profile.php?rid=rlN31cjpPvtV',
 'https://www.diningcode.com/profile.php?rid=QuTVZ7eAmVvR',
 'https://www.diningcode.com/profile.php?rid=kkIUDZnHBIpt',
 'https://www.diningcode.com/profile.php?rid=AYQsX9L0k2oA',
 'https://www.diningcode.com/profile.php?rid=vAekr6UVblJ6',
 'https://www.diningcode.com/profile.php?rid=NU4V8AYXg142',
 'https://www.diningcode.com/profile.php?rid=GRr9UWjd8GqI',
 'https://www.diningcode.com/profile.php?rid=gzA6UJdxeavT',
 'https://www.diningcode.com/profile.php?rid=ubUZX53kWj5m',
 'https://www.diningcode.com/profile.php?rid=0haNb3mwAXQz',
 'https://www.diningcode.com/profile.php?rid=QhnzeMHJdh0Q',
 'https://www.diningcode.com/profile.php?rid=GgwBseTJQFob',
 'https://www.diningcode.com/profile.php?rid=1teeNcuJ6NA8',
 'https://www.diningcode.com/profile.php?rid=4VJ8QlhMsrMh',
 'https://www.diningcode.com/profile.php?rid=vNt714s2dO8W',
 'https://www.diningcode.com/profile.php?rid=gbMs62YtaoTl',
 'https://www.diningcode.com/profile.php?rid=tZknX2H9SdJo',
 'https://www.diningcode.com/profile.php?rid=A2EF5ZNPl9AS',
 'https://www.diningcode.com/profile.php?rid=XqVK9N66vdGd',
 'https://www.diningcode.com/profile.php?rid=kwdUq6LBFrrJ',
 'https://www.diningcode.com/profile.php?rid=Oi4s4WbcVhDn',
 'https://www.diningcode.com/profile.php?rid=5DrsfzZ6YWkt',
 'https://www.diningcode.com/profile.php?rid=bdwkCguAn8oJ',
 'https://www.diningcode.com/profile.php?rid=WsEUDeSK1Xcw',
 'https://www.diningcode.com/profile.php?rid=E7Mo4kNvfPgB',
 'https://www.diningcode.com/profile.php?rid=MeZ2Y8Idxqb6',
 'https://www.diningcode.com/profile.php?rid=yMSsDhYiJwK6',
 'https://www.diningcode.com/profile.php?rid=Vm8ZUlpWQnxZ',
 'https://www.diningcode.com/profile.php?rid=F3F3FnnOX4sL',
 'https://www.diningcode.com/profile.php?rid=7QYZVP1dCQSv',
 'https://www.diningcode.com/profile.php?rid=Oorv5xxvAYqi',
 'https://www.diningcode.com/profile.php?rid=WaH1PcBw73di',
 'https://www.diningcode.com/profile.php?rid=Gau3N8eMaxZv',
 'https://www.diningcode.com/profile.php?rid=jSOHQA2UVVuk',
 'https://www.diningcode.com/profile.php?rid=bCIEgJcuFhbu',
 'https://www.diningcode.com/profile.php?rid=kXWkO1e2FIuv',
 'https://www.diningcode.com/profile.php?rid=gsxaiq6TY1Nl',
 'https://www.diningcode.com/profile.php?rid=Ki3cMNRDDrz5',
 'https://www.diningcode.com/profile.php?rid=X8mwFWa6Adu7',
 'https://www.diningcode.com/profile.php?rid=kOCflyl1Mc4h',
 'https://www.diningcode.com/profile.php?rid=Btn3fd2QF8hl',
 'https://www.diningcode.com/profile.php?rid=t6h6GpPIg7Vp',
 'https://www.diningcode.com/profile.php?rid=5d9l2YW80lhW',
 'https://www.diningcode.com/profile.php?rid=VFj0vDaW3tOd',
 'https://www.diningcode.com/profile.php?rid=Umatcp7Smitw',
 'https://www.diningcode.com/profile.php?rid=bEZXzgJcI530',
 'https://www.diningcode.com/profile.php?rid=lCAx6uaVRYkV',
 'https://www.diningcode.com/profile.php?rid=dPIvSSSMthQB',
 'https://www.diningcode.com/profile.php?rid=XN1hoUSLM9vv',
 'https://www.diningcode.com/profile.php?rid=f549JLWcaeYT',
 'https://www.diningcode.com/profile.php?rid=HlgBxhl5Qdxc',
 'https://www.diningcode.com/profile.php?rid=C4L6rbNF6Qts',
 'https://www.diningcode.com/profile.php?rid=1MnDDh0HMDxl',
 'https://www.diningcode.com/profile.php?rid=74F63ca7mJoU',
 'https://www.diningcode.com/profile.php?rid=dFjH9IaSesjU',
 'https://www.diningcode.com/profile.php?rid=pTGW5nxdVPVc',
 'https://www.diningcode.com/profile.php?rid=tvJZTgYacghD',
 'https://www.diningcode.com/profile.php?rid=hTDRRXD7OC4a',
 'https://www.diningcode.com/profile.php?rid=5jd7lDjE5yZ5',
 'https://www.diningcode.com/profile.php?rid=4HsIClKxshAp',
 'https://www.diningcode.com/profile.php?rid=arQeeqJGeblm',
 'https://www.diningcode.com/profile.php?rid=G1j9zI8Wukia',
 'https://www.diningcode.com/profile.php?rid=Ku3cIFCKrzAV',
 'https://www.diningcode.com/profile.php?rid=TLkYodL8VXJw',
 'https://www.diningcode.com/profile.php?rid=BFAihbIfBBJV',
 'https://www.diningcode.com/profile.php?rid=IjWexXq5Vlmi',
 'https://www.diningcode.com/profile.php?rid=5O6P3j019i77',
 'https://www.diningcode.com/profile.php?rid=frq7e3MgBolr',
 'https://www.diningcode.com/profile.php?rid=WguZpMryQHyb',
 'https://www.diningcode.com/profile.php?rid=14NFWd2O6ORI',
 'https://www.diningcode.com/profile.php?rid=I5VP0rtlJLfV',
 'https://www.diningcode.com/profile.php?rid=GsICORYYNLEs',
 'https://www.diningcode.com/profile.php?rid=a06bC927gZlD',
 'https://www.diningcode.com/profile.php?rid=hMap6Y5Divpk',
 'https://www.diningcode.com/profile.php?rid=bYEcoR5h7O5e',
 'https://www.diningcode.com/profile.php?rid=UzfghC7EJc4y',
 'https://www.diningcode.com/profile.php?rid=OYV1OFujcP4O',
 'https://www.diningcode.com/profile.php?rid=unTQ776AEJyz',
 'https://www.diningcode.com/profile.php?rid=I51VgwTGIVGC',
 'https://www.diningcode.com/profile.php?rid=FifDkSgi1aTi',
 'https://www.diningcode.com/profile.php?rid=0HWKeMiP3oLG',
 'https://www.diningcode.com/profile.php?rid=JeuHoNzGt3EY',
 'https://www.diningcode.com/profile.php?rid=qHn3fRlxIjHp',
 'https://www.diningcode.com/profile.php?rid=kpUfdl195qqY',
 'https://www.diningcode.com/profile.php?rid=uA9Kymqt5uVw',
 'https://www.diningcode.com/profile.php?rid=0hOl4NloZ4cD',
 'https://www.diningcode.com/profile.php?rid=83txlws37uGM',
 'https://www.diningcode.com/profile.php?rid=UCw35wnYgApa',
 'https://www.diningcode.com/profile.php?rid=Xy50jfZZTIzX',
 'https://www.diningcode.com/profile.php?rid=E8bvPYVlpCBY',
 'https://www.diningcode.com/profile.php?rid=MqSPrWq4MCFi',
 'https://www.diningcode.com/profile.php?rid=smh3IkKGxKNZ',
 'https://www.diningcode.com/profile.php?rid=fAaYVH7bahro',
 'https://www.diningcode.com/profile.php?rid=oshF9vZKc8pl',
 'https://www.diningcode.com/profile.php?rid=jfKUnPTxoheI',
 'https://www.diningcode.com/profile.php?rid=l1SUGbIU0mhP',
 'https://www.diningcode.com/profile.php?rid=Q2gu84vBJ8kJ',
 'https://www.diningcode.com/profile.php?rid=dEd2Z4qs1ADs',
 'https://www.diningcode.com/profile.php?rid=thFCta5fO5oo',
 'https://www.diningcode.com/profile.php?rid=ZVZLd0BV0ZhV',
 'https://www.diningcode.com/profile.php?rid=D94DnLr2xFVq',
 'https://www.diningcode.com/profile.php?rid=ALUHZ9aHi8lv',
 'https://www.diningcode.com/profile.php?rid=DAmrGXY1Vd5o',
 'https://www.diningcode.com/profile.php?rid=Y8gw6DNblVZC',
 'https://www.diningcode.com/profile.php?rid=hsxNkssbzOjg',
 'https://www.diningcode.com/profile.php?rid=dwvS1BAUzBBY',
 'https://www.diningcode.com/profile.php?rid=faImPvzDoVRy',
 'https://www.diningcode.com/profile.php?rid=jPaKJVUiYWrk',
 'https://www.diningcode.com/profile.php?rid=6T7Df2H1TMf7',
 'https://www.diningcode.com/profile.php?rid=HlOB3IMpPH4H',
 'https://www.diningcode.com/profile.php?rid=rS0YKcScRaO3',
 'https://www.diningcode.com/profile.php?rid=QoiMP1LccdCG',
 'https://www.diningcode.com/profile.php?rid=0zgdfBymiRJQ',
 'https://www.diningcode.com/profile.php?rid=tLqfXBhhzECk',
 'https://www.diningcode.com/profile.php?rid=AuvHUlVPTEf1',
 'https://www.diningcode.com/profile.php?rid=NCCwdTmBqelK',
 'https://www.diningcode.com/profile.php?rid=Qf2JmKCvGQRZ',
 'https://www.diningcode.com/profile.php?rid=Q2aMjuw2lv7M',
 'https://www.diningcode.com/profile.php?rid=86swa21VRGsh',
 'https://www.diningcode.com/profile.php?rid=qH2vAlWrswOZ',
 'https://www.diningcode.com/profile.php?rid=kFFoAT3nW4dD',
 'https://www.diningcode.com/profile.php?rid=V9elszqTY8cR',
 'https://www.diningcode.com/profile.php?rid=slgiHfQs8bzN',
 'https://www.diningcode.com/profile.php?rid=3O9QJ8FvZxs1',
 'https://www.diningcode.com/profile.php?rid=Am3aXR5T30v0',
 'https://www.diningcode.com/profile.php?rid=Furi4ETVCRuG',
 'https://www.diningcode.com/profile.php?rid=nPsRHncwrqYB',
 'https://www.diningcode.com/profile.php?rid=6H0fnYbHDSQ3',
 'https://www.diningcode.com/profile.php?rid=9rKDDwOTZvvS',
 'https://www.diningcode.com/profile.php?rid=fOdj2WchYbaW',
 'https://www.diningcode.com/profile.php?rid=IJI5rFM8I7fJ',
 'https://www.diningcode.com/profile.php?rid=IEDnbeacvZRy',
 'https://www.diningcode.com/profile.php?rid=1k1ZOCRnRZIq',
 'https://www.diningcode.com/profile.php?rid=AA5aI0TNaQmb',
 'https://www.diningcode.com/profile.php?rid=xh3yZTrL4gEY',
 'https://www.diningcode.com/profile.php?rid=3pCfPg9sK2iM',
 'https://www.diningcode.com/profile.php?rid=Vl381E1OAcwh',
 'https://www.diningcode.com/profile.php?rid=SVFxZTgqnm9J',
 'https://www.diningcode.com/profile.php?rid=DojYc2KkvL0t',
 'https://www.diningcode.com/profile.php?rid=DGMdBn1U1ENd',
 'https://www.diningcode.com/profile.php?rid=Bugh3o659f7W',
 'https://www.diningcode.com/profile.php?rid=qaYFEeMGw3g5',
 'https://www.diningcode.com/profile.php?rid=ZDA8SjIMU5VQ',
 'https://www.diningcode.com/profile.php?rid=ipp9DGiQbVn7',
 'https://www.diningcode.com/profile.php?rid=YJoe1dB5bKNw',
 'https://www.diningcode.com/profile.php?rid=istSp9nBTlDp',
 'https://www.diningcode.com/profile.php?rid=5P6cDG6wx8CL',
 'https://www.diningcode.com/profile.php?rid=oWCsVQVpDkBU',
 'https://www.diningcode.com/profile.php?rid=Z02tOiGZKKVI',
 'https://www.diningcode.com/profile.php?rid=h0jCQ7zQ6IDd',
 'https://www.diningcode.com/profile.php?rid=swggRI9VTqp1',
 'https://www.diningcode.com/profile.php?rid=PeVSD0gnWJdo',
 'https://www.diningcode.com/profile.php?rid=wSJahbdw0wJQ',
 'https://www.diningcode.com/profile.php?rid=QEVxyuzLAXnh',
 'https://www.diningcode.com/profile.php?rid=SAfGGTpYLa9P',
 'https://www.diningcode.com/profile.php?rid=sZjcIKe0jlZU',
 'https://www.diningcode.com/profile.php?rid=Pjz9cNmTlyxC',
 'https://www.diningcode.com/profile.php?rid=iuSWFNhg9c7J',
 'https://www.diningcode.com/profile.php?rid=IcDyEnt92zcY',
 'https://www.diningcode.com/profile.php?rid=xL6rOmT1L9RD',
 'https://www.diningcode.com/profile.php?rid=TjHHaWq8Ylqt',
 'https://www.diningcode.com/profile.php?rid=hI8HuREl1vU7',
 'https://www.diningcode.com/profile.php?rid=WFvLd1mhIIkO',
 'https://www.diningcode.com/profile.php?rid=60pHzfCyRJRw',
 'https://www.diningcode.com/profile.php?rid=WXCIw2xRplLG',
 'https://www.diningcode.com/profile.php?rid=HnnUtuV6DUeq',
 'https://www.diningcode.com/profile.php?rid=ZRVmgBQx2HMd',
 'https://www.diningcode.com/profile.php?rid=c6h6aCJ83Pwn',
 'https://www.diningcode.com/profile.php?rid=bEblm3kJNbjF',
 'https://www.diningcode.com/profile.php?rid=M9vl3l8ri8r3',
 'https://www.diningcode.com/profile.php?rid=9kG5UXmeDFEW',
 'https://www.diningcode.com/profile.php?rid=Z9B95VkbEgJ4',
 'https://www.diningcode.com/profile.php?rid=xeYf3MMLKZfR',
 'https://www.diningcode.com/profile.php?rid=vM5Ku9pMI80Q',
 'https://www.diningcode.com/profile.php?rid=FPLXJW8GsFWS',
 'https://www.diningcode.com/profile.php?rid=WsBxWFQ0OAnd',
 'https://www.diningcode.com/profile.php?rid=rGcbaqHumjcz',
 'https://www.diningcode.com/profile.php?rid=TIsrMm19rLFS',
 'https://www.diningcode.com/profile.php?rid=TJmzHYPSn5tw',
 'https://www.diningcode.com/profile.php?rid=ADeAL1nyxmUf',
 'https://www.diningcode.com/profile.php?rid=rLjtrMFJxQVm',
 'https://www.diningcode.com/profile.php?rid=UUsonHg7U8zE',
 'https://www.diningcode.com/profile.php?rid=JmLm8KwoaR9O',
 'https://www.diningcode.com/profile.php?rid=WbUm0nI2fGgI',
 'https://www.diningcode.com/profile.php?rid=iy9p4dIoSUk2',
 'https://www.diningcode.com/profile.php?rid=0SliO8h8FeJ2',
 'https://www.diningcode.com/profile.php?rid=qvB74D5s6kNQ',
 'https://www.diningcode.com/profile.php?rid=6XkYCafqP5iL',
 'https://www.diningcode.com/profile.php?rid=FpAduWrqgNxr',
 'https://www.diningcode.com/profile.php?rid=l9tGzjoxBOEH',
 'https://www.diningcode.com/profile.php?rid=JraNJCqaGV7H',
 'https://www.diningcode.com/profile.php?rid=pZSQVPwSlaEh',
 'https://www.diningcode.com/profile.php?rid=xEk0DbQkG8aX',
 'https://www.diningcode.com/profile.php?rid=JryW2FvUrIzf',
 'https://www.diningcode.com/profile.php?rid=ePnCFlG3y9fP',
 'https://www.diningcode.com/profile.php?rid=c2PBWmURFJVw',
 'https://www.diningcode.com/profile.php?rid=3uS8vM9Tj8LR',
 'https://www.diningcode.com/profile.php?rid=lxe78zlj6hNI',
 'https://www.diningcode.com/profile.php?rid=gJnizhISs3wN',
 'https://www.diningcode.com/profile.php?rid=IqGjznzijBZL',
 'https://www.diningcode.com/profile.php?rid=Mvyr90GuJzLF',
 'https://www.diningcode.com/profile.php?rid=sn8cwC6qOaYy',
 'https://www.diningcode.com/profile.php?rid=9CFFhN8mmKJD',
 'https://www.diningcode.com/profile.php?rid=taLseaZGyocE',
 'https://www.diningcode.com/profile.php?rid=9O0MfeRQknpi',
 'https://www.diningcode.com/profile.php?rid=8db9tlEZe9WK',
 'https://www.diningcode.com/profile.php?rid=i44BaFBDQ8CS',
 'https://www.diningcode.com/profile.php?rid=PVWfLhVVM0Vz',
 'https://www.diningcode.com/profile.php?rid=RGeOls104akj',
 'https://www.diningcode.com/profile.php?rid=WdiCq7SBB590',
 'https://www.diningcode.com/profile.php?rid=moDvKQwdsEO8',
 'https://www.diningcode.com/profile.php?rid=zw45Jjq1sTDA',
 'https://www.diningcode.com/profile.php?rid=UY4CjxBdMCVW',
 'https://www.diningcode.com/profile.php?rid=jpLlPo8E11gz',

In [ ]:
def crawling_reviews_DiningCode(name, link, driver):
    reviews = pd.DataFrame(columns=['res_name','user_name','rating','review'])
    try:
        driver.get(link)
    except:
        return None

    while True:
        try:
            click_more = driver.find_element_by_xpath("""//*[@id="div_more_review"]""")
            click_more.click()
        except:
            break

    time.sleep(1)

    try:
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')

        for user in soup.find('div',{'id':'div_review'}).find_all('div',{'id':re.compile('div_review_+')}):
            tmp = user.find('span','btxt').get_text()
            user_name = tmp[:tmp.find('(')].strip()
            user_rating = int(re.findall('\d+',user.find('i',{'style':re.compile('width:+')})['style'])[0])//20
            user_review = user.find('p','review_contents btxt').get_text().replace('\n','')

            reviews = reviews.append({'res_name':name,
                                    'user_name':user_name,
                                    'rating':user_rating,
                                    'review':user_review}, ignore_index=True)
    except:
        return None

    return reviews

In [ ]:
D_restaurants_df
D_review_df

Empty DataFrame
Columns: [res_name, user_name, rating, review]
Index: []

In [ ]:
def crawling_res_data_DiningCode(link, driver):
    try:
        # Chrome 드라이버를 사용하여 링크 불러오기
        driver.get(link)

        # 페이지 로딩을 기다림 (예: 10초 동안 대기)
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, 'tit'))
        )
    except Exception as e:
        print('링크 에러:', link)
        print(e)
        return None, None, None, None, None, None, None, None, None, None

    # 상호명
    try:
        name = driver.find_elements_by_class_name('tit')[3].text
        print(name)
    except:
        name = None

    # 주소
    try:
        address = driver.find_element_by_class_name('locat').text
    except:
        address = None

    # 업종(다이닝코드엔 업종이 없음)
    category = None

    # 주메뉴
    try:
        main_menu = driver.find_element_by_css_selector('div.menu-info.short p.l-txt').text.strip()
    except:
        main_menu = None

    # 가격(주메뉴)
    try:
        price = int(driver.find_element_by_css_selector('div.menu-info.short p.r-txt').text[:-1].replace(',', ''))
    except:
        price = None

    # 영업시간
    try:
        time_dict = dict()
        opening_time_list = driver.find_elements_by_css_selector('div.busi-hours.short p')[1:]
        for i in range(len(opening_time_list))[0::2]:
            if opening_time_list[i].text != '더보기':
                time_dict[opening_time_list[i].text] = opening_time_list[i+1].text

        opening_time = str(time_dict)
    except:
        opening_time = None

    # 평점과 리뷰 수
    try:
        ratings = float(driver.find_element_by_css_selector('strong.rate-point span').text)
        tmp = ratings[0].text.strip()
        rating = float(ratings[1].text[:-1])
        review_count = tmp[:tmp.find('명')]
    except:
        rating = None
        review_count = None

    # 태그
    try:
        tags = ','.join([i.text[:i.text.find('(')] for i in driver.find_elements_by_css_selector('p.icon')])
    except:
        tags = None

    # 리뷰 데이터 가져오기
    res_reviews = crawling_reviews_DiningCode(name, link, driver)

    return name, address, category, main_menu, price, opening_time, rating, review_count, tags, res_reviews

In [ ]:
count = 1
for url in urls:
    try:

        chrome_path = '/usr/lib/chromium-browser/chromedriver.exe'
        driver = webdriver.Chrome(options=chrome_options)

        print(count, '\t|', end='')

        name, address, category, main_menu, price, opening_time, rating, review_count, tags, review_df = crawling_res_data_DiningCode(url, driver)

        D_restaurants_df = D_restaurants_df.append({
            'name': name,
            'address': address,
            'category': category,
            'main_mn': main_menu,
            'price': price,
            'opng_tm': opening_time,
            'rating': rating,
            'rvw_cnt': review_count,
            'tags': tags
        }, ignore_index=True)

        D_review_df = D_review_df.append(review_df, ignore_index=True)

        count += 1
    finally:
        if 'driver' in locals():
            driver.quit()

In [ ]:
D_restaurants_df.to_csv('/content/drive/MyDrive/ML_data/DiningCode_df.csv', index=False)
D_review_df.to_csv('/content/drive/MyDrive/ML_data/DiningCode_review_df.csv', index=False)


LabelEncoder를 사용하여 식당 이름과 사용자 이름을 숫자 값으로 변환

문장부호 제거

번역 후 라벨 추가

In [ ]:
!pip install pypapago

Collecting pypapago
  Downloading pypapago-0.1.1.1-py3-none-any.whl (4.5 kB)
Requirement already satisfied: requests<3 in /usr/local/lib/python3.10/dist-packages (from pypapago) (2.31.0)
Requirement already satisfied: tqdm<5 in /usr/local/lib/python3.10/dist-packages (from pypapago) (4.66.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3->pypapago) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3->pypapago) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3->pypapago) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3->pypapago) (2023.7.22)
Installing collected packages: pypapago
Successfully installed pypapago-0.1.1.1

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm
from pypapago import Translator

In [ ]:
# Load DiningCode data
eat_info = pd.read_csv("/content/drive/MyDrive/ML_data/DiningCode_df.csv")
eat_review = pd.read_csv("/content/drive/MyDrive/ML_data/DiningCode_review_df.csv")

In [ ]:
eat_info.head()

,name,address,category,main_mn,price,opng_tm,rating,rvw_cnt,tags
0,놀부만두,서울특별시 동대문구 휘경2동 276-33,NaN,냉모밀,6000.0,"{'월-금,일': '오전 11시 - 오후 8시 30분 '}",NaN,NaN,"점심식사,혼밥,저녁식사,간식,지역주민이 찾는,서민적인,시끌벅적한,가성비좋은,푸짐한,..."
1,호반,서울특별시 종로구 낙원동 85-7,NaN,순대국,8000.0,{'매일': '오전 11시 30분 - 오후 10시 (준비시간 15:00~16:30)...,NaN,NaN,"저녁식사,점심식사,식사모임,가족외식,술모임,접대,혼술,데이트,혼밥,회식,아침식사,서..."
2,민벅 건대점,서울특별시 광진구 화양동 10-1,NaN,알리오올리오,9900.0,{'매일': '오전 11시 30분 - 오후 10시 (구정 추석 당일 3시 오픈)'},NaN,NaN,"점심식사,저녁식사,데이트,여자끼리,가족외식,모임,기념일,식사모임,아침식사,이국적/이..."
3,뉴델리,서울시 동대문구 회기동 3-182,NaN,치킨 탄두리 (한마리),15000.0,{'매일': '오전 11시 - 오후 10시 '},NaN,NaN,"점심식사,저녁식사,데이트,식사모임,이국적/이색적,깔끔한,캐주얼한"
4,강릉스낵,서울특별시 양천구 목동 406-65,NaN,직송 모듬 회,60000.0,"{'월-금': '오후 5시 - 오전 1시 ', '토/일': '오후 4시 - 오전 1...",NaN,NaN,"술모임,점심식사,저녁식사,간식,데이트,아이동반,가족외식,식사모임,혼밥,서민적인,캐주..."

In [ ]:
eat_review.head()

,res_name,user_name,rating,review
0,놀부만두,Youngmi Lee,5,지역맛집답게 적당히 허름하고 작지만 손님이 꽉차 있었다. 냉모밀 국물은 깊은달달함~...
1,놀부만두,Kunwoo Kim,4,제기동 평양냉면 갔다가 정기휴일 발길돌려휘경동 생방송투데이 맛집 놀부만두로 아버지와...
2,놀부만두,erica,3,비빔모밀 온모밀 김치만두 먹어봄유명세에 비해 그닥...그나마 셋 중에는 김치만두가 ...
3,놀부만두,발챙이,4,김치만두랑 냉모밀 조합이 최고입니다. 만두피가 엄청 쫄깃해요.
4,놀부만두,nelia,5,NaN

In [ ]:
# Drop NaN values
eat_info = eat_info[eat_info['name'].notnull()]
eat_review = eat_review[eat_review['user_name'].notnull()]

# Reset index
eat_info.reset_index(drop=True, inplace=True)
eat_review.reset_index(drop=True, inplace=True)

# Delete overlapped data
# 식당 정보 데이터 세트에서 중복 제거. 중복은 식당 이름 기준
for id in eat_info.index:
    if list(eat_info['name']).count(eat_info.loc[id, 'name']) > 1:
        eat_info.drop(id, inplace=True)

In [ ]:
# Label encoding, Place_name -> p_id, User_name -> u_id
# LabelEncoder를 사용하여 식당 이름과 사용자 이름을 숫자 값으로 변환
# (p_id는 place_id 및 u_id는 user_id로) 인코딩
le = LabelEncoder()
le.fit(eat_info['name'])
eat_info['p_id'] = le.transform(eat_info['name'])
eat_review['p_id'] = le.transform(eat_review['res_name'])

user_le = LabelEncoder()
user_le.fit(eat_review['user_name'])
eat_review['u_id'] = user_le.transform(eat_review['user_name'])

In [ ]:
# Delete punctuation marks
# 리뷰에서 문장 부호 제거
def delete_punctuation_marks_review(review):
    review = review.replace('.', '. ')
    review = review.replace('!', '! ')
    review = review.replace('(', '( ')
    review = review.replace(')', ') ')
    review = review.replace('^', '')
    review = review.replace('*', '')
    review = review.replace('-', ' ')
    review = review.replace('\n', '. ')
    review = review.replace('\"', '. ')
    return review

In [ ]:
eat_info.head()

,name,address,category,main_mn,price,opng_tm,rating,rvw_cnt,tags,p_id
0,놀부만두,서울특별시 동대문구 휘경2동 276-33,NaN,냉모밀,6000.0,"{'월-금,일': '오전 11시 - 오후 8시 30분 '}",NaN,NaN,"점심식사,혼밥,저녁식사,간식,지역주민이 찾는,서민적인,시끌벅적한,가성비좋은,푸짐한,...",304
1,호반,서울특별시 종로구 낙원동 85-7,NaN,순대국,8000.0,{'매일': '오전 11시 30분 - 오후 10시 (준비시간 15:00~16:30)...,NaN,NaN,"저녁식사,점심식사,식사모임,가족외식,술모임,접대,혼술,데이트,혼밥,회식,아침식사,서...",2234
2,민벅 건대점,서울특별시 광진구 화양동 10-1,NaN,알리오올리오,9900.0,{'매일': '오전 11시 30분 - 오후 10시 (구정 추석 당일 3시 오픈)'},NaN,NaN,"점심식사,저녁식사,데이트,여자끼리,가족외식,모임,기념일,식사모임,아침식사,이국적/이...",770
3,뉴델리,서울시 동대문구 회기동 3-182,NaN,치킨 탄두리 (한마리),15000.0,{'매일': '오전 11시 - 오후 10시 '},NaN,NaN,"점심식사,저녁식사,데이트,식사모임,이국적/이색적,깔끔한,캐주얼한",311
4,강릉스낵,서울특별시 양천구 목동 406-65,NaN,직송 모듬 회,60000.0,"{'월-금': '오후 5시 - 오전 1시 ', '토/일': '오후 4시 - 오전 1...",NaN,NaN,"술모임,점심식사,저녁식사,간식,데이트,아이동반,가족외식,식사모임,혼밥,서민적인,캐주...",81

In [ ]:
eat_review.head()

,res_name,user_name,rating,review,p_id,u_id
0,놀부만두,Youngmi Lee,5,지역맛집답게 적당히 허름하고 작지만 손님이 꽉차 있었다. 냉모밀 국물은 깊은달달함~...,304,1616
1,놀부만두,Kunwoo Kim,4,제기동 평양냉면 갔다가 정기휴일 발길돌려휘경동 생방송투데이 맛집 놀부만두로 아버지와...,304,905
2,놀부만두,erica,3,비빔모밀 온모밀 김치만두 먹어봄유명세에 비해 그닥...그나마 셋 중에는 김치만두가 ...,304,1817
3,놀부만두,발챙이,4,김치만두랑 냉모밀 조합이 최고입니다. 만두피가 엄청 쫄깃해요.,304,3911
4,놀부만두,nelia,5,NaN,304,2151

In [ ]:
eat_info['reviews'] = ''

In [ ]:
ts = Translator()
eat_review['review_eng'] = ''

In [ ]:
eat_info.head()

,name,address,category,main_mn,price,opng_tm,rating,rvw_cnt,tags,p_id,reviews
0,놀부만두,서울특별시 동대문구 휘경2동 276-33,NaN,냉모밀,6000.0,"{'월-금,일': '오전 11시 - 오후 8시 30분 '}",NaN,NaN,"점심식사,혼밥,저녁식사,간식,지역주민이 찾는,서민적인,시끌벅적한,가성비좋은,푸짐한,...",304,
1,호반,서울특별시 종로구 낙원동 85-7,NaN,순대국,8000.0,{'매일': '오전 11시 30분 - 오후 10시 (준비시간 15:00~16:30)...,NaN,NaN,"저녁식사,점심식사,식사모임,가족외식,술모임,접대,혼술,데이트,혼밥,회식,아침식사,서...",2234,
2,민벅 건대점,서울특별시 광진구 화양동 10-1,NaN,알리오올리오,9900.0,{'매일': '오전 11시 30분 - 오후 10시 (구정 추석 당일 3시 오픈)'},NaN,NaN,"점심식사,저녁식사,데이트,여자끼리,가족외식,모임,기념일,식사모임,아침식사,이국적/이...",770,
3,뉴델리,서울시 동대문구 회기동 3-182,NaN,치킨 탄두리 (한마리),15000.0,{'매일': '오전 11시 - 오후 10시 '},NaN,NaN,"점심식사,저녁식사,데이트,식사모임,이국적/이색적,깔끔한,캐주얼한",311,
4,강릉스낵,서울특별시 양천구 목동 406-65,NaN,직송 모듬 회,60000.0,"{'월-금': '오후 5시 - 오전 1시 ', '토/일': '오후 4시 - 오전 1...",NaN,NaN,"술모임,점심식사,저녁식사,간식,데이트,아이동반,가족외식,식사모임,혼밥,서민적인,캐주...",81,

In [ ]:
eat_review.head()

,res_name,user_name,rating,review,p_id,u_id,review_eng
0,놀부만두,Youngmi Lee,5,지역맛집답게 적당히 허름하고 작지만 손님이 꽉차 있었다. 냉모밀 국물은 깊은달달함~...,304,1616,
1,놀부만두,Kunwoo Kim,4,제기동 평양냉면 갔다가 정기휴일 발길돌려휘경동 생방송투데이 맛집 놀부만두로 아버지와...,304,905,
2,놀부만두,erica,3,비빔모밀 온모밀 김치만두 먹어봄유명세에 비해 그닥...그나마 셋 중에는 김치만두가 ...,304,1817,
3,놀부만두,발챙이,4,김치만두랑 냉모밀 조합이 최고입니다. 만두피가 엄청 쫄깃해요.,304,3911,
4,놀부만두,nelia,5,NaN,304,2151,

In [ ]:
!pip uninstall googletrans

WARNING: Skipping googletrans as it is not installed.

In [ ]:
!pip install googletrans==4.0.0-rc1

Collecting googletrans==4.0.0-rc1
  Downloading googletrans-4.0.0rc1.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting httpx==0.13.3 (from googletrans==4.0.0-rc1)
  Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2023.7.22)
Collecting hstspreload (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hstspreload-2023.1.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 17.2 MB/s eta 0:00:00
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.0)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 9.7 MB/s eta 0:00:00
Collecting idna==2.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 6.3 MB/s eta 0:00:00
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.3 MB/s eta 0:00:00
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 6.4 MB/s eta 0:00:00
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 7.0 MB/s eta 0:00:00
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17396 sha256=e0e66b0f5175f5a2c9b98276c11519d3a98d2b63642cb5c91d5d8c6b2cbe202a
  Stored in directory: /root/.cache/pip/wheels/c0/59/9f/7372f0cf70160fe61b528532e1a7c8498c4becd6bcffb022de
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, idna, hstspreload, h2, httpcore, httpx, googletrans
  Attempting uninstall: chardet
    Found existing installation: chardet 5.2.0
    Uninstalling chardet-5.2.0:
      Successfully uninstalled chardet-5.2.0
  Attempting uninstall: idna
    Found existing installation: idna 3.4
    Uninstalling idna-3.4:
      Successfully uninstalled idna-3.4
Successfully installed chardet-3.0.4 googletrans-4.0.0rc1 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2023.1.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0

In [ ]:
from tqdm import tqdm
from googletrans import Translator
import pandas as pd

# 리뷰 번역 함수
def translate_review(review):
    try:
        translator = Translator()
        translated_review = translator.translate(review, src='ko', dest='en').text
        return translated_review
    except Exception as e:
        print(f"번역 오류: {e}")
        return ''

# 리뷰 번역 및 결과 출력
for id in tqdm(eat_review.index):
    review = eat_review.loc[id, 'review']

    if pd.isnull(review):
        continue

    # 리뷰가 이미 번역되었는지 확인
    if pd.isnull(eat_review.loc[id, 'review_eng']):
        review_pre = delete_punctuation_marks_review(review)
        review_ts = translate_review(review_pre)

        eat_review.loc[id, 'review_eng'] = review_ts
        print(f"원본: {review}, 번역: {review_ts}")

In [ ]:
# 각 레스토랑에 대한 번역된 리뷰 수집
for id in eat_info['p_id']:
    review_all = ''

    for review in eat_review[eat_review['p_id'] == id]['review_eng']:
        if isinstance(review, str):
            review_all += review + '. '
        elif isinstance(review, float):
            review_all += str(review) + '. '

    eat_info.loc[eat_info['p_id'] == id, 'reviews'] = review_all

In [ ]:
eat_info.head()

,name,address,category,main_mn,price,opng_tm,rating,rvw_cnt,tags,p_id,reviews
0,놀부만두,서울특별시 동대문구 휘경2동 276-33,NaN,냉모밀,6000.0,"{'월-금,일': '오전 11시 - 오후 8시 30분 '}",NaN,NaN,"점심식사,혼밥,저녁식사,간식,지역주민이 찾는,서민적인,시끌벅적한,가성비좋은,푸짐한,...",304,"Like a local restaurant, it was moderately sha..."
1,호반,서울특별시 종로구 낙원동 85-7,NaN,순대국,8000.0,{'매일': '오전 11시 30분 - 오후 10시 (준비시간 15:00~16:30)...,NaN,NaN,"저녁식사,점심식사,식사모임,가족외식,술모임,접대,혼술,데이트,혼밥,회식,아침식사,서...",2234,It is a Korean restaurant located at the edge ...
2,민벅 건대점,서울특별시 광진구 화양동 10-1,NaN,알리오올리오,9900.0,{'매일': '오전 11시 30분 - 오후 10시 (구정 추석 당일 3시 오픈)'},NaN,NaN,"점심식사,저녁식사,데이트,여자끼리,가족외식,모임,기념일,식사모임,아침식사,이국적/이...",770,"If you have 1 menu per person, it will give yo..."
3,뉴델리,서울시 동대문구 회기동 3-182,NaN,치킨 탄두리 (한마리),15000.0,{'매일': '오전 11시 - 오후 10시 '},NaN,NaN,"점심식사,저녁식사,데이트,식사모임,이국적/이색적,깔끔한,캐주얼한",311,You can enjoy delicious Indian curry at an old...
4,강릉스낵,서울특별시 양천구 목동 406-65,NaN,직송 모듬 회,60000.0,"{'월-금': '오후 5시 - 오전 1시 ', '토/일': '오후 4시 - 오전 1...",NaN,NaN,"술모임,점심식사,저녁식사,간식,데이트,아이동반,가족외식,식사모임,혼밥,서민적인,캐주...",81,"Tteokbokki is spicy, so it's delicious.The fri..."

In [ ]:
eat_review.head()

,res_name,user_name,rating,review,p_id,u_id,review_eng
0,놀부만두,Youngmi Lee,5,지역맛집답게 적당히 허름하고 작지만 손님이 꽉차 있었다. 냉모밀 국물은 깊은달달함~...,304,1616,"Like a local restaurant, it was moderately sha..."
1,놀부만두,Kunwoo Kim,4,제기동 평양냉면 갔다가 정기휴일 발길돌려휘경동 생방송투데이 맛집 놀부만두로 아버지와...,304,905,I went to Pyongyang cold noodles and turned on...
2,놀부만두,erica,3,비빔모밀 온모밀 김치만두 먹어봄유명세에 비해 그닥...그나마 셋 중에는 김치만두가 ...,304,1817,Bibim Mumil Onmemin Kimchi Band only eat bumen...
3,놀부만두,발챙이,4,김치만두랑 냉모밀 조합이 최고입니다. 만두피가 엄청 쫄깃해요.,304,3911,Kimchi -man dumplings and cold hair combinatio...
4,놀부만두,nelia,5,NaN,304,2151,NaN

In [ ]:
# Save to CSV
eat_info.to_csv('/content/drive/MyDrive/ML_data/translated_eat_info.csv', index=False)
eat_review.to_csv('/content/drive/MyDrive/ML_data/translated_eat_review.csv', index=False)

prevent unnecessary API calls for already translated reviews

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tqdm.notebook import tqdm

from tqdm import tqdm
from googletrans import Translator

# DiningCode 데이터 로드
eat_info = pd.read_csv("/content/drive/MyDrive/ML_data/translated_eat_info.csv")
eat_review = pd.read_csv("/content/drive/MyDrive/ML_data/translated_eat_review.csv")

# 리뷰 번역 함수
def translate_review(review):
    try:
        translator = Translator()
        translated_review = translator.translate(review, src='ko', dest='en').text
        return translated_review
    except Exception as e:
        print(f"번역 오류: {e}")
        return ''

# 리뷰 번역 및 결과 출력
for id in tqdm(eat_review.index):
    review = eat_review.loc[id, 'review']

    if pd.isnull(review):
        continue

    # 리뷰가 이미 번역되었는지 확인
    if pd.isnull(eat_review.loc[id, 'review_eng']):
        review_pre = delete_punctuation_marks_review(review)
        review_ts = translate_review(review_pre)

        eat_review.loc[id, 'review_eng'] = review_ts
        print(f"원본: {review}, 번역: {review_ts}")

 32%|███▏      | 7091/22421 [00:00<00:01, 15321.49it/s]

번역 오류: the JSON object must be str, bytes or bytearray, not NoneType
원본: ^^, 번역:

 80%|████████  | 17976/22421 [00:00<00:00, 24608.24it/s]

원본: 소문듣고 점심시간 지나 15시 도착 웨이팅 없이 한가하게 식사 칼국수 동네에서 먹던 멸치국물이 아니라 뭔가 진한게 넘어가는 식감 좋았으며 면도 무척 부드러웠음 만두도 속이 꽉차 육즙이 있어 좋았음, 번역: After listening to rumors, the arrival time after lunchtime was 15 o'clock without a weight, but it was not anchovy broth that was eaten in the kalguksu neighborhood, but something rich and the texture was good and the shave was very soft.
원본: 명동하면 빠질 수 없는 맛집 명동교자본점!미쉐린 가이드 2020에 선정된 만큼 외국인들도 굉장히 많이 오는 칼국수집인데요.칼국수 + 비빔국수 + 만두를 주문해봤습니다😄달달한 칼국수랑 매콤한 비빔국수에 사이드 만두까지 조합이 아주 좋아요👍👍 추천추천, 번역: Myeongdong Kyo Country Store that you can't miss if you do not miss Myeongdong!As it was selected for the Michelin Guide 2020, it is a kalguksu restaurant where many foreigners come.I ordered kalguksu + bibim noodles + dumplings 😄 Sweet kalguksu and spicy bibim noodles and side dumplings are very good.
원본: 전체적으로 칼국수와 만두의 고기가 굉장히 기름집니다 고기 육수 기름진 맛 좋아하시면 추천합니다 김치가 마늘 양념이 많아서 국물에 타 먹기 좋습니다 전 콩국수가 정말 맛있었어요 국물이 진하고 정말 고소합니다, 번역: Overall, the meat of kalguksu and dumplings is very oily.
원본: 명동교자 오랜만에 가봤어요. 녹진한 국물과 살짝 퍼진 면발. 여전히 맛있더라고요. 마늘 향이 가득한 김치는 굿굿!, 번역: I've been to Myeong -dong Gyoza for a long time.Green broth and slightly spread noodles.It was still delicious.Kimchi is full of garlic scent!
원본: 30년 넘게 다니지만 변하지 않는 맛, 그리고 마늘 김치가 일품이다. 그런데 중국인이나 일본인들의 명소로 각광받아 식시시간 대에는 줄을 서서 기다림이!, 번역: It has been around for more than 30 years, but it doesn't change, and garlic kimchi is excellent.However, it is the spotlight of Chinese and Japanese attractions, and in line with the time of time, waiting!
원본: 김치로 유명한 식당이에요. 마늘맛이 강하게 나는데 맵지 않아서 칼국수, 만두랑 잘 어울려요. 손님이 많고 명동에 있다보니 외국인 관광객도 많아요. 정신없고 어수선한 분위기지만 맛은 정말 좋아요., 번역: It's a famous restaurant for kimchi.Garlic tastes strong, but it's not spicy, so it's good with kalguksu and dumplings.Since there are many customers and Myeong -dong, there are many foreign tourists.It's a crazy and cluttered atmosphere, but the taste is really good.
원본: 명동교자만두가 그르케 유명하다고해서, 명동가는길에 가봤습니당.칼국수시켰는데 만두랑 만두속(갈은고기)가 얹어서 나와요!만두탕같음~가격은 8,000원으로 그냥그런 가격?그래도 밥달라고하면 밥도 주시고,사리추가도 가능해서 좋았어요!그리고 회전력도 엄청 빨라서 시키면 빨리나와요.사람도 빠지고 채워지는속도가 빨랐습니당.맛은 음....익숙한 짭쪼름한맛이였어요!먹었을때, 어 이건 중식이네? 이런생각할정도로많이 익숙한 국물맛확실히 다른 칼국수집에 비해서 국물맛이 깊긴했어요.그래도 막 30분 기다려 먹을 맛은아니였습니당..!와이거 신선해!! 라는 맛보단 뭔가 우리가 예상할수있는맛이기때문에, 저는 먹다가 끝에가서 좀 질렸어욬ㅋㅋㅋㅋㅋ김치는 시원하기보단 짠편!솔직히 다먹고 식당에서 제공되는 자일리톨이 신의한수입니다!약간 짠맛이 입안에서 돌아 좀 텁텁해지는데,그느낌을 식당에서도 알았는지 자일리톨먹으면 해결됨 ㅋㅋㅋㅋㅋㅋㅋㅋ메뉴는 저것밖에없오요!메뉴판 혹시 참고하시라고 같이올려드립니당~, 번역: Myeong -dong Gyoza Dumplings are famous for Greke, so I went to Myeong -dong.I put it on the kalguksu, but the dumplings and dumplings are put on it!It looks like Dandu -tang ~ The price is 8,000 won.And the rotational power is so fast that it will come out quickly.The speed of people missing and filling was fast.The taste is um....It was a familiar taste!When you eat, this is Chinese food?The soup tasted more than the other kalguksu restaurant.Still, it wasn't just 30 minutes to eat..!Wigger is fresh!!It's a taste we expect than it tastes, so I'm tired of eating and going at the end.Honestly, Xylitol is a god of God!A little salty taste turns around in the mouth, but it's solved by eating xylitol if you know it in the restaurant.I'll post it together to refer to the menu ~
원본: 오래되고 가끔은 생각나는 진정한 노포집. 이젠 입맛이 변해 약간 짜거나 너무 강한 마늘 김치가 부담스럽지만 그래도 가끔 갈수밖에 없는 그런곳 같습니다., 번역: A true old collection of old and sometimes reminds of.Now that the taste changes, it is a bit salty or too strong garlic kimchi, but it seems like a place where you can only go.
원본: 명동하면 생각나는곳~마늘향이 강한 김치에 칼국수 한입~, 번역: If you think of Myeongdong ~ A kalguksu with a strong garlic scent.
원본: ◈ 맛집기록 #22 '명동교자 본점'(4.0점 / 5점 만점)- 미슐랭에서도 자주 언급되는, 전통깊은 식당이다. 아마 대부분 사람들이 알고 있는 곳!- 여름에 방문했을 때는, 칼국수(9000원, 무료 사리 리필가능)와 콩국수(9000원)를 먹었다.- 사람들이 정말 많지만, 음식 나오는 속도랑 회전이 빨라서 좀 낫다. 혼밥하기에 매우 좋은 구조.- 칼국수 맛은 말할 필요도 없이 최고. 불향이 나고 진한 고기맛이 나는게 특징이다. 마늘김치랑 먹으면 행복한 맛이다. 콩국수도 별 기대 없이 먹었는데 너무 맛있었다. - 다 좋았는데 수저가 설거지가 덜 되어있었는지 젓가락 처음 꺼냈을 때 양념이 막 묻어있었다. 그거 때문에 찝찝해서 별 하나 감점.., 번역: ◈ Restaurant record #22 'Myeong -dong Gyoja Headquarters' (4. 0 /5 points) It is a traditional restaurant that is often mentioned in Michelin.Perhaps most people know!When I visited in the summer, I ate kalguksu (9000 won, free saree refills) and bean noodles (9000 won).There are so many people, but it's a little better because the speed of food and rotation are fast.Very good structure to do it.The taste of kalguksu is the best.It is characterized by the taste and rich meat.It is a happy taste to eat with garlic kimchi.Bean noodles were also eaten without expectations.It was all good, but when I first took out the chopsticks, the seasoning was just buried.Because of that, one star is deducted..
원본: 워낙 유명해서 대기줄도 있던 곳인데 요새는 바로 입장이 가능하지만 역시 명동 대표 맛집인건 그럼에도 사람이 많았음. 근데 그거치곤 그냥 국수가 그닥 내 스타일은 아니었음 뭔가 시원하다기보단 좀 느끼하단 느낌을 줬고 김치는 지나치게 자극적이어서 왜 매울까했는데 김치.. 어쨌든 추가로 사리나 밥을 줘서 양은 듬뿍 먹을 수 있으나 막 생각나고 그립진않을 맛임. 맛이 없다기보단 기대보단 엄청나지 않았을뿐, 번역: It was so famous that there was a waiting string, but the fortifications can be entered right away, but there are also many people.But that's just the noodles, the noodles were not my style..Anyway, you can eat plenty of sheep by giving you sari or rice, but you can't remember it.It wasn't much more than expected than it had no taste
원본: 칼국수에 밥까지 말아 싹싹 긁어 먹은 빈그릇을 인증샷으로 남긴다. 다이닝코드 100점 맛집답다! 마늘향가득한 김치는 중독이다!, 번역: Kalguksu rolls rice and leaves an empty bowl that was scraped.It's a dining code 100 -point restaurant!Kimchi is addicted to garlic!
원본: 아 너무 시끄럽고 좁아요. 에어컨은 어찌나 빵빵한지 먹다가 추워서 나왔네요;; 그리고 맛은 기대이하였어요 왜 미슐랭 3년연속 받은거지 싶은 그런 느낌.. 굳이 또 가진 않을듯  웨이팅하느니.., 번역: Oh, it's so noisy and narrow.The air conditioner came out because it was so cold that it was so cold;And the taste was expected..Do you wake up as if you don't have it again?.
원본: 옛날부터 자주 가시던 아빠가 우리나라 김치 중 제일 맛있는 김치가 있는 곳이라고 칭찬하는 곳입니다 마늘 맛이 많이나서 호불호가 갈릴순 있지만 저는 좋았고 교자도 육즙이 많아 맛있었습니다, 번역: My dad, who has been there since ancient times since the old days, complimented it as the most delicious kimchi among Korean kimchi.
원본: 맛은 처음 먹어본 칼국수의 맛임 칼국수를 첫 맛은 고기 들어간 불짜장 그래서 단거 좋아하고 기름진거 좋아하는 사람은 추천담백한맛 좋아하시면 비추천, 번역: The taste of the first taste of kalguksu is the first taste of the meat.
원본: 워낙 유명한 집이라...전 뭣보다 김치가 존맛이라고 생각합니다. 싸진 않지만 맛좋아서 용서..서버 분들이 정말 프로페셔널 해요, 번역: It's so famous...I think kimchi is more than.It's not cheap but tastes good for forgiveness..Servers are really professional
원본: 하도 유명하길래 가봤는데 맛있습니다.직원분들 친절하신 것 같고 김치 부족해보이면 알아서 주시더라구요.매장 넓고 회전율도 좋아서 웨이팅 길지 않아요.다만 가성비가 좋은지는 모르겠어요.둘이 가서 3개 시키니 국수집에서 3만원이..만두 빼고 식사 두개만 시켜도 될것 같아요. 부족하면 밥 말아 먹을 수 있습니다., 번역: I've been famous for it, but it's delicious.The staff seemed to be kind and if Kimchi was not enough, he gave it to me.The store is wide and the turnover is not long.I don't know if the cost is good.Two people go three and 30,000 won at the noodles..I think you can have two meals except dumplings.If you are not enough, you can eat rice.
원본: 언제와도 한결 같은 맛. 중독성 강한 마늘 김치. 부드러운 칼국수. 연휴에 사람대박 많음., 번역: It tastes like anytime.Addictive garlic kimchi.Soft kalguksu.There are a lot of people during the holidays.
원본: #맛 두말할거없이 맛있음종종 생각나는맛만두는 평범한 고기만두칼국수의 면보단 국물이 기억남비빔도 양념장이 찐득하고 맛있음 #서비스 및 분위기 명동이고 사람많고 시끄러움#장점 맛 맛 맛#단점 예전에 비해 점점 위생상태가 좋지않은거같음#한줄평맛있어서 종종감명동가는이유, 번역: #The tastes, it's delicious, but the soup of the noodles of the noodles of the ordinary meat dumpling noodles is often reminiscent of the soup.It seems that the hygiene is not good.
원본: 유명한 곳이지만 항상 사람이 많아 한번도 가보지 않다가 처음 방문해봤는데 맛은 생각보다 괜찮았다. 칼국수 국물은 약간 맑은 짬뽕?맛이 나기도 했고 만두도 정말 맛있었다. 칼국수는 여자 셋이서 칼국수 2그릇 시켜도 될 정도로 많았고 세그릇 시켜서 거의 남겼다.아무래도 명동이라 가격이 비싸지만 맛이 생각나서 다음에 한번 더 방문할듯하고추운날 따뜻한 국물 생각날때 와도 좋을듯하다, 번역: It's a famous place, but I've always been there a lot of people, so I visited it for the first time, but the taste was better than I thought.Kalguksu broth was a bit clear champon and tasted and the dumplings were really delicious.Kalguksu was so many that the three women could have two bowls of kalguksu, and they were almost left with a segment.It's expensive because it's Myeong -dong, but it's like a taste, so I'll visit you once more and come when you think of a warm broth on a cold day.
원본: 우리나라에서 아마도 가장 유명한 칼국수집.이곳만의 독특한 마늘김치와 육수 맛이 한결같은 맛을 유지하는 덕에 응대가 그리 친절하지는 않아도 수많은 내국민과 관광객들의 발걸음이 끊이지 않는다.강한 한방이 있는 맛. 여전히 맛있습니다., 번역: Perhaps the most famous kalguksu collection in Korea.The unique garlic kimchi and the taste of the broth remain consistently, so the response is not so kind, but the steps of many people and tourists are not over.Taste with a strong one.Still delicious.
원본: 말이 필요없는 유명한 곳. 야들야들한 면발과 강렬한 김치맛이 이상하게 종종 생각나는 곳. 사업으로서도 참 대단해보인다., 번역: A famous place that does not need words.The noodles and the intense kimchi flavors often remind you.It seems great as a business.
원본: 저렴하고 맛도 좋아요ㅎㅎ 칼국수에 고기가 들어가있어서 고소하고 만두도 엄청 부드럽고 맛있어요!, 번역: It's cheap and good.
원본: 칼국수 면이 생각보다 얇고 국물 맛이 굉장히 독특합니다. 일반적으로 칼국수하면,해물 베이스로 칼칼하거나 깔끔한 맛을 연상하는데 고기 베이스로 기름맛이 살짝 느껴집니다.만두는 다른 만두 전문점에서 흔히 접할 수 있는 맛입니다., 번역: The kalguksu noodles are thinner than I thought and the soup tastes very unique.In general, kalguksu is reminiscent of a seafood base or a clean taste.Dumplings are common in other dumplings.
원본: 명동 최고의 맛집.1인 1김치접시, 빠른 서빙, 정돈된 분위기, 친절한 직원들.담백한 육수는 언제나 일품이다.모든게 쉽게 변하는 세상에서 한결같은 맛과 분위기를 제공하는 사장님이 존경스럽다., 번역: Myeong -dong's best restaurant.One person 1 kimchi, fast serving, tidy atmosphere, friendly employees.The light broth is always excellent.In a world where everything changes easily, the boss who provides a consistent taste and atmosphere is respectful.
원본: 워낙 이름난 곳이라 개인취향에 따라 판단하면 될 것 같아요.깊은 맛이 나는 칼국수가 좋네요., 번역: It's a famous place, so I think you can judge according to your personal taste.I like kalguksu with a deep taste.
원본: 칼국수, 교자 다 맛있지만, 특히 교자가 정말 맛있어요. 칼국수는 별점 4점, 교자는 5점, 번역: Kalguksu, Gyoza are all delicious, but especially the gyoza is really delicious.Kalguksu is 4 stars and 5 points for Gyoza
원본: 진한 닭고기 육수, 칼국수와 교자 그리고 칼칼한 김치 등 명동을 찾게 되면 늘 생각나는 곳이다. 담백한 국물도 그렇지만 면발에 국수가 잘 베어들어가 아삭한 김치랑 함께하면 그게 참~잘 어울린다는 생각이 든다. 겨울 되면 또 한번 상경해서 방문해야겠다., 번역: It is always a place to come to mind when you find Myeong -dong such as rich chicken broth, kalguksu, gyoza, and kimchi.Even though the soup is also a good soup, the noodles are well cut and the noodles are crispy.In winter, I have to go to visit again.
원본: 명동에서 제일 그나마 먹을만한집칼국수 1 만두 1 시켜 둘이먹으면 적당김치 너무 생강 마늘맛 강해서 자극적인데땡기는맛에 계속먹어요, 번역: It's the best thing to eat in Myeong -dong.
원본: 맛있어요! 다만 기본적으로 이정도 칼국수 하는 집은 여기저기 엄청 많은 것 같아요. 비빔은 다른 곳이 더 맛있는 것 같고요. 명동의 비싼 임대료 때문인지 가격이 칼국수치곤 비쌉니다. 가볍게 먹기엔 좋아요!, 번역: it is delicious!However, basically, there are a lot of houses that are all over this place.Bibim seems to be more delicious.The price is expensive because of the expensive rents in Myeong -dong.It's good to eat lightly!
원본: 가게는 크지만 그만큼 손님도 엄청 많아서대기는 필수국수류는 무료로 사리 추가가 가능함칼국수는 육수가 진하고 육향이 많이 나는편원래 면이 좀 불어서 나온다는데개인적으로 불호였음비빔국수는 안맵고 정말 맛있었다김치는 서울김치 스타일이 아니고 꽤 맵다칼국수랑 궁합은 잘 맞는데 좀 많이 매운듯개인적으로 만두가 제일 맛있었음작은 크기에 육즙이 꽊무조건 시키세요, 번역: The shop is large, but there are so many guests, so the essential noodles can be added free of charge.Is not Seoul Kimchi style, but it's pretty good with the spicy noodles, but it's a bit spicy.
원본: 웨이팅 라인이 길어서 걱정했는데 순환이 빨라서 빨리들어갔습니다. 날이 추워서 칼국수땡겨서 간건데 🤗가서 먹어본 후기로는 김치는 정말정말 짜고칼국수도 많이 짜더라구용(물한컵넣고 먹었습니닷)후식으로 주시는 자일리톨이 제일 좋았..ㅎㅎ재방문은 안할거같습니담, 번역: I was worried about the long waiting line, but the circulation was fast and I went quickly.It was cold, so I went to kalguksu..I don't think I'm going to do the door
원본: 유명하다 그리고 유명할만 함칼국수는 고기맛이 진한 육수가 면에도 잘 베어들어있고 만두 역시 속이 꽉 찼다마늘향 강한 김치도 독특하고칼국수랑 만두를 같이 먹다보면 고기육수 특유의 기름기가 느껴져서 막판가면 약간 물리는 감이 없지는 않지만맛이 잊혀질때쯤 되면 또 먹고 싶어짐, 번역: Famous and famous, Hamkalguksu has a strong broth with a lot of meat, and dumplings are also full.I don't have a sense of bite, but I want to eat again when the taste is forgotten.
원본: 맛있는 #명동교자 #명동칼국수 진짜 먹을때 마다 정말 맛있어😍 엄마가 처녀때 명동 무역회사 다닐때부터 즐겨먹던 #칼국수 를 나도 열심히 먹지~ 맛이 변함없지만 가격은 정말 무섭게 오른다😝 #마늘김치 너무 매워서...ㅜ 먹고 나면 속이 아리지만... 중독적이야😚, 번역: Delicious #Myeongdong Gyoza #Myeongdong Kalguksu is really delicious!..I get inside after eating...It's addictive 😚
원본: 국수가 먹고싶어 방문했습니다.비빔국수 양념장이 매콤하니 맛있었습니다., 번역: I visited because the noodles wanted to eat.Bibim noodle sauce was so spicy that it was delicious.
원본: 시원하고 담백합니다만두 최고입니다계속 생각나는 맛입니다, 번역: It's cool and light, but it's the best.
원본: 예전보다 김치 맛이 많이 싱거워졌다. 좀 짭짤해서 정말 맛있었는데 아쉽다.칼국수는 예나 지금이나 맛있음., 번역: The taste of kimchi has become more fresh than before.It was a little salty and it was really delicious.Kalguksu is delicious now.
원본: 사람이 되게 많은만큼 자리도 많아요. 메뉴는 간단하게 보통 칼국수 많이 먹구 주문하면 빨리 나와요. 사람이 하도 많아서인지 아예 김치 리필만 돌아다니면서 해주시는 분이 계시더라구요. 앞치마는 없어요. 칼국수는 맛있는데 살짝 짜요. 근데 이거 좋아하는 사람들은 맛이 딱 좋을 거 같아요., 번역: There are as many seats as many people.The menu is simply eaten a lot of kalguksu and it comes out quickly.There are a lot of people, so there is a person who only walks around Kimchi refills.There is no apron.Kalguksu is delicious but salty.But people who like this will taste perfect.
원본: 최근 방문시 국물 컬러가 좀더 짙어졌고 맛이 조금 아주 조오금 변했다고 느꼈습니다그 전 방문시엔 너무 맛있었던 기억으로 오랜만에 방문이었는데 그때 그맛이 아닌 것은... 그날그날의 컨디션 탓일수도요., 번역: Recently, the broth color was getting darker and the taste changed a little...It may be due to the condition of the day.
원본: 칼국수 맛있습니다... 사리랑 공기밥이 추가됩니다..파워풀한 양념에 버무린 김치 때문인지 먹고나면 속이 좀 아려요..^^분기에 한번 정도 생각나는 듯.., 번역: Kalguksu is delicious...Sari and rice are added..It's because of the kimchi mixed with powerful sauce..I think about it once in a quarter..

 88%|████████▊ | 19641/22421 [00:21<00:07, 364.27it/s]

원본: 1. 맛 : 칼국수는 진한 닭 육수 국물과 약간 퍼진 듯한 면이 어우러져 맛있어요. 만두, 야채, 고기도 적당히 들어가있고, 면이나 공기밥 추가도 무료로 가능해서 양도 만족해요 (근데 먹고 나면 은근 배불러서 사리 추가는 한 번도 해본적 없네요ㅜㅜ)김치는 마늘 향이 강하고 자극적이에요. 다 먹고 자일리톨을 꼭 먹어줘야 입 안이 텁텁하지 않아요. 2. 분위기 : 명동에서 혼밥하기 좋은 곳이에요. 혼자 앉는 자리가 따로 있어서 점심시간에 가도 전혀 눈치보이지 않아요., 번역: 1. Taste: Kalguksu is delicious with rich chicken broth and slightly spreading noodles.Dumplings, vegetables, and meat are also moderately included, and the noodles and rice are also available for free.You have to eat everything and eat xylitol.2. Mood: It's a good place to go to Myeong -dong.There is a separate seating seat alone, so I don't see it at all.
원본: 일단 만두는 만두피도 정말 얇고 속이 꽉차서 너무 맛있었어요. 칼국수 국물 또한 맛이 깊어서 맛있었는데 면이 불었었어요. 칼국수는 ⭐️⭐️⭐️.5/5 만두는 ⭐️⭐️⭐️⭐️⭐️/5. 혼밥전용 테이블도 마련되어있고 음식은 시키자마자 거의 바로 나와요., 번역: Once the dumplings were so thin and filled with dumplings, it was so delicious.Kalguksu broth was also delicious and delicious, but it was blew.Kalguksu is ⭐️⭐️⭐️.5/5 Tall is ⭐️⭐️⭐️⭐️⭐️/5.There is also a table for Honbab, and as soon as the food is made, it comes out almost immediately.
원본: 몇년만에 방문. 기억했던 것과 달리 맛잇어서 놀람. 김치 마늘은 그대로다. 기분좋게 먹고나옴, 번역: Visit in a few years.Unlike what I remembered, it was surprised.Kimchi garlic remains the same.Eat comfortably
원본: 첨에 먹었을때 그냥그래도 계속 생각나는 마늘김치. 먹고 나오면 마늘냄새 가득한데 그래도 맛있어. 중독성에 열번도 더간듯해서 5점., 번역: Garlic kimchi still reminds me of when I ate it.When you eat it, it's full of garlic smell, but it's delicious.It seems to be 10 times more addictive.
원본: 명성대로 사람이 엄청 많았으나, 11시쯤 방문하여 웨이팅은 없었다. 칼국수와 만두가 왜 유명한지 알 것 같았다. 비빔국수는 쏘쏘, 번역: There were a lot of people as reputation, but there were no waiting around 11 o'clock.Kalguksu and dumplings seemed to know why.Bibim Noodles
원본: 최애 음식 중 하나인 명동교자 칼국수...김치가 자극적이지만 늘 언제나 계속 땡기고... 국물은 고기 육수 양념때문에 먹어도먹어도 입을 행궈도 또 먹게되고, 면발은 퍼지지 않았지만 너무 부드럽고, 먹고나면 주는 아주 작은 공기에 조밥을 한숫가락 말아 먹고나면 서울 사는게 너무 행복한 느낌이죠~^^, 번역: One of the best foods, Kalguksu, Myeong -dong...Kimchi is irritating, but it always keeps it always...The broth is eaten because of the meat broth seasoning, but even if you eat it, you will eat it again, but the noodles are not spread, but it is too soft, and after eating a very small air in the very small air, it is so happy to live in Seoul.
원본: 여유있는 데이트 코스로 적합하진 않은 것 같아요 그정도로 사람이 많고 시끌시끌하면서 좁은 공간에 많은 인원을 수용하려다 보니 테이블 간격이 너무 좁아요만두랑 칼국수를 시켰는데 만두 속에 고기 많고 칼국수 국물도 진하고 평소 익은 김치보다 겉절이를 좋아해서 김치도 맛있었어요 근데 전체적으로 간이 좀 세요 칼국수 국물이 좀 짜고 김치도 좀 매운 편입니다 맵고 짠 음식을 좋아하지 않는 분에겐 크게 추천하고 싶지 않아요, 번역: I don't think it's suitable as a relaxed date course. I tried to accommodate a lot of people in a narrow space, so there are so many people, noisy and noisy space, so I made a lot of dumplings.I like kimchi because I like it.
원본: 비빔국수 꼭 드세요 !!!!! 칼국수는 고기 국물 베이스라 맛 없을 수가 없고, 비빔국수는 식초 뿌려서 먹는데 그렇게 맛있을 수가 없음 사람이 엄청 많은데도 회전율이 빠른 편이니 부담 없이 방문하기에도 좋음 명동이라 외국인이 많을줄 알았는데 거의 다 한국인이어서 놀람 역시 현지인 맛집, 번역: Be sure to eat bibim noodles!!!!!Kalguksu is a meat soup base, so it can't be tasted, and bibim noodles are eaten with vinegar, but they can't be so delicious.Local restaurant
원본: 1.맛- 워낙 유명한 명동칼국수. 면은 꼬들꼬들하고 만두는 육즙이 많이 나왔어요. 김치가 역시 최고!2.분위기- 뭔가 엄청 빠르게 지나가는 느낌이라 자리를 빨리 비켜줘야 되는 듯한 분위기가 있어서 그건좀 ㅠ3.서비스- 기본적으로 친절하십니다., 번역: 1. Myeongdong Kalguksu is so famous.The noodles are twisted and the dumplings are juicy.Kimchi is the best!2. The atmosphere feels so fast, so there is a mood that seems to have to get out of the seat quickly.Service is basically kind.

 88%|████████▊ | 19650/22421 [00:28<00:11, 245.60it/s]

원본: 전분이 들어간 듯한 꾸덕한 칼국수. 만두는 맛있었다 .... 그리고 김치는 맛이 너무 강해서 한 입먹으면 김치맛 밖에 안남... 근데 전체적으로 가격이 너무 비싸다. 재방문 의사 없음., 번역: Kalguksu, which seems to have starch.Dumplings were delicious....And kimchi tastes so strong that if you eat only kimchi...But the price is too expensive overall.No re -examination.
원본: 사람이 많다..  대기해야하고 앉아서도 상당히 북적거림.하지만 그 와중에 직원분들은 잘 해주심. 오이 빼달라는 등의 요구사항도 잊지 않으신다. 가격이 조금 있기는 하지만 만두는 정말 맛있다. 기다릴만 하다는 생각이 들었음. 칼국수에도 만두가 들어있고, 고기가 많다. 무조건 선불, 번역: There are many people..I have to wait and sit quite crowded.But in the meantime, the staff are good.Do not forget the requirements to take out cucumbers.Although the price is a bit, the dumplings are really delicious.I thought it was worth waiting.Kalguksu also contains dumplings and many meat.Prepaid unconditionally
원본: 대박사건 진짜 어디가서 먹기힘든맛 맛있는맛 이맛이라면 명동을 갈 만 합니다 집에서는 이맛 못내죠 사람은 많지만 가격도 저렴하고 맛있고 냠냠 다음엔 만두도 먹어보고싶네요, 번역: If it's really good to eat anywhere, it's hard to go to Myeong -dong. I can't taste it at home.
원본: 만두 맛있어요~ 칼국수는 고기야채 불맛내서 넣어주네요 맛있었어요., 번역: Dumplings are delicious ~ Kalguksu is delicious.
원본: 맛은먹을만합니다칼국수국물도 만두도 비빔도 양념도 국물도 맛있어서 손이갑니다외국인온손님 많고 바빠서 어수선하고직원들 불친절합니다저는 다신안갈듯하네요, 번역: The taste is worth eating.
원본: 웨이팅이 많을까바 걱정이 많았는데 딱 웨이팅없던 시간에 가서 잘먹고왔습니다!김치가 쫌 맵긴했지만 칼국수랑 만두짱!!나올때는 웨이팅하시더라구요...ㄷㄷㄷ, 번역: I was worried about the a lot of waiting, but I went to eat well at the time without weight!Kimchi was very spicy, but Kalguksu and dumplings are awesome!!When I came out, he waited...ㄷㄷㄷ
원본: 사람이 진짜 많아서 줄서서 먹었는데 회전율이 좋아서 오래기다리지는 않았어요 근데 가격이 비싼편인데 만두는 진짜 맛있어요 만두는 인정.., 번역: I had a lot of people in line, but I didn't wait for a long time because the turnover rate was good. But the price is expensive..
원본: 면은 불고 국물은 짜다 좁은 통로까지 사람 앉혀서 다닥다닥 붙어있음 4인석에 모르는 사람까지 합석시킴명동은 역시 정신없이 밥먹는곳, 번역: The noodles are blowing and the broth is salty.
원본: 칼국수 설명에 닭육수래서 기대했는데 고기? 맛에 묻혀서 별 맛이 안나더라고요 ㅠ, 번역: I was looking forward to chicken meat in the Kalguksu description.It didn't taste much because it was buried in the taste.
원본: 찾기가 어려워요 포에버 21근처에 있어요. 이 번이 두번째 찾은 건데 맛있습니다 가끔 생각나서 먹고싶어요 만두가 중국만두식로 즙이 많았구요 면이나 국물은 계속 리필됩니다 김치는 마늘 맛이 많이 나지만 그것도 이 집의 매력입니다., 번역: It's hard to find it near Forever 21.This time is the second time I found it, but it's delicious. I think it's sometimes thought that I want to eat it. Dumplings have a lot of juice.
원본: 명동교자 말해 뭐해요ㅠㅠㅠ시끌벅적하지만 음식 맛은 변하지 않아 좋아요!비빔면과 만두의 조합도 꿀입니다, 번역: What are you doing?The combination of bibimbyeon and dumplings is also honey
원본: 어릴적 먹던 그 맛.. 겉절이의 강한 마늘향은 여전함.. ^^;, 번역: That taste when I was young..The strong garlic flavor of the man is still still..;
원본: 언제나 먹어도 너무 맛있어요. 대학생때부터 십년넘게 쭉 가는 집이에요. 혼밥하기도 너무 좋습니다., 번역: It's so delicious to eat at all times.It's a house that has been going on for more than a decade since I was a college student.It is also good to have a good rice.
원본: 서울시내 최고점을 받은 식당. 어플의 신뢰도를 한층 높이는 계기가 되었음. 김치를 포함해 맛의 특별함이 있음., 번역: A restaurant with the highest score in Seoul.It was an opportunity to increase the reliability of the app.There is a special taste of taste, including kimchi.
원본: 국물맛이 깊고 맛있음. 만두는 피가 정말 얇고 육즙이 가득함. 줄이 길지만 회전이 빠른 편이라 생각보다 일찍 들어갈 수 있었음., 번역: The soup tastes deep and delicious.Dumplings are really thin and juicy.The line was long, but the rotation was faster, so I could go in earlier than I thought.
원본: 만두,   칼국수 비빔국수 존맛 마늘맛 김치가 포인트!, 번역: Dumplings, kalguksu bibim noodles zone taste garlic taste kimchi point!
원본: 부드러운 칼국수면발과 중독성강한 김치가 일품 밥과 면이 리필되어 좋다, 번역: Soft kalguksu surface and addictive kimchi are good because they are refilled.
원본: 칼국수와 만두 모두 깔끔한 맛입니다. 사람이 많으나 회전율이 빨라 오래 기다릴 필요 없고 음식도 금방 나와서 좋습니다., 번역: Both kalguksu and dumplings are clean.There are a lot of people, but the turnover is fast, so you don't have to wait for a long time.
원본: 가격도 저렴하고 인당 메뉴를 시키면 면사리 무한리필이여서 가성비 이득주문하면 10분내로 모든 음식이 나옴ㅋㅋㅋㅋㅋ, 번역: The price is cheap and if you have a menu per person, it is an infinite refill of cotton.
원본: 칼국수 사리 육수 밥 리필 다 되는 거 아시죠? 진짜 눈물나게 맛있으니까 사리 추가 밥추가 해서 두 번 드세여ㅠ, 번역: Kalguksu Sari Sari Broth Rice Filter?It's really tearful, so it's so good to add sari.
원본: 20년 전엔 느끼해서 다시는 안 온다고 했는데. 다시 먹어보니 맛있네요. 내 입맛이 변한건지 국수 맛이 변한건지, 번역: 20 years ago, I felt that I never came again.It's delicious to eat again.Whether my taste has changed or the noodles have changed
원본: 콩국수 육수가 걸쭉하니 괜찮음. 면도 잘 어울리고, 만두도 육즙이 찐함. 단 가격 대비는 호불호가 있을 듯., 번역: Bean noodles are so thick that it is okay.The shave goes well, and the dumplings are also juicy.However, the price is likely to be unfavorable.
원본: 점심식사로 먹기 좋고 냉난방이 잘되서 여름이지만 땀 안흘리고 먹음고기국물맛이 진함재방문의사있음, 번역: It is easy to eat for lunch and heating and heating, but it is summer, but it does not sweat and eat meat soup.
원본: 많은 후기와 리뷰 맛있는 만두국 과 만두 본점의 힘을보요주는군요, 번역: Many reviews and reviews give you the power of delicious dumpling soup and dumpling headquarters.
원본: 맛있는데 대기있고 사람 많아서 정신이 없음하지만 명돔 갈 때마다 여기감면이나 밥 달라고하면 주심, 번역: It's delicious, but there's a lot of people, but I'm insane, but every time I go to Myeongdom, I ask you to reduce it here.
원본: 너무맛있어요12345678901234567890123456, 번역: It's so delicious 12345678901234567890123456
원본: 외국인들이 많이 오는거 같았어요 사람이 많아요 주문한 음식 다 맛있었어요, 번역: It seemed that there were a lot of foreigners. There are a lot of people.
원본: 가성비가 최고립니다. 들이 가면 칼국수 하나 만두 하나가 적당합니다., 번역: The price is the best.If you go, one dumplings are suitable.
원본: 음식이 빨리나와서 회전율이 빠르고 칼국수 특유의 마늘향이 시간 지나면 또 생각나는 맛ㅜ, 번역: The food comes out quickly, and the rotation rate is fast and the unique garlic scent of kalguksu reminds me of it again.
원본: 항상 맛있다. 친절한 직원분들 덕에 기분까지 좋은곳. 영원해라, 번역: Always delicious.Thanks to the friendly staff, it is a good place to feel.Forever
원본: 음식이 빨리 나옴 특유의 마늘향이 강한 김치가 맛있음공기밥 무료로 먹을 수 있음, 번역: Kimchi, which has a strong garlic scent that comes out quickly, can be eaten free of charge.
원본: 마늘김치랑 먹으면 대존맛이고 명동갈 일 없어도 있게 만드는 맛, 번역: If you eat it with garlic kimchi, it tastes great and makes Myeong -dong
원본: 딱히 맛이 없어 보이는데 먹어 보니 한 끼든든하게 챙겨 먹은 것 같네요,맛있어요!, 번역: It doesn't taste good, but when I eat it, it looks like I have eaten one meal, it's delicious!
원본: 맛을 떠나 두번다시는 가고 싶지 않은 음식점. 대기 손님이 많은 것은 이해를 하지만 먹고 있는 중에 자꾸 와서 다 먹었는지 물어보는 것은 아니지 않나 싶다. 손님이 돈내고 눈치 보고 음식 먹어야 하니..., 번역: I don't want to go back to the taste.I understand that there are a lot of waiting guests, but I don't think I keep coming and eating.Do you have to eat and eat?..
원본: 항상 갈때마다 줄을 서야 먹을 수 있는 명동교자 칼국수집. 점심이나 저녁때를 피해서 가면 줄서는건 없을수 있다. 약간 불탄맛의 칼국수집. 매번 갈때마다 항상 맛있게 먹고 온다. 요즘은 관광객들도 많아서 대기하는 사람이 너무 많다., 번역: Myeongdong Gyoja Kalguksu House is always in line whenever you go.If you go to lunch or evening, you may not be in line.Slightly burned flavor kalguksu.Every time I go, I always eat deliciously.These days, there are so many tourists, so there are too many people waiting.
원본: 만두는 맛이 좋았습니다. 칼국수는 오래 끓였는지 조금 흐물거렸습니다. 가격이 싸다고는 할 수 없을 것 같네요. 종업원 분들이 지치신건지 화가나신 건지 모르겠지만 서비스는 친절했습니다., 번역: The dumplings tasted good.Kalguksu was a little sluggish if it boiled for a long time.I can't say that the price is cheap.I don't know if the employees are tired or angry, but the service was kind.
원본: 칼국수로 유명한 정말 괜찮은 맛집입니다. 같이 주시는 김치가 매력적이에요, 번역: It is a really good restaurant famous for Kalguksu.The kimchi that gives together is attractive

 88%|████████▊ | 19688/22421 [00:40<00:20, 134.72it/s]

원본: 명동교자는 역시 ㅠ 너무 마싯서요 ㅠ 다음에는 비빔국수 먹으러 갈구에요ㅠ, 번역: Myeong -dong Gyoja is so too much.
원본: 인기가 많은 음식점인데 저는 만두는 보통이고 칼국수는 느끼하고 특유의 향이 나길래 잘 못먹었어요 볶은 양파가 들어있는건가요? 저는 살짝 실망했어요 입맛은 개인차이라 제 경우는 맛집이 아니더라고요, 번역: It's a popular restaurant, but I have dumplings, kalguksu feels and has a unique scent.I was a little disappointed. The taste is a private car, so I was not a restaurant in my case.
원본: 특징 : The Original '명동칼국수' 대한민국의 전국에 있는 칼국수 식당의 이름을 명동칼국수가 되게 한 바로 그 집으로 현 '명동교자' 임 진한 닭국물 베이스로 마늘 폭탄 김치와 잘 어울리는 맛의 칼국수임. 사리 및 공기밥 무료 제공으로 매우 푸짐하게 먹을 수 있습니다. 명동에 명동교자 두군데가 있으며. 이전에는 많은 대기시간이 필요했는데 옆가게 까지 확장해서 자리를 이전대비해서 두배가량 넓혀서 이전과 같은 대기는 없어진것으로 보이네요. 처음 보는 분들과의 합석이 당연시 되는 식당이었으나. (예전에는 작은 4인용 식탁만 있었으니) 이제는 1인석도 생기고 2인 테이블도 많아서 예전과 같은 정신 없음은 좀 줄어들었네요. 김치는 중독성이 있는 맛으로 계속 리필해 주기 때문에 계속 먹고 나오면 다음날 오전까지 입에서 마늘 냄새가 날 수 있습니다. 칼국수와 더불어 만두도 꽤 맛있습니다수십년째 같은 맛을 유지하고 있는 집으로 오래된 연륜있는 역사의 식당입니다. 부모님대에서 자녀들까지 계속 찾게 되는. 명동을 가면 명동교자에 가느라 다른 식당을 방문하지 못하게 하는 식당입니다., 번역: Features: The Original 'Myeongdong Kalguksu' The name of the Kalguksu restaurant in Korea is the Myeongdong Kalguksu.You can eat very much with free saree and rice rice.There are two Myeong -dong Gyoja in Myeong -dong.Previously, I needed a lot of waiting time, but it expanded to the next store, and it seemed to have disappeared as before.It was a restaurant that was taken for granted with the first people to see.(There were only a small four -person dining table in the past) Now there are a single seat and a two -person table.Kimchi keeps refilling with addictive flavors, so if you keep eating, you can smell garlic in your mouth until the next morning.Along with Kalguksu, the dumplings are also quite delicious. It is a house that has the same taste for decades.I keep looking for my parents in my parents.If you go to Myeong -dong, it is a restaurant that prevents you from visiting another restaurant.
원본: 마늘맛 찐하고 짱맛ㅜㅜ 집만 가까웠으면 맨날 먹으러 갈텐데.. 매장은 거의 국수 공장에 가까움. 음식 빨리 나오고 가격싸고 양 많고 그대신 대기 항상 길어서 후루룩 먹고 나와야될 것 같은 분위기. 관광객도 많아요, 번역: Garlic tastes steamed and tasted..The store is almost close to the noodles factory.The food comes out quickly, the price is cheap, and the atmosphere is always long.There are many tourists
원본: 마늘김치 맛있아요입냄새나요 흑흑😥😥😥😥😥😥, 번역: Garlic kimchi is delicious
원본: 유명할대로 유명한 맛집이니, 별다른 설명이 필요없음.명성만큼이나 국물, 면발, 김치 어느 하나 빠지는 것이 없음.특히나 마늘이 잔쯕 배인 김치는,말 그대로 마약임., 번역: It is famous as it is famous, so no explanation is required.There is nothing missing as much as the reputation, noodles, or kimchi.In particular, kimchi, which has a cup of garlic, is literally a drug.
원본: 김치가 마늘맛이강해서 매력잇어요 생각나는맛이에요 맛잇어요, 번역: The kimchi tastes attractive because it tastes attractive.
원본: 만두도 국물도 면도 맛있음칼국수는 리필되며 밥도 무료임, 번역: Dumpling and broth is also delicious.
원본: 명동가서 뭐 먹을까 고민하면 그냥 명동교자가 답이죠잉~, 번역: If you go to Myeong -dong and think about what to eat, Myeong -dong Gyoja is the answer ~
원본: 칼국수. 만두. 비빔국수 등 다 먹어봤음. 짜거나 탄 듯한 맛이 나고 칼국수에 빈번히 고춧가루가 들어가 있음. 남은 국물을 섞거나 남은 국수를 섞거나 그릇이 지저분하거나 등등의 이유일 듯. 중국인들 많이 오는 것을 보면 스타일에는 어울리는 듯, 번역: Kalguksu.dumpling.I've eaten all bibim noodles.It tastes like a salty or burned taste, and kalguksu frequently contains red pepper powder.The remaining broth is mixed, the remaining noodles are mixed, the bowl is messy, etc.If you see a lot of Chinese people, it seems to be suitable for the style
원본: 개인적으로 좋아하는 칼국수 스타일이라 자주 가요! 사리, 국물 리필 가능해서 둘이 가면 칼국수 하나랑 만두 하나 주문 합니다. 가격이 야금야금 오르는 듯ㅋㅋ, 번역: I personally like kalguksu style, so I often go!Sari and broth can be refilled, so if you go, you can order one kalguksu and dumplings.The price seems to rise in metallurgical metallurgy haha
원본: 대체 1위인 이유를 모르겠네요 평범한 칼국수입니다 기름져서 맛있지도 않고 같이나오는 김치도 너무 짜기만해요 시장에서 파는 3천원짜리 칼국수가 더 있있어요, 번역: I don't know why it's the first place. It's an ordinary kalguksu.
원본: 정말 맛있었어요 국물도 깊은맛이고 메뉴도 빨리 나와서 정말 추천합니다, 번역: It was really delicious. The broth is deep and the menu comes out quickly.
원본: 예상했던 맛과 너무 다름.칼국수, 김치에서 너무 심한 마늘맛이 남.국물이 꾸덕하고 약간 비림.엄청 시끄럽고 바빠서 그닥 친절하지 않음., 번역: Too different from expected taste.Kalguksu, too severe garlic flavor in kimchi.The broth is slightly overwhelming.It's so noisy and busy that it's not kind.
원본: 음식 굉장히 맛있습니다. 지역맛집 유명맛집이라 관광객, 외국인이 주로 갑니다. 유명식당특유의 서비스가 제공됩니다. 면사리 리필가능입니다., 번역: The food is very delicious.It is a famous restaurant, so tourists and foreigners go mainly.A famous restaurant is provided.It is possible to refill cotton.
원본: 칼국수 존맛이구요 물컵에서 이상한 냄새 나요 전부 다.. 직원분들은 좀 불친절 하십니다, 번역: It's a kalguksu zone taste and a strange smell in the water cup..Employees are a little unkind
원본: 양파를 많이넣고 볶듯이 만든 칼국수인같아요. 조금느끼하지만 맛있습니다. 명동가면 또먹을수도?, 번역: It looks like a kalguksu made with a lot of onions.It's a little bit, but it's delicious.Can you eat again when you go to Myeong -dong?
원본: 맛은 조미료와 후추가 느껴져서 맛있으나 가격이 점점 사악해져서 안가게 됨., 번역: The taste is delicious because of seasoning and pepper, but the price becomes more and wicked.
원본: 퀄리티 미침; 진짜 맛난곳. 밥이랑 사리 추가하면 더 주는곳..하지만 김치많이먹게되면 속쓰리고 만두는 조금 그렇고, 2층이상으로 가면 서비스 질이 많이 떨어짐. 그래서 별 4개요, 번역: Quality crush;Really delicious place.If you add rice and saree, you can give more..However, if you eat a lot of kimchi, the dumplings are a little bit so, and if you go to the second floor, the quality of service will be reduced.So 4 stars
원본: 어머니 뱃속에서부터 먹었던 맛집. 너무많이알려져서 맛은 그대로지만 종업원분들의 친절함이사라진거같다., 번역: Restaurant I ate from my mother's belly.It is so much known that it tastes the same, but it seems to be a kindness director of the employees.
원본: 예전에 먹었는데 그때도 지금도 참 맛있네요. 칼국수를 별로 안좋아하는데 이건 간이 되서 맛있어요., 번역: I ate it before, but it is still delicious even now.I don't like Kalguksu very much, but it's delicious.
원본: 무난무난한 칼국수개인적으론 바지락칼국수를 저 선호해서 제가 선호하는 칼국수는 아니긴 합니다, 번역: Kalguksu is a good person, and I prefer clam kalguksu and it's not my favorite kalguksu.
원본: 역시 맛있어요 김치가 진짜 맛있는거같아요 둘이가서 만두랑 칼국수 하나 시키면 딱인거같아요, 번역: After all, it is delicious. Kimchi seems to be really delicious.
원본: 안먹어봤음 드셔보시길 추천 데일리로먹긴 자극적근데 맛있음 근처에 오셨다면 드셔보실만 함 명동 대표메뉴이기도하고 명성만큼 맛도 괜찮음 단, 먹고난 후 엄청난 고춧가루로인한 치아끼임 주의, 번역: It's a recommended daily daily, but it's irritating, but it's delicious.
원본: 유명한 곳이라 해서 가봤어요예상외로 좋았어요 별기대 안했는데일행모두 만족이었어요, 번역: It was a famous place, so I went there. It was unexpectedly good.
원본: 유명하다기에 만두 포장해왔는데솔직히 하나 당 천원이라기엔크기,맛 둘 중 하나도 맘에 들지 않네요최근 사먹은 음식 중 젤 효용낮ㅠㅠ, 번역: It's famous, so I've been packing dumplings, but I honestly don't like one of the thousand won, one of the two tastes.
원본: 오래된 맛집입니다. 사리와 밥이 무료제공되고, 여름 계절 메뉴인 콩국수도 맛있어요, 번역: It is an old restaurant.Sari and rice are available for free, and the summer season menu is also delicious.
원본: 맛있습니다. 가격 만큼의 값을 합니다. 하지만 유명한 식당입니다. 명동에 갈 일이 있다면 추천합니다. 하지만 명동교자를 가기 위해 명동에 가는 것은 말리고 싶습니다., 번역: Delicious.It pays as much as the price.But it is a famous restaurant.Recommended if there is something to go to Myeong -dong.But I want to get to Myeong -dong to go to Myeong -dong Gyoza.
원본: 엄마랑 쇼핑하구 간단하게 점심먹기 좋은곳근데 뭔가 빨리먹어야될거같음, 번역: If you shopping with your mom, it's a good place to have lunch, but I think I should eat something quickly
원본: 워낙 유명한 곳. 칼국수는 우리 입맛의 칼국수는 아니다. 살짝 단맛과 불맛이 어우러진 일본식 느낌이다. 명동에서 쇼핑하다 허기진 배를 채우기 그만인 집, 번역: It is so famous.Kalguksu is not the kalguksu of our taste.It is a Japanese -style feeling that combines sweetness and fire.Shopping in Myeong -dong and stop filling my hungry stomach
원본: 잘먹고갑니다 괜찮네여, 번역: It's okay to eat well
원본: 정말 오랜만에 가봤는데 맛은 그대로더군요. 인생칼국수집입니다. 만두속이 이렇게 알찰수가..., 번역: I've been there for a long time, but it tastes like.It is a life -kalguk restaurant.The dumplings are like this...
원본: 야채육수로 내는 칼칼한 맛과면의 부드러우면서 쫄깃한 면발이 훌륭, 번역: The soft and chewy noodles of vegetable broth
원본: 분위기 맛 정말 좋았습니다!, 번역: The atmosphere was really good!
원본: 처음 가봤는데 색다른 맛이네요. 중식같은 맛이나요. 만두도 맛있었고. 그냥 딱 별 네개 정도요., 번역: I've been to it for the first time and it's different.It's like a lunch.The dumplings were also delicious.There are just four stars.
원본: 걍 적당한 정도, 번역: The degree of appropriate
원본: 칼국수의 지존 아빠에서 아들도 먹는 집 30년 째 즐겨먹는 집, 번역: Kalguksu's dad's dad's home for 30 years
원본: 먹었던 만두중 단연 으뜸 ㅎㅎ, 번역: Among the dumplings I ate haha
원본: 이제 줄 안서도 될까?, 번역: Can I have a line now?
원본: 지인추천으로 방문한 식당 제육에 돌솥밥과 반찬이 여러가지 나오는 식이다 제육은 저렴한 뒷다리 살로 만든 제육이고 냄새나지 않게 잘볶았다 밑반찬이 예상외로 맛있어서 돌솥밥이 나오는동안 기다리는 시간이 길었지만 하나씩 먹어보는 재미가 있었다. 직원분들과 사장님도 친절하고 너무 좋았지만 식사내내 파리가 윙윙거리고 반찬에 앉고... 이것빼곤 재방문하고 싶은 식당이다, 번역: Dolsot rice and side dishes come out of the restaurant's recommendation.The staff and the boss were kind and so good, but Paris wicked and sat on the side dishes throughout the meal...Except for this, it is a restaurant I want to return to visit.
원본: 인테리어만 좀 고치고 메뉴 약간만 퀄리티 높이면 완전 좋을거같은집., 번역: It will be a good house if you only fix the interior and increase the quality of the menu.
원본: 반찬도 맛있고 배부르게 잘 먹었어요! 다시 오고싶은 맛입니다!, 번역: The side dishes were also delicious and full!I want to come back!
원본: 가격대비 먹을 만한 돌솥밥 집입니다., 번역: It is a stone pot restaurant that can be eaten for the price.
원본: 가게 내부에 자리가 별로 없어서 웨이팅이 긴 편이에요! 된장,고추장을 이용한 요리라서 그런지 식당에 장냄새가 많이나서 꾸리꾸리한냄새 못 참는분들은 좀힘들듯!음식은 맛있었고 시래기봉골레파스타가 제일 만족스러웠어요ㅎㅎ, 번역: There is not much seat inside the store, so we have a long weight!It's a dish that uses miso and red pepper paste, so it's a little hard for those who can't stand the smell of the restaurant.The food was delicious and the Siraebong Golepasta was the most satisfied.
원본: 와 너무 좁다 너무너무 좁다 물이 안 시원해서 힘들다 엘베 없이 높이 올라가야해서 힘들다, 번역: It's too narrow. It's too narrow.
원본: 고추장 삽겹살 파스타는 인생파스타 축에 속하는 편이다. 달래된장크림파스타? 이것도 맛있었음! 다만 봉골레는 개인적으로 입맛에 맞지 않았음., 번역: Gochujang Sapgyeopsal Pasta belongs to the life pasta.Soothing miso cream pasta?This was also delicious!However, Bongolet personally did not fit the taste.
원본: 재료끼리 잘 어우러진 맛이었고 양도 적당한 편입니다. 웨이팅이 없다면 갈만한것 같습니다., 번역: It was a good combination of ingredients and the amount was also suitable.If you don't have a weight, it seems to be worth going.
원본: 이전하고 테이블이 조금 더 많아졌어요. 고추장 된장이 들어간 메뉴들이 있어서 조금 새로워요, 번역: I moved and got a little more table.There are menus with red pepper paste soybean paste
원본: 2층에 위치한 테이블 10개도 안 되는 작은 식당. 작은 산장이나 숲 속에 있는 작은 펜션같은 곳에 초대받은 듯한 아늑한 분위기예요. 오픈 키친의 형태라서 쉐프님들 요리하시는 모습을 힐끔 볼 수도 있습니다. 규모도 작지만 테이블 간격도 좁은 편이라서 자리를 넓게 쓰시는 분들에게는 다소 협소할 수 있습니다. (그럼에도 불구하고 비교적 조용한 것은 장점.) sns에서 핫한 고추장 삼겹살 크림파스타는 진짜진짜 꼭 드셔보세요. 개인적으로 적당히 매콤하면서 크림이 쫀쫀해서 맛있었고 삼겹살도 퀄리티 좋았습니다. 그외에 다양하게 시켜 먹어봤는데 차돌 오일 파스타는 고추장 삼겹살 크림파스타에 비해 더 매콤합니다. 살짝 코 찡하게 만드는 부분이 있어요. 볶음밥은 플레이팅이 독특하게 나와서 예뻤고 모든 음식이 평타이상입니다. 가격대가 조금 있는 편이지만 그럼에도 불구하고 계속 가고 싶은 곳이에요!직접 방문해서 웨이팅 리스트 올려놓으면 카톡으로 바로 연동되어 연락이 옵니다. 전화를 주시기도 하고요. 가게 규모가 작다보니 자리가 생각보다 잘 안나기도 합니다. 지리적 특성상 주차공간 없어 근처 유료주차장 이용하셔야 하고 화장실은 남녀공용 형태입니다., 번역: A small restaurant with less than 10 tables on the second floor.It's a cozy atmosphere that seems to be invited to a small hut or a small pension in the forest.It's an open kitchen, so you can see the chef's cooking.The size is small, but the table interval is narrow, so it can be somewhat narrow for those who are spacious.(Nevertheless, it's relatively quiet.) Really, hot red pepper paste pork belly cream pasta on SNS.Personally, it was moderately spicy and the cream was so delicious, and the pork belly was also good.I've eaten a variety of things, but the marbled oil pasta is more spicy than the red pepper paste pork belly cream pasta.There's a little bit of a nose.The fried rice was pretty because of its unique plating, and all foods are flat.There's a little price range, but it's still a place I want to go!If you visit in person and put up the waiting list, you will be linked directly to the katok.I can call you.The store is small, so the seat is not better than I thought.Due to its geographical nature, it is necessary to use a paid parking lot near the parking lot.
원본: 맛있다는 후기가 압도적인데 기대했던 것만큼 맛있지 않았음..개인적으로는 진짜 별로고추장파스타는 아웃백 투움바 파스타 느낌인데 투움바가 훨씬 맛있음리조또는 너무 느끼해서 반도 못 먹었고...같이 간 친구도 맛없음에 탄식함가게 분위기 자체는 고즈넉하고 좋은 편임재방문의사 x, 번역: The reviews that are delicious are overwhelming, but it was not as delicious as expected..Personally, the red pepper pasta feels like an outback tooum bar pasta...The friend who went with me is also tasteless, so the atmosphere of the shop is quiet and good.
원본: 퓨전요리라 기대하고 갔는데 기대치만큼 엄청 맛있었어요. 고추장 삼겁살 파스타도 맛있고 된장 리조또?? 그거도 엄청 맛있어요!!! 서비스는 진짜 친절해요 중간중간 물 마시면 다시 따라주고 또 자리 잡을때도 안쪽이 에어컨쪽이라 시원하다고 해주시고 오픈키친이라 그런지 더 믿음직스럽고 들어가자마자 나는 된장냄새?? 그런게 있는데 그냄새가 진짜 배고프게해요 ㅋㅋㅋ, 번역: I expected it because it was a fusion dish, but it was as delicious as expected.Gochujang samgal pasta is also delicious and miso risotto ??It's also very delicious!!!The service is really friendly. If you drink water in the middle, it will follow you again, and even when you settle down, it is cool because the inside is cool.There is something like that, but the smell makes me really hungry hahaha
원본: 매장이 작은게 너무 아쉬워요ㅠㅠ 웨이팅만 아니면 연남 갈때마다 방문하고 싶은 맛집입니다ㅜㅜㅠㅠㅠㅠㅠ, 번역: It's too bad to have a small store ㅠㅠ If you don't just wait, it's a restaurant that you want to visit every time you go.
원본: 파스타와 고추장, 된장이 어울릴 줄 몰랐는데 너무 조화가 잘되어서 맛있게 먹었습니당, 번역: I didn't know that pasta, red pepper paste and miso were so good, but it was so harmonious that it was delicious
원본: 대표메뉴로 먹어봤는데 완전 굿! 파스타 별로 안 좋아하는데 싹싹 다 긁어먹었으니..ㅎㅎ 퓨전이라 익숙하면서도 새로운 맛인데 정말 감칠맛 난다, 번역: I've eaten as a representative menu, but it's good!I don't like pasta, but I scratched everything..ㅎㅎ Fusion, but it's familiar but new, but it's really good.
원본: 고추장삼겹살크림파스타랑 불고기볶음밥먹었는데 맛있고 양도많았어용 분위기도좋았습니다! 그런데 간판이작아서 가게가 찾기힘들수있을거같아욧, 번역: I ate red pepper paste pork belly cream pasta and bulgogi fried rice.But the signboard is so big that the store may be hard to find.
원본: 맛있다 고추장 삼겹살 파스타 추천 느끼하지 않고 좋다 가게도 깔끔하고 좋다, 번역: It's delicious Gochujang pork belly pasta recommended.
원본: 음식 깔끔하고 맛있었어요. 가격도 그렇게 비싸지 않고. 다만 내부가 조금 좁아요~, 번역: The food was clean and delicious.The price is not so expensive.But the inside is a bit narrow ~
원본: 위생상태가 아 최악이에요.아니 메인서빙하는 분이 바닥에 다니는 개를 들고만지고 쓰다듬다니... 심지어 개도 더러움그 손으로 서빙을 함 안 씻고내 두눈으로 여친과 똑똑히 봣음이글을 보고 안 그런다해도 하나를 보면 열을 안다는... 안 보이는데서는 얼마나 더러울까아오.. 더러워 나와서 토할뻔, 번역: The hygiene is the worst.No, the main servant is stroking with a dog on the floor...Even the dog did not wash with the dirt of the hand...How dirty it will be when you can't see it..I almost vomited because it was dirty
원본: 식당 매우 작음네이버에 검색해서 갔지만 별로였슴일단 파스타 면이 식으면 바로 떡지듯이 되었고맛도 예상보다 더 ... 😦, 번역: I searched on the restaurant very small, but it was not good...😦
원본: 작고 아담했어요. 메뉴가 특색이 있는 것 같아 좋았어요. 크림리조또는 좀 밍밍한 맛이었어요. 고추장 삼겹살 파스타 맛있어요!, 번역: It was small and small.It was nice that the menu was characteristic.It was a creamy or a little bitter taste.Gochujang pork belly pasta is delicious!
원본: 된장 리조또와 고추장 파스타 시켰느데 거부감도 없고 맛있네요. 가게는 좁아 북적되지만 재방문의사 있습니다!!, 번역: I made miso risotto and red pepper paste pasta, but I don't have a sense of rejection and delicious.The store is narrow and crowded, but I have a doctor!!
원본: 음식은 맛있으나 너무 느립니다. 그 느린 와중에도 직원들은 강아지랑 놀아주고 있네요. 직원 마인드가 최악임., 번역: The food is delicious but too slow.In the midst of that slow, the staff are playing with the dog.Employee mind is the worst.
원본: 고추장삼겹살 크림파스타도 맛나지만... 백김치볶음밥 시레가봉골레 등 숨은 메뉴도 맛나다는거! 감칠 2호점도 생겼어요 근데 2호점은 파스타를 팔지않음 ㅠㅜ 대신 오븐에 기름끼 쫙뺀 삼겹살이 제맛이에용 ㅋㅋ, 번역: Gochujang Pork Belly Cream Pasta is also delicious...Baek Kimchi Fried Rice Bob Sire Garbong Golle also tastes good!There is also a second store. But the second store does not sell pasta.
원본: 식사시간엔 줄서야함..간이 약간 강한면이 있지만.. 백김치와 함께 먹으면 딱맞음..가정집 개조해서 만든 식당이라..분위기 내기 좋고.. 답답하지 않은 인테리어라 좋음..음식도 맛있고, 늘상먹던 음식이 아닌 독특한 퓨전 요리라 먹으면서도 재미있고 좋았음.. 대기시간 주의 필요..일찍가길.. 권함.., 번역: You have to line up in meals..There is a slightly strong liver..It's perfect if you eat it with Baek Kimchi..It is a restaurant made by renovating home..Good atmosphere..It's not frustrating..The food was delicious, and it was fun and good because it was a unique fusion dish..Wait time attention..Going early..Recommendation..
원본: 맛이 보장돼있는 체인점이죠! 차돌어쩌고만 먹다가 눈꽃삼겹떡볶이 나와서 먹어봤어요 역시 맛있습니다. 근데 떡볶이 데우는 플라스틱?실리콘? 부분에 모르고 젓가락이 닿아있었는지 그냥 먹었다가 입술 호되게 데여서 물집잡혔습니다.. 불이 없다고 안일하게 생각하면 안되고 조심해야돼요, 번역: It's a chain store that guarantees taste!I ate it, but I ate snowy samgyeokbokki.But tteokbokki warms plastic? Silicone?I didn't know it, but I just ate chopsticks, and then I caught it..You shouldn't think that there is no fire

 88%|████████▊ | 19688/22421 [01:00<00:20, 134.72it/s]

원본: 청년다방 떡볶이 차돌시리즈로 먹어봤는데 맛있어요. 많이 맵지 않아서 매운거 못먹는 쪼렙도 거뜬히 먹어요. 두명이서 방문한지라 볶음밥이랑 감튀는 못먹었지만 떡볶이 자체로도 좋았습니다!밀떡이 길쭉하게 들어있어서 가위로 잘라먹는 매력이 있어요. 다음에 또 방문하고 싶은곳.※ 프랜차이즈지만 개인적으로 떡볶이를 좋아해서 편파적인 리뷰가 되었습니다., 번역: I tried it as a young teapot Tteokbokki Chadol series and it was delicious.It's not very spicy, so I can't eat spicy.I visited two people, so I couldn't eat stir -fried rice and rice cake, but it was good for Tteokbokki itself!The wheat rice cake is long, so it has a charm to cut with scissors.I want to visit again next time.※ I personally like tteokbokki, but I became a biased review.
원본: 재방률86%. 노하우가 있는 곱창집은 서울에서 드물다. 대부분 그냥 팔 뿐이지. 나쁘지 않은 가격에 나름의 노하우가 담긴듯한 메뉴가 곱창을 흡입하게 만들었다. 더군다나 함께 더해진 버섯이나 호박 덕에 3인분을 밥 없이 먹었는데도 충분히 배가 불렀다. 물론 여자 2에 남자 1이긴 했지만..치즈가 인상깊다. 물론 뭔가 애매한 느낌이 들기는 했지만 소스 그 자체만으로 메리트 있었기때문에 불만은 없었다. 사장님이나 직원분들도 친절했고 모든게 좋았다. 옆집 곱창집들 놓아두고 미아사거리까지 가서 굳이 한번 더 먹어보고싶은 곳이다. 추천한다., 번역: 86%rerun rate.Gopchang houses with know -how are rare in Seoul.Most of them are just selling.The menu that contains its own know -how at a bad price made the giblets inhaled.Moreover, thanks to the mushrooms and pumpkin added together, I had enough hungry even though I ate three servings without rice.Of course, she was a man 1 in a woman..The cheese is impressive.Of course, I felt something ambiguous, but there was no dissatisfaction because there was a merit alone.The boss and the staff were kind and everything was good.I want to leave the giblet house next door and go to Mia Intersection and try it again.I recommend you.

 88%|████████▊ | 19780/22421 [01:00<00:46, 57.10it/s]

원본: 여기 일단 사장님 너무 친절하셔요 ㅠ ㅠ 무한 감동! 막창맛도 고소하니 아주 좋았아요., 번역: Here, the boss is so kind ㅠㅠ Infinite impression!It was very good to taste the makchang.
원본: 막창은 전국에서 제일 맛있는듯. 진짜 맛있어요..가격도 괜찮은데 딱! 시장판입니다. 그 분위기 좋아하시는 분들은 상관없어요, 번역: Makchang seems to be the best in the country.It's really delicious..The price is fine, but it's perfect!Market board.It doesn't matter if you like that atmosphere
원본: 지역 주민들에게 소문난 곱창 막창 맛집입니다 미아사거리 들르시면 들러서 드실만합니다, 번역: Gopchang Makchang Restaurant is known for local residents.
원본: 숭인시장의 곱창 막창 맛집, 번역: Gopchang Makchang Restaurant in Sungin Market
원본: 막창 최고에요!, 번역: Makchang is the best!
원본: 이태원 식당 중에서 제법 많이 먹었다고 자부하는데 가장 기억에 남는 식당입니다. 꾸덕꾸덕한 치즈가 생각 날 때 가면 좋습니다. (크림드 스피니치)양갈비 한 대에 8000원인데, 크기도 심지어 커요~ 적당히 익혀 나오는데 아주 맛있습니다. 사이드 메뉴도 넘 맛있구료~ 브런치 먹으러 11:20 쯤 갔는데 제 뒤부터 웨이팅이 엄청 길어지더라구요 사람이 많은 식당이에요ㅜㅎ, 번역: It is the most memorable restaurant to be proud of eating a lot among Itaewon restaurants.It is good to go when you think of a lot of cheese.(Cream Spinachi) It's 8,000 won for lamb ribs, but it's even big.The side menu is also delicious ~ I went to eat brunch about 11:20, but the weighting was very long after me.
원본: 평소에 접하기 힘든 남아프리카 음식을 먹을수 있어 좋았습니다👍 양고기 냄새도 별로 안나고 넘 고소했어요 ㅎㅎ 치킨파이는 무난한 맛이었고 치즈가 들어간 시금치도 특색있고 맛있었네요 ㅎㅎ 가격은 착하지 않지만 가끔 방문하면 좋을 곳이예요, 번역: It was good to be able to eat South African foods that are hard to see.
원본: 양고기 맛있게 먹으려면 강추. 직원들이 한국어를 몰라서 한국에서 영어로 주문해야 하는 기괴함 ㅡㅡ 데이트 코스로는 나쁘지 않다., 번역: Lamb is recommended to eat deliciously.The bizarreness that employees should order English in English because they don't know Korean.
원본: 향신료 향 너무 강하지 않고 맛있어요둘이서 메뉴 두 개 시켰는데 배불러서 남겼어요 하우스 와인을 500ml, 1L로 시킬 수 있어서 좋아요, 번역: It's not too strong and it's delicious. They had two menus, but I left them in full.
원본: 미트플래터의 양고기 스테이크에는 고기냄새도 없고 꼭 소고기같은 느낌이에요.정말 맛있었어요!램파이에서는 약간 양고기냄새가 나서 호불호가 갈릴 수 있어요.대체적으로 너무 맛있어요.양고기 못먹는 분들도 이 곳은 쉽게 접할 수 있을 것 같아요., 번역: The lamb steak of the meat platter doesn't smell meat and it feels like beef.It was really delicious!In Lampi, it smells a bit like lamb, so you can dislike it.It's so delicious.Even if you can't eat lamb, I think you can easily access this place.
원본: 남아프리카음식은 이렇구나 알 수 있었어요. 이전에 전혀 먹어보지 못한 이국적인 음식을 찾으시는 분들에게 추천드립니다, 번역: South Africa food was like this.Recommended for those looking for exotic foods that have never been eaten before
원본: 향이 좀 쎈편이라 취향 탈듯 합니다.수요미식회 나온 뒤로 더 붐비는 듯. 양갈비는 괜찮았지만 소시지의 경우 좀 저랑은 좀 안맞았던듯., 번역: The fragrance is a bit strong, so it looks like a taste.It seems to be more crowded since the demand gourmet.Lamb ribs were fine, but in the case of sausage, it didn't fit me a little.
원본: 맛은 전반적으로 아주 좋아요. 그런데 미트플래터의 양갈비가 언더쿡된 부분이 있어 아쉬웠다는, 번역: The taste is very good overall.However, it was a pity that the lamb ribs of the meat platter were under cook.
원본: Meat Platter - 소세지 2개, 양고기 2개, 으깬감자, 코올슬로와 옥수수소세지는 두종류가 나옴. 둘 다 고기고기함. 조금 퍽퍽한감이 없잖아 있긴한데 중요하지 않음. 맛있기때문에.양고기는 정말 맛있음. 잡내 이런거 전혀 안나고 진짜 육질도 부드럽고 간도 잘 되어있어서 존맛탱임 다만 고기가 조금 두껍고 주문이 몰려 바쁜 시간에 가서 그런지 안익은 부분이 좀 있었음. 레어정도의 굽기가 아니라 겉만 익은 부분ㅇㅇ.으깬감자는 갈릭솔트랑 허브가 들어가서 간도 알맞고 양고기 그리고 소새지랑 같이 먹으면 홍콩감. 그냥 먹어도 맛있는데 같이 먹으면 진짜..코올슬로는 평범...옥수수는 위에 발사믹 소스가 뿌려져 있는데 맛난. 코올슬로 옥수수 둘 다 느끼함을 잡아줘서 좋음.추가로 sweet potato 시켰는데 아마 시나몬가루? 가 들어간 으깬 고구마임. 내 취향 아니라 한입먹고 패스함...3줄 요약1. 맛은 존맛탱2. 조금 북적거림 1시 30분쯤 도착했는데 웨이팅 있었음. 3층에서 웨이팅 할 수 있어서 춥지 않았다3. 가격대는 조금 있음., 번역: Two MEAT Platter sausages, 2 lamb, mashed potatoes, koolslo and corn hydroside are available.Both meat meat.There's no a little bit of a feeling, but it's not important.Because it is delicious.Lamb is really delicious.It's not like this, and the meat is soft and the liver is good.It's not a rare baking, but a ripe part.The mashed potatoes are suitable for garlic sol and herbs, and if you eat it with lamb and small birds, Hong Kong feels.It's delicious even if you just eat it..Koolslo is ordinary...Corn is sprayed with balsamic sauce on top.It is good to grab both corn with koolsl.In addition, I made suet potato.Mashed sweet potato mime.I eat and pass, not my taste...3 line summary 1.The taste is John Matang 2.I arrived a little crowded at about 1:30 and was waiting.It wasn't cold because I could wait on the third floor.There is a little price range.
원본: 정말 맛있어서 잘 먹었습니다. 다만 소시지 네 개 나오는건 가격에 비해선 아쉬운 맛이었어요. 가격이 더 착하면 좋겠지만 배부르게 먹고 셋이 78000이면 나쁘지 않았죠? 물론 맥주 두잔에 생과일쥬스 가격 빼면 58000에 요리 세 개, 번역: It was so delicious that I ate well.However, four sausages were unfortunate compared to the price.It would be nice if the price would be better, but it wasn't bad if the three were 78000.Of course, two glasses of beer are 58000 and three dishes.
원본: 양갈비를 좋아하는 사람이면 꼭 가봐야할곳!제가 나름 미식가이고(자칭...) 가리는 음식이 없는 사람이라...저를 만족시키는 음식이 많지 않았기 때문에 글을 올리지 않았으나, 브라이리퍼블릭은 너무나 맛있어서 글을 올려봅니다.양갈비는 누린내 없고 맛있어요손에 꼽을 정도로 맛있어요시금치와 고구마와 함께 나오는데정말 맛있어요램파이도 같이 먹었는데이건 약간 특유의 양고기 냄새가 있어호불호가 갈릴것같아요여기는 초딩입맛은 가면 안된다는 단점이 있어용대부분 양고기 음식이다보니.. 호불호가 갈릴수도그리고 대부분 외국인이 방문하는식당이라영어로 주문받고 서빙한다는 점.,그래도 매우 맛있어요!매니아층이 좋아할듯합니다., 번역: If you like lamb ribs, you must go!I am a gourmet (self -proclaimed.....) And I don't have food...I didn't post because there aren't many foods that satisfy me, but Briepublick is so delicious that I can post it.The lamb ribs are delicious and delicious. It is delicious enough to be one of the hands.I have..It may be divided and most of foreigners are ordered and served as a restaurant., But it's very delicious!The enthusiasts seem to like it.
원본: 실내에 연기가 자욱한거 빼고는 음싯맛 가격 다 만족스럽습니다. 추운데 연기 배려구  창문 열어놓으시더라구요., 번역: Except for the smoke in the room, the price of the tastes is satisfactory.It was cold, but it was open to the window.
원본: 깨끗, 깔끔, 시끌벅적맛있다가격이 과하다.양념마늘과 매콤한 조개(제첩?)국으로 불백두번은 더 추가할 수 있을 듯.불백은 맛있다., 번역: Clean, neat, and noisy.Seasoned garlic and spicy shellfish can be added more.The fire is delicious.
원본: 그냥 딱 잘 만든 맛이에요. 막 그렇게 멀리서 찾아갈 정도는 아니에요! 근데 마늘 쌈장은 마늘 좋아해서 좋았어요! 냉면은 그냥 시판냉면이에요~, 번역: It's just a good taste.It's not enough to go from far away!But garlic ssamjang liked garlic!Cold noodles are just commercial cold noodles ~
원본: 맛있는데 양은 적어요~ 조개국이 시원합니다~~~부대찌개는 그럭저럭, 번역: It's delicious, but the sheep is small ~ The clam is cool ~~~
원본: 성북동 유명한 식당이지만, 사람이 꽤 많아서 친절한 서빙을 바랄 수 없는 곳입니다. 양이 좀 작고요., 번역: It is a famous restaurant in Seongbuk -dong, but there are quite a lot of people so you can't wish you kind.The amount is a little small.
원본: 부대찌개는 그냥그럼.불백은 맛있음!!그러나 양은아주아주 적은편, 번역: Budae stew is just.The fire is delicious!!However, Yang Eun -ah
원본: 돼지불백 8000원인데 양이 대패삼겹살 1줄 잘라놓은 정도의 양밖에 안나옵니다맛은 있는데 그렇다고 유명해질 정도로 맛있지도 않구요, 번역: It's 8,000 won for pork, but the amount of pork belly is only cut.
원본: 고기도 맛있고 무엇보다 조개국이 진짜 맛있어요 갈때마다 세번은 리필해 먹어요야채랑 반찬도 무한리필이라 좋아요, 번역: The meat is delicious and most of all, the clam is really delicious. Every time I go, I refill it.
원본: 먹을만한 곳. 항상 기대만큼 하는 곳., 번역: A place to eat.Always do as expected.
원본: 지나가다 들릴만한집.. 굳이 멀리서 찾아오긴 별로.. 한번쯤 먹어본 연탄불고기 그이상 그이하도 아님.. 가격대비 양이 작아요.., 번역: A house that can be heard by passing by..I don't have to come from afar..Briquette Bulgogi I've eaten once..The price is small..
원본: -깔끔하고 친절함-평양냉면 을밀대보다 나음-주차 6대밖에 안됨-만두 개당2천원으로 나눠시킬 수 있음-완냉함! 재방문의사있음!, 번역: Neat and kindly, Pyongyang cold noodles can only be divided into 2,000 won per dumplings.I have a doctor's doctor!
원본: 가족끼리 자주 가는데 진짜 맛있음구워주는 마늘마저 맛있음 진짜 맛있음, 번역: Family goes often, but even the garlic that bake is really delicious
원본: 음식: 세트였는지 코스였는지... 어쨌든 그것을 주문했습니다. 파스타는 트러플파스타로 했고요. 음식들은 당연히 (가격대비)무난하게 맛있습니다. 피자맛집이라던데 개인적으론 파스타가 훨씬 맛있었네요. 트러플파스타 먹고 너무 맛있어서 눈물을 흘릴 뻔했습니다.서비스: 당연히 친절하시고요. 종종 신경써주시고 와인도 서빙해주시고 그랬습니다.분위기: 좋아요.위생상태: 깨끗해요., 번역: Food: Is it a set or course?..Anyway, I ordered it.Pasta was truffle pasta.The food is, of course, it is safe.It's a pizza restaurant, but personally, pasta was much more delicious.It was so delicious that I ate truffle pasta, so I almost shed tears.Service: Of course you are kind.Often carefully and served the wine.Mood: Good.Hygiene: Clean.
원본: 한줄평👉 도산공원 속 유럽레스토랑 느낌-전좌석이 야외 테라스 같은 느낌인데 생각보다 난로 시설이 잘되있어서 추운 느낌 없었고 트러플 들어간 피자와 파스타가 정말 맛있었어요!, 번역: One line 👉Dosan Park feels like an outdoor terrace, but the stove is better than I thought.
원본: 인테리어와 분위기는 특별함을 느낄 수 있을 정도입니다.비가와서 실내에서 식사를 했지만, 날씨 좋은 날은 길게 이어져있는 바깥 테라스에 앉아있으면 그림이 나올 거 같습니다. 오픈키친도 활기차 보입니다. BGM(?)은 일렉트로닉 계열의 알수없는 음악을 무한반복시켜 놓았어요. 컨셉인 듯.피자는 맛있었는데요. 리조또는 쌀이 덜익은 듯하고 그리 만족스럽지 않았어요.샐러드와 같이 나온 스테이크는 미디엄이 마치 미디엄 웰던 처럼 느껴졌습니다. 미디엄 레어가 나을 듯 합니다.봉골레파스타는 해산물이 듬뿍 들어있어서 놀랐네요. 해산물모듬 요리도 괜찮은 거 같아요.쪼금쪼금 나오는 기존의 이탈리안 레스토랑에 비해서 손이 큰거 같아서 좋습니다.  전체적으로 아쉬운 점이 있다면, 간이 쫌 짠 거 같다는 생각이 들었습니다.발레파킹됩니다., 번역: The interior and atmosphere are special.I ate it indoors because it was raining, but the good day would be a picture when I sat on the long -standing outside terrace.Open kitchen also looks lively.BGM has repeated the unknown music of electronic.It seems to be the concept.The pizza was delicious.Riso or rice seemed to be less and not satisfactory.The steak that came out like a salad felt like a medium well.Medium rare seems to be better.Bonggol Foresta was surprised that it contained plenty of seafood.Seafood assorted dishes are also good.It's good to have a bigger hand compared to the existing Italian restaurant.If there is something unfortunate overall, I thought it seemed to be salty.Ballet parking.
원본: 피자가 맛있네요 파스타는 별로고! 가격대비 특별한건 없고 자리가 좋고 테라스가 있어서 좋아용, 번역: Pizza is delicious. Pasta is not good!I don't have anything special for the price, I have a good seat, and I have a terrace
원본: 점심 미니부페로 방문했어요 야외 테라스에서 먹으니 여유롭고 좋아요 부페음식이 무난하게 좋았고요 피자는 원래 맛있아요 다만 참치파스타는 참치통조림 넣은 파스타가 나와 당황했네요 그래도 괜찮은곳^^, 번역: I visited the lunch mini buffet. I ate it on the outdoor terrace.
원본: 봉골레시킬때 나폴리식이라 짜다는 얘기를 들었지만 괜찮았는데 카프레제 샐러드 야채 위에 소금이 너무 많이 뿌려져 있어서 야채는 거의 못먹었네요..., 번역: I heard that it was salty when I was a bonggol recipes, but it was okay, but I had so much salt on the caffeze salad vegetables, so I rarely eat vegetables...
원본: 가을저녁쯤 갔었는데 테라스에 앉으니 분위기 좋았어요 발렛도 가능했고 피자도우도 훌륭하고 맛있었어요 점심엔 뷔페 형식으로도 운영하는걸로 알고있습니당먹물파스타는 연인끼리 간다면 비추입니다^^ㅋㅋㅋㅋㅋㅋ, 번역: I went to the autumn evening, but I sat on the terrace, so it was nice to see the ballet, and the pizza dough was great and delicious.
원본: 기본적으로 시끌하고 액티브한 분위기를 지향하는데다 테이블간격이 좁아 쾌적한 환경은 아니지만 사실상 유럽의 핏제리아도 그러하다. 무엇보다 피자맛은 반박불가... 서비스도 가격도 그저그렇지만 피자를 못잃어 끊임없이 재방문하게 된다. 도우의 쫄깃고소함과 토마토 베이스의 신선한 감칠맛이 훌륭하다.#피자러버두번가세요, 번역: Basically, it is a loud and active atmosphere, and the table interval is not a pleasant environment, but in fact, European Fiteria is true.Above all, the taste of pizza is impossible...The service and the price are just a pizza, but they are constantly returning.The chewy sue of the dough and the fresh rich taste of the tomato base are excellent.#Pizza Rubber Dumplings
원본: 유명한 집인데 맛 자체는 애매했음. 내 입맛이 서민적이여서 그런지는 모르겠는데 피자 맛이 시켜먹는 거랑 비교해서 대단하다고 느껴지지 않았음. 밤에 갔는데 조명이 매우 어두웠음., 번역: It is a famous house, but the taste itself was ambiguous.I don't know if my taste is so common, but I didn't feel great compared to the pizza taste.I went at night and the lighting was very dark.
원본: 피자는 맛있어용. 치즈가 정말 달라요.근데 파스타는 짜고 제 입맛에는 별로네요.. 좀 덜짜게를 요청해도 짰어요. 평일런치 샐러드바 이용가능한데 나름 괜찮아요~가격은 1인 3만원안쪽부터 시작하는데 위치와 샐러드바를 생각하면 저는 괜찮은것같아요., 번역: Pizza is delicious.The cheese is really different.But pasta is salty and it's not good for my taste..I asked for a little less.Weekday lunch salad bar is available, but it's okay ~ The price starts from 30,000 won per person.
원본: 예약하고 늦게갔는데도 잘받아줬음그런데 안쪽 테이블은 바닥은 장판깔려있는데 엄청 쿵쾅거렸음 사람들이 걸어만 다니는데도게다가 식기가 오래된건지 나이프가 날이 없는것도 있었음 ㅋㅋ분위기 식사 다 좋았지만 바닥이랑 식기때문에 별하나뺌, 번역: I made a reservation and received it late, but I accepted it well, but the inner table is laid down, but it was so thump that people walked around.Hana
원본: 저는 런치에 갔는데 샐러드바 이용 할 수도 있고 음식도 맛있어요! 2인석 테이블간의 간격이 좁았던 게 좀 아쉽긴 해요, 번역: I went to the lunch, but I can use the salad bar and the food is delicious!It's a bit unfortunate that the interval between the two -seat tables was narrow.
원본: 장한평역 가성비 스시맛집이에요.얼마전에 유명한 스시집에서 구운 초밥을 먹고 신세계를 맛봤는데요.스시긴도 구운모듬초밥이 있더라구요.맛이 아주 뛰어나진 않지만 가격을 생각해보면 굉장한 수준이라고 생각해요.재방문의사 있습니다.주차는 가게앞에 한두자리 정도 있네요., 번역: Janghan Pyeong Station is a sushi sushi restaurant.Not long ago, I ate the grilled sushi at a famous sushi restaurant and tasted the new world.Sushi is also baked sushi.It's not very good, but I think it's a great level considering the price.I have a doctor of return.There are about one or two parking in front of the store.
원본: 가성비최강. 구운모듬초밥 진짜 맛있었습니다.음식으로 맛있게 싸대기 맞은느낌이에요.일본갔다온지 몇일되지도 않았는데 일본초밥을 잊어버리게 만들어주네요.진짜 엄청맛있게잘먹었습니다.재료만 있으면 라스트오더는 1시30분 정도라네요! 참고하세요!, 번역: Non -prospect of value.It was really delicious.I feel delicious with food.It's been a few days since I went to Japan, but it makes me forget Japanese sushi.I ate really deliciously.If you have the ingredients, the last order is about 1:30!please refer to this!
원본: 장안동 작은 초밥집. 단골 손님이 많이 오는 것 같은데 단골이 되면 잘 챙겨주시는 듯 하다. 초밥은 무난합니다. 가끔씩 초밥 생각날 때 가면 좋을 것 같아요., 번역: Jangan -dong small sushi restaurant.It seems that a lot of regular customers come, but when they become regulars, they seem to take care of them.Sushi is okay.I think it would be nice to go when I remember sushi.
원본: 같이나오는 냉모빌이 맛있었고, 초밥도 밥양이 많지않아 좋았습니다. 술 즐기시는 분들이 도란도란 이야기 하고계시는 시끌벅적한 분위기였습니다., 번역: The cold hairs that came together were delicious, and the sushi was not good.It was a noisy atmosphere that people who enjoyed dorando were talking about Dorando.
원본: 초밥과 우동 냉메밀 전부 맛있습니다. 매장이 협소하여 매장 내에서 먹은 적은 없고 보통 포장해서 집에서 먹습니다. 포장 기다리면서 매장 둘러보면 매장분위기 아기자기하니 좋고 직원들도 친절합니다. 개인적으로 동네에서 가장 좋아하는 식당 중 하나입니다., 번역: Sushi and udon cold buckwheat are delicious.The store is narrow and I have never eaten in the store and usually packs it at home.If you look around the store while waiting for the packaging, it is good to be cute and the staff are kind.Personally, it is one of my favorite restaurants in the neighborhood.
원본: 여기 자주 방문하는데 갈 때 마다 서비스, 맛, 분위기 모두에 감동하고 나온답니다., 번역: I often visit here, but every time I go, I am impressed by the service, taste and atmosphere.
원본: 식객촌 안에 있어요 넷마블 직원 구내식당인듯 사람몰릴때는 엄청많네요 맛은 평범, 굳이 찾아올만한 정도는 아닌듯, 번역: It's in a restaurant. It's a lot of Netmarble staff cafeteria.
원본: 여기 유니짜장 진짜 최고예용.... 짱맛있엉!!!!!! 비싼만큼 맛있음 ~~~!!!!구로디지털 단지 일대 짜장중 최고 근데, 점심시간에 조금 늦으면 바루 웨이팅이에요!! ㅋㅋㅋ, 번역: Unijajang is really the best....It's delicious!!!!!!It's as expensive as expensive ~~~!!!!The best of the Guro Digital Complex, but it's a little late for lunch.!lol
원본: 지벨리 지하에있어요 자극적이지않아 가족외식에 좋아요 찹쌀탕슉이 맛나요 가격은 조금 비싼편., 번역: It's in the basement of Gibili. It's not irritating, so it's good for family dining.
원본: 해물칼국수라 쓰고 백짬뽕이라 읽는다. 금액도 싼것도 아니면서 퀄이 왜이런가. 간짜장은 평범하다. 볶음밥은 안나온다. 맛을 평가해야 하는데 주문을 해도 안나온다. 세번 얘기하면 나온다. 10분에 한번씩 3번을 얘기해야 나오니 미리미리 주문해야한다. 그리고 앞으로 수요미식회 진짜 믿고 거른다. 사장이 장사가 좀 되서 그런가 굉장히 언짢다. 인사한마디 건내지 않는 시니컬한 사장이 마성의 매력이 있다.사진 찍을 비주얼로 나오는 식당이 아니라 사진 따위 찍지않는다. 조만간 손님보다 파리가 많을 상이니 주변에 망조가 가득한 형국이다.있을때 잡아야지 잃고 나서 고치는건 무의미하다., 번역: I use seafood kalguksu and read it as a white champon.Why is Quality like this, not cheap?Ganjajang is ordinary.The fried rice does not come out.You need to evaluate the taste, but you don't order it.Talking three times comes out.You have to talk three times every 10 minutes, so you have to order it in advance.And in the future, I believe in the demand gourmet.The boss is a bit old, so it's very upset.A sensational boss who does not say a word is fascinating.It is not a restaurant that comes out as a visual to take a picture, but does not take a picture.Sooner or later, there are more flies than the guests, so they are full of nets around.It is meaningless to fix it after losing it.
원본: 짜장면이 너무먹고싶어서갔다. 여기 종업원들이 중국인인데 겁나 불친절하다. . . .짜장면 ? 먹을만하다 근데 다시갈생각은 없다, 번역: I went to jjajangmyeon too.The employees here are Chinese, but they are scared and unkind....Jajangmyeon ?It's worth eating, but I don't want to go back
원본: 골드키위칠러는 얼음에 시럽에 넣어 갈은거라고 하는데, 역시 달달하네요^^ 애플파이보다 콘파이가 더 맛있네요~, 번역: Gold Kiwi Chiller is said to be in the syrup in ice, but it's sweet.
원본: 다른지점에 비해 깔끔하고 친절해서 자주가요. 스낵랩 간식으로 혼밥하기 좋아용, 번역: It's clean and kind compared to other branches.I like to eat as a snack lap snack
원본: 좌석수가 생각보다 많네요카운터보던 알바는 그다지 친절하진 않았어요, 번역: There are more seats than I thought.
원본: 역시 맥도날드는 간단하게 먹으면서 시간을 보낼수 있어서 좋은거 같네요, 번역: After all, McDonald's seems to be good because I can spend time while eating simple
원본: 점심때 혼밥하기도 좋고 간편하고 입지 좋은기 있어서 좋아요, 번역: It's good to be good at lunch, it's easy and good.
원본: 안암역 근처에 있는 스콘맛집 키라쿠입니다!깔끔하고 예쁜 화이트톤의 인테리어가 인상깊었던 곳이에요. 스콘맛집이라고 해서 들려봤답니다! 카운터 옆에 정~말 많은 스콘이 있어요. 녹차스콘 얼그레이스콘 생크림스콘 플레인스콘 크랜베리스콘 앙버터 등등...그 중에 말차스콘을 먹었어요! 스콘 특유의 바삭함과 버터향이 확 나고, 거기에 녹차향까지! 중간중간 씹히는 견과류까지 정말 맛있었어요ㅠ 음료는 그렇게 생각나는 맛은 아니었지만, 스콘만으로도 갈 가치가 충분한 곳이에요! 스콘 크기는 조금 작은편이고, 가격은 2800원이에요. 싼편은 아니죠? 그런데도 집에 갈때 스콘 세 종류나 더 포장해갔어요..ㅎㅎ... 얼그레이스콘이 향이 진짜 좋아요. 여기 스콘들은 향에서 한번 먹고들어가는듯...스콘 종류가 고르기 어렵다면 사장님께서 잘나가는 메뉴도 골라주신답니다! 그걸로 처음 도전해보시는것도 좋을듯하네요:), 번역: This is Kiraku, a scones restaurant near Anam Station!It's a clean and pretty white interior.I heard it as a scones restaurant!There is a lot of scones next to the counter.Green Chachascon Earl Grace Conficulum Plain Scon Cranberryis Converter and so on...Among them, I ate horse carcons!The crispy and butter flavor of the scone, to the green tea flavor!It was really delicious to chewy nuts.The scone size is a bit small, and the price is 2800 won.Isn't it cheap?Nevertheless, when I went home, I packed three more scones..lol...Earl Grace Concorn has a really good fragrance.The scones here seem to eat once in the incense...If the scone type is difficult to choose, the boss will also choose a menu!I think it's good to try it for the first time :)
원본: 안암에 이런 스콘 맛집이!! 종류많규 커피두 맛잇고 사장님도 좋아서 자주 갈듯, 번역: This scorn restaurant is in Anam!!There are many kinds of coffee, and the boss tastes good and the boss is good.
원본: 스콘이 맛있는 카페. 커피는 무난하고 아아보단 플랫화이트가 더 맛남. 스콘 종류가 다양하니 플레인만 먹지 말고 딴 것도 골라 먹어보길., 번역: A delicious cafe with scones.The coffee is okay and the flat white is more delicious than Ah.There are many types of scones, so don't just eat plains and choose something else.

 88%|████████▊ | 19780/22421 [01:20<00:46, 57.10it/s]

원본: 고기랑 우렁 된장도 맛있고 무엇보다 야채가 머무 싱싱해서 좋았습니다., 번역: The meat and miso are delicious, and most of all, the vegetables stayed fresh.

 89%|████████▊ | 19878/22421 [01:20<01:29, 28.50it/s]

원본: 이수역에서 가성비 좋은거 같아요. 쌈 종류가 신선해서 좋아요. 반찬들도 맛있어요., 번역: I think it's good at Isu Station.The kind of ssam is fresh.The side dishes are also delicious.

 89%|████████▊ | 19879/22421 [01:21<01:32, 27.54it/s]

원본: 쌈밥집답게 쌈채소가 정말 많이 나와요. 주변 주민들의 숨은 맛집 같네요. 다음엔 소불고기를 먹어볼 생각이에요. 반찬도 가짓수가 많아서 배부르게 먹고 왔어요. 가성비 짱!, 번역: Like Ssambap restaurant, there are so many ssam vegetables.It's like a hidden restaurant for the people around you.Next time, I'm going to eat beef bulgogi.The side dishes have a lot of money, so I ate it.Value!
원본: 음식은 기본은 하는 맛입니다. 밑반찬 많고 훌륭합니다.이 정도 가격에 양이나 맛이나 만족합니다. 그리고 주변 동네분들도 많이 오신 거 봐서 지역맛집인듯!재방문할 거 같아요~  추천드려요, 번역: Food is the basic taste.There are many side dishes and great.I am satisfied with the amount, the amount of the price.And it seems to be a local restaurant because you have seen a lot of people around you!I think I will return to visit ~ I recommend it.
원본: 다이닝코드 보고 집근처라서 처음 가봤네요 그냥 그냥 집근처 밥집 정도로 생각하면 될듯해요 저는 그냥 그랬던거 같아요, 번역: I've been to the dining code for the first time because it's near my house.
원본: 여기서만 파는 오리차돌박이는 한번도 안먹은 사람은 있어도 한번만 먹은 사람은 없는 전설의 메뉴드셔보시기를 강추합니다, 번역: It is recommended that there is a legendary menu that is not eaten here, but no one has eaten.
원본: 소박하고 아담한 식당이지만 사장님이 너무 친절하시고 가성비가 정말정말 좋은 맛집이예요! 직장인들이 점심먹기 딱 좋아요. 제육쌈밥과 부대찌개가 맛있어요 :), 번역: It's a simple and small restaurant, but the boss is so kind and the price is a really good restaurant!It is good for office workers to have lunch.The meat ssambap and the bag stew are delicious :)
원본: 맛좋고 가성비 좋은 쌈밥집. 다만 쌈장은 안주고 강된장만 주는게 좀 아쉬움, 번역: Good and good value for money.However, it is a pity to give only soybean paste without giving ssamjang.
원본: 맛도 양도 친절도 만족.좌식이라 불편할수도 있어요., 번역: Satisfaction with taste, amount, and kindness.It may be uncomfortable because it is sitting.
원본: 처음에 지인소개로 찾아가게되었는데 내용물이 신선하고 양도 푸짐한 편이여서 보통의 순대국집보다 비싸지만 만족하고 다녔는데 요샌 초심을 잃은듯 .... 양이 많이 줄었어요예전엔 포장도 해서 먹고 자주 먹으러갔는데 안가게 되네요, 번역: At first, I went to the introduction of acquaintances....The amount has been reduced a lot.
원본: 이수역 시장골목과 미샤골목 사이에 위치한 순대국집중 가장 유명하고 장사가 잘 되는 집. 순대국에 순대가 없어 당황. 들깨를 갈지않고 통으로 쓰는데 개인적으로 식감은 별로. 국물은 맛있으나.., 번역: The most famous and well -established house is located between Isu Station Market Alley and Missha Alley.There is no sundae in the sundae soup.I use it as a barrel without going to perilla.The soup is delicious..
원본: 고기 야들야들하고 맛잇어요. 냄새안나고 양도 푸짐해요!, 번역: It's delicious with meat.It doesn't smell and the amount is full!
원본: 맑은 국물에 양념장, 대창, 막창 등이 들어가있다. 통깨도 듬뿍.순대국이라고 돼있지만 사실 순대가 없다...!메뉴판을 보면 순대는 팔지 않음을 알 수 있다.그럼에도 불구하고 맛있다. 가게가 좁아서 많이 붐비는 편이다. 국밥에 술한잔 마시면 굿!, 번역: The clear broth contains sauce, Daechang, and Makchang.There is plenty of sesame seeds.It is said to be Sundae, but there is no sundae...!If you look at the menu, you can see that Sundae does not sell.Nevertheless, it is delicious.The shop is narrow, so it's crowded.If you have a drink in soup!
원본: 순댓국에 곱창이 들어가 있음. 예술임. 두명이서 순댓국에 머리고기(18,000) 먹으면 딱임. 머리고기 반드시 먹어야 함., 번역: There is a giblet in Sundaeguk.Art.It is perfect if you eat two people (18,000) in Sundaeguk.Hair meat must be eaten.
원본: 순대 없는 순대국밥. 내장 좋아하는 분들께 강추함. 섞어와 함께 소주 한잔하면 금상첨화임, 번역: Sundae soup without sundae.It is recommended for those who like the intestines.If you mix and have a glass of soju
원본: 양이 많지는 않아요 젤라또니까 정말 금방! 녹기도하고 하지만 맛있음, 번역: It's not a lot, it's a gelato, so it's really right!It is melted but delicious
원본: *콘이 컵보다 많이 줍니다*정량체크를 안하고 감으로 퍼주기때문에 많이 드시고 싶으면 콘으로 하세요.홍대매장은 AK신사옥 1층에 있는데 신규 매장이라 아주 깨끗하고 쾌적합니다.-이천쌀: 담백하고 쌀알(?)같은 곤약이 살짝 씹히며 달달합니다. 베스트 메뉴-솔티드카라멜초코: 단짠단이라 아주 자극적일 줄 알았는데 적당히 달달합니다. 이천쌀과 잘 어울립니다., 번역: Cone gives a lot more than a cup.The Hongdae store is located on the first floor of the AK new building, which is very clean and comfortable because it is a new store.Icheon Rice: The konjac, like a light and rice, is chewed slightly.Best Menu Salted Caramel Choco: I thought it would be very irritating because it was sweet.It goes well with Icheon rice.
원본: 젤라띠젤라띠~ 네이밍 센스가 느껴진다.웬만한 맛은 다 먹어봤는데.. 사실 기대하고 먹으면 그저 그런 맛이다.추천하고 싶은 맛은 이천쌀이랑 티라미수였으나 티라미수가 없어진 걸로 봐서 나름이 메뉴 개발을 계속 하고 계신듯 하다.원픽을 이천쌀로 하고 (쌀보다도..약간 코코넛 느낌.. 그런 맛이당) 나머지도 이천쌀로 하는게 좋다.샤벳종류는 기대 이하이고 다른 맛도 사실 그냥 그렇다. 사실상 젤라띠젤라띠는 이천쌀맛 아이스크림을 위해 존재하는 것이 아닐까??, 번역: Gelati Zelati ~ I can feel naming sense.I've eaten all the taste..In fact, if you look forward to eating, it's just that.The taste I would like to recommend was Icheon Rice and Tiramisu, but it seems that the tiramisu is gone.It's a good idea to make one pick with Icheon rice (than rice.The sherbet type is below expectations, and the other taste is actually just.Is it actually a gelatigelati for Icheon rice?
원본: 홍대와 상수의 중간쯤 위치해있고 근처 술집과 클럽이 많아 굉장히 시끄럽고 가게밖 주변이 약간 지저분함 자리가 협소하나 맛은 적당히 괜찮음 주변에 있으면 한번쯤 먹어볼만함, 번역: It is located in the middle of Hongdae and the constant, and there are many nearby pubs and clubs, so it is very noisy and the surrounding area outside the store is a bit messy, but the taste is moderately good.
원본: 쌀 아이스크림 녹차맛 아이스크림 강추합니다. 매장은 작지만 깔끔합니다., 번역: Rice ice cream green tea taste ice cream is recommended.The store is small but tidy.
원본: 맛잇는 젤라또~! ㅇ아이스크림 땡길때 먹으면 꿀맛입니당, 번역: Delicious gelato ~!ㅇ If you eat ice cream when you eat it, it tastes like honey
원본: 이천쌀맛 정말 맛있어요~_~새로 나온 그린티코코넛도 코코넛이 씹히는 게 재밌었어요, 번역: Icheon rice taste is really delicious ~ _ ~ It was fun to have coconuts chewing.
원본: 우리나라에 여기만한 젤라또집은 없는것같다 주변에 보이면 무조건 찾아가는 집, 번역: There seems to be no gelato restaurant in our country.
원본: 여기 몇년전에 처음만들어지고 어리숙한 남자사장님이 판매하길래 잘되려나했는데 먹어보고 대박날거라생각했습니다 아이스크림에 진짜 과일맛이납니다 ㅋㅋㅋ 혁신임 그리고 콘안에 초코넣어주는것도 핵꿀맛입니다 티비방송타고 리뉴얼하고 손님많아져서 제가다 기분좋습니다 비록 줄서야한다는 단점과 자리가 협소하여 앉아서 여유롭게 즐기긴 어렵지만..그래도 꿀맛탱이니 다들 꼭 가보시길 추천합니다, 번역: Here's the first time a few years ago and the foolish male boss sold it, but I thought it would be good to eat, but I thought it would be a big fruit.I feel good..Still, it's a honey taste, so everyone should go to it.
원본: 종류가 다양한 젤라또가 있고, 아스크림보다 맛있음. 이천쌀 추천., 번역: There are various types of gelatoes and are more delicious than As cream.Icheon Rice Recommended.
원본: 이천쌀이랑 티라미수맛이 제일 맛있다고 해서 그걸로 초이스!이천쌀맛에는 쌀알갱이같은게 들어가있고, 티라미수엔 작은 큐브빵이 들어있다 가격대는 좀 나가지만 쫄깃쫄깃하고 굿~ 확실히 젤라또라 일반 베스킨이나 나뚜루같은 곳의 아이스크림과는 다른 식감이다가끔 먹으면 좋을 맛, 번역: Icheon rice and tiramisu taste is the most delicious, so choice!Icheon rice tastes like a rice grain, and the tiramisu contains a small cube bread. The price is a little chewy but chewy and good ~
원본: 이천쌀이 제일 유명하다. 다른 메뉴들도 맛있고 가격도 다른 수제아이스크림에 비해 괜찮다.앉을곳이 별로 없다. 갈때마다 그냥 들고 먹어야한다, 번역: Icheon rice is the most famous.Other menus are delicious and the price is better than other handmade ice cream.There is not much place to sit.Every time you go, you have to eat it
원본: 맛은 있지만..처음 간 사람에게 스쿱 설명도 제대로 안해주고 말투도 불친절한..나이가 있는 사람에게는 눈길도 곱지 않은 집..몹시 기분 나쁨, 번역: It tastes good..It is unkind to the first person who did not explain it properly..A house that is not eye -catching for older people..Very bad mood
원본: 깔끔한 후식을원한다면 이곳으로단연 재료의 순수한 맛을 부드러운 느낌으로 바꿔서 내놓는 느낌개인적으로는 처음간다면 이천쌀 맛을아니라면 과일류가 들어간 맛을 추천한다, 번역: If you want a clean dessert, you can change the pure taste of the ingredients into a soft feeling, and if you don't have the taste of Icheon rice, I recommend a taste with fruits.
원본: 진리의 이천쌀, 내사랑 피스타치오❤️❤️ 그냥 지나칠 수 없는 맛 ㅠㅠㅠㅠ, 번역: Icheon rice of truth, my love pistachio ❤️❤️
원본: 한번 먹고나면 후식으로는 여기가 생각나게됨주변에서 저녁이나 술먹고 항상 들르게 되는 곳체인점을 늘렸으면 하는 곳, 번역: Once you eat it, you can think of this for dessert.
원본: 발렛비는  천원회냉면을 주문하고 육수를 마시니  속이 시원하고  면은 아주 좋은데, 함흥 냉면의  진수를 보게한다.오장동 흥남집이 휴일인 수요일 많이 북적이며 1, 2층이  만적 대기를 해야한다., 번역: Valetbi orders a thousand won cold noodles and drinks broth, so the inside is cool and the noodles are very good.Heungnam House, Ojang -dong, is very crowded on Wednesday, and the first and second floors should be full.
원본: 음식: 찐 함흥냉면은 처음 먹어보는데.. 오.. 평소에 함흥냉면이라 생각하고 먹어오던 것보다 훨씬 슴슴한 맛이라 재밌었습니다. 맛있네요. 다음엔 옆에 유명한 집도 가보고싶어졌어요.서비스: 친절하세요.분위기: 리모델링해서 밝고 깨끗하네요.위생상태: 깨끗합니다., 번역: Food: Steamed Hamheung Cold Noodles for the first time..oh..It was fun because it was much more tasty than I thought it was Hamheung cold noodles.It's delicious.Next time I wanted to go to the famous house next to it.Service: Be kind.Mood: It's bright and clean by remodeling.Hygiene: Clean.
원본: 회냉면 맛집으로 단연 일순위에 뽑힐 만하다.공간이 넓어서 대기를 오래하지 않아서 좋았고 음식도 금방 나오기 때문에 가볍게 먹고 나올 수 있어서 좋았다., 번역: It is a cold noodle restaurant.It was good because the space was large and the food was not long, and the food came out quickly, so it was good to be able to eat lightly.
원본: 미슐랭 가이드으도 나온 함흥냉면 맛집! 너무 맛있지만 한그릇 만천원 너무 비싸요ㅠ, 번역: Michelin Guide Udo Hamheung cold noodle restaurant!It's so delicious, but only a bowl is too expensive.
원본: 미슐랭 함흥냉면확실히 평냉집이랑은 다르게 어르신들 많음.맵지 않고 간장베이스?의 짠맛임. 맛있음., 번역: Michelin Hamheung cold noodles are definitely a lot of seniors.It's not spicy and soy sauce.Delicious.
원본: 저녁 시간 지나면 기본적으로 줄을 서야 하는 집. 맛은 평타 이상은 되지만, 굳이 줄 서서 먹어야 하는지는 의문이 들었네요. 하지만 금방금방 가게가 바뀌는 천호에서는 실패는 없을 집, 번역: A house that must be lined up after dinner.The taste is more than flat, but I wondered if I should eat it in line.However, in Cheonho, where the store is changing quickly, there is no failure.
원본: 음식은 대부분 맛있습니다. 그치만 몇몇 음식은 일본 현지 음식보다 제 입맛에 더 맞아서 맛있더라구요. 오코노미야끼는 개인적으로 일본에서 먹은것보다 괜찮았습니다. 촉촉하구 술안주로 제격이에요. 무엇보다 기본인주가 곤약메추리알장조림이구요. 꼬치구이는 직접 주인분께서 구워주시는데 버섯류가 일품입니다. 표고버섯 쯔쿠네와 같은게 참 맛있더라구요. 야채 별로 안좋아하는데 참 맛있게 먹었습니다. 야끼소바도 나쁘지 않구요. 스키야끼도 맛있습니다. 다만 간사이오뎅탕은 조금 일본식이라 입맛에 안맞을 수도 있어요. 그래두 한달에 한번씩은 꼭 가는 맛집입니다., 번역: Most of the food is delicious.However, some foods are delicious because it fits my tastes than Japanese food.Okonomiyaki was personally better than he had eaten in Japan.It is a moisturized and snack.Above all, the basic stock price konjac quail is stewed.Grilled skewers are baked by the owner and mushrooms are excellent.The same as shiitake mushrooms Tsukune is so delicious.I didn't like vegetables very much, but I ate it so much.Yakisoba is not bad either.Skiyaki is also delicious.However, Kansai Odentang is a little Japanese, so it may not suit your taste.Then it is a must -have restaurant once a month.
원본: 연아사시미는 양이좀 적고 대신 야끼소바가 푸짐하고 맛있어요음식나오는 시간이 좀 있어요분위기가 좋고 그렇게 시끄럽지않았어요데이트하기에 좋아요, 번역: Yuna Sashimi is a little small and instead of yakisoba is rich and delicious.
원본: 시키는 것마다 너무 맛있어요. 다만 양이 많지는 않아서 1차 배부르게 하고 간단히 2차하러 오기에 정말 좋아요., 번역: It's so delicious every time you let it.However, it is not so large that it is really good to make the first full and simply come to the second round.
원본: 가격이 싸보이지만 배고플 때 가지는 마세요. 오히려 더 비싼 감이 있어요. 가격이 싸지만 그만큼 양도 적어서요. 오히려 단품요리 시키는 곳보다 돈이 더 나와요. 대부분 맛은 있어요. 그래서 가끔 가는 곳.안주 많이 안먹거나, 2차로 가기 좋은 이자까야 ^^ 1차는 비추, 2차로는 추천 ^^, 번역: The price looks cheap, but don't go when you're hungry.Rather, it is more expensive.The price is cheap, but the amount is small.Rather, it costs more money than a separate dish.Most of them have a taste.So sometimes go.I don't eat a lot of snacks, or Izakaya is a good way to go to the second.
원본: 분위기는 좋구 술도 맛있는데 오꼬노미야키가 너무....제 취향이 아니었어요..양배추만 잔뜩..ㅜㅜ 꼬치들은 부추삼겹 치즈베이컨 명란 등등 먹었는데 부추삼겹빼고 다 맛있었어요 ㅎㅎ, 번역: The atmosphere is good and the alcohol is delicious, but Okanomiyaki is too....It wasn't my taste..Only a lot of cabbage..The skewers were eaten with leek chesty cheese bacon, but it was delicious except for leek pork.
원본: 자주 가는 집입니다. 저랑 제 친구는 술보다 식사하러 가는 것 같아요^^,,, 음식들이 다 맛있어요ㅠㅠ실패하는 메뉴가 없습니다, 번역: It is a often goes house.I think my friend and my friend are going to eat more than alcohol.
원본: 이집 찾아가는 건 조금은 힘드실수도 있으나 정말 맛있습니다. 가격도 저렴하구요 .시사모구이, 모듬꼬치,우설꼬치, 타코와사비하이볼, 자몽사케, 프로즌 기린생맥주 먹었어요여자친구가 자몽사케 정말 좋아했어요, 번역: It's a bit hard to go to this house, but it's really delicious.The price is also cheap.Sisa Moi, Assorted Skewers, Woo Sulki, Taco and Sabi High Ball, Grapefruit Sake, Frozen Giraffe Beer I ate.
원본: 서비스만 좋으면 더 완벽한 이자카야 천호동에 종종 가는 단골집소규모 모임에 최적화, 맛도 분위기도 좋음, 번역: If the service is good, it is optimized for the size of a regular parliamentary meeting in Cheonho -dong, which is more perfect if the service is good.
원본: 분위기 좋은데, 사람이 진짜 많아 시끄러워요~음식은 깔끔하고 맛있는데, 양이 좀 적습니다.1차로 배를 채우고 가심을 추천드립니다, 번역: The atmosphere is good, but there are a lot of people, so it's noisy ~ The food is clean and delicious, but the amount is a little small.I recommend filling the stomach for the first time and recommend it.
원본: 좀 지저분 어수선. 음식은 그리 나쁘진 않지만 정신없는 분위기가 저는 좀 별로라..., 번역: It's a bit messy.The food is not so bad, but I don't have a crazy atmosphere...
원본: 비린맛이 안나고 회가 다 신선하며 맛있었습니다. 비린맛이 나면 아예 못먹는데 여기 초밥은 다 잘먹었습니다., 번역: The fishy tastes and the sashimi were all fresh and delicious.I couldn't eat at all when it tasted fishy, but I ate all sushi.
원본: 은행골은 체인점이긴 하지만 이 지점이 유난히 더 맛있어요, 번역: The bank goal is a chain store, but this branch is exceptionally delicious.
원본: 스시가 다름 맛있음전통있는 집체인점이 아니라 실장들이 기술 가지고 운영한다고 함, 번역: Sushi is not a traditional collective point that is said to be operated by the heads of skills, not a traditional collective point.
원본: 얘들이 초밥이 먹고싶다 해서 큰맘 먹고 갔는더 초밥이 아주 끝내줬어요.. 혼마구로 대뱃살 완전 강추.. 가격은 쪼끔 부담되네요, 번역: They went to sushi because they wanted to eat sushi..Honmagu is full of fat..The price is burdensome
원본: 짱맛.. 우동 사이드 메뉴도 있으면 좋겠습니다! 초밥 하나는 정말 맛있어요👍🏻, 번역: Taste..I hope there is a udon side menu!One sushi is really delicious 👍🏻
원본: 일식집 느낌에 깔끔하고 가성비 좋은 곳입니다. 돈카츠는 셋트로 시키면 우동을 주는데 추가금액을 비교하면 돈카츠만 먹는게 좋을 듯 싶습니다. 가츠나베는 밥을 따로주는데 기호에 맞게 밥위에 올려서 먹으니 괜찮았습니다. 카레도 맵지 않고 맛있었다고 합니다., 번역: It is a neat and good place for a Japanese restaurant.Don Katsu gives you udon if you set it up, but if you compare the additional amount, it would be better to eat only Donkatsu.Katsunabe gave me rice separately, but it was okay to eat it on the rice to suit my preference.The curry was not spicy and delicious.
원본: 저는 진돈카츠, 와이프는 치즈돈카츠를 주문했습니다. 치돈은  치즈가 위에 덮여있는 형태이구요. 진돈카츠는 기름이 오래됬는지 모르겠으나 깔끔한 맛이 아니었습니다. 치돈이 그나마 치즈가 그 불쾌함을 잡아주어 먹을만했네요...고기식감도 그렇고 튀김상태도 그렇고 별로 추천드리고 싶지는 않습니다., 번역: I ordered Jindon Katsu and my wife ordered cheese pork.Chidon is a form of cheese covered on top.Jindon Katsu didn't know if it was oiled for a long time, but it wasn't clean.Chidon didn't eat the unpleasant cheese...I don't want to recommend the meat style and the tempura.
원본: 카레, 돈까스 맛있어요가쿠하이볼 맛있어요가성비좋아요, 번역: Curry, pork cutlet delicious yoga Kuhai Ball is delicious yoga
원본: 🦁샐바보단 스테이크가 더 만족물론 샐러드바도 나쁘진 않지만 회전율이 좋고 사람많을 때 와야 더 막 나온 음식들을 먹을 수 있다.스테이크 전맛탱 ㅎㅎ주차공간은 넉넉함., 번역: 🦁 Salvadan steak is more satisfied, and the salad bar is not bad, but the turnover rate is good and when there are many people, you can eat more foods.Steak -tank ㅎㅎ There is plenty of parking space.
원본: 공릉빕스 방문했구요 가격은 할인받아서싸게 다녀왔구 맛있습니다또가고싶어요, 번역: I visited Gongneung Bibs. The price was discounted and went cheap.
원본: 오랜만에 빕스 갔는데 맛있었어요고기도 질기지 않았어요 샐러드바는 먹을게 많진 않았지만 쏘쏘했어요, 번역: It's been a long time since I went to Bibs, but it was delicious.
원본: 8시 넘어서 방문했는데 매장에 손님은 3~4 테이블 정도 있었구요. 키오스크로 주문 후 대기시간은 10분 정도? 였어요. 정말 맛있었고 근처 분식집 간다면 무조건 여기 올듯. 튀김 어니언링이 특히나 맛났고 낱개로 어묵 시킬 수 있는것도 좋았어요^^, 번역: I visited after 8 o'clock, but there were 3 ~ 4 tables in the store.The waiting time after ordering with a kiosk is about 10 minutes?It was.It was really delicious and if you go to a nearby snack shop, it will come here.The fried onion was especially delicious, and it was good to be able to make fish cakes individually.
원본: 떡볶이의 신세계!! 너무 맛있어요. 다음에 가면 마늘 후레이크 꼭 추가해서 먹으려구요. 저 마늘이 별미더라구요! 손님 대부분이 어린 학생들이었는데, 그만큼 가성비가 좋아요! 마늘향이 은은하게 돌면서 매콤하고 쫄깃한 떡이 씹히는데.. 또 먹고 싶어요 ㅠㅠ 홍대 가면 또 찾고 싶을거 같아요, 번역: New world of Tteokbokki!!It's so delicious.Next time, I will add garlic flakes.That garlic is delicately!Most of the guests were young students, but the price is good!The garlic scent is soft and the spicy and chewy rice cake is chewed..I want to eat again ㅠㅠ I think I would like to find it again when I went to Hongdae
원본: 처음 먹고 정말 맛있어서 한동안 생각났던 홍대마늘떡볶이입니다.제가 마늘을 좋아해서 그런가 진짜 맛있었어요! 한동안 계속 생각날정도... 포장까지 비조리로 했었는데 집에서 조리하니 그 맛이 안나서 조금 아쉬웠습니다ㅠ 김밥도 큼지막하니 맛있었어요., 번역: This is the first time I ate and I was really delicious.It was really delicious because I like garlic!I keep thinking for a while...I didn't even pack the packaging, but it was a little unfortunate because it didn't taste like it.
원본: 오랜만에 떡볶이 흡입했다 큰 기대는 없이 마늘맛이 궁금해서 가봤는데 오... 괜찮다마늘향이 많이나는 라면국물같은 맛..! 조미료팍팍 들어갔을 것 같은 맛인데 그래서 맛있다 마늘은 일반적인 후레이크보다 훨씬 덜 튀겨져있고 더 두꺼운데 그래서 감자같은 식감도 살짝 느껴진다 너무 튀겨지거나 구워진 마늘은 살짝 쓴맛이나는데 이건 전혀 그런게 없어서 더 좋았음김밥은 통새우김밥으로 먹어봤는데 생각했던 것보다 훨씬 굵은 새우가 들어있어서 만족 타르타르소스랑도 잘 어울리고 새우식감도 탱글한데다 마성의 떡볶이국물에 찍어먹으니 최고인 거시다!!!다음에 올 땐 좀 여럿이와서 크림치즈김밥이랑 튀김도 같이 먹어봐야겠음 생각보다 맛있었던 덕볶이집., 번역: It's been a while since I was inhaled with tteokbokki...It's okay..!It's a seasoning, so it's delicious, so it's delicious. The garlic is much less fried than normal flakes and thicker, so it's a bit thicker.I tried it with gimbap, but it contains much thicker shrimp than I thought, so it goes well with the satisfaction tartarus, and the shrimp is tangled and eats it in the magical tteokbokki broth.!!The next time I come, I have to eat cream cheese gimbap and fries together.
원본: 좌석 간격이 매우 좁은편 이지만 마늘맛이 듬뿍나서 맛있다. 재방문의사있음, 번역: The seats are very narrow, but they have plenty of garlic.Re -vision intention
원본: 떡볶이는 밀떡이고 국물이랑 같이 떠먹는게 맛있어요김밥중엔 통새우살김밥이 맛있었고튀김은 약간 수련회급식에 나올것같은 스타일?먹고나면 종종 생각나는 곳입니다홍대점만 여러번 갔는데테이블간 간격이 아주 좁아서 불편한게 단점이고 갈때마다 대기줄 있었어요, 번역: Tteokbokki is a wheat rice cake, and it's delicious to eat with the soup. The styles that are likely to come out at the training recovery ceremony.There was a waiting line
원본: 굉장히 푸짐함 포장부탁드렸더니 흔쾌히 해주심 맛있게 매운 떡볶이에 마늘후레이크 너무 잘 어울림, 번역: I asked for a very rich packaging, but please be happy to do it.
원본: 소스가 진짜 특이하고 맛있는 떡볶이집. 튀김도 너무 바삭함, 번역: The sauce is a really unusual and delicious tteokbokki restaurant.Tempura is too crispy

 89%|████████▊ | 19879/22421 [01:40<01:32, 27.54it/s]

원본: 엽떡 달달버전?입니다.익숙한맛이에요.떡볶이양념맛이아니라 다른맛이에요.양이너무 많아서 질려서 못먹겠어요., 번역: This is the moon -tteok moon version.It's a familiar taste.Tteokbokki seasoning is not a different taste.I can't eat because I'm so tired.

 89%|████████▉ | 19954/22421 [01:40<02:38, 15.54it/s]

원본: 홍대 마늘 떡볶이ㄹ확장하고 생긴 자동주문 시스템이오히려 불편해요 맛은 너무 있어요, 번역: Hongdae Garlic Tteokbokki ㄹ It is uncomfortable with the automatic ordering system.

 89%|████████▉ | 19955/22421 [01:40<02:39, 15.42it/s]

원본: 맛잇어용 특히 김밥과 떡볶이 소스가 궁합이 잘 맞아용 튀김도 바삭!, 번역: It's delicious, especially gimbap and tteokbokki sauce.
원본: 여기 러쉬자리였나 그옆에였나 여튼 처음생겼을때 가보고 유레카였음 마늘덕후들이라면 환장함 약간 페리카나치킨 마늘맛에 끌리는분들이 좋아할만함 국물먹는게 핵꿀맛 그러나 이상하리만치 찾아가진않게됨, 번역: It was a rush place here or it was next to it, and it was the first time that it was Eureka.
원본: 마늘떡볶이, 튀김, 크림치즈김밥 다 맛있음 특히 김밥이 완전 맛있었음, 번역: Garlic Tteokbokki, Tempura, Cream Cheese Gimbap is delicious.
원본: 국물이 너무 인공적인 맛이났어요.. 떡도 국물이 안 배여서 따로노는 느낌.. 김밥은 맛있어요!!, 번역: The soup tasted so artificial..The rice cake is not soup, so it feels separately..Gimbap is delicious!!
원본: 줄길길래 30분 기다리고 먹었는데마늘면떡볶이  먹다가 마늘냄새가 코를 찌름모듬튀김은 먹을만함 특히 게살튀김, 만두튀김은 맛있음그냥 이런맛이 있구나하고 체험하기 좋은곳, 번역: I waited for 30 minutes and ate it, but I ate garlic rice cake.
원본: 가게가 너무 좁다는 것만 빼면 맛, 가격 모두에서는 최고, 번역: Except that the shop is too narrow, the best in both taste and price
원본: 3년간 홍대에서 먹어 본 떡볶이 중 최고!, 번역: The best of the tteokbokki I've eaten in Hongdae for 3 years!
원본: 맛찬들 또한 유명한 삼겹살집이지 않나 싶음. 오늘은 구로디지털쪽에 일이 있어 약속이 잡혔는데 처음 방문한 맛찬들 지점. 결과적으로 좋았음.담당 테이블 분께서 짬있는 분이어서 그런진 모르겠으나 친절하기도 하셨고 중간중간 말걸어 주시는 것들이 좋았음.연말이라서 회식하는 팀분들이 많았음에도 테이블 간격이 너무 붙지않아서 좋았고 술먹고 실수하는 분들도 안계셨음.고기 퀄리티야 두말할 것 없었고 직영점같이 좋은 고기 쓴것 같았음(직영점인지 체인점 인지는 모름). 세트메뉴도 있었는데 음료대신 맥주로 바꿔주기도 하셨으며(차액 요금 있음) 할인요금 폭 또한 있어서 만족했음.된장찌개 퀄리티도 좋았고 마늘기름장 요청 가능했으며 콩나물무침도 가져다 주셨음. 맛찬들 한번 들러봐야지 싶었는데 좋은 인상이 남아서 좋음. 장사 잘 되는곳은 체인점 여부인지와 상관없이 손님들의 재방문율이 높지 않을까 싶음. 이곳도 마찬가지., 번역: The taste is also a famous pork belly.Today, there was a job on Guro Digital side, so I had an appointment.As a result, it was good.I don't know if the table is in charge, but I was kind and I liked it.At the end of the year, there were a lot of teams who dinner, but the table was not too bad, and no one who made a drink and made a mistake.It was a meat quality, and it seemed to be a good meat like a retail store (I don't know if it's a retirement or a chain store).There was also a set menu, but he also changed it to beer instead of a drink (there was a difference rate).The quality of the miso stew was also good, the garlic oil was requested, and the bean sprouts were also brought.I wanted to stop by the taste, but it is good to have a good impression.The good place for business is that the return rate of the guests will be high regardless of whether it is a chain store.The same is true for this place.
원본: 14일 숙성고기! 부드럽고 맛있다 그리고 무엇보다 친절하고 반찬이 넘나 맛있어서 대만족했던곳!, 번역: 14 days aged meat!It was soft and delicious, and most of all kind and side dishes were so happy!
원본: 삼겹살 맛있어요!항상 사람이 많은 것 같아요 ㅎㅎ회식하는 모습들도 자주 볼 수 있어요, 번역: Pork belly is delicious!I think there are always a lot of people.
원본: 냉면이 의외로 맛있고 특히 비빔냉면이 삼겹살이랑 궁합이 최고예요!!, 번역: Cold noodles are surprisingly delicious, and especially bibimb cold noodles are the best with pork belly!!
원본: 최고다.. 돼지는 이래야된다 진짜맛있당 ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ, 번역: The best..Pigs have to be like this.
원본: 50년을 넘게 이어 온 용두동 터줏대감 용두동 노포 해장국집. 소고기 선지 해장국이라는 조금은 특별한 조합의 해장국.잘게 썰은 고기. 부드럽고 잡내없는 선지. 우거지와 콩나물의 조화. 약간은 맑은듯 하지만 진함이 있는 곰탕느낌의 육수.무엇하나 하찮게 생각할 수 없는 어머니대성집만의 조화로움이 참 좋다. 해장하러 가서 한 잔 더먹고 나오게 하는 해장국 어머니대성집. 싱싱하고 잘 양념 된 육회비빔밥 또한 별미.이전하며 조개젓이 없어진것과 가격이 비싸진것은 별로., 번역: Yongdu -dong, Daegam -dong, Yongdu -dong, and Haejangguk restaurant for over 50 years.Haejangguk of a little special union called Beef Prophecy Haejangguk.Finely chopped meat.Soft and no choice.Harmony of lugs and bean sprouts.It looks a bit clear, but the broth with a dark soup.The harmony of the mother Daesung House, which you can't think about, is very good.Haejangguk's mother Daesung House, who goes to eat one more drink.Fresh and well seasoned bibimbap is also delicious.It is not good that the shellfish is lost and the price is expensive.
원본: 수요미식회 방송 이후 자주찾는 식당. 재개발철거로 인해 10월말까지만 이곳에 운영하고 근처 다른곳으로 이전 한다고함.일반자극적인 해장국과는 정반대로 국물이 맑고 깊어서 부드럽게 속을 달래주는 음식., 번역: Restaurant frequently visited after a demand gourmet broadcast.Due to the demolition of redevelopment, it is operated here until the end of October and moved to another nearby.Contrary to the general stimulating Haejangguk, the soup is clear and deep, so it soothe the inside.
원본: - 간단후기위에 다른 분들이 써둔 평가는 정확합니다. 깔끔하고 깊은 맛의 해장국이 먹고 싶다면 강력히 추천합니다. - 한줄평가게: 깔끔 화장실: 깔끔음식: 깔끔- 총평모든 면에서 깔끔함이 느껴집니다. 만원짜리 해장국의 정석이라 표현하고 싶은 수준이며 소주와 매우 잘 어울립니다. 제가 방문했을땐 차량으로 찾아갔기 때문에 식사만 하고 나왔으나 이마저도 매우 만족하였습니다. 선지가 아주 신선하며 잡내 따위는 없습니다. 맑은 국물이지만 깊고 진한 맛을 원하신다면 꼭 방문 해보시길 추천합니다. 기본반찬은 사진과 같이 김치와 채짠지(무채) 가 나옵니다. 개인적으로 무채(?) 가 아주 해장국과 잘 어울려 맛있게 먹었습니다. 주차 공간은 있으나 넉넉하지 않습니다. 바로 앞이 큰길가인 관계로 길가에 주차는 할 수 없으니 차 없이 방문 하심이 정신건강에 이로울 것이라 여겨집니다.- 재방문 의사꼭 다시 찾아갈 예정, 번역: Simple later, the evaluation that other people wrote in the same period is correct.If you want to eat Haejangguk with a clean and deep taste, it is highly recommended.One -line section: Neat toilet: Clean Food: Neatly, I can feel neat.I want to express it as a craftsman of Haejangguk, and it goes very well with shochu.When I visited, I went to the car, so I only ate it, but I was very satisfied with this.The prophet is very fresh and there is no catch.It is a clear broth, but if you want a deep and rich taste, it is recommended to visit.The basic side dishes are kimchi and saltyji (radish) as shown in the picture.Personally, the radish (?) It went well with Haejangguk and ate deliciously.There is a parking space but not enough.Because it is a big road in front of you, you can't park on the side of the road, so visit without a car is considered to be beneficial to mental health.I will definitely go back to the doctor
원본: 재개발로 주소가 서울 동대문구 용두동 232-24로 옮겨졌습니다너무 뜨겁지 않은 적당한 온도로 토렴된 국밥은 선지와 고기가 푸짐하게 들어가 있고, 무채와 조화가 상당히 좋습니다기존 해장국 보통 8,000원 없어지고해장국 10,000원 으로 통합된건 좀 서운하네요, 번역: Redevelopment has been moved to 232 Yongdu -dong, Dongdaemun -gu, Seoul.I'm a little sad
원본: ※ 용두동에 위치한 유명한 해장국집입니다.용두동 조금 안쪽에 있던 어머니 대성집이  재개발을 하면서 길가 쪽으로  이전했습니다. 보니까 예전 간판도 가져와서 달아놨습니다. 이전한 후에는 접근성이 좋아지긴 했지만 가격이 또 올라서 이제 해장국 한 그릇에 만 원이 되었습니다. 식사를 했던 1층엔 테이블이 넷 정도 밖에 없었지만 위로 올라가면 자리가 꽤 있는 거 같았습니다.  해장국을 시켜보니 장사 잘 되는 집 특유의 속도로 찬이 깔리고 음식이 나옵니다. 항상 생각하지만 정말 빠릅니다. 맛을 보니 안에는 선지와 야채, 고기가 섭섭지 않게 들어있습니다. 선지의 상태는 아주 좋은 편입니다. 국물의 간은 조금 센 편이고 조미료맛도 생각보다 강하지만 전체적으로 지나치게 짜지 않은 수준에서 밸런스가 좋습니다. 밥알도 질척하지 않게 잘 토렴되어 있어서 밥알이 살아있다는 표현이 어울립니다. 반찬으로는 김치와 석박지, 그리고 무생채가 나오는데 무생채가 시원달달하면서 해장국의 짠 맛을 잘 잡아줍니다. 김치와 석박지는 직접 담근 거 같긴 하나 맛은 평범합니다. 워낙 유명한 집이라 그런지 식사시간을 약간 비낀 시간에도 손님이 끊임없이 들고 있었고 먹는 김에 포장도 하는 손님이 제법 있었습니다.해장국 맛은 보편적인 취향에 맞는 맛이고 이전 후에는 인테리어나 위생면에서도 흠잡을 곳이 없는 식당입니다. 이미 유명한 집이고 업력 또한 오래되었기 때문에 앞으로도 부근에는 견줄만한 가게가 나오기 어려울 거 같습니다. 1층 이모님이 나긋나긋한 톤으로 서빙을 하고 계셨는데 이런 바쁜 가게에선 좀처럼 받기 어려운 친절한 서빙이었습니다.가게 자체의 주차장엔 두 대, 그리고 가게를 따라서 또 몇 대의 주차가 가능하긴 합니다만 식사시간에는 주차하기가 만만치 않아 보였습니다., 번역: ※ This is a famous Haejangguk restaurant located in Yongdu -dong.The mother Daesung House, which was a little inside Yongdu -dong, moved to the side of the road while redevelopment.I also brought the old sign and put it on.After the relocation, the accessibility improved, but the price rose again, and now it is 10,000 won for a bowl of Haejangguk.There were only about four tables on the first floor where I ate, but when I went up, there was a lot of seats.Haejangguk is made at the peculiar speed of the house and the food comes out.I always think, but it's really fast.The taste shows that the prophets, vegetables, and meat are not stumbled inside.The condition of the prophet is very good.The liver of the broth is a little strong and the seasoning taste is stronger than I thought, but the overall balance is well balanced.The rice eggs are so good that the rice is alive, so the expression is alive.The side dishes include kimchi, master's paper, and nothing.Kimchi and doctor's grounds seem to be soaked in person, but the taste is plain.It was so famous that the guest was holding a constant time even when it was a bit of a meal.Haejangguk tastes like a universal taste and is a restaurant that has no flaw in interior or hygiene after the previous.It is already a famous house and the company is also old, so it will be difficult to see a store comparable to nearby.The first floor aunt was serving in a lax tone, and it was a kind serving that was hard to receive in these busy shops.The parking lot of the store itself is possible to park two and several parking, but it was not easy to park during the meal time.
원본: 새벽에 술을 먹다가 택시타고 대성집 해장국을 먹으러 이동했다. 해장국은 고기도 넉넉히 찢어 넣고 우거지가 큼지막하게 들어 있는게 술안주로도 일품이었다. 지인이 굳이 그 늦은 시간 택시까지 타고 가려했던 이유를 알았다., 번역: After drinking at dawn, I took a taxi to eat Daesung Haejangguk.Haejangguk torn plenty of meats and had a lot of bouquets.I knew why an acquaintance tried to take the late taxi.
원본: 서울 출장을 갔을 때, 점심을 먹어야겠기에 직장 선배님께서 폭풍검색을 하고 찾아간 어머니대성집..​알고보니 개그맨 신동엽씨의 단골 해장국집으로 유명하다고 한다.​주당들이 맞다면 그 집은 맞는 것이다..ㅎㅎ​1967년부터 이 자리에서 영업을 하셨다니깐 무려 50년이 넘은 노포이다.​그런데, 지금은 재개발로 인해 대로변으로 옮겨 재오픈 했다는 것을 블로그를 통해 알 수 있었다.그동안 수많은 해장국들을 먹어봤지만, 어머니대성집의 해장국은 상상을 초월했다.​비주얼부터도 달랐고 우거지와 고기 및 선지, 콩나물과 밥 등이 들어있는 맑은 국물의 해장국은 정말이지 대박 맛있었다.​같이 나오는 조개젓 또한 인상깊은 맛이었고..​이 해장국을 먹고 싶을 때 먹을 수 있는 동네 사람들은 얼마나 행복할까 하는 생각도 들었다.​같이 갔던 일행 4분을 한 방에 만족시켜버렸다는..​한줄평 : 꼭 한 번 다시가서 맛보고 싶은 집.., 번역: When I went to Seoul, I had to have lunch, so my mother's house was searched for a storm..It turns out that it is famous as a regular haejangguk house of gagman Shin Dong -yeop.If the weekly party is right, the house is right..ㅎㅎ Since 1967, you have been in business here for more than 50 years.However, it was possible to see the blog that the redevelopment was moved to the side of the street and reopened.I have eaten a lot of haejangguk, but the Haejangguk of the mother Daesung House has been beyond imagination.It was different from the visuals, and the Haejangguk of the clear broth containing the bugs, meat and prophets, bean sprouts and rice was really amazing.The shellfish that came together was also impressive..When I wanted to eat this haejangguk, I thought how happy people could eat.I satisfied four minutes of the party in one room..One line comment: I want to go back and taste..
원본: 나름 집근처인데 찾아가기 어려워서 못가고 잇다가 방문햇는데 진짜 해장하러 갓다가 술 마셧어요...육회는 나중에 비빔밥으로 먹고 싶고 수육은 진짜 기가막혀요 너무 맛일어요 ㅠㅠ 해장국은 왜 2인 1해장국햇나 후회되요 ㅠㅠㅠ, 번역: It's near my house, but it's hard to visit, so I visited it...The sixth sashimi later wants to eat with bibimbap and the meat is really amazing.
원본: 사장님과 일하시는 분들 대체적으로 친절하심.20~60세대가 어우러지는 수육, 해장국 맛집으로본연의 재료 맛과 간이 잘되어서 자주 방문하는 집.주변 지인들에게 꼭 한번은 추천하는 용두동 맛집입니다가성비 좋은 집은 아니나..., 번역: Those who work with the boss are generally kind.20 ~ 60 households are combined with soup and Haejangguk restaurant.It is a good place to be a good place to be a good place for the acquaintances...
원본: 해장국은 당연히 맛있고 수육 진짜 부드러워요!! 고기 안좋아하는데 폭풍흡입...다진 고추도 주시는데 매운거 좋아하면 넣어먹으면 돼요!술이랑 먹다보니까 나중에 국물이 부족해서 국물 조금만 더 주실수 있냐고 여쭤봤더니 새 그릇에 고기까지 더 주시더라구요ㅠㅠ사장님 엄청 친절하시고 뭐 부족한거 있는지 계속 살피시더라구여추천 합니당 맛있어요! 수육 특히 짱!, 번역: Haejangguk is, of course, delicious and sour pork is really soft!!I don't like meat but storm suction...I also give you chopped peppers, but if you like spicy, you can eat it!When I was drinking with alcohol, I asked if I could give me a little more broth, so I gave you more meat in a new bowl.Sourced, especially good!
원본: 용두동 해장국 맛집. 고기랑 선지가 푸짐하게 들어있고 국물도 아주진하고 맛있어요., 번역: Yongdu -dong Haejangguk restaurant.The meat and the prophets are rich and the broth is very delicious and delicious.
원본: 정말 가보고싶었던 국밥집인데 기대가 커서 그런지 조금 실망함. 우선 밥이 기본으로 말려나오다보니 국물양이 넘 적게 느껴졌고 따뜻함이 덜했으며 고기가 질겼다. 선지는 맛있었다., 번역: I really wanted to go, but I was a little disappointed because it was high.First of all, when the rice was dried up, I felt less soup, the warmth was less, and the meat was tough.The sun was delicious.
원본: A deep taste of 해장국 that kept its tradition for a while. Such taste is very specific to this place however, it may not be suitable for everyone as the taste of the cows blood can be extremely rich and almost pungent., 번역: A Deep Taste of Haejangguk That KEPT ITS Tradition for a while.Such Taste is very specific to this place However
원본: 선지해장국 맛집입니다. 선지가 잡내없이 신선합니다. 국물도 진하고 우거지도 좋습니다. 다만 고기는 약간 질겨요., 번역: It is a restaurant in the Seonji Haejangguk.The prophet is fresh without catching.The broth is also rich and good.But the meat is a bit tough.
원본: 집 근처라 자주가는 맛집입니다. 워낙 유명하고 맛있는 집이에요. 친구들이랑 술 마시기 좋아요. 술 엄청 잘 들어가요. 추천 메뉴는 모듬수육 입니다. 가격은 비싼편이에요., 번역: It is a restaurant that is often near the house.It's a famous and delicious house.It's good to drink with friends.Alcohol is very good.Recommended menu is assorted meat.The price is expensive.
원본: 일하다가 오랜만에 찾은 대성집 오랜만에찾아도옛날맛 그대로입니다, 번역: It's been a long time since I worked for a long time.
원본: 해장국: 조미료 맛이 나지 않는 해장국. 이런 맛의 해장국은 접해본 적이 없다. 조미료 맛에 익숙한 분이라면 만족도가 높지 않을 수 있겠다. 깔끔하고 시원하다. 연세가 꽤 되어보이는 할머니들이 서빙하신다., 번역: Haejangguk: Haejangguk does not taste seasoning.Haejangguk of this taste has never been encountered.If you are familiar with seasonings, you may not be satisfied.Clean and cool.Grandmothers who look quite old are serving.
원본: 13살부터(지금은 44살) 약수터 다니면서먹던 꾸준히 변함없는 맛입니다. 다만 가격이 많이 비싸졌습니다, 번역: From the age of 13 (44 years old), it's a steady taste that I've eaten.But the price is very expensive
원본: 원래 선지를 좋아하지않는데 해장국에 들어간 선지를 맛있다 생각하면서 먹을 수 있었다 국물도 훌륭했다, 번역: I didn't like the original paper, but I was able to eat while thinking about the prophets in Haejangguk.
원본: 어쩌다가 얘기듣고 찾아가봤는데, 꽤 찾기 어려운곳에 있었음에도 불구하고 괜찮은 편이었다., 번역: Somehow I heard about it and went to it, but it was okay despite being in a very difficult place.
원본: 선지해장국에 소고기가 들어가있어 맛있어요육회는 소고기 품질이 아주 좋아 맛도 좋아요, 번역: The beef is delicious because it contains beef in the soup.
원본: 어렸을때부터 다니던 집. 해장국 국물 최고죠... 추천합니다., 번역: I have been to a house since I was young.Haejangguk soup is the best...I recommend it.
원본: ㅇㅅㅇb, 번역: ㅇㅅㅇ b
원본: 국물 진하고 고기 짱짱 많이 들어서 한그릇만으로 배빵빵!! 김치도 맛있었어요, 번역: The broth is rich and the meat is great.!Kimchi was also delicious
원본: 음식 가격 모드 맘에 든다.직원분들도 모두 친절하며 맛도 좋다진정한 서민음식인 순댓국을 파는곳이라 할 수 있다, 번역: I like the food price mode.The staff are also friendly and tastes good.
원본: 순대국이 뭐다그게그거겠지만 맛있고 양이 말이안댑니다 진짜 추천, 번역: Sundae soup is something that's what it is, but it's delicious and the sheep are not words. Really recommended
원본: 사골베이스 육수라 깔끔한맛이 강함. 순대자체의 맛은 지극히평범. 머릿고기또한 평범. 오징어순대는 그냥 질척한 동그랑땡과 오징어를 같이먹는느낌 .., 번역: The beef bone bass broth has a strong taste.The taste of Sundae itself is extremely ordinary.Head meat is also plain.Squid sundae just feels like eating round and squid together..
원본: 맛있어요 식당도 넓어서 혼밥하기도 눈치 안보여요 국물 땡길때 오기 좋아요, 번역: It's delicious. The restaurant is spacious, so I can't even notice it.
원본: 순대국 맛있습니다. 깊은 국물과 알찬 고기를 맛볼 수 있습니다, 번역: Sundae soup is delicious.You can taste deep broth and rich meat
원본: 맛있는데 가격이 좀 올랐네요 그래도 역시 본순대국입니다., 번역: It's delicious, but the price is a bit rising.
원본: 맛있음~ 오징어 순대는 별로, 번역: Delicious ~ Squid Sundae is not good
원본: 점심시간에 고갈비구이세트하고 제육볶음세트 먹었습니다. 1인당 7천원입니다. 가격 좋습니다.닭갈비도 많이 드십니다., 번역: During lunch time, I ate grilled ribs and stir -fried meat.7,000 won per person.The price is good.He also eats a lot of chicken ribs.
원본: 커리 종류도 다양하고 특히나 난이 맛있어요. 잘 구워 주셔서 좋고 점심 할인도 되고 무려 리필도 있으니 좋에요, 번역: There are many kinds of curry, and especially Nan is delicious.It is good to bake well, lunch discount, and refills.
원본: 평소에 베나레스 커리집 좋아하는데여기도 너무 맛있다!!, 번역: I usually like Benares Curry House, but it's so delicious here!!
원본: 커리 종류가 정말 다양합니다.런치때는 사람이 가득찰 정도로 인기가 많고커리 주문시 밥은 무료제공입니다., 번역: There are so many kinds of curry.When lunch, it is so popular that people are filled with people, and rice is free when ordering.
원본: 언제먹어도 맛있는 치킨마크니 향신료 강하지 않고 깔끔하고 맛있어요, 번역: It's not strong and delicious, it's delicious and delicious when you eat it anytime
원본: #맛 보쌈 누린내도 안나고 누린내를 없애려고 넣은 다른 향신료?맛도 안나고 엄청 담백함굴도 싱싱함#서비스 및 분위기 시끌벅적협소#장점 맛#단점 웨이팅이 너어어어어무 길다#한줄평딱 오픈할때 뛰어가면 너무 맛있게 먹을수있음, 번역: #The other spices that I don't have to get rid of the flavored bossam?Eatable
원본: 4월이라 간재비보쌈으로 먹엇는데 느무 맛잇엇어요. 해물순두부도 너무 맵지 않고 깔끔하고요. 맥주는 카스밖에 없어서 아쉬웟어요 ㅋㅋㅋ, 번역: It's April, so I ate it as a boss.Seafood soft tofu is not too spicy.I was sorry that the beer was only Cas hahaha
원본: 5시에 가서 먹었다 줄서는 맛집이고 지금 굴 철이라 굴보쌈 존맛탱 굴전 기절한다., 번역: I went to 5 o'clock and ate it.
원본: 서울대입구역에서 나름 유명한 외래향입니다. 주말에는 점심특선코스를 2만5천원에 즐길 수 있습니다. 3품냉채, 팔보채, 깐풍기, 깐쇼새우, 탕수육, 식사, 후식까지... 가성비로는 감히 따라올 중식당이 없다고 생각합니다... 가격대비 맛과 양이 매우 훌륭합니다. 다만 손님이 붐비는 시간대에 방문하면 서빙하시는 분들도 바쁘셔서 서비스가 살짝 아쉬울 때도 있습니다. (가위 요청시 여러번 말해야 한다던지... 후식이 안나온다던지... 포장요청시 여러번 말해야 한다던지...) 일부러 그러시는거 같지는 않고 말 그대로 바빠서 응대가 힘드신것 같습니다. 그래서 왠만하면 주말 점심시간 이후(1시 이후) 방문하는 편입니다.  2만 5천원에 다양한 음식을 배부르게 먹고 싶으시다면 주말 점심 (2시 반이전) 방문 추천드립니다. ~!!, 번역: It is a famous foreign scent in Seoul National University.On weekends, you can enjoy lunch special courses for 25,000 won.Three products, arms, kanpungi, kansho shrimp, sweet and sour pork, meals, desserts...I think there is no Chinese restaurant that will dare to follow the price...The taste and amount are very good for the price.However, when you visit the crowded time, even those who serve are busy, so the service is a bit disappointing.(I have to say many times when I ask for a scissors.... ..I have to say many times when I request a packaging.) I don't think it's like that.So I visit after the weekend lunch time (after 1 o'clock).If you want to eat a variety of foods for 25,000 won, we recommend a weekend lunch (2:30).~!!
원본: 서울대입구에서 오래된 맛집이에요예전에 일층이였는데 장사잘되어서 확장했어요자주가는데 요즘은 일하시는분들이 좀 늦은대응하셔요;;; 부탁드리면 다른테이블 다돌고와서 대응해준다던지 예전엔안그랬는데한두분이 그런게 아니에요, 번역: It was an old restaurant in Seoul University, but it was the first floor, but it was expanded because it was good.If you would like to ask you to come back and respond to another table, but it was not like that.
원본: 절대로 제 돈 주고 가진 않지만(너무 비싸서) 교수님이 사준다면 항상 가는 곳 ^_^ 맛있어요, 번역: I never pay my money, but if you buy it, it's always going to go.
원본: 내부도 너무 깔끔했고 음식 맛도 너무 좋았어요. 가격대비 양도 많았고 특히 직원분께서 짜사이랑 단무지가 떨어지기전에 리필해주셔서 너무 편하게 먹었습니다!, 번역: The inside was so clean and the food was so good.There was a lot of price for the price, especially the staff refilled it before the radish and the radish fell.
원본: 손님이 많아서 대기가 필요합니다. 외래향 탕수육이 유명하고 맛있습니다., 번역: There are many guests, so you need a waiting.Outpatient sweet and sour pork is famous and delicious.
원본: 가게 이전하기전에는 탕수육이 이런맛이 아니었는데 너무너무 맛이 없어졌네요...주문하자마자 나오는걸보니 대충 튀겨놨던거 다시튀겨서 나오는것같고 튀김옷이 넘나 딱딱하네요 게다가 튀김옷이 군데군데 탄자국이 있어요...하....이집 탕수육 다시는 안먹을듯 자주 갔었는데 실망입니다, 번역: Before I moved to the store, sweet and sour pork didn't taste like this, but the taste was so tasty...As soon as I ordered it, it seemed to be fried again, and the fried clothes were so hard...under....I went to this house often as if I would never eat again, but I'm disappointed.
원본: 잔뜩 기대하고 갔는데 생각보다 별로였음외래향 탕수육에 삼선짬뽕 흑미 볶음밥을 주문해서 먹었는데탕수육은 어디서나 먹을수 있는 맛이었고짬뽕은 국물만 뻘겋고 해산물이 너무 적어서 실망이고복음밥은 짜장 소스도 주지 않고.. 종업원더러 좀 달라고 그랬더니 짜장면을 안시켜서 못준대.종업원이 너무 불친절..완전 개무시 당한 느낌 하여튼 그랬음, 번역: It was a lot of expectation than I thought, but I ordered a three -line champon black rice fried rice in the outfit sweet and sour pork..I asked for some employees, but I couldn't give me jjajangmyeon.The employee is too unkind..I felt like it was completely open
원본: 니뽕내뽕 암사점🍜매번 가던곳만 가다가 처음으로 암사점 방문했네요ㅎㅎ 먹어보고싶었어요. 3단계 제일 매운 단계인데 많이맵지않아요~~ 체인점이라도 니뽕내뽕은 약간씩 맛이 다 달라요. 오징어 홍합 해산물 양도 많았어요.재방문의사 100프로 직원분도 친절하세요!, 번역: Nippon Nakmong Amsa Branch 🍜 I only went to Amsa Branch for the first time.It's the 3rd spicy stage, but it's not very spicy ~~ Even in a chain store, Nipong Nakpong is a little different.There was also a lot of squid mussels.Return to 100 % staff is also kind!
원본: 니뽕내뽕 암사점 다녀왔어요매장이 크고 깔끔해서 자주가고싶어요, 번역: I went to Nippon Nakmong Amsa Branch.
원본: 주차 가능해요매장 넓고 쾌적해요아가의자 준비되어있어요맛있어요, 번역: It is possible to park. The store is wide and comfortable.
원본: 가성비 아주 좋은 음식이네요 로제짬뽕을 먹었는데 국물맛이 정말 맘에 드네요 얼큰하면서도 부드럽고 전혀 느끼하지 않았어요, 번역: It's a very good food.
원본: 크뽕이랑 고구마피자 조합 너무 좋아요. 종종 친구들이랑 가는데 갈 때마다 직원들이 친절해요, 번역: I love the combination of bumpon and sweet potato pizza.I often go with my friends, but every time I go, the staff are kind.

 89%|████████▉ | 20044/22421 [02:01<04:09,  9.52it/s]

원본: 가격이 살짝 있었지만 랍스타라는 점 고려하면 푸짐하고 배부르게 먹을 수 있었어요! 맛도 괜찮았어요 넓어서 그런지 대기가 있긴 했는데 금방 자리 빠져서 오래기다리지 않았어요~, 번역: The price was a bit, but considering that it was a lobster!The taste was fine. It was so wide that I had a waiting, but I didn't have a long time.
원본: 나쁘지 않았어요. 맛도 괜찮고 직원분들 친절하고. 근데 세계 1위 피자 셰프라는 타이틀 걸기엔 조금...평범? 하지 않나 싶습니다., 번역: It wasn't bad.The taste is good and the staff are kind.But the world's No. 1 pizza chef is a bit title...common?I want to.
원본: 음식은 맛있는 편이고, 양도 넉넉했어요. 대신 가격은 좀 있는 편인데 데이트나 기념일, 가족 외식할때 가볼만한 곳이에요~, 번역: The food was delicious and the amount was plenty.Instead, the price is a little bit, but it's worth a visit when dating, anniversary, and family eating out.
원본: 직원분들 친절하고 가게 내부도 넓고 음식도 맛있긴한데, 가격대가 엄청 세요, 번역: The staff are friendly, the inside of the store is wide and the food is delicious, but the price range is huge.
원본: 서울의 3대 피자집이라고 함. 전통 이탈리아식 피자, 1인1피자가 적당한듯..(?), 번역: It is said to be the three largest pizza restaurants in Seoul.Traditional Italian pizza seems to be suitable for one person..(?)
원본: 이탈리아 피자로 유명해서 대기 줄 길어요로제파스타 맛나요피자는 보통요, 번역: It is famous for Italian pizza, so the waiting line is long.
원본: 1. 두시 조금 넘은 시간에 매장에 방문 했는데 먼저 인기척을 내기 전까진 손님이 온지 모르시더라고요.2. 첨부된 사진 보시면 아시겠지만 베이컨이 떨어지지도 않은채 조리되서 서빙됬습니다. 맛에 큰 영향을 주지는 않지만 한 접시에 만원 후반대인 파스타가 보여줘야하는 완성도는 아닌것 같습니다.3. 양은 많았습니다. 일반적인 파스타집에 비교하면 한 접시에 1.5인분 정도 하는 것 같습니다.다이닝코드에서 혜화 검색하면 가장 먼저 나오는 식당인데 서비스 측면에서나 음식 맛,완성도에서 별로 추천드리고 싶은 음식점은 아닙니다. 일년 반정도 전에 가족끼리 방문하고 괜찮았던 기억이 있어서 오랜만에 친구들과 방문했는데 이번에는 썩 좋은 인상으로 기억되는 집은 아니네요.피자가 유명한 집에가서 파스타만 먹고 왔지만 다음에 방문할 기회가 있다면 파스타보단 피자를 먹어보겠습니다., 번역: 1. I visited the store in a little over two o'clock, but I didn't know if a guest came until I first got popular.2. As you can see from the attached photo, it was served because it was cooked without the bacon.It doesn't have a big impact on the taste, but it doesn't seem to be the perfection that Pasta, which is the second half of 10,000 won, should show.3. The amount was large.Compared to a typical pasta house, it seems to be about 5 servings per plate.If you search Hyehwa in the dining code, it is the first restaurant that comes out.I visited my family for about a year and a half a year ago, so I visited with my friends for a long time.I have been to the famous house and eat only pasta, but if you have a chance to visit the next time, let's eat pizza rather than pasta.
원본: 친절도 : 매우 친절함맛 : 준수함양 : 매우 많음재방문 의사 : 있음, 번역: Kindness: Very Friendly Taste: Compliance: Very many visits:
원본: 양이 많다고 하는데 적음 맛도 잘 모르겠음 사람이 많아서 시끄러움 그냥 페밀리 레스토랑 느낌, 번역: It's a lot of sheep, but I don't know the little taste.
원본: 음식 양이 짱 많음, 직접만든 스트로베리 음료, 화덕피자 짱 맛나요, 까르보나라 양 많음, 번역: The amount of food is so great, the homemade strawberry drink, the oven pizza -chan tastes good, the amount of Carbonara
원본: 양이 진짜 많아요!The pizza and salad is recommended.One more thing, do not forget ordering grapefruit ade.When u go to 대학로 for watching 연극, u can eat here., 번역: There is a lot of quantity!The Pizza and Salad is recommended.One more thing, do not forget ordering grapefruit ade.When U Go To University for Watching, U Can Eat Here.
원본: 학생이라 가격때문에 자주는 못가고 가끔 가서 먹습니다.이름이 기억안나지만 항상 샐러드피자에 새우로제파스타 먹고오는데진짜 맛있어요그런데 저번에 샐러드피자에서 초록애벌레가 나왔습니다유기농 채소라 벌레 제거하는데도 가끔 나온다 하군요다른 피자로 교환해주셨는데개인적으로 정말 맛집인데 다음번에 방문할수있을지 의문이네요.., 번역: I'm a student, so I can't go often because of the price.I don't remember the name, but it's always delicious to eat a shrimp with a salad pizza.It's a question..
원본: 여기가 막 극찬할 정도의 맛인가 싶은데 맛있고 꽤 맛있는데 정말 맛있다 수준까지는? 음료도 어디선가 먹어봤는데 설마 여기가 원조인가루꼴라 팍팍 얹는 스타일 좀 세상에서 사라졌으면 하는데 그게 본고장 스타일인가 안사라지는거 보면 나올때 풍성한거 말고 좋은게 뭔지, 번역: I want to taste it here, but it's delicious and pretty delicious.I've eaten the drink somewhere, but I hope this is a way from the world that's the original Jakjiru Colla Pak.
원본: 음식 정말 맛있습니다. 서비스도 상당히 친절하시고요.가격이 조금 있긴 하지만 이 정도의 맛과 서비스면 적절하다고 생각됩니다. 까르보나라를 꼭! 드셔보시길., 번역: The food is really delicious.The service is also very friendly.Although the price is a bit, I think this taste and service are appropriate.Carbonara!Please try it.
원본: 남친이랑 주소보고 찿은데 인데 양이 푸짐해서 다먹지도 못하고 나옴, 번역: I was looking at the address with my boyfriend, but the sheep were so large that they couldn't eat everything.
원본: 랍스타피자, 리코타치즈샐러드, 로제파스타 먹었습니다. 랍스타피자는 기대보단 별로였습니다. 랍스타 외 토핑이 거의 없습니다.리코타치즈 샐러드와 로제파스타는 맛있었습니다., 번역: I ate lobster pizza, ricotta cheese salad, Rose pasta.Lobksta Pizza was not as expected.There are few toppings other than lobster.Ricotta cheese salad and Rose pasta were delicious.
원본: ''돌체''라는 초콜렛피자가 굿이였습니다.분위기도 좋고 채광도 잘 되는 곳이라 음식사진이나 인물사진도 예쁘게 찍히더라구요ㅎㅎ, 번역: The chocolate pizza called `` Dolce '' was good.The atmosphere is good and the mining is good, so the food photos and portraits are also beautiful.
원본: 자초코피자 먹었는데 일단 비쥬얼은 최고~맛은 초코가 들어있어 느끼할 거라고 생각했는데 오히려 일반 피자보다 깔끔하고 맛있었는듯~, 번역: I ate my own nose pizza, but I thought it would feel because the visuals are the best ~ The taste is in chocolate, but it was clean and delicious than regular pizza ~
원본: 진짜 맛있어요!! 마가리타피자랑 샐러드먹었는데 맛이 깔끔하고 진짜 취저었어요!, 번역: It's really delicious!!I ate Magarita Tapie Salad, but it tasted clean and really drunk!
원본: 불광역 근처에 있는 오리집인데 정식 명칭은‘이창연의 능이마을’ 이라고 적혀있어요~ 능이마을 이라는 상호가 많은데 여기는 다른데 인거 같네요뭔가 가족회식이나 어르신들 등산 후 식사하시기 딱 좋은거 같은곳 이에요. 일단 기본 반찬들이 너무 괜찮아요 찰밥도 나오는데 오리랑 김이랑 같이 싸먹을 수 있어서 좋고 김치도 좋아하는 새김치였어요~ 콘옥수수는 맛이 없을수가 없구요^^국물도 진하고 능이도 푸짐하게 들어있어요.오리도 살이 부드럽고 푸짐했구요.. 반마리인데도 양이 많았어요~ 다리도 2개 들어있어서 마음에도 들었구여. 다 먹고 칼국수도 넣어서 먹을수 있게 주셨는데 정말 둘이서 먹기 배불렀어요!, 번역: It's a duck house near Bulgwang Station, but the official name is 'Lee Chang -yeon's Neungi Village'.First of all, the basic side dishes are so good.The duck was soft and rich..I had a lot of quantity even though it was half. I had two legs.He gave it all the kalguksu to eat it, but it was really full of eating!
원본: 일부러 멀리 찾아갈 정도는 아니지만, 근방에 등산 왔던분들한테는 완전 취향저격이겠다는 생각이 드는 곳.전형적으로 등산로 주변에 있는 백숙집. 닭과 오리, 능이버섯으로 백숙/구이를 판매하신다. 별 기대없이 갔는데 생각보다 오리백숙 고기가 부드럽고 육수는 능이버섯이 많이 들어가서인지 깊은 맛이 났다. 김치도 백숙이랑 잘 어울렸음. 아재입맛인 분들과 몸보신 좋아하는 분들에게 추천!, 번역: It's not enough to go far away, but it's a place where people who have climbed nearby are a perfect sniper.Typically, Baeksuk House around the hiking trail.He sells Baeksuk/grilled with chickens, ducks and mushrooms.I went without expectation, but the duck white meat was softer than I thought, and the broth has a lot of mushrooms.Kimchi also went well with Baeksuk.Recommended for those who have a good taste and those who have seen them!
원본: 노량진에서 만만하게 술 마시기 좋은 곳으로 정말 다양한 세트메뉴가 준비되어있다. 해물왕파전 + 묵사발 세트로 단돈 1.5! 해물파전은 바로 부쳐서 빠삭빠삭하니 뜨끈하게 나와서 맛있었다. 사이즈가 정말 크다 ㅋㅋ 묵사발은 에잉 너무 달았음 ㅠㅠㅋㅋㅋ 세번 갔는데 그때마다 일곱시넘으면 웨이팅. 테이블이 좀 붙어있는 편에 시끌시끌 울려서 다들 목소리가 커진다 ㅋㅋㅋㅋ, 번역: Noryangjin is a great place to drink, and there are a variety of set menus.Seafood King Pajeon + Muksaba Set 1. 5!The seafood pajeon was right and crispy, so it was hot and delicious.The size is really big ㅋㅋ Muksabal was too sweet.Everyone's voice grows because the table is noisy on the side of the table.
원본: 오픈 시간 직전에 갔지만 바로 착석 가능하다고 해서 1등으로 들어갔다 세트 1번이었나 김치전에 국수가 13000원이어서 저렴했던 기억이 난다 국수가 살짝 매콤해서 전이랑 먹을 때 잘 어울렸다 블루베리 막걸리는 진짜 블루베리 갈음 거 같이 다 먹고 나면 잘게 갈은 흔적이 있다 양도 많았다 또 방문할 의향이 있다, 번역: I went just before the opening time, but I was able to seat immediately because I was able to seat first.After eating together, there are traces of chopped crops.
원본: 공릉역에서 제일 유명한 카페인데 시끄럽지 않고 조용해서 좋았어요. 혼자 책읽고, 공부하기 딱 좋은 곳입니다. 모모라떼가 재일 맛있어요!!, 번역: It was the most famous cafe at Gongneung Station, but it was not noisy and quiet.It's a good place to read and study alone.Momo Latte is delicious in Japan!!
원본: 커피도 맛있고 특히 밀크티가 맛있는 곳. 스콘류도 괜찮고 자리도 널찍널찍해서 좋습니다., 번역: The coffee is also delicious and the milk tea is especially delicious.The scorn is fine and the seats are good.
원본: 예쁘고 귀엽고 깔끔하고 맛있고 인스타 감성이 있는 요즘 젊은 사람들이 좋아할 카페, 번역: Pretty, cute, clean, delicious, and Instagram emotions
원본: 공릉에 예쁜 카페를 발견했네여양버터는 정말 맛나구 귀여우ㅜ요, 번역: I found a pretty cafe in Gongneung.
원본: 매장도 넓고 청결도나 점원 친절도 또한 좋아 카페 내에 있는 동안 매우 쾌적하게 있을 수 있었음 요즘 스콘에 빠져서 매일 클래식 스콘과 카카오 스콘만 주문해서 먹는데 너무 맛있어서 어쩔줄 모르겠음 주문하면서 데워달라고 한 후 먹으면 더욱 맛있으니 참고하시길 바람, 번역: The store is wide and clean, and the kindness of the clerk is also very comfortable while being in the cafe. These days, I fell in love with scones, so I ordered only classic scones and cacao scones every day.Please refer to the wind
원본: 어딜가나 인기있는 스타벅스입니다노원역출구바로앞이라 역시 사람많지만스타벅스답게 커피. 좋아요, 번역: It's a popular Starbucks wherever you go.great
원본: 직원분들이 친절하셔서 기억에 남는 곳이에요.가게 내부도 넓고 쾌적해서 맛있게 먹을 수 있었어요:), 번역: It's a memorable place for employees.The interior of the store was also spacious and comfortable, so I could eat it deliciously :)
원본: 백종원 만세고 찹쌀탕수육 작은사이드로 먹을 수 있어서 너무좋아, 번역: Baekjongwon Long Live and Leave Live Line
원본: 먼저.. 기다리면서 좀 짜증이 나더라고요. 가게도 작은데 직원이 부족한지 테이블 회전도 너무 느리더라고요.. 덕분에 약 10팀 안되는 사람들 빠지는데 1시간 정도 걸리는 수준. 기다리면서 주문 미리 받는데 앉자마자 나오는 것도 아니고 앉아서도 한참기다리게 만들어요. 그럴거면 주문 대체 왜 미리 받는지 의문.더 큰 문제는 그닥 특별할 것도 없는 맛이었다는 거. 돈파스는 그냥 딱 상상하시는 그 맛이에요. 맛있다던 찹스테이크도 먹었는데 평범했고요. 주변에 아무 양식집 잡아서 들어가도 다 이정도맛은 하죠. 가격에 걸맞는 맛은 당연히 아니었고요. 돈까스랑 파스타 섞어먹는다고 새로운 맛이 창조되진 않아요..결론은 가지마세요. 줄 없어도 두 번 갈 집은 아닌데 줄 서서까지 먹을 이유가 전혀 없습니다. 돈 아깝고 시간 아까워요. 별 맛집도 아닌데 테이스티로드하고 삼대천왕 때문에 떴나보네요., 번역: first..It was a little annoying while waiting.The shop is also small, but the table rotation was too slow..Thanks to this, it takes about 10 teams to miss about 10 teams.While waiting, I get a pre -order, but it doesn't come out as soon as I sit down.If so, I wonder why I receive it in advance.The bigger problem was that there was nothing special.Donpas is just the taste you imagine.I also ate delicious chop steaks, but it was ordinary.Even if you get into any farming house around you, it tastes like this.Of course it wasn't the price.Eating pork cutlet and pasta doesn't create a new taste..Don't conclude.Even if you don't have a line, it's not a house to go twice, but there's no reason to eat until you stand up.It's a waste of money and a waste of time.It's not a star restaurant, but it's because of the tasty road and the king of Samdaecheon.
원본: 친구한테 들어보고 궁금해서 찾아보니 맛나보여서 다녀왔는데 맛있었어요 ㅎㅎㅎ 또 가게 될듯, 번역: When I heard it because I was curious, I was curious, so I went there and it was delicious.
원본: 별미. 맛이 있으면서도 노말하지는 않은 곳, 번역: Delicacy.Where it is tasty but does not normal
원본: 점심식사도 있고 삼계탕이 진국이네요닭갈비는 생각보다 별로였어요, 번역: There is lunch, and Samgyetang is Jinguk.
원본: 막국수랑 만두 맛있게 하는 집입니다.족발과 수육은 소주 한잔하기에 좋구요.참 좋은 식당입니다., 번역: Makguksu and dumplings are delicious.Jokbal and meat are good for a drink.It is a good restaurant.
원본: 막국수,곰국시,보쌈,족발,만두까지 정말 맛있습니다 모임장소 적극 추천~, 번역: Makguksu, Gomguk, Bossam, Jokbal, and Dumplings are really delicious.
원본: 족발맛은 정말 좋았고. 만두도 정말 맛있었음. 서비스 최고. 보쌈 고기가 조금 아쉬움., 번역: The jokbal taste was really good.The dumplings were really delicious.Service best.Bossam meat is a bit unfortunate.
원본: 보들보들 족발과 어리굴젓이 넘 넘 맛있어요.메밀 손 국시 국물을 써비스로 주시는데 넘 맛있어 결국 국수를 추가 주문했지요., 번역: The jokbal and foolish are so delicious.I gave it as a soba soup and it was so delicious that I ordered additional noodles.
원본: 가격은 조금 있는 샤브샤브집.고기제외 무한리필가능.맛은 보통소스는 3~4가지 있는데 조금 아쉬웠음, 번역: Shabu -shabu house is a little price.Unlimited refills except meat.There are usually 3 ~ 4 sauce, but it was a bit unfortunate.
원본: 얇고 긴 건물 15층 맨위에 있습니다. 접근성이 조금 떨어져요. 주차도 불가능...최저가격 메뉴가 다른게 있는데 이건 샤브샤브에 적합한 고기가 안나오는 이상한 메뉴라 사실상 가격은 평일점심 15000원 / 나머지 20000원이 맞는 것 같습니다. 우삼겹, 오리훈제, 떡갈비는 샤브샤브와 어울리지 않고 월남쌈 메뉴는 한우 세트에 기본적으로 포함되있습니다.가족단위의 손님이 많으며 주말 휴일은 대기열이 깁니다.샤브샤브는 1개의 육수에 매운 양념을 넣는 것으로 구분합니다. 무난한 육수이고 버섯류와 나머지 만두, 청경채, 배추, 파, 마늘 등등 신선합니다. 만족스러웠습니다. 다만 후식으로 커피나 아이스크림이 있는데 이것은 따로 별도 결제입니다. 별로 좋은 퀄리티도 아닌데 굳이 돈을 받는 이유를 모르겠습니다., 번역: It is on the 15th floor of a thin and long building.The accessibility is a little lower.Parking is also impossible...The lowest price menu is different, but this is a strange menu that doesn't have the right meat for shabu -shabu.Uri -pork belly, duck smoked, and tteokgalbi are not matched with shabu -shabu.There are many families, and the weekend holidays are long.Shabu -shabu is divided into one spicy seasoning in one broth.It is a good broth and mushrooms, the rest of the dumplings, bokchae, cabbage, green onions, garlic, etc. are fresh.I was satisfied.However, there are coffee or ice cream as a dessert, which is a separate payment.It's not a good quality, but I don't know why I get paid.
원본: 맛은 그냥 그렇지만 재방문의사 있어서 별 4개! 고기질은 막 좋지는 않지만 야채랑 가득 먹을 수 있어 좋았네오, 번역: The taste is just, but there are four stars!The meat is not good, but it was nice to be able to eat vegetables and vegetables
원본: 쌀국수 먹을땐 사이공 윤다이👍가격대비 양도 엄청 많고 맛도 베트남식인데 한국사람 입맛에 안성맞춤.일하시는 분이 전부 베트남 현지분들이라 맛있어용ㅎㅎ, 번역: When you eat rice noodles, there are a lot of price for Saigon Yoon Dai 👍 and the taste is a battling.All those who work are locals in Vietnam, so it's delicious.
원본: 즐겨가던 쌀국수집이 닫아서 급하게 검색해서 갔네요. 베트남 현지분들이 운영하는듯 합니다. 맛있습니다. 메뉴도 다양하지만 익숙한 쌀국수 막었네요. 군만두 비슷한 음식을 먹었는데 이름이 잘 기억이 나질 않아요. ㅎㅎㅎ 메뉴판을 안 찍었네요. 고수를 좋아하시면 꽤 괜챦은 맛의 쌀국수를 드실듯 합니다.메뉴와 관련해서 설명을 해주면 더 좋았을 듯 합니다., 번역: The rice noodles I enjoyed was closed and I searched in a hurry.It seems to be run by Vietnamese locals.Delicious.There are many menus, but I blocked rice noodles.I ate a similar food, but I don't remember the name.ㅎㅎㅎ I didn't take the menu.If you like the master, you'll have a pretty good taste.It would have been better to explain the menu.
원본: 건물 무료주차 가능하고 쌀국수 진짜 맛있어요~! 칠리소스 굿굿, 번역: The building is free parking and rice noodles are really delicious ~!Chili sauce good good
원본: 정말 예상외의 맛집. 지금까지 먹어온 베트남 음식하고는 다르다. 오리지날 느낌이 남. 사장님이 베트남 분이셔서 진짜맛인듯!, 번역: Really unexpected restaurant.It is different from Vietnamese food that has been eaten so far.It feels like the original.The boss is Vietnam, so it's really taste!
원본: 자부심있는 간판쌀국수 완전 좋아하는데 마곡나루에서는 최고의 집인듯베트남 출신 사장님 알바 모두 친절, 번역: Proud signboard rice noodles, but I like Magog Naru, all Vietnamese boss Alba is kind.
원본: 다양한 종류의 와플과 커피를 판매 하고 있어요  와플이 맛있어요, 번역: We sell a variety of waffles and coffee.
원본: 좋아요. 회사단지 근처라 그런지 회전률도 빨라요. 그리고 저렴해요., 번역: great.It's near the company complex, so the turnover is also fast.And it's cheap.
원본: 가게 입구가 너무 작고 허름해서 두 세 번 확인하고 들어갔는데 내부 인테리어도 그냥 그랬지만... 손질한 대게를 이 가격에 먹을 수 있는 것만으로도 만족합니다 :), 번역: The entrance to the store was so small and shabby that I checked it two or three times, but the interior of the interior was just like that...I am satisfied with the fact that the trimmed snow crab can be eaten at this price :)
원본: 메인 2개 (대게+랍스타) 원가만 해도 4만원이 넘던지 이 언저리 일겁니다. 그런데 1번도로 참치와 각종 조개찜+새우찜(인원수에 따라 다르지만 전복도 나옴)도 나오고.. 거기에 밥과 라면까지. 밑반찬으로 부침개랑 새우튀김도 나옵니다.(밑반찬 리필 안됨) 가성비 면에서는 최고가 아닐까 싶네요. 맛은 뭐 말할것도 없구요. 사장님 존경함.👍👍, 번역: Two main (usually+lobster) costs over 40,000 won.However, there are also roads 1 tuna and various shellfish steamed+shrimp steamed (depending on the number of people, but the abalone comes out)..There is also rice and ramen.As a side dish, the dogs and fried shrimp are also available.(No side dish) I think it's the best in terms of price.Not to mention the taste.Respect the boss.👍👍
원본: 대게 큰 놈이 나오면서 스끼다시하가 나오는 것치고 가격이 저렴하다. 물론 맛도 있다. 분위기는 서민적인 시장 횟집 느낌이다., 번역: Usually a big guy comes out, the price is cheaper.Of course it tastes.The atmosphere is a common market sushi.
원본: 회식 하기 좋아요 대게는 당연히 존맛탱 대게 라면도 사랑합니다, 번역: It's good to drink.
원본: 대만의 딘타이펑을 잊지못해 여기저기서 종종 사먹곤 했었습니다. 그런데 지인의 추천으로 서촌의 포담에서 샤오롱빠오를 먹었더니 정말 마있네요.내부는 테이블이 많지 않지만 그래도 6테이블 이상은 되은듯 하구요. 샤오롱빠오는 주문한지 얼마 되자 않아 바로 나옵니다. 저는 돼지고기 들어간 것과 새우가 들어간 것 그리고 탕수육을 먹어봤는데요. 탕수육은 제입맛엔 별로였고 샤오롱빠오가 최고였습니다. 참 식당의 화장실이 내부에 없고 매장의 바깥에 있는데 좀 무섭고 찾기 어려웠습니다. 화장실만 고쳐진다면 참 좋을 것 같습니다. 재방문의사 있습니다요., 번역: I couldn't forget Taiwan's Din Taipeng, so I often bought it here and there.However, I ate Xiaolong Pao at Seochon's Poam with the recommendation of acquaintances.There aren't many tables inside, but it seems to be more than 6 tables.Xiaolong Pao will come out immediately after ordering.I ate pork, shrimp, and sweet and sour pork.Sweet and sour pork was not good for the taste and Xiaolong Pao was the best.There is no toilet in the restaurant and is outside the store, and it was a bit scary and hard to find.It would be great if only the bathroom was fixed.I have a doctor.

 90%|████████▉ | 20098/22421 [02:20<06:15,  6.19it/s]

원본: 여기 원래 존맛이었는데올만에 방문하니 별로였음 ㅠㅠ 맛이 하향평준화됨.. ㅜㅜ 아쉽다 아쉬워 ㅜㅜ 뭔가 애매해진 맛 혹시 주인님이 바뀌셨나 의심됨, 번역: It was originally John Taste, so I visited it..TT TT Unfortunately I'm sorry ㅜㅜ I doubt that the master has changed

 90%|████████▉ | 20099/22421 [02:20<06:20,  6.10it/s]

원본: 전체적으로 괜찮았습니다! 딤섬 맛집이 근처에 많이 없는데, 포담은 딤섬 먹고싶을 때 갈만한 맛집입니다 가격도 타 딤섬집들에 비해 괜찮은 것 같고, 맛도 더 괜찮은 거 같아요 여기 찹쌀 탕수육도 맛있었어요, 번역: Overall it was fine!There aren't many dim sum restaurants nearby, but Podam is a good restaurant to eat when you want to eat dim sum.
원본: 매장이 약간 작습니다. 대표메뉴인 딤섬이 맛있는데 의외로 마라탕면도 아주 맛있습니다., 번역: The store is a bit small.The representative menu, Dim Sum, is delicious, but the Maratang noodles are also very delicious.
원본: 샤오롱빠오는 깔끔하고 맛있었으며, 간장탕수육은 양념시 맛있었다, 번역: Xiao Long Pao was clean and delicious, and the sweet and sour pork was delicious during seasoning.
원본: 육즙이 터지는 샤오롱바오가 먹고싶어서 방문했는데 딘타이펑이 더 맛있는 것 같아요 탕수육은 새콤한 맛이 강했고 탄탄면에서는 땅콩맛이 났어요! 무난한 맛이었어요 재방문의사는 없습니다, 번역: I wanted to eat the juicy Xiao Long Bao, but Din Tai Peng seems to be more delicious.It was a good taste. There is no doctor
원본: 회사 근처라서 갔는데 대만에서 먹은 딤섬이랑은 별반 차이가 없다. 그만큼 맛있다. 면은 향이 나서 그런지 우육면은 별로였다.탕수육은 흑초소스라 신기했다. 맛있었다.근데 서비스는 불만족스러웠다. 대기 손님이 많아서 급하게 식사했고, 가게가 좁아서 불편하다. 무엇보다 일하시는 분들이 웃지 않는다고 해야하나? 그리고 제일 싫었던 건 불러도 못 듣는다....통통한 여성 분이 불러도 애기를 하고 있어서 그런지 이런 부분들이 별로였다. 띵동 벨을 만들던가...., 번역: I went near the company, but there is no difference from Dim Sum I ate in Taiwan.It is so delicious.The noodles were fragrant, so the noodles were not good.Sweet and sour pork was amazing because it was a black vinegar sauce.It was delicious.But the service was dissatisfied.I had a lot of waiting guests, so I ate in a hurry, and the shop was narrow.Above all, should I say that people don't laugh?And I can't call it the most....Even if a chubby woman was calling, it was not good because it was a baby.Do you make a 동 bell?...
원본: 수요미식회에서 보고 찾아간 맛집. 브레이크타임끝나자마자 찾아갔음에도 사람이 많았다. 음식은 예상대로 굉장히 맛있었고 기대를 충족시켜준 맛집., 번역: Restaurant I visited at the demand gourmet sashimi.As soon as the brake time was over, there were many people.The food was very delicious and the restaurant was satisfied with expectations.
원본: 돼지고기 누린내 나는 만두 마라맛 조금 넣은 라면 같은 면 별로임, 번역: I don't like the noodles with a little bit of ramen.
원본: 탄탄면, 우육탕면, 샤오롱바오 먹어봤습니다. 제 생각에는 조금만 더 맛있으면 대박 날듯 해요. 그래도 맛있긴 맛있습니다. 분위기도 좋고 직원도 친절하고 가격도 합리적이라 다음에와서 다른 메뉴도 먹어보고 싶네요~, 번역: I ate Tantan noodles, Wuyuktang noodles, Xiaolong Bao.I think it's a little better if it's a little better.Still delicious.The atmosphere is good, the staff is friendly, and the price is reasonable, so I want to come next time and eat other menus ~
원본: 삼청동에서 부담없이 한끼 할만한 곳인것같고블루보틀이랑 바로 옆에 붙어있네요내부도 넓고 손님도 많았고음식도 무난하네요칼국수와 만두국 둘다 자극적이지 않은부담없이 먹을만한 음식이었어요가봐도 나쁘지 않은곳, 번역: It seems to be a place in Samcheong -dong, and it is located next to Blue Bottle. The wealth is wide and there are many customers, and the food is good.
원본: 칼국수를 워낙 좋아하는지라 소문듣고 찾아간 집이에요사골칼국수인데 국물이 진하고 고기만두도 맛있었어요북창동위치다보니 외국인들이 많이 찾는것같고 수육과 전등 메뉴가 다양해 접대하기도 좋아요발렛비 4천원중 2천원은 식당지원받고 2천원 받더라구요음식값이 조금 비싼것같지만 고급스럽고 위치도 좋으니 크게 비싼 느낌은 아니에요여기저기 방송도 많이 나온 맛집이에요, 번역: I like Kalguksu so much that I heard rumors.I got 2,000 won. The food is a bit expensive, but it's luxurious and the location is not very expensive.
원본: 정갈하고 깔끔합니다. 테이블도 깨끗이 닦은 듯하고 도자기로 된 깔끔한 식기가 맘에 들어요. 백김치와 김치가 같이 나오고 특히 직접 만드신듯해서 더 좋아요. 아이를 배려해 고명이 따로 나오는 점도 훌륭하네요!, 번역: It's tidy and tidy.The table seems to be wiped and I like a neat dish with pottery.Baek Kimchi and kimchi come together, and it's especially good to make them.It is also great to see the garnish in consideration of the child!
원본: 깡통만두가 문을 닫아서 찾아간 곳인데 줄이 꽤 있었지만 회전률이 빠른지 대기 한 10분 정도 해서 먹을수 있었어요. 2층에 별관까지 있어서 좌석이 많은것 같았어요. 칼국수는 국물이 맛있었고 면은 평범했어요. 만두가 정말 맛있었는데 날이 쌀쌀해져서 그런지 금방 식더라구요. 오히려 만두국이 좋았어요. 2명이서 가시는거라면 칼국수에 만두국 조합을 추천해드리고 싶어요. 메뉴3개는 2명이서 먹기 많아서 남은건 포장해왔어요. 만두가 정말 맛있는 곳입니다., 번역: The tin dumplings were closed and visited, but there were quite a few lines, but I could eat it for about 10 minutes waiting for a quick turn rate.There was a lot of seats on the second floor, so there seemed to be a lot of seats.Kalguksu was delicious and the noodles were plain.The dumplings were really delicious, but the days got chilly, so it was cool.Rather, I liked dumplings.If you are going to go to two people, I would like to recommend a dumpling country union for Kalguksu.There are three menus for two people, so I have been packed.Dumplings are really delicious.
원본: 11시 40분경 도착해서 웨이팅없이 자리 잡았는데 잘 먹고 나오니 줄을 쭉 서있더군요.사골칼국수와 사리추가, 그리고 왕만두를 시켰습니다.사리추가는 유치원생 아이를 데리고 가서 혹 모자랄 것 같아 시켰는데 거의 한그릇 수준이더군요.사골칼국수는 국물이 정말 좋았어요. 면은 그냥 생면을 쓰는 듯 했지만 국물이 워낙 맛있어서 전혀 불만스럽지 않았어요.만두는 옛날 만두(70년대 먹던) 맛이 나서 좋았습니다.아이랑 함께 가기 좋은 식당이라 생각합니다, 번역: Arrived around 11:40 and settled without waiting, but I ate well and stood all the way.I added the bone bone kalguksu, the saree, and the dumplings.I took a kindergarten child and thought it would be enough.The bone bone kalguksu was really good.The noodles seemed to use raw noodles, but the broth was so delicious that I wasn't dissatisfied at all.The dumplings were good because of the old dumplings (70s).I think it's a good restaurant to go with
원본: 오늘 휴일 점심은 북촌에 있는 황생가 칼국수에서..미슐랭가이드 한국판에 실렸다고 해서 얼마나 맛있기에 하는 마음에 방문을..- 맛은 깔끔하게 떨어지는 맛- 백김치가 시원하게 맛있고 그냥 김치는 매워보이지맛 그리 맵지 않는 맛- 콩국수는 맛있지만 아주 맛있다 할수는 없을 듯..- 칼국수는 육수로 우려냈지만 느끼하지 않고 멸치국물처럼 깔끔한 맛..- 만두는 고기를 넣지 않고 야채을 넣고 양파와 호박의 아삭함을 살린 맛 ... 가장 낳은듯...대단한 맛은 아니고. 그냥 깔끔한 맛과 MSG를 안썼다는, 번역: Today's holiday lunch is in the Kalguksu, the Hwang Saega Kalguksu in Bukchon..I visited the Korean version of the Michelin Guide..The taste of white kimchi, which tastes neatly, is cool, and kimchi just looks spicy, but the flavored bean noodles are delicious, but it can't be very delicious..Kalguksu was worth it as a broth, but it doesn't feel like anchovy broth..The dumplings are made of vegetables without meat, and the taste of onion and pumpkin is used...It seems to be the most...It's not a great taste.Just neat taste and MSG
원본: 만두가 진짜 엄청 맛있어요. 칼국수도 맛있지만 만두가 감칠맛 최고. 쓰는 와중에도 또 먹고 싶습니다., 번역: The dumplings are really delicious.Kalguksu is also delicious, but dumplings are the best flavor.I want to eat again while writing.
원본: 경복궁 보고 삼청동 들어가는 길에 위치한 미슐랭이 인정한 칼국수 맛집! 만두도 존맛이니까 꼭 드세요~, 번역: Kalguksu restaurant recognized by Michelin on the way to Samcheong -dong, Gyeongbokgung Palace!Dumplings are also John, so please eat it ~
원본: 왜때문에 이곳이 빕구르망인가.. 특색없는 맛에 만두도 충격적으로 감흥이 없다. 반찬도 무난하다. 위치 빼곤 남는게 없었고 그 누구도 재방문을 하거나 단골처럼 오진 않을 것 같은 곳이다. 내 맘속엔 영원히 패스#칼국수맛있는집어딨지, 번역: Why is this Bib Gurman?.Dumplings are shockingly inspired by the uniqueness.The side dishes are also good.There is nothing left except location, and no one will return or come like a regular.In my heart
원본: 사골국물도 김치도 그렇고 전체적으로 음식들이 간이 좀 쎈듯한.. 간이세서 그런지 백김치가 오히려 더 잘어울렸습니다, 번역: The bone soup and kimchi, and the food seems to be a little liver..It's so good that Baek Kimchi looks better.
원본: 국물이 기본적으로 정말 짭니다. 이모한테 말씀 드리면 간 안한 육수 가져다 주십니다.만두가 정말 맛이 없습니다. 시중에 파는 꼬마물만두가 훨씬 맛있습니다., 번역: The broth is basically really good.If you tell my aunt, he brings the broth.The dumplings are not really good.The dumplings on the market are much more delicious.
원본: 50년전통을 자랑하며 백년음식으로 선정되었던 가게이다내입맛에 맞고안맞고의 이상으로 50년이상을 지내온가게는 맛있게먹어줘야겠다는 생각이 든다 ㅋㅋ오향장육을 처음먹어봐서, 기준이 되는 평가는 내릴수없지만, 맛있었고, 군만두가 솔직히 맛있다 ㅎㅎ맥주한잔에 군만두 하나~~ㅎㅎ, 번역: It is a 50 -year -old shop and has been selected as a hundred -year food.It was delicious, and the dumplings are honestly delicious ㅎㅎ A glass of beer.
원본: 어른들이 소주 한잔하기 좋습니다. 외관은 서민적인 분위기에요. 역이랑 가깝습니다, 번역: Adults are good for a drink.The exterior is a common atmosphere.It's close to the station
원본: 가게가 오래된 만큼 다양한 나이대의 손님들이 오는집.몇년전에 바로 옆으로 가게를 확장했다.가끔 갈때마다 시끄러운 술취한 노인 손님들이 있어서 조금은 꺼려지지만맛이 종종 생각나서 찾는 집.메인메뉴는 오향장육이고 다른 곳보다는 고기가 덜 뻑뻑하다. 오향장육은 고기한점에 채선 오이약간 부추 절임같은거 조금 올리고 고기를 끓여 굳힌것 같은 벌벌이 같은 녹는 묵형태의 검을 젤리를 한덩이 올리고 생마늘 한조각을 올려먹는 방법이 있는데 한국 중국요리들처럼 먹기 수훨하고 기존에 이런 중국요리를 접해 보지 않았으면 새롭게 느껴질 수 있는 난이도가 아주 낮은 중국요리.보통 오면 둘이서 오향장육 중짜리 하나 시키고 군만두 하나 시키고 술을 시키는데 이 집은 오향장육과 군만두가 유명하다.군만두는 가격대비 양이 좀 적게 느껴질 수 있으나 일반 중국집 군만두가 아니라 손으로 직접 빛은 이 집 특유의 만두임을 생각하면 먹을 만 하다. 물만두는 그닥.이 곳엔 송화단도 있는데 송화단은 삭힌 오리알로 짚단이랑 진흙이랑 섞은 반죽속에 오리알을 넣고 몇개월동안 숙성시킨 중국 음식중 하나인데 이집에서 맛을 볼 수 있다.가격은 기억이 잘 안나지만 꽤 비싼 편(삭힌 오리알 하나를 잘게 썰어주는데 가격이...근데 집에서 먹으면 괜히 이 맛과 분위기가 안난다)이 송화단 썰은걸 소금에 살짝찍어 이과두주와 함께 먹으면 정말 별미다.송화단의 맛은 되게 녹지인한 맛이랄까? 녹찌이인 한 느낌에 약간 삭힌듯 향이 난다. 그래서 그런지 이과두주같은 중국 백주와 잘 맞는듯하다.영등포에서 약속이 있으면 한번즈음은 꼭 데려가보는 집.아 같이 나오는 걸죽한 굴미역국 같은것도 은근히 맛난다., 번역: As the store is old, the house is home to various guests.A few years ago, the store was extended to the side.Every time I go, I have a noisy drunken old guests, so I'm a little reluctant, but I often find a house.The main menu is five -flavored meat, and the meat is less stiff than anywhere else.Five -flavored meat is a little bit of pickled cucumbers at a single meat and a little bit of leek pickles and boiled meat.If you haven't encountered such a Chinese cuisine, it's a very low difficulty that you can feel.When you come, they usually have a five -fledged jang meat, one dumplings, and drinks.Military dumplings may feel a little less for the price, but it is worth eating considering that light is unique to this house.Water dumplings are so.There is also Songhwadan, and Songhwadan is one of the Chinese foods that have been aged for several months with duck eggs in a half -mixed half -mixed and mud.I don't remember the price, but it's quite expensive (I chop one cut duck eggs, but it's the price. But when I eat it at home, it's not this taste and atmosphere).The taste of Songhwadan is a very green taste.It feels like a rusting feeling.That's why it fits well with Chinese white liquor like this.If you have an appointment in Yeongdeungpo, you must take it.Oh, it's also delicious.
원본: 바삭한 군만두와 처음먹어보는 오향장육 맛이독특해요 처음먹어보는 맛이었습니다처음에주는 국도 걸쭉하니 맛있어여, 번역: The crispy dumplings and the first five flavors are unique.
원본: 만두맛집으로 유명해진 대문점입니다. 점심에 방문했을 때에는 유명세에 비해 비교적 한산한 모습이었습니다. 만두는 만두피가 독특하고, 오향장육과 송화단도 맛있습니다. 다만 이 모든 메뉴들이 술안주로 저녁에 주로 소비되는 메뉴들이라 그런지 식사로 먹기에는 뭔가 애매한 구석이 있습니다. 전반적으로 회사 부장님급 정도 되시는 분들을 모시고 오면 좋아하시겠다 싶은 인상을 받은 음식점입니다.홀을 담당하시는 사장님도 친절하신 편입니다. 먹자골목 한가운데라 주차장은 없습니다., 번역: This is a famous dumpling restaurant.When I visited lunch, it was relatively quiet compared to the famous world.Dumplings are unique in dumplings, and five flavored meat and Songhwadan are delicious.However, all these menus are mainly consumed in the evening as a snack, so there is something ambiguous to eat.Overall, it is a restaurant that received an impression that you would like to like when you come with those who are about the company manager.The boss in charge of the hall is also kind.There is no parking lot in the middle of the food alley.
원본: 한번은 궁금해서 갔지만 두번은 안갈듯.음식은 제 입맛만 기준으로 봤을 때만두는 먹을만 했으나 원래 의도한건지 내용물이 참 적다 라는 인상이 강했음. 가격 생각하면 두번 사먹긴 별로인..오향장육 참... 양.. 같이 간 사람은 적다고 했는데 뭐 24000원 가격에 비하면 뭐 이해 안가는 양은 아님. 남자 둘이먹기 모자란건 맞음.맛.. 불맛을 내려했는지 모르겠으나 탄맛남.       퍽퍽함.       동내서 흔히 먹는 족발고기에 불맛 낸다고 살짝 그을려서 식힌느낌 이었음.처음에는 이것저것 싸먹는 재미는 있지만... 맛은 뭐 그닥... 특별히 맛있다 느껴지지않음.. 싸먹는거 처음에는 하는데 나중에는 귀찮아서 걍 따로먹게됨..자리 앉자마자 뭐 시킬거냐고 뚷어지게 쳐다보는데 메뉴도 못봤는데 주문부터 받으니 당황했음 전반적인 서비스는 나쁘지 않았음오이 채 썰다 말아서 뭉탱이가 집힘.바빠서&맛에는 영향 없음 이해는 하지만성의없어보였음., 번역: I was curious once, but I didn't go twice.The food was only eaten on the basis of my taste, but the impression was that the contents were less intended.If you think about the price, you don't have to buy it twice..Ohhyangjang meat...sheep..There are few people who have been together, but compared to the price of 24,000 won, it is not a quantity that I don't understand.It is right for two men to eat.taste..I don't know if it tasted.Pucked.It was chilled because it was slightly gone because of the common jokbal meat.At first, it's fun to eat...The taste is that...It doesn't feel especially delicious..At first, it's bothersome to eat, but it's bothersome..As soon as I sat down, I looked at what you're going to do, but I didn't even see the menu, but I was embarrassed. The overall service was not bad.I was busy and didn't affect the taste, but I didn't see it.
원본: 오향장육 맛있음 피딴과 오이의 콜라보가 좋다!, 번역: Five -flavored meat is delicious, you can have a good collaboration of cucumbers!
원본: 보통 웨이팅 있음체인점이라 어딜가나 기본이상의 맛재방문의사 있음, 번역: Usually there is a waiting chain, so everywhere you go to taste materials.
원본: 일단 이곳의 사이드 메뉴인 떡 맛있습니다 겉은 바삭하구 속은 말랑 ''내가 치즈를 먹은 건가'' 라는 착 각마저 들게하죠. 그리구 간천엽 무한리필. 저는 간천엽 안주는 곱창집은 안갑니다. 신선해야 하는 곱창인데  간천엽은 매일 축산시장에 가야 하는거니 신선한 곱창을 위한 저만의 척도인데 두번리필까지는 괜찮은데  세번째는 간이 쓰더라구요 저만 그런지 알았는데 여친도 뒷맛이 쓰다고 그래서 아쉬웠어요. 저는 간때문에 곱창집 가거든요. 그리고 저는 한우곱창 1인, 한우막창 1 인분 먹었는데 너무기름져서 둘다 대창먹는 줄알았어요. 그램수를 맞추기우해 겉에 기름제거를 안한 느낌. 막창은 쫄깃한 맛은 없고 그냥 기름덩어리  먹는 느낌이었습니다. 볶음밥도 먹었는데  맛있었어요. 특이하고요. 곱창 이곳 저공 많이 먹고 다니는데 이 곳에서 맛있었던건 사이드 메뉴인 떡과 볶음밥, 서비스로 주는 음료수 정도 였습니다. 저는 다시는 가지 않을 것같아요. 어짜피 맛집은 개인취향이니까요, 번역: The side menu of this place is delicious.And the liver leaf infinite refill.I don't go to the giblet house for Gancheon Leaf.It's a fresh giblet, but Gancheon leaves have to go to the livestock market every day, and it's my own measure for fresh giblets.I go to the giblet because of the liver.And I ate one Korean beef giblet and one serving, but I was so oily that I thought they were eating Daechang.It feels like the gram is not removed from the outside.The makchang has no chewy taste and it was just like eating oil.I also ate fried rice and it was delicious.It's unusual.I eat a lot of low air here, but it was a drink that was delicious here.I don't think I will go again.Anyway, because the restaurant is a personal taste
원본: 건대입구역 주변에서 이곳이 곱창 퀄리티가 가장 좋다고 느낍니다. 죽염가루를 뿌려주는 것이 독특합니다., 번역: I feel that this is the best giblet quality around Konkuk University Station.It is unique to sprinkle bamboo salt powder.
원본: 다른지점 갔다가 맛있어서 또갔어요 역시나 맛있네용 감자떡사리최고!!!, 번역: I went to another store and went to it again.!!
원본: 공간이 협소하지만 소곱창을 이가격에 먹을수있다는것이 큰 장점인듯!, 번역: The space is narrow, but it seems to be a big advantage that you can eat the small giblets at this price!
원본: 마카롱 필링이 두껍고 꼬끄가 부드러워요. 그리고 커피 가격이 저렴하고 맛있어요., 번역: Macaron peeling is thick and soft.And the price of coffee is cheap and delicious.
원본: 이 집 마카롱은 꼬끄가 부드럽고 필링이 두껍지만 깊은 맛이 나진 않아요. 하지만 가성비 좋기 때문에 또 사서 먹을 거 같긴 해요., 번역: This house macaroon is soft and thick, but it doesn't taste deep.But it's good to buy and eat again.
원본: 수락산역 가까운곳에..주말이면 등산객들이 많을듯..평일 조금 늦은 점심에 노부부들이 많이 앉아계신다.인정받고 있다는 얘기겠지..맛은 약간 고급진 명동칼국수..국물맛은 명동칼 그대로이고 소고기 고명이 얹혀지 있다는 정도 차이..9천원은 너무 착하지 않다..그래서 아쉽다, 번역: Near Suraksan Station..There are many hikers on weekends..A lot of old couples are sitting in a little late lunch on weekdays.You're recognized..The taste is slightly luxurious..The taste of the soup is the same as the Myeongdong knife and the beef garnish is placed..9,000 won is not too good..So it's a pity
원본: 오래전부터 우리 가족이 참 좋아하는 칼국수 집이 었습니다. 여러가지 내부 사정으로 상당기간 문을 닫았어서 너무 모두들 실망하고 있었는데...다이닝코드를 보다보니 평가글이 올라왔다. 바로 찾아갔다.전에 있던 건물은 그냥두고 새로 건물이 생기고 그곳에서 다시 장사를 시작한지 거의 1년 다 되어간다고 한다.다이닝코드 아니었으면 우리 가족은 영원히 추억속의 칼국수집이 될뻔 했다.여전히 닭칼국수맛은 일품이다. 꽤 오랜시간 가계가 쉬었음에도 예전맛을 거의 가지고 있었다. 다행히도 ^^노원구, 도봉구, 강북구(노도강), 남양주, 구리, 의정부 이런쪽에 사신다면 꼭 한번가보시길 권합니다. 그냥칼국수도 사골국물에 좋지만 특히 닭칼국수는 최상입니다. 만두도 상위 10%안에 들구요., 번역: For a long time, my family has been a favorite kalguksu house.I was so disappointed that I had been closed for a long time due to various internal circumstances...Looking at the dining code, the evaluation article came up.I went right away.It is said that the building was left alone and it was almost a year since the new building was created and the business began again.If it wasn't a dining code, my family was forever a kalguksu collection in memories.Still, the chicken kalguksu taste is excellent.Even though the household was rested for quite some time, I had a taste of the old taste.Fortunately, if you live in Nowon -gu, Dobong -gu, Gangbuk -gu (Nodo River), Namyangju, Guri, and Uijeongbu, I recommend you to go.Kalguksu is also good for bone soup, but chicken kalguksu is especially best.The dumplings are also in the top 10%.
원본: 칼국수로 건물세운곳.가격이 올라 아쉽지만 맛있다. 특이하게 닭칼국수도 파는데 이게 인기메뉴다., 번역: The building was built with kalguksu.It's a pity that the price is rising, but it's delicious.It's unusual to sell chicken kalguksu, which is a popular menu.
원본: 오래전부터 단골인 집이에요. 최근까지 법정소송으로 문을 닫았다가 영업을 재개했어요. 그전에 비해서 사실 양대비 가격이 많이 오른것 같아서 그점이 좀 아쉬워요. 그래도 여전히 맛있고 친절하십니다., 번역: It's a regular house for a long time.Until recently, I closed the door in court and resumed business.In fact, it seems that the price of the two has risen a lot compared to before.Still, it's still delicious and kind.
원본: 예전부터 참 좋아하던집이었는데 건물상속과 관련한 자식들간 분쟁으로 한동안 문닫았었어요. 우연히 지나가다가 뒷건물에 오픈한걸 발견했습니다. 새로지어서 그런지 내부는 깔끔합니다. 주차공간도 갖추고 있어 방문하기 편해요. 메뉴는 똑같이 칼국수, 닭칼국수, 콩국수(계절), 만두(한접시/반접시), 만두국이 있네요. 이전에는 다 먹어보긴 했는데 새로 오픈하고는 콩국수, 칼국수, 만두시켜서 먹어봤는데 맛은 그대로인듯 합니다. 맛있구요!! 밥은 추가로 원하면 먹을 수 있어요. 양이 근데 워낙 많은편이라 양 적으신 분들은 밥 못드실듯ㅠㅋㅋ 면추가는 2천원이에요. 여기서 문젠 가격입니다. 칼국수 한그릇이 9천원까지 올랐는데 콩국수는 심지어 만원 ㅠㅜ 너무 아쉽습니다. 예전처럼 자주 방문할 수 있을지는 미지수에요., 번역: It was a favorite house for a long time, but it was closed for a while due to disputes between children related to the inheritance of the building.I accidentally passed by and found it opened in the back building.It's new and the inside is clean.It also has a parking space, making it easy to visit.The menus are equally kalguksu, chicken kalguksu, bean noodles (seasonal), dumplings (one plate/counterpart), and dumplings.I had eaten all of them before, but I opened the new noodles, kalguksu, and dumplings, but the taste seems to be the same.It's delicious!!You can eat rice if you want additional.The amount is so much that the quantity is not good.Here is the price of the door.A bowl of kalguksu rose to 9,000 won, but bean noodles are even 10,000 won.It's unknown whether you can visit as often as before.
원본: 밀푀유나베는 건강하고 깔끔한 맛이며야채를 충분히 섭취할 수 있어 좋아요.게다가  칼국수와 마무리죽까지 배가 든든해집니다^^간단한 덮밥 3종도 맛나게 먹었습니다, 번역: Millet Yunabe is a healthy and clean taste and can be eaten enough vegetables.In addition, Kalguksu and finishing porridge are full of hungry.
원본: 아주 건강한 맛임. 음식이 정갈하게 나와서 보기도 좋음.칼국수와 죽까지 만족스러움, 번역: Very healthy taste.It's good to see the food neatly.Satisfaction with kalguksu and porridge
원본: 음식은 정갈하고 담백합니다. 채소와 고기의 균형이 잘 잡혀 있어서 건강한 맛이 나요. 조용하고 차분한 분위기입니다. 4인 이상 모이는 시끌벅적한 회식자리엔 잘 어울리지 않는 것 같아요., 번역: The food is tidy and light.Vegetables and meat are well -balanced so it tastes healthy.It is a quiet and calm atmosphere.I don't think it's a good match for a noisy dinner.
원본: 예쁜 비주얼에 양도 푸짐한 나베에요. 소고기를 양배추, 깻잎이 켜켜이 싸고 있어서 먹기 편합니다.양배추 단맛이 우러나와서 국물에서 은근한 단맛이 나고 짜지 않아서 좋았구요. 소스는 간장소스와 칠리소스 두 가지가 같이 나오는데 특별하진 않아요. 김치맛도 좀 아쉬웠어요. 급식김치맛...일하시는 분들이 친절하고 바빠도 빨리 대응을 해주는 편입니다.내부가 아주 넓지는 않아서 금요일 저녁과 주말에는 좀 기다릴 수도 있습니다., 번역: It's Nabe, a lot of pretty visuals.Cabbage and sesame leaves are wrapped in beef, making it easy to eat.The cabbage sweetness came out, so it was good because it was sweet and salty in the broth.The sauce is not special, with two types of soy sauce and chili sauce.The taste of kimchi was also a bit unfortunate.Food kimchi flavor...The people who work are kind and are busy.The interior is not very wide, so you can wait for Friday evening and weekends.
원본: 회사 근처에 있어서 가끔 직원들하고 가는 집입니다. 밀푀유나베, 스키야키 이런 메인 메뉴도 맛있고 가라아게 같은 사이드 디쉬도 맛있어요. 근처에 있다면 한번쯤 가볼만 합니다., 번역: It is a house that sometimes goes with employees near the company.Millet Yunabe, Sukiyaki's main menu is delicious, and side dishes like Karage are delicious.If you're nearby, it's worth a visit.
원본: 맛남 근데 가격이 좀 있음 그래도 먹을만하고 재방문의사 있음, 번역: It's delicious, but there's a little price.
원본: 건강한 메뉴, 매뉴와 인테리어를 고려했을때 부담없는 가격, 골목에 자리잡은 모습도 예뻐요산나물밥 부담스럽지도 않고 맛있게 잘 먹었어요. 가게가 아주아주 작아요.테이블 네개, 혼밥자리 두개정도 되는 거 같네요. 조용히 혼자 편하게 먹을 수 있는 분위기에요., 번역: Considering the healthy menu, the menu and the interior, the price and the alley are also beautiful.The store is very small.I think there are four tables and two Honbibap.It's a quiet atmosphere that you can eat comfortably alone.

 90%|████████▉ | 20163/22421 [02:40<08:01,  4.69it/s]

원본: 산토리 하이볼에서 보듯 일본의 느낌이 물씬 난다. 서비스를 많이 주신다. 단골이 많은 식당, 번역: As you can see in Santori High Ball, it feels like Japan.Give a lot of services.A restaurant with many regulars

 90%|████████▉ | 20164/22421 [02:40<08:01,  4.69it/s]

원본: 내가 먹어본 일본식요리중 인생맛집입니다.너무 유명해지면 먹기 힘들것 같아서 글쓰기가 망설여지는 집.오뎅탕의 국물이 어떻게 이런맛이 날까 궁금함.초밥 한땀한땀 맛잇는집..., 번역: This is a life restaurant in Japanese dishes I have eaten.If you become so famous, it will be hard to eat, so you can hesitate to write.I wonder how the soup of Odentang will taste.Sushi sweating house...
원본: 일본요리는 왠만한 강남 일식집보다 더 잘합니다~~강추, 번역: Japanese cuisine is better than some Gangnam Japanese restaurant ~~
원본: 할머니의 인심만큼이나 푸짐한 양3천원이라는 가격이 말도 안될만큼 정성있고 맛있는 떡볶이 였습니다늦게 가서 아쉽게 김밥이랑 순대는못 먹었어요 ㅠㅠ, 번역: The price of 3,000 won as much as my grandmother's human heart was ridiculous and delicious Tteokbokki.
원본: 사장님이 푸짐하게 주시고 맛도 부담없는 맛이라 좋습니다. 다 먹고 나갈때 아이를 데리고 온 엄마가 하는 얘기를 들었는데, 엄마가 어릴때 여기서 자주 먹었다고 하더군요. 그 얘길 들으니 정말 오랫동안 자리를 지키며 맛을 유지한 곳이라는 것이 느껴집니다., 번역: The boss gives you a lot and tastes good.When I went out, I heard a mother who brought the child, and when I was young, I ate it often.Listening to that, I feel that it is a place where I kept my seat for a long time.
원본: 착한 가격에 푸짐한 양. 국물이 깊으면서도 깔끔함. 멀리서도 찾아갈만한 떡볶이 맛집!, 번역: A lot of good price.The broth is deep and tidy.Tteokbokki restaurant to visit from afar!
원본: 의외인 곳에 위치해서 눈에는 잘 안띄는데 레트로 느낌이 예쁜곳입니다.동네주민이라면 가기좋을것같아요!, 번역: It is located in an unexpected place, so it is not noticeable.If you are a local resident, it would be nice to go!
원본: 인근에서 보기드문 캐쥬얼한 식당. 맛도 괜찮은 편입니다., 번역: A rare casual restaurant in the vicinity.The taste is good.
원본: 해산물 요리 전문점이죠... 전국 어디서나 맛볼수 있을 정도로 매장이 많아졌어요... 그래서 좋다구요... ^^오늘은 꽃게살비빔밥을 먹었습니다. 양념된 꽃게살과 밥을 따로 내주시는 방식은 양념을 기호에 맞게 조금씩 넣어가면서 맛보시라는 뜻이 있을 겁니다. 양념을 한번에 다 넣고 비비시면 입맛에 따라 짜거나 매울 수 있습니다., 번역: It's a seafood restaurant...There are so many stores that I can taste anywhere in the country...So it's good...Today I ate crab bibimbap.The seasoning crab meat and rice separately will mean to taste the seasoning little by little.If you rub it all at once and rub it, you can squeeze or spicy depending on your taste.
원본: 목동 현대41타워에 위치한 연안식당. 브레이크 타임 있고 베스트 메뉴는 역시 꼬막비빔밥. 고막이 듬뿍 들어있어 푸짐함! 양념은 메뉴에 순한 맛도 따로 있으니 입맛대로 주문 가능, 번역: A coastal restaurant located in Mokdong Hyundai 41 Tower.Brake time is the best menu.There are plenty of eardrums and rich!The seasoning has a mild taste in the menu, so you can order according to your taste.
원본: 여기는 진짜.. 두끼는 비교군이 안됩니다.종류가 진짜 많은데다 메뉴마다 퀄리티가 높은편.회전율도 좋아 주방에서 계속 ~이요, ~이요 하면서 음식이 새로 나와 튀김류가 엄청 맛있습니다.모두 맛봤지만 허니도넛이 가장 최고라고 들었는데 그 정돈 아니었어요. 그냥 겉만 조금 더 달콤 할까말까한 찹쌀도넛..이런저런 구비되어있는게 많아 주먹밥 만들어먹기 안내와 함께 위생장갑도 있습니다. 또한 덮밥도 충분히 해먹기 좋다고 하네요.떡볶이는 매콤치즈소스로 배합했는데 분말이라 치즈향도 강하고 좋았어요. 그런데 소스가 좀 짠 편이에요.이외에도 냉우동, 김치말이국수, 떡꼬치, 순대 등 모두 맛있으며 사진 상으론 채소+떡사리 코너와 음료 빼곤 모두 찍었으니 참고 되시길.참고로 식사시간 이외에도 항시 대기 필수입니다., 번역: This is real..Two meals are not comparable.There are a lot of kinds and high quality for each menu.The turnover is also good, and the food comes out in the kitchen.I had a taste, but I heard that honey donuts are the best, but it wasn't that tidy.It's just a little sweeter or not..There are so many things that are available.Also, rice bowl is also good to eat.Tteokbokki was mixed with spicy cheese sauce, but the powder was strong and good.But the sauce is a bit salty.In addition, cold udon, kimchi horse, noodles, rice cake skewers, and sundae are all delicious.For reference, it is always necessary to wait in addition to meals.
원본: 가성비 좋은 떡볶이 무한리필돈가스와 각종 튀김도 제공된다.원하는대로 소스와 사리를 넣어 만들어먹으면 된다., 번역: Tteokbokki infinite filled gas and various fries are also provided.You can eat it with sauce and saree as you want.
원본: 튀김이 맛있는 즉떡뷔페.매장 손님 수에 따라 튀김양을 조절해서항상 따뜻하고 바삭한 튀김이 준비되어있음.돈까스도 무한리필로 제공되는데꽤나 괜찮은 수준.사장님 내외도 친절하셔서 부담없이 먹을수 있다는 점도 장점.여기먹고는 두끼 다시는 못감., 번역: Tempura is delicious.Depending on the number of stores, the fried amount is always controlled, and warm and crispy tempura is always available.The pork cutlet is also provided with unlimited refills.The boss is also kind and can be eaten casually.After eating here, I can never give you two meals again.
원본: 저렴한 가격에 맛도 있어요. 돈까스 냉우동 등 사이드도 괜찮습니다, 번역: It tastes at an affordable price.The side of the pork cutlet cold udon is also fine
원본: 음.......간이 쎄지 않아서 대중적인 입맛을 가지신 분은 별로일 수 있을 듯, 번역: hmm.......The liver is not strong, so if you have a popular taste,
원본: 갈때마다 재료소진이여서 놀랐습니다. 식전스프도 맛있고 메인도  퍽퍽하지않고 소스 간이 적당해서 밥이나 빵이랑먹어도 맛있어요 !사람들 없을때 가면 분위기가 너무 좋아요 !, 번역: Every time I went, I was surprised that the ingredients were exhausted.The soup is delicious before the meal, the main is not so good and the sauce is suitable, so it's delicious to eat with rice or bread!When there are no people, the atmosphere is so good!
원본: 스프도 맛있고 다른 요리들도 맛있다 함박의 육즙이 느껴지면 더 좋을것같다, 번역: Soup is delicious and other dishes are delicious.
원본: 명품갈비설농탕은 안에 갈비가 적당히 들어있고 당면도 있어서 맛있게 먹었음! 고기듬뿍설농탕은 고기가 많이 들었지만 일반과 가격이 거의 두배 차이가나서 가성비는 떨어지는편임! 무료주차시설은  항상 만족!, 번역: The luxury ribs ribs are in a good ribs and have a vermice.The meat soup has a lot of meat, but the price is almost double because of the general price and price.Free parking facilities are always satisfied!
원본: 깔끔하고 맛있는 음식, 편한 주차장이 있어서 종종 갑니다. 화장실도 깨끗한 편입니다. 엘리베이터도 있어 이동이 편합니다., 번역: There is a clean and delicious food and a comfortable parking lot.The bathroom is also clean.There is also an elevator, making it easy to move.
원본: 설렁탕 먹을때는 항상 여기로 가요! 친절하고 변함없는 맛이에요, 번역: When you eat Seolleongtang, always go here!It's kind and unchanged
원본: 맛있습니다하지만 가격을 생각한다면 이가격에 더맛있는게 너무많이요, 번역: It's delicious, but if you think about the price, it's too delicious at this price.
원본: 동생아들 입대전 모임 모든 메뉴가 맛있었고 밑반찬도 간이 딱딱맞음 구워주는 서비스 굳, 번역: All menus before joining the younger brothers were delicious, and the side dishes were also tightly baked.
원본: 고기 맛잇고요, 잘 구워주세요! 반찬도 골고루 나와서 좋구요. 구워먹는 치즈도 맛잇어요 ^ㅇ^ 반찬으로 김치국 주시는 것도 맛잇어요, 번역: It tastes like meat, bake well!The side dishes are also good.The baked cheese is also delicious.
원본: 역시 돼지고기에 더 잘 어울리는 와사비!! 와사비를 주는 고기집이 더욱늘기를, 번역: Wasabi better suits pork!!The meat house that gives wasabi
원본: 개인적으로 먹어본 삼겹살 중에 제일 맛있었던 집. 직원분들이 고기를 직접 잘라서 구워주시는 게 편함. 밑반찬도 맛있는 것들이 꽤 많이 나옴.. 돼지고기 먹으러 가자면 자신있게 데려갈 수 있는 곳 ㅋ, 번역: Personally, the most delicious house was.It is convenient for employees to cut the meat and bake them.There are quite a lot of delicious side dishes..If you go to eat pork, you can take it with confidence ㅋ
원본: 아니 진짜 맛있네하남돼지집이 최애였는데 여기가 더 맛있음 삼겹살 육즙이 와우.., 번역: No, it's really delicious. Hanam pig house was the best..
원본: 매일 먹는 집밥을 제외 하고지금껏 살면서  가장 많은 횟수 로 먹은건  셀것도  없이삼겹살 이다 . 어릴적  심부름 장소중 하나 정육점신문지에 싸서  비닐 봉지에 두어근 싸들고 집으로 뛰어가면 어머니는 상추를 씻고 계셨고.. 그렇게 먹고 자라고 또한 대학가서도 엠티 동문 각종환영회등 모임에 는 삼겹살이 주인공 이였다 ㅎ;사회 나와서도 회식 은 또 삼겹살 ㅎㅎ 그렇게 헤아릴 것 도 없이 무수히 먹는 삼겹살 목살이가장 많이 먹은 음식이라는 것는  사실이다.대패삼겹살 와인삼겹살 숫붛 . 생고기 . 녹차 먹인 돼지대나무숙성 .  솥뚜껑 . 또 뭐 있지?? 암튼  이렇게 먹어 왔건만 ..가락동 화포 삼겹과 목살은 ... 처음 봤을때솔직히  살짝 충격 이였다.압도적 비주얼에  잠시 눈을 떼지 못했다.지금까지 먹어온 삼겹살 과는 차원이 다르다.소고기 버금 가는 고소함 과 부드러운 육질감탄이 저절로 나왔다  그리고 참 맛있었다.마무리 비냉도 매우 괞찮아서 기분까지 좋아졌다 ㅎ당분간은 이 삼겹살 만 먹을 거 같다. ㅎ또 몇년?? 이 지나면  또 어떤 삼겹살이 내게 올까 ??, 번역: Except for the house rice that I eat every day, I have eaten the most frequently and eat it.When I was young, I wrapped it in a butcher newspaper, wrapped it in a plastic bag, and ran home..It is true that pork belly was the main character in the gathering of various welcoming meetings such as MTI alumni.Place pork belly wine.raw meat .Green tea fed pork.Pot lid.What else is there?Anyway, I've eaten like this..Garak -dong pork belly and neck...Honestly, it was a bit shocking.I couldn't take my eyes off for a while.It is different from the pork belly that has been eaten so far.Beef is a bit of savory and soft meat.The finishing non -cold was also very bad, so I felt better.How many years ??What else will come to me after this?
원본: 만족합니다 맛있어요 좋아요 맛있어요 좋아요 맛있어요좋아요, 번역: Satisfied, it's delicious. It's good. It's good. It's good.
원본: 육즙이 터지는 삼겹살 완전 맛있네요밑반찬도 깔끔하니 맛있고, 주말에 가서 주차 공간도 여유롭고~너무 좋았습니다, 번역: The juicy pork belly is so delicious.
원본: 마포 본점만 못함, 번역: Mapo headquarters only
원본: 해물은 대체적으로 싱싱한 편이고 라면은 가격대 비에 비싸긴 하지만 푸짐해서 한번쯤은 먹을만 합니다., 번역: Seafood is generally fresh, and ramen is expensive in price rains, but it is rich and worth eating.
원본: 서비스 분위기 모두 보통 정도.우리만 이상한건지 아니면 그때만 특히 이상했던건지해산물이 신선하지않아서 먹다 나왔네요., 번역: The service atmosphere is all normal.It was only weird or especially strange at that time, so the seafood was not fresh.
원본: 작은 규모지만, 해산물류가 풍성하게 나오는 곳. 해물라면 짱!, 번역: It's a small, but a plenty of dissolution.If it's seafood!
원본: 가격은 다소 비싸지만 모든 음식이 맛있다! 특히 무쇠솥밥은 필수 주문이다!, 번역: The price is a bit expensive, but all the food is delicious!Especially iron pot rice is a must!
원본: 참고로 자리가 적어서 식사시간엔 기다릴 가능성이 높습니다. 음식은 정갈하고 깔끔했어요. 일식집과 위스키바를 믹스한 인테리어 느낌? 이었습니다., 번역: For reference, it is likely to wait during the meal time.The food was tidy and tidy.The interior is mixed with Japanese restaurants and whiskey bars?It was.
원본: 음식이 깨끗하고 전반적으로 맛이좋아용~충무김밥은 없어졌습니다깨끗하게 음식을준비하시는게 보기좋았어요 ㅎㅎ 단지 가격이 인상되서 양에비해 비싸다는 느낌이있네요~ 금액은 달라졌으니 사진참고해주세요~, 번역: The food is clean and the overall taste is good ~ Chungmu Gimbap is gone. It was nice to prepare the food cleanly.
원본: 전복솥밥 전복도 튼실하고 맛있었어요 또 먹고싶어요 ㅎㅎ 누룽지도 엄청 맛있고!! 굴전도 시켰는데 굴전 시킨게 진짜 신의한수였어요 굴전때문에라도 또 가고싶을정도예요 굴전진짜 맛있음!!!, 번역: The abalone rice abalone was strong and delicious.!It was also a real god, but I wanted to go again because of the oyster war.!!
원본: 동네 흔한 굴국밥, 꼬막비빔밥보다 한 5천원 비싸다. 하지만 그만큼 고급진 맛이 난다...!!깔끔한 해물요리를 먹고싶은 날엔 또갈거다.특히 굴전은 상상속의 맛이다 ㅋㅋ하지만 좁은 실내. 불편한 주차는 감수해야한다 ㅜㅜ, 번역: It is 5,000 won more expensive than common oyster soup and bibimbap in the neighborhood.But it tastes like that...!!I will go again when I want to eat neat seafood dishes.In particular, oyster war is the taste of imagination ㅋㅋ but a narrow interior.You have to take uncomfortable parking.
원본: 청담점에 비해 더 서민적이라고 한다. 동네사람들이 주로 찾는듯 보였으며 맛이 깔끔하다. 해산물쪽이라 그런지 가격대가 약간 있는 편이다., 번역: It is said to be more common than Cheongdam.The people in the neighborhood seemed to be looking for it and the taste was clean.It's a seafood side, so there's a little price range.
원본: 전복솥밥 맛있어요. 충무김밥에 주는 오징어랑 깍두기 다 맛있어요, 번역: Backpot rice is delicious.The squid and diced kakbab for Chungmu Kimbab are delicious
원본: 이곳정도면 치킨에 맥주먹기에는 좋은곳이라고 생각합니다 종종 생각나는곳이고동네에서 멀지않은곳이라 열번 넘게 방문한 곳이구요제일 자주먹는 메뉴는 누룽지양념통닭에 치즈와 옥수수콘 추가입니다양은 두명기준 치킨 한마리면 적당합니다맛은 거의 일정한 편이나누룽지는 어떨땐 잘눌어져있고 어떨때는 그냥 밥 느낌일때가 있어요갈때마다 느끼는건 사장님이 손님들앞에서 직원분들께 너무 소리를 지른다는것주방에 요리하시는 나이많은분께나 어린 알바생에게나 혼내시는 경우를 자주보는데내부도 시끄럽고 손님도 많고 정신없는건 이해하지만 그럴때마다 가게안 분위기가 좋진않습니다그래도 손님들한테는 사장님이나 직원분이나 친절하십니다, 번역: I think it's a good place to eat beer for chicken, and it's not far from the neighborhood.It's appropriate. It's almost a certain side, and sometimes it's just a good time, and sometimes it's just like rice.I often see the case of being confused, but I understand that my banks are noisy, there are many guests, and they are crazy, but every time I do, the atmosphere of the store is not good.
원본: 콘치즈가 제일 맛있는 것 같다. 밑에 리뷰처럼 예전만 못한 것 같지만 가성비가 좋다., 번역: Concees seem to be the most delicious.Like the review below, it doesn't seem to have been like before, but the cost is good.
원본: 처음먹었을땐 담백하고 고소하니 맛있었음. 내 입맛이 변한건지 음식이 변한건지, 오랜만에 먹으니 누룽지 빼고는 맛이 없음. 누룽지 맛도 평균. 닭은 퍽퍽해서 목넘김이 힘듬. 누룽지는 아래깔려있이니 당연히 양적음., 번역: When I ate it for the first time, it was delicious because it was light and savory.Whether my taste has changed or the food has changed, it has been eaten for a long time.Nurungji taste is also average.The chicken is so hard that the neck is hard.Nurungji is laid below, so of course.
원본: 1회 방문. 통닭과 치즈와 옥수수와 누룽지의 조합이 엄청나다., 번역: One visit.The combination of chicken and cheese, corn and Nurungji is enormous.
원본: ㅣ, 번역: tooth
원본: 최근들어, 아니 20살 이후로 베트남 가서 먹었던 쌀국수와 분짜보다 매우 맛있게 먹은 곳입니다.맛도 맛이지만 깔끔한 인테리어로 두번 사로 잡네요. 분짜의 큼직큼직한 고기와쌀국수의 고소한 국물. 너무 좋았습니다., 번역: Recently, it is more delicious than the rice noodles and jeans that have been eaten in Vietnam since the age of 20.It tastes good, but it is captivated twice with a clean interior.The big broth of the large meat and the rice noodles.It was so good.
원본: 인테리어도 예쁘고 음식도 깔끔하고 맛이 좋습니다. 짜조는 라이스페이퍼가 조~금 질겨요ㅠㅠ!! 그래도 전체적으로 모두 맛있습니다!, 번역: The interior is pretty and the food is clean and tasty.The rice paper is tired of the rice paper.!Still, it's all delicious as a whole!
원본: 친구가 성신여대에 방문하게 되면 무조건 데려가는 맛집! 베트남 음식임에도 불구하고 향신료향이 쎄지 않아서 좋고 플레이팅과 가게 내부도 예뻐서 데려간 친구들 모두 만족해한다 :), 번역: When a friend visits Sungshin Women's University, he takes it unconditionally!Despite the Vietnamese food, the spices are not strong, and the plating and the interior of the shop are so pretty :)
원본: 매장도 예쁘고 반쎄오 파는곳 흔치않은데 너무 맛있게 잘 먹었어용!, 번역: The store is pretty and it's rare to sell Banseo.
원본: 가끔 생각나는 맛이에요. 은근 맛있네요!! 만족 만족!, 번역: Sometimes it tastes like.It's delicious!!Satisfaction!
원본: 분위기 좋았고 음식도 맛있었습니다 일하시는 분들도 친절했어요, 번역: The atmosphere was good and the food was delicious.
원본: 정말 좋아하는 태국 음식점 중에 하나. 이수점 분점 내줬다. 짱, 팟타이도 태국에서 먹는거랑 젤 비슷하고 면발도 얇아 좋다. 하지만 무엇보다 가격이 진짜.. 너무 좋음, 번역: One of my favorite Thai restaurants.I gave a branch point.Chan and Pat Tai are similar to the gel in Thailand and the noodles are thin.But most of all, the price is real..So good
원본: 진짜 맛있어요 태국음식점도 복불복 많은데,정말 현지맛같은 느낌이예요 가격도 저렴해서 부담없어요, 번역: It's really delicious.
원본: 아는 형네 동네에 낮술하러 칮아갔더니 정말 맛있는곳을 소개시켜준디면서 먹여준 이것...진심 맛있더라!!, 번역: I knew it in the neighborhood of my brother, and I introduced me to a really delicious place...It was really delicious!!
원본: 여기 유명해지지 않았으면 하는 음식점임태국에서 먹은 맛집들보다 맛있음갈일있을때마다 매일 먹으러 가는 음식점브레이크타임있음 오후3시부터 못먹음.., 번역: I don't want to be famous here..
원본: 시끄럽고, 불친절해서 맛을 느낄 수 없던 집. 힙한 게 아니라 엉망진창인 것 같다 ㅎㅎ 다시는 안 갈 것 같고, 주변 사람들에게 널리 널리 가지 말라고 얘기해주고 싶음., 번역: The house was noisy and unknowingly.I don't think it's a hip, but I don't think it's going to go again.
원본: 저녁 때 갔는데도 제법 웨이팅이 길어서 20분 가량 기다렸습니다. 보통 바베큐 플래터는 엄청 크고 양이 많아 둘이 먹기 부담스러운데 효자바베-자는 둘이 먹으면 딱 배부른 정도였어요. 첨엔 괜찮았는데 시간이 지날수록 고기가 식어서  그냥 소스빨로 먹는 느낌이 있었습니다., 번역: Even though I went in the evening, I waited for about 20 minutes because of the long weight.Usually the barbecue platter is so big and large that it is burdensome for them to eat, but Hyoja Barbae was just full when they eat.At first, it was okay, but as time went by, the meat cooled down and it felt just eating with sauce.
원본: 기대하고 먹을만한 메뉴는 아닌데 바글바글한 인파탓에 기대했다가 실망했다. 예측되는 정도의 맛, 번역: It wasn't a good menu to eat, but I was disappointed because of the crowds of crowds.Taste of predicted
원본: 음 파스타는 실패. 여자 셋이서 파스타에 바베큐 중자 시키니까 너무 충분해서 남음, 번역: Well pasta fails.Because the three women are in the pasta, the barbecue is so good that it is so enough
원본: 공간도 넓고 빙수는 4대빙수안에 드는 프랜차이즈답게 맛있습니다근데 가격은 보통을 줬어요요즘 모든 가게 빙수값이 많이 비싸요;;:, 번역: The space is spacious and the shaved ice is like a franchise on the 4 Liangsuan, but the price is usually given.
원본: 멜론빙수의 멜론이 정말 맛있네요. 양이 좀 적은게 아쉽지만.. 망고치빙이도 맛은 있는데 양이 아쉬워요;, 번역: Melon Bingsu's melon is really delicious.It's a pity that the amount is a little small..Mangochi is also tasted, but the amount is regrettable;
원본: 엘가커피의 시그니처메뉴인 메론빙수를 먹으러 가는 곳입니다, 번역: This is the place to eat Melon Bingsu, the signature menu of Elga Coffee.
원본: 석계역에서 산지 15년째인데, 이 곳 커피 맛이 제일 좋다고 생각합니다. 대학생때부터 시험공부도 하고 했던지라 애착이 가는 곳입니다., 번역: It's been 15 years in Sukgye Station, and I think the coffee is the best.Since I was a college student, I had been studying for exams.
원본: 최자로드에 방영된 것을 보고 만두돌이인 내가 가리봉동에 있는 월래순 교자관을 방문했다. 사람이 엄청 많을 줄 알았는데 주말 오후 6시경 방문했는데도 한가했다.메뉴는 군만두,찐만두,오향건두부를 시켰다. 오향건두부부터 나왔는데, 그냥 오향건두부 맛이였다. 만두와 곁들여먹이면 맛있다.최자가 한것 처럼 간장과 흑식초를 2:1로 섞고 마늘과 고추 한수푼을 넣었는데, 흑식초 맛이 역시 좋았다. 소스맛 최에에고 !!그리고 만두가 나오고, 군만두는 역시 양이 푸짐했다 군만두,찐만두 둘 다 육즙이 가득했고, 만두의 피는 쫀득쫀득하니 일품이였다.나는 앞으로 불행질꺼 같다. 앞으로 여기 만두보다 맛있는 만두집을 찾을 수가 없으니, 만두를 먹을때 마다 이 곳과 비교를 하게 되겠지.... 불행을 돈 주고 산 기분이다., 번역: Seeing it was aired on the Choija Road, I visited Wolrae Soon Gyo -gwan in Garibong -dong.I thought there were a lot of people, but I visited around 6 pm on weekends.The menu has a dumpling dumplings, steamed dumplings, and five flavored tofu.It came out from the tofu tofu, but it was just a flavored tofu tofu.It is delicious to feed with dumplings.As Choi did, he mixed soy sauce and black vinegar 2: 1 and put garlic and red pepper.Sauce Taste Choi Ego!!And the dumplings came out, and the military dumplings were also rich.I feel unhappy in the future.I can't find a delicious dumpling house than the dumplings here, so I'll compare it with this place every time I eat dumplings....I feel like I bought unhappy.
원본: 군만두 맛잇어요, 양도 꽤 되어요. 가지튀김은 군만두만 못하더군요. 옆테이블에서 시킨 꿔바로우 좋아보여서 부러웟어요 ㅋㅋㅋ 가격대도 착한 편인데, 계란찜 서비스도 주셧어요 ^^, 번역: It tastes good dumplings, and the amount is quite a bit.I couldn't do the dumplings of eggplants.I was envious of it because it looked good at the side table.
원본: 맛있음 소스는 자기취향대로 만들어서 찍어먹으면 된다 최자로드에 나와서 사람들이 많이오는듯포장도된다 주차공간이 없다고 봐야한다 가게앞에 한대만 주차가능, 번역: Delicious sauce can be made by making it according to your taste.
원본: 최자로드로 유명한 집. 가리봉시장 안에 위치, 주차는 최대 3대까지 가능할 듯, 중국느낌이 물씬나는 맛, 향신료 느낌이 어색하다, 양은 엄청 많다., 번역: A famous house for Choija Road.Located in Garibong Market, parking is up to three units, and the taste of Chinese feel, the spice feeling, and the amount of spices are huge.
원본: 저는 맛있게 먹었는데 중국식이라 향이 좀 있어서 호불호가 있을 수 있어요!시킨거 전부 추천 드리고, 가성비 짱입니당계란볶음밥에 마파두부 비벼먹다가 군만두 하나씩 집어먹으면 꿀맛👍🏻, 번역: I ate it deliciously, but it's Chinese, so there's a little fragrance.It is recommended that all I made it is recommended.
원본: 킹성비가 내려오는곳.만두의 양부터 어마어마하다술먹으면 더 맛있을곳, 번역: Where the King's rain comes down.From the amount of dumplings, it will be more delicious to eat.
원본: 총평: 싸고 맛있고 양많은 중국식 만두꽤나 외진 곳에 위치한 터라 찾아가기가 쉽지 않음에도 항상 최소 30분은 대기해야 할 정도로 북적임향신료향과 고기향이 강하게 느껴져 중국식 만두가 무엇인지 제대로 알 수 있음가격도 부담스럽지 않아 만족스럽게 식사할 수 있어 거리만 가깝다면 자주 들르고 싶은 거게, 번역: Comprehensive: Cheap, delicious, and many Chinese dumplings are located in a very remote place, so it's not easy to visit, but the crowds of ledger and the meat are so strong that they should be waiting for at least 30 minutes.You can eat satisfactorily. If you are close to the street, you want to stop by often
원본: 여러명이서 다녀왔습니다. 일단 군만두 최고 입니다. 완탕은 조금 심심한 맛인데 간장 넣어서 먹으면 딱 맞구요. 군만두도 육즙 터집니다!또 가고 싶은 곳입니다., 번역: I have been to several people.First of all, it's the best dumpling.Wantang is a bit boring, but it's perfect to eat soy sauce.Dumplings burst juicy!It is a place I want to go again.
원본: 가성비 갑 만두정말 많고 겉바 속촉 제대로 느낄수 있는곳 힘들게 찾아간 보람이 너무 있었다 ㅠㅠJMT, 번역: There was a lot of money dumplings, and there was a lot of reward that I could find a place where I could feel the outside.
원본: 워낙 유명한 맛집. 찾아가는데 조금 귀찮았고 가성비가 좋았다. 배부른상태에서 가서 다양한 종류를 못먹어봐서 아쉽다. 나중에 한번 더 가보고싶다., 번역: A famous restaurant.It was a bit annoying to go and the price was good.It's a pity that I can't eat a variety of different kinds.I want to go one more later.
원본: 주차는 3대정도 가능한데 가게 앞 물건들 상황에 따라 다른 듯.. 화장실은 내부에.., 번역: There are only three parking, but it seems to be different depending on the situation in front of the store..The bathroom is inside..

 90%|█████████ | 20242/22421 [03:00<08:31,  4.26it/s]

원본: 회사 점심 회식 목적으로 방문했습니다.일단 식당이 위치한 곳이 중국 분들이 많이 거주하시고 생활하는 공간이라 깔끔하다거나 안전한 느낌은 아닙니다.식당 자체 평가로는 가성비가 굉장히 뛰어납니다. 기본적인 만두 개념을 다시 느낄 수 있는 식당입니다. 큰 접시와 큰 찜통에 가득찬 만두를 식탁에빈공간없이 주문해도 가격이 굉장히 저렴합니다.만두 속또한 고기와 야채가 적당히 어우러져 영양면에서도 우수하다고 생각됩니다.술한잔 하기도 좋고 만두 많이 먹고싶을때 가면 좋은 식당입니다.소룡포는 육즙이 많이 부족한 편입니다.전체적인 메뉴가 피가 많이 두꺼운편이고 샐러리를 만두 재료로 사용하기 때문에 샐러리 향이 싫으신 분은음식에 불호적일수도 있다고 생각합니다.와 이 집 만두 진짜 잘한다 느낌은 아니지만저렴한 가격에 푸짐하게 먹을수 있는 곳이라고 생각합니다., 번역: I visited the company for lunch.The place where the restaurant is located is a space where many Chinese people live and live, so it is not neat or safe.The price of the restaurant is very good.It is a restaurant where you can feel the basic dumpling concept again.The price is very cheap even if you order dumplings filled with large plates and large steamers without a dining table.In addition, the meat and vegetables in the dumplings are moderately combined, so I think it is excellent in nutrition.It's a good restaurant to have a drink and when you want to eat a lot of dumplings.Soyongpo is not enough juicy.Since the overall menu is a lot of blood and the celery is used as a dumpling ingredient, I think that if you don't like the celery, you may be dissatisfied with the food.Wow, I don't feel really good, but I think it's a place where you can eat at a low price.
원본: 찐교자와 마파두부를 먹었는데 둘 다 맛있었음. 다음엔 마파두부와 밥을 꼭 함께 먹어봐야겠다!, 번역: I ate steamed gyoza and mapo tofu, both of which were delicious.Next time, I must eat Mapa Tofu and Rice together!
원본: 평일에 가면 인당 만4천원 정도의 가격으로 샤브샤브와 뷔페를 즐길수 있어요. 샐러드 바 음식이 나름 괜찮아서 등갈비랑 간장 치킨류 가져다 먹고 야채도 계속 먹을수 있어서 좋았습니다. 다 먹고 칼국수나 밥도 가져다가 조리해먹을수 있어요. 빙수랑 케익도 있긴 한데 케익은 그렇게 맛있지는 않아요. 가성비 괜찮은 샤브샤브집입니다., 번역: If you go on weekdays, you can enjoy shabu -shabu and buffet at a price of about 4,000 won per person.The salad bar food was fine, so I could eat back ribs and soy sauce chicken and continue to eat vegetables.You can eat it all, bring kalguksu or rice and cook it.There are bingsu and cakes, but the cake is not so delicious.This is a decent shabu -shabu house.
원본: 가성비좋은 샤브샤브 전문점으로 유명한 바르미다운 인테리어가 돋보였습니다.가격대비 퀄리티 좋은 편이고 음식 종류가 다양한 것도 장점이에요. 특히 샐러드 종류가 다양한 편이었고 뜬금없지만 기름떡볶이가 맛있었습니다. 보온 철저히 한다고는 하지만 가끔 식은 음식도 있어서 아쉬웠습니다.무료 주차가 되고 개별룸이 여러개 있다는 것도 큰 장점입니다. 화장실은 식당 밖 건물 같은 층에 있습니다. 깨끗한 편이에요!, 번역: Barmi -down interior, famous for its good shabu -shabu specialty store, was outstanding.It is also good for the price for the price and the variety of foods.In particular, there were various types of salads, and it was not crazy, but the oil tteokbokki was delicious.It was said that it was a thorough warmth, but sometimes there was a cold food.It is also a great advantage that there are free parking and several individual rooms.The toilet is on a floor like a building outside the restaurant.It's clean!
원본: 샤브뷔페 여기가 젤 맘에듬. 샐러드도 신선하고 회무침도있고. 호박죽 맛잇음, 번역: Shabu Buffet This is the gel.The salad is fresh and there is a sashimi.Pumpkin porridge taste
원본: 배달도 좋지만 직접가서먹어도 괜찮다 양많고 착한맛도 맛있다 다른지점보다 맛이 괜찮은편이다, 번역: Delivery is good, but it's okay to go and eat it.
원본: 추천받아 가봄배민 주문 계속 옴국물은 다른 지점에 비해 적은 편맛 괜찮음재방문의사 있음, 번역: Recommended for the spring Baemin order continues to om -soup compared to other points.
원본: 여기는 진짜 양이 많고 맛있어요. 식어도 맛있구!! 엽떡8 년찬데, 이만큼 양 주는 집은 여기말고 없어용, 번역: Here is really a lot and delicious.It's delicious even if it cools down!!This is 8 years of lobster, but there are no houses here.
원본: 대기가 엄청 길어요 두시간 기다린듯, 대기있으면 2시간 제한있는데 우린 그냥 적당히 먹고 나왔는데 다드신거 맞냐고 너무 먹고나와서 걱정해주시더라구요 그 모습이 친절해보였어요 비쥬얼 품질은 대만족인거같아요 가격이 비싸서 그렇지, 번역: The atmosphere is so long. I waited for two hours, and I had a 2 -hour limit, but we just ate it, but we ate it.
원본: 여자친구와 데이트 코스로 방문 했습니다분위기가 너무 좋고 우선 고기맛이 최고!플레이팅도 깔끔해서 먹기 아까울정도 ㅠㅠ또 다른 메뉴도 재 방문해서 먹어 보려구요, 번역: I visited a date course with my girlfriend.Plating is also clean, so it's a waste to eat.
원본: 친구커플이랑 저녁 늦게 갔던 오사카하루친구는 자주 가는 곳이라고 했다일단 야끼니꾸는 합격 ,고기의 질도 좋고귀엽게 이름표도 붙어있어  더 먹고싶으면 추가도 가능했다혼마구로도후는 처음 먹어봤는데 진짜 맛있었음 직원한테 이게 무슨 젓갈이냐고 물어봄 ㅋㅋㅋ 참치내장젓갈이라 하심버섯 ,두부,젓갈의 삼합  굿!젓갈 비린내 하나도 안나고 고소한맛!와사비명란파스타랑 로제크림파스타는 생각보다 별로 ...., 번역: Osakaharu friend who went late with a friend couple said that it is a place to go to the place.Ask what's the salted fish lol.No fishy fishy fishy taste!Wasa screams pasta and Rose Cream Pasta are much better than you think....
원본: 일본에 온 것 같은 이색적인 분위기의 야끼니꾸 전문 레스토랑. 야끼니꾸에 포함된 고기 종류도 다양하고 나름대로 좋은 부위 위주로 선별해서 세트 메뉴로도 팔고 있는데, 레스토랑 분위기가 (조금) 고급스러운 일본식당 느낌이라 특별한 날에 분위기 내기에 좋았어요. 야끼니꾸는 질 좋은 부위를 제공하고 있지만 퀄리티는 그 가격만큼은 아니었던 것 같습니다. 야끼니꾸 프리미엄 스페셜에 진갈비 추가해서 정말 다양한 종류로 먹었는데 업진살이 제일 괜찮았어요. 마지막에 소유라멘 먹었는데 국물부터 면발까지 라멘은 정말 맛있었습니다!식당 앞에 주차할 수 있는 공간이 2-3대 정도 있고, 예약하고 가시는게 편할 거예요. 시간 잘 맞추면 예약없이도 들어가는 것 같은데 피크타임에는 기다리는 사람들이 엄청 많더라고요. 화장실은 그럭저럭 깨끗한 편이었습니다., 번역: Yakiniku restaurant with a unique atmosphere that seems to come to Japan.There are many kinds of meat contained in Yakiniku, and they are also selected as a set menu, and the restaurant atmosphere is a little luxurious Japanese restaurant.It offers a good quality part of yakini, but the quality was not as much as that price.I added Jean Ribs to the Yakiniku Premium Special, and I ate it in a variety of kinds.At the end, I ate Soyu Ramen, but the ramen was really delicious from broth to noodles!There are about 2 3 units to park in front of the restaurant, and it will be convenient to make a reservation and go.If you match the time, it seems to go in without a reservation, but there are a lot of people waiting for the peak time.The bathroom was clean.
원본: 별 1점 주기도 아깝네요. 연어는 먹자마자 역한 맛이나고, 차슈 토마토 가라아케는 고기 샐러드 토마토의 최악의 조합. 샐러드에 슈가파우더는 이해할수 없네요. 달게만 만들어서 손님에게 내놓으면 좋아할줄 아셨나보군요. 음식하는 사람으로서 부끄러운줄 아세요., 번역: The star one point is also a waste.Salmon tastes like as soon as you eat, and Chashu Tomato Karaake is the worst combination of meat salad tomatoes.Sugar powder is not understood in the salad.I think you would like to make it sweet and give it to your guests.Know that you are ashamed as a food person.
원본: 야끼니꾸 소고기도 너무 훌륭하고치킨가라아게는 뻑뻑살 1도 없이 살살녹았어요ㅜㅜ치킨전문점보다 맛있다는...먹을수록 행복해지는 음식이었습니다번창하세요~^^, 번역: The yakiniku beef is so great and the Chi Kinara Lage is melted gently without any stiffness...The more you eat, the more you become a happy food.
원본: 다양한 부위별로 야끼니꾸를 즐길 수 있는 곳입니다프라이빗하면서도 고기냄새 많이 없이 야끼니꾸 즐기기 좋습니다 :), 번역: It is a place where you can enjoy yakiniku for each various parts.
원본: 깔끔한 분위기에 깔끔한 플레이팅까지,, 감사하게 잘 먹었습니다.이런 맛집이 잘되야할텐데 이미 잘되고 있는 것 같아 걱정은 없네요 ^__^, 번역: Thank you very much, even clean plating with a neat atmosphere.I think it's going to be a good restaurant, but I don't have to worry about it.
원본: 웨이팅만 없다면 진짜 맨날 가고싶음같이 간 친구들은 또 가자고 멀리서도 오는곳ㅋㅋ맛도좋고 분위기 좋고 뭣보다 플레이팅이 예뻐서음식나오면 그냥 기분이 좋음ㅋ, 번역: If you don't have a waiting, you want to go to your friends.
원본: 소비자의 심리란 참 알 수 없다. 가게 인테리어만 괜찮으면 음식의 맛은 상관이 없단 말인가? 차라리 커페로 만들었으면 나았을뻔. 음식 맛도 그저 그런데 가격은 오지게 비싸다. 고기집에 어울리지 않는 인테리어는 부산스럽고 집중이 안된다. 이쁘다고 그래서 맛집이라고 점수를 받은 것이라면 그것도 이 가게의 재주일 것이다., 번역: Consumers' hearing is unknown.If the interior of the store is okay, the taste of food doesn't matter?I would have been better if I had made it a krpe.The taste of food is just expensive.The interior that does not suit the meat house is Busan and cannot be concentrated.So if you're pretty, it's also the talent of this store.
원본: 고기맛있구 친절해서 좋았어요~ 딸기모찌리도후 존맛!!! 자꾸 생각나고 빨리 또 가고싶네요, 번역: The meat was delicious and it was nice ~!!I keep thinking and I want to go again quickly
원본: 고기는 맛있음.비싸다.서비스는 엉망. 전반적 불친절 정신없는., 번역: The meat is delicious.expensive.The service is a mess.Overall unkindness.
원본: 오랜만에 나온 을지로. 을지로는 방문할 일이 없지만 이미 검증된 곳들이 많기에 크게 걱정할 일이 없음. 그런의미에서 이곳도 검증이 완료된 곳.이 집의 대표메뉴는 오무라이스와 카츠산도 라고 하는데 양이 애매해서 카츠산도 대신 스파게티를 시킴. 참 잘 시킨듯 싶었음.오무라이스는 과하지않은 소스의 단맛과 적당한 깊은 맛. 그리고 부드러운 계란이 덮여져 맛있음. 인스타용으로 커팅순간 동영상 찍게도 해줌.더 맛있었던 것이 매콤크림스파게티. 느끼할 수도 있을 크림을 고춧가루로 잘 잡아냈다고 생각함. 손이 가게하는 느끼함. 그리 맵지도 않음.힙지로 이기에 가성비는 물건너갔지만 맛이 있어 가격표에 크게 눈이 돌아가지 않는 곳., 번역: Euljiro after a long time.Eulji has nothing to visit, but there are many proven places, so there is nothing to worry about.In that sense, this place is completed.The representative menus of this house are called Omurice and Katsudo, but the amount is ambiguous, so Katsudo is spaghetti instead.I wanted to make it very well.Omurice is a sweet and appropriate deep taste of the sauce.And soft eggs are covered and delicious.You can also take a video of the cutting moment for Instagram.The more delicious thing was spicy cream spaghetti.I think that the cream that I might feel is well caught with red pepper powder.I feel that my hands are going to go.Not so spicy.It's a place to go to the hip paper, but it's tasted, but it's a place where you don't have much eye on the price tag.
원본: 오무라이스와 가츠산도가 유명한 곳. 음식 전반적으로 맛이 좋음. 가격도 나쁘지는 않음. 다만 가츠산도는 인터넷에서 화제가 된 것에 비하면 그다지 특색있는 맛은 없었음. 오히려 게살 크림 리조또가 히든카드였음. 꾸덕하고 담백한 맛에 약간의 매콤한 맛이 일품임. 음식은 괜찮았으나 주말 낮이어서 그런지 줄이 매우 길었음. 줄도 길었는데 줄 서는 환경이 그닥 좋지는 않음. 계단이 좁다보니 답답한 느낌은 어쩔 수 없음. 가기 3일 전에 예약 필수로 해야 함., 번역: Omurice and Katsudo are famous.The whole food tastes good.The price is not bad either.However, Katsudo was not very unique compared to the topic on the Internet.Rather, the crab cream risotto was a hidden card.It is a great taste and a little spicy taste.The food was fine, but the weekend day was very long.The line was long, but the line is not very good.The stairs are narrow, so I can't help it.It should be required to make a reservation three days before going.
원본: 을지로 치고 규모가 크다. 특히 천고가 높아서 더 그래보임. 식기류 예쁘지만 사용 불편하고 직원들은 친절. 맛은 그냥 그랬다. 다만 가격이 그렇게 비싸진 않아서 한번 오고 또 오진 않을듯.. 한번쯤 오기 좋다. 웨이팅 있음., 번역: It is big and big.In particular, it looks more likely because of the high heaven.Dishes are pretty but uncomfortable and employees are kind.The taste was just like that.However, the price is not so expensive, so I will not come once again..It's good to come once.Waying.
원본: 힙한 을지로의 대표 맛집, but 바지락조개의 해감상태 실망!, 번역: The representative restaurant of Hiphan Euljiro, but the clam shellfish is disappointing!
원본: 왠 인쇄공장사이에 이렇게 예쁜집이 잇는지.. 다들 엄청 헤메요ㅋㅋ찾기 힘들어요ㅋㅋ 가격은 조금 잇는편이에요. 의외로 에그인헬이 제일 맛잇엇고, 오므라이스는 그냥 쏘소!, 번역: Why is there such a pretty house in the printing factory?.Everybody's so huge lol It's hard to find it.Surprisingly, egg -inhel is the best, and Omurice is just Soso!
원본: 찾아가기 어려운데 지도 보고 가세요! 5시 부터 저녁인데 웨이팅 길었어요. 음식은 정말 맛있어요. 재방문 할 예정이에요, 번역: It's hard to visit, but go to the map!It's dinner from 5 o'clock, but it was long.The food is really delicious.I'm going to return to visit
원본: 이렇게 간판도 잘 안보이는 곳 건물에...2층에..숨어있는데 예약안하고 가면 웨이팅입니다...꼭하세요..저희는 예약해서 금방 들어갔어요. 을지다락 시그니처 메뉴 두개 먹었는데 둘다 맛있었구요 다락 오므라이스는 시키시면 계란 칼로 갈라주시는거 영상 찍을 시간도 줍니다ㅋㅋㅋ맛잇고 분위기 좋아요, 번역: In the building where the signboard is not visible...On the second floor..If you do not make a reservation, we are waiting...Be sure to do it..We made a reservation and went in quickly.I ate two menus, but both were delicious.
원본: 오므라이스가 이렇게 맛있는 음식인지 처음 알았어요. 오므라이스 꼭 드셔보세요...크림 파스타도 매콤해서 맛이 좋았어요. 뿐만아니라 좌석마다 무선충전기가 있어 편리했습니다.요즘 뜨는 힙지로답게 웨이팅 많습니다... 예약은 꼭 하세요., 번역: I first knew it was such a delicious food.Please try omelet...The cream pasta was also spicy and it tasted good.In addition, each seat has a wireless charger.These days, there are many waiting...Be sure to make a reservation.
원본: 테이블 간격이 좁지만 짐보관과 휴대폰 충전이 편하게 되어있어 인상적이였어요맛은 괜찮지만 다소 비싼편생수는 분명 병으로 주시는데 컵에서 비린내가 심하게났네요 물컵도 세제로 꼭 설거지 해야 물비린내 안나요 !, 번역: The table spacing was narrow, but it was impressive because it was easy to store luggage and cell phone.
원본: 평일 점심에 방문했는데, 오픈 시간 전부터 줄 서있는 맛집입니다! 음식이 좀 비싸긴 해도 맛은 최고! 직원분들도 친절하시고, 점심은 12시 30분과 1시에 예약이 된다고 하니 참고하시면 좋을 것 같아요, 번역: I visited for lunch on weekdays, and it is a lining restaurant before the opening time!Even though the food is a bit expensive, the taste is the best!The staff are also kind, and the lunch will be reserved at 12:30 and 1:00.
원본: 웨이팅하는 계단 위험하고, 웨이팅도 깁니다.인스타용으론 핫하지만 제 기준으로 맛집은 아니에요.가격도 많이 비쌉니다.데이트로는 가볼만한듯 하네요., 번역: The staircase to wait, and the waiting is also long.It's hot for Instagram, but it's not my restaurant.The price is also very expensive.It seems to be a dating.
원본: 인기 많은 곳이라 조용히 밥먹기는 불가능하지만 맛있게 잘 먹었다, 번역: It's a popular place, so it's impossible to eat quietly, but it was delicious
원본: 일단 식당이 이쁘고 엄청 친절해요! 음식도 대체적으로 다 맛있었고 특히 오므라이스! 자리가 금방금방 차더라구요 웨이팅있었어요!, 번역: The restaurant is pretty and very kind!The food was generally delicious, especially omurice!The seat was kicked up soon.
원본: 파스타류가 먹고 싶어서 찾아간 곳. 웨이팅도 좀 길었고 큰 기대는 없었으나 생각보다 맘에 들었던 곳. 오므라이스, 매콤크림파스타, 스테이크를 시켰는데 깔끔하고 맛도 있었다. 워낙 배가 고팠어서 그런지 양이 적은 감이 없지는 않긴 했지만...? 을지로3가에 있는 간판없는 식당들 깜깜한 조명인 곳이 많았는데 오히려 이곳은 조명이 환하고 밝아서 좋았던 것 같다. 친구들 저녁모임이나 데이트 장소로도 괜찮은듯. 재방문의사 있음., 번역: I went to Pustada because I wanted to eat.The weight was a bit long and there was no expectation, but I liked it more than I thought.Omurice, spicy cream pasta, and steak were clean and tasty.I was so hungry that I didn't have a small amount...?There were many dark lights of restaurants without signboards at Euljiro 3 -ga, but it seemed to be good because the lighting was bright and bright.It seems to be good for friends dinner or dating.I have a re -examination.
원본: 이근방 힙지로 분위기를 물씬 풍기는 건물과 내부 인테리어. 트렌디한 메뉴가 많은데 이 근방 이런 음식 파는 곳중 최고 맛있음. 매콤까르보나라인데 맛 밸런스 좋음, 번역: The building and the interior of the building with the atmosphere with Lee Geun -bang hip paper.There are many trendy menus, but it's the best among these foods.Spicy Car Bonara, but good taste balance
원본: 서비스도 좋고 음식도 맛있었어요. 오므라이스가 가장 대표메뉴인데 생각보다 그저 그랬고 매콤 크림 파스타가 느끼하지도 않고 맛있었네요!, 번역: The service was good and the food was delicious.Omurice is the most representative menu, but it was just better than I thought, and the spicy cream pasta didn't feel it and it was delicious!
원본: 웨이팅있지만 순환이 빠른편! 음식맛이며 직원들 친절도며 다시한번 방문의사 100%, 번역: There is a waiting but the circulation is fast!It tastes like food and is kind, and once again, 100% doctor
원본: 오무라이스는 필수에요. 동영상 찍으셔야 합니다. 찹스테이크나 매콤크림파스타도 맛있어요. 을지로에 숨어있는 맛집이네요., 번역: Omurice is essential.You need to take a video.Chop steak and spicy cream pasta are also delicious.It's a restaurant hiding in Euljiro.
원본: 찾기가 어려웠다. 맛있었고 좀 자극적인 맛? 가츠산도는 느끼했다, 번역: It was difficult to find.It was delicious and a little irritating?Katsudo felt
원본: 카레와 카레우동의 카레 맛이 다르다고한다.카레가 기본적으로 매콤한 맛이고 카레우동에 수란을 추가하면 조금 더 부드럽게 먹을 수있다. 반공기를 추가할 수 있어서 좋다, 번역: The curry taste of curry and curry udon is said to be different.The curry is basically spicy and you can eat it a little more smoothly by adding a furnace to the curry udon.It's good to be able to add anti -air.
원본: 새우튀김이 파사삭! 커리 내공은 보통이상! 커리가 생각나는 날이면 쌩쌩부는 바람을 뚫고라도 가서 먹을 맛이다. 위치가 석촌호수가라 좋은 위치인듯하면서도 걸어서가자면 애매한 위치인 듯. 내가 갔을 때는 항상 대기가 있었지만 그 정도 쯤이야^^ 양파로 자연스러운 단 맛을 내고 오래오래 끓여 깊은 맛이 난다던 일본 장인의 현지 카레가 생각나는, 바삭한 튀김은 다른가게보다 훨씬 수준높은, 까다롭게 보아도 중타 이상의 커리맛집., 번역: Shrimp fried!Curry is more than normal!On the day when you think of curry, it tastes like you can go through the wind.The location is a good location because the location is a good location.When I went there, I always had a waiting, but it was about that, but it reminded me of a local curry of Japanese artisans who had a natural sweet taste with onions and boiled for a long time.restaurant.
원본: 기본메뉴에 센다마고, 가라아게, 고로케, 새우, 치즈 토핑을 각자 추가 하였습니다.가격대는 있는 편이지만 푸짐해서 가격 값을 합니다., 번역: We have added each of the Senda Margot, Karah, croquettes, shrimp, and cheese toppings.There is a price range, but it costs a lot.
원본: 카레소스가 인위적인 맛이 없어서 좋았고, 매운맛을 조절해서 먹을 수 있어 좋았습니다. 치킨 카레우동을 먹었는데, 카레와 우동의 조합이 의외로 좋았습니다., 번역: The curry sauce was good because it didn't have artificial taste, and it was good to be able to adjust the spicy taste.I ate chicken curry udon, and the combination of curry and udon was surprisingly good.
원본: 잠실 갈 일이 있어서 검색하다 알게 되었는데 양도 많고 맛도 있어서 기분좋게 먹고나왔습니다, 번역: I had to go to Jamsil, so I found out while searching for it, but it was so good and delicious that I ate it.
원본: 너무 그대했나요 저는 크기 감동은 없었어요그냥 비오는날 생각날따 가까우면 가면 좋을정도, 번역: Was it too much? I didn't have the size.
원본: 일식 카레 맛을 먹고싶은데 동네 마트에서 S, 번역: I want to eat Japanese curry, but S at the neighborhood mart
원본: 소개팅, 데이트, 모임하기에 최적인 곳이다.인테리어도 좋고 오픈 주방이라 보는 재미도 있다. 무엇보다 음식들이 대체적으로 맛있는 편이라 웨이팅이 상당하다. 최소 30분 정도 기다려야 되는 듯 싶다. 1. 총각핏짜(18,000원)이름도 귀여운 총각핏짜를 시켰는데 우리가 흔히 아는 피자와는 사뭇 다르다. 피자가 돌돌 말려서 나오는데, 거기에 리코타 치즈와 토마토 소스와 소고기 등 맛있는 재료들이 들어가 있다 :) 잘라서 한 입 푸짐하게 먹으면 건강하고 맛있는 피자의 맛을 느낄 수 있다. 도우도 쫄깃하고 재료들의 식감이 살아있어서 먹는 재미가 있다.  프랜차이즈에서 시켜먹는 피자와는 상당히 다른 맛.. 가격이 좀 비싼게 아쉽긴 하지만 만족스러웠다2. 까르보나라(17,000원)맛있긴 했는데 기대했던 것보다 맛이 평범해서 놀랐다. 피자를 먹고 나니까 색다른 맛을 기대했던 걸지도 모른다. 양은 적당했다.하지만 17,000원 주고 먹기엔 살짝 아깝다는 생각이 들었다.., 번역: This is the best place for blind dates, dates and meetings.The interior is good and it is fun to see it as an open kitchen.Above all, the food is generally delicious, so the weighting is considerable.I think I have to wait at least 30 minutes.1. Bachelor's name (18,000 won) has a cute bachelor's name, which is quite different from the pizza we know.The pizza comes out, and there's delicious ingredients such as ricotta cheese, tomato sauce and beef :) If you cut it and eat it, you can feel the taste of a healthy and delicious pizza.The dough is chewy and the texture of the ingredients is alive.It's quite different from the pizza you eat in the franchise..It's a pity that the price is a bit expensive but satisfactory 2.Carbonara (17,000 won) was delicious, but I was surprised because it tasted more than expected.After eating pizza, I might expect a different taste.The sheep were appropriate.But I thought it was a bit wasteful to eat 17,000 won..
원본: “추천하고 싶지는 않은... 누구나 아는 맛”솔직히 이태리 총각은 너무나도 유명해서 방문하면서 웨이팅이 길었음에도 전혀 불만이 없었다. 하지만 음식을 맛 보면서 짜디 짠 느낌과 깊이가 없는 맛에 실망을 할 수밖에 없었다... 이태리총각 피자는... 이것이 피자인가 집에서 그냥 막 만든 또띠아 롤인가 모를 맛... 아무튼 정말 실망을 금치 못했다., 번역: “I don't want to recommend...The taste that everyone knows. ”Honestly, the Italian bachelor was so famous that there was no complaint at all, even though the wait was long.However, while eating food, I was disappointed by the feeling of salty and depth...Italian bachelor pizza...I don't know if this is just a pizza or a tortilla roll just made at home...Anyway, I was really disappointed.
원본: 서촌 추천 맛집으로 소개 받아서 방문. 즐겁게 4명이서 수다를 떨며 회의 겸 식사를 함. 하우스와인 1잔씩 시키는 것보다 다같이 와인 1병을 시켜서 먹는 것이 좋았음. 음식은 글쎄... 남자보다는 여성들이 좋아할 메뉴와 맛. 그런데 함께 한 일행에게서 맛있다는 평을 듣진 못 함., 번역: I was introduced as a recommended restaurant in Seochon.Four people chat with four people and have a meeting and meal.It was better to eat one bottle of wine rather than one glass of house wine.Food is well...Menu and taste that women love rather than men.But I can't hear that it is delicious from the party.
원본: 총각핏짜가 진짜 독특하니 완전 맛있다~! 도우는 바삭쫄깃하고 속엔 리코타치즈랑 토마토, 양상추, 다진고기가 들어가있는데 발사믹소스랑 잘 어우러져서 새로운 맛!! 관자로제파스타는 관자가 별로 없었고 크림소스가 진하지 않아서 그냥그랬다 웨이팅이 많이 기니까 예약하고 가시길! 30분이라 했지만 1시간 기다린듯..ㅠ, 번역: The bachelor fit is really unique, so it's so delicious ~!The dough is crispy and there is a ricotta cheese, tomato, lettuce, and chopped meat in the inside.!Ze Pasta as a temple was not a temple and the cream sauce was not dark, so I just had a lot of weight.It was 30 minutes, but I waited for an hour..ㅠ
원본: 오픈 시간 부터 대기가 어마어마해요. 그래서 맛도 너무기대 했는지 조금 아쉽네요. 피자는 맛있었고 샐러드는 내용물이 부실해서 실망스러웠어요.., 번역: The atmosphere is enormous from the opening time.So it's a bit unfortunate that the taste was too expected.The pizza was delicious and the salad was disappointing because of the poor contents..
원본: 총각피자가 특이하고 너무 맛있었어요. 게살새우크림파스타도 맛있어서 강추합니다 :) 서촌에서 식사하실 일 있으면 무조건 이태리총각이요!!, 번역: The bachelor pizza was unusual and so delicious.The crab shrimp cream pasta is also delicious :) If you have something to eat in Seochon, it's an Italian bachelor!!
원본: 경복궁역에서 그리 멀지않은 곳이에요. 내부 넘 아기자기하고 음식 맛났어요! 점심시간인데도 사람이 거의 꽉차더라고요~ 예약하고가면 좋을듯해요, 번역: It's not far from Gyeongbokgung Station.The inside of the inside is cute and delicious!Even though it was lunchtime, people were almost full ~ I think it would be good to make a reservation.
원본: 피자도 파스타도 기본 이상은 하는 곳. 경복궁에서 피자는 여기!, 번역: Pizza and pasta are more than basic.Pizza in Gyeongbokgung Palace here!

 91%|█████████ | 20316/22421 [03:20<08:47,  3.99it/s]

원본: 떡볶이 맛은 특색없는 맛. 맛없진 않음. 카레가루가 들어간 듯. 쿨피스가 세트에 포함이길래 매운지 알았는데 전혀 맵지 않다. 떡은 매끈하고 쫄깃해 마음에 들었음. 나머지 메뉴도 평범함, 번역: Tteokbokki tastes without unique flavor.Not delicious.It seems like curry powder is in.I thought it was spicy because Cool Peace was included in the set, but it wasn't spicy at all.The rice cake was smooth and chewy.The rest of the menu is also common
원본: 카레맛이 살짝 나요. 생각보다 맵진 않았고. 특별히 기억에 남는 맛은 아니에요. 양은 푸짐한 듯 해요. 매장도 깔끔하고 좋아요. 다음엔 다른 메뉴도 먹어보고 싶어요, 번역: The curry tastes slightly.It wasn't as hot as I thought.It's not particularly memorable.The sheep seem to be rich.The store is also clean and good.Next time I want to try another menu
원본: 떡볶이 맛있음. 쿨피스가 커서 왕놀랐음. 화장실이 불편함., 번역: Tteokbokki is delicious.The cool pieces were so big that they were so surprised.The toilet is uncomfortable.
원본: 오리주물럭 특별하지 않아요 쫄아들수록 국물이 우러나가 그러지는 않고 짜요, 가격 양대비 비싼듯 해요, 부천에 X오리가 더 나은듯합다., 번역: It's not special.
원본: 오리주물럭 찾아가서 드세요. 정말 맛납니다.양념이 맛있어서 채소도 많이 먹게 되네요.허름하지만 깨끗하고 무뚝뚝하지만 친절한 식당^^, 번역: Go to duck and eat.It's really delicious.The sauce is delicious, so I eat a lot of vegetables.A shabby, clean, blunt but friendly restaurant
원본: 양도 푸짐하고 야채 및 고기가 정말 맛있다. H빔에 구워먹는거고 인테리어는 상당히 올드하지만 정감이 간다. 친절하지는 않다, 번역: The amount is also rich and the vegetables and meat are really delicious.Baked on the H beam and the interior is quite old, but it feels emotional.Not kind
원본: 사람많아서 직원 부르기도 힘들고 벨도없어요. 맛은 맛있는데 가격비해 양도적고 그냥 그래요, 번역: There are a lot of people, so it's hard to call the staff and there's no bell.The taste is delicious, but the price is small and just
원본: 일단, 가게 인테리어 참 아담하고 이쁩니다. 주차공간은 딱히 없으니 근처 유료주차장에 주차하시고, 음식은 주문후 빨리 나오는편입니다.피자는 씬피자로 라지라고 해도 성인남자가 혼자서 먹을 양이구요세트는 스파게티 1,스테이크 1,음료1 나옵니다.후식으로는 아이스크림을 주는데 기대는 마세요 ㅎㅎ가격대비 만족도 좋구요 가성비가 좋습니다.세트 2종 시켜먹었는데 73,000원 나왔습니다.성인남자 2명 성인여성 1명 초등4하년 1명 가서 배 부르게 먹었습니다., 번역: First of all, the interior is very small and pretty.There is no parking space, so park it in a nearby paid parking lot and the food will come out quickly after ordering.Even if the pizza is a thin pizza, the old yo -yo set for an adult man alone is spaghetti 1, steak 1, and drink 1.I don't expect it to give it an ice cream for dessert ㅎㅎ The price is good.I ate two sets and came out 73,000 won.Two adult men were one adult woman, one elementary school year, one person who was hungry.
원본: 망원동특유의 예쁜 식당이에요~ 가격은 평범하고 맛은 보통정도 하는것같아요!, 번역: It's a beautiful restaurant unique to Mangwon -dong ~ The price is normal and the taste is normal!
원본: 서비스: 2시에 남자친구랑 오목교역에서 만나 바로 가서 바로 주문함. 4테이블 정도 있었음. 꽃게로제파스타. 양념팬스테이크 주문. 식전빵 주고 2시45분 되는데도 안 나옴. 우리보다 늦게 온 혼자 먹는 여자 봉골레가 더 일찍 나옴. 그래서 언제나오냐고 묻자 종업원이 확인해본다고 함. 30분 이상 안나오는데 기다리는 손님 체크도 안 하고 확인해보겠다고.. 그제서야 파스타 하나 나오는데 죄송하다 오래 기다리셨다 이런 말 하나 없이 파스타 나왔다고만 함..보니까 배달의 민족 주문건으로 계속 포장 배달만 하고 배달 기사 왔다갔다함. 배달의 민족도 주문이 밀렸는지 전화가 왔는데 "자기네는 음식만 만들고 배달은 배달의 민족에서 하는 것이라 본인도 어쩔 수 없다"라는 통화내용.. 식당 손님이랑 배달이랑 둘 다 관리가 안 되는 것 같은데 하나에만 집중하길. 그러다가 둘 다 놓침. 심지어 점심시간 지나 두시에 갔는데 일어난 일.. 파스타 먼저 나오고 그때 스테이크 만들었는지 파스타 거의 다 먹어 갈 때쯤 나옴. 면이랑 소고기 익히는거 기다려봤자 그렇게 오래 걸리는 일인가. 주문 받은거 언제 만들기 시작한 건지.. 죄송하단 말 한 마디 없는게 정말 기분 나빴음. 음식: 가격 합리적이라는데 비등한 맛. 평일 점심에나 가야 합리적임. 꽃게 반 잘린거 3조각이 나왔는데 그 중 2개는 너무 신선도 떨어지고 비려서 한 입 먹는 순간 버림. 양념스테이큰데 고기에 양념 덜 되어 싱거움. 인테리어: 벽에 붙어있는 까만 일렬 의자에 앉았는데 의자기 높아 식탁히고 폭이 얼마 만 되어 진짜 불편함. 1인 의자는 편한데 일렬 의자 진짜.. 오래 기다리면서 불편했음. 목동에서 합리적인 가격의 파스타라고 주목받길래 오랜만에 재방문 했는데 진짜 별로. 각성. 반성하고 방문손님이라도 잘 잡길. 정말 마음에 안 들어 가입하고 씀. ㅡㅡ, 번역: Service: At 2 o'clock, I meet with my boyfriend in concave trade and order right away.There were about 4 tables.Blast crab zepasta.Seasoned fan steak order.I don't even come out at 2:45 for bread before the meal.The woman Bongolet, who is eating later than us, comes out earlier.So when I asked when it came out, the employee confirmed it.I don't even check the guests waiting for more than 30 minutes..Then, I'm sorry that I came out with a pasta. I waited for a long time..As a result, he continued to deliver packaging as a national order of delivery and went back and forth.The people of delivery have also been called.You can't help it because you only make food and deliver it in the people of delivery.The call..I don't think both of the restaurant guests and delivery are not managed.Then both missed.Even after lunch, I woke up..Pasta comes out first and then I made a steak at the time when I ate almost all of the pasta.It takes so long to wait to cook noodles and beef.When did you start making your order?.I was so sorry that I was sorry.Food: Price is reasonable, but it tastes boiled.It's reasonable to go to lunch on weekdays.Three pieces of crab cuts came out, two of which were too fresh and thoroughly abandoned.Seasoned stay is big, but seasoned with meat.Interior: I sat in a black -line chair attached to the wall.One chair is comfortable, but the chair is real..It was uncomfortable waiting for a long time.It was a long time since I was attracting attention as a reasonable pasta in Mok -dong.Awakening.Reflect on and get a good visit.I don't really like it.ㅡ ㅡ
원본: 들어갔을때 분위기가 너무 좋았습니다. 연인세트 시켰는데 정말 양도 많아 배가 엄청 부르더군요. 피자, 파스타, 스테이크 한번에 이 가격에 먹을 수 있다니! 추천합니다^^, 번역: The atmosphere was so good when I went in.I made a set of lovers, but it was so much that I was very hungry.You can eat pizza, pasta, steak at this price at once!I recommend it
원본: 하동관 곰탕은 누구나 다 알고 계시듯 맛나죠~^^ 개인적으로는 하동관 본점과 코엑스본점이 가장 하동관의 진짜맛을 볼 수 있다고 생각합니다..예전에 포스코뒤에 있는 하동관에 갔다가 너무 느끼함에 하동관에 실망한적이 있는데..코엑스점에서 계산하다 물어봤더니 실제 본점의 개념은 명동과 코엑스밖에 없다고 하시더라구요..ㅎ 분명 맛이 다르니 개인 추천은 코엑스점입니당, 번역: Hadonggwan Gomtang tastes good as everyone knows ~ I personally think that Hadong -gwan headquarters and COEX headquarters can see the real taste of Hadonggwan..I went to Hadong -gwan behind POSCO and was disappointed by Hadonggwan because I felt it too much..When I asked at the COEX store, the concept of the actual headquarters was Myeong -dong and COEX..ㅎ It tastes different, so personal recommendation is COEX
원본: 명동때부터 종종방문했던 곰탕집입니다. 코엑스점은 처음 방문했는데요 여전히 구수하고 깊은 맛입니다. 아이와함께 방문했는데 아이도 먹기에 부담없는 한끼 입니다. 특히 김치가 굿입니다., 번역: It is a gomtang house that I have often visited since Myeong -dong.I first visited COEX. It is still delicious and deep.I visited with my child, but my child is not comfortable to eat.Especially kimchi is good.
원본: 짜지않아 담백하고 깔끔한 맛으로 먹기에 부담이 없습니다., 번역: It's not salty, so it's not burdensome to eat with a light and clean taste.
원본: 투명한 육수의 곰탕. 먹다보면 밥에서 우러나와 나중에는 육수가 쌀뜨물 비슷한 맛이 남. 파를 따로 넣을 수 있게 하고 김치를 인당 한그릇씩 줘서 좋았음., 번역: Gomtang of transparent broth.If you eat, you get out of the rice, and later the broth has a similar taste.It was good to let the green onions and give a bowl of kimchi per person.
원본: 시원한 국물맛의 곰탕입니다은근하게 깊은 맛이 정말 좋습니다한번드셔 보세요, 번역: It is a cool soup.
원본: 코엑스에 있는 지점맛은 그냥 곰탕맛이고유명한거에 비해서는 특별히 맛있는지는 모르겠어요다른 곰탕집이랑 비교했을때더 맛있는지는 모르겠는데가격은 더 비싸다는 생각이 드네요, 번역: The point of the branch at COEX is just a taste of Gomtang and I don't know if it's particularly delicious compared to other Gomtang houses.
원본: 진정한 곰탕. 솔직히 맛은 나무랄 곳이 없습니다. 그런데 모든 음식에 가격을 떼어두고 생각할 수는 없으니까요..가성비를 생각하면 참 아쉬운 맛집입니다.명동 하동관과 맛은 똑같습니다. 가까운 곳에서 한번쯤은 먹어봄직합니다., 번역: True Gomtang.Honestly, the taste is no place.But I can't think of all the foods..Considering the price, it is a sad restaurant.The taste is the same as Myeongdong Hadonggwan.At least once nearby.
원본: 하동관코엑스 곰탕집 맛 =  코엑스몰에 몇개 없는 한식당입니다.  확실히 코엑스라 그런지 양에 비해서 비싼 건 확실하네여. 깔끔한 맛이 특징이구요. 깊다는 맛은 잘 느끼지 못 하겠습니다. 분위기 = 사람이 많아 생각보다 안쪽이 덥다는 느낌이 많이 듭니다. 점원분들은 매우 친절하십니다. 총평 = 코엑스 땅값은 비싸다., 번역: Hadonggwan COEX Gomtang Taste = There are a few Korean restaurants in COEX Mall.It's definitely COEX, so it's clear that it's expensive.It is characterized by a clean taste.I can't feel the deep taste.Mood = There are many people, so I feel a lot hotter than I thought.The clerks are very kind.General review = COEX land price is expensive.
원본: 일단 밥말아 먹기 싫으셔도 밥이 말아져서 나옵니다. 조미료 없이 건강한 맛인데 느끼해서 김치 없이는 못 먹어요 ㅜ비싸기도 너무 비쌌고 직원도 사람이 많다보니 그닥 친절하지 않았네요., 번역: Once you don't want to eat rice, the rice comes out.It's a healthy taste without seasonings, but I can't eat it without kimchi.
원본: 다이닝코드에서 코엑스맛집 검색해보고 간 곳ㅋㅋㅋ 워낙 국 밥을 좋아해서 기대하고 갔는데 진짜 맛있었음! (또먹고싶다 ㅠ) 한가지 아쉬웠던건 국이 너무 빨리 식는다는것 ㅠㅠㅠㅠ, 번역: I searched COEX restaurants in the dining code ㅋㅋㅋ I loved soup so I expected it, but it was really delicious!(I want to eat again ㅠ) One thing that was unfortunate was that the soup cools down so quickly ㅠ ㅠㅠㅠ
원본: 월요일 점심 무얼 먹을까 고민하다 따끈한게 생각나서 하동관에 방문했어요ㅎㅎ 인기있는 맛집답게 웨이팅이 조금 있었지만 금방 들어갈 수 있었답니다! 웨이팅은 있었지만 자리에 앉아 주문하자마자 바로 음식이 나와서 좋았어요♡ 맑은 곰탕이지만 뽀얀 곰탕보다도 더 부드럽고 고소한 맛을 느낄 수 있답니다! 단일메뉴답게 맛은 보장합니다ㅎㅎ 김치도 너무 맛있고,  원하시는 분들은 깍두기 국물을 주전자로 부어드립니당ㅋㅋㅋㅋㅋ, 번역: I was worried about what to eat on Monday, so I thought it was warm, so I visited Hadong -gwan.There was a weight, but as soon as I sat down, the food came out right away.Like a single menu, the taste is guaranteed.
원본: 유명세믿고 가격 엄청올려 이익챙기는 프렌차이즈. 맛도 보통인데.. 그냥 담백한 맛. 가격은 최악이다 이돈내고 먹을바에 동네 국밥집 가겟다, 번역: Believe in the famous, franchise is a profit.The taste is normal..Just light taste.The price is the worst.
원본: 접근성 : 코엑스 안맛과 가격 : 맛은 깔끔해요. 가격은 좀 비싸요. 코엑스 가격이겠죠..?! 13천원치고  배가 부르진 않아요.., 번역: Accessibility: COEX Taste and Price: The taste is clean.The price is a bit expensive.It's COEX..?!I'm not hungry for 13,000 won..
원본: 코엑스 식당 주차할인은 5만원 이상 부터, 맛은 담백 개인김치 개별 주고 맛 좋음. 단, 가격이 사악. 기본1.3만 특1.5만 곰탕외 다른메뉴 없음 줄서서 입장. 전체 인원 안오면 입장불가. 거의 패스트푸드급으로 주문하면 바로 나옴. 추가주문 안됨. 이름빨로 여러군데 지점이 있으나 꼭 먹어야할 맛은 아닌듯. 세월이 많이 변해 명성만으로 사람들이 모이진 않을듯. 먹고선 노브랜드 햄벅 하나 더먹음., 번역: COEX restaurant parking discount is more than 50,000 won, and the taste is delicious.However, the price is evil.Basic 1.30,000 specials 1.50,000 Gomtang and other menus are in line.If you do not come to the entire person, you cannot enter.Almost if you order a fast food class, it will come out right away.No additional orders.There are several branches in the name of the name, but it is not a must -eat taste.The years have changed so much that people won't gather just by reputation.After eating, I eat one more hamburger.
원본: I have been here twice.Every time I eat, the taste is stable and fresh!Menu is here. Ps: 통닭 is only 500won. What''s this? Next time, I will try!, 번역: I have beenhere twice.Every Time I Eat, The Taste is Stable and Fresh!Menu is here.PS: Tong Chicken is Only 500 Won.What''s this?Next Time, I will try!
원본: 기대보단 대간치 않은 곳. 곰탕인데 국물이 맑습니다. 웨이팅이 조금 있습니다., 번역: It is not much more than expected.It's in Gomtang, but the broth is clear.There is a little weighting.
원본: 맛있어요. 그런데 본점이 더 맛있던 것 같은데.. 기분 탓이겠죠? 기분 탓일 거예요.., 번역: it is delicious.But I think the main store was more delicious..Maybe it's because of the mood?It would be because of the mood..
원본: 원래 유명한 그집 하동관코엑스 들릴때마다 꼭 먹는 편입니다.저는 코엑스점이 본점에 비해 더 깔끔하고 맛있는 느낌이 들더군요.성인 남성분은 공기밥 추가해서 드시면 아주 배부르게 드실 수 있습니다., 번역: Every time I hear the famous Hadong Gwan COEX, I eat it.I felt more neat and delicious than the headquarters.Adult men can eat very full by adding rice.
원본: 가격은 비싸지만 맛있습니다! 점심시간엔 줄이 길어요 특히 김치가 맛있음, 번역: The price is expensive but delicious!The line is long at lunchtime, especially kimchi is delicious
원본: 곰탕 맛집 하동관에 갔음 맛은 맛있고 여전한 맛 코엑스에서도 먹을 수 있어서 좋음 하지만 가격은 안 착함, 번역: I went to Hadonggwan, Gomtang, and the taste is delicious and still can be eaten at COEX, but the price is not good.
원본: 추운 겨울에 든든하게 한끼 먹을 수 있는 집입니다. 인당 김치 한 접시씩 주는 게 좋아요.가만 가격이 조금 쎕니다., 번역: It is a house where you can eat one meal in a cold winter.It is good to give a plate of kimchi per person.The price is a bit pricey.
원본: 20공 깔끔하게 비웠네요. 딱히 나무랄 데 없는 곰탕입니다. 매장이 시끄럽고 정신사납긴 합니다., 번역: 20 balls were emptied neatly.It is a gomtang that is not frustrating.The store is noisy and mental.
원본: 맛은 있는데 가격이랑 양적인 면에서 아쉬움이 컸어요 코엑스에 있으니 그럴수도 있겠지만 ㅜ, 번역: It tastes good, but it was a pity in terms of price and quantity.
원본: 맛있어요 근데 가격이 너무 비싸기도 하고 친절하진 않아서 또 가진 않을 것 같아요., 번역: It's delicious, but the price is too expensive and it's not kind.
원본: 처음에는 모르고 보통만 시켜먹었는데, 20공을 먹고 난 후로는 보통을 못시키겠습니다. 20공 강추!! 다만 가격부담이 크긴해요ㅠ 그래도 맛있어서 사먹을 수밖에 없네요., 번역: At first, I didn't know it, but I usually eat it, but I can't do it since I after eating 20.20 balls!!However, the price burden is high.
원본: 여기 보다는 포스코쪽을 자주 갔었는데,맛있어서 좋아했던 곳이다.지금은 안간다.너무 비싸다.10년전 즈음에도 비싸다는 생각이 있었지만이정도는 아니었다. 곰탕 한 그릇 가격이 ㅎㄷㄷ...반찬이 많은 것도 아니고, 주인의 양심이 없다는 생각이 들 정도다., 번역: I often went to POSCO rather than here, but it was delicious.I don't go now.too expensive.I thought it was expensive around 10 years ago, but it wasn't this much.The price of a bowl of bears is ㅎㄷㄷ...I don't have a lot of side dishes, and I don't think there is no conscience.
원본: 20공 시켰습니다내장이랑 같이나오는걸 시켰는데 고기가 의외로 적어서 이만원이라는 가격이 조금 아까웠습니다확실히 맛은 있었지만 특출나다고 생각하긴 부족했네요좋은건 시키면 거의 바로 나옵니다, 번역: I made 20 balls.
원본: 사람이 너무 많아서 맛있다는 그 맛을 느낄 여유가 없음, 번역: I can't afford to feel the taste of so many people
원본: 맑은 곰탕의 맛집명성에 걸맞게 맛이 깔끔하고 만족스러움, 번역: Clean and satisfactory taste for the restaurant's restaurant's restaurant.
원본: 제가 정말좋아하는 맑은국물의 담백한 곰국입니다 시원해요 저는 깎국을 만들어 먹는 편입니다 아무리 양많은걸 시켜도 국물조금도 남기지 않고 다먹습니다, 번역: It's a light bear soup of my favorite clear broth. It's cool. I'm making a mowing soup.
원본: 진하게 끓여낸 깔끔한 국물이 너무 맛있어요. 소금 간은 하지 않고, 파 듬뿍 넣고 드셔보세요. 그냥 본연의 맛을 즐기기에도 바쁩니다. 근데 가격은 좀 비싼게 흠이긴 해요., 번역: The clean broth is so delicious.Don't salt it, but add plenty of green onions.I'm just busy to enjoy the original taste.But the price is a bit expensive.
원본: 20공 최고!, 번역: 20 balls!
원본: 노래에 언급된거 보고 궁금해서 가본 집개인적으론 그냥 무난히 즐겼어요국밥매니아들은 충분히 좋아하실듯 합니다, 번역: I was curious to see the song mentioned in the song, so I personally enjoyed it.
원본: 놋그릇에 나오다 보니 펄펄 끓는 뜨거운 국물은 아니에요. 국은 진국이지만, 뭔가 이전에 먹던 것들과는 다른 느낌입니다. 저는 뜨~거운 국물을 호호 불며 먹는 것을 좋아해서 그런면에서 기대치에는 못 미친 것 같아요. 그 외에 분위기와 위생은 굿입니다~, 번역: It's not a hot broth when it comes out in a brass bowl.The soup is Jinguk, but it feels different from what I had before.I like to eat hot broth and eat it, so I don't expect it.Other than that, the atmosphere and hygiene are good ~
원본: 곰탕 먹었는데 맛은 줄서서 기다린만큼의 맛으로 보상해줍니다., 번역: I ate Gomtang, but the taste is rewarded with the taste of waiting in line.
원본: 회사 미팅 때 성인 남자 분들 모시고 가기에 너무 좋았습니다.분위기 점잖으면서 음식맛도 빠지지도 않구요특히 곰탕을 먹을 때 습관처럼 소금을 넣었는데간을 하지 않고 나온 그대로 먹어도 삼삼하니 맛있던 곳은 여기가 처음이었던 것 같아요 :), 번역: It was so good to go with adult men at the company meeting.It doesn't taste good and tastes it.
원본: 대형쇼핑몰 내에 위치해서 그런지 뭔가 어수선해서 식사하기가 좀 불편합니다, 번역: It's located in a large shopping mall, so it's a bit uncomfortable to eat because it's cluttered.
원본: 점심에 곰탕먹으러 자주갑니다맛도있고 무난해서 점심으로 좋은듯!, 번역: I often go for lunch for lunch. It tastes good and good for lunch!
원본: 비싼거 빼곤 빠르고 맛있음, 번역: Except for expensive, fast and delicious
원본: 8군데 가봤네, 번역: I've been to 8 places
원본: 맛있음. 근데 매장 엄청 더움. 8시까지 함., 번역: Delicious.But the store is very hot.Until 8 o'clock.
원본: 엄청 추운 날씨에도 웨이팅이 있는 곳이었다. 약간 허름한 느낌에 엄청난 맛집의 느낌을 풍겼지만 평범했던 곳.마늘닭볶음탕이 마늘향이 꽤 강해서 좋았고 그래서 국물이 시원하다. 아, 감자가 맛있다. 볶음밥은 무난.양으로 보면 (대)에 한 마리 들어가는 느낌. 양이 꽤 많았는데 가격은 그에 비해 저렴하게 먹을 수 있다.#서울대 샤로수길 서울대한식 샤로수길한식, 번역: It was a place where we had a waiting even in the very cold weather.It feels a bit shabby and it feels like a huge restaurant, but it was an ordinary place.The garlic chicken fried soup was good because the garlic scent was quite strong, so the soup was cool.Oh, the potatoes are delicious.Fried rice is good.In terms of sheep, it feels like a large.The amount was quite large, but the price can be cheaper than that.#Seoul National University Charosu -gil Seoul National Food
원본: 맛이없지는 않지만빨간 닭한마리에 더 가깝다웨이팅이 있을때가 간혹있는데 그정돈 아닌것같다, 번역: It's not tasteless, but it's closer to a red chicken.
원본: 샤로수길에 위치한 닭볶음탕 집이에요!가게 규모는 아담해서 소소하게 술 모임하게 좋은 장소에요.음식도 나름 맛 괜찮아요~, 번역: It's a chicken fried soup located on Sharosu -gil!The size of the store is small and it's a good place to drink.The food tastes good too ~
원본: 특색을 찾기 어려울만큼 지극히 평범하고 무난한 국물 닭도리탕. 그렇게 심하게 자극적이지도, 그렇다고 건강한 맛까지는 아니에요.그냥 가성비 괜찮은 학교 앞 식당 인데, 왜 대기까지 생기면서 유명세를 타게 되었는지는 조금 의문이네요., 번역: It is extremely ordinary and easy to find characteristic.It's not so stimulating, but it's not even a healthy taste.It's just a restaurant in front of the school, and it's a bit doubtful why it became famous as it was atmospheric.
원본: 매운맛을 좋아하는 사람에겐 주저없이 추천드립니다!! 보통 2던계를 많이드시는데 저랑 여자친구는 매운걸 즐기는편이라 3던계먹었는데요 매운거 좋아하시는 분은  과감히 맥심 단계인 5단계를 추천드립니다 저도 재방문시5 단계 먹으려구요 ㅎㅎ아쉬움점은  화장실 위생상태가  안상태네요 ...ㅠㅠ, 번역: If you like spicy taste, we recommend it without hesitation!!I usually have a lot of 2 dancers, but I and my girlfriend enjoyed spicy streets.It's not...ㅠㅠ
원본: 기대하고 갔는데 너무 조미료맛 강하고자극적인 맛임. 짜고 매움27,000원 대 자 시켰는데도 닭 조각 겁나 작고 양도 적음국물이 8할임, 번역: I expected it and it was so seasoning and stimulating.Even though it was salty and spicy 27,000 won
원본: 닭볶음탕이 먹고싶어서 지나가다가 들어갔는데 가게가 매우커서 놀람 근데 양념이 닭에 베거나 그렇지 않아 국물과 먹어야함 볶음밥필수!, 번역: I wanted to eat chicken fried soup, but the shop was very big, but it was surprised.
원본: 엄청 특별하지도 않고 별로이지도 않음... 면식가 여자 3명이서 소자+면사리 추가해서 배불리 먹고 옴., 번역: Not very special and not much...There are three women who have three women, adding devices+cotton.
원본: 최애 닭도리탕집 ㅎㅎ사장님께 가게이름의 뜻을 물어보았다.손녀딸이 할아버지를 하찌라 불러서 도리도리하찌라고지으셨다고. . ㅎㅎ 첨엔 일본어인줄매운닭볶음탕이지만 매운맛 조절가능해서 좋고국물떡볶이처럼 국물이 낭낭해서 떠 먹으면 맛있다.떡도 들어있는데 완전 쫄깃하고 맛있음.아직 웨이팅하는 정도 아니고 아는 사람만 가는샤로수길 맛집 인정!, 번역: I asked the boss of the name of the shop.My granddaughter called my grandfather to say that he was called Doridori..ㅎㅎ At first, it is a Japanese fishing chicken fried soup, but it can be adjusted with spicy taste.It also contains rice cakes, but it is so chewy and delicious.Recognizing the Sugil Restaurant, which is not yet waiting, but only a person you know!
원본: 맛있어요👍🏻매운 맛 조절 가능해요 !!, 번역: It's delicious 👍🏻 Spicy taste can be adjusted!!
원본: 여기 닭볶음탕 먹은 이후에 집에서 자꾸생각남 진짜 맛남 소주한잔하기딱!, 번역: After eating chicken fried soup, I keep thinking at home.
원본: 맵고 맛있습니다., 번역: Spicy and delicious.
원본: 모둠 숙성회 아주 맛나용. 싱싱하구.모쯔나베도 만원치구 괜찮은 것 같아요!!! 분위기 조용하고 딱좋았어요 깔끔하구. 혼술집으로도 추천, 번역: A group aging sashimi is very delicious.It's fresh.Motsunabe seems to be okay!!!The atmosphere was quiet and perfect.Recommended as a sneak collection

 91%|█████████ | 20385/22421 [03:38<08:35,  3.95it/s]

원본: 세트 메뉴로 주문하면 저렴하게 먹을수 있습니다.매운맛 정도 조절 가능하고 소주를 시키면 기본적으로 홍초가 같이 나와요., 번역: If you order with a set menu, you can eat cheaply.You can adjust the spicy taste and the soju is basically red vinegar.
원본: 똥집도 맛있고 술을 시키면 홍초소주를 만들어 먹을 수 있게 홍초를 줍니다! 해물 계란탕도 정말 맛있어요!!, 번역: The dung house is delicious and you can make red vinegar so that you can make red vinegar soju!Seafood egg soup is really delicious!!

 91%|█████████ | 20386/22421 [03:38<08:33,  3.96it/s]

원본: 국물맛이 깔끔하고 맛있음. 모듬세트에 튀김종류가 많아서 좋았음., 번역: The soup tastes clean and delicious.It was good to have a lot of tempura in the assorted set.
원본: 수년간 형제상회를 단골로 생각하고 다녔습니다. 해가 갈수록 메뉴의 질이 떨어지는 것보다도 더 화가 나는 것은 서비스가 최악으로 치닫는 정도가 된다는 것. 자신들의 배달에 대해서도 책임을 지지 않는다면, 누가 책임지나요? 배달부가 집에 계신 노인들을 협박해서 배달비 더 달라고 했습니다. 가게에 따지니, 자신들이 알 바가 아니라고 하고 오히려 회의 때문에 전화 못 받은 저를 탓합니다. 효도한다고 주문한 것이었는데, 그만 부모님께 깡패를 보내버렸더군요. 실망해서 쓰는 글 맞습니다. 너무 화가 나서 쓰는 글도 맞구요. 하지만, 이런 저의 경험도 사실이며, 앞으로도 다른 분들께 얼마든지 일어날 수 있음을 알려드립니다. , 번역: I have been thinking of brothers and brothers as regulars for many years.More angry than the quality of the menu is that the service is the worst.If you are not responsible for their delivery, who is responsible?The delivery man threatened the elderly at home and asked for more delivery costs.In the store, they say they are not known and blame me for not being called because of the meeting.I ordered it for filial piety, but I stopped it to my parents.I'm disappointed.I'm so angry that I write.However, this experience is true, and I will tell you that it can happen to others in the future.
원본: 노량진 수산시장에 있는 횟집입니다. 그럭저럭 깔끔한 분위기예요. 주변에서 횟감을 사오면 상차림 비용을 받고 맛있게 차려주십니다., 번역: It is a sushi restaurant in Noryangjin Fish Market.It is a neat atmosphere.If you buy a sashimi from the surrounding area, you will receive the cost of the table and make it delicious.
원본: 오랜 단골.사장님은 항상 바쁘시지만 기억해 줘서 감사한 곳., 번역: A long regular.The boss is always busy but thank you for remembering.
원본: 가격도 저렴하고 깔끔해요!! 정말 맛있게 먹었어요 ㅎㅎ, 번역: The price is cheap and tidy!!I really ate it haha
원본: 주차장이 넓게 있어 차로 움직이기 편했구요 화장실은 2층에 있어요~ 2층에서 보통 모임이나 행사할때 예약하는 것 같았고 저는 1층에 앉았어요 야채 고기 모두 신선해서 좋았고 고기양은 조금 아쉬웠네요, 번역: There is a large parking lot, so it was easy to move by car. The toilet is on the second floor ~ It was usually a meeting or event on the second floor, and I sat on the first floor.
원본: 소갈비 해물찜 소자 4명이서 먹으면 딱 좋다 건물주가 아닌이상 나올 수 없는 재료구성, 번역: It is good to eat with 4 people with beef rib seafish.
원본: 명동과 남대문 중간에 있는 예쁜 브런치카페! 데이트하기에도 좋고 여친들과 오기 좋음~ 예쁜 테이블과 옘븐 샹들리에가 있고 음식도 정말 예쁨 여긴 수플레핫케이크가 인기라는데 못먹고 와서 아쉬움 ㅠ, 번역: Pretty brunch cafe between Myeong -dong and Namdaemun!It's good to date and it's good to come with girlfriends ~ There are pretty tables and 옘ven chandeliers and the food is really pretty.
원본: 인테리어가 예쁜곳입니다. 간단하게 티타임 즐기기 좋아요., 번역: The interior is pretty.It's easy to enjoy tea time.
원본: 내부 분위기는 좋은데 가격대비 서비스 그닥이에요 ㅠㅠ 내부가 생각보다 작아서 예약하거나 대기 하셔야 하니 미리 예약하심이!! 제가 별 두개 드리는 이유는 가격은 왠만한 루프탑 레스토랑 수준인데 위치는 1층 입구에 모델하우스 느낌... 뭔가 팝업스토어 같아서 좀 실망했어요. 케이크는 글래머러스 팽귄에서 공수한다는 것 같은데 그건 맛있더라고여~~ 어쨌든 이 가격으로는 근처에 분위기 좋은 다른 레스토랑 추천입니다, 번역: The internal atmosphere is good, but the price is very good.!The reason I'm two stars is that the price is at the level of a rooftop restaurant...I was a little disappointed because it was like a pop -up store.The cake seems to be delivered from the glamorous penguin, but it's delicious ~~ Anyway, this price is recommended nearby other restaurants.
원본: 신선하고 맛있었어요. 그러나 가격대비 쏘쏘입니다. 직원분들이 영업마감시간 한시간 전인데도 주방을 마감하기시작하고 저희만 쳐다보고 있어서 좀 부담스러웠어요. 영업시간 10시까지인데 아홉시부터 그러셨어요... 남자 직원분이 여자화장실 청소하고 계셨는데 손님이 들어갔는데도 배려안해주시고 계속 청소하고 계셔서 결국 이용 못했습니다... 다시 생각해도 너무했던 것 같아요...ㅎㅎ, 번역: It was fresh and delicious.But it's a price for the price.It was a bit burdensome for employees to start to finish the kitchen even though they had an hour before the business deadline.It's until 10 o'clock in business hours...The male staff were cleaning the women's toilet, but even though the guests entered, they did not care and kept cleaning...I think it was too much to think again...lol
원본: 모듬회를 주문하니 숙성회가 나왔어요. 구성은 괜찮았어요. 회에 간장이 미리 발라져 나오는게 특징이라면 특징이에요. 근데 나가사키 짬뽕은 기대보단 별로 ... 일요일이라 그런지 영업을 일찍 마감하시더라구요. 22시까지 영업시간이었는데 21시도 안되어서 주방마감에 전 직원이 열중쉬어 하고 제가있는 테이블을 쳐다보고 있었어요. 주말인데 빨리 퇴근하고 싶은 마음은 알긴 하지만 ㅋㅋ 대놓고 나가달라고 그러셔서 너무 눈치가 보여서 조금 아쉬웠습니다., 번역: I ordered assorted sashimi and came out.The composition was fine.It is characteristic that the soy sauce is applied to the sashimi.But Nagasaki Champon is not expected...It's Sunday, so I finished business early.It was open until 22 o'clock, but it was less than 21, so I was looking at the table where all employees were heated up in the kitchen finish.I knew I wanted to go home soon, but I was a little unfortunate because I noticed so much that I asked me to go out.
원본: 비오는날 술한잔 생각나서 들른 곳.근처 사는 지인이 추천한 곳이기도 하다.숙성회라고 하는데 살이 연하고 비린맛이 없다.간장이 미리 발라져서 나와서 신기했다.초밥 먹으러 다시 와볼 예정., 번역: I visited a drink on a rainy day.It is also recommended by an acquaintance nearby.It is called aging sashimi, but it is soft and has no fishy taste.The soy sauce came out in advance and it was amazing.I will come back to eat sushi.
원본: 정말 잘먹고왔네요스시 맛있고 식당도 조용합니다다시한번가서 먹고싶습니다 강추요, 번역: I've eaten really well. Yosesi is delicious and the restaurant is quiet.
원본: 천호역 6번 출구 나와서 쭈꾸미골목에 중간정도 위치한 독도쭈꾸미 2호점-맛은 있는데 이시국에 사람이 심각하게 많아서 당분간 못갈거같아여ㅠㅠ 자리가 다닥다닥 붙어있어서... (⑉･̆-･̆⑉), 번역: There is a taste of Dokdo Zukkumi 2, which is located in the middle of Cheonho Station Exit 6, and there are so many people in Lee Si -guk, so I can't go for a while...(⑉ ･ ̆ ･ ･)
원본: 날치알 인심이 후한 것은 맞으나딱히 혜자 스럽지는 않음.맥주는 병당 5,000원 인듯.2인 + 볶음밥 + 맥주2  39000원 나옴, 번역: It is true that the false egg is generous, but it is not beneficial.Beer seems to be 5,000 won per bottle.2 people + fried rice + beer 2 39000 won
원본: 쭈꾸미가 다 비슷하겠지 했는데 여긴 기대 이상이었어요..!! 적당히 맵고 삼겹살 새우도 쭈꾸미랑 잘 조화된 맛이에용 볶음밥에 날치알도 엄청 많이 뿌려주셔요 직원분들도 넘나 친절해요 추천합니당~, 번역: The squash was all similar, but it was more than expected..!!It's a moderately spicy and pork belly shrimp, and it's a good harmonious taste with the fried rice.
원본: 콘치즈.날치알.쌈 모두 푸짐하게 제공되어 중았고 셀프지만 무심하게 자리에 놓아주는 센스 ㅋㅋ 추천 맛집이예요!, 번역: Concees.Flying egg.Ssam was all provided in a lot, and it was self -confidentiality.
원본: 맛있긴한데 너무 매웠어요. 볶음밥을 추가하니까 간이 맞았고, 테이블은 많은데 사람도 많아서 좀 시끄러웠어요., 번역: It was delicious, but it was so spicy.I added fried rice, so the liver was right, and there were a lot of tables, but there were a lot of people.
원본: 천호 쭈꾸미골목에 위치해 있고 역에서 가까워서 찾기 쉬워요콩나무 당면사리랑 날치알이 공짜여서 너무 좋았고 쭈꾸미도 맛있었어요~!직원분들도 너무 친절하셔서 맛있고 기분 좋게 잘먹었고 담에 또 방문할 거에요!, 번역: It is located in the alley of Cheonho and is close to the station, so it's easy to find.The staff were so kind that they ate delicious and pleasantly, and I will visit the wall again!
원본: 뭐든지 혜자스러운 곳..!날치알부터 치즈까지..!기분 좋게 먹고 왔습니다~, 번역: Anything is beneficial..!From flying to cheese..!I've eaten comfortably ~
원본: 아주머니가 너무 친절했어요! 맛도 좋고! 다시 갈 의향 있습니다!, 번역: Aunt was so kind!It tastes good!I am willing to go again!
원본: 십년전 대학다닐 때부터 알던 곳이다. 쭈꾸미 맛이 다 거기서 거기다. 이집또한 평범한 쭈꾸미볶음이지만 쭈꾸미를 다먹고 먹는 볶음밥이 일품이다. 시끌버쩍한 분위기 친구들과 술마시러 가기에 좋은 곳이다, 번역: It was a place I knew since I went to college ten years ago.The taste of the squash is there.This house is also an ordinary squash fried, but the fried rice that eats all the squash is excellent.It is a good place to go to drink with a noisy atmosphere
원본: 쭈꾸미 먹고싶을땐 여기만가요~다 비슷한거같은데 남자친구는 다먹어봤는데 여기가 제일맛있다더라구요 ~저번에 포장도 했는데 1인분은 주문 안되는데 그냥 해주시고 심지어 양도 2인분스럽게 주셔서 잘먹었어요^^, 번역: When I want to eat it, I only go here ~ I think it's all similar, but I ate all of my boyfriend, but it's the best here.
원본: 천호 쭈꾸미ㅡ골목에 있는 곳. 왁자지껄 하고 서민적인 느낌입니다, 번역: Cheonho Zyakkumi -place in the alley.It's a waxy and common feeling
원본: 이 주변 쭈꾸미집은 거의다 비슷비슷해요. 아무데나 들어가도 별차이 없어요., 번역: This surrounding squash house is almost the same.There is no difference if you go in anywhere.
원본: 천호살면서 7년동안 가는데 항상 맛있음 ㅎㅎ, 번역: It's always going to go for 7 years while living in Cheonho.
원본: 돼지불백 강추 ( 제육볶음은 평범)밑반찬, 국, 밥, 숭늉을 셀프로 가져다 먹을 수 있게 해놓으셨고, 여러번 가져다 드실 수 있어요. 메뉴주문하면 공기밥은 기본으로 가져다 주시고, 나중에 모자르시면 밥통에서 더 가져다 드실 수 있습니다.  돼지불백 드실 때 마늘 좋아하시면 부페코너에서 생마늘 더 가져다 구우셔도 좋습니다. 불백 구울 실 때는 센불에 바짝 익혀서 물기없어질때까지  졸이셔야 맛있습니다 ^^ 한약재도 들어가고 고기도 큼직하고 도톰하니 깊은 맛 느껴져서 아주 만족스러웠습니다. *매장을 리모델링 하셔서 예전보다 분위기가 많이 깔끔해져서 좋네요 ^^, 번역: Pigsa Buddha (stir -fried meat is normal) Side dishes, soup, rice, and sung -nuk, you can eat it as a self, and you can bring it several times.If you order the menu, bring the rice as default, and if you do not, you can bring more from the rice bowl.If you like garlic when you eat pork, you can bring more raw garlic from the buffet corner.When you burned it, you had to cook it on a high heat so that it was delicious until it was gone.It's nice to have a cleaner atmosphere than before by remodeling the store.
원본: 말그대로 기사식당입니다. 주당들이 찾을만한 술안주도 저렴하게 마련되있고요 주차는 가게앞에 하면되고 반찬은 셀프로 갖다가 먹으면 되요 예전엔 계란후라이도 셀프로 해먹을수 있었는데 계란값이 올라서... 코다리찜은 조금짠데 아구찜처럼 콩나물도 많이주셔서 술안주에 좋았어요 대부분의 메뉴를 1인분도 주문할수 있는게 좋았어요. 기사식당 가보면 원래 2인분부터 되는데 오늘만 해준다고 이상한소리하는 식당도 많은데 여기 이모님들 친절하세요., 번역: It is literally an article restaurant.There is also a cheaper drink for the week, and the parking is in front of the store...The steamed steamed kodari was a little salty, but it was good for drinking because it was a lot of bean sprouts.If you go to the knight restaurant, there are many restaurants that say that they only do it today.
원본: 제육볶음 먹었는데 맛있고 사장님이 친절하세요, 번역: I ate stir -fry, but it's delicious and the boss is kind.
원본: 자리는 협소한데 맛있게 먹어서 괜찮았어요. 만두피가 두꺼운데도 맛있었어요., 번역: The seat was narrow, but it was okay to eat it.The dumpling skin was thick, but it was delicious.
원본: 많은 만두와 딤섬집들중 내 입맛엔 쟈니가 No.1고급지고 중후한 맛보다 '와삭'빠르게 전달되는 반달군만두를 제칠 대타가 아직은 없어요!, 번역: Among the many dumplings and dim sum houses, Johnny is NO.1 There is no hit that will beat the dumplings that are delivered 'Wasak' faster than the luxurious taste and the high -end taste!
원본: 늘 갈때마다 군만두 찐만두 홍합탕 조합.군만두는 육즙 팡팡홍합완탕은 국물땜에 시키지만 매번 너무 짜서후회 하면서도 시키는 메뉴담엔 만두랑 마파두부를 먹을거예요..., 번역: Every time I go, my dumpling dumpling dumplings.Jufang Panghonghap Wan -tang, which is used in the military, is made of soup, but it is too salty to eat dumplings and mapo tofu in the menu...
원본: 몇 번 갔던 음식점이어서 최근 방문에 실망이 더 했습니다. 마치 요리사가 바뀐 듯이 맛이 달라졌으며 군만두는 튀긴 부분은 태워 나오고 반대는 밀가루 반죽 상태로 나왔습니다. 이를 지적하니 먹고 남은 몇개 만두를 그대로 가져다가 다시 구워서 내오는 상식 밖의 행동을 보였습니다. 음식도 먼저 온 사람보다 숫자가 많은 일행한테 먼저 주는 등, 손님 접대의 기본이 안 된 집입니다. 만두를 좋아해서 만두 먹고 싶을 때, 생각하던 집이었는데, 안타깝게도 영원히 list에서 지워야 하겠습니다., 번역: It was a restaurant that I went a few times, so I was disappointed with the recent visit.The taste changed as if the chef changed, the military dumplings came out of the fried part, and the opposite was the dough.I pointed out this, and I took some of the remaining dumplings as it was and then baked it again.It is a house that is not basic of hospitality, such as giving to a group of people who have more than first.When I wanted to eat dumplings because I liked dumplings, I thought it was a house I thought, but unfortunately, I have to erase it from List forever.
원본: 한창 만두에 빠졌을때 갔던 가게 중 하나입니다. 군만두(반은 찌고, 반은 구운 반달)가 맛있다는 평이 많아서 갔는데, 정말로 맛있었습니다.육즙이 가득하고 피도 바삭바삭해서 진짜 맛있었어요.... 물만두나 만두국도 있는데 나중에 한번 먹어볼 의향이 있습니다. 근데 군만두가 이 가게의 메인 메뉴라서 그게 언제가 될지는 모르겠어요()가게 내부는 고급스러운 쪽은 아닙니다. 그래서 혼밥하기엔 오히려 좋은것같아요! (자리마다 칸막이 없습니다. 미리 얘기드립니다) 2층 자리도 있는데, 혼자 드시는거면 2층 가서 먹는것도 좋을것같아요., 번역: It is one of the shops that I went when I fell into the dumplings.I went to the military dumplings (half -steamed, half -grilled half moon), but it was really delicious.It was really delicious because it was full of juicy and crispy blood....There are also water or dumplings, but I am willing to eat it later.But because the dumplings are the main menu of this store, I don't know when it will be.So I think it's good to be good!(I don't have a partition in every seat. I'll talk about it in advance. There's also a second floor.
원본: 포장해가서 먹고 실망했었는데 홀에서 먹는건 완전 딴판임. 진짜 맛있다. 물만두와 군만두 둘다 우열을 가리기 힘듬., 번역: I was packed and disappointed, but it was a different plate to eat in the hall.Really delicious.Water dumplings and groups are hard to cover the superiority.
원본: 비오는날 방문해서 만두 종류별로 시키고 맥주랑 먹고 마셨다. 정말 배부르고 행복했다. 다시 가고 싶은데 멀어서 자주 못감... 꼭 술이랑 같이 드세요., 번역: I visited on a rainy day and drank with beer.I was really full and happy.I want to go back, but I can't go often...Be sure to eat with alcohol.
원본: 인생만두라고 할만큼 맛있게 먹었어요. 오늘도 그렇듯 줄이 있었는데 2~3팀 정도 있길래 기다렸어요. 만두라서 그런지 테이블 회전율이 놓아 웨이팅이 길진 않았어요. 저녁을 가볍게 먹고난 상태라 군만두 반달만 먹었는데 육즙이 팡팡 터지는게 너무 맛있게 먹었어요. 10개 8천원이라 가성비도 괜찮았어요. 만두만 파는 전문점 다운 맛!! 또 가서 다른 메뉴도 도전할 예정 ~, 번역: It was delicious enough to say life dumplings.Like today, there was a line, but I waited for 2 ~ 3 teams.Because of the dumplings, the table turnover was not long.I ate dinner lightly, so I ate only dumplings and half months.It was 10,000 won, so the price was fine.A specialty shop that sells only dumplings!!I will go and challenge another menu ~
원본: 안에 새우씹히는게 진짜 너무맛있고 마파두부도 매콤하니 다 좋았어요 ㅜㅠ, 번역: The shrimp chewy inside is so delicious and the mapo tofu is spicy.
원본: 수요미식회 나왔다고 해서 갔는데 진짜 맛있어용 ㅎㅎ 만두존맛, 번역: I went to the demand gourmet sashimi, but it was really delicious.
원본: 군만두는 육즙이 흐르고 물만두는 담백하고 식어도 맛있습니다. 이미 재방문이고 충분히 유명하지만 강추강추 미친 강추!, 번역: The military dumplings are juicy, and the dumplings are light and cool.Already returned to visit and famous enough, but recommended crazy!
원본: 그냥 물만두랑 뭐가 다른지 모르겠다ㅋㅋㅋㅋㅋㅋ 평일 저녁시간전에 갔더니 1호점 1층은 만석이고 2층 첫손님으로 들어갔다..그냥 만두..물만두.., 번역: I just didn't know what's different from the water..Just dumplings..Water dumplings..

 91%|█████████ | 20434/22421 [03:50<08:23,  3.95it/s]

원본: 존맛탱ㅠㅠㅠㅠㅠ이태원 집에서 먼데 이거 먹으러 이태원 가야됨ㅠ큨ㅋㅋㅋㅋㅋㅋㅋ, 번역: John Tang Tang ㅠ ㅠㅠㅠ This Taewon house is far away, but I have to go to Itaewon to eat this ㅠ 큨 ㅋㅋㅋ ㅋㅋㅋ ㅋㅋㅋ
원본: 군만두가 걍 미쳤는데 여자 세명이서 만두 두개 시켜 먹고 카페가니까 양이 딱 맞더라구요, 번역: The dumplings were crazy, but the three women were eaten by two dumplings.
원본: 줄서서 먹었던 맛집:-) 너무 유명해서 궁금했는데 맛있었어요, 번역: The restaurant I ate in line :) I was so famous that I was curious, but it was delicious
원본: 군만두와 물만두가 상당히 맛있다. 다만 매장이 작아 줄을 서야하는 경우가 많다., 번역: Dumplings and water dumplings are quite delicious.However, the store often needs to be small.
원본: 군만두가 진리임육즙이 풍부하고미소가 지어지는 맛이 었음, 번역: Gundu dumplings are rich in truth juice and smiles.
원본: 어짜피 이태원에 차 댈 곳은 만만치 않다 ㅠ ㅠ용산구청 아니면 해밀턴 호텔 주차장이그나마 만만함예전에 비하면 다소 약해지긴 했지만 아직도 군만두는 참 먹을만하다한 번 쯤은 도전해 보시길, 번역: Anyway, it's not easy to get to Itaewon.
원본: 이런 중국스타일 교자는 사랑입니다~~ 줄 서도 괜찮아요~~! 가게가 다 이태원에 있어서 2호점에 붐비면 1호점 가서 줄서고 이래요 막 ㅋㅋㅋ 새우교자 진짜 너무 맛나요~~ 씹으면서 새우 찾는 재미 쏠쏠합니다~~, 번역: This Chinese style gyoza is love ~~ It's okay to stand in line ~~!If the shop is crowded with Itaewon, if you are crowded with the second store, you can go to the first store.
원본: 겉은 바삭한 속은 말랑한 군만두.  홍합 가득한 국물이 일품인 만두국, 번역: On the outside, the crispy inside is soft dumplings.Mandu -guk, which is full of mussels full of mussels
원본: 반달은 언제 먹어도 맛있어요! 가격이 올랐지만 이태원의 다른 가게들에 비해서 비싼 편은 아니라고 생각해요. 단점은 줄이 길 때가 있고, 직원들이 딱히 친절하진 않아요., 번역: The half moon is delicious anytime!The price has risen, but I don't think it's expensive compared to other shops in Itaewon.The downside is that the line is long, and the staff are not very kind.
원본: 만두덕후 둘이서 언제먹어도 옳은 자니덤플링 ㅋ 제주까지 포장하고 싶었는데 재고없어서 못사간 친구가 많이 아쉬워 했어요 ㅎㅎ, 번역: I wanted to pack the right man, even if I eat it, I wanted to pack it to Jeju.
원본: 내용물은 상당히 맛있지만 만두피가 너무 두꺼워서 여자들이 싫어하는 것 같음. 이태원에 이것 먹으러 가기는 애매하니깐 다른 데서 저녁 먹고 들러서 만두 한두접시 하고 가는 적이 몇 번 있었는데 배부르니까 자꾸 만두피를 안먹게 됨. 그정도로 좀 부담스러움.만두피는 벗겨버리고 속만 먹는 사람들 (특히 여자들) 여럿 있었음.집에 가져가서 먹으면 음식이 식으니깐 비린내가 좀 나기도 함., 번역: The contents are quite delicious, but the dumpling skin is so thick that women don't like it.It is ambiguous to go to Itaewon, so I had dinner and stopped at dumplings and had a dish of dumplings a few times.That's a bit burdensome.There were many people who peeled off and eaten only people (especially women).If you take it home and eat it, the food will cool, so it may be fishy.
원본: 왜 맛집인지를 알게해주는 특이한 맛이 있네요. ,,맛집은 맛집입니다, 번역: It has a unique taste that lets you know why.,, Restaurant is a restaurant
원본: 이것이 진정한 만두? 군찐만두에 칭따오~, 번역: Is this a true dumplings?Qingdao on the dumplings of the steamed dumplings ~
원본: 특색없고 보통임 ㅇㅅㅎ가 더 맛있음.화장실 너무 헬게이트, 번역: There is no characteristic and normal.Toilet too Hellgate
원본: 유명새에 비해 여기보다 더 맛있는 집이 많음, 번역: Compared to famous birds, there are more delicious houses than here
원본: 가격도 합리적이고 육즙도 좋고 먹을수록 맛있는 맛특히 칭따오주문은 필수 기대한만큼은 아니지만 괜찮은 집, 번역: The price is reasonable and the juicy is good, and the more delicious the taste, the more delicious, the more necessary.
원본: 주차x(용산구청이용가능), 항상 대기줄있음, 자리 좁음, 포장은 거의 바로 됨, 군만두가 맛있음!!, 번역: Parking X (Yongsan -gu Office available), always waiting lines, narrow seats, packaging almost immediately, gun dumplings are delicious!!
원본: 4인가족이 다녀왔어요고기군만두와 만두국, 마파두부덮 밥 모두 맛있었어요, 번역: 4 families have been there.
원본: 깔끔하고 맛도 괜찮은편 가격도 나쁘지않음 그러나 줄서서 먹을정도는 아니다, 번역: The price is clean and the taste is not bad, but it's not enough to eat in line.
원본: 유명한 집이죠. 근데 유명세에 비해 그리 특별하진 않아요 ㅎ, 번역: It's a famous house.But it's not very special compared to the famous world
원본: 좋아요!!!!!, 번역: great!!!!!
원본: 벽돌 인테리어로 고급스럽고 깔끔한 느낌의 고깃집이에요. 근데 내부가 작은 편이라 웨이팅이 길고 시끄러웠어요. 회식하러 많이 오는 분위기에요. 7시 20분정도에 가니 30분정도 기다리더라구요. 알등심이 테이블당 2인분씩만 주문이 가능해서 알등심으로 주문하고 뼈무게 만큼 가브리살로 더 주셔서 맛있게 다른 부위도 맛보았습니다. 시즈닝으로 나오는 북어채에 소금 간 된 것이 너무 맛있어서 직원분이 구워주시고 그릇에 시즈닝해서 올려주신것 먹어보고 엄청 놀랐어요. 직접 구워주셔서 대접 받는 기분입니다. 진짜 맛있어서 다음에 또 방문하고 싶다고 느꼈어요.근데 볶음밥은 솔직히 그냥 그래요. 평범한 맛입니다.ㅋㅋㅋㅋ, 번역: The brick interior is a luxurious and clean meat.But the interior was small, so the weight was long and noisy.It's a lot of dinner.I went to 7:20 and waited for about 30 minutes.I can order only two servings per table, so I ordered it with a sirloin and gave it to Gabri -Sal as much as the bone weight.It was so delicious that salted by the North Koreans in the seasoning of seasoning was so delicious that the staff baked it and put it in the bowl.It feels like you are treated by yourself.It was so delicious that I wanted to visit again next time.But fried rice is honestly just.It is an ordinary taste.lol
원본: 우연히 지나가다 웨이팅이 좀 있길래 맛집인가 ? 라고 검색해보니 역시나 맛집이더라구요알등심 꼭 꼭 드세요 정말 맛있어요고기 육즙과 찍어먹는 소스 ? 소금 ?이 잘 어울리고 부드럽게 넘어가요 말캉말캉 해서 젤리인가 ? 싶었어요 정말 맛있어요 !!!!! 정말 ㅠ 먹어보시면 아실거에요직원분이 빠르게 구워주고 먹기 편하게 빠르게 잘라주세요 정말 빠르게 먹고 나왔습니다다음번에도 갈거에요, 번역: I accidentally passed by, so there is a way of waiting.When I searched, it was a restaurant.Salt? This goes well and gently.I wanted to be really delicious!!!!!If you really eat it, you will know.
원본: 인스타나 여러 후기들이 많길래 남친이랑 갔는데 웨이팅은 거의 한시간하고 내부는 공기순환 안되고..가격대비 맛은 그냥 그랬습니다덜 익히겠다고 하셨는데 생각보다 많이 익고 닭가슴살 먹는 느낌이였어요 남친도 저도 하남돼지집이 더 맛있다고 했습니다 순두부찌개는 맛있었어요, 번역: I went to my boyfriend because there were a lot of Instagram and many reviews..It was just the taste of the price. I said that I would cook less, but I felt more cooked and chicken breast.
원본: 금요일 저녁 약 30분정도 웨이팅해서 먹었던 집입니다.일단 외관은 고깃집같이 생기지 않았고 제법 손님이 있을 것 같은 카페처럼 생겼고 음악도 고깃집 느낌의 음악은 아니었지만 그 내부는 시끌벅적한 고깃집입니다.메뉴는 알등심, 삼겹살, 천겹상, 투뿔채끝이 있는데요. 저는 한테이블당 2인분만 주문 가능한 알등심을 먹었었습니다.알등심의 경우 뼈에 붙어나오는데 뼈의 중량만큼 가브리살을 가져다주셔서 두 종류의 부위를 즐길 수 있단 장점이 있습니다.찬은 김치와 순두부찌개가 나오는데요. 전체적으로 찬들은 다 짰습니다. 그래도 순두부찌개는 계속해서 손이 가는 묘한 매력이 있었구요.또, 북어채로 시즈닝한 소금과 북어우린물로 만든 간장은 고기와 정말 잘어울렸습니다.후에 기회가 있다면 또 오고 싶은 집이에요.P.S 딱 하나 아쉬운 점이라면 인테리어 때문인지 테이블간 간격이 가까웠는데 전체적으로 회식분위기인 것 처럼 시끄러워서 조용한 분위기를 원하시는 분들에겐 추천드리지 않습니다., 번역: It was a house I ate for about 30 minutes on Friday evening.The exterior did not look like a meathouse, it looked like a cafe that seemed to be a guest, and the music was not a meat -like music, but the interior is a noisy meat.The menu has sirloin, pork belly, pork belly, and ending ends.I had a speech that could be ordered only two servings per table.In the case of egg soul, it comes to the bones, and it has the advantage of bringing Gabri -Sal to the weight of the bone so that you can enjoy two kinds of areas.Chan has kimchi and soft tofu stew.Overall, the colds are all over.Still, the tofu stew had a strange charm.In addition, the salted salted salt and the soy sauce made in the North Korean fish are really good with meat.If you have a chance later, you want to come again.P. s is only one unfortunate thing, because of the interior, the interval between the tables was close, but it is not recommended for those who want a quiet atmosphere because it is as if it is a dinner atmosphere.

 91%|█████████▏| 20468/22421 [03:56<07:15,  4.48it/s]

원본: 무조건 가야할 정도는 아니지만 한번쯤 가보기 나쁘지 않은 고기집, 번역: It's not enough to go, but it's not bad to go at least once
원본: 맛있어요 돼지고기인데 부드러워요다만~~ 기름때문인지 바닥이 너무 미끄러워요 화장실 가려고 일어나다 자빠질뻔. 바닥시공이 아쉽네요 ㅋ, 번역: It's delicious. It's soft but it's soft ~~ It's because of oil, so the floor is so slippery.The floor construction is a pity
원본: 모양만 흉내낸 스페인 요리집스페인에서 먹었던 맛을 기대할 수는 없겠지만, 요리나 재료의 수준이 상당히 낮았어요. 간단 레시피책 보고 만든 느낌...오징어 먹물 빠에야는 가리비가 너무 비렸고, 다른 재료들도 별로였어요ㅠ 소스는 꾸덕하기는 했는데.. 깊은 맛은 전혀 아니였어요. 인스턴트 맛.오리지널 샹그리아는 실제 샹그리아의 맛을 전혀? 재현하지 못한 것 같아요ㅠ 과일이 더 베어있어야 하는데... 그냥 와인맛만 조금 났네요. 감바스는 기름 덩어리ㅠ 마늘은 맛있긴 했지만, 집에서 만드는 수준의 오일베이스에요. 어느정도 육수를 조금 내서 해야하는데, 그냥 올리브유?만 철철 부음. 그래도 워낙 실패하기 어려운 음식이라 그나마 젤 맛있었어요! 감자크로켓 괜찮긴 했는데... 감자+치즈+튀김이 실패하긴 힘드니까요ㅎㅎ 이 또한 고급진 맛은 아니에요, 번역: You can't expect the taste you ate in Spanish cuisine, which mimics the shape, but the level of cooking or ingredients was quite low.Feeling a simple recipe book...Squid ink Paella was too scallops, and other ingredients were not good..The deep taste was not at all.Instant flavor.Original Shangri -A is the actual taste of Shangri -La?I can't reproduce it...It's just a little bit of wine.Gambas is oil mass, but garlic was delicious, but it is an oil base at home.I have to do some broth, but I just olive oil?But it was so hard to fail, so it was delicious!It was okay for the potato rocket...Potatoes+cheese+tempura is hard to fail.
원본: 가격이 괜찮지만 양이 적다. 대신 여러명이 가서 다양한 메뉴를 시켜서 맛보기 좋음. 식사보다는 술안주로 좋은듯, 번역: The price is okay but the amount is small.Instead, several people go and have a variety of menus.It seems to be better as a snack rather than a meal
원본: 이태원에서 스페인 요리 먹고싶으면 여기 추천합니다~~ 메뉴도 다양하고 스페인에서 먹었던 맛이랑 흡사한게 많아서 좋았어요!, 번역: If you want to eat Spanish cuisine in Itaewon, it is recommended here ~~ There are many menus and the taste you ate in Spain!
원본: 거리 분위기처럼 시끌벅적하고 다소 좁은 테이블에 큰 팝 음악이 나오는 펍에 가깝습니다. 해산물 토마토 빠에야는 맛이 익숙하기는 했으나 기대에는 못미쳤습니다. 사프란이 들어간 메뉴가 오리지널의 맛에 더 가까울 것 같습니다. 소문대로 감바스는 매우 맛있었습니다. 샹그리아도 모두 만족합니다., 번역: It's close to a pub with a big pop music on a noisy and somewhat narrow table like a street atmosphere.Seafood tomato Pagaya was familiar with the taste, but it was not expected.The menu with Spran seems to be closer to the original taste.As rumors, Gambas was very delicious.I am satisfied with Shangri.
원본: 가격대가 진짜 저렴한 스페인음식점! 서비스도 넘좋고 다좋은데 자리가 좀좁아요ㅠㅠ 대신 나머지가 최고 술도 맛있어요!, 번역: Really cheap Spanish restaurant!The service is so good and good, but the seats are a bit narrow.
원본: 이국적 음식맛에 놀라고 분위기에 놀랐습니다. 창문을 열어놓고 장사하셔서 좀 담배냄새에 취약했습니다., 번역: I was surprised by the exotic food taste and was surprised.I opened the window and sold it, so I was vulnerable to the smell of cigarettes.
원본: 감바스가 너무 맛있습니다. 양은 적은 편이라 간단하게 한잔 할때 가면 좋을거 같습니다., 번역: Gambas is so delicious.The amount is small, so it's good to go when you have a drink.
원본: 감바스나 빠에야와 같은 요리와 샹그리아를 같이 먹으면 좋아요~, 번역: It is good to eat dishes like Gambas or Paella and Shangri -A together.
원본: 저렴한만큼 양은 적습니다이것저것 시켜먹기 좋은듯합니다, 번역: The amount is small as it is cheap.
원본: 감바스가 진짜 맛있었음 감바스 이후에도 여러번 먹어봤지만 탑 쓰리에 속함, 번역: Gambas was really delicious. I tried it many times after Gambas, but it belongs to the top three.
원본: 양 진짜 작아요ㅋㅋㅋㅋㅋㅋ, 번역: It's really small hahahahahaha
원본: 음식: 고기 맛있음. 단, 굽는 사람의 스킬에 따라 좌지우지 됨. (안구워줌)서비스: 매우 친절. 한 분이 항상 손님들 주시하며 대기중. 분위기: 손님 적당히 있음. 주변 술집의 소음이 약간 있음. 위생상태: 보통임., 번역: Food: Meat is delicious.However, depending on the skill of the baking person.(Eye) Service: Very kind.One person is always waiting for the guests.Mood: Guest in moderation.There is a little noise in the bars around.Hygiene: Normal.
원본: 사장님도 너무 친절하시고 고기도 맛있게 잘먹었어요~ 음료서비스도 감사합니다!, 번역: The boss was so kind and the meat was also delicious ~ Thank you for the drink service!
원본: 일반적인 삼겹살 가격이고 육즙이 살아있으면서 고기가 부드러우요 디저트 아이스크림 존맛, 번역: It is a general pork belly price and the meat is alive and the meat is soft. Dessert ice cream zone taste
원본: 분명 맛있는 고기이다.싸게 배채우는 식당은 아닌듯 하다.와규가 특히 맛있다.깔끔한 분위기는 훌륭, 번역: It's definitely a delicious meat.It doesn't seem to be a cheap restaurant.Wagyu is especially delicious.The neat atmosphere is great
원본: 분위기좋고 맥주마시기 좋아요서비스도 좋고 안주가 좋아요 나베 전골국물맛이 좋아요!  안주도맛잇고 아사히도 맛좋아요 재방문의사잇습니다!, 번역: The atmosphere is good and the beer is good and the service is good and the snacks are good!The snacks are also delicious and Asahi tastes good.
원본: 한잔하기 괜찮은 곳이라 사료됩니다..술 취해서 진상부려도 서버들이 잘 대처하더라구요..^^좀 어두워요.., 번역: It's a good place to have a drink..Even if I was drunk, the servers responded well..It's a bit dark..
원본: 활화산 떡볶이는 여자 4명이서 먹으면 딱 적당한 정도의 양이다 맵지 않고 살짝 단느낌의 떡볶이 쪽이 가깝다 양도 많고 양의 비해 가격도 적당한거 같다!가곱새전골은 국물이 맛있고 술안주로 딱이지만 양이 많지는 않고 추가메뉴없이 여자 둘이 먹으면 좋은정도이다!, 번역: The active volcano tteokbokki is just the right amount of 4 women.The seven new hotpot is delicious and it's perfect for the soup, but it is not large and it is good for two women to eat without additional menus!
원본: 분위기가 좋았습니다. 매장 직원분들도 친잘하셨고, 음식 맛도 좋았어요, 번역: The atmosphere was good.The staff of the store were also friendly, and the food was good.
원본: 가격, 맛, 인테리어 면에서 두루두루 무난한 편. 흡연실도 잇고 화장실도 깨끗해서 술 마시러 가기 편해요, 번역: In terms of price, taste, and interior.The smoking room and the toilet are clean, so it's easy to go to drink.
원본: 종종 술마시고 2차로 방문했는데 딱히 먹을 메뉴가 없다, 번역: I often drank and visited the second round, but there is no menu to eat.

 91%|█████████▏| 20492/22421 [04:01<07:06,  4.52it/s]

원본: 깔끔하고 이쁜 매장 그리고 친절한 서비스맛있는 파스타. 나에겐 양이 조금 적었던..빵은 별도로 시켜야 하는 점이 조금 아쉬움.이름이 좀 어렵지만 머든 실망은 안함.지역주민들이 많이 찾을듯 합니다., 번역: A clean and pretty store and a friendly service delicious pasta.The amount was a little less for me..It's a bit unfortunate that bread should be done separately.The name is a bit difficult, but I'm not disappointed.It seems that local residents will find a lot.
원본: 가격도 좋고 맛도 좋다. 특히 고르곤졸라피자는 진짜 강추. 다른 집들은 치즈 비싸니까 다른 치즈랑 쓰까서 파는 경우도 있는데 여기는 후하게 많이 넣는 느낌? 암튼 향도 다른곳에 비해 진하고 맛있다. 남직원분도 친절하고 여긴 내부도 깔끔하지만 화장실맛집이다. 화장실도 깔끔. 인테리어 신경 많이 쓴것같다. 응암동에 이런곳이 있다니..하는 그런 생각이 들었다. 암튼 개강추합니다., 번역: The price is good and the taste is good.Especially Gorgonzola Pizza is really recommended.Other houses are expensive, so you can sell them because they are sold.Anyway, the flavor is stronger and delicious compared to other places.The male staff are kind and the inside is clean, but it is a toilet restaurant.The bathroom is also clean.I think I paid much attention to the interior.There is a place like this in Ngam -dong..I thought that way.Anyway, the opening is open.
원본: 생긴지 얼마 되지 않아서 깔끔하고 예뻐요! 음식도 맛있고, 꽤 저렴합니다 ㅎㅎ, 번역: It's been a while since it's been a while!The food is also delicious and pretty cheap haha
원본: 직원 분이 아주 친절하시고 매장도 모던하고 넓은 편이다. 파스타 면은 굵은 편 소스 양은 자작하고 간이 잘 배어있는지는 모르겠다., 번역: The staff are very friendly and the store is modern and spacious.The pasta noodles are bold and I don't know if the liver is soaked.
원본: 굉장히 오래 걸리지만 밀크티가 굉장히 맛있다.  분위기도 매우 좋다, 번역: It takes a long time, but the milk tea is very delicious.The atmosphere is also very good
원본: 안쪽 골목에 숨은 조용한 카페. 한 골목 들어왔을 뿐인데 바깥 세상과는 완전히 다른 분위기에요. 스콘은 추천할만한 맛은 아니었지만^_ㅠ 커피는 맛있었고 직원분들이 무척 친절하셔서 재방문의사 있습니다. 동네에 있었다면 단골이 되었을 것 같아요., 번역: A quiet cafe hidden in the inner alley.It's just one alley, but it's completely different from the outside world.The scone was not recommended, but the coffee was delicious and the staff were very friendly.If you were in the neighborhood, it would have been a regular.
원본: 연신내에서 보기드문 분위기의 카페. 깔끔하고 음악좋고 분위기도 좋아요. 원목계열 인테리어에 ㄷ자형 테이블. 사장님이 굉장히 친절하시고 고객들과 대화하려고 나름 노력하시는 것 같아요., 번역: A rare cafe in the stretch.It's clean, good music and good atmosphere.C -shaped table in solid wood interior.The boss is very kind and seems to try to talk to customers.
원본: 사장님 혼자서 운영하시는 곳인데  공간도 예쁘고 움악도 좋아요. 바형태로 대화도 나눌수 있고 혼자서 커피 즐기기에도 좋습니다!손수 직접 인테리어 한 공간에서 애정이 느껴집니다., 번역: The boss is operated by yourself, but the space is pretty and the music is good.You can also talk in the form of a bar and enjoy coffee by yourself!I feel affection in the interior space.
원본: 재방률96%. 종로구에서 맛있는 라멘집 top5안에 들지않을까 싶다. 가격이 좀 있고 국물이 적은편이라는 단점이 있기는 하나 충분히 그 가격 내고 먹을 가치가 있는 라멘이며 많은 라멘집들이 놓치는 국물과 면이 따로노는 현상이 일어나지 않고 절묘하게 어우러지는 깊은 맛을 자아내니 누구에게나 '맛있는 라멘이다' 라는 생각을 불어넣게 해줄것이다. 특출나게 맛있다고는 할 수 없지만 복싱에서도 잽만 잘 써도 웬만한 탑클라스 선수가 되듯이 멘야사다이메는 기본만으로도 최강자리라 할 수 있는 그런 라멘집 되겠다., 번역: Rerun rate 96%.I think it will be in the top five delicious ramen restaurants in Jongno -gu.Although it has a disadvantage that it is a little price and little broth, it is a ramen that is worth at that price and eats, and the broth that many ramen houses miss and the noodles do not have a separate phenomenon, and the deep taste is exquisitely harmonized.It's ramen. 'It's not unusual and delicious, but in boxing, it's like a top -class player, and it's a ramen house that's the strongest position alone.
원본: 혜화 멘야산다이메. 바로 옆에 위치한 부탄츄와 함께 유명한 라멘 체인점이다. 여러 군데에 지점이 있지만 혜화점이 다른 지점에 비해 밀리지는 않는 것 같다. 가격에 비해 다소 적은 양은 단점. 혜화 라멘 하면 붙어있는 부탄츄와 멘야산다이메 중 고민하게 되는데, 돈코츠 이외에 다른 메뉴도 먹고싶다 하면 이곳으로, 나는 먹는 양이 좀 많다 하면 부탄츄를 선택해서 가는 것이 합리적, 번역: Hyehwa Menyasan Dame.It is a famous ramen chain store with Bhutanchu located next to it.There are several branches in places, but Hye -hwa does not seem to be pushed compared to other points.A little less than the price is a disadvantage.Hyehwa Ramen will be worried about Bhutanchu and Menyasan Dame.
원본: 라멘은 기본적으로 짜고 특유 고기냄새가 나서 일본음식 좋아하는 남자친구는 맛있게먹음(남친때매재방문) 근데 나는 아님그래서 미소라멘 도전해보았는데우동느낌 면발에 살짝 달아서 맛있게 먹음, 번역: Ramen is basically salty and the smell of meat is unique, so Japanese food likes to eat delicious boyfriend (visit when you're a boyfriend).
원본: 라멘을 좋아하고 특히 돈코츠를좋아함멘야산다이메가면 항상 카라쿠치라멘을먹음!국물도맛있고 ㅠㅠ여튼맛있음!!!!!!, 번역: I like ramen, especially if I like Donkatsu, I always eat Karakuchi Ramen if I like Hamenyasan Dai Mega!The soup is also delicious and it's delicious anyway!!!!!!
원본: 그냥 영화보기 전에 간단히 한끼 떼우려 했는데 맛도 좋고 가격도 적당했음.근데 국물이 별로 없었음 국물애호가들에게는 비추. 아예 없는편은 아닌데 오 국물! 이러면 끝나있음., 번역: I was worried about just before watching the movie, but it was good and the price was appropriate.But there was not much broth.It's not at all, but Oh soup!This is done.
원본: 대학로는 거의 그렇겠지만 10분정도 기다렸고, 주문후에는 빨리 나왔습니다.저렴하지는 않았지만 맛있었고,라멘과 교자 혼자서 먹기에 배부르게 적당한 양이였습니다, 번역: It is almost the same as college, but I waited for 10 minutes and came out quickly after ordering.It wasn't cheap, but it was delicious, and it was a good amount of ramen and gyoza to eat alone.

 91%|█████████▏| 20509/22421 [04:05<06:52,  4.64it/s]

원본: 사람 없는 시간 대에 방문하여 한산한 식당에서 조용히 식사했습니다.차슈 추가는 너무 짜고 고기의 지방이 느끼해서 추가 없이 그대로 먹는게 맛을 살리는 길이였을 것 같습니다. 제가 느끼한 걸 못먹는 편이기도 하고요. 참고하세요.마제소바도 맛있지만 약간 짰다고 하네요.전체적으로 양이 푸짐하고 맛있었습니다., 번역: I visited the time -free time and ate quietly at a quiet restaurant.Chashu is too salty and the fat of the meat is felt, so it would have been the way to eat it without any additional taste.I can't eat what I felt.please refer to this.Majesoba is also delicious, but it's a bit hot.Overall, the amount was rich and delicious.
원본: 라멘으로 유명한 멘야산다이메.체인점도 몇군데 있어서 가끔방문.이번에 쿠로라멘 먹음.차슈가 맛있음.재방문 의사 있음., 번역: Menyasan Dame is famous for ramen.There are also several chain stores.This time, kuroramen eats.Chashu is delicious.I have a re -examination.
원본: 장 : 가게가 일본풍으로 조용하고 단란함 직원분들이 매우 친절하심 음식의 나오는 속도와 가격, 맛이 모두 좋음단 : 약간 구석진 위치에 있으며 가게가 피크 타임때엔 약간의 웨이팅이 있을거라 예상됨, 번역: Zhang: The shop is quiet and firmly staff members are very friendly.
원본: 제가 라멘을 잘 모르긴 하지만 유독 느끼하고 일식치고도 짜서 한 젓가락에 물 두 모금씩은 마셨고 매운 거라면서 하나도 안 맵고 테이블은 비좁고 음악은 너무 시끄럽고…, 번역: I don't know the ramen, but I feel poisonous and squeezed out, so I drank two sip of water in one chopstick, and I didn't spicy, and the table was cramped and the music was too noisy.
원본: 멘야산다이메 라멘은 기본에 충실하면서도 너무 맛있습니다. 교자도 꼭 드세요., 번역: Menyasan DaiMe ramen is faithful to the basics and is so delicious.Be sure to eat gyoza.
원본: 혜화에서 유명한 라멘집입니다. 맛도 좋고 분위기도 좋아요. 친절은.. ㅠ, 번역: It is a famous ramen restaurant in Hyehwa.The taste is good and the atmosphere is good.Kind..ㅠ
원본: 멘국물을 먹어보니 기본적으로 돼지뼈로 우러내어 진국인 돈코츠라멘의 육수와 달리,카라쿠치라멘의 육수는 확실히 먹자마자 칼칼한맛부터 확 느껴졌습니다.뭐 체인점이라 크게 실패할일도 없었지만 가끔 지점마다 맛없는곳도 있다고 하던데 멘야산다이메 대학로점은 나쁘지 않은 편이었던듯 하네용, 번역: When I ate men's soup, it was basically a pork bone, and unlike the broth of Don Kotsu Ramen, which was a pork bone.Well, there was no big failure because of a chain store, but sometimes there are some places that are tasteless.
원본: 돈코츠 라멘의 진한 국물과 네기, 차슈 등 정말 맛있었지만 면이 덜 익었던 게 아쉬웠습니다. 교자는 보통이었습니다., 번역: Donkotsu Ramen's rich broth, Negi, and chashu were really delicious, but it was a pity that the noodles were less cooked.Gyoza was normal.
원본: 예상보다 맛있어서 놀랐다. 양은 많으나 가격이 만만치는 않은 편. 매장이 좁은 점이 아쉽다., 번역: I was surprised that it was better than expected.The amount is large, but the price is not full.It's a pity that the store is narrow.
원본: 음식이랑 가격은 좋은데 노래가 너무 시끄러워서 조용한 분위기를 바란다면 비추천, 번역: The food and the price are good, but the song is so noisy that if you want a quiet atmosphere, it is not recommended

 92%|█████████▏| 20521/22421 [04:06<06:23,  4.95it/s]

원본: 강남 대학로점 기본적으로 믿음가는 곳입니다. 자랑스럽게 추천합니다. 면의 양은 많으니 토핑을 기호에 맞게 추가하시는것이 좋습니다., 번역: Gangnam University Road is basically a trusted place.Proudly recommend.The amount of cotton is large, so it's a good idea to add toppings to your preference.
원본: 진한국물의 라멘먹고 싶을 때 가는집! 맛달걀이 맛있어서 꼭 하나 더 추가해서 먹는 곳, 같이 곁들여 먹는 파김치가 있어서, 질리지 않는 맛!, 번역: When you want to eat the ramen of Jinhan Mokmu!The taste egg is delicious, so you can add one more and eat it together.
원본: 아주자주가는 단골집입니다주차는 바로밑에 택시회사에 하시면되고 메인도 맛있지만 밑반찬이 아주맛있어요 셀프리필이라 눈치 안 보고 먹어도돼요, 번역: It is a regular restaurant. The parking is just under the taxi company, the main side is delicious, but the side dishes are very delicious.
원본: 여기 존맛ㅠㅠ반찬도 셀프리필가능 주차도 편함!!!반찬하나같이 다 맛있어요, 번역: Here is John Taste.!!All the side dishes are delicious
원본: 카페랑 레스토랑이랑 나뉘어져 있답니당카페 근처에 데코를 잘 해놔서 예뻐용 카페는 두 층으로 되있는데 윗층은 긴 테이블 한개만 있어용 카펜데도 화덕피자를 팔더라구요음료는 무난무난 맛있었어용, 번역: It is divided into a cafe and a restaurant, so the deco is good near the cafe, so the beautiful café is on two floors, but the upper floor is only one long table.
원본: 비쥬얼 최강! 기념일이나 드라이브때 기분 낼때 좋음.통삼겹 하와이안 바베큐 예상하는 맛은 미쿡, but 맛은 이것도 저것도 아닌 퓨전코리안의 맛., 번역: Visual strongest!Good when you feel like an anniversary or drive.The expected taste of Hawaiian Barbecue is Micook, but the taste of fusion Korean is not that or that.

 92%|█████████▏| 20530/22421 [04:07<06:01,  5.24it/s]

원본: 볶음밥이 살짝 매콤하고 보슬보슬해서 맛있다. 삽겹살 요리도 정말 추천! 스테이크가 부드럽고 향이 좋다. 탄두리치킨은 무난한 맛. 시저샐러드도 좋다., 번역: The fried rice is slightly spicy and delicious.I also recommend sapgyeopsal dishes!The steak is soft and fragrant.Tanduri Chicken is a good taste.Caesar salad is also good.
원본: 출입구가 지하로 들어가는 작은 문이라 그냥 지나치기 쉬워요~안은 이국적이고 활기찹니다~음식은 다 맛있었는데 특히 껌진 하이산이라는 매운 해산물 볶음밥이 참 맛있었어요~ 반쎄오, 분짜, 쌀국수도 먹는 즐거움을 배가해주는 좋은 맛이었습니다~가격대비 굉장히 푸짐하구요^^, 번역: It's just a small door that enters the basement, so it's just easy to pass ~ It's exotic and lively ~ The food was delicious.It was a good taste ~ It's very rich for the price
원본: 1. 평일 오후 7시30분쯤 방문, 테이블 꽉차기 직전이라 웨이팅 없이 입장2. 이국적인 분위기, 알록달록한 느낌3. 셋이서 분짜, 볶음밥, 쌀국수 주문4. 볶음밥은 매운맛이 선택가능해 중간맛으로 시켰는데 적당히 매콤해서 좋았음5. 쌀국수는 뭐 맛있는 쌀국수 맛, 고기가 푸짐해 좋았음6. 분짜는 다 좋았는데 소스맛이 좀 아쉬웠음7. 적당한 가격으로 베트남 음식 한번씩 먹기 좋은 곳, 번역: 1. Visit at 7:30 pm on weekdays, just before the table is full.Exotic atmosphere, colorful feeling 3.Set out of the three, fried rice, rice noodles order 4.The fried rice is a spicy taste, so it was made of medium.Rice noodles are delicious, the taste of rice noodles, the meat was great.The bun was good, but the sauce taste was a bit unfortunate 7.A good place to eat Vietnamese food at a reasonable price
원본: 알록달록한 인테리어의 베트남음식점입니다.반쎄오가 맛있는데, 분무기로 라이스페이퍼를 적셔서 먹어야하는 거라 먹기 불편한면이 조금 있습니다만 맛은 정말 맛있습니다!쌀국수는 무난한 맛이었어요., 번역: It is a Vietnamese restaurant with colorful interiors.Banseo is delicious, but I have to moisten the rice paper with a sprayer, so I have a little inconvenient to eat, but the taste is really delicious!The rice noodles were good.

 92%|█████████▏| 20537/22421 [04:09<06:13,  5.04it/s]

원본: #주님이먹여살려주시는인생 #안녕베트남-✔반쎄오 (14,000원)✔반미 (7.500원)✔청포도에이드-#샤로수길처돌이 오랜만에 베트남음식 먹고왔어요.[안녕베트남]이라고 들어본적은 많은데,지하에 있어서 잘 안보였었네용.#안녕과자점 #안녕부산 이랑 같은 회사겠죠?베트남 느낌 물씸나는 인테리어와 분위기도 음식점의 매력을 더 upup 시키는것 같습니다 :)-[반쎄오]는 라이스 페이퍼에 소고기,새우,숙주를 싸서 먹는 베트남 전통 음식이래요! 숙주소고기 튀김은 겉바삭 속촉촉하니 맛있었습니다. but 맛있지만 번거로운 음식! 저한테는 번거롭게 느껴지더라고요.. 장갑끼고, 물 칙칙 뿌려서 라이스페이퍼를 싸서 먹는게 귀찮기도하고.. 똥손..이라, 페이퍼가 예쁘게 안 싸져요 흑흑. 예쁘게 싸는법 아시는 분 😭???-[반미]는 바삭한 바게트가 돋보이는 샌드위치인데요,바게트 정말 바삭바삭하니 맛있더라고요.. 고기랑 야채도 가득가득 푸짐해서 반미 하나만 먹어도 배가 찹니다.또 먹고싶다... #반미 💛💛🙆🏻‍♀️고수 싫어하시는 분들은 고수 빼달라고 꼭 말씀하세요!-다음에는 분짜를 먹으러 가야겠어요.#샤로수길맛집 #샤로수길베트남 음식집으로 추천드릴게요., 번역: #Life that the Lord feeds and saves #He Vietnam ✔ Banseo (14,000 won) ✔ Banmi (7. 500 won) ✔ Cheongpo AidI have heard of [Hello Vietnam], but I couldn't see it in the basement.#Hey a confectionery #Hoh Busan is the same company?!The fried meat was delicious because it was crispy.But delicious but cumbersome food!I felt cumbersome for me..It is bothersome to eat with gloves and sprinkle with water..Dungson..So, the paper is not pretty cheap.If you know how to pack it pretty 😭 ???[Banmi] is a sandwich with crispy baguettes..The meat and vegetables are also full, so even if you eat only one half, you will be hungry.I want to eat again...#Bani 💛🏻‍♀️ If you do not like adherence, please tell us to take it out!Next time, I have to go to eat.#Sharosu -gil restaurant
원본: 베트남 여행 브이로그를 보고 반쎄오가 너무 먹고싶었는데 샤로수길을 가게되어 맛집뒤져보는데 마침 이 곳에서 반쎄오를 판다길래 가보았습니다. 너무 맛있었어요. 짜조도 바삭바삭하고 안에도 살짝 기름지니 맛있었는데, 반쎄오는... 진짜 너무 맛있었급니다. 노란 튀김이 뭔지는 잘 모르겠는데 라이스페이퍼에 같이 싸먹으니 완전 바삭거리면서 맛있더라구요. 또 갈겁니다 ㅠㅠ.. (팃커층? 충? 이건 그냥 그랬어요.. 같이 간 친구가 쌀국수를 별로 안좋아해서 밥으로 된거 시켜봤는데 저한텐 좀 향이 안맞았던거같아요)(2019.12.03), 번역: I watched Vietnam Travel V Log and I wanted to eat Banseo too much.It was so delicious.It was crispy and it was a bit greasy inside, but Banseo was delicious...It was so delicious.I don't know what the yellow tempura is, but it's so crispy and delicious because it's wrapped in rice paper.I'll go again..(I just did it. I didn't like rice noodles because I didn't like rice noodles.
원본: 반세오를 처음먹엇는데 신세계네요! 정말 맛잇엇어요! 베트남 모자가 있어서 인증샷 찍기도 넘나 좋았어용 ㅎㅎ, 번역: I ate Banseo for the first time, but it's Shinsegae!It was really delicious!I had a Vietnamese hat, so it was good to take a certification shot.
원본: 2회 방문. 휴양지 분위기의 베트남 음식점. 바삭한 반쎄오가 제일 맛있었다., 번역: Two visit.Vietnamese restaurant with a resort.The crispy Banseo was the most delicious.
원본: 베트남음식 처음 먹어본 친구도 정말 맛있게 먹고왔습니다!!그리고 식당을 아기자기하게 잘 꾸며놓았어요! 외국에 온 느낌!, 번역: The first friend who had eaten Vietnamese food was really delicious!!And I decorated the restaurant very well!Feeling abroad!
원본: 분짜랑 반쎄오 둘다 처음 먹어봤는데 특이한거같아요. 분짜는 사실 면이랑 고기랑 채소랑 따로나오는데 어떻게 먹는건지 애매했는데 그냥 그렇게 따로 먹는 음식인가봐요...반쎄오는 튀김을 쌈에 월남쌈으로 말아서 싸먹는데 이것도 특이했어요. 맛이 엄청 있다기보다 이색적인 맛이어서 한번쯤 먹어보기 좋은 거 같아요. 매장 내 분위기도 신선하고 좋아요., 번역: I've eaten both Bunja and Banseo for the first time, but I think it's unusual.It's actually a noodle, meat and vegetables, but it's ambiguous how to eat...Banseo wrapped the tempura in a ssam and wrapped it in a ssam.It's a unique taste rather than a lot of taste, so I think it's good to eat.The atmosphere in the store is fresh and good.

 92%|█████████▏| 20542/22421 [04:10<06:04,  5.16it/s]

원본: 마치 베트남에 온듯한 인테리어🌴음식도 깔끔하고 술먹은 다음날 쌀국수로 해장👍여름엔 분짜 추천✌️하지만 여름 한정 비빔쌀국수는 비추...😂, 번역: The interior is like Vietnam 🌴 The food is clean and the next day after drinking...😂
원본: 샤로수길 베트남 음식으로 추천좌석불편. 가격이 조금 내려갔으면..., 번역: Sharosu -gil Vietnamese food is inconvenient.I hope the price goes down a little...
원본: 음식의 맛이 풍부하고 다양한 선택지가 있습니다. 고수와 특이한 향 좋아하신다면 추천합니다., 번역: There is a variety of options rich in the taste of food.It is recommended if you like the coriander and the unusual fragrance.
원본: 샤로수길 베트남은식점인데 웨이팅 있음 쌀국수는 맛있나 볶음밥은 비추 망고맥주가 젤맛있다 인테리어는 너무예쁘다, 번역: Sharosu -gil Vietnam is a shopping branch. We have a weighted rice noodles. The fried rice is delicious.

 92%|█████████▏| 20546/22421 [04:11<05:54,  5.29it/s]

원본: 일요일 11:30분 방문쌀국수가 안된다고 함. 여기서 1차 벙.하지만 분짜와 반쎄오를 시킴.맛없기 힘든 분짜는 걍 보통이고오돌뼈가 좀 많음.반쎄오는 기름기가 너무 많았다.많이 먹고 싶어도 먹을수가 없다.안녕~베트남.재방문의사 없음, 번역: Sunday 11:30 Visit Rice Noodles.Here's the first bun.But I made a ja and Banseo.The hard -to -tasty man is normal and there are a lot of bones.Banseo had too much greasy.Even if you want to eat a lot, you can't eat.Hello ~ Vietnam.No willingness to return
원본: 아기자기하게 잘 꾸며놔서 분위기도 좋고 맛있어요:) 쌀국수는 무난무난, 번역: The atmosphere is good and delicious because it decorates well. :) The rice noodles are good
원본: 항상 줄이 길어 못갔다운좋게 간날볶음밥이 정말 맛있었다, 번역: The fried rice was really delicious on the day that I couldn't go long because of the long lines.

 92%|█████████▏| 20549/22421 [04:11<05:52,  5.31it/s]

원본: 샤로수길에 존재하는 몇안되는 진짜 맛집 반쎄오 가격이 좀있지만 맛있다, 번역: There are some real restaurants Banseo's price in Sharosu -gil, but it's delicious.

 92%|█████████▏| 20551/22421 [04:11<05:39,  5.51it/s]

원본: 인테리어가 너무 예뻐요. 웨이팅이 길긴 하지만 맛있으니까 참을만 해요., 번역: The interior is so pretty.The weight is long, but it's delicious.

 92%|█████████▏| 20554/22421 [04:12<05:03,  6.15it/s]

원본: 허울만 좋은 일회용 인스타카페가 난무하는 송리단에서 유일하게 맘에 들었던 곳. 전체적인 공간이나 메뉴에서 정돈된 컨셉이 잘 느껴지고 고민을 해서 운영하시는 게 디테일에 묻어난다. 매장 자체의 인테리어나 경험이 돈값을 하고, 수플레 자체로는 더 맛있는 곳도 많지만 메뉴, 커피, 기물 모두 평타 정도는 하는 퀄리티다., 번역: The only place I liked in the Songri Team, which is a good disposable Instagram Cafe.The organized concept is well felt in the overall space or menu, and the details are buried in detail.The interior or experience of the store itself is paid, and the souffle itself is more delicious, but the menu, coffee and objects are all about flat.
원본: 온커피는 묵직한 맛의 드립커피이고, 화커피는 산미가 있는 가벼운 드립커피이다. 플레인 수플레는 부드러우면서 폭신하고, 개인적으로 생크림이 부드럽고 맛있었다. 수플레 좋아하면 와볼만하다고 생각이 든다., 번역: The whole coffee is a drip coffee with a heavy taste, and the coffee is a light drip coffee with acidity.The plain souplet is soft and fluffy, and personally, the fresh cream was soft and delicious.I think it's worth seeing if you like souffle.

 92%|█████████▏| 20556/22421 [04:12<05:21,  5.80it/s]

원본: 주말이라 웨이팅 있었지만 예쁘고 깔끔했어요 ~~! 바 좌석 앉으면 직접 핸드드립 하는 모습도 볼 수 있습니당 핸드드립 맛있어요 ~~!! 수플레팬케이크도 과일소다도 맛있어요,,그런데 아쉬운건 가격이 또르르 ,,, 밥먹었다 생각했어요, 번역: It was a weekend, but it was pretty and neat ~~!If you sit down, you can see the hand drip directly.!Supplet pancake is also delicious, but it's a shame, but the price is too price ,,, I thought it was eaten.
원본: 팬케이크 맛있지만 점 비싼느낌은 있어요. 커피도 맛있습니다., 번역: Pancake is delicious but it feels expensive.Coffee is also delicious.

 92%|█████████▏| 20558/22421 [04:12<05:40,  5.47it/s]

원본: 비싸도 너무 비싸요.. 물론 수플레 팬케이크에 들어가는 노력을 제가 몰라서 하는 말 일 수도 있지만.. 맛있긴한데 저 돈 주고 또 먹고싶지는 않네요 ㅠㅠ 음료도 너무 비쌌어요. 그리고 2인석 위주로만 되어 있어서 3명이서 갔는데 앉기도 너무 불편했어요. 2명 이서 가는거 추천드려요., 번역: It's too expensive..Of course, I don't know about the effort to enter the souffle pancake..It's delicious, but I don't want to eat that money again.And it was only two people, so I went to three people and it was too uncomfortable to sit.I recommend two people going.

 92%|█████████▏| 20559/22421 [04:13<05:49,  5.32it/s]

원본: 여기 분위기 좀 묘함..... 뭔가 사이비 종교 단체가 만든 호텔 로비에서 커피 마시는 느낌...;;;;;; 엄청 이색적임 그래도 커피나 팬케이크는 괜찮 #온화, 번역: The atmosphere here is a bit strange.....I feel like drinking coffee in a hotel lobby made by a pseudo religious group...;;;;;;It's so unusual, but coffee and pancakes are okay

 92%|█████████▏| 20560/22421 [04:13<05:59,  5.18it/s]

원본: 수플레 제대로 된곳이 이곳이 처음인거 같네요.입에 넣는 순간 사라지는 마법이라.먹는데 몇분 안걸린거 같아요.분위기 있는곳에서 수플레와 함께 하실려면이곳 추천 드러요.다만 커피는 제가 예가체프 매니아인데특유의 향이 많이 안나서 아쉬웠습니다. 산미도 아쉬웠구요. 명색이 드립 커피인데이점이 개선이 되었음 하네요.편의 시설은 바로 옆 유료주차장 있구요.오전 일찍가는거 외엔 웨이팅이 존재합니다.참고하세요, 번역: I think this is the first place here.It's a magic that disappears the moment you put it in your mouth.I think it took a few minutes to eat.It is recommended here to be with the souven in the atmosphere.However, the coffee is a chiff enthusiast, but it was a pity that it didn't have much flavor.I was sorry for the acidity.The destination, which is a drip coffee, has been improved.There is a paid parking lot next to it.There is a weight except to go early in the morning.please refer to this

 92%|█████████▏| 20561/22421 [04:13<06:07,  5.06it/s]

원본: 처음 가본 곳인데, 수플레케이크가 몽실몽실 정말 맛있었어요!!!! 가격은 조금 비싼 편이지만 그래도 만족해요!, 번역: I've been to the first place, and the soufflecake was really delicious!!!!The price is a bit expensive, but I'm still satisfied!

 92%|█████████▏| 20562/22421 [04:13<06:26,  4.81it/s]

원본: 송리단길 수플레팬케이크와 밀크티 맛집! 나쁘지 않은 가성비를 자랑함, 단점은 테이블이 작아서 뭔가 불편하게 먹는 느낌이 든다!, 번역: Songri -gil Supplet Pancake and Milk Tea Restaurant!It is not bad, and the disadvantage is that the table is small, so it feels uncomfortable!

 92%|█████████▏| 20563/22421 [04:14<06:31,  4.74it/s]

원본: 웨이팅이 꽤 길고 수플레를 시켜먹어야 하는듯 하다. 수플레 안시키고 밀크티만 마셔봤는데 이것도 무난하다., 번역: The weighting is quite long and it seems to have to be eaten with a souffle.I didn't have a souffle and I only drank milk tea, but this is okay.

 92%|█████████▏| 20564/22421 [04:15<11:36,  2.67it/s]

원본: 비쥬얼만큼 맛또한 훌륭함 재방문하여 다른 팬케이크도 도전해보고싶음, 번역: I want to try to try other pancakes by visiting other pancakes as good as visuals.

 92%|█████████▏| 20565/22421 [04:15<10:37,  2.91it/s]

원본: 수플레 , 2만원치고는 별로 였던것 같아요.. 음료는 맛있었어요., 번역: Souffle, I think it was not good for 20,000 won..The drink was delicious.

 92%|█████████▏| 20566/22421 [04:16<13:54,  2.22it/s]

원본: 일단 분위기가 차분하고 직접 조리하는 것도 볼 수 있어서 좋았어요, 번역: It was nice to see the atmosphere calm and cooked directly.

 92%|█████████▏| 20567/22421 [04:16<11:58,  2.58it/s]

원본: 음식들이 다 맛있습니다. 내부가 좀 좁은 편이라 식사시간에 맞춱시면 웨이팅은 좀 있으나, 기다려서 먹을만큼은 맛있어요! 특히 음식소스들이 딱 알맞게 맛있네요!, 번역: The foods are all delicious.The interior is a bit narrow, so if you match the meal time, there is a weight, but it's delicious enough to wait!Especially food sauce is just right!

 92%|█████████▏| 20568/22421 [04:16<10:32,  2.93it/s]

원본: 너무 맛있었어요, 파스타 간이 좀 세서 깔조네는 가지를 시키길 잘한 것 같아요! 조합이 너무 좋았습니다, 번역: It was so delicious, I think that the pasta was a little good to have a good branch!The combination was so good

 92%|█████████▏| 20569/22421 [04:16<09:38,  3.20it/s]

원본: 생각보다 골목안에 있고 아담한 곳이었어요.페퍼크림파스타가 꾸덕하고 약간의 매콤함이 느끼함을 잡아줘서 정말 맛있었어요., 번역: It was in an alley than I thought.Pepper Cream Pasta was so delicious that it felt a little spicy and a little spicy.

 92%|█████████▏| 20570/22421 [04:16<09:03,  3.41it/s]

원본: 연남동에 먹으러 다니면서 재방문한 곳은 처음이다 음식이 좀 단짠이라 자극적이긴 한데 계속 손이간다 특히 페퍼크림파스타가 제일 맛있었다, 번역: It's the first time I've returned to Yeonnam -dong and returned to it.
원본: 신라호텔 주방장이 차렷다고 해서 엄청 기대하고 갔는데 그냥 무난저난해요.. 아무래도 음식은 알바생이 만들어서 그렇겟죠?ㅠ, 번역: The chef of the Shilla Hotel was very excited..Maybe it's because the food is made by Alba Saint?

 92%|█████████▏| 20572/22421 [04:17<07:15,  4.24it/s]

원본: 일단 매장은 크지 않고 아기자기한 분위기이고 오픈키친형식입니다. 시그니처 메뉴인 페퍼크림 파스타는 처음에 먹었을땐 오 맛있다 하는데 먹다보면 좀 자극적+어디선가 맛본듯한? 그런 맛이에요., 번역: First of all, the store is not big, a cute atmosphere and an open key friend.Pepper Cream Pasta, the signature menu, is delicious when you first eat it.It tastes like that.

 92%|█████████▏| 20574/22421 [04:17<06:11,  4.97it/s]

원본: 골목 좀 깊은 곳에 있어서 찾아갈때 헤멤웨이팅 시 명부에 연락처 적고, 자리났을때 전화해 주는건 좋았는데... 그렇게 들어가서도 음식이 좀 늦게 나옴.차라리 명부에 웨이팅 적을때 메뉴까지 같이 적게하고, 자리 나고 전화해서 오는 시점부터 바로 요리 들어갔으면 더 회전률이 빨랐을 텐데 싶음.맛은 있었음. 깔조네 양이나 맛은 상상 이상이었고 샐러드도 괜찮았고.시간이 없어서 아쉬웠던 거지 다음번에 여유있을때 와서 천천히 먹고가고 싶었음, 번역: It's a little deep in the alley, so when I go to Hayemway, it was good to write down the list and call when I was in place...Even if you go in, the food comes out a little late.I'd rather have a menu when I wake up on the list, and if I went to the dishes from the time of calling and calling, I would like to have a faster turnover.It tasted.The sheep and the taste were beyond imagination and the salad was fine.It was a pity that I didn't have time. I wanted to eat slowly when I was relaxed next time
원본: 근처에 있으면 몇 번 더 갈 의향이 있는 곳이에요. 소프트크랩 특성상 게의 향보다는 튀김 옷 맛이 강하고 소스가 매우 꾸덕해서 취향이 갈릴 수도 있을 것 같네요🤔 명란 오일 파스타는 두번 먹어봤는데 두번 다 괜찮았어요., 번역: If you are nearby, you are willing to go a few more times.Due to the nature of the soft crap, the taste of the fried clothes is stronger than the scent of crabs, and the sauce is very dull.

 92%|█████████▏| 20577/22421 [04:18<04:52,  6.31it/s]

원본: 골목에 위치하고 있어 찾기 조금 힘들 수있어요 파스타랑 스테이크 맛있었어요, 번역: It's located in the alley, so it's a little hard to find it.
원본: 음식이 전체적으로 맛있습니다. 가격대비 훌륭하구요. 페퍼크림파스타는 제 초딩입맛 취저하였습니다. 연어도 맛있고 찹스테이크도 맛있고..다 맛있네요. 와인 가격 35천까지.. 부담없이 소규모 모임에 최고인듯 합니다., 번역: The food is delicious as a whole.It's great for the price.Pepper Cream Pasta was tasted in my choding.Salmon is delicious and chop steak is delicious..It's all delicious.Wine prices up to 35 thousand..It seems to be the best for small meetings.

 92%|█████████▏| 20579/22421 [04:18<04:49,  6.35it/s]

원본: 비프 칼조네 피자와 비프크림스파게티 모두영념소블고기 단맛이 너무 강해서 단맛이음식의 맛을 싹  망치네요.피자도우와 파스타는 좋은데 양념불고기의과다한 양념맛때문에 질려서 다 먹을수 없었음., 번역: Both Beef Kalzone Pizza and Beef Cream Spaghetti have a strong sweet taste of meat and ruin the sweet seams.Pizza dough and pasta were good, but they were tired because of the excessive seasoning of seasoned bulgogi.
원본: 고르곤졸라 깔조네, 가지치즈 파니니맛은 무난무난하니 괜찮은편, 직원분들 친절도는 매우 좋음!, 번역: Gorgonzola, Gaepanini tastes good, it's okay, and the staff's kindness is very good!

 92%|█████████▏| 20580/22421 [04:18<05:05,  6.02it/s]

원본: 테이블이 몇개 없는게 단점이긴 한데 파스타는 정말 맛잇음 피자는... 특이하긴한데 피자 스타일의 맛은 아닌듯, 번역: There are a few tables, but pasta is really delicious...It's unusual, but it's not like the taste of pizza style

 92%|█████████▏| 20582/22421 [04:19<07:21,  4.16it/s]

원본: 생긴 지 얼마 안됐을 때 방문했을 때도 친절해서 기억이 많이 남았는데(물론 음식도 맛있었고요)여전히 친절한가 보네요^^음식도 양 많고 진짜 재방문 의사 있는 식당입니다.이번 달에도 갈거에요 오랜만에 ㅎㅎㅎ아무튼 강추!! 번창하시길 바라요!, 번역: It was not a while since I visited, and I remembered a lot of memories (of course the food was delicious).I'm going to go this month too.!I hope you thrive!
원본: 맛이 강한 편이었어요. 파니니보다 파스타가 더 맛있었어요!, 번역: It tasted strong.Pasta was more delicious than panini!

 92%|█████████▏| 20586/22421 [04:19<05:42,  5.36it/s]

원본: 아침시험이 있던 날이라 끝나자마자 웨이팅이 없는적이 없던 버터밀크에 오픈 전 줄서러 가봤다10시 오픈인데 9시40분에 도착했으나! 우리 앞엔 이미 10명 대기중ㅠㅠ 오픈때까지 우리 뒤로도 7-8명 정도가 더 기다렸다문열고 딱 우리 앞에서 끊겨서 다시 45분정도 대기해서 입장..! 시간없는 사람들은 절대 못 먹어볼 가게다세명이 가서 팬케익을 종류별로 다 시켜봤다가장 기본인 버터밀크팬케익은 빵이 아주 포슬포슬 포근포근하다 맛도 약간의 달콤과 담백함의 조화라 달콤한 시럽, 휘핑같은 것이 가득 나오는 디저트식 팬케익하곤 다르게 샐러드가 어울리고 한끼식사를 하는 느낌!리코타치즈팬케익은 안에 리코타치즈가 들어있는데 버터밀크보다 좀 더 촉촉하고 살짝 쫀득?한 식감이다 리코타치즈답게 치즈맛은 강하지 않다! 리코타세트에 소세지도 추가를 했는데 얇게 썰어서 팬케익과 함께먹으면 꽤나 잘 어울린다트리플치즈팬케익은 단품으로 주문! 안에는 고다, 고르곤졸라, 리코타치즈가 풍성히 들어있다 하지만 너무 풍성했는지 느끼하다 처음 몇 입은 맛있게 먹었지만 느끼함때문에 많이는 먹을 수 없는 맛여기에 10-3월 한정메뉴라는 양파크림수프까지 먹어봤는데 하얀크림수프에 양파가 들어있을 것 같았지만 나무색?수프가 나왔다 양파와 버섯이 굉장히 많이 들어있고 꾸덕한 스프가 아니라 국처럼 묽은 스프였다 먹으면 표고버섯향이 먼저 훅 들어오고 그 후에 스프의 맛이 느껴진다 같이 나오는 토스트는 그냥 버터만 올라가있는 것이기 때문에 스프에 찍어먹는게 더 맛있다~전체적으로 양이많아서 꽤 남겼는데 다음에 또 세명이서 오게되면 버터밀크세트하나 리코타단품하나 꿀딸리요! 시켜서 먹을 듯 하다 시즌이 안 맞아서 못 먹어본 꿀딸리요가 궁금해서라도 한 번 더 오고싶긴 한데 웨이팅이 너무 길어서 과연 올 수 있을지는 의문,,ㅎㅎ, 번역: As soon as the morning test was there, I went to butter milk that I had never had no weight, but I went to the line before opening at 10 o'clock and arrived at 9:40!In front of us, 10 people are already waiting for us..!People without time will never eat three people, and the pancakes are made by type.It's a dessert pancake full of things, and the salad looks like a meal and a meal!Ricotta Cheese Pancake has a ricotta cheese inside, but it's more moist and slightly chewy than butter milk.I added sausages to the licota set, but sliced thinly and eat it with a pancake.There are rich in Goda, Gorgonzola, and Ricotta Cheese, but I feel so rich.The soup seemed to contain onions, but the wooden color? Soup came out. It contains a lot of onions and mushrooms, and it is a thin soup like soup, not a soup.It's just a butter, so it's more delicious to dip it in the soup.I think I'll eat it.

 92%|█████████▏| 20588/22421 [04:20<05:58,  5.11it/s]

원본: 굉장히 맛있던 팬케이크 집입니다. 가성비도 가성비지만 맛도 굉장히 좋았어요.이전에 유행했던 수플레식 팬케이크는 아닙니다. 하지만 식감은 거기에 지지않을만큼 푹신하고 부드러워요.혼자 갔을때는 리코타나 버터밀크 핫케이크 단품에 꿀딸리요(시즌한정 메뉴)를 곁들여 먹었어요.여러 사람이 갔을때는 리코타, 버터밀크, 트리플 세트를 시켜서 나눠먹었습니다.개인적으로 여기는, 두 사람이 가서 리코타 팬케이크 세트와 트리플 세트와 꿀딸리요를 시킨 후, 서로 팬케이크를 한쪽씩 교환해서 먹는걸 추천드려요.리코타는 부드러운 치즈가 든 고소한 맛입니다. 트리플은 짭쪼름하고 진한 치즈맛이 강한 팬케이크고요. 트리플 맛이 진하다보니까, 2장째를 먹기 시작하면 살짝 입 안이 물리더라고요. 그래서 처음엔 리코타 1장을 먹고, 그 뒤에 트리플 1장을 먹는 편이 좋을것같아요!먹는 양이 그리 많지않으시다면 단품도 좋은 선택같아요 (특히 혼밥의 경우) 세트는 으깬 감자랑 샐러드 등이 더해지는거라서.. 전 사실 단품으로 먹는게 더 좋더라고요.여기 가게는 꽤 작은 편입니다. 한 테이블에 인원은 셋 이상 못 들어가니 이 점 주의하세요. (셋까지가 한계. 4명 X)가게 주인분의 기억력이 매우 비상하세요. 계산하는데 예전에 방문한걸 바로 알아보시고 인사해주시더라고요..., 번역: It is a very delicious pancake house.The price was also costly, but the taste was very good.It's not a souples pancake that was popular before.But the texture is soft and soft enough not to lose there.When I went alone, I ate Ricotana butter Milk hot cake with honey (season limited menu).When several people went, I had a set of ricotta, butter milk, and triple.Personally, I recommend that the two go to the ricotta pancake set, the triple set, and the honey.Ricotta is a savory taste with soft cheese.Triple is a pancake with a strong cheese taste.The triple taste is rich, so when I start eating the second chapter, my mouth is bitter.So at first, I think it's better to eat one ricotta and one triple after that!If you don't have a lot to eat, the a la carte is a good choice (especially for Honbab)..I actually liked it as a la carte.The store here is quite small.Note that you can't enter more than three people in one table.(The limit to the three. 4 people x) The owner of the store is very extraordinary.I found out that I visited and greeted me...
원본: 홍대 최고의 브런치집. 그렇지만 정작 매일 홍대를 가는 홍대생들은 웨이팅때문에 맛도 못 본다는 사람이 태반이다. 오픈 한시간 전부터 줄이 생긴다...! 외국인 관광객들이 몰리면 두시간 반씩 줄을 서야함 (근데 이정도로 맛집은 아님)애매한 시간대에 가서 적당히 기다리다가 웨이팅 없이 먹는다면 5점이겠으나 .. 그렇지 못한 경우가 많아서 4점으로 깎음.최고의 메뉴는 사실 팬케이크보다도 꿀딸리요다. 싱싱한 딸기와 리코타치즈, 요플레에 꿀을 곁들인 흔한 조합인데 이게 미치도록 맛있다....!  (이거 다 떨어지면 가게 문 닫고 퇴근하심 3시 40분경)1인 1메뉴 아니니까 둘이 가서 팬케익세트 하나에 사이드 이것저것 시키는것을 추천그리고 다른거 말고 무조건 소시지를  추가해야지만 단짠 밸런스가 맞는다. 잊지말고 추가하기~~! 추가주문 안받으니까 먹어볼까 싶은건 그냥 시켜라.오렌지 주스는 밍밍한게 5천원값을 못했다. 돈아까웠음. 시키지 말자, 번역: Hongdae's best brunch house.However, the placenta who can't taste the taste because of the waiting for Hongdae students every day.There is a line before the opening...!If foreign tourists are crowded, they have to line up for two and a half hours (but it's not a restaurant)..There are many cases where they are not so 4 points.The best menu is actually a honey -soaked teeth than a pancake.Fresh strawberries, ricotta cheese, and yople are commonly combined with honey....!(If this falls, it's a person to close the store and leave the office around 3:40.) It's not a one -person menu.Don't forget to add ~~!I don't get an additional order, so just do it.Orange juice did not pay 5,000 won.It was a waste of money.Let's not let you

 92%|█████████▏| 20590/22421 [04:20<05:54,  5.17it/s]

원본: 이 집 맛집이다. 테이블이 6개정도라 웨이팅을 30분정도 해야하지만 실망시키지 않는 맛과 가격이다. 팬케잌은 포슬포슬하고 알맞다 샐러드도 싱싱하고 계란도 올리브유에 알맞게 구워져나옴 베이컨이 약간짜지만 밸런스가 좋다 늦게가면 재료소진될수 있으니 주의할것.사장님도 매우친절4.1 / 5.0, 번역: This is a restaurant.There are about six tables, so we have to wait 30 minutes, but it's a taste and price that doesn't disappoint.The pancake is suitable for the porsnot. The salad is fresh and the eggs are baked for olive oil.The boss is also very kind 4.1 / 5. 0
원본: 꿀딸리요라는 딸기 꿀 리코타 요거트 샐러드와 치즈 패케이크 와 기본 팬케이크를 먹었는데 그냥 그랬음 요즘 수플레 팬캐이크가 유행하고 여기를 가봤는데 음....여기 들어가려고 추운날 거의 1시간 대기해서 먹었는데 그정도의 값어치는 모르겠다 가성비는 나쁘지 않아서 사람없으면 가볼만함 살면서 한번정도는 먹어볼만 험, 번역: I ate a strawberry honey yogurt salad, a cheese pack and a basic pancake....I ate almost an hour of waiting for a cold day to go in, but I don't know the value of that price.

 92%|█████████▏| 20591/22421 [04:20<05:39,  5.39it/s]

원본: 추운아침에 길고 긴 줄을 오지게 기다려서 먹을 보람이 있는 맛.아침에 일찍 기상해서라도 사수해보고싶은 메뉴들.꿀딸리요는 정말 상큼하게 부드럽고 버터밀크는 폭신폭신하고 든든하다, 번역: Waiting for a long and long line in cold morning, it is rewarding to eat.The menus I want to shoot even if I wake up early in the morning.Honey is so fresh and soft and the butter milk is fluffy and strong

 92%|█████████▏| 20593/22421 [04:21<07:02,  4.33it/s]

원본: 벌써 4번이나 방문한 늘 웨이팅이있는 작은 팬케이크 맛집. 웨이팅은 점점 길어지기만 하는데.. 수프를 빼도좋우니 꿀딸리오는 꼭 먹으세요 팬케익은 눈감고시켜도 맛있음, 번역: A small pancake restaurant with always waiting has already been visited four times.The weighting is getting longer..It's good to get rid of the soup.
원본: 진짜 인생 맛집입니다!!지금까지 먹었 던 팬케이크 중에 제일 맛있었어요.한입 먹는 순간 입에서 부드러움과 고소함이결합되어서 너무 감동적이였어요 ㅠ단,웨이팅이 너무 길어서 눈치게임에성공하길 바래요~, 번역: It's a real life restaurant!!It was the most delicious pancake I've eaten so far.At the moment of eating, it was so touching that the softness and the savoryness were combined in the mouth.

 92%|█████████▏| 20595/22421 [04:21<05:58,  5.10it/s]

원본: 워낙 웨이팅이 길다해서 4시쯤 혹시나하고 가봤는데 앞에 두팀정도 있어서 30분정도 기다렸다가 들어갔어요! 저희 들어가고 두세팀정도 받고 마감하시더라는...! 팬케잌 세트 세가지있는거 다시켰는데 플레이팅도 넘 예뿌고 맛도 죠았습니당 단점은 조리시간이 좀 길다는거..?근데 팬케잌 특성상 어쩔수없는 부분인거 같아영ㅎㅎㅎㅎ느긋하게 기다리면 됩니당! 다음엔 토스트나 샌드위치도 먹어보구싶네욘ㅎㅅㅎ, 번역: I was so long, so I went around 4 o'clock, but I waited for 30 minutes and went in in front of you!We went in and received about two or three teams and finished...!There are three pancake sets, but the plating is over and the taste is tasted..? But I think it's inevitable because of the pancake.Next time, I want to try toast and sandwiches.
원본: 설명이 필요없어요 다들 가세요 웨이팅이 단점이긴하지만 먹어보면 맛이 잊혀지지가 않아요. 맛있어요 정말., 번역: There is no need for explanation. Everyone goes, but the weighting is a disadvantage, but the taste is not forgotten when you eat it.It's delicious.

 92%|█████████▏| 20597/22421 [04:22<05:44,  5.30it/s]

원본: 정말 맛있는 팬케이크집입니다. 항상 대기가 있다는게 조금 단점이지만 기다릴수 있을정도로 맛있어요!, 번역: It's a really delicious pancake house.It's always a disadvantage to have a waiting, but it's delicious enough to wait!
원본: 웨이팅이 꽤 긴편인데 그걸 상쇄하는 맛있음이었어요! 브런치 좋아하시는 분들께 강추!!, 번역: The weight is quite long, but it was delicious to offset it!Recommended for those who like brunch!!

 92%|█████████▏| 20601/22421 [04:22<03:38,  8.33it/s]

원본: 로제 파스타 먹고 싶어서 방문했는데 접시도 크고 양이 아주 많았어요. 소스가 조금 뻑뻑하다 싶긴 했는데 맛있었어요.산토리 하이볼이 6000원이라 파스타에 한 잔 하기 좋네요., 번역: I wanted to eat Rose pasta, but the dishes were large and very large.I wanted to be a little stiff, but it was delicious.Santori highball is 6,000 won, so it's good to have a drink at pasta.
원본: 해물이 들어간 메뉴는 모두 다 맛있었어요~(파스타 or 리조또 / 크림 or 토마토 or 로제)그래도 굳이 꼽자면,<크래미새우로제파스타> 추천드려요!2인 3만원이면 배불러요;;양도 푸짐하고, 분위기도 괜찮은 편이예요사장님도 친절하시구요~(식전 빵 셀프 리필 가능한데,구워먹을 수도 있어요~), 번역: The menus with seafood were all delicious ~ (Pasta or Risotto / Cream or Tomato or Rose) Still, I would recommend <Krami Shrimlos Gemasta>!If you are 30,000 won for 2 people, you will be full ;; The amount is also good and the atmosphere is good.

 92%|█████████▏| 20603/22421 [04:22<04:23,  6.89it/s]

원본: -무료주차 가능하고 주차장 넓습니다.-두명이서 세개 주문하면 많이 남길듯하네요-로제, 크림 전부 맛있습니다 !, 번역: Free parking and spacious parking lots.If you order three people, it will be left a lot.
원본: 식전빵이 맛있음! 명란크림파스타는 명란맛이 많이 나진 않았지만 맛있음! 전체적으로 소스가 꾸덕하고 재료들이 실하고 신선함! 양이 많음!, 번역: The bread is delicious!The cod roe cream pasta didn't have a lot of spicy clever taste, but it's delicious!Overall, the sauce is thin and the ingredients are fresh and fresh!A lot!

 92%|█████████▏| 20605/22421 [04:23<04:30,  6.71it/s]

원본: 새우로제파스타랑 스테이크피자를 먹었는데 정말 맛있더군요. 스테이크 피자는 저는 치즈 맛이 강해서 스테이크는 잘 못 느꼈는데 여자친구는 맛있다고 합니다.새우는 오동통해서 정말 맛있고요.이 식당의 최고 특징은 식전빵을 마음대로 먹을 수 있는겁니다. 식전빵 주제에 너무 맛있어요. 허니 소스 찍어먹으면 그야말로 꿀맛..., 번역: I ate Zefasta and Steak Pizza with shrimp and it was really delicious.The steak pizza has a strong cheese, so I didn't feel the steak, but my girlfriend is delicious.Shrimp is really delicious through malfunction.The best feature of this restaurant is that you can eat before your meal.It is so delicious on the bread topic before the meal.If you eat honey sauce, it's really honey...
원본: 두명이서 파스타1, 피자1 시켰는데 양이 생각보다 많아서 놀랐습니다. 플레이팅도 예쁘고 일단 주문을 타블렛으로 하는것부터 신선했고 식전빵에 찍어먹는 소스 정말 맛있었습니다., 번역: Two people were pasta 1 and pizza 1, but I was surprised that the amount was more than I thought.The plating was pretty, and it was fresh from making a tablet as a tablet, and the sauce was really delicious.

 92%|█████████▏| 20607/22421 [04:23<04:44,  6.38it/s]

원본: 늘 맛있었는데 처음 방문시엔 음식준비가 엄청 느렸었는데 최근엔 빨리 완성해 주시네요맛나게 먹었습니다재료가 신선하고 풍부해 맛있습니다~, 번역: It was always delicious, but when I first visited, the food was very slow.
원본: 해산물 오일파스타 맛있다토마토 아라비아따 맛있다맥주세트메뉴, 번역: Seafood Oil Pasa Tasty Tomato Arabia Ta Mac Mac Set menu

 92%|█████████▏| 20609/22421 [04:23<04:43,  6.39it/s]

원본: 다이닝코드 평점보고 갔는데..서비스 맛 둘다 엉망이었습니다.알바생의 실수로 저희 주문이 옆 테이블로 갔는데 이에 대한 설명도 없이 기다리게만 하고, 한참뒤에 컴플레인 하려고 벨 눌렀더니 그제서야 와서 상황 설명하고 죄송하다면서 에이드 한잔 주셨습니다. 그리고, 새로 만들어서 나온 음식은 급하게 만들어서인지 맛이 없었습니다. 리조또는 밥알이 뭉쳐있었고, 파스타는 매우 짰습니다. 먹다가 어이가 없어서 숟가락 놓고 계산만 하고 나왔습니다.실수는 할 수 있다고 생각합니다. 하지만 그에 대한 대응이 최악이었고, 음식이라도 맛이 있었으면 헤프닝 정도로 끝났을텐데.. 즐거운 저녁 시간에 얼굴만 붉히고 나왔네요.방문 고려하시는 분들은 참고해주세요., 번역: I went to the dining code rating..Both the service taste was a mess.With Alba's mistake, our spell went to the table next to it, and I just waited without explaining it, and I pressed the bell to complain for a while.And, the newly made food was made in a hurry and it was not cognitive.Risoto or rice eggs were together, and the pasta was very hot.It was ridiculous to eat, so I put a spoon and calculated it.I think you can make mistakes.But the response to that was the worst, and if the food was tasted, it would have been over as the hef..I only blushed my face in a fun evening.If you are considering a visit, please refer to it.
원본: 너무 느끼할것 같았지만 그러지 않아서 더 매력적인 맛의 파스타였음, 번역: It seemed too much, but it wasn't because it was a more attractive pasta

 92%|█████████▏| 20611/22421 [04:24<04:55,  6.12it/s]

원본: 국물이 진짜 뜨끈뜨끈하게 나와서 속푸는데 좋아요. 들깨탕은 특히나 저희 엄마께서 고소하다고 정말 좋아하셔요.  들깨탕도 국밥도 안에 건더기가 정말 많아요. 가격도 저렴하도 직원분들도 어르신들에게 너무 친절해서 마음이 늘 따뜻해지는 곳이네요^^, 번역: The soup is really hot and it's good to get rid of it.You really like the perilla soup, especially my mom is sued.There are so many plums in the perilla soup and soup.Even if the price is low, the staff are so kind to the elderly.
원본: 저렴한 가격에 점심 먹기 굿건강하고 집밥 먹는 기분굿, 번역: Good for lunch at an affordable price

 92%|█████████▏| 20613/22421 [04:24<05:07,  5.87it/s]

원본: 시래기국밥시래기들깨탕부추전 시래기소불고기시래기갈비, 번역: Sirae Ki -gukbab Siraegi
원본: 2회 방문. 고기 잡내가 전혀 없는 깔끔한 순대국. 순대와 부속고기도 푸짐하게 나온다., 번역: Two visit.A neat sundae soup with no fish.Sundae and attached meat also come out.

 92%|█████████▏| 20615/22421 [04:24<04:50,  6.21it/s]

원본: 시래기순대국이 일품단품 순대도 매우 훌륭함공간이 협소해서 식사시간때는 웨이팅이 많아 빨리 가야 함혼자 갈 경우 다른 사람과 같은 테이블을 써야 하니 주의, 번역: The Sirae Gi -Soon Power is also very good, so the space is also very good, so there is a lot of weight at the time of meals, so if you have to go fast, you have to use the same table as others.
원본: 전국 순대투어를 해본 나로써는, 여기가 진짜 가격대비, 제일 만족한다혼자 먹으러와도 되고, 가격도 착한데, 맛은 일품이다 집만 가까우면 맨날 가고싶다 포장에는 국물 서비스를 안 주는게, 지하에 있는게 좀 아쉽지만. 아 또 먹고싶다 ㅠ.ㅠ, 번역: In my national sundae tour, here is the real price for the real price. I can come to eat alone, and the price is good. The taste is excellent.Unfortunately.Oh I want to eat again.ㅠ

 92%|█████████▏| 20616/22421 [04:24<05:09,  5.83it/s]

원본: 회전율이 좋고 바쁜데 친절한 집 많이 없는데, 여기는 친절한데다가 밥 무한리필이구요, 처음에 에피타이저로 편육을 주네요 ㅎㅎ, 번역: The turnover rate is good and busy, but there are not many kinds of kind house, but this is kind and it is an infinite refill.

 92%|█████████▏| 20618/22421 [04:26<10:01,  3.00it/s]

원본: 양고기 냄새가 심하지 않아 좋아요! 양등갈비 뼈발라먹기 귀찮지만 너무 맛있어요, 번역: It's good because the smell of lamb is not severe!It's annoying to eat both ribs, but it's so delicious
원본: 양꼬치 자체의 질은 평균이상, 향신료도 챙겨먹게 비치되 있는건 좋지만 요리류의 수준이 처참하다.  꿔바로우는 과하게 두꺼운 튀김옷으로 내가 지금 꿔바로우를 먹는건지 기름찹쌀떡을 먹은지 헷갈릴 지경에 소스도 다소 역한 향이 섞여있다.  마파두부는 당황스럽게도 연두부로 조리되 나오며 소스는 지나게 짜 원래 잇어야 할 알싸하게 매운맛을 덮어버린다.  양꼬치만 먹자면 갈수 있겠지만 맛난 중식을 생각하고 간다면 큰 실수가 될 곳이다.  종업원들은 말하지 않아도 자잘한 반찬을 잘 가져다 주는등 친절하지만 요리류의 퀄리티가 씁쓸함을 감추기 힘들게 한다., 번역: The quality of the skewer itself is more than average, and the spices are good, but the level of cooking is terrible.The sauce is mixed with too thick fragrance, with excessive thick fried clothes.The mapo tofu is embarrassedly cooked with soft tofu, and the sauce is overwhelmed with the spicy taste.If you only eat lamb skewers, you will be able to make a big mistake if you think about delicious lunch.Employees are kind, such as bringing good side dishes without saying that they do not say, but the quality of cooking makes it hard to hide its bitter quality.

 92%|█████████▏| 20621/22421 [04:26<05:38,  5.32it/s]

원본: 강서구청 유명한 양꼬치집 중 하나입니다. 꿔바로우도 너무 맛있어요, 번역: Gangseo -gu Office is one of the famous lamb skewers.It's so delicious
원본: 맛있어서 재방문한 맛집가게분위기도 깔끔하고 음식도 깔끔하고 정갈하게 나옴연어뱃살이 품절이라 연어사시미, 우나기벤또, 나가사키라멘을 시켰는데 메뉴가 모두 다 너무 맛있었고 신선해서 깨끗하게 싹싹 긁어 먹음연어사시미는 2-3부위가 나왔던 거 같고 도톰하고 신선해서 맛있었고장어덮밥은 밥 양념도 정말 너무너무 맛있었고 나가사키라멘은 해산물도 꽤 들어가 있고 싱싱해서 씹는 맛이 있어 좋았음다른 메뉴들도 또 먹어보고 싶어 다음에 또 방문할 예정주차는 불가하고 공릉역에서 그리 멀지 않으니 대중교통 이용을 추천점심, 저녁 피크타임에는 대기가 있는 편, 번역: The restaurant's atmosphere was delicious because it was delicious, the food was clean and tidy.It seemed to come out and it was so thick and fresh, and the eel rice bowl was so delicious, and Nagasaki Ramen had a lot of seafood and fresh and chewy.It is impossible and not far from Gongneung Station.

 92%|█████████▏| 20623/22421 [04:26<05:31,  5.43it/s]

원본: 처음 생겼을 때부터 갔던 곳인데 인기 너무 많아져서 테이블 수가 늘었음.맛있는데 양도 많음. 그래서 4명이 가면 3개 시키는 게 더 나을 수 있음.같이 데려간 친구 중에 안좋아한 사람이없음.이 근처는 주차지옥이라서 지하철, 버스로 공릉역 2번출구 나와서 걸으면 금방임.사케도로동은 먹는 방법 직원이 설명해줌., 번역: It was a place I had since first, but it was so popular that the number of tables increased.It is delicious but it is also a lot.So if four people go, it may be better to do three.None of the friends who took it together did not like it.This is a parking hell, so if you walk out of Gongneung Station Exit 2 by subway and bus, it will be right if you walk.How to eat sake -do -dong is explained by the staff.
원본: 깔끔하고 맛있어요! 음식 시킨것마다 하나같이 맛있어서 재방문 많이 한 곳이에요 일요일은 휴무고 중간에 브레이크 타임 피해서 가면 좋습니당!!, 번역: Clean and delicious!Everything I made was delicious, so I returned to visit a lot.!

 92%|█████████▏| 20625/22421 [04:27<05:23,  5.55it/s]

원본: 일본 가정식 맛집! 가츠동 너무 부드럽고 맛있어요 ㅎㅎ, 번역: Japanese home -style restaurant!Katsu -dong is so soft and delicious haha
원본: 맛있었고, 먹는방법도 설명해주시고, 조용한편이라 대화하기도 좋고..추천이요, 번역: It was delicious, explained how to eat, and it's quiet..Recommended

 92%|█████████▏| 20626/22421 [04:27<05:37,  5.32it/s]

원본: 점심시간에 갔더니 웨이팅 이삼십분 한듯.. 왕기대해서 그런가 그냥 그랬다. 줄서서 먹을 정도는 아닌듯. 그냥 보통사케동이랑 똑같았다. 좀 더 깔끔하게 나오는 정도??, 번역: I went to lunch and it seemed to be twenty minutes of weight..It was just like that.It's not enough to eat in line.It was just the same as a normal.It comes out more neat ??

 92%|█████████▏| 20627/22421 [04:27<05:56,  5.03it/s]

원본: 공릉동 맛집 랭킹 1위라 기대했는데 가츠동은 좀 국물이 많고 그냥 적당히 맛있는 수준이었다. 기대가 컸나... 가격은 가츠동이 만원이면 솔직히 비싼편인데 양도 많은편은 아님. 다만 생맥주는 ㄹㅇ 입자가 조밀하다 해야되나 목넘김이 부드럽고 3천원밖에 안함 추천합니다., 번역: I was looking forward to the ranking of Gongneung -dong restaurant, but Katsu -dong had a lot of broth and it was just a moderately delicious level.Did you expect great?..The price is honestly expensive if Katsudong is 10,000 won, but not a lot.However, the draft beer should be dense, but the neck is soft and only 3,000 won is recommended.

 92%|█████████▏| 20628/22421 [04:27<06:18,  4.74it/s]

원본: 늘 사람많음. 맛 괜춘. 마파덮밥메뉴도 맛있음. 2호점은 이제 밥을 안 판다고 함(선술집으로 변경), 번역: There are always many people.Good taste.Mapa Rice Bowl menu is also delicious.The second store says that it is no longer sold (change to a tavern)

 92%|█████████▏| 20629/22421 [04:28<06:34,  4.55it/s]

원본: 음싯맛보통 그냥그랫고 분위기 아담하고 깔끔함 사람이많음, 번역: Music Sit taste is usually just a lot of people and neatness.

 92%|█████████▏| 20630/22421 [04:28<06:37,  4.50it/s]

원본: 본인은 가츠동을 먹었는데 분위기 좋은 것, 요리 예쁘게 만든 것 빼고 너무함.  고기는 질기고, 튀김은 딱딱하고, 기름은 느끼하고, 소스는 너무 달고... 현재 63점의 평가는 주변 분위기에 의해 과대 평가된 것으로 판단됨.주인께서는 종로 긴자바이린이나 동부이촌동 모모야 가츠동을 보고 배워야 할 듯., 번역: I ate Katsu -dong, but it's too good to make it good.The meat is tough, the fried is hard, the oil is felt, the sauce is too sweet...Currently, the evaluation of 63 points is judged to be overestimated by the surrounding atmosphere.The owner seems to have to learn from Jongno Ginzaberin or Momoya Katsu -dong, Dongbu Ichon -dong.

 92%|█████████▏| 20631/22421 [04:28<06:42,  4.45it/s]

원본: 깔끔하고 연어 상태 나쁘지않고, 직원이 설명해주는 사케동 먹는 방식은 ??싶은데 뭐 그렇다. 고로케도 따끈하고 기름 쩐내 안 나고 만족. 사케동을 먹고 싶고 내가 공릉동이다, 그러면 고민없이 갈듯., 번역: It's not clean and bad salmon, and the way of eating sake -dong explains ??Therefore, it is also warm and grease.I want to eat sake -dong and I am Gongneung -dong, and then I will go without worry.

 92%|█████████▏| 20632/22421 [04:28<06:39,  4.48it/s]

원본: 공릉역 철길 근처구요가격저령하고 맛은 평범합니다 좋아요, 번역: It's near Gongneung Station Iron Railroad.

 92%|█████████▏| 20633/22421 [04:28<06:48,  4.37it/s]

원본: 벌써 3번째 다녀감 ㅋ 새우튀김도 엄청 맛있고 무엇보다 대표 메뉴인 사케동 예술임 ㅋ, 번역: Already the third time, the shrimp tempura is very delicious, and most of all, it is a representative menu.

 92%|█████████▏| 20634/22421 [04:29<07:03,  4.21it/s]

원본: 저녁식사로 간단히 사케동을 먹었는데 평범한 식사였습니다.단지 아쉬운 점은 김치가 중국산이라 특유의 맛 때문에 실망 했어요, 번역: I simply ate sake -dong for dinner and it was an ordinary meal.I was disappointed that I was disappointed because of the unique taste because kimchi was made in China.

 92%|█████████▏| 20635/22421 [04:29<06:58,  4.27it/s]

원본: 브레이크타임에 몇번 걸려서 ㅠㅠ ㅋ가게가 작아서 테이블간격이 좁아서 좀 불편해요.맛은 괜찮아요!, 번역: It's a little uncomfortable because the shop is small because it takes a few times in the break time.The taste is fine!

 92%|█████████▏| 20636/22421 [04:29<07:05,  4.19it/s]

원본: 사케동이 정말 맛있는 일상다반. 좀 좁고 웨이팅이 잦은 것 빼곤 만족합니다. , 번역: Sake -dong is really delicious everyday.I am satisfied with the narrow and the frequent weight.

 92%|█████████▏| 20637/22421 [04:29<07:02,  4.22it/s]

원본: 사케동은 맛있는데 나머지는 그럭저럭..양도 그렇게 많은편은 아님. 배 안부름. 가성비 별로., 번역: The sake -dong is delicious, but the rest is..The amount is not so much.Heart.By price.

 92%|█████████▏| 20638/22421 [04:30<06:57,  4.27it/s]

원본: 대부분 메뉴를 맛있게 즐길 수 있지만, 자리도 좁은데 가격이 아쉽다, 번역: You can enjoy most of the menu, but the seat is good, but the price is unfortunate.

 92%|█████████▏| 20639/22421 [04:30<11:23,  2.61it/s]

원본: 평범해요, 번역: Ordinary

 92%|█████████▏| 20644/22421 [04:32<08:14,  3.59it/s]

원본: 지나갈 때마다 맛있는 냄새가 나서 궁금했는데 한번 가 보았다. 일단 매장이 작은 편이라 자리는 협소. 테이크아웃이나 배달 주문도 많은 편이라 회전율은 빠른 편이다. 수제버거인데 가격대가 합리적이어서 괜찮은 듯. 기본 치즈버거도 구성이 꽤 풍성하다.(토마토,치즈,패티 두툼함) 버거 크기도 다른 수제버거집들 생각하면 큰 편. 세트로 시키면 생각보다 배부르고 양이 많으니 참고하세요~음료는 1인 1음료시 무한 리필인데 탄산음료 구성도 꽤 다양하다. 감자튀김 맛은 쏘쏘. 사실 버거+음료만으로도 배가 부르다. 아보카도 들어간 버거가 유명한 모양이라 재방문 예정., 번역: Every time I passed by, I was curious because it smelled delicious.Once the store is small, the seat is narrow.There are also a lot of takeout and delivery orders, so the turnover is fast.It's a homemade burger, but the price is reasonable.The basic cheeseburger is also quite rich.(Tomato, cheese, patty thick) Burger size is also big when you think of other homemade burgers.If you set it with a set, it is full and sheep more than you think. Please refer to it.Potato fries taste.In fact, Burger+drink alone is hungry.Avoca is also famous because it is famous.

 92%|█████████▏| 20645/22421 [04:32<08:41,  3.40it/s]

원본: 처음 개업했을 때부터 갔는데 한결같이 맛있어요. 추천합니다, 번역: I've been to the first time, but it's delicious.I recommend it

 92%|█████████▏| 20646/22421 [04:32<08:23,  3.52it/s]

원본: 매장도 아담하고 조용해여 수제버거가 진짜 맛있어요 머쉬룸 버거에 계란후라이 추가는 진리, 번역: The store is small and quiet, and the homemade burger is really delicious.

 92%|█████████▏| 20648/22421 [04:33<07:25,  3.98it/s]

원본: 요즘 수제버거집 기본 만원이 넘어가는데 셋트 시켜도 만원이 안넘고, 몇주년 기념일 할인 이벤트도 가끔 하는데 맛도 있고 저렴하게 먹게되어 기분이 좋다. 햄버거 생각나면 롯데리아 맥날 이런데 안가고 버거파크에서 패티맛 제대로 느껴지는 버거 먹는다., 번역: Nowadays, the basic burger house is over 10,000 won, but even if you set it, it is not over 10,000 won.If you think of hamburgers, you don't go to Lotteria McMall, but you eat burgers that you can taste properly in Burger Park.
원본: 음식은 먹어본수제버거중 상위에속할정도로 맛있다가격도 저렴한편에속하는거같다주차는 알아서골목에 살짝해야될거같다 전용주차장은없고 빌라촌인근이다, 번역: The food is delicious enough to belong to the top of this waterburger.

 92%|█████████▏| 20650/22421 [04:33<06:48,  4.34it/s]

원본: 맛있음 베이컨 바삭바삭함 콜라리필 가능 / 근데 깨가 많아요, 번역: Delicious bacon crispy collar refills / but there are many sesame seeds
원본: 매장이좁고 사람이많습니다맛은있는데 늦게 가면 기름이 좀 안깨끗한것 같기도하고..여튼 맛은있어요, 번역: The store is narrow and there is a lot of people..Anyway, it tastes

 92%|█████████▏| 20652/22421 [04:33<06:04,  4.85it/s]

원본: 성신여대 근처에서 가장 맛잇는 버거입니다 다른 데는 못가요, 번역: It's the most delicious burger near Sungshin Women's University.
원본: 재료가 금방 떨어져서 메뉴가없어 아쉬웠다 성신여대 버거중제일 맛있다, 번역: It was a pity that the ingredients were falling away, so there was no menu.

 92%|█████████▏| 20654/22421 [04:34<05:24,  5.45it/s]

원본: 즉석 햄버거 집 분위기이고 가격은 비싸지만 특색있는 햄버거를 많이 팔고 맛도 있어요. 아포카도가 들어간 햄버거 먹었는데 맛있었습니다  다만 좀 비싼편이죠, 번역: The instant hamburger is the atmosphere and the price is expensive, but it sells a lot of unique hamburgers and tastes.I ate a hamburger with apokado, but it was delicious but it was a little expensive.
원본: 가게가 좁은데 사람이 많아서 많이 기달려야하지만, 버거가 정~말 맛있어요. 종이 포장도 아주 마음에 듭니다!, 번역: The shop is narrow, but there are a lot of people, so I have to wait a lot, but the burger is good ~I also like paper packaging!

 92%|█████████▏| 20659/22421 [04:35<06:58,  4.21it/s]

원본: 작고 좌석이 많지 않다. 양은 딱 적당! 맛있게 잘 먹었다. 가끔 찾아갈듯, 번역: Small and not many seats.The sheep are just appropriate!I ate well.Sometimes I look for
원본: #사당역맛집 #안성각#전통중국요리 중에서도 내가 정말 좋아하는 #마라샹궈 (#마라향과 ) 랑 #띠산시엔 (#지삼선 ) 이 맛있는 곳!!! 😍 #샤로수길맛집 인 #두만강샤브샤브 랑 맛이 거의 비슷한 곳♡ 이곳의 #마라향궈 는 진짜 중국향이 많이 나서 호불호가 있을 수 있지만 #중국유학생 들이 추천하고 자주 찾는 곳이니~ 믿고 한번 먹어봐도 됨~ 백퍼센트 중국이랑 똑같다고 하긴 어려워도 한국에서 이정도로 맛을 내는 곳은 없음! 서울에서 먹어 본 곳중에서 이곳이 가장 #마라샹궈맛집 임!! 그리고 #띠산시엔맛집 이라고 해도 될 정도로 이집만의 특색이 가득담겨 있음 중국에서 접한것과는 다른 맛이지만 이대로가 그냥 맛있음! 이건 호불호 전혀 없을 맛이니 이곳에 방문하는 사람들은 꼭 시켜서 먹어볼 것을 추천드림♡ #중국요리맛집 #진짜중국요리 #사당맛집 #예약가능 바로 앞에 공영주차장 있음!! #남현동제1공영주차장 바로 앞, 번역: #Sadang station restaurant #Ansunggak #Am traditional Chinese cuisine, I really like #mara Xiang Guo (#Mara -hyang) and #Tisan City ( #Ji Samseon)!!!😍 #Sharosu -gil restaurant #Tumen River shabu -shabu is almost the same.It's hard to say it's the same as China, but there's no place in Korea!Among the places I have eaten in Seoul, this is the #marashang Guo restaurant!!And it is full of unique characteristics of this house that it can be called a #Tisan -si restaurant.This tastes like this.!#Namhyeon -dong Festival 1 Public Parking Lot

 92%|█████████▏| 20661/22421 [04:36<06:17,  4.66it/s]

원본: 1. 사당역 가성비 좋은 중국요리집2. 한국식 중국요리와 본토 중국요리를 함께파는데 맛이 썩 괜찮고 가격도 상당히 합리적3. 가게내부도 깔끔해서 식사만 하고 가는 커플들도 꽤 많더라4. 종종 들를법한 곳, 번역: 1. Sadang Station is good for Chinese cooking 2.It tastes good and the price is quite reasonable 3.There are quite a lot of couples who eat and eat in the store.Often
원본: 양도 많고 맛있다. 게다가 이런 가격이라면 친구들이랑 종종와서 마라탕도 실컷 즐길 수 있을거같구. 다른 메뉴들도 다 먹어보고싶다., 번역: It is also a lot and delicious.Besides, if it's a price, you can often come with your friends and enjoy Maratang.I want to eat all other menus.

 92%|█████████▏| 20663/22421 [04:37<09:15,  3.16it/s]

원본: 중화요리전문점. 마라샹궈는 개인적으로 얼얼함이 부족했지만 적당히 매워서 좋았음. 꿔바로우 맛있음. 지삼선 괜찮은 편., 번역: Chinese cuisine specialty store.Mara Xiang Guo was personally lacking, but it was good to be moderately spicy.It's delicious.Jisamseon is good.
원본: 음식은 다양하나 맛은 평범하거나 이하입니다, 번역: There are many foods, but the taste is normal or below.

 92%|█████████▏| 20665/22421 [04:37<07:46,  3.77it/s]

원본: 귀염뽀짝한 동네 카페상호에 맞게 달력 관련 물품들이 많다맛은 평범하지만 분위기가 따뜻해서 좋다, 번역: There are a lot of calendars related to the cute neighborhood cafe. The taste is plain but the atmosphere is warm
원본: 주택가에 위치한 숨은 카페커피에 그날의 날짜를 적어주는 재미난 컨셉과 아기자기한 인테리어가 좋았다커피는 부드러우면서 라떼의 우유거품과 잘 어우러져 맛있었다^^ 3가지 정도의 디저트가 있었는데 젤작은 앙버터링 구매. 시중 버터링쿠키안에 버터와 단팥을 넣었는데 1500원? 글쎄다--; ㅋㅋ  날씨가 추워서인지 카페안이 꽤 추웠다 따뜻한 봄날에 와서 먹어야지 재방문 의사 있다, 번역: The hidden café coffee located in the residential area has a fun concept that writes the date of the day and the cute interior. The coffee is soft and it blends well with the milk bubble of latte. There were three desserts.I put butter and red beans in the market buttering cookie.Well;ㅋㅋ The weather was cold, the cafe was quite cold.

 92%|█████████▏| 20667/22421 [04:38<06:28,  4.51it/s]

원본: 조용하고 예쁜 카페입니다. 한 가지 아쉬운건 매장이 워낙 좁아서 느긋하게 있기엔 좀 어려워요., 번역: It is a quiet and pretty cafe.One thing that's unfortunate is that the store is so narrow that it's hard to be relaxed.
원본: 애견동반 가능한 구산역 카페동네에 위치해 조용합니다., 번역: It is located in the Gusan Station Café neighborhood where you can be a dog.

 92%|█████████▏| 20669/22421 [04:38<05:50,  4.99it/s]

원본: 대조동에 요즘 이쁜카페들이 많아지고 있어요. 커피맛도 좋고 분위기도 짱이에요., 번역: There are a lot of pretty cafes these days in Daejo -dong.The coffee tastes good and the atmosphere is great.
원본: 점심시간에 손님이 많아서 웨이팅이 좀 있어요; 우동 전문점이라 우동 종류가 맛있고, 소스에 찍어먹는 마약김밥도 괜찮아요., 번역: There are a lot of guests at lunch, so there are some weighting;It is a udon specialty store, so the udon type is delicious, and the drug gimbap is also fine.

 92%|█████████▏| 20672/22421 [04:38<04:16,  6.83it/s]

원본: 여기 맛있어요사람 많아서 점심시간보다 빨리오거나 아예 늦게 와야해요 전 쫄면이 맛있더라구요, 번역: It's delicious here.
원본: 당산역에서 꽤 붐비는곳이에요 체인인만큼 맛보장됩니다 배달주문도 꾸준히 있더라구요 다먹을대쯤 조금 짠 느낌도 납니다 ㅎㅎ 튀김이 바로바로 튀겨져 나와서 맛있어요, 번역: It's a very crowded place at Dangsan Station. It's a chain.

 92%|█████████▏| 20674/22421 [04:39<04:35,  6.34it/s]

원본: 너무 맛있어요, 떡이 쫄깃쫄깃하구요 이인분이 양이 많아서 볶음밥은 못먹었어요’ 진짜 맛있어요, 번역: It's so delicious, the rice cake is chewy.
원본: 다양한 종류의 즉떡을 파는 분식집이에요.오징어 튀김이 많이 들어있고, 양념은 적당한 매콤한 달콤함이 있어 무난히 맛있게 드실수 있을거에요, 번역: It is a snack shop that sells various kinds of rice cakes.It contains a lot of squid tempura, and the seasoning has the appropriate spicy sweetness, so you can enjoy it.

 92%|█████████▏| 20676/22421 [04:39<04:42,  6.17it/s]

원본: 청년다방 오짱 정말 맛있어요차돌이 유명하지만 오징어 튀김이 훨씬 맛있더라구요, 번역: Youth Dabang Oh -chan is so delicious.
원본: 가성비가 매우 좋습니다. 세트 하나 시켜도 둘이 다 먹기가 힘들 만큼 많이 나옵니다. 저녁에는 웨이팅이 좀 있는데, 웨이팅이 길어져서 사장님께서 음료 무료 쿠폰을 주셨습니다., 번역: The price is very good.Even if you set up a set, they are as hard as it is hard to eat.In the evening, there is some weighting, and the weight is longer, so the boss gave me a free drink coupon.

 92%|█████████▏| 20678/22421 [04:39<05:05,  5.70it/s]

원본: 1회 방문. 맛은 괜찮았지만 떡을 잘라 먹기 번거로웠다., 번역: One visit.The taste was fine, but it was cumbersome to cut the rice cake.
원본: 친구랑 간식으로 요기 맛나요 에이드랑 먹으면 맛잇어요~, 번역: It tastes good for a snack with a friend and a snack.

 92%|█████████▏| 20680/22421 [04:40<05:06,  5.67it/s]

원본: 학교 앞에서 먹던 떡볶이 맛입니다. 고춧가루 맛이 칼칼하게 나면서 달짝 지근해요. 양도 푸짐하니 다 좋아할 맛이예요., 번역: Tteokbokki flavored in front of school.The red pepper flavor is tight and sweet.The amount is also rich, so it tastes like.
원본: 30년 전통, 고척동 맛집...여러 블로그에 올라있어 잔뜩 기대하고 갔었는데, 도로변의 그냥 오래 장사한 집일 뿐이었다. 떡볶이 2인분에 5천원. 가는떡과 불어터진 당면, 아주 약간의 야채...어묵이나 계란등 어떠한 단백질거리도 없다. 2인분임에도 혼자먹기에도 푸짐해 보이지 않는다. 맛은 흔한 동네의 떡볶이 수준, 뒤끝이 꽤 맵다.핫도그. 하나에 천원.가늘고 뻑뻑한 일반 소시지가 한개도 아니고, 반으로 잘라 들어간 비교적 살찐(?) 핫도그이다.튀김만두 3개 천원.약간의 당면만 들어간 기성품으로 추정되는 얇은 만두. 맛은 패쓰~....그외 다수 메뉴는 먹어보지 않았다.한마디로 실망스럽다.단지 오래되었다는 이유만으로 여러 블로그에 맛집으로 올라 있는건가?아련한 정성도, 음식의 푸짐함도, 안달나게하는 맛스러움도,..아무것도 없다.그냥, 2차선 도로 인도위에서 오고가는 자동차의 경적소릴 들으며 잠시 기웃거리게 되는 분식집이다., 번역: 30 years tradition, Gocheok -dong restaurant...I was on several blogs and I was looking forward to it, but it was just a long business on the roadside.5,000 won for 2 servings of Tteokbokki.Thin rice cake and bulging vermicelli, very little vegetables...There is no protein street such as fish cake or eggs.Even if you are two servings, you don't look so full.The taste is a common tteokbokki level, the back end is quite spicy.Hotdog.One thousand won in one.It is not a thin and stiff ordinary sausage, but a relatively fat (?) Hot dog that was cut in half.Three won of fried dumplings.A thin dumplings that are believed to be a ready -made product with only a little vermony.The taste is Pass ~....I haven't eaten many other menus.In short, I'm disappointed.Is it just a long time because it's old?.there's nothing.It's just a snooping house where you can listen to the car's horns that come and go from the two -lane road.

 92%|█████████▏| 20683/22421 [04:40<04:02,  7.17it/s]

원본: 달달한 떡볶이! 옛날 느낌 분식집야끼만두 필수! 어묵 필수! 쫄면 필수!마무리로 핫도그는 두말하면 잔소리!, 번역: Sweet Tteokbokki!Old feeling snacks, dumplings are essential!Essential fish cake!Must be a must!In the end, hot dogs are nagging!
원본: 어제 회식하고 먹는 음식 너무 맛이 있더라고요 고기가 살살 녹아요, 번역: It was so tasty that the food to eat and eat yesterday.

 92%|█████████▏| 20686/22421 [04:40<03:24,  8.49it/s]

원본: 구디에선 찾을수없는 고퀄의 고기집, 번역: High -quality meat restaurant that cannot be found in Gudi
원본: 산딸기바게트 맛있습니다(하지만 몇년 전보다 크기는 작아지고 안에 산딸기 보이는 것도 적어지긴 했습니다) 가격은 조금 있지만 맛은 괜찮습니다. 가게 확장이전했습니다., 번역: Ranked giveaway is delicious (but it's smaller than a few years ago, and it's a smaller thing to see raspberries).The store expansion has been transferred.

 92%|█████████▏| 20688/22421 [04:41<04:02,  7.15it/s]

원본: 천호의 유서깊은 빵집마감세일 시간에 방문해 만원박스 겟너무나도 혜자스럽다빵 각각의 맛이 동네빵집의 한계를 뛰어넘는 고퀄의 맛이었다, 번역: Cheonho's historic bakery was visited during the time of tax cuts, and it was a high -quality taste that went beyond the limits of the neighborhood bread.
원본: - 확장 이전해서 넓고 깔끔해요- 커스터드 레몬 크로아상 시켰는데 겉은 바삭하고 안에는 상큼해서 아메리카노랑 함께 먹는거 추천입니다- 빵 가격은 비싼편이지만 맛있음, 번역: It is spacious and tidy before the expansion. Custard lemon croan was made.

 92%|█████████▏| 20690/22421 [04:41<04:25,  6.51it/s]

원본: 전반적으로 가격대는 높으나 케이크와 음료 다 맛있음. 티라미수 라떼는 정말 티라미수 맛이 난다. 다른 카페에 티라미수 흉내만 낸 음료와 다름., 번역: Overall, the price range is high, but the cake and drinks are delicious.Tiramisu Latte really tastes tiramisu.It's different from a drink that just mimics tiramisu in another cafe.
원본: 큰길가에 있던 가게가 골목쪽으로 옮겼어요. 전용 건물이라 건물 자체도 크고 가게도 깔끔해요! 아이스 아메리카노는 고소한 맛이에요. 근데 사람들이 많아서 많이 시끌시끌하긴 하더라구요., 번역: The store on the big road moved to the alley.It's a dedicated building, so the building itself is big and the shop is clean!Ice Americano is a savory taste.But there are a lot of people, so it's so noisy.

 92%|█████████▏| 20692/22421 [04:41<04:53,  5.89it/s]

원본: 슈크림빵은 크림은 풍성하고 제일 추천하고 싶은건 카스테라크림롤. 부드럽고 달콤하게 넘어간다. 강추., 번역: The cream bread is rich in cream and the best recommended is Castella Cream Roll.Soft and sweet.Recommended.
원본: 빵한바구니에 만원이라 사먹었는데 전반적으로 맛있었어용 ㅎㅎ 가격에 비해 양도 많고 괜찮네요, 번역: I bought it because it was 10,000 won for the bread, but it was delicious overall.

 92%|█████████▏| 20694/22421 [04:42<04:47,  6.01it/s]

원본: 피자빵을 원래 좋아해서 빵집가면 피자빵을 먼저찾는데 p사의 피자빵이 성에 안차던 요근래 하이몬드를 방문하게 되었음빵가격은 3800으로 싼가격은 아니지만 맛있게 먹기좋은 간식!, 번역: I like pizza bread, so when I go to the bakery, I visit the pizza bread first.
원본: 워낙 괜찮은 빵집들이 많아져서 그냥.... 그저 그래요, 번역: There are so many decent bakery....So so

 92%|█████████▏| 20696/22421 [04:42<04:47,  5.99it/s]

원본: 성북동 빵공장 옆. 사람 많은 곳. 올때마다 같이 오는 사람들이 다 만족하는 곳. 깔끔 하고 맛이 있다, 번역: Next to Seongbuk -dong Bread Factory.Many people.Every time I come with people who come together.Clean and taste
원본: 음식이 참 깔끔하고 맛깔나요~만둣국은 색색이 이쁘고 맛도 깔끔 ~그치만 갠적으론 만둣국보단 갈비탕 추천합니다홍어회무침 좋아해서 시켜봤는데 조금 비싸긴하지만 양념 넘 자극적이지않고 괜찮았어요!부모님 모시고 다시 오고픈곳, 번역: The food is so clean and delicious ~ Mangukguk is so colorful and tidy.Where I want to come back with my parents

 92%|█████████▏| 20697/22421 [04:42<04:58,  5.78it/s]

원본: 갈비찜과 만두를 먹었다.갈비탕은 포장으로 가져왔다.갈비찜은 고기가 부드럽고 비쥬얼 역시훌륭해서 특색이 있게 맛있었다. 만두 역시 천연 재료로 색을 내서 형형색색 아름답고 맛도 무난히 좋았다.갈비탕은 상대적으로 무난한 느낌.갈비찜과 만두가 시그니쳐인 것 같다.다만 주말에 가면 사람이 너무 많아서 시장통 분위기이니... 바쁜 시간을 피해서 방문하면 더 한적하게 좋을 듯., 번역: I ate ribs and dumplings.Galbi -tang brought it to the packaging.The ribs steamed were soft and the visuals were excellent, so it was delicious.Dumplings were also colored with natural ingredients, so it was beautiful and beautiful.Galbi -tang feels relatively good.Ribs and dumplings seem to be signature.However, there are so many people on weekends, so it's a market...It would be nice to visit for avoiding busy time.

 92%|█████████▏| 20698/22421 [04:43<06:44,  4.26it/s]

원본: 주차공간이 좁아서 발렛주차를 해야되는 단점이 있지만 갈비탕에 고기도 많고 물냉면도 맛있었어요, 번역: The parking space is narrow, so there is a disadvantage of having to park valet parking, but the meat was delicious and the water cold noodles were delicious.

 92%|█████████▏| 20699/22421 [04:43<06:36,  4.35it/s]

원본: 갈비찜은 어떤거는 부드럽고 어떤거는 질겨요..! 직원분들이 잘라서 갖다주셔서 좋아용 양념은 최고 맛있어용비빔냉면도 많이 안맵고 맛잇습니당ㅎㅎ 여기 만두도 맛있어요!사람 많을 때는 벨 눌러도 안오셔서 별하나 빼요 ㅎ, 번역: Ribs are soft and some are tough..!The employees are cut and cut, so the sauce is the best.When there are a lot of people, even if you press the bell, it is not coming.

 92%|█████████▏| 20700/22421 [04:43<06:35,  4.35it/s]

원본: 마감하기 전에 가서 줄안서고 먹었는데 평소에는 줄서는것 같음다음번엔 갈비찜도 먹어보고 싶고네이버에 회냉면이 대표메뉴라고 써있어서 회냉면 먹었는데 조금 간이 쎈듯하나 맛있음, 번역: I went to the line before the end, but I usually seem to be lining up.

 92%|█████████▏| 20701/22421 [04:43<06:29,  4.42it/s]

원본: 갈비찜 먹고 고기 많이 남았는데 볶음밥 볶아달라고 하니까 고기 같이 볶아드릴까요 해서 네 같이 볶아주세요라고 했더니 나온건 잘게 썰어진 고기의 흔적? 큰걸로 여섯조각 넘게 남겼는데 주방에서 버린건지 집어먹은건지 어이가 없어서 그건 아무말도 안하고 나왔는데 볶음밥 드실거면 꼭 고기다 드시거나 빼두세요 눈탱이 맞습니다.알바는 부르면 대답도 안하고 지긋이 쳐다보고주문해도 고개만 살짝 끄덕이고.. 갈비찜이 이삼만원하면 그런 서비스 이해 하겠네요, 번역: I ate a lot of meat and left a lot of meat.I left more than six pieces of big things, but I didn't say anything because I had to eat it in the kitchen, so I didn't say anything.When Alba calls, he doesn't answer, but he looks at him and places his head slightly nodding..If the ribs steamed two thousand won, I will understand such a service.

 92%|█████████▏| 20702/22421 [04:44<06:37,  4.32it/s]

원본: 회냉면, 갈비탕 모두 아주 깔끔하게 맛있었습니다. 조미료 맛이 나지 않아서 더 좋았습니다, 번역: The sashimi cold noodles and ribs were all very neat.It was better because it didn't taste seasoning

 92%|█████████▏| 20703/22421 [04:44<06:31,  4.39it/s]

원본: 물냉면을 주문해서 먹었습니다. 육수는 단맛이 너무 강하게 돌아 다른 맛과 향이 묻히는 지경이고 면은 질기고 메밀향은 찾아 볼 수 없습니다. 여느 고기집 후식냉면으로 쓰는 면같네요. 공들인 음식이라고 전혀 느껴지지않아 실망입니다., 번역: I ordered water cold noodles and ate it.The broth is so strong that the sweetness is so strong that the other tastes and aromas are buried.It looks like it's used as a dessert in any meat house.I am disappointed that I don't feel it at all.

 92%|█████████▏| 20704/22421 [04:44<06:41,  4.28it/s]

원본: 줄서서  먹는집  이해안감  ㅜ ㅠ, 번역: I don't understand the house to eat in line ㅜ ㅠ

 92%|█████████▏| 20705/22421 [04:44<06:59,  4.09it/s]

원본: 건강식 먹고 싶을 때 가는 곳가격대에 비해서 돗때기 시장같은 곳, 번역: When you want to eat a healthy food, a place like a dodting market compared to the price range

 92%|█████████▏| 20706/22421 [04:45<06:55,  4.13it/s]

원본: 갈비찜이 정말 맛있네요.. 다시 한번 방문하고 싶은 맛집입니다. 강추^^, 번역: Ribs are really delicious..I want to visit again.Sublime

 92%|█████████▏| 20708/22421 [04:45<05:21,  5.32it/s]

원본: 라자냐가 대표메뉴이며 편안한 분위기가 인상적임 포르치니리조또는 약간 짰음, 번역: Lajaga is a representative menu, and the comfortable atmosphere is impressive.

 92%|█████████▏| 20709/22421 [04:45<05:47,  4.92it/s]

원본: 진짜매움 스트레스 확 날아감 양푸짐서비스좋고 뜨거운육수 맛짱 3컵마심줄서는맛집 땡기는 매운 맛 다시첮았다매운데 속이 편함 비법이겠죠맛있는 매운맛 중독 오늘은 아내와이전한곳은 가위와 김치는 셀프이다 맛은 그대로 기분좋게 매운 맛 지켜주세요, 번역: Real bitter stress flew away service good and hot broth, 3 cups of hot broth.Please keep the spicy taste pleasantly

 92%|█████████▏| 20710/22421 [04:45<05:59,  4.76it/s]

원본: 갑자기 매운음식이 생각나서 방문!! 난 매운걸 잘 못 먹기에 난 물냉 ! 동생은 비냉~! 비냉 한입 먹었는데 오오오 맵다 ㅋㅋㅋ 근데 이게 맛있게 매운게 아니라 쓰면서 매운맛? 맛있게 매운맛이 아니다ㅠㅜ. 이게 또 해주냉면만의 스타일일지도 !!! 만두 같은것도 있으면 더 좋을듯!! 물냉은 흔히 파는 냉면맛!!! 개인적으로는 비냉 양념에 새콤달콤 했으면 어떨까 하는 생각이 든다! 가격은 저렴하니 해주 냉면 유명하니까 한번 맛본것에 의의를 둬야겠다! 그냥 맵기만 하다. 한번 먹어봤으니 이제 안녕~ ㅋㅋ, 번역: Suddenly I remember spicy food!!I can't eat spicy things well!My brother is cold ~!I ate a rainy mouth, but it's spicy.It's not delicious.This is the style of cold noodles again!!!It would be better if there was something like dumplings!!Cold noodles are commonly sold!!!Personally, I think it's a sweet and sour seasoning!The price is cheap, so it's famous for the cold noodles, so I have to put it on the taste!It's just spicy.I've eaten it once, now hello ~ ㅋㅋ

 92%|█████████▏| 20711/22421 [04:45<06:06,  4.67it/s]

원본: 몇년 전, 잠실새내역쪽에서 자리옮기기전에 갔었을때 "맛집이었다"는 기억하는데 매력을 느끼진 못했었다.항상 물냉면을 먹어서 당연 물냉면을 시켰는데 식초,겨자 매운양념 첨가안했을때는 밍밍한 평양냉면인데 첨가하자마자 어떻게 이렇게 맛있어질까..? 원하는 컨디션으로 맛조절 가능! 매운양념 겁대가리없이 두 번 넣었다가 하..씁... 소리내면서 먹게된다 ㅋㅋㅋ자주 와보신 분들은 "비냉에 육수조금 주세요"하는거 보고 다음에는 나도 그렇게 먹어봐야겠다., 번역: A few years ago, when I went to the place of Jamsil's new history.It was a restaurant.I didn't feel attractive to remember.I always ate water cold noodles and made water cold noodles..?Taste can be adjusted with the desired condition!Put it twice without spicy seasoning..Write...I eat it in a sound ㅋㅋㅋ If you have come often.I would like a little broth in the rain cold.I have to try it next time.

 92%|█████████▏| 20712/22421 [04:46<06:17,  4.53it/s]

원본: 20년 단골. 신천에서 잠실종운동장 사거리 쪽으로 옮겨 특유의 공장 분위기가 없어지고 깔끔해졌지만, 개인적으로 신천쪽 분위기가 나름 느낌있었음. 오랜만에 갔는데 맛은 그대로 ㅎ 하지만 가격이 오름. 그래도 한그릇 6천원. 4천원이던 시절부터 갔는데 그래도 푸짐히 먹고 저렴하죠. 개인적으로 매운냉면집 중에서는 갑! 맛있게 매콤하면서 중독성있는 양념장. 맵지만 적당한 수준이라 스트레스 풀리는 곳! 무채가 적당히 감칠맛나고 맛난 곳 . 특히 면발이 쫄깃 탱탱한게 비법일듯, 번역: 20 years regular.It was moved from Sincheon to Jamsil Stadium Intersection, and the unique factory atmosphere disappeared and became clean, but I personally felt the atmosphere of Sincheon.It's been a long time, but the taste is as it is, but the price rises.Still, 6,000 won for a bowl.I went to 4,000 won, but it's cheap.Personally, among the spicy cold noodles!Deliciously spicy and addictive sauce.It's a spicy but appropriate level, so it's stressful!The radish is moderately rich and delicious.Especially, it seems to be a secret that the noodles are chewy

 92%|█████████▏| 20713/22421 [04:46<06:21,  4.47it/s]

원본: 꿀팁: 물냉을 시킨다-겨자0.5줄-설탕3스푼-식초0.5줄++++++++양념장1스푼^^*-육수 원샷으로 마무리왜냐면 양념에 겨자가 퐉퐉퐉쳐있음.. 모르고 겨자1스푼 따라했다가 다 못먹었어요, 번역: Tip: Make Water Cooling 0.5 lines of sugar 3 spoon vinegar 0.5 lines ++++++++ Seasoned 1 tablespoon broth one shot..I didn't know it and followed 1 tablespoon of mustard and couldn't eat it all

 92%|█████████▏| 20714/22421 [04:46<06:26,  4.42it/s]

원본: 엄~청 맵지않지만 매운ㅋ물냉면에 양념소스 넣어 먹는 걸 추천, 번역: It is not spicy, but it is spicy.

 92%|█████████▏| 20715/22421 [04:46<06:38,  4.28it/s]

원본: 해주냉면의 육수맛을 잊을 수가 없네요. 여전히 매운 마약같은 양념도 일품이에요., 번역: I can't forget the taste of the broth.Still spicy drugs are also a gem.

 92%|█████████▏| 20716/22421 [04:47<07:30,  3.78it/s]

원본: 와 쇼킹하게 매운맛입니다..근데 맛있네요 그리고 가격이 착해!!!서좋아요, 번역: Wow, it is spicy..But it's delicious and the price is good!!!I like it

 92%|█████████▏| 20717/22421 [04:47<07:19,  3.88it/s]

원본: 역시 그 명성에 뒤지지 않는 매운맛 맛있게 매워요 설탕조금 추가하면 대박이에요, 번역: After all, it's spicy and spicy.

 92%|█████████▏| 20718/22421 [04:47<07:01,  4.04it/s]

원본: 맛 안따지고 매운거 먹고싶은 사람은 비빔냉면 시키고 따로 테이블에 있는 양념장 추가해서 먹으면 되는데 엄청 매워서 맛 생각이 안남. 물냉 양념빼고 시켰는데 좀 별로여서 거의 다 먹어갈 때 양념장 약간 넣으니까 괜찮았어요., 번역: If you want to eat spicy and spicy, you can eat bibimb noodles and add seasoning sauce on the table.I made it out of water and seasoned, but it was a little bad, so when I eat it, it was okay because I put a little sauce.

 92%|█████████▏| 20719/22421 [04:47<07:13,  3.93it/s]

원본: 이 집 1대사정님이신 할머님 께서는 친절하고 유명하고 맛있었지만 2대로 넘어가면서 그 명성을 다 까먹고 불친절하고 맛도 없어졌습니다 맛을 떠나 믿도끝도없이 그냥 매운것만 맛보고 싶은 분만 가세요대신 서비스는 최악입니다, 번역: The grandmother, who is the first ambassador of this house, was kind, famous and delicious, but over two to two, forgot all the reputation, unkind and taste.

 92%|█████████▏| 20720/22421 [04:48<07:10,  3.95it/s]

원본: 주문하면 빨리 나오고 맛도 정말 좋았습니다!! 웨이팅은 없었는데 웨이팅이 있는 경우가 많다고 하네용, 번역: When I ordered it, it came out quickly and the taste was really good!!There was no weighting, but there are many ways to wait.

 92%|█████████▏| 20721/22421 [04:48<06:58,  4.06it/s]

원본: 무슨 맛인지 모르겠다. 맵기만 맵고... 매운 거 좋아하는 분들이 찾는 듯. 개인적으로는 다시는 안 갈 집., 번역: I don't know what it tastes like.It's spicy...It seems that people who like spicy are looking for.Personally, I can't go again.

 92%|█████████▏| 20722/22421 [04:48<06:58,  4.06it/s]

원본: 별하나도 아까운집. 너무 불친절해서 맛이 있어도 기분나쁠 마당에 맛까지 별로라 진짜 욕나왔어요. 냉면 팔기 싫으면 장사하지마세요 먹으러 온 사람까지 기분나쁘게 하지말고, 번역: One star is a waste.It was so unkind and it was so bad that it was bad in the yard.If you don't want to sell cold noodles, don't sell it. Don't feel bad even if you come to eat

 92%|█████████▏| 20723/22421 [04:49<09:07,  3.10it/s]

원본: 특제소스를 넣어먹어야 맛이남.굉장히 싸다.그냥 먹으면 쫌 맛이없음...., 번역: It tastes to have a special sauce.Very cheap.If you just eat it, it doesn't taste good....

 92%|█████████▏| 20725/22421 [04:49<07:04,  4.00it/s]

원본: 완전 매콤 달콤 맛잇어서 혼자서도 찾아가는집 육수랑 부어먹으면더맛나요, 번역: It's so spicy and sweet, so it's better to pour with the broth that you visit by yourself
원본: 매워도 너무 맵네요ㅎ 매운거 좋아하시면 좋아할듯 도전!, 번역: It's too spicy.

 92%|█████████▏| 20727/22421 [04:49<05:50,  4.83it/s]

원본: 매운음식 좋아하는분들 강추합니다, 번역: Spicy foods are recommended
원본: 저도 무슨맛인지 모르겠다는데에 공감ㅠㅠ 일반 냉면 생각하고 갔는데 뭔가 맛은 밋밋하고 엄청 매움!, 번역: I don't know what it tastes like.

 92%|█████████▏| 20729/22421 [04:50<05:21,  5.27it/s]

원본: 유명해서 가봤지만 딱히.. 그냥 냉면집가는게 더 나은것같기도, 번역: I've been famous, but it's just..It seems better to just go to cold noodles
원본: 제가 신천20년살았는데 맵기만하고 맛없는데 왜먹는지 이해안가는 유일한 식당, 번역: I lived for 20 years, but it's spicy and tasteless.

 92%|█████████▏| 20733/22421 [04:50<03:11,  8.81it/s]

원본: 중독성 있는 엄청난 매운 맛, 요즘 보기드문 불친절한 식당, 번역: Addictive spicy taste, rare unkind restaurant these days
원본: 오류동 팔칠닭강정 본점닭강정하면 여기다.. 진짜 이게 닭강정이다란 말이나올정도로 맛있음방문포장하면 할인해줘서 항상 미리연락해 방문 포장함식어도 맛있는데 좀 딱딱할수있음팔칠 이거 알고 속초닭강정 먹었는제 맛없더라 ㅡㅡ, 번역: This is here if you Gangjeong, the head of the Palchil Chicken Gangjeong Main Store..It's really good to say that it's chicken Gangjeong. If you visit the packaging package, you can always contact you in advance so that the visit packaging is delicious, but it can be hard.

 92%|█████████▏| 20735/22421 [04:50<03:44,  7.50it/s]

원본: 닭강정은 여지껏 맛이 없다고 생각했었는데 지인으로부터 알게되어 맛을본 순간 반하고 말았습니다.지방여행중에도 유명한 강정집 이라는 곳도 맛보았지만 이곳의 맛을 잊을수없어서 여생 갔다와서 사먹기도 했었습니다.매운음식은 저혀 먹지 못하지만 여기는 매운맛도 3가지가 있어서 나름 나에게 맞는 매운맛을 찾았습니다.매운맛 중에서도 중간매운맛을 주문하면 저처럼 매운것 못먹는 사람도 맛나게 먹을수 있어요~~~, 번역: I thought the chicken Gangjeong was not good, but when I learned from an acquaintance, I fell in love with it.I also tasted a famous Gangjeong house during my trip, but I couldn't forget the taste of this place.I can't eat spicy food, but there are three spicy flavors here, so I found the spicy taste that suits me.If you order a spicy taste in the spicy taste, even if you can't eat something like me, you can eat deliciously ~~~
원본: 가끔 혼맥하고 싶을 때 배달합니다. 바삭하고 맛있어요., 번역: Sometimes it is delivered when you want to mix.It's crispy and delicious.

 92%|█████████▏| 20737/22421 [04:51<03:58,  7.06it/s]

원본: 조용한 곳에 위치해 있고 평일 낮이라 그런지 사람 없이 조용하고 아주 좋았어요😊깔끔하고 찰떡와플은 빵이 아닌 떡이 와플 모양으로 나오는데 위에 아이스크림, 견과류, 꿀이 얹어져있어 달콤하고 아주 맛있었어요👍🏻운영시간은 오전 11시~ 저녁7시까지이고 일요일은 쉬는날! 카페치고 일찍 문을 닫아서 아쉽지만 시간내서 오기 좋은 카페 입니다., 번역: It is located in a quiet place and it was a weekday day, so it was quiet and very good without a person 😊 Neat and squat waffle is a waffle, not bread.Si ~ 7:00 pm and Sunday rest day!It's a pity that I closed the door early for a cafe, but it's a good cafe to come from time.
원본: 일하는곳 주변에 유명한카페가 있다길래 방문!!외관부터 너~무 이뻐요 앞에 물이 흐르고있는데 그 소리가 너무 좋습니다와플을 평범한 와플 생각했는데 떡을 와플모양으로 만들어낸거같아요 굉장히 쫄기하고 맛있습니다 커피들도 맛있었으나 양은 적었어요!!만족스럽습니다 재방문의사 있어용, 번역: There is a famous cafe around the place where you work.!From the exterior, you are so pretty. The water is flowing in front of you, but the sound is so good.!Satisfied, I am a doctor

 92%|█████████▏| 20739/22421 [04:51<04:20,  6.45it/s]

원본: 바비레드본점에 다녀왔습니다 강남역에 있구요 다른 지점과 비교할 때 확실히 감각있는 느낌으로 매장이 꾸며져 있어요 꽤 넓은 편으로 단체모임도 가능할 것 같습니다 ^^ 젊은 감각에 어울리는 레스토랑이에요 1) 서비스 : 직원분들이 친절한 편인데 일반 레스토랑과 다르게 주문서를 직접 작성해서 계산대에 직접 가서 선불로 결제해야 합니다 그래도 음식도 빨리 나오고 계속 살펴주시는 부분이 좋았어요 2) 가격대: 인당 1.5만원정도는 잡아야합니다 솔직히 가성비를 따진다면 조금 비싼 편이지만 그래도 맛있고 분위기가 좋아서 저는 마음에 들었어요 인근 강남역 음식점 물가도 만만치 않아서요 ㅎㅎ 3) 샐몬 샐러드 ★★★★ 생각보다 연어가 많이 들어있어서 놀랐습니다. 드레싱은 깔끔한 레몬 드레싱 느낌이구요 야채도 그렇고 양이 꽤 있어서 한끼 식사로도 괜찮아요 ^^ 다이어트 하시는 분들은 이거 하나만 시켜도 좋을거 같네요4) 레드크림파스타 : ★★★예전에는 진짜 감동하며 먹었던것 같은데 등갈비가 살짝 질겨진 느낌이라 아쉬워하며 먹었습니다 그래도 매콤한 크림소스가 특이해서 한번쯤은 꼭 먹어봐야하는 메뉴에요 고기도 많이 들어있어요5) 갈릭 밥스타 ★★★★★메뉴 중에 가장 맛있었습니다 와 미쳤어요!저는 리조또인줄 알았는데 그게 아니라 파스타에+밥이 들어있는 탄수화물이 폭발하는 메뉴더라고요 ㅋㅋㅋ 그런데 그게 엄청 맛있어요 튀긴 마늘 후레이크를 아낌없이 뿌려줘서 그런가 마늘 감칠맛 장난 아니구요 소스도 중독성 갑! 꼭 드세요 6) 블랑맥주 : 갈릭밥스타보다는 레드크림파스타랑 어울리는 느낌이에요 맥주가 아주 쭉쭉 들어가더라구요 맛있게 잘 먹었습니다 다음에도 또 재방문할게요!, 번역: I went to Bobby Red Headquarters in Gangnam Station. Compared to other branches, the store is definitely decorated with a sense of feeling. It is quite large.Unlike the restaurant, I have to write the order document directly and go to the cashier directly and pay for the prepaid.But I still liked it because it was delicious and the atmosphere was good.Dressing feels neat lemon dressing. It's also a lot of vegetables and a lot of sheep. It's okay for one meal.It feels tough, so I ate it, but the spicy cream sauce is unusual.I thought it was a risotto, but it was a menu that explodes carbohydrates with pasta+rice.Be sure to eat 6) Blanc beer: It feels like red cream pasta rather than Garlic Bob Star. The beer is very straight.
원본: 꽤 신선하게 맛있었고요. 파스타는 약간 라면맛? ㅎ 애들이 가기 좋은 컨셉인데.. 가격은 어른용? ㅎㅎ셀프로 주문하고 천천히 나옵니다.잘 즐기고 왔네용~, 번역: It was pretty fresh.Pasta tastes a bit?ㅎ It is a good concept for kids to go..Is the price for adults?ㅎㅎ Self order and come out slowly.I've enjoyed it well ~

 93%|█████████▎| 20741/22421 [04:51<04:34,  6.13it/s]

원본: 시끌시끌 사람들이 많다 무료주차는 모르겠음 앞에 주차 공간이 없음 아기 의자는 없음 맛은 있고 되게 생각보다 양이 많음, 번역: There are a lot of noisy people. I don't know free parking. There is no parking space in front. There is no baby chair.
원본: 친구들이랑 단체로 가서 하나씩 시켜먹어보기 좋아요. 맛도 독특한데 이상하지 않고 다 맛있네요 밥스타라는게 신기했어요 밥도 먹고 면도 먹고..갈비가 든것도 맛있고 신기했어요 괜찮은 퓨전 음식 하나 먹은 기분입니당., 번역: Go to your friends and groups and try one by one.The taste is unique, but it's not strange and it's all delicious..It was delicious and amazing to have ribs.

 93%|█████████▎| 20743/22421 [04:52<04:48,  5.81it/s]

원본: ✔️2인세트 (40,000원)파스타+샐러드+에이드✔️레드갈비스튜 (16,000원)-강남역의 오래된 맛집!블로그에 올리고 남은 사진들[빨간밥]이 [무한리필]정말 #바비레드 밥이 빨개요매콤한 소스들이 돋보이는 파스타와 스튜도만족스러웠습니다 크크크에이드도 맛있었는데사진을 빼먹었네요, 번역: ✔️ 2 Set (40,000 won) Pasta+Salad+Aid ✔️ Red Galvis Tue (16,000 won) Old restaurant in Gangnam Station!The remaining pictures of the blog [Red Rice] [Infinite Refill] Really #Barbie Red Bob is also a lot of spicy sauces and stews were also satisfied.
원본: 파스타 곱빼기의 양이 생각외로적음. 그리고 연어샐러드 야채도 별로없고, 블로그에보면 가성비갑이라고 하는데..내생각에는 밥과 김가루가 무제한이라 그런듯!, 번역: The amount of pasta multiplying is small.And there are not many salmon salad vegetables, and on the blog, it's called caustic..In my opinion, rice and seaweed are unlimited!

 93%|█████████▎| 20745/22421 [04:52<05:01,  5.56it/s]

원본: 데이트코스로 적당한 곳. 음식이 개성이 강하며 매우 맛있음밥이 무한리필이라 소스에 비벼먹으면 최고, 번역: Appropriate place as a date course.The food is very unique and very delicious rice is infinite refills, so if you mix it in the sauce, the best
원본: 후기 보고 갓는데 이렇게 맛없는데 유명한 이유를 모르겠어요고기도 싸구려닭에서도 냄새 너무 나서 못먹고 나왓어요비추~, 번역: I watched the reviews, but I don't know why it's so famous.

 93%|█████████▎| 20747/22421 [04:53<04:46,  5.84it/s]

원본: 가격이 저렴하거나 맛이 아주 특출나지는 않지만, 강남역 근처 특성상 이 근방에서는 제일 괜찮은 선택 중 하나라고 생각합니다. 밥스타가 제일 맛있고 밥 추가 가능합니다., 번역: Although the price is not cheap or the taste is very unusual, I think it is one of the best choices near this due to the nature of Gangnam Station.Bobstar is the most delicious and can be added.
원본: 레드크림파스타 진짜 대박임 이건 꼭 먹으러 감. 양도 많고 남은 소스에 밥도 비벼먹을수 있게 흰밥도 무제한임. 갈비스튜도 맛있음. 밥반찬같은 느낌. 연말에도 간적있는데 크리스마스 느낌 물씬 나고 분위기도 좋아서 데이트 식사로 제격임, 번역: Red Cream Pasta is really awesome.White rice is unlimited so that you can eat rice in the remaining sauce.Galvistu is also delicious.It feels like a side dish.I went to the end of the year, but it feels like Christmas and the atmosphere is good.

 93%|█████████▎| 20749/22421 [04:53<04:42,  5.93it/s]

원본: 바비레드는 말 그대로 적색을 띄고 있는 밥을 무료로 제공해줍니다. 갈비파스타랑 스튜를 주문했는데 국물에 밥을 비벼먹으면 그렇게 맛있을 수가..ㅠㅠ 갈비도 잘 익혀나와서 살살 녹아용 연어샐러드도 정말 맛있습니다!! 밥은 셀프로 떠와야합니당, 번역: Bobby Red literally offers free rice.I ordered Galbi pasta and stew, but it can be so delicious when I mix rice in the broth..ㅠㅠ ribs are also cooked well, so the salmon salad is really delicious!!The rice should be self -floating
원본: 분위기가 엄청좋았고 복층디자인에 하늘엔 별도떠있고 벽에 빔을설치해서 찰리채플린이 나오더라구요 인스타에올리기 딱좋았어요.. 맛도있고! 둘이가서 두개시키면 살짝 모자랄거같아요!, 번역: The atmosphere was very good, the multi -layered design was separate in the sky, and the beam was installed on the wall, and the Charlie Chae Fleen came out..It tastes!If you go and do two, I think it's a little short!

 93%|█████████▎| 20750/22421 [04:54<09:48,  2.84it/s]

원본: 컨셉 확실하고 널찍한 인테리어 좋습니다. 음식은 약간 아쉬워요.아무래도 양념이 강하게 되는 메뉴가 많다보니 소스맛, 양념맛으로 먹게 됩니다. 소고기 냄새가 약간 났고, 파스타는 면이 너무 삶아졌어요.일하시는 분들 활기차고 친절해요. 밥이랑 피클 같은 건 셀프입니다.좋은 분위기에서 무난하게 먹기엔 괜찮을 거 같습니다., 번역: The concept is good and spacious.The food is a bit unfortunate.Since there are many menus that are so seasoned, they are eaten with sauce and sauce.The smell of beef is a bit, and the pasta is so boiled.Those who work are lively and friendly.Bob and pickles are self.It would be okay to eat in a good atmosphere.

 93%|█████████▎| 20752/22421 [04:54<07:34,  3.67it/s]

원본: 들어있는 갈비가 참 맛있었어요!다만 간혹 조그마한 뼈가 씹혀서 이가 나가는줄..그것만 빼고 만족이용 ㅠㅠ, 번역: The ribs contained were so delicious!Sometimes a small bone is chewy..Except for that, satisfaction is used ㅠㅠ
원본: 그냥 매콤한 맛. 음식들이 일반 음식 맛에 매운 맛만 추가된 느낌입니다. 스테이크 샐러드에 스테이크는 질겼습니다., 번역: Just spicy taste.The food is added to the spicy taste of the general food.The steak is tough in the steak salad.

 93%|█████████▎| 20754/22421 [04:54<06:15,  4.44it/s]

원본: 맛 괜찮은 집! 가격대가 좀 있긴 한데 매콤한 파스타 땡길 때 가면 좋음ㅎㅎ, 번역: Tasteful house!There is a price range, but it's good to go when you have a spicy pasta
원본: 4인세트 시켜서 4명이서 배불리 먹었습니다. 파스타 안에 있는 고기가 양도 많았어요!, 번역: I ate 4 people and ate four people.There was a lot of meat inside the pasta!

 93%|█████████▎| 20756/22421 [04:55<05:20,  5.20it/s]

원본: 스테이크 질기고 밥은 그냥 그렇고 파스타는 맵기만하고 별로였어요, 번역: The steak is tough and the rice is just so hot and not good.
원본: 밥도 무한리필이고 너무 맛있었어요 망고쥬스는 양이 너무 적었어요, 번역: The rice was also infinite and so delicious. The mango juice was too small

 93%|█████████▎| 20758/22421 [04:55<04:57,  5.60it/s]

원본: 크림레드파스타 가장 덜 매운 정도로 선택했는데 적당히 매콤하면서 크림도 꾸덕해서 맛있었어요!, 번역: I chose cream red pasta as the least spicy, but it was moderately spicy and the cream was delicious!
원본: 비슷한 느낌의 식당은 많은데(서가앤쿡, 미즈컨테이너) 저는 바비레드가 제일 좋아요.매운 정도도 조절할 수 있고 가성비가 좋다고 생각합니다😊레드크림파스타에는 밥을 비벼 먹을 수 있는데 색다르고 좋았어요두명이서 3만원 정도 나왔었는데 많이 배부르지는 않지만 다른 곳보다 느끼함이 적었어요., 번역: There are many restaurants that feel similar (Seo Ga & Cook, Mizu Container) I have the best Barbie Red.I can adjust the spicy degree and I think the price is good 😊 Red Cream Pasta can be mixed with rice, but it was different and good.

 93%|█████████▎| 20760/22421 [04:55<04:52,  5.68it/s]

원본: 레드크림파스타는 크림소스에 매콤한 맛이 들어가있어 좋았어요 떡볶이 맛 같은 느낌이었어요 파스타를 만들 줄 알아서 그런지 가격대가 만족스럽지는 않네요 사람들도 많아서 시끌벅적해요 주문하고 기다릴 때 빨간 봉을 주는데 뭔가 클럽같기도..., 번역: Red cream pasta had a spicy taste in the cream sauce. It felt like tteokbokki taste...
원본: 생각보다 고기 양이 많아서 좋았음. 야채의 굽기 정도도 딱 알맞았음. 가격이 살짝 아쉬움. 한번 가봤다 정도..?, 번역: It was good because the amount of meat was more than I thought.The degree of grilling of vegetables was just right.The price is a bit disappointing.I've been there once..?

 93%|█████████▎| 20764/22421 [04:56<02:56,  9.37it/s]

원본: 전반적으로 맛있었고(음료도 맛있었다.) 가격도 무난했지만 바비레드 즉 밥을 남은 소스에 비벼먹는 컨셉인데 밥을 비벼먹을 때쯤엔 음식이 식어서 아쉬웠다. 온기를 유지할 수 있는 용기를 사용하면 좋았을 것 같다., 번역: Overall, it was delicious (the drink was delicious), but the price was good, but it was a concept of mixing it in the Barbie red sauce.It would have been nice to use the container to keep the warmth.
원본: 맛없음 너무 느끼하고 밥이랑 먹기좋다는데? 그냥 그랬음...샐러드가 가장 맛있음 샐러드는 진짜 맛있음, 번역: It feels so tasty that it's good to eat with rice?I just did it...The salad is the most delicious, the salad is really delicious

 93%|█████████▎| 20767/22421 [04:56<02:54,  9.47it/s]

원본: 연인끼리 데이트하기에 분위기좋고 이쁜곳!! 음식또한 맛이있고 가격또한 나쁘지않다, 번역: The atmosphere and pretty place to date lovers!!The food is also tasty and the price is not bad
원본: 생각보다 양이 적어보이지만 딱 기분좋게 배부름, 번역: It looks smaller than I thought, but it is just full

 93%|█████████▎| 20769/22421 [04:56<03:24,  8.06it/s]

원본: 좋아요, 번역: great
원본: 음식이 기대 보다는 가격대비 별로임. 맛 기대하지 않고 가야 만족할 듯., 번역: Food is not as good as expected.You must be satisfied with you without expectation.

 93%|█████████▎| 20771/22421 [04:58<09:11,  2.99it/s]

원본: 언젠간 다시 가보겠지.. 굳이 지금은 음..., 번역: I'll go back someday..Um now...
원본: 평범합니다. 그럭저럭, 번역: Ordinary.so so

 93%|█████████▎| 20776/22421 [04:58<03:47,  7.23it/s]

원본: 맛은 있으나 한사람이 먹기에는 양이 너무 많다., 번역: It tastes good, but it is too much for one person to eat.
원본: 직원이 계산해 주는게 아니라 셀프로 미리 결제를 해야  됩니다  쌀국수가 맛있고 푸짐 합니다, 번역: The staff should not be calculated, but you have to pay in advance. The rice noodles are delicious and rich.

 93%|█████████▎| 20778/22421 [04:58<03:56,  6.93it/s]

원본: 팟키마오’러는 해장용 쌀국수 대박입니다~~울렁이는 속을 확 잡아줘요~~ 단 좀 맵습니다.똠양쌀국수는 똠양꿍에 쌀국수를 넣었습니다.새콤달콤매콤...이 집의 유일한 문제는 점심특선 6,900원과 메인 쌀국수 10,800원의 가격차이~~~점심특선엔 좀 작은 양지쌀국수와 파인애플볶음밥이 나오는데~~ 가성비 갑이거든요 ㅋㅋ, 번역: Pod Kimao ”is a great rice noodle for haejang ~~ Ulong -gi will hold the inside ~~ It's a bit spicy.Shenyang Rice Noodles put rice noodles in Mongyang.Sweet and sour and mad...The only problem of this house is the price difference between 6,900 won for lunch and 10,800 won for main rice noodles ~~~ Lunch specials are a little small and pine apple fried rice.
원본: 맛있음 다음번엔 다른 메뉴도 먹어보고싶음 재방문 의사있어요~, 번역: It's delicious next time I want to try another menu. I have a doctor's doctor ~

 93%|█████████▎| 20781/22421 [04:59<04:07,  6.63it/s]

원본: 한국식 맛이지만 맜있다 양 이 매우많다 점심에가면 더 합리적인가격에 먹을수있다, 번역: It tastes like Korean, but there is a lot of amount.
원본: 똠양 맛이 덜해서 조금 아쉽네요. 무난하게 먹을만한 곳입니다., 번역: It's a little disappointing because it tastes less.It's a good place to eat.

 93%|█████████▎| 20782/22421 [04:59<05:18,  5.15it/s]

원본: 가산에서 먹을수있는 태국음식점~ 무쌉메뉴 맛있었당~~~, 번역: Thai restaurant that can be eaten in Gasan ~ It was delicious without a menu ~~~

 93%|█████████▎| 20783/22421 [04:59<05:30,  4.95it/s]

원본: 가산에서 6년 동안 회사 생활하면서 손에 꼽는 맛집임11시 50분에 가도 늘 사람이 많아서 줄을 서야함밥 종류보다는 쌀국수가 맛있음 특히 육수가 다른데랑은 다름, 번역: Even if you go to Gasan for 6 years, you can go to the restaurant at 11:50, so there are a lot of people.

 93%|█████████▎| 20784/22421 [05:00<05:47,  4.72it/s]

원본: 진짜 멍땅 맛잇음 다 맛잇음 꼭가보세요오, 번역: Really tasted delicious, please go.

 93%|█████████▎| 20786/22421 [05:00<05:07,  5.31it/s]

원본: 요즘 유행하는 낙곱새. 매운맛을 정할 수 있어 좋고 안에 낙지도 통통한 편이었어요.  반찬은 셀프., 번역: The trendy loving birds these days.It was good to have a spicy taste and the octopus was plump.The side dish is self.

 93%|█████████▎| 20787/22421 [05:00<05:23,  5.05it/s]

원본: 초여름에 가야 진정한 멋을 느낄 수 있는 곳.한여름에 가면 덥기도 덥고, 줄무늬 산모기한테 물어뜯김.닭백숙의 크기와 산 아래로 보이는 서울의 경관이 일품인 곳. 서울 한복판에서 계곡의 기분을 느끼고 싶다면 추천.참고로 닭도리탕은 고춧가루가 씹히며 맛도 고춧가루 맛이 강하게 남. 별로임. 김치랑 석박지 말고는 밑반찬이랄 것도 없지만 거기서 먹으면 맛남. 밥이 질어서 별로임.어쨋든 여긴 단점을 다 씹어먹고도 남을만한 백숙과 경관이 있음. 추천!, 번역: A place where you can feel true in early summer.In midsummer, it's hot and hot and bite from a striped parent.The size of the chicken and the scenery of Seoul, which appears below the mountain, is a gem.Recommended if you want to feel the valley in the middle of Seoul.For reference, chicken doritang is chewed with red pepper powder and the taste of red pepper powder is strong.Not not.It's not a side dish, but it's a good side dish.The rice is not good.Anyway, there are Baeksuk and scenery that can be left after chewing the disadvantages.suggestion!

 93%|█████████▎| 20788/22421 [05:00<05:34,  4.88it/s]

원본: 차돌 부채살 곱창 대창 막창 같이 나오는 세트가 괜찮았습니다.다만 원래 염통까지 세트인데 염통이 품절이어서 다른 고기를 더 받았습니다.양은 아주 많진 않으나 가격 생각하면 적당합니다. 쫄면이랑 볶음밥도 아주 맛있습니다., 번역: The set that came out like a marbled giblet giblet phase was fine.However, it was originally a set of salt, but it was sold out and received more meat.The amount is not very large, but it is appropriate to think about the price.The noodles and fried rice are also very delicious.

 93%|█████████▎| 20789/22421 [05:01<05:48,  4.68it/s]

원본: 차돌이 먹고 싶어 들어갔다가차돌 곱창세트도 맛있어보여서 차돌곱창세트를 시켰어요어무래도 차돌만 시킨게 아니다보니 차돌이 엄청 조금 나와 아쉬웠고 맛은 전반적으로 만족스러웠어요그래서 추가로 차돌된장찌개를 시켰고 공기밥 하나 같이 나왔고 차돌된장찌개 역시 맛있었지만 차돌은 2-3개밖에 안들어 있어서 아쉬웠어요차돌이 먹고싶다면 꼭 차돌 단품으로 시키길 추천합니다~손님이 많아서 매장 내부는 좀 정신없고 볶음밥은 직접 볶아 먹어야해요~~~맛은 있었어요~~, 번역: I wanted to eat the marbled giblet set, so I made the marble giblet set, so I made the margin of the car.It was delicious, but there were only 2 chadols, so it was a pity.

 93%|█████████▎| 20790/22421 [05:02<11:30,  2.36it/s]

원본: 저렴한 가격에 푸짐하게 차돌박이을 맛볼 수 있다. 초밥으로 먹으면 맛있고 제공되는 소스가 뭔가 독특한데 맛있음. 사이드메뉴도 다양함. 야끼니꾸꽃살도 먹었는데 차돌이 더 맛있는 듯, 번역: You can taste marbled at a reasonable price.If you eat it with sushi, the sauce provided is something unique.There are also a variety of side menus.I also ate yakiniku flowers, but the marble looks more delicious

 93%|█████████▎| 20791/22421 [05:02<10:14,  2.65it/s]

원본: 노원역2번출구 문화의거리에 있구요체인점이라 전체적으로 무난합니다일단은 가격이 가성비가 좋아서부담없이 많이 먹을수 있어서 좋습니다, 번역: Nowon Station is located in the street of exit 2, so it's good because it's good.

 93%|█████████▎| 20792/22421 [05:02<09:16,  2.93it/s]

원본: 저렴한 가격에 점심식사로 차돌박이를 맛볼 수 있음.  쫄면정식보다는 된장과 밥이 나오는 차돌 정식 추천, 번역: You can taste marbled at a low price.Recommended for tea stone with miso and rice rather than noodles

 93%|█████████▎| 20793/22421 [05:02<09:20,  2.91it/s]

원본: 점심 정식에 된장찌개와 돌초밥이 포함되어 가성비좋고 든든해요!, 번역: The lunch is included in the lunch meal, which is good for money.

 93%|█████████▎| 20794/22421 [05:03<08:25,  3.22it/s]

원본: 음 우순 차돌은 그냥 딱 그 가격맛이다. 야끼니꾸? 이건 진짜 먹지말자.. 노맛, 번역: Well, right -handed margin is just that price.Yakiniku?Don't really eat this..Nobility

 93%|█████████▎| 20795/22421 [05:03<08:00,  3.39it/s]

원본: 전에 갔을 때는 그런 느낌 못 받았는데 야외테이블 갔는데 가스 버너 쪽에 음식물 떨어져있고 가스통 밑에 청결상태 엉망... 밥맛 떨어짐..., 번역: I didn't feel that when I went before, but I went to the outdoor table...Taste of rice...

 93%|█████████▎| 20797/22421 [05:03<05:45,  4.71it/s]

원본: 맵기 선택도 가능하고 토핑도 원하는대로 추가할 수 있어서 좋아요!!, 번역: You can choose a spicy machine and add toppings as you want!!

 93%|█████████▎| 20798/22421 [05:03<05:53,  4.59it/s]

원본: 점심으로 먹기 좋아요!ㅎㅎ 데코가 예쁘게 되어있어서 먹기도 괜찮아요 ^^*, 번역: Good for lunch!ㅎㅎ Deko is pretty, so it's okay to eat

 93%|█████████▎| 20799/22421 [05:04<06:06,  4.43it/s]

원본: 가게가 아담하고 조용해서 좋았어요가격대도 적당하고 양도 많아서 좋았습니당, 번역: The shop was small and quiet.

 93%|█████████▎| 20801/22421 [05:04<04:50,  5.58it/s]

원본: 가족끼리 외식하기에 좋아요. 등급이 높은 고기는 아니지만 푸짐하고 맛있습니다. 10명 이상일 땐 룸 예약해서 가는게 좋아요. 룸도 조용하진 않지만 홀보다는 덜 시끄러워요ㅎㅎ, 번역: It's great for eating out with your family.It is not a high level of meat, but it is rich and delicious.If you have more than 10 people, you should book a room.The room is not quiet, but it is less noisy than the hall haha

 93%|█████████▎| 20802/22421 [05:04<05:10,  5.22it/s]

원본: 고기 량도 괜찮게 있고 고기 품질도 꽤 괜찮아요 그래서 더 맛있네요., 번역: The meat is good and the meat quality is pretty good.

 93%|█████████▎| 20803/22421 [05:04<05:21,  5.03it/s]

원본: 가디에서 분위기 좋은 맛집이에요 1-3층까지 있고 옥층에는 루프탑이라 분위기 좋아요평일에도 항상 사람많아요!, 번역: It's a good restaurant in the cardi, and it's a 3rd floor and a rooftop on the jade floor.

 93%|█████████▎| 20804/22421 [05:05<05:38,  4.77it/s]

원본: 가산디지털단지역 근처 숨은 술집~! 인테리어 갬성있게 잘해 놓고 메뉴도 어지간하면 다 맛 괜츈~~!! 추천~~!!, 번역: Hidden bar near Gasan Digital Complex ~!If you do well with the interior and the menu is quite good ~~!!Recommended ~~!!

 93%|█████████▎| 20805/22421 [05:05<05:56,  4.53it/s]

원본: 닭갈비가 제일 유명한거같라요! 다른 메뉴들도 많지만 정말 가성비 좋음ㅋㅋㅋ 그리고 뭔가 갬성있는듯한 인테리어예요! 술마시러가기 딱 좋은집!, 번역: I think the chicken ribs are the most famous!There are a lot of other menus, but it's really good.A good house to go to drink!

 93%|█████████▎| 20807/22421 [05:05<05:25,  4.95it/s]

원본: 사람들 엄청 많음 대부분 술 여기서 마시는 듯 삼층에 루프탑있음, 번역: Most people have a loop top in the three floors as if they were drinking here.
원본: 상수동 골목안 가정집 음식점 오늘먹은 터키풍함박스테이크와달걀볶음밥 한마디로 앗!!맛있다 가성비굿이다 고체연료 버너가 접시맡에 있어 먹는 내내 따습게 먹을 수 있다 맛집이다 다시 가봐야겠다, 번역: A restaurant restaurant in Sangsu -dong Alley Today Turkish style Park steak and egg fried rice!!It's delicious. It's good. It's a solid fuel burner. You can eat it all the time.

 93%|█████████▎| 20808/22421 [05:06<10:08,  2.65it/s]

원본: - 반지하 가정주택을 개조한 곳에 위치한 식당. 뷰가 구리고, 좁고, 환기가 안되는 단점이 있습니다.- 절대 4인이상 가지 마세요! 좁아요..- 윤씨 함박 스테이크 정식 : 패티로 써도 괜찮을 것 같은 함박. 느끼하지 않고 담백하며 같이 나오는 양송이와 조합이 좋습니다. 다만 밥에 쓸때없이 참기름이 들어가서 분위기를 깨버림. 😥- 터키풍 함박 & 계란볶음밥 : 일반 정식과 다르게 볶음밥이 나오는데 이게 차라리 낫습니다. 일반도 계란볶음밥 주면 좋겠습니다. 특이하게 온열기구(?)가 같이 나옵니다. 그런데 함박 고기가 일반 정식보다 조금 떨어지는 느낌을 받았습니다., 번역: A restaurant located in a renovated house under the ring.There is a disadvantage that the view is narrow, narrow, and cannot be ventilated.Never go over 4 people!It's narrow..Yoon Ham Bak Steak Equation: Hambak seems to be okay to use it as a patty.It is a good combination with the mushrooms that come together without feeling.However, sesame oil enters without using it, breaks the mood.😥 Turkey -style Hambak & egg fried rice: Unlike regular meals, fried rice comes out, which is better.I would like to give the egg fried rice.Unusually, the heat mechanism (?)However, the seaweed meat felt a little lower than the regular meal.

 93%|█████████▎| 20809/22421 [05:07<12:59,  2.07it/s]

원본: 간판이 없어 찾는데 좀 헤맸습니다. 지하1층에 위치해있습니다.가격이 비싸지않고 양이 푸짐해서 배부르게 먹었습니다. 식기 및 깍뚜기는 셀프입니다.음식은 대체로 맛있었는데 반찬으로 나온 떡볶이는 정말 맛이 없었어요. 차라리 피클을 제공하시는게 좋을듯해요., 번역: There was no signboard, so I was looking for it.Located on the first basement.The price was not expensive and the amount was large and I ate it.Dishes and diced are self.The food was usually delicious, but Tteokbokki, which came out as a side dish, was not really good.I'd rather provide a pickle.

 93%|█████████▎| 20811/22421 [05:07<10:07,  2.65it/s]

원본: 넷이가서 세개시켰는데 남겼다 생각보다 양이 엄청많음..!터키식 함박스테이크 존맛나중에 계란볶음밥 다 먹고나서 김치볶음밥 남은 것도 넣어서 먹었는데 이게 제일 맛있닼ㅋㅋㅋㅋㅋ역시 맛은 찾아가는거야..!투움바 파스타도 꾸덕꾸덕하고 맛있었고, 김치볶음밥은 그냥 볶음밥~ 전체적으로 만족스러운 식사였다.역시 가성비최고인 윤씨밀방다섯이가서 터키풍함박과 존슨탕, 섬마을파스타, 김치볶음밥을 주문했다 아주 배부르게 먹고 옴!개인적으로 터키풍함박스테이크를 가장 선호하는데 넉넉히 나오는 국물이 너무 맛있다 함박도 촉촉하고 밑에 불을 켜두기때문에 따뜻함도 유지됨! 로제보다 살짝 토마토비율이 높은듯한 소스는 밥을 비벼먹기에 정말 좋고 함께 나오는 샐러드도 아주 잘 어울린다 윤씨밀방 갈때마다 주문하는 고정메뉴존슨탕은 저번에 먹었을 때 괜찮았던 기억이 있어서 또 시켜봤다 간단하게 표현하자면 크림소스를 넣은 부대찌개같은 느낌이다 안에 우동사리와 함께 함박,소세지,양파,김치 등 여러가지가 들어있는데 크림맛이 슬쩍슬쩍 느껴짐 하지만 그래서 살짝 애매한 점도 없지않아있다 탕이어서 아주 묽고 그 묽음이 함박과 잘 어울리지 않는다 우동이나 소세지 등 다른것과는 그럭저럭 괜찮지만 함박이 아쉬움!우마이 섬마을 파스타는 새우가 들어간 로제파스타인데 요 소스가 올리브빵이랑 잘 어울린다 새우는 부족하지않을만큼 들어있는듯하고 면이나 다른건 뭐 그냥 쏘쏘함! 일단 소스가 맛있어서 다 괜찮은 느낌이다 새우덕분인지 해물향이 은은하게 느껴지는 편.김치볶음밥은 항상 말하지만 그냥 그렇다 밥메뉴를 하나 시키고싶어서 매번 시키지만 언제나 쏘쏘한 메뉴. 알고 시키는거라 뭐 괜찮음~소스가 맛있는 집이라 뭘 먹어도 맛있는 편인데 이 모든건 기다리지 않고 먹었을 때를 전제로한다 긴긴줄 끝에 이 음식들을 접하면 화남. 줄 안서고 친구들이랑 저렴하게 양식먹고싶을 때 딱인 곳이다, 번역: The four went and made three, but there are a lot more than I thought..!Turkish Hambak Steak Zone Taste After I ate fried eggs, I ate kimchi fried rice. This is the most delicious..!Touuma Pasta was also smoked and delicious, and kimchi fried rice was just fried rice.After all, the best price of money, Yun Seedbang, and ordered Turkish bak, Johnson -tang, island village pasta, and kimchi fried rice.Personally, I prefer Turkish style Park steak, but the broth that comes out is so delicious.The sauce with a slightly higher tomato ratio than Rose is really good for mixing rice, and the salad that comes out together is very good.It feels like a bodhisattva stew with a cream sauce. There are various things such as udon sari, sausages, onions, kimchi, etc.It doesn't suit you.Umai Island Village Pasta is a Rose pasta with shrimp. The sauce goes well with olive bread.Once the sauce is delicious, it feels good.Kimchi fried rice is always said, but I just want to have a rice menu, but I always shoot it.It's okay to know and let me know ~ It's a delicious house, so it's delicious.It is perfect when you don't line up and want to eat food cheaply with your friends
원본: 유명한 집이라 길게 넣을 필요는 없을듯. 소스가 맛있어서 빵 리필해서 찍어 먹었음. 다만 같이나온 떡볶이는 그저 그랬음. 밑반찬이 깍두기 하나라 피클 같은게 있었으면 좋을듯 싶음., 번역: It's a famous house, so you don't have to put it in.The sauce was delicious, so I refilled bread and dipped it.But the tteokbokki that came out was just like that.I hope there is a side dish like a pickle.

 93%|█████████▎| 20813/22421 [05:08<07:08,  3.76it/s]

원본: 먹어봤던 함박스테이크 집 중에 가성비와 맛을 둘 다 가진 집 중 하나임 홍대 들리신다면 꼭 먹어보시길 왕추천함 양도 매우 푸짐하며 맛도 매우 맛있음 존슨탕 국물 맛으로 보아 이 집은 스파게티도 매우 잘할 것으로 추정됨 웨이팅은 항상 많은 편이니 참고하고 가시길 추천드림 핵존맛탱구리, 번역: If you hear Hongdae one of the houses that have both price and flavor, you can eat it.It is always a lot of us, so please refer to the recommended Dream Nuclear Taste Tasting
원본: 가격도 저렴하고 너무 맛있어요 줄서는 맛집입니다 2호점은 줄 덜 서요~, 번역: The price is also cheap and it's so delicious. The row is a restaurant.

 93%|█████████▎| 20815/22421 [05:08<05:48,  4.61it/s]

원본: #상수동#윤씨밀방 #함박스테이크정식 #상수동맛집 학생때라면 좋은곳이다, 생각할수도 있었겠지만...글세..한여름에는 가기 어려운곳, 날씨가 그렇게 더웠는데 현장예약 해야하고 ,식당앞에 줄을서서 자리가 나는데로 들어갈수 있는 방식인데...사람들이 길게 줄을선 곳에 에어콘 실외기가 있다. 같이 갔던 지인은 식당에 들어갈땐 이미 더위에 지친상태, 식사후 몸이 않좋다며 쉴곳을 찾을 정도..같이 갔던 지인들은 음식은 나쁘지 않다고 했지만, 실상 함박스테이크는 어지간해서는 맛없기 힘들다. 백종원에 3대천왕이 무슨 맛집 검증시스템 처럼..알려진 지금, 백3천이라도 무조건 신뢰하긴 힘들듯., 번역: #Susu -dong #Yoon Seamil Room #Hambak Steak Squadron..Writing..It's hard to go in midsummer, the weather was so hot, but I have to make a reservation on -site, and I can get in line in front of the restaurant...There is an air conditioner outdoor unit where people line up long.The acquaintance who went with me was already tired of the heat when I entered the restaurant, and I was looking for a place to rest because I was bad after meals..The acquaintances who went together said that the food was not bad, but in fact, the steak was quite difficult.Like a restaurant verification system in Baekjongwon..Now is known, it seems hard to trust even a hundred and three thousand.
원본: 평일오후 7시에 갔는데 웨이팅이 3-4팀정도있었어요! 맛은 그렇게 맛있진 않았는데 평타는 하는것같아요. 내부는 좀 좁고 조용하진 않았어요. 엄청 기대하고갔지만 그정도는 아니였어요ㅠㅠ 양은 꽤 많았고 가격은 9000-10000원대라 가성비도 보통인것같습니당, 번역: I went to 7:00 pm on weekdays and there were about 3 teams!The taste wasn't so delicious, but I think it's a flat hit.The interior was a bit narrow and quiet.I expected it with a lot of expectations, but it wasn't that much.

 93%|█████████▎| 20817/22421 [05:08<05:02,  5.31it/s]

원본: 양이 더 많아진 것 같네요 그런데 왜이리 짠건지 ㅜㅜ 물까지 먹어서 더 배부른 느낌. 몇년째 애정하는 맛집이지만 요즘은 나이가 들어서인지 간이 쎄다고 느껴지네요, 번역: I think there's a lot more.It's a loving restaurant for a few years, but nowadays, I feel like I'm old.
원본: 친구따라 홍대와서 추천받은 함박맛집... 제 인생 함박에 등극했습니다. 양도 푸짐하고 먹고 있으면서도 밑에서 보글보글 끓고있는 소스가 너무 신기하고 맛있기더라구요. 제가 갈 때 마다 기본 대기 30분이었는데 요즘은 바로 들어간다던데... 진짜인가요? 아 코로나만 아니어도 가는데 ㅠㅠㅠ, 번역: Hambak restaurant recommended by Hongdae with a friend...I was in my life.The amount is so rich and eaten, but the sauce boiling from the bottom is so amazing and delicious.Every time I went, it was 30 minutes of basic waiting, but nowadays I go right now...Is it real?Oh, it's not just corona.

 93%|█████████▎| 20819/22421 [05:09<04:43,  5.65it/s]

원본: 꽤 오래된 맛집임에도 여전히 웨이팅이 많다.가성비 양이 많고 맛있다. 다양한 메뉴, 번역: Even though it is a pretty old restaurant, there is still a lot of weight.The amount of price is high and delicious.Various menus
원본: 함박존슨탕은 생각보다 매콤합니다일행중에 느끼한게 싫은분이라면 추천해요칼칼한느낌기본 함박스테이크정식도 소스가 많이느끼하지않고 양도 많고 맛있었어요다만 주방앞쪽에 앉았는데가스냄새같은게느껴져서 살짝 머리가 아팠네요, 번역: Hambak Johnsontang is more spicy than I thought. If you don't like it, I recommend it.

 93%|█████████▎| 20821/22421 [05:09<05:29,  4.86it/s]

원본: 후기가 좋아서 완전 기대하고 갔는데 기대 이하였어요웨이팅 심하다는 후기보고 오픈시간 15분 전에 도착했는데 아무도 안와서 11시에 바로 들어갔습니다일단 웨이팅하는데 너무 좁고 덥고 벌레도 많아요ㅠㅠ함박스테이크 먹었는데 그냥 일반 함박스테이크 집이랑 맛은 비슷하고 오히려 빵이 더 맛있어요ㅎㅎ 식전 나오는 떡볶이두요 ㅋㅋ 리필해서 드세요반찬 수저는 셀프고 20분도 안되서 차리 꽉차고 나갈땐 다섯팀 웨이팅 하더라구요 더우니까 오려면 일찍와서 드세요!, 번역: I was very excited because I liked the reviews, but it was less than expected.It's similar and the bread is more delicious.
원본: 머쉬룸투움바파스타랑 터키풍함박스테이크와계란볶음밥 시켰는데 넘 맛나서 이래서 웨이팅 하는구나! 싶었다 ㅎㅎ 특히 터키풍함박스티이크는 토마토크림소스랑 반숙, 갈릭드링샐러드 조합이 굿이었고, 머쉬룸투움바는매콤하고 고소한 소스에 버섯도 꽤 많아서 올리브빵 찍어먹으면 대박 ㅠㅠ 전체적으로 양도 많아서 배불리 잘 먹음ㅋㅋㅋ 오전 11시30분쯤 갔는데도 웨이팅 15분 했고, 재방문의사는 100프로!! 존슨탕도 먹어보고싶당, 번역: Mushroom Toum Baffa Star and Turkish Steak and Egg Fried Rice.In particular, the Turkish -style box teak was a good combination of tomato cream sauce, half -boiled and garlic drinking salad.Even though I went around 11:30, we were 15 minutes for the waiting, and the doctor was 100 %!!I want to try Johnsontang

 93%|█████████▎| 20823/22421 [05:10<05:13,  5.10it/s]

원본: 좋아하는 사람과 따뜻한 한끼를 먹기에 정말 좋은 곳이예요ㅎㅎ 내부가 좁지만 이야기 나누기 어려울 정도로 소리가 울리지 않고 평화롭게 정다운 이야기를 하며 식사하기 좋은 곳입니다 : ) 빵이랑 떡볶이도 리필이 됩니다❣️완전 추천이예요 ㅎㅎㅎ : )) 제가 먹은 메뉴는 함박 정식이랑 우마이 섬마을 파스타 입니다! 둘다 너무 맛있었어요 ㅎㅎ!!, 번역: It's a great place to eat a warm meal with a favorite person ㅎㅎ The inside is narrow, but it's hard to talk about it.:)) The menu I ate is Hambak meal and Umai Island Pasta!Both were so delicious haha!!
원본: 대기가 조금 있어서 기다렸지만 가성비 좋고 독특한 함박 스테이크가 기다릴 만했어요 생각나는 맛입니다, 번역: I waited a little while, but the price was good and the unique hamburger steak was waiting.

 93%|█████████▎| 20825/22421 [05:10<04:44,  5.61it/s]

원본: 자주가는 윤씨밀방그 추억때문인지 맛때문인지항상 다시 가게 된다2호점이 없어져 슬프다날치알파스타는 늘 맛있고터키풍함박 메뉴는 처음먹었는데 역시나 맛있더라, 번역: I always go back to the second place because of the memories of Yun Si Mill Bangga.
원본: 역시 음식은 기본이 제일 맛있는것 같네요~~파스타는 기대 안햇는데 엄청 맛잇게 잘 먹엇고 함박스테이크도 맛있엇어요~ㅎㅎ 둘이가서 세개나 먹고 왓슴니닷, 번역: After all, the food is the most delicious ~ ~ I didn't expect the pasta, but I ate it very well and the hamburger steak was delicious ~ ㅎㅎ

 93%|█████████▎| 20827/22421 [05:10<04:37,  5.74it/s]

원본: 저 메뉴판 사진 가격에서 천원정도 오른거 같으니 참고하세요! 여기 정말 맛있습니다. 대학교 1학년일때가 생각이 나네요 ㅎㅎ 돈없는 대학생커플들 여기서 데이트 하시면 좋을거에요! 가격이 전보단 올랐어도 아직도 양대비 저렴하고 분위기도 너무 좋아요 ㅎㅎ 또 가고싶네요, 번역: Please note that it has risen about 1,000 won from that menu photo price!It's really delicious here.I think I was a freshman in college.Even though the price has risen than before, I still want to go again.
원본: 4시 조금 넘어 갔는데 웨이팅 40분정도 한것같아요. 머쉬룸투움바랑 터키풍함박스테이크먹었는데스테이크는 딱히 특별한 맛은 없고 토마토맛 소스랑 샐러드가 맛있었어요. 파스타는 투움바파스타를 좋아하는편이라 기대했는데 아웃백투움바랑은 맛이 많이 달라요. 제 입맛에는 약간 땅콩버터맛이 났는데 그래도 맛있었습니다. 양이 많지는 않은것 같지만 그래도 먹다보니 적당히 배불렀어요.떡볶이랑 빵도 맛있구요전체적으로 싼 가격에 맛도 맛있어서 괜찮지만 줄이 너무 길어서 먹기가 힘들어서 또 올것같진 않아요., 번역: It's been a little over 4 o'clock, but I think it's about 40 minutes for weighting.I ate the Mushroom Tuum Bar and Turkish Bak Steak, but the steak didn't taste special and the tomato flavored sauce and salad were delicious.Pasta was expected to like to -view Baffa Star, but the outback toum Barang tastes very different.My taste tasted a bit butter, but it was delicious.I don't think it's a lot, but I still eat it.Tteokbokki and bread are delicious.

 93%|█████████▎| 20829/22421 [05:11<06:51,  3.87it/s]

원본: 웨이팅이 길고 줄이 빨리 빠지는 것도 아니라서, 약간 애매한 시간대에 가시는 것을 추천합니다. 그리고 음식은 터키식 함박이 정말 맛있어요..♡ 터키식 함박입니다 여러분 터키식 함박., 번역: The waiting is not long and the line is not fast, so I recommend going to go to a little ambiguous time.And the food is really delicious..♡ It's Turkish Hambak.
원본: 무슨 존슨함바그? 같은걸 시켰는데 배부른 양에 밥도 주고 매콤하니 맛있었다. 대기를 1시간 40분한 점이 아쉽지만 유명한 곳이니 그러려니 했다.직원들은 대체로 친절하고 식당 내부 분위기는 조용해서 식사에 방해되는 점이 없었다., 번역: What Johnson Hambag?It was the same, but it was delicious because it was spicy and spicy.It's a pity that the atmosphere was 1 hour and 40 minutes, but it was a famous place.Employees were generally kind and the interior of the restaurant was quiet, so there was no interference with the meal.

 93%|█████████▎| 20831/22421 [05:11<05:48,  4.56it/s]

원본: 가성비 좋은 맛집 음식 전반적으로 맛이 좋고 푸짐함 특히 빵이 아주 맛있음! 기다려야 하는 단점 있지만 만족함!, 번역: Good food restaurant foods are all delicious and the bread is especially delicious!There is a disadvantage to wait but satisfied!
원본: 떡볶이가 오늘은 좀 딱딱했다 원래 이렇게 매웠나? 오랜만에 왔는데 전체적으로 간이 세진 듯, 번역: Tteokbokki is a bit hard today.It's been a while, but as a whole

 93%|█████████▎| 20833/22421 [05:12<05:10,  5.12it/s]

원본: 외식 별로 안 좋아하는데 맛있었어요~~함박스테이크에 로제소스 뜨끈하니 맛있어요.존슨탕은 쪼금 매워요, 번역: I don't like food, but it was delicious ~~ It's delicious because it's hot and hot.Johnsontang is spicy
원본: 가성비좋았고 양이많아서 만족스러웠다 전반적으로 소스가 맛있어서 모든음식들이 맛있었다, 번역: It was good and was satisfied with the good price. Overall, the sauce was delicious, so all the foods were delicious.

 93%|█████████▎| 20835/22421 [05:13<08:44,  3.02it/s]

원본: 주문했던 투움바 파스타가 기대이상으로 맛이 괜찮았음. 적절히 매콤해서 느끼할 것 같았던 비쥬얼을 상쇄시켜줌. 꾸덕한 느낌의 식감도 만족스러웠음. 다만 가게가 생각보다 좌석이 많지 않고, 웨이팅이 생기기 시작하면 오래 기다려야하는 점이 약간의 단점., 번역: The Tuum Bar Pasta I ordered was better than expected.It offssets the visuals that seemed to be appropriately spicy.The texture of the feeling was also satisfactory.However, the store does not have more seats than you think, and if we start to develop, you have to wait for a long time.
원본: 홍대 맛집 답게 웨이팅이 많았지만 맛있었다. 기본으로 나오는 떡볶이도 맛있었고 존슨탕이 맛있다는데 다음번에 먹어봐야겠다, 번역: As a Hongdae restaurant, there was a lot of weight, but it was delicious.The basic Tteokbokki was also delicious and Johnson -tang is delicious.

 93%|█████████▎| 20837/22421 [05:13<06:27,  4.09it/s]

원본: 구석에 있는데도 불구하고 최소 20분 최대 2시간이상은 기다리는 맛집가성비가 좋아서 자주 방문하지만 이 맛을 위해 홍대까지 와야한다 정도는 아니다.수저 단무지 김치 셀프, 번역: Despite being in the corner, the gourmet rains are waiting for at least 20 minutes for more than 2 hours, so they often visit Hongdae for this taste.Spoon Rush Kimchi Self
원본: 볼케이노덮밥은 살짝 호불호 갈릴 맛이고 터키풍은 진짜 맛있오요 ㅎㅎ  웨이팅 진짜 깁니당 ;;;;, 번역: Ballcano rice bowl is slightly unfavorable and Turkish is really delicious ㅎㅎ Waying Really Gibidang ;;;;

 93%|█████████▎| 20839/22421 [05:13<05:28,  4.82it/s]

원본: 작은 식당이라 웨이팅 줄이 항상 너무 길다. 한번은 포기했고 한번은 엄청 기다려서 들어갔는데 또 주문한 음식 나올 때까지 시간 꽤나 소요됨. 천장이 낮고 전체적으로 좁은느낌이 들어 좀 답답했으나 홍대 상가 특성이니 그러려니 함.. 근데 맛이 뭐 그렇게 소문날정도로 특별함이 있지 않고 즈엉말 무난한 맛이라 좀 실망했음.. 가격이 저렴한편이고 메뉴가 밥과 함께 적당히 따뜻하고 너무 무겁지않게 한 끼 할 수 있는 메뉴라 홍대생들이 찾아 소문난 것 같은데 그 긴 줄을 서서 먹을 만한 맛은 전혀 아니라 허망함. 홍대 맛집으로 소문난 곳들 대부분이 허풍. 홍대생 피셜 "사람만 많고 다 작아서 줄 서는 거", 번역: It's a small restaurant, so the waiting line is always too long.I gave up once and I waited a lot once, but it takes quite a while until I ordered the food.The ceiling was low and the overall feeling was a bit frustrating, but it was the characteristic of Hongdae shopping mall..But the taste was so rumored that it was a little disappointed because it was a good taste..The price is cheap and the menu is a moderately warm and too heavy menu with rice.Most of the places rumored as a Hongdae restaurant are bluff.Hongdae Student Physical.There are only a lot of people and small.
원본: - 매장이 협소하고 덥습니다- 은근 양이 많아요 배불러요- 반지하라 찾기 살짝 어려웠어요, 번역: The store is narrow and hot. It's a lot of silver. I'm full.

 93%|█████████▎| 20841/22421 [05:14<04:46,  5.51it/s]

원본: 함박스테이크는 정말 맛있었는데..저만 그랬을지는 모르지만 섬마을 파스타에서 약간 비린내가 났습니다. 물론 심하지 않아서 잘 먹었지만 재방문한다면 함박스테이크만 먹으러 올 것 같네요. 점심에 웨이팅 20분 정도 했으니까 참고하시길 바랍니다~, 번역: Hambak steak was really delicious..I might have been, but it's a bit fishy in the island village pasta.Of course, it wasn't bad, so I ate it well, but if you visit, I think it's going to come to eat only hamburger steaks.Please note that we did 20 minutes for lunch.
원본: 처음이랑 두번째까는 맛도 좋고 괜찮았는데 그 후부터는 파스타 면도 다 붙어서 제대로 조리가 안되서 나오더라구요. 그리고 대기할 정도로 맛있는지도 모르겠습니다. 투움바파스타와 끓여먹는 함박스테이크 먹었는데 샐러드소스가 맛있어요., 번역: The first and second one tasted good and fine, but after that, it was not cooked properly because it was attached to the pasta.And I don't know if it's delicious enough to wait.I ate Suum Baffa Star and boiled steak, but the salad sauce is delicious.

 93%|█████████▎| 20843/22421 [05:14<04:28,  5.87it/s]

원본: 홍대 다니면서 이름은 옛날부터 들었지만 최근에야 가봤다. 대표 메뉴인 함박스테이크를 먹었는데 함박스테이크 맛은 평범하고 다른 메뉴들이 조금 생소한 느낌이었다. 다만 그 줄을 서서 먹을 정도는 아닌걸로, 번역: I have been listening to Hongdae and have been heard recently, but I've been to recently.I ate a representative menu, Hambak Steak, but the taste of the hamburger steak was plain and the other menus were a bit unfamiliar.But it's not enough to stand in line
원본: 맛있었어요! 데이트하기에 너무 좋았던 곳이고 양도 푸짐했어용, 번역: It was delicious!It was so good to date and the amount was rich.

 93%|█████████▎| 20845/22421 [05:14<04:25,  5.93it/s]

원본: 친구가 유명한 곳이라고 해서 가봤는데 남여노소 연령 상관없이 다들 줄서서 기다리고 있더라고요!! 근데 정말 맛있고 양도 엄청 많이서 놀랐어요^^, 번역: I've been to a friend because it's a famous place, but everyone is waiting in line with the age of male and female.!But I was surprised that it was really delicious and the amount
원본: 후...요즘 맛있는 집이 너무많죠?여기는 예전에 성지스러운 곳인가 봅니다.모든게 무난하고문제점은 오래기다려야하는점.겨울이나 여름에 ㄷㄷ.., 번역: after...There are so many delicious houses these days.Everything is good and the problem is that you have to wait for a long time.In winter or summer..

 93%|█████████▎| 20847/22421 [05:14<03:20,  7.86it/s]

원본: 인생맛집입니다 그만큼 맛도있고 저렴하고 당당하개 추천해줄수있는곳입니다터키풍함박스테이크와계란볶음밥 완전 추천, 번역: It's a life restaurant. It tastes like that, cheap, and recommended place.

 93%|█████████▎| 20848/22421 [05:15<07:03,  3.71it/s]

원본: 줄이 길어지기 전 애매한 시간대로 오는걸 추천. 엄청 기다려서 먹을 정도의 맛은 아니고 가성비 좋아요., 번역: It is recommended to come to the ambiguous time before the line gets longer.It's not enough to wait and eat it.

 93%|█████████▎| 20849/22421 [05:15<06:49,  3.84it/s]

원본: 오 맛있었어요 저는 오래 기다린 만큼 보람이 있었음 터키탕이 맛났음 ㅎ 아내는 정식에 한표, 번역: Oh, it was delicious. I waited for a long time.

 93%|█████████▎| 20850/22421 [05:16<10:00,  2.62it/s]

원본: 윤씨밀방이 막 생겼을 때 방문했던 기억이 난다.분위기도 좋았습니다.음식맛은 와! 맛있다하는건 아니었지만자극적이지 않은 은은한 맛이 인상적이었습니다~, 번역: I remember visiting when I had a Yoon Si wheat room.The atmosphere was good.The food tastes!It wasn't delicious, but the soft taste that was not irritating was impressive ~

 93%|█████████▎| 20851/22421 [05:16<08:58,  2.92it/s]

원본: 조금 좁긴 했지만 그래도 맛있었어요. 느끼한 거 잘 못 먹는 사람에겐 비추, 번역: It was a little narrow, but it was delicious.For those who can't eat what you feel

 93%|█████████▎| 20852/22421 [05:17<08:19,  3.14it/s]

원본: 맛있었어요! 음식이 대체적으로 짠건 있었지만 맛있어서 잘먹었어요 ㅎㅎ, 번역: It was delicious!The food was generally salty, but it was delicious and I ate well.

 93%|█████████▎| 20853/22421 [05:17<07:42,  3.39it/s]

원본: 정말 다른데 가서 별로인거 먹을때마다 생각남 그냥 윤씨밀방 갈껄 ㅠㅜ 존슨탕이랑 함박스테이크도 맛나구 양이랑 가격대비 쵝오//, 번역: It's really different, but every time I eat something, I just go to Yun Si Milk.

 93%|█████████▎| 20854/22421 [05:17<07:08,  3.66it/s]

원본: 사람이 많아 웨이팅 있습니다 제 입맛에 맛있지는 않았어요, 번역: There are a lot of people, and we are waiting. It wasn't delicious for my taste.

 93%|█████████▎| 20855/22421 [05:17<06:39,  3.92it/s]

원본: 사람이 너무 많아서 웨이팅이길어서 별로 맛은 괜찮은 정도, 번역: There are so many people, so we're waiting, so the taste is good

 93%|█████████▎| 20856/22421 [05:18<06:24,  4.07it/s]

원본: 맛있게 먹었습니당!대기가 항상 길다는게 힘듬 ㅜ, 번역: I ate deliciously!It's hard to say that the atmosphere is always long.

 93%|█████████▎| 20857/22421 [05:18<10:26,  2.50it/s]

원본: 함박테이크 너무 쏘스가 요란해 개인적으로 좋아하지는 않지만 아주 맛나다, 번역: Hambak Take is so loud that I don't like it personally, but it tastes very delicious.

 93%|█████████▎| 20859/22421 [05:19<06:59,  3.72it/s]

원본: 가성비 좋은 편. 대기인원이 많지 않다면 잠깐 기다려서 먹어 볼 만 함., 번역: Good price.If you don't have a lot of waiting, it's worth waiting for a while.

 93%|█████████▎| 20860/22421 [05:19<06:41,  3.89it/s]

원본: 가성비 굿.맛있는데 투움바가 매움, 번역: Good price.It's delicious

 93%|█████████▎| 20865/22421 [05:19<03:18,  7.84it/s]

원본: 터키풍 함박스테이크가 제일 맛있음줄이 길어서 기다리기는 빡시지만 한번쯤은 기다려볼만함, 번역: Turkish style hamburger steak is the longest, so it's hard to wait, but it's worth a look at it.

 93%|█████████▎| 20866/22421 [05:19<03:52,  6.68it/s]

원본: 존슨탕 치즈라면에 함박고기 건져 먹는 느낌함박은 자극적이지 않으며 달달한 느낌, 번역: Johnsontang cheese ramen is not irritating and sweet feels sweet.

 93%|█████████▎| 20867/22421 [05:20<04:17,  6.04it/s]

원본: 마약밀방 정말맛있음., 번역: Drug wheat room is really delicious.

 93%|█████████▎| 20868/22421 [05:20<04:32,  5.70it/s]

원본: 줄서서 기다려서 먹을 정돈지는 모르겠다..  줄 안서면 갠춘, 번역: I don't know if I will wait in line..If you don't line up,

 93%|█████████▎| 20869/22421 [05:20<04:48,  5.38it/s]

원본: 가격대비 상당히 만족스러움소스 고기 특색있게 맛있었음., 번역: It was quite satisfactory for the price.

 93%|█████████▎| 20870/22421 [05:20<05:02,  5.13it/s]

원본: 별로, 번역: not really

 93%|█████████▎| 20878/22421 [05:20<01:51, 13.87it/s]

원본: 기력이 부족할때 생각날집이에요. 멀어도 다시 찾아오고 싶게 만드는 맛집이고 고기 냄새가 안나서 부담없이 먹을수 있어요., 번역: It's a house that comes to mind when you lack energy.It's a restaurant that makes you want to come back, but it doesn't smell the meat so you can eat it casually.
원본: 맛있어서 자주 가는 식당이라맛은 별다섯개입니다동네맛집이라 약간 시끌시끌한 분위기예요, 번역: It's delicious, so it's a restaurant that's often because it's a lot of taste.

 93%|█████████▎| 20882/22421 [05:21<02:38,  9.70it/s]

원본: 칼국수 맛이 달라졌네요.. 육수에 뭔가 더 들어간 느낌.. 해물느낌나는 이상한 향이 나는데 비려요.., 번역: The taste of kalguksu has changed..I feel something more in the broth..It's a strange scent that feels like seafood..
원본: 워낙.유명한 곳이라서 13년만에 재방문했는데 역시나 예전에 왔을때만큼은 아니여도 순대국 속 고기 등이 누린내가 좀.. 남~ 그냥 순대만 들어간 걸 시키면 좀 나은데 고기든거 먹으면 누린내 심함...여긴 요즘 젊은이들이 좋아하는 순대국은 절대 아님... 동네 노인들이나 등산객들이 많이 오는 맛있다고 보긴 어려운? 옛날 냄새나는 순대국임. 재방문의사 없음~, 번역: So.It's a famous place, so I've been returning to 13 years, but I'm not as much as I used to be..It's a little better if you just have a sundae, but if you eat meat, it's my severity...This is not an absolute sundae soup that young people like these days...Is it hard to say that it is delicious with many elderly people and hikers?It is an old smell of sundae.No doctor's intention to return ~

 93%|█████████▎| 20884/22421 [05:21<02:58,  8.59it/s]

원본: 내용물이  푸짐하게 들어가 있는 순대국입니다워낙 내용물이 많다보니 소주한잔 곁들이시는 어르신들이 많아서 사람이 항상 붐비는 식당입니다겨울엔 줄서는 날이 많으니 시간을 잘 맞춰가셔야 해요, 번역: It is a sundae soup with a lot of contents.
원본: 이 동네 터줏대감이라고 불릴만 합니다! 부속고기 정말 많이 들어있고 맛있어요. 다데기랑 새우젓은 알아서 넣고, 말 안하면 순대국에 순대 두개만 넣어주셔요. 그래서 부속고기랑 반반 넣어달라고 하시거나 아니면 순대만 달라고해서 취향따라 시킵니다. 순대도 매우 맛있습니다. 자리가 협소하고 복작대긴 하지만 맛있기 때문에 인정할 수 밖에 없습니다. 월요일 휴무고 술국에는 공기밥없이 부속고기가 더 많이 나온대요., 번역: It is called this neighborhood!It is a lot of attached meat and delicious.Put the daede and shrimp chops, and if you don't talk, please put two sundae in Sundae soup.So you ask you to put half and half or half, or you can just ask for sundae.Sundae is also very delicious.The seat is narrow and abdominal, but it is delicious, so you have no choice but to admit it.Monday is closed and there are more attached meats without air rice.

 93%|█████████▎| 20885/22421 [05:22<03:13,  7.95it/s]

원본: 은평구 순대국 파는곳 중에 최고에요맛도있고 고기가 엄청 많아요어르신들은 두분이 오셔서 한그릇시키고 약주한잔씩 하시는 그런곳 입니다줄서서 먹을때도 있고 합석하는 경우도 많아요맛은 최고 순대국에 필수인 김치도 맛납니다가게가 너무 바빠서 친절하진않아요그렇다고 딱히 불친절하지도 않아요혼밥 혼술하기에 이집이 최고입니다, 번역: It is the best of Eunpyeong -gu Sundae Soup. It tastes the best and has a lot of meat.I'm so busy that I'm not kind.

 93%|█████████▎| 20886/22421 [05:22<03:37,  7.06it/s]

원본: 여기 복불복입니다. 어쩔땐 엄청 맛있는데, 어쩔땐 이것 뭐지? 이런소리 나옵니다. 사람은 엄청많아요., 번역: Here is a bokbulbok.Sometimes it's very delicious, but sometimes this is this?This sounds like this.There are so many people.

 93%|█████████▎| 20888/22421 [05:22<04:15,  6.00it/s]

원본: 유명세에 비해 맛은 그냥 그래요. 손님이 넘 많아서 시끄럽고 테이블 등 깨끗하진 않은 듯합니다., 번역: The taste is just like that.There are so many guests, so it doesn't seem to be loud and clean.
원본: 전통의 안동장굴짬뽕이 대세다그래도 난 짜장면나이 지긋한 혼밥족이 많은것몬 봐도알만한 집이다나이 먹어도 생각나서자꾸 찾게되는 집...근처 직장인들과찾아온 원로들의 비율이 적절하다ㅎㅎ, 번역: The traditional Andongjanggul champon is so popular...The proportion of the elders who came to nearby office workers is appropriate.

 93%|█████████▎| 20890/22421 [05:23<04:21,  5.86it/s]

원본: 우리나라에서 가장 오래된 중화요리집이다. 서빙 보시는 분들이 중국분이신지 조선족분들이신지는 모르겠지만, 중국적인 억양이 섞여있어 이국적 분위기가 난다. 굴짱뽕이 대표메뉴이며 굉장히 담백하고 맛이 있다. 엄청나게 특별한 맛이라고 할 수 있지만, 주변을 들렀을 때 한 번 쯤 들러서 먹어볼만한 정도의 맛으로 추천한다. 더불어 새우간짜장을 시켰는데, 엄청나게 독특한 맛은 아니었다. 소스의 국물이 좀 적은 편이라 비비기 쉽지는 않았다. 개인적인 취향으로는 소스의 국물이 좀 더 많았으면 더 맛있었을 것으로 생각된다. 나머지 서비스와 분위기는 불만이 없다. 서빙 보시는 분들은 친절하게 잘 대해주셨고, 식당분위기는 비록 처음 방문했음에도 불구하고 동네에 온 것 처럼 친숙하고 정겨웠다., 번역: It is the oldest Chinese cooking restaurant in Korea.I don't know if the serving of the serving is Chinese or Koreans, but it is exotic because of the mix of Chinese accents.Oysters are representative menus and are very light and taste.It's a huge taste, but it's recommended as a taste that is worth stopping when you stop by.In addition, I made a shrimp jjajang, but it was not a very unique taste.It was not easy to rub because the soup of the sauce was a bit less.Personally, I think it would have been more delicious if the soup of the sauce was more.The rest of the service and atmosphere are not complaints.The serving people were kindly treated, and the atmosphere of the restaurant was familiar and friendly as it came to the neighborhood despite the first visit.
원본: 을지로에 직장이 있을때부터 단골집이였던 안동장 다영한 요리와 식사를 즐겼던 곳으로 모든 메뉴별 맛은 별이5개 추천음식 깐쇼세우, 굴짬뽕, 잡채밥 점심시간에 회사원들로 붐비는 곳으로 웨이팅 있음., 번역: It was a place where I enjoyed Andongjang Damaki and meals, which had been a regular house since I had a job in Euljiro.

 93%|█████████▎| 20891/22421 [05:23<04:26,  5.74it/s]

원본: 배추를 넣어서 그런지 시원하고 맑은 짬뽕국물이 개운하다! 하지만 삼선이란 말이 부끄러울정도로 해물이 별로 없다, 번역: The cool and clear champon broth is refreshing with cabbage!However, there are not many seafood because the word trilateral is ashamed.

 93%|█████████▎| 20893/22421 [05:23<04:35,  5.55it/s]

원본: 개인적으로 간짜장이 맛있지만 겨울에 굴짬뽕도 맛있다. 탕수육도 수준급이다. 일하시는 분들이 모두 화교임, 번역: Personally, the jjajang is delicious, but the oyster jjambpong is delicious in winter.Sweet and sour pork is also a level.All those who work are Chinese
원본: 흑석동에 있는 안동장은 이곳 을지로 안동장에서 일했던 주방장이 나가서 차린 곳이라고 했다. 안동장의 이름은 북한 신의주 부근의 단동 지역 출신 화교가 70년전에 을지로에 차린 음식점 이름. 굴짬뽕이 정말 시원하고 맛나다., 번역: Andongjang in Heukseok -dong said that the chef who worked in Andongjang went out and set up.The name of Andongjang is the name of a restaurant that was set up 70 years ago by Chinese -Chinese from Dandong area near Sinuiju, North Korea.Oyster champon is really cool and delicious.

 93%|█████████▎| 20895/22421 [05:23<04:30,  5.64it/s]

원본: 굴짬뽕 전문 중화요리집입니다. 굴짬뽕에 굴이 많이 들어 있어서 좋았습니다. 굴에 비린내도 나지 않았습니다. 이 점은 매우 좋았습니다. 굴이 괜찮았던 걸 빼고 짬뽕 자체로는 평범했습니다. 매운굴짬뽕을 주문해야 빨간 국물로 나오는 것 같습니다. 다음에 빨간 국물로 먹어봐야 하겠습니다. 백짬뽕은 조금 간이 덜 됬다하는 그런 느낌이 있었습니다.바빠서 그런진 모르겠습니다만 앉았을 때 테이블에서 식초 냄새가 나서 갖고 있던 물티슈로 직접 닦았습니다. 테이블을 대충 닦는 것 같네요., 번역: It is a Chinese restaurant specialized in oyster champon.It was nice to have a lot of oysters in oyster champon.There was no fishy smell on the oyster.This was very good.Except for the oysters, Champon itself was ordinary.It seems that you have to order the spicy cave champon to come out as a red broth.Next time, I should try it with red broth.The white champon felt a little less liver.I don't know if it's busy, but when I sat down, I smelled the vinegar at the table and wiped it directly with the wet wipes I had.It seems to clean the table roughly.
원본: 엄청 추웠던 날 을지로 외근 끝내고 굴짬뽕 한 그릇 1.혼자 갈 만 하고 2.깔끔한 이라는 두 가지 모두를 충족 시키는 가게가 생각보다 을지로에 별로 없다 보통은 2번을 포기해야 하는데 그러고 싶지 않은날이 있으니 그럴때 쉬운 선택으로 고르는 코스굴짬뽕의 오리지널로 유명한 곳이기 때문에 평소에도 그렇지만 겨울에는 특히 홀 메뉴 대부분이 굴짬뽕일 정도로 인기가 많다 매운 것 안 매운 것 둘 다 먹어봤는데 안 매운 것은 시원한 느낌보다는 좀 느끼한 편이어서 좀 더 개운한 매운 쪽을 추천하고 싶다 매장이 2,3층도 있어서 단체 손님도 많은 편, 번역: A bowl of oyster champon is finished with a very cold day.It's a famous place for the easy choice, so it's a famous place for the original, so in winter, it's so popular that most of the hall menus are oyster jjambpong.After that, I would like to recommend a more refreshing spicy side.

 93%|█████████▎| 20897/22421 [05:24<04:17,  5.93it/s]

원본: 유명한 곳이죠. 유명한 굴짬뽕 라면이 이곳 굴짬뽕 구성을 벤치마킹했다고 합니다.해선볶음면은 잡탕에 면을 넣은 느낌인데 쏘쏘,  굴짬뽕은 얼큰한 맛이 명불허전이었습니다., 번역: It's a famous place.The famous oyster jjambbong ramen is said to have benchmarked the oyster champon composition.The fried noodles have a noodle in the jummy, but the sox and oyster champon have a spicy taste.
원본: 비교적 심심한 간, 편안한 맛, 노포가 주는 안정감. 다소 비싼 가격, 트렌드와는 벗어난 맛, 번역: Relatively boring liver, comfortable taste, stability of old age.Somewhat expensive prices, flavors that are out of trend

 93%|█████████▎| 20899/22421 [05:24<05:55,  4.28it/s]

원본: 전통있는 중국집. 아주 좋습니다. 역사가 숨쉬는 곳. 맛있습니다., 번역: A traditional Chinese house.very good.Where history breathes.Delicious.
원본: 어느동네를가나 짬뽕 전문점이 있기 마련이지만 얼마나 큰 차이가 나겠나 의심하고 갔다가 큰코다쳤습니다. 진한 국물맛과 푸짐한 건더기가 좋았고 다른 가게 굴짬뽕 많이 먹어봤지만 한두단계정도 업그레이드 된 맛입니다. 기름기가 약간 많아서 매운맛으로 주문 하였는데 생각보다 느끼하지않았고 맵기는 신라면정도로 무난합니다. 흰옷을 입고가서 말씀도 안드렸는데 앞치마를 주셔서 약간 감동했습니다. 직원들도 모두 친절하고 자주 가고싶은 곳입니다., 번역: There is a specialty shop in a neighborhood, but I doubted how big it would be.The rich broth and the rich dried pile were good and I ate a lot of other shops, but it is upgraded one or two levels.I ordered it with a spicy taste because it was a bit greasy, but I didn't feel it than I thought.I went to white clothes and didn't speak.The staff are all kind and often you want to go.

 93%|█████████▎| 20901/22421 [05:25<05:08,  4.93it/s]

원본: 겨울은 굴의 계절이다. 여기 굴짬뽕 너무 맛있다 굴이 통통하고 국물이 깊은맛이 난다 웨이팅 길지만 회전 빠른 편, 번역: Winter is the season of oyster.Here, oyster champon is so delicious. The oysters are chubby and the broth tastes deep.
원본: 평타는 침. 맛있는거:안매운굴짬뽕,류산슬덮밥 맛없는거:탕수육,유린기 전반적으로 식어서 나온다. 정성이 없음. 직원분들도 겁내 불친절.. 그냥 주변에 있다면 가볼법하지 굳이 찾아갈거면 송쉐프 가세요, 번역: Pyeongta is saliva.Delicious: Anmae Ungul Champon, Ryu San Seul Rice Bowl Taste: Sweet and Sour and Overall.No devotion.Employees are also scared..If you're just around, you can go to Song Chef if you're going to go.

 93%|█████████▎| 20903/22421 [05:25<04:33,  5.56it/s]

원본: 짬뽕이 유명하다고 해서 짬뽕 먹었는데, 맛있더라구요 원래 짬뽕 안좋아하는데. 단무지조차 맛있음 ,, 탕수육도 맛있구요,,, 번역: I ate Champon because it was famous, but it was delicious.Even sweet radish is delicious, sweet and sour pork is also delicious,
원본: 예전부터 맛집이라 소개받아 찾아갔는데 다른 유명한 음싣을 먹기 전 기본인 짬뽕을 먹어 정말 어떻게 간을 내는지 알고 싶었다. 간은 약간 밍밍한 편이며 매운 걸 잘 못 먹는 나도 맵지 않다고 느낄 정도 였으며 특히 사용한 오징어는 일반 냉동 오징어들와는 다른 싱싱한 오징어였다. 다만 면발 아쉽게 조금 불었었고 짬뽕을 정말 잘 하는 집은 아니라는 결론이다., 번역: It was a restaurant for a long time, but I wanted to know how to season by eating the basic champon before eating other famous mood.The liver was a bit mingling and I felt that I couldn't eat spicy well, especially the squid I used was a fresh squid different from ordinary frozen squids.However, it is a conclusion that the noodles were a little unfortunate and are not really good at champon.

 93%|█████████▎| 20905/22421 [05:25<04:20,  5.83it/s]

원본: 기대 안하고 갔는데 굉장히 맛있어요! 크림파스타가 소스가 엄청 넉넉해서 빵찍어먹고도 남았어요! 함바그는 좀 단짠이긴 한데 맛있네요 가성비 아주 훌륭합니다 ㅋㅋ, 번역: I didn't expect it, but it's very delicious!The cream pasta has a lot of sauce, so I eat it!Hambag is a little sweet, but it's delicious.
원본: 한상에 서양식과 한식이 딱~!!함바그의 고기도 소스와 치즈가 잘 어울려져서 풍미가 있구, 그 옆에 밥과도 잘 어울렸다 서양음식이 한식으로 변화한 느낌 신선합니다 그리고 맛있었어요, 번역: Western style and Korean food in Hansang ~!!Hambag's meat is also a good match with the sauce and cheese, and it goes well with rice. Western food is fresh and delicious.

 93%|█████████▎| 20907/22421 [05:26<04:15,  5.92it/s]

원본: 프랜차이즈화로 인해 아르바이트 조리장의 손을 타며 점점 특색을 잃어가는 전형적인 식당. 아직 나쁘지는 않지만 이정도의 맛을 내는 베트남 쌀국수는 이제 즐비합니다. 줄 서서 기다릴 정도는 아닙니다., 번역: A typical restaurant that loses its characteristics by riding the hand of a part -time cooking center due to the franchise.It's not bad yet, but it's a lot of Vietnamese rice noodles.It's not enough to wait in line.
원본: 진짜.. 진짜 너무 맛있어요 인생 최고의 쌀국수집이에요 저 원래 쌀국수 별로 안좋아하는데 여기서 먹고 너무 맛있어서 충격받았어요 계속 생각나는 맛이에요ㅠㅠ 가격이 좀 비싸다고 생각될수도 있는데 가격값을 하는 맛인거같아요 진짜 국물 최고 너무 맛있구ㅠ 볶음밥도 진짜 최고 맛있어요! 친구랑 가서 볶음밥 하나에 쌀국수 하나 하면 딱인거같아요 많이먹는 편이면 면추가하구! 양도 되게 많이나와요! 짜조도 되게 맛있어요~~ 여기 데려가서 맛없다고 한사람 한명도 없고 제 친구들도 한번만 간 사람이 없어요 다들 또 다른 친구 데리고가고ㅋㅋㅋ 오래 번창하세요ㅠ 너무 맛있어요, 번역: really..It's so delicious. It's the best rice noodle restaurant in life. I don't like rice noodles very much.The best!I think it's perfect if you go with a friend and one rice noodle.It comes out a lot!It's so delicious ~ ~ There's no one who said it's not delicious and I have no one who has been tasted and no one has gone once. Everyone takes another friend.

 93%|█████████▎| 20909/22421 [05:26<04:07,  6.11it/s]

원본: 쌀국수는 해물보다 소고기 쌀국수가 더 맛있습니다 ~ 그리고 국수에 같이 만두 드심 맛있어요 사람도 많은데는 이유가 있더라구요 !!!!!! 정말 맛있어요 파인애플 볶음밥도 맛있고 볶음면?? 도 멋있어요 그냥 다 맛있음 강추👍, 번역: Rice noodles are more delicious than seafood.!!!!!It's really delicious. Pineapple fried rice is also delicious and fried noodles ??It's cool too, it's just delicious 👍
원본: 지점 간의 편차 없이 맛이 균일해졌지만 국물은 많이 옅어졌습니다. 삶은 숙주가 서브되어 지나치게 뜨거운 국물에 숙주를 익힌 후 식힐 필요가 없게끔 배려한 점이 좋습니다., 번역: The taste became uniform without the division between branches, but the broth became a lot faded.It is good to be considerate of the boiled host so that you do not need to cool after cooking the host in the hot broth.

 93%|█████████▎| 20911/22421 [05:26<04:11,  6.01it/s]

원본: 쌀국수 하나만 보고 베트남 갔다온 쌀국수 처돌이인데, 맛집 소리 정말 많이 듣고 기대하고 갔더니.. 제가 좋아하는 쌀국수 맛이 아니었어요.........,,,,,...... 웨이팅 장난 아닙니다 삼십분은 기본으로 기다려야해요, 번역: I went to Vietnam only one rice noodles, but I heard a lot of restaurants and expected it..It wasn't my favorite rice noodles.........,,,,......It's not a weighting joke.
원본: 제대로된 베트남 음식 맛집!! 특히 분보싸오의 소스에서 하노이의 그 맛이 느껴져 놀라웠어요!! 가격도 적당하고 웨이팅 줄도 금방 빠지는 편이라 강추입니닷, 번역: Proper Vietnamese food restaurant!!Especially in the sauce of the bacteria, I felt the taste of Hanoi!!The price is appropriate and the waiting line is missing quickly.

 93%|█████████▎| 20913/22421 [05:27<04:19,  5.82it/s]

원본: 이곳 처음 오픈 때 부터 들렀었다. 그때 키작은 베트남 주방장의  쌀국수 맛은 기막혔다. 그래서 네이버 맛집에 소개글도 올렸던 것이다. 하지만... 지금은??? No Comment !!!, 번역: I have stopped by since the first opening.At that time, the short taste of the rice noodles of the Vietnamese chef was amazing.That's why I posted an introduction to Naver restaurant.but...now???No Comment!!!
원본: 정말 오랜만에 방문했다. 2층도 생겼다볶음밥은 여전히 맛있으나쌀국수는 나는 너무 달았고 친구는 너무 짰다고 한다., 번역: I've been to it for a long time.There is also a second floor. The fried rice is still delicious, but the rice noodles are too sweet and the friend is too hot.

 93%|█████████▎| 20914/22421 [05:27<04:17,  5.85it/s]

원본: 맛도 좋고 양도 많고 좋은데 아르바이트로 추정되는 젊은 여성분의 태도가 참.... 직원교육이 필요할듯싶네요, 번역: It tastes good, has a lot of good and good, but the attitude of a young woman who is believed to be a part -time job is true....I think I need employee education

 93%|█████████▎| 20916/22421 [05:27<04:32,  5.52it/s]

원본: 맛은 평타 그나저나 직원 싸가지가 없다.차라리 아무 포메인 가길 추천., 번역: The taste is not cheap.Rather, it is recommended to go any Formaine.
원본: 쌀국수랑 볶음밥 야채스프링롤 다 맛있음 ㅠㅠㅠㅠ 좋아하는 곳, 번역: Rice noodles and fried rice vegetables spring rolls are delicious ㅠ ㅠㅠㅠ Favorite place

 93%|█████████▎| 20917/22421 [05:27<04:23,  5.71it/s]

원본: 예전과 비교하여 확실히 맛이 떨어졌습니다. 사람은 여전히 많고 북적이나 특히 serve 하시는 분들의 태도 개선이 많이 필요하다고 생각됩니다. 손님이 올때갈때 인사를 할때 퉁명스러운 표정으로 대답도 하지 않으니 떨어진 음식맛과 함께 그간 좋은 기억도 지워지더군요, 번역: Compared to the past, it definitely tasted.There are still many people, and I think it is necessary to improve the attitude of people who are crowded or especially services.When the guests come, they don't answer with a blunt look when they say hello.

 93%|█████████▎| 20919/22421 [05:28<04:37,  5.41it/s]

원본: 별로맛없던데. 왜 인생맛집이라는건지..국물맛이며,  면발이며 실망스러웠다., 번역: It wasn't very good.Why is it a life restaurant?.It tasted soup, noodles and disappointing.
원본: 실패하지 않을 맛있는 쌀국수. 오늘 합정역이나 상수역에서 시간을 보낼 예정이라면 방문해보세요., 번역: Delicious rice noodles that will not fail.If you are going to spend time at Hapjeong Station or Sangsu Station, please visit.

 93%|█████████▎| 20925/22421 [05:28<01:46, 14.02it/s]

원본: 기본 찬이나 고기 맛은 괜찮은 편. 화구 쎄기가 약한지 고기가 잘 안 익는게 아쉬웠음. 서빙하시는 분들 반응 속도도 빠르고 친절했으나 뭔가 어설펐음. 무료주차가능!, 번역: The basic cold and meat taste is good.It was a pity that the meat was weak.The reaction speed was fast and kind, but something was clumsy.Free parking!
원본: 가마솥 갈비 시켯으나 그냥 갈비로 주셧네요... 그냥 갈비탕은 고기양이 적네요내부 인테리어는 깔끔하고 김치 맛은 살짝 달지만 깔끔합니다, 번역: I've been giving it a ribs, but I just gave it to the ribs...The ribs have a little meat.

 93%|█████████▎| 20930/22421 [05:29<02:00, 12.34it/s]

원본: 비싼 갈비집친절도 및 서비스가 좋지는 않음갈비 먹으러 가는 곳, 번역: Expensive ribs are not good and services are not good.
원본: 여태까지 먹은 파스타 양식 집 중에서 최고의 가성비를 자랑함.넷이서 가면 세 개 배터지게 먹을 정도.둘이서 가서 두 개 시켰다가 죽는 줄 알았습니다. 맛도괜찮음.네이버로 예약해야하는 이유를 알겠음, 번역: It is the best price of pasta farming collections that have been eaten so far.If you go to four, you can eat three batters.I thought I would go two and died.The taste is good.I know why you should make a reservation with Naver

 93%|█████████▎| 20932/22421 [05:29<02:36,  9.52it/s]

원본: 방문시 꼭 먹어야하는 로제파스타!!!!!!양이 어마어마하게 많고, 지금까지 먹었던 로제중 제일 맛있었습니다~스테이크는 살짝 질겨서 아쉬웠어요ㅠㅠ, 번역: Rose pasta must be eaten when visiting!!!!!!The amount was huge, and it was the most delicious Rose I've eaten so far ~ The steak was a bit tough.
원본: -주차없음-화장실 따로있어 별로(위생 별로)-가성비는 괜찮은듯. 양은 많음.-스테이크 못먹는 부위가 많음-날파리, 파리가 몇마리 계속 날라다녀서 거슬림-앞치마에서 음식물 냄새남. 빨기는 하는지 궁금-오픈키친이지만 위생상태가 좋아보이지는 않았음-자리 협소-내외부 깔끔하지는 않고 분위기가 좋은 편도 아님-왜 사당주변 1위일지 의문-재방문 의사 없음, 번역: There is no parking room.The amount is large.There are a lot of steaks that can't eat steaks, flies, flies, and smells of food in slim apron.I wonder if I was sucked, but I didn't look good for hygiene.

 93%|█████████▎| 20934/22421 [05:29<02:59,  8.30it/s]

원본: 주택가에 있어서 입구에 서기 전까지 진짜 영업하는지 고민을 좀 했어요.파스타는 2인분이 좀 넘는 양이고로스트비프도 불향나고 굽기도 따로 오더 받아요전체적으로 간이 좀 짠편이기는 해요그래도 맛있었어요, 번역: In the residential area, I wondered if I was really open until I was at the entrance.Pasta is a bit over two servings, and the roast beef is inconvenient, and the roasting is ordered separately.
원본: 항상 예약하기 힘든 곳. 로제 파스타가 맛있고 점심에 즐길 수 있는 스테이크도 맛있다, 번역: It is always difficult to make a reservation.Rose pasta is delicious and steaks that can be enjoyed for lunch are also delicious.

 93%|█████████▎| 20936/22421 [05:30<03:21,  7.37it/s]

원본: 일단 양이 상당히 많습니다. 여성기준 4인분 정도 되는것같네요.ㅎㅎ 인테리어는 완전 빈티지 하고애플망고 쥬스(?) 참 맛나네요. 스테이크도 진짜 맛있는데 넘 크다보니 금방 식어서 아쉬워요 ㅠ로제파스타는 정말 제가 먹어본 파스타 중 젤 진하고 맛있습니다., 번역: First of all, there is a lot.It seems to be about 4 servings of women.ㅎㅎ The interior is completely vintage and Apple's mango juice is so delicious.The steak is really delicious, but it's so big.
원본: 사장님도 친절하시고, 무엇보다 음식이 참 맛있었습니다., 번역: The boss was kind, and most of all, the food was very delicious.

 93%|█████████▎| 20938/22421 [05:30<03:45,  6.57it/s]

원본: 양이 혜자고 맛도 괜춘해서 항상 웨이팅 쩌는 집ㅜㅠㅠㅠ 내부가 작은  편이고 테이블 간 간격도 좁은 편임. 갈때 네이버 예약 꼭 하고 가야 됨, 번역: The sheep is good and the taste is fine, so the waiting is always small.When you go, you have to make a reservation
원본: 오랫만에 만난 친구랑 네이버예약을 통해서 예약하고 간 곳이예요. 일단 주문하면, 추가 주문은 안되다고 하셨어요. 스테이크는 원했던 굽기에 잘 맞춰주셨고 아주 부드럽고 육즙이 풍부했어요. 같이 나온 버섯도 맛있었어요. 파스타는 소스 많은거 좋아하시는 분들은 아주 좋아하실 것 같아요. 남녀노소 가리지 않고 모두가 좋아할 맛, 분위기가 있는 식당이예요~, 번역: It's a place where I made a reservation with a friend I met after a long time.Once you order, you said you can't order an additional order.The steak was well matched to the baking you wanted and was very soft and rich.The mushrooms that came out were also delicious.Pasta is a favorite if you like a lot of sauce.It is a restaurant with a taste and atmosphere that everyone will like regardless of age and age.

 93%|█████████▎| 20940/22421 [05:30<03:58,  6.22it/s]

원본: 양도 많고, 맛있고, 친절한 곳.예약 후 방문해야함., 번역: A lot of amounts, delicious and friendly places.You must visit after a reservation.
원본: 맛은 가격대비 괜찮아요 예약도 해야되고 추가주문을 못해서 자주가지는 않을 것 같아요 가격대비 양이 많아서 좋아요 근데 장소가 너무 좁고 환기가 잘안되고 덥더라구요 빨리 나가고 싶었어요 그점만 빼면 에이드도 맛있고 좋아요, 번역: The taste is fine for the price. I have to make a reservation and I can't order it often because I can't order it. It's so good that the place is so narrow and the ventilation is not good and it's hot. I wanted to go out quickly.

 93%|█████████▎| 20942/22421 [05:31<04:05,  6.03it/s]

원본: 예약하기 힘들어서 먹기가 힘든점만 빼고는 모든 것을 만족하는 식당이었습니다. 강추입니다., 번역: It was a restaurant that satisfies everything except for the difficulty to eat because it was difficult to make a reservation.It is recommended.
원본: 전반적으로 좋습니다, 번역: Overall good

 93%|█████████▎| 20944/22421 [05:31<04:16,  5.76it/s]

원본: 정말정말정말 파스타 양이 어마무시합니다!전 남자예요! 맛과 포만감! 모두 훌륭해요.예약하지 않으면 못먹어요, 번역: It's really really pasta!I'm a man!Taste and satiety!All are great.I can't eat unless I make a reservation
원본: 정말 맛있어요, 번역: It is very delicious

 93%|█████████▎| 20946/22421 [05:31<03:38,  6.75it/s]

원본: 평양냉면과 갈비탕이 유명한 가게입니다. 제가 다녀본 평양냉면 집 중 가장 좋아하는 평양냉면입니다. 특히 면이 좋습니다. 서울 중심가에, 골목길에 위치해 있어 지리적 특성이 좋지 않음에도 많은 사람들이 찾아오는 가게입니다., 번역: Pyongyang cold noodles and ribs are famous shops.Pyongyang cold noodles I have been to Pyongyang cold noodles.Especially good noodles.It is located in the center of Seoul, and it is a shop where many people visit even though the geographical characteristics are not good.

 93%|█████████▎| 20947/22421 [05:31<04:05,  6.00it/s]

원본: 이름값을 하는 집이다 육수 육향 면발 메밀향 접시만두는 촉촉하고 먹기좋은크기다 갈비탕 고기는 정말 소고기냄새가 진동을한다 비린내 전혀 없음 밑잔찬도 실속있습니다, 번역: It is a house that costs the name of the broth.

 93%|█████████▎| 20948/22421 [05:32<04:31,  5.43it/s]

원본: 2017년부터 4년동안 미쉐린 가이드 빕 그루망에 선정되고 있으며 대통령도 다녀간 식당으로 유명한 곳. 기존 건물보다 별관까지 확장할 만큼 인기가 대단한가 봅니다. 규모가 굉장히 넓은 편이고, 좌식형 개별룸도 있어서 단체로 가기에도 좋습니다.가장 유명한 메뉴는 쟁반만두와 냉면, 갈비탕 등이 있습니다. 쟁반만두는 사이드메뉴로 시키기에 딱 좋은 스타일로, 물만두에 가깝지만 속이 꽉 차있고 피가 얇아 식감이 정말 좋아요. 평양냉면을 좋아하는 사람이라면 후회하지 않을거예요. 면발이 아주 좋고 육수가 깔끔해서 평양냉면 특유의 맛을 딱 살린 듯 했습니다. 개인적으로 비빔냉면은 너무 맵기도 했고 비빔소스가 너무 강렬해서 면 식감을 즐기기에 과했던 것 같아요. 갈비탕은 가격대비 갈빗대가 많이 들어가 있었고 육수에 기름없이 깔끔해서 속이 든든합니다.• 골목 내에 위치해 있어 접근성이 어려운 편입니다., 번역: For four years since 2017, it has been selected as a Michelin Guide Bib Gruang and is famous for its restaurant.It is so popular that it expands to the annex than the existing building.It is very large and there is a seated individual room, so it is good to go to the group.The most famous menus are tray dumplings, cold noodles, and ribs.The tray dumplings are perfect for the side menu, and it is close to water dumplings, but the texture is full and the blood is thin.If you like Pyongyang cold noodles, you won't regret it.The noodles were very good and the broth was clean, so it seemed to make the taste of Pyongyang cold noodles.Personally, the bibim cold noodles were so hot and the bibimb sauce was so intense that I enjoyed the texture.The ribs have a lot of ribs for the price, and the broth is clean without oil.• Located in the alley, it is difficult to access.

 93%|█████████▎| 20949/22421 [05:32<04:45,  5.15it/s]

원본: 그냥저냥 무난한 냉면유명세에 비해서 특별히 맛있는 건 모르겠음냉면보다는 그나마 온면이 육수맛이 느껴져 조금 나은 듯내부는 아주 넓은 편이나 사람 굉장히 많음인근 회사들 회식용으로 많이 쓰이는듯함, 번역: It's just a good cold noodle.

 93%|█████████▎| 20950/22421 [05:32<05:02,  4.86it/s]

원본: 대통령도 왔다간 식당이라고 해서 기대는 했지만 무난한 맛이었음. 반찬이랑 동치미가 맛있었다., 번역: If the president came to the restaurant, it was a good taste.The side dishes and Dongchimi were delicious.

 93%|█████████▎| 20951/22421 [05:34<15:59,  1.53it/s]

원본: 한줄평 👉 평양냉면을 좋아하는 이들에겐 성지.-미쉐린가이드에도 나온 평냉 맛집이에요! 시청역 광화문 근처서 평냉 땡길 때 좋네요 :), 번역: One line of peace 👉 Pyongyang cold noodles for those who like it.It is also a pyeong -cold restaurant in the Michelin guide!It is good when you are near the city hall station Gwanghwamun :)

 93%|█████████▎| 20952/22421 [05:34<12:55,  1.89it/s]

원본: 깔끔한 한옥 느낌이었고 이명박 문재인 대통령 사인이 걸려있었네요.비빔냉면 맛은 자극적이지않았으나 양념은 많이 쓴듯 했어요. 만두는 순했습니다., 번역: It was a neat hanok and Lee Myung -bak, Moon Jae -in's sign.The taste of bibim cold noodles was not irritating, but the seasonings seemed to be used a lot.Dumplings were mild.

 93%|█████████▎| 20953/22421 [05:34<10:46,  2.27it/s]

원본: 평양냉면을 한번도 안먹어본 사람들은 이 곳에서 먼저 먹고 평양냉면 집을 찾길 추천한다.  우래옥보다는 여기가 육수에 간이 더 되어있어서 밍밍한 맛을 싫어하는 사람에게는 좋다. 그리고 식전에 나오는 동치미는 정말 개운하고 특히 갈비탕은 이 집이 최고인 것 같다. 냉면이 안맞으면 갈비탕 때문에라도 다시 찾게되는 집🍴, 번역: People who have never eaten Pyongyang cold noodles are recommended to eat here and visit Pyongyang cold noodles.Rather than Uraeok, this is more liver in the broth, so it is good for people who don't like the mingling taste.And Dongchimi, which comes out before the ceremony, is really refreshing, and especially Galbi -tang seems to be the best.If the cold noodles are not right, the house that you will find again because of the ribs tang

 93%|█████████▎| 20954/22421 [05:35<09:14,  2.65it/s]

원본: 평양냉면 맛이 이게 뭐지 싶었다 내가 잘못 됐나?? 글쎄 이곳은 좀 아니였다, 번역: Pyongyang's cold noodles wanted to know what was this wrong?Well, this was not a little

 93%|█████████▎| 20955/22421 [05:35<08:23,  2.91it/s]

원본: 주말에도 본관은 열어요! 평양냉면 좋아하는데 여기 냉면은 평양냉면과 일반냉면의 중간이랄까..? 이도저도 아닌 맛이라 실망스러웠다,,ㅠ 게다가 이 가격에 먹을 냉면은 진짜 아님.. 그래도 갈비탕은맛있어서별두개.. 반찬은 전체적으로 깔끔해서 좋았음, 번역: The main building is open on weekends!I like Pyongyang cold noodles, but here's cold noodles between Pyongyang cold noodles and regular cold noodles..?It was disappointing because it was not a taste, but the cold noodles to eat at this price are not real..Still, the ribs are delicious..The side dishes were neat as a whole

 93%|█████████▎| 20956/22421 [05:35<07:38,  3.19it/s]

원본: 미슐랭가이드에 선정된 집으로 가족외식을 하기에 제격입니다. 어복쟁반도 맛있었습니다., 번역: It is perfect for a family eating out with a house selected for the Michelin Guide.It was also delicious.

 93%|█████████▎| 20958/22421 [05:35<05:24,  4.50it/s]

원본: 국물이 진함 슴슴한 평양냉면맛은 아니나 고기 오이 각각의 조합이 훌륭함 면발은 평이해 보이나 실제 먹으면 식감이 매우 좋고 완냉하고 왔습니다 ㅋ 점심 때 줄이 긴데 본점?이 줄이 보기보단 더 줄이 짧습니다 줄 설  때 참고하세요, 번역: The broth is not dark, but the combination of each meat cucumbers is good, but the noodles look good, but when you eat it, the texture is very good and cold.Please refer to it when you stand

 93%|█████████▎| 20959/22421 [05:36<05:24,  4.51it/s]

원본: 미슐랭.등록됚다고 해서 먹었는딩 건강한 맛 맛있네요오오 육수~~, 번역: Michelin.I ate it because I registered it.

 93%|█████████▎| 20960/22421 [05:36<05:22,  4.53it/s]

원본: 가면 무슨 민속촌 온 것 같아요~ 몇 십 년은 되 보이는 항아리부터 한옥 구조에~ 저는 보통 냉면 갈비탕 육개장 이렇게 자주 먹는데 냉면은 워낙 유명한 집들 많으니 그렇다 치고 갈비탕이랑 육개장이 진짜 시원해요~! 이 동네에서 육개장이랑 갈비탕 맛집이 딱히 없어서 여기 좋아요!, 번역: I think it's a folk village.There is no Yukgaejang and Galbi -tang restaurants in this neighborhood!

 93%|█████████▎| 20961/22421 [05:36<05:29,  4.43it/s]

원본: 동치미 국물 맛 나는 냉면 맛있어요갈비탕은 깔끔한데 고기 양은 적은 편이에요.가격대비는 보통. 하지만 그냥 맛만 따지면 맛있어요., 번역: Dongchimi broth tastes delicious cold noodles.The price is usually.But it's delicious if you just taste it.

 93%|█████████▎| 20962/22421 [05:36<05:26,  4.47it/s]

원본: 무엇을 먹어도 맛있는 노포, 번역: No matter what you eat

 93%|█████████▎| 20963/22421 [05:36<05:34,  4.36it/s]

원본: 세젤맛없음 ㅡㅡ서비스 최악에 냉면에서 이상한 약냄새남, 번역: Sezel is not tasted ㅡ ㅡ Service Worst in cold noodles

 94%|█████████▎| 20969/22421 [05:37<02:53,  8.39it/s]

원본: 모듬순대는 대창순대 말고는 기대이하였어요가성비 충이라 나중엔 순대정식으로 시켜보려고요, 번역: Assorted Sundae was expected except Daechang Sundae.
원본: 대창순대로 유명한 집 답게, 대창순대(아바이 순대)가 너무 맛있었어요! 다만 내장류에 약하거나 냄새에 민감한 사람들은 어렵게 느낄 수 있는 맛이어서 호불호가 갈리네요. 저녁에 순대 2인분 시키면 술국이 딸려나와요.점심에 순대정식 4인분 시키면 사진에 보이는만큼 순대+내장이 나오고 국물 4개, 밥4개가 나와요. 점심 순대정식에 딸린 국물은 건더기 없이 국물만인 점 참고하세요~, 번역: Like Daechang's famous house, Daechang Sundae (Abi Sundae) was so delicious!However, people who are weak or sensitive to the intestines are difficult to feel difficult.If you divide Sundae 2 servings in the evening, you will get a soup.If you have four servings of Sundae for lunch, you will see Sundae+Intier as you can see in the picture.Please note that the broth with lunch sundae is the soup

 94%|█████████▎| 20971/22421 [05:37<03:19,  7.26it/s]

원본: 수요미식회, 최자로드에 나오기 전부터 이 부근에 근무하는 지인이 맛있다고 극찬한 집토요일 6시에 갔는데 1시간 웨이팅 추운데 기다리다 먹어서 더 맛 있었슴순대국밥에 돼지 비린내 하나 없이 깔끔하고아삭하고 시원한 깍두기며 열무와 대파가 들어간 겆절이도 맛 있었슴특히 김치 맛에 민감한같이 간 친구도 맛있다고2번씩 리필함다만 예전 건물이라화장실이 좀 아쉬웠음, 번역: Prior to the demand gourmet, the acquaintances who worked near this area were delicious, I went to 6 o'clock, which was praised for being delicious.The dishes with green onions were also delicious.
원본: 을지로의 유명한 대창순대 집. 순대 정식은 순대를 포함해 새끼보, 수육, 귀 등 다양한 부위가 나오는데 손질이 잘 되어서인지 냄새는 없음. 기본 국물 맛은 조금 아쉬움. 대기가 긴 편., 번역: Daechang Sundae House in Euljiro.Sundae set meals, including sundae, various parts such as baby beams, meat, and ears.The basic broth taste is a bit unfortunate.The atmosphere is long.

 94%|█████████▎| 20973/22421 [05:39<09:57,  2.42it/s]

원본: 주차는 가게앞 세대 정도 운 좋으면 할 수 있는 정도 ㅎ 피크시간엔 대기 감수해야하는 곳. sns에서 모듬순대 비주얼을 보고 급방문... 흐린날 두시쯤 갔는데.. 안타깝게 점심시간 모듬순대 완판이라고 ㅜㅜ 3시~5시가 브레이크 시간이라 5시에 와야 먹을 수 있대서 고민하다가 그냥 순대국 시켰어요. 순대국 특을 시켰는데 실수로 보통이 나와버렸는데.. 내용물이 많고... 다른 곳보다 기름기와 잡내가 적어서 정말 구수하고 맛있게 먹었구요. 기름도 손질된듯하고 고기가 굉장히 부드러웠습니다. 김치와 깍두기도 굿. 양파만 주면 좋겠음.. 가격대도 착한데... 모듬순대는 얼마전 가격 인상한듯 ㅎ평일 두시쯤에도 테이블이 거의 꽉차 있었고 손님들 계속 들어오는..., 번역: Parking is a place where you can do it if you are lucky to generation in front of the store.Seeing the assorted sundae visuals on SNS...I went around two o'clock on a cloudy day..Unfortunately, it was a complete version of the assortment of lunch time. 3 ~ 5 o'clock was brake time, so I had to eat at 5 o'clock, so I thought about it.I had a sundae soup, but it was usually out of mistake..There are many contents...I had less greasy and greasy than anywhere else, so I ate really delicious and delicious.The oil was trimmed and the meat was very soft.Kimchi and Kakdudu are also good.I want to give only onions..The price is also good...The assorted sundae was a while ago...
원본: 퇴근하고 땡 하고 갔는대로 줄이 어마하게 길었어요. 기다릴 각오라고 가야합니당. 하지만 기다린만큼 저는 만족스러웠어요. 이렇게 맛있는 순대 첨먹어봐서 이색적이라 좋았습니다., 번역: The line was so long as I went home and went.I have to be ready to wait.But I was satisfied as much as I waited.It was good to have such a delicious sundae.

 94%|█████████▎| 20975/22421 [05:40<09:31,  2.53it/s]

원본: 평일 오후 방문 사람이 굉장히 많았다.대학생 둘이라 그런지 사장님이 반말을 쓰셨다. 이거까지는 어떻게 이해하고 넘어갔다.순대 정식 두 개를 시켰다. 이 곳에 처음 방문 하는지라 순대 정식을 시키면 음식이 어떻게 나오는지 몰랐다. 시키고 나서 순대국 하나가 왔는데 당연히 우리꺼 하나 미리 나와서 먼저 하나 준줄 알았다. 근데 잘못 준 거였다.도로 가져가면서 왜 잘못 온지 알면서 말 안했냐고 우리한테 화를 내더라 어이가 없었다.그리고 나온 음식, 근데 밑반찬 중 하나인 고추가 반쯤 잘라진 채 왔더라. 잘보니까 누가 한입 베어먹은 자국이다. 충격적이였다.이거에 대해 말씀 드리니 짜증을 내면서 가져가고 새걸로 아무말 없이 다시 줬다.죄송하다는 말은 한번도 안했다.살아서 이런 몰상식한 서비스는 처음 받아본다. 음식이고 뭐고 간에 사람을 대하는 기본 태도가 안되어있다. 두번 다시 방문할 일 없을 집. 형편 없다., 번역: There were a lot of people on weekday afternoon.I was two college students, so the boss wrote.I understood this and went over.I had two sundae officials.I first visited here, so I didn't know how food would come out if I had a sundae formula.After I told you to have a sundae soup, and of course we came out in advance and thought it was one first.But it was wrong.I was angry at us that I didn't tell me why I came wrong while taking the road.And the food that came out, but one of the side dishes, the peppers came half cut.Looking at it, someone is a bite.It was shocking.I talked about this and took it back and gave it again without saying anything.I'm sorry.I live for the first time to live this kind of service.It's a food and it's not the basic attitude toward people.A house that will not be visited again.Targe.
원본: 특이한 서빙방식. 3-5시 브레이크타림. 4시반부터 줄서 있어요. 5시 오픈해서 들어가면 원하는자리 앉지만 주문은1번테이블부터받네요. 간만에 정성들여 삷은 순대. 머리고기. 국물 너무 맛있게 먹었답니다. 번창하세요., 번역: Unusual serving method.3 5 o'clock brakes.I'm in line from 4:30.If you open 5 o'clock, you sit down, but you will receive the first table.Sundae was sincere in a while.Hair meat.The soup was so delicious.Prospery.

 94%|█████████▎| 20977/22421 [05:40<06:53,  3.49it/s]

원본: 순대 정식 2인 먹었는데 같이 나오는 순대모듬 맛있어요. 오히려 같이 나오는 순대국 국물이 쏘쏘임, 번역: I ate Sundae 2 people, but it is delicious sundae assorted.Rather, the sundae soup that comes out together
원본: 이거 뭐 더 할말이 있겠습니까. 순대와 내장 좋아하시는 분들은 꼭한번 가시길..., 번역: What's more to say?If you like Sundae and internal organs, please go...

 94%|█████████▎| 20979/22421 [05:41<05:19,  4.51it/s]

원본: 맛집소개에 여러번 나온 순대 맛집이에요.대창순대가 특이하고 맛났고 돼지비린내 없이 맛났어요. 모듬순대는 좀 차갑게 나오는 편입니다. 재방문 예정입니다.가격인상이 전반적으로 있었던것 같아요 메뉴판에 스티커를 덕지덕지~ 붙여놓으셨고.. 줄서서 들어가는 집입니다, 번역: This is a sundae restaurant that appeared several times in the introduction of the restaurant.Daechang Sundae was unusual, delicious and delicious without pork fishy.Assorted Sundae is a bit cold.It is scheduled to return.I think the price hike was overall. You put the sticker on the menu..It is a house in line
원본: 어떤 음식들은 맛에 대해 생각을 하고 먹어야 하는 부분들이 있다고 생각함. 이미 오랜 시간 동안 분식집 순대와 프랜차이즈 순대국밥 집에 길들여져 있는 젊은 사람들에게는 정제되지 않은 돼지고기 특유의 누린내가 남. (이건 맛 없다는 표현이 아님)토속적인 입맛의 기준에선 충분히 맛있음. 주변의 광장시장이나 낙원상가에서 파는 시장의 맛도 남. 어른들을 위한 맛임. 한번 쯤은 와 볼 만한 곳. 호불호가 있음.위생상태는 그닥 좋아보이지 않음. 사람이 너무 많아서 나 같은 건 안중에도 없음. 그러나 주인집 사장님의 기억력과 입담으로 해결됨.특이점은 수요미식회를 보고 온 손님보다 원래 오던 손님이 더 많음., 번역: Some foods think that there are parts that need to be thought about and eat.For young people who have been tamed in snacks sundae and franchise sundae soup for a long time, I enjoy unrefined pork.(This is not a good expression.) It is delicious enough for the standard of native taste.The taste of the market sold in the square market and paradise shopping malls is also left.Taste for adults.At least once.There is a dislike.The hygiene does not look good.There are so many people that I don't have anything like me.However, it was solved by the memory and talk of the owner's house.The peculiarity is that there are more guests who originally came than the guests who watched the demand sashimi.

 94%|█████████▎| 20980/22421 [05:41<04:51,  4.95it/s]

원본: 점심시간 12시 반쯤 갔는데 사람이 좀 있어서 웨이팅 10분쯤 했다. 정식은 늦게 나올 것 같아서 순대국밥을 시켰는데 빨리 나왔다. 순대국밥 맛이 깔끔하고 부드럽고 고소하니 좋았고 뒷맛이 깔끔했다. 김치도 아삭하고 맛있었다. 주인분께서 친절하시지는 않았지만 나름 괜찮았다. 다음 방문때는 정식이랑 술을 먹어보고싶다!, 번역: I went around 12:30, but I had some people for about 10 minutes.The ceremony seems to be late, so I made Sundae soup rice and came out quickly.Sundaeguk rice taste was clean, soft and savory, and the aftertaste was clean.Kimchi was crispy and delicious.The owner was not kind, but it was okay.I want to have a meal and alcohol at the next visit!

 94%|█████████▎| 20982/22421 [05:41<04:42,  5.10it/s]

원본: 분위기는 시끌벅적 시장통 나이든사람많음 위생상태는 깔끔하기보단 오래된상태 대창순대 맛있음 대창순대 꺼멓고 부담스럽게생겼는데 먹자마자 사르륵녹음 이것때문에 최자로드에서 온것 순대국은 평양냉면같은 심심하지만 계속먹고싶은맛 나이든사람이 좋아하는맛간도맛있어서 소주한잔하면서 먹기좋은곳재방문보다는 대창순대포장정도? 줄도길어서 일부로와서 기다려서 먹기보다는 지나가다가 잠깐들를까정도 순대국은 다른맛집이 더 나음, 번역: The atmosphere is noisy market age.The taste of people is also delicious, so it's a great place to eat with a glass of shochu.Rather than waiting for a part of the way, I passed by, and I passed by.
원본: 내가 갔을땐 점심 끝자락 평일이라서 그런지 순대가 별로 없는 상황 모듬순대에 순대 너무 조금 ㅡ온통 내가 못 먹는 것뿐 ㅡ내가 순대만 그랬는데 순대만 줄 양이 없다고 기다려야한다고 그래서 ㅡ반이상 남겼더니 내가 순대 처음 먹는줄 암 ㅡ혼자갔는데 모듬 시키니 서비스는 뭔가 좀 달라졌지만 ㅡ솔직히 난 순대투어 나름 마니했는데 ㅡ여기 순대는 너무 부랴부랴 만든 느낌 ㅡ 느끼했던 기억이 많다 ㅡ아니면 내가 내가 원한데로 안 나와서 그랬을지도, 번역: When I went, it was a weekday at the end of the lunch, so there was not much sundae.ㅡ I went to the married man, but the service was a little different, but the service was a little different.

 94%|█████████▎| 20984/22421 [05:41<04:30,  5.31it/s]

원본: 비교적 일찍 갔는데도 이미 만석이었어요 점심 때 방문하시려면 오픈시간 전에 가시던지아예 늦게 가실 것을 추천드립니다, 번역: Even though I went relatively early, it was already full.
원본: 정말 맛있게 잘먹었습니다. 별다섯개는 쉽게 주는게 아닌데 줘야겠습니다. 합리적 가격과 맛을 모두 가지고 있는 집이네요, 번역: I ate really deliciously.It's not easy to give five stars.It's a house that has both reasonable prices and flavors.

 94%|█████████▎| 20986/22421 [05:42<04:05,  5.85it/s]

원본: 을지로의 노포, 방송에서 몇번 나와서 사람들이 많습니다만...서비스가 그리 좋다고 하기는 힘듭니다 주문이 잘못들어가 다른 음식이 나와서 물어봐도 그냥 넘어가버리더군요, 번역: There are a lot of people in Euljiro's old age, broadcasted several times from the broadcast...It's hard to say that the service is so good.
원본: 제가 비록 많은 순대국밥을 먹어본것은 아니지만 맛 본 순대국밥 중에서는 으뜸 가는 맛이였습니다. 국물이 다른 순대국밥집보다는 담백한 편이 었습니다. 개인적인 견해로는  순대와 부속고기의 비율에서 부속고기부분이 다른 집보다는 더 큰 편입니다. 순대에 쌀이 들어있어서 순대가 쫄깃합니다., 번역: Although I haven't eaten many sundae soup rice, it was the best taste among Sundae soup.The soup was pleasant than other sundae soup restaurants.In my personal opinion, the attached meat part is larger than other homes in the ratio of sundae and attached meat.Sundae contains rice, so Sundae is chewy.

 94%|█████████▎| 20988/22421 [05:42<05:33,  4.29it/s]

원본: 그냥 맛있다인생순대국집, 모듬과 국밥을 시켜서 혼자 다먹어야 행복하다다 맛있다, 번역: It's just delicious.
원본: 평일 저녁 8시 쯤 도착했다가 모듬순대가 다 떨어졌다고 해서 다른날 6시반 쯤 재방문. 50분 대기해서 들어갔는데 역시나 조금은 불청결하고 시끄러웠어요.모듬순대는 비주얼이나 기대했던 것에 비해 따뜻하지 않고 냄새가 살짝 나서 아쉬웠지만, 대창순대, 귀 등 독특한 부위가 많아서 즐겁게 먹었습니다. 지긋이 앉아서 술먹기는 어려운 분위기라, 이른 시간 술과 순대가 그리울때 방문할 것 같습니다., 번역: Arrived around 8:00 pm on weekdays, and the assorted sundae fell, so it was returned around 6:30 on the other day.I waited for 50 minutes, but it was a bit unclear and noisy.Assorted Sundae was not warm compared to the visuals and expectations, but it was a little smelly, but it was fun because there were many unique parts such as Daechang Sundae and ears.It's hard to sit down and drink, so it's going to be visited when you miss early drinking and sundae.

 94%|█████████▎| 20990/22421 [05:43<06:31,  3.65it/s]

원본: 순대는 나쁘지않은 정도~ 근데 저녁이라 사람이 많아서 그런지 넘 어수선., 번역: Sundae is not bad ~ But it's evening, so there are a lot of people.
원본: 기대를 많이 하고 간 곳, 맛은 있었지만 너무 정신없고, 친절하진 않다. 그리고 모듬은 조금 잡내도 있다, 번역: Where I expected a lot, it was tasty, but too crazy and not kind.And there is a little assorted

 94%|█████████▎| 20992/22421 [05:43<05:15,  4.52it/s]

원본: 기본에 충실한집. 순대국밥이 이런것이라는걸 한수 배우고 감, 번역: A house faithful to the basics.Learn that Sundae Gukbap is like this
원본: 점심시간 직전에 갔는데 유명한 곳이라 그런지 붐볐다. 국물은 참 좋았음. 토속적이다라고 표현하면 좋을듯, 번역: I went just before lunch, but it was crowded because it was famous.The soup was great.It would be nice to express it as native

 94%|█████████▎| 20994/22421 [05:44<04:45,  5.00it/s]

원본: 최자로드로 유명하길래 다녀왔어요 대창순대와 간이 진짜 맛있어요 다른 부위는 돼지내가 좀 났어요, 번역: I was famous for the Choija Road.
원본: 누린내 안나는 순대대창순대를 안먹어봤다면 여기로 가시면 되요~~, 번역: If you haven't eaten Sundae Daechang Sundae, you can go here ~~

 94%|█████████▎| 20996/22421 [05:44<04:29,  5.30it/s]

원본: 신발장에 신발 않넣었다고 옆테이블 손님 욕 먹음 끝까지 쫒아와서 신발 올리리고 소리 지름. 세상에 이런 광경 처음 봤음고기이 차가웠음. 이유가 있을것 같긴 한데 개인적으로 차가운고기 싫어함, 번역: The table is not put in the shoe rack, and the side table guests are followed to the end of the swearing.I saw this sight in the world for the first time. The meat was cold.I think there's a reason, but personally I don't like cold meat
원본: 순대국의 내공이 상당한 집가격도 착하고 순대를 좋아한다면 꼭 가볼만한집, 번역: Sundae soup is a good house, and if you like Sundae, you must visit

 94%|█████████▎| 20997/22421 [05:44<04:19,  5.48it/s]

원본: 인기가 너무 많아서 50분 줄 서고 겨우 먹었는데 진짜 맛있어요, 번역: It was so popular that I lined for 50 minutes and ate it, but it was really delicious.

 94%|█████████▎| 20998/22421 [05:45<08:16,  2.87it/s]

원본: 최자 맛집이라 방문해봄대창순대는 맛있고 나머지는 그냥 그럼, 번역: It is the best restaurant.

 94%|█████████▎| 21000/22421 [05:45<06:14,  3.80it/s]

원본: 순대모듬은 진짜 최고! 순댓국도 맛있고 클래스가 남다른 집, 번역: Sundae Assorted is really the best!Sundaeguk is also a delicious and classy house
원본: 유명해지기 전에 갔었는데 맛있었음 언젠가 사람 없을 때 다시 가고 싶음, 번역: I went before it became famous, but it was delicious.

 94%|█████████▎| 21002/22421 [05:46<05:03,  4.67it/s]

원본: 먹어본 순대중 으뜸!!, 번역: Sundae -jang for eating!!
원본: 음식가격: ☆☆☆☆음식의양: ☆☆☆☆음식의맛: ☆☆☆☆☆    서비스: ☆☆☆☆=  4.3/5점, 번역: Food Price: ☆☆☆☆ Food Price: ☆☆☆☆ Taste of Food: ☆☆☆☆☆ Service: ☆☆☆☆ = 4. 3/5

 94%|█████████▎| 21005/22421 [05:46<03:24,  6.92it/s]

원본: 하드한 풍미와 비주얼의 순대맛집.모듬순대와 국밥이면 술이 술술 들어간다.보기와 다르게 잡내를 거의 없앴다.그래도 비주얼이 비주얼인지라, 순대 크기를 좀 작게 하면 더 잘 먹을 수 있을 것 같은데..., 번역: Sundae restaurant of hard flavor and visuals.Assorted sundae and soup are drinking.Unlike the view, almost eliminated it.Still, the visuals are visuals, so if you make the sundae size a little smaller, you can eat better...
원본: 돼지냄새 음식,  고성 취객 만원동네 순댓국집 보다 훨 못함, 번역: Pig smell food, Goseong drunkard is much worse than Sundae -guk house

 94%|█████████▎| 21011/22421 [05:46<02:09, 10.93it/s]

원본: 술안주로 모듬순대 정말 좋고 밥으로 순대국밥 좋다!, 번역: Assorted Sundae is really good and sundae soup is good with rice!
원본: 일단 전복삼합이 너무 맛있었어요!! 음식이 맛있는데 그보다 더 중요한 것은 없다고 생각합니다~ 저는 회사 회식으로 갔지만, 깔끔해서 가족들과 외식 장소로도 좋을 것 같아요^^ 건강한 음식입니다~!, 번역: First of all, the abalone samhab was so delicious!!I think the food is delicious but I don't think it's more important than that ~ I went to the company's dinner, but it would be nice to be a family with my family.

 94%|█████████▎| 21013/22421 [05:47<02:44,  8.55it/s]

원본: 전복 요리를 전문으로 하는 곳. 인근 직장인 들이 점심 식사로 많이 찾는다., 번역: A place specializing in abalone dishes.Nearby office workers find a lot of lunch.
원본: 불맛느껴지는 제육 추천하구요. 콩국수 열무국수도 시원하고 좋네요., 번역: It is recommended that it feels like a fire.Bean noodles are also cool and nice.

 94%|█████████▎| 21014/22421 [05:47<03:13,  7.28it/s]

원본: 구로 족발 맛집~!!둘이서 세트 시켜먹었어요.양이 너무 많아서 결국 남은 거 포장했어요.반반족발은 양념족발 반, 전통족발 반으로 구성되어 있어요.양념족발은 맵기 조절가능한데 1단계도 맵더라구요. 매운거 잘 못드시는 분들은 주의하시길..전통족발은 부드럽고 쫄깃합니다.해물파전은 일빈 파전과 다르고 튀김파전 느낌이에요.강추~!!! 꼭 드셔보세요~!!, 번역: Guro jokbal restaurant ~!!I ate them two.It was so large that I finally wrapped up the rest.Half -half pork feet are composed of half seasoned jokbal and traditional jokbal.Seasoned jokbal can be controlled, but the first stage is also spicy.Please note that if you are not spicy..Traditional jokbal is soft and chewy.Seafood Pajeon is different from Ilbin Pajeon and feels like fried waves.Recommended ~!!!Be sure to eat ~!!

 94%|█████████▎| 21015/22421 [05:47<03:46,  6.20it/s]

원본: 점원분들이 친절해요! 양도 많아서 배부르게 먹고왔네요. 맛도 굿입니다!, 번역: The clerks are kind!I have a lot of amounts, so I eat it.The taste is also good!

 94%|█████████▎| 21017/22421 [05:48<03:22,  6.92it/s]

원본: 위치가 조금 번화가랑 떨어져있는데 그래서 좋은 것 같아요. 따뜻하고 아늑한 분위기에요. 데이트도 좋지만 여자친구들 끼리 놀러가기 좋아요., 번역: The location is a little far away, so I think it's good.It's warm and cozy.Dating is good, but girlfriends are good to go to play.

 94%|█████████▎| 21018/22421 [05:48<03:47,  6.16it/s]

원본: - 가격 저렴한편이고 스누피가 너무 귀여워요- 카페 직원분도 너무 친절합니다, 번역: The price is cheap and the snoopy is so cute.

 94%|█████████▎| 21019/22421 [05:48<04:06,  5.68it/s]

원본: 조용하고 아늑한 카페. 커피랑 와플 비주얼이 너무 좋고 사장님이 정말 친절하심, 번역: Quiet and cozy cafe.Coffee and waffle visuals are so good and the boss is really kind

 94%|█████████▍| 21020/22421 [05:48<04:21,  5.35it/s]

원본: 화장실 불편한거 빼고 다좋아요, 번역: I like everything except the toilet uncomfortable

 94%|█████████▍| 21021/22421 [05:49<04:44,  4.93it/s]

원본: 웨이팅이 항상 심한걸 봤기 때문에 오후 4시에 대기자 순번을 적을 때 시간맞춰 갔어요. 3시 55분에 도착했는데 앞에 무려 6팀이나 있었어요. 다행히 5시에 오픈하자마자 오래 기다리지 않고 들어갔어요. 자리가 좁아서 두툼한 외투를 입는 겨울에는 다소 불편하네요.맛은 기대 이상이었습니다. 돈가스, 로카츠 등은 항상 그 맛이 그 맛이라고 생각하고 썩 좋아하지도 않거든요. 이 맛이면 ‘30분정도는 기다릴만 하다’ 가 총평이에요. 부드럽고  촉촉한데 겉은 바삭해서 맛있었습니다~! 특히 로카츠가 겨자와 잘어울린다는 사실을 처음 알았습니다. 히말라야 소금 찍어 먹는 것도 너무 맛있었습니다~~, 번역: I always saw the weight of the waiting, so I time when I wrote the waiting number at 4 pm.I arrived at 3:55 and there were 6 teams in front.Fortunately, as soon as I opened at 5 o'clock, I didn't wait for a long time.It's a bit uncomfortable in the winter when the seat is narrow and wearing a thick coat.The taste was more than expected.Pork cutlet, Lokatsu, etc. I always think that the taste is its taste and I don't like it very much.If this taste is, '30 minutes is worth waiting' is a general review.It was soft and moist but it was crispy on the outside ~!In particular, I first knew that Rokatsu went well with mustard.It was so delicious to eat the Himalayan salt dip ~~

 94%|█████████▍| 21022/22421 [05:49<04:47,  4.87it/s]

원본: 작은 반지하 식당인데 오픈부터 사람이 많고 줄을 섭니다. 음식은 가성비가 아주 괜찮고, 깔끔해요. 레모네이드는.. 구지 시킬 필요는 없다고 봅니다. 음식이 천천히 나오는 편인데 데이트하거나 여유있을 때 가면 웨이팅리스트에 이름 올려놓으면 되서 실제로 서서 줄을 서는게 아니라 기다릴만한 정도 입니다., 번역: It's a small ring restaurant, but since the opening, there are a lot of people and lines.The food is very good and tidy.Lemonade is..I don't think it is necessary to keep it.The food comes out slowly, but when you go dating or relaxed, you can put your name on the waiting list, so you don't actually stand in line.

 94%|█████████▍| 21023/22421 [05:49<05:11,  4.49it/s]

원본: 겉은 바삭하고 속은 촉촉한 유명한 돈가스에요. 명성만큼 식감, 맛 너무 만족했어요! 제 입맛엔 로스가스가 부드럽고 맛있던거 같아요ㅎㅎ특로스가츠정식은 한정수량이라 못먹어봤지만 만약 일찍 방문하게된다면 한 번 먹어보고싶네요. 대기가 좀 있지만 시간 잘 타서 가면 안기다려도되요. 유명해지니까 주말에 가면 항상 기다리더라구요. 오픈 전에도 줄 서있는 걸 보았네요.. 점심시간 끝나구 아니면 좀 늦은 저녁에 기면 안기다려도 되는데 다만 늦은 저녁엔 픔절일 수 있습니다 ㅜㅜ 일식 돈가스를 좋아한다면 크레이지카츠의 로스카츠정식, 히레카츠정식은 안좋아할 수가 없는 메뉴일거에요~^^, 번역: It's crispy on the outside and a moist famous pork cutlet.The texture, the taste was so satisfying as well as the reputation!My taste is soft and delicious.There's a little waiting, but you can hug you when you go well.It's famous, so I always wait for the weekend.I saw you lined up before the opening..You can hug your lunch or a little late evening, but it's a late evening.

 94%|█████████▍| 21024/22421 [05:49<05:25,  4.29it/s]

원본: ◈ 맛집기록 #1 '크레이지카츠' (4.0점 / 5점 만점)- 우리나라 3대 돈가스 식당을 언급할 때마다 등장하는 곳. 웨이팅을 피하기 위해 오픈 30분 전부터 미리 와있었다. 다행히 3번째 정도로 입장 성공.- 크레이지 돈맥세트를 주문했더니, 이곳의 대표메뉴인 특로스가츠를 비롯해, 로스가스/히레가스/새우튀김/고로케가 골고루 나왔다. 시원한 생맥주랑 잘 어울리는 조합이었다.- 특로스가츠는 그 유명세만큼 실망시키지 않는 맛이었다. 사실 일반 로스가스도 충분히 맛있어서, 가격대가 부담스럽다면 일반으로 주문해도 문제 없다.- 웨이팅이 많은 것도 불편하고, 내부 테이블이 미로처럼 되어있어 앉기도 불편한 건 단점. 주차할 곳 없는 것도 불편하다..- 가격대도 조금 높은 편이지만, 맛만 생각하면, 돈가스 성애자라면 한번쯤은 방문해봐야 할 곳이다. 하지만 개인적으로는 정돈이 더 만족스러웠다..!, 번역: ◈ Restaurant record #1 'Crazy Katsu' (4. 0 /5 points) It appears every time you mention the three major pork cutlet restaurants in Korea.It has been previewed 30 minutes before opening to avoid waiting.Fortunately, entering the third time.When I ordered a crazy pon Mac set, I had a special menu, a special menu, and a Los Gas/Hiregas/Shrimp French/Gorogke.It was a combination that goes well with cool draft beer.The well -known roses were not as disappointed as the famous world.In fact, regular roosth gas is also delicious, so if the price is burdensome, it is not a problem to order general.It is inconvenient to have a lot of weight, and the interior table is like a maze.There is no place to park..The price is a bit high, but if you think about the taste, if you are a pork cutlet, you should visit at least once.But personally, the tidy was more satisfying..!

 94%|█████████▍| 21025/22421 [05:49<05:17,  4.40it/s]

원본: 너무 기대를 하고 가서 그런지 생각만큼 그렇게 맛있다고 말하기가 좀 그렇습니다.맛이 없는것은 아니지만 1시간 웨이팅해서까지 먹을 정도는 아닌거 같습니다.로스카츠를 먹었는데 살짝 오버쿡 된 느낌이 듭니다. 주말이라 사람이 많아서 그런건지 원래 그런건지는 모르겠지만 다음에 평일에 와서 히레카츠를 한번 먹어보고나서 재방문은 다시 생각해봐야겠습니다., 번역: It's so delicious as I think it's so delicious.It's not tasteless, but it's not enough to eat for an hour.I ate Roscatsu and it feels slightly overcooked.I don't know if it's because there are a lot of people because it's a weekend, but I'll come to the next weekday, try Hirecatsu, and then think about it again.

 94%|█████████▍| 21026/22421 [05:50<05:18,  4.38it/s]

원본: 이름 그대로 미친 카츠를 먹어볼 수 있다. 특 로스 카츠를 꼭 먹어보고 대기시간이 기니 가급적 평일에 시간내서 먹는걸 추천한다., 번역: As the name suggests, you can eat crazy Katsu.It is recommended to eat special Los Katsu and eat it on weekdays.

 94%|█████████▍| 21027/22421 [05:50<05:21,  4.34it/s]

원본: 합정에서 인기를 끌고있는 일본식 돈까스집입니다. 혼밥하러 갔는데 일찍 가도 웨이팅이 있었어요. 웨이팅 없으면 여유로운 마음으로 즐겼을텐데, 인기 많은 가게에서 밥 먹기 힘드네요ㅠㅠ 특로스카츠는 준비 수량이 적은 건지..?늦게 가면 못먹을지도 몰라요.  소금 찍어먹는 것도 맛있습니다. 그리고 겨자도 좋아요. 하지만 와사비도 같이 주셨으면 더 좋을 것 같네요. 그리고 같이 나오는 사이드메뉴가 다양하지 않아서 어쩔 수 없이 연남동의 ㄷㄹㅋㅊ와 비교가 됩니다. 둘 중엔 ㄷㄹㅋㅊ가 더 낫네요.. 그래서 다시 가고싶다는 생각이 강하게 들지는 않지만 역시 평가에서 가장 중요한 요소는 맛이겠지요. 맛있게 먹었기 때문에 별 네개! 양은 과하게 배부르지도 않고 그렇다고 적지도 않고 적당했습니다., 번역: It is a Japanese pork cutlet restaurant that is popular in Hapjeong.I went to Honbab and I had a waiting even if I went early.If you don't wait, you would have enjoyed it with a leisurely heart, but it's hard to eat at a popular shop..? If you go late, you may not eat.It is also delicious to eat salt.And mustard is also good.But it would be better if you were giving wasabi together.And the side menus that come together are not varied, so it is inevitably compared to the ㄷㄹ ㅋㅊ of Yeonnam -dong.One of them is better..So I don't think I want to go back, but the most important factor in the evaluation is taste.Four stars because they ate deliciously!The amount was not too full, but it was not good.

 94%|█████████▍| 21028/22421 [05:50<05:15,  4.41it/s]

원본: 두꺼운 돈까스가 너무 좋았습니다.살짝 와사비를 얹어서, 소금에 찍어먹는 맛은 최고네요.  특로스카츠 먹고 싶었는데, 점심 일찍 와야 먹을 수 있나봐요 ㅠㅠ...다음엔 또 와야겠어요!, 번역: The thick pork cutlet was so good.The tastes of water are the best to put on the wasabi.I wanted to eat Scatsu as a special, but I must come early for lunch...I'll come again next time!

 94%|█████████▍| 21029/22421 [05:50<05:12,  4.45it/s]

원본: 7시반쯤 갔는데 이미 특로스는 매진로스랑 히레 먹어봤는데 로스는 그냥 무난했고 히레는 맛있었음튀김옷이 얇고 육즙이 살아있다특히 샐러드드레싱이 존맛평일이었음에도 불구하고 8시20분쯤 재료소진으로 라스트오더 치던데 주말에는 더더욱 낮시간 아니면 온전히 먹기 힘들 것 같음, 번역: I went around 7:30, but I had already eaten the soldiers and Hire, but the Ross was just good, and the Hire was delicious. The fried clothes were thin and juicy.It seems to be hard to eat even more during the weekend or even more daytime.

 94%|█████████▍| 21030/22421 [05:51<05:14,  4.42it/s]

원본: 일본 정통 느낌의 돈가츠 입니다. 골목길에 숨어있는 좀 좁다 싶을 정도로 작은 가게입니다만, 두툼한 돈가츠를 소금에 찍어 먹는 맛이 꽤 좋습니다. 가격대는 일인당 만원대 생각하시면 충분히 드실듯 합니다. 살짝 부담스럽긴 하지만, 그래도 추천합니다., 번역: This is a Japanese authentic porkstone.It's a small shop that wants to be a bit narrow in the alley, but it's pretty good to eat thick pork stones in salt.The price range seems to be enough if you think about 10,000 won per person.It's a bit burdensome, but it's still recommended.

 94%|█████████▍| 21031/22421 [05:51<05:28,  4.23it/s]

원본: 돈까스를 좋아해서 유명맛집을 여기저기 다녀보는데 개인적으론 그저 그랬습니다 다만 치즈 퐁듀가 특색있고 맛있었어요, 번역: I like pork cutlet, so I went to a famous restaurant here and there, but I personally did it.

 94%|█████████▍| 21032/22421 [05:51<05:26,  4.26it/s]

원본: 돈까스 맛집 고기질이 다르다 그러나 가격대비 그렇게 맛잇다고는 생각치 않는다, 번역: The pork cutlet restaurant is different, but I don't think it's so good for the price.

 94%|█████████▍| 21033/22421 [05:51<05:29,  4.21it/s]

원본: 돈까스가 굉장히 맛있습니다 지방이 많아서 느끼할 수 있지만 와사비와 소금을 같이 먹으면 괜찮습니다, 번역: The pork cutlet is very delicious. It can be felt because it has a lot of fat, but it is okay to eat wasabi and salt together

 94%|█████████▍| 21034/22421 [05:52<05:34,  4.14it/s]

원본: 합정에 위치한 존맛탱 돈카츠 맛집! 크레이지카츠! 돈까스와 돈카츠의 차이를 보여주는 집!, 번역: John Tang Ton Katsu Restaurant located in Hapjeong!Crazy Katsu!A house that shows the difference between pork cutlet and pork katsu!

 94%|█████████▍| 21035/22421 [05:52<05:27,  4.23it/s]

원본: 여기저기 매스컴 타서 인기폭발중인 돈까스집웨이팅 몇시간은 기본이고 못 먹을때도 있음합정에 이 이상 돈까스집은 없을듯맛있음 확실히, 번역: The pork cutlet house, which is being popular here and there, is basic and sometimes not eaten.

 94%|█████████▍| 21036/22421 [05:52<06:34,  3.51it/s]

원본: 진짜 장난아니게맛있습니다 운좋게 특 로스가츠정식 먹었는데 너무 맛있었습니다, 번역: It's not really a joke, so I was lucky to eat special Ross Gatsu, but it was so delicious.

 94%|█████████▍| 21037/22421 [05:52<06:26,  3.58it/s]

원본: 지금까지 먹어본 돈까스집 중 맛있는 집이었다. 푸짐해서도 만족. 대기줄있음., 번역: It was a delicious house of the pork cutlet.Satisfied with rich.There is a waiting line.

 94%|█████████▍| 21038/22421 [05:53<06:17,  3.67it/s]

원본: 정돈 하위호환 같았음덜 맛있는 대신 더 싸다돈까스 괜찮음, 번역: It was like compatibility with the subordinates.

 94%|█████████▍| 21039/22421 [05:53<05:58,  3.86it/s]

원본: 최고에요..👍 돈까스는 여기가 최고, 번역: It's the best..👍 Pork cutlet is the best here

 94%|█████████▍| 21040/22421 [05:53<05:48,  3.96it/s]

원본: 구석탱이에 자리잡은 돈가츠의 참 맛.보기에는 여느 돈가츠와 다를게 없지만 맛보면 상상을 초월한다., 번역: The true taste of porksticks in the corner.It is no different from any other moneygatsu, but it is beyond imagination.

 94%|█████████▍| 21042/22421 [05:53<04:14,  5.41it/s]

원본: 진짜 맛있고 정성이 담겨있어요! 이국적인 느낌이 들고 테이블도 넓어서 커피한잔까지 하고 나오면 너무 좋은 곳입니다~ 롯데타워 쇼핑하기전에 배띵띵~~, 번역: It's really delicious and sincerity!It feels exotic and the table is wide, so it's a good place to have a cup of coffee.

 94%|█████████▍| 21043/22421 [05:54<04:32,  5.06it/s]

원본: 롯데월드몰 지하에 위치한 음식점임 맛있고 분위기 좋았음 넓은 공간이 좋았음, 번역: It was a restaurant located in the basement of Lotte World Mall.

 94%|█████████▍| 21045/22421 [05:56<12:22,  1.85it/s]

원본: 사과쥬스 별로에요 가격은 턱없이 비싼듯 안이 좋아보여서 들어왔는데 자리를 안내해주네요 저쪽에 앉으라고  앉고싶은데 막 못앉나봐요, 번역: Apple juice is not very good.
원본: 롯데월드몰 지하에 위치한 넓은 규모의 고급스러운 레스토랑. 깔끔하고 유럽 느낌의 인테리어로 꾸며져 있습니다.음식은 전반적으로 짜지않고 조금 싱거운 스타일이었어요. 조개때문에 원래 봉골레가 짠 편인데 짜지 않았고 생면이 조금 덜익은? 스타일로 나왔습니다. 리조또는 쌀이 좀 많이 늘러붙어서 아쉬웠어요. 죽 되기 전 단계같은 식감이었습니다. 맛이나 양에 비해 가격대는 좀 있는 편이에요.롯데월드몰 특성상 주차지원 안됩니다. 화장실은 롯데월드몰 지하에 있고 레스토랑에서 3분정도 거리에 있습니다., 번역: A large -scale luxurious restaurant located in the basement of Lotte World Mall.It is decorated with a clean and European interior.The food was not squeezed overall and was a bit fresh.The original Bonggol is woven because of the shellfish, but it wasn't salty.It came out in style.It was a pity that risoto or rice stuck a lot.It was the same texture before dying.There is a price range compared to the taste or amount.Parking support is not due to the nature of Lotte World Mall.The toilet is in the basement of Lotte World Mall and is about 3 minutes from the restaurant.

 94%|█████████▍| 21047/22421 [05:56<08:08,  2.82it/s]

원본: 분위기, 위생상태 좋아요 직원분도 친절하시고 음식도 맛있어요 :), 번역: The atmosphere and hygiene is good. The staff are friendly and the food is delicious :)
원본: 롯데월드몰 주변에 갈일이 있어 들렀는데 가격대가 좀 있긴 하지만 메뉴들 다 맛있었어요. 이국적인 음식을 즐길 수 있단 점에서 좀더 맘에 들었어요, 번역: I stopped by the Lotte World Mall, but there was a price range, but the menus were delicious.I liked it more because I can enjoy exotic foods.

 94%|█████████▍| 21049/22421 [05:57<06:02,  3.79it/s]

원본: 맛있어요 ㅎㅎ메뉴판은 남들이 안찍는 드링크메뉴판 청부함돠, 번역: It's delicious ㅎㅎ The menu is a drink menu board that is not taken by others
원본: 메뉴선택이 별로였는지 가격대비 그닥..피자 평소에 좋아하는데 느끼했음 풀떼기도 막 얹어놔서 먹기 불편, 번역: The price of the menu was not good..Pizza usually likes it, but I felt it.

 94%|█████████▍| 21050/22421 [05:57<05:21,  4.26it/s]

원본: 로봇이랑 사람이 같이 서빙하는 신기한 식당. 그러나 알리오올리오 면이 불어있고 맛이없다, 번역: A wonderful restaurant where robots and people serve together.However, the Alio Olio is blew and it is not delicious

 94%|█████████▍| 21052/22421 [05:57<04:45,  4.79it/s]

원본: 넓은 공간에서 다양한 디저트류를 분위기있게 즐길 수 있는 곳, 번역: A place where you can enjoy a variety of desserts in a large space
원본: 런치 메뉴 가성비 좋았는데갈수록 맛이 없어지네요아쉬워요, 번역: The lunch menu was good, but it's getting more and more tastes.

 94%|█████████▍| 21054/22421 [05:57<04:23,  5.18it/s]

원본: 지하1층 매장은 만족스러우나. . .31층 푸드코트는 31층 분위기에 맞지않는서비스로. . 매우.불쾌하네요. . 그럴꺼면 매장 철수 하시죠. . .ㅡ 냅킨 은 없나요?      >없어요. ㅡ 그럼 먹을때 어떡해요. .ㅡ.ㅡ?      >그러면 저기 퇴식구 가서 가져가세요. .ㅡ 음식이 남았는데. . .투고박스없어요?     >여기는 투고 박스 없어요.ㅡ 그래도 좀 많이 남 았는데. . .     > 없어요.(인상을 직접 보셔야)ㅡ . . . . 어떡하지 자리로옴     >뒤에다. . 여기는.푸드코트예요.헐! . . .     비추입니다.., 번역: The first basement store is satisfactory...The 31st floor food court is a service that does not fit the 31st floor atmosphere..very.It's unpleasant..If so, please withdraw the store...ㅡ Is there any napkin?> No.ㅡ Then what do you do when you eat?.ㅡ.ㅡ?> Then go there and take it..ㅡ Food is left...Do you have any submission boxes?> There is no submission box here.ㅡ Still a lot left...> No.(Look at the impression) ㅡ....What should I do?.here is.It's a food court.omg!...It is light..
원본: 자리서비스도 시끄러운 자리 배정받고 음식이 가격대비 너무 아마추어적인 맛과 비쥬얼이라 먹는 내내 별로였네요그냥 집에서 전자렌지 돌린 음식 모양과 맛, 번역: The place service was also loud and the food was too amateur for the price.

 94%|█████████▍| 21056/22421 [05:58<04:19,  5.27it/s]

원본: 매장이 월드몰 지하에 있고 넓고 늘 손님이 많아서인지 소란스러운 분위기입니다. 식사보다는 디저트 먹으러 갑니다., 번역: The store is in the basement of the World Mall and is wide and there are always many guests.I go to eat desserts rather than meals.
원본: 롯데몰 지하에 있어서 좋구 색다른 음식 먹고 싶을때 오면 좋을거 같아요. 친구들이랑 자주 가봐야겠어요, 번역: It's good to be in the basement of Lotte Mall.I have to go often with my friends

 94%|█████████▍| 21058/22421 [05:58<04:08,  5.48it/s]

원본: 가성비는 정말 롯데월드몰 내부 입점 식당이고 이탈리안인걸 고려하고라도 양이 너무 없음분위기 빼고는 맛도 뛰어난 점은 없음..., 번역: The price is really a restaurant inside Lotte World Mall and it is an Italian...
원본: 분위기는 좋으나 생각보다는 실망함파스타 스테이크 수제버거를 먹었는데스테이크는 가격을 고려한다면 준수한편파스타와 수제버거는 맛있음, 번역: The atmosphere is good, but I ate a disappointing Hampasta steak homemade burger than I thought.

 94%|█████████▍| 21061/22421 [05:58<03:00,  7.54it/s]

원본: 신정동 동네 빵집. 근데 퀄리티는 동네 빵집 수준이 아니다. 맛있는 빵들 너무 많다., 번역: Sinjeong -dong neighborhood bakery.But quality is not the level of local bakery.Too many delicious breads.
원본: 가격이 괜찮은 편이고, 친절하세요. 가게 내부도 깔끔하고 대화나누면서 식사하기 괜찮아요!, 번역: The price is decent and kind.The inside of the store is clean and it's okay to eat while talking!

 94%|█████████▍| 21063/22421 [06:00<06:38,  3.41it/s]

원본: 사진보고 간거여서 빠네, 간장소스오징어비빔밥..?, 미트볼&감자튀김 시켰는데 빠네로 흘러넘치는 면 양 을 보고 감탄했는데 빠네 빵을 덜 파서 그 위로 면들이 흐르는거였고 소스가 부족했습니다 그리고 오징어는.. 솔직히 말해서 정말 모를 다리 부분이 씹기 힘들게 질겼고 싱거웠습니다 근데 감자튀김&미트볼 진짜 맛있었어요 다음에 갈땐 날이 좀 풀렸을때 가서 야외에서 감튀에미트볼 맥주 시켜서 간단하게 먹고오려구요 그리고 가격이 안착해용, 번역: I went to see the picture, so I couldn't see it..?, Meatball & French fries, but I admired the amount of noodles flowing to Pane, but it was less noodles on the noodles, and the sauce was lacking..Honestly, the legs that I don't know are hard to chew and it was fresh, but it was really delicious.
원본: 매장 청결하고 깔끔해요 메뉴가 저렴하진 않지만 퀄리티가 좋아요분위기도 좋아요 데이트 장소로 추천!, 번역: The store is clean and clean. The menu is not cheap, but the quality is also good.

 94%|█████████▍| 21065/22421 [06:00<05:20,  4.24it/s]

원본: 분위기가 좋았지만 가격이 너무 비쌌다 다음번엔 안갈 것 같다, 번역: The atmosphere was good, but the price was too expensive.
원본: 빠네가 맛있고 오징어는 짜르기 귀찮아요올라가는 길을 찾기 어렵습니다. 잘 찾아가세요, 번역: Pane is delicious and squid is bothersome to be squeezed.Go well

 94%|█████████▍| 21067/22421 [06:00<04:34,  4.93it/s]

원본: 숙성된 목살은 부드러웠고이겹살은 고소한 맛이 별미 된장술밥은 밋밋해서 아쉬웠다 큰 감흥은 없었고, 그렇다고 많이 아쉬운 점은 없었는데 특별히 고기 생각이 나서 이곳을 다시 와서 먹고 싶다는 생각은 들지 않는다, 번역: The aged neck was soft, and the pork belly was so savory that the so -called miso sulbab was unfortunate. There was no great inspiration.
원본: 1회 방문. 고기 질이 정말 좋고 하얀살은 별미였다. 된장라면이 기대 이상으로 맛있었다., 번역: One visit.The meat quality was really good and the white meat was a delicacy.Doenjang ramen was more delicious than expected.

 94%|█████████▍| 21070/22421 [06:01<03:17,  6.84it/s]

원본: 대존맛!! 특히 이집에서만 판매하는 하얀살은 쫀득한 식감이 짱 맛있음, 번역: Subsequent taste!!In particular, the white meat, which is sold only in this house, has a good texture.
원본: 코로나 때문에 가게에 손님이 우리 밖에 없었음ㅠㅠ 이대앞이라 특히 학기가 아직 시작하지 못한 상황 때문에 손님이 더더욱 없었음ㅠ 주인아저씨가 친절했어서 너무 안타까웠음아라비아따 파스타 양념이 살짝 강했지만 맛있다.시카고 피자는 보통 사이즈가 커서, 여자 둘이 가면 비싸게 주고 시켜서 남기게 되는 경우가 많은데뽀모도로의 경우에는 2인용 스몰 피자가 있어서 먹는 양에 맞게 시키고 소비할 수 있는 장점이 있음.스몰 피자도 천원 추가하면 반반피자로 먹을 수 있음.피자 크러스트 부분에 뿌려먹을 수 있도록 딸기쨈 제공되는데 뿌려 먹어보는 것을 추천함.피클이랑 할라피뇨는 셀프임., 번역: There was only guests in the store because of Corona.Chicago pizza is usually large, so when two women go, they often leave them expensive and leave them. In the case of Pomodoro, they have two -person small pizza to suit the amount they eat.If you add a thousand won, you can eat it with half a pizza.Strawberry is provided so that you can eat it on the pizza crust.Pickle and Jalapiño are self.

 94%|█████████▍| 21072/22421 [06:01<03:30,  6.41it/s]

원본: 가성비가 정말 좋아요 이제까지 먹은 피자나 파스타 가게들 중 제일 저렴하고 맛도 있었던 것 같아요! 재방문하고싶은 집이고, 직원분들도 너무 친절하셔서 기분 좋았습니다, 번역: The price is really good.I wanted to return to visit, and the staff was so kind that I felt good
원본: 매장은 크고 깨끗하고 항상 음식은 맛있어요! ㅠㅠㅠ 특히 치즈가 아낌없이 많이 넣어주시는 느낌이라 처음에 받고 가격에 비해 사이즈가 작아서 놀랄 수 있지만 은근 배차고 맛있어요... 파스타도 생면이라 식감이 좋고, 맛이 깊고 풍부해요! 마늘맛이 가득해서 좋았는데 집에서 해먹으니 저런 맛이 절대 안나더라구요... 데이트나 외식 장소로 추천합니다, 번역: The store is big and clean and the food is always delicious!ㅠㅠㅠ especially the cheese feels generously, so it can be surprised because it is smaller than the price at first and is small...Pasta is also raw noodles, so the texture is good, tastes deep and rich!It was good because it tasted like garlic, but it didn't taste like that...Recommended for dating or eating out

 94%|█████████▍| 21074/22421 [06:01<03:44,  6.01it/s]

원본: 학교 앞 식당 중에서 제 기준 맛있는 집입니다 가격대가 있어서 자주는 안가지만 시카고피자 진짜 맛있어요! 분위기도 시끌벅적하지 않고 조용해서 친구랑 얘기하며 여유롭게 먹을 수 있습니다! 사장님이 남자이신데 항상 친절하셔서 기억에 남습니다~~! 학교 앞 피자집으로 추천합니다, 번역: This is a delicious house among the restaurants in front of the school.The atmosphere is not noisy and quiet, so you can talk to your friend and eat relaxed!The boss is a man, but I always be kind and remember it ~~!Recommended as a pizza in front of school
원본: 피자는 전반적으로 좀크기가많이 작아서 놀랬어요 파스타도맛잇는데 전반적으로 양이조금 부족해서 아쉬워요, 번역: The pizza was a bit small overall, so I was surprised.

 94%|█████████▍| 21075/22421 [06:02<03:47,  5.92it/s]

원본: 이집은 피자맛집이기도 하지만 파스타 맛집임. 생면으로 파스타 내주는 집이 요즘 흔치 않은데 정말 맛있었음! 피자도 도우가 일반적이지 않지만, 사장님의 내공이 느껴지고요. 파스타 강추(생면+오일소스) 피자도 추천. 이대 학생분들은 좋겠네요!, 번역: This house is also a pizza restaurant, but it is a pasta restaurant.It is rare these days, but it was really delicious!Pizza is not common, but I feel the boss's inner.Pasta recommendation (raw noodles+oil sauce) pizza is also recommended.It would be nice for this university student!
원본: 사장님이 굉장히 친절하셔서 들어가기만 해도 기분이 좋다음식은 시카고피자라 평타는 치며인테리어가 약간 촌스럽지만 또 그런대로 괜찮다, 번역: The boss is very kind and feels good to go in, and the meal is a chica gopija.

 94%|█████████▍| 21077/22421 [06:02<03:55,  5.71it/s]

원본: 가성비 좋은듯하나 먹다보면 가격 좀 나와요. 탕위주로 소주1잔하기는 편할듯 합다. 사람이 많아 붐비고 주문할때 벨을 누르는데 손님이 많다보니 신속대응은 좀 어려운듯 합니다.편하게 1잔 하기는 좋은듯 합니다.메뉴선정 잘 하시고,예산안에서 맛있는 식사하려면 메뉴 선정 잘 하시면 됩니다., 번역: If you eat one like a good price, it comes out.It seems to be easy to drink 1 soju with a hot water.There are so many people, and when you order, there are a lot of customers to press the bell.It seems good to have one glass.You can select the menu well, and if you want to eat delicious meals in the budget, you can select the menu well.

 94%|█████████▍| 21079/22421 [06:02<03:50,  5.83it/s]

원본: 노량진 맛집 노량해전은 노량진역 먹자골목에서 회가 광어, 우럭 등 회를 만원부터 먹을수 있는 유일한 노량진 횟집이에요. 노량진 횟집 중에서 유일하게 주차장이 있는 곳이고 비브리오 없이 신선도 높은 회를 제공하기 위해서 uv해수살균기를 설치했으며 노량진 맛집 유일하게 단독룸 여러개를 보유해서 예약이 가능한 횟집이에요. 특히 위생에 좋지 않은 회를 주문할때 회 밑에 깔아주는 천사채 대신에 깔끔하고 차가운 정수된 얼음으로 만든 얼음위에 회가 올라가져서 처음부터 마지막순간까지 신선도 높은 쫄깃하고 담백한 회를 먹을수가 있다. 4명이 푸짐하게 땀을 흘리며 먹기 좋은 매콤한 해물찜과 여름철 보양식으로 많이들 먹는 보양물회와 모든 매운탕중에서 가장 쫄깃한 식감을 자랑하는 생우럭탕이 인기가 높고 겨울철에는 고소하고 담백한 대방어와 새우튀김이 인기가 높다., 번역: Noryangjin Restaurant Noryanghaejeon is the only Noryangjin sashimi restaurant where you can eat sashimi such as flounder and rockfish in the alley of Noryangjin Station.It is the only parking lot among Noryangjin sashimi restaurants, and we have a UV seawater sterilizer to provide fresh sashimi without vibrio.In particular, when ordering a sashimi that is not hygienic, the sashimi is climbed on the ice made of clean and cold purified ice instead of the angelic bonds that are laid under the sashimi, so you can eat fresh and light sashimi from the beginning to the last minute.Four people sweat and eat spicy seafood steamed and summer food sashimi, and the most chewy texture of all Maeuntang is popular, and in winter,High.
원본: 노량진 구석에 위치한 횟집인데 가성비 최고이고 맛은 이루말할 것 없습니다.술은 어찌나 잘 들어가던지 다코에 올리려고 다른 사진 찍어야지 했다가 이미 다 먹고 마셔버려서 남은건 빈 그릇뿐이더군요...다만 평일에 갔는데도 웨이팅할만큼 주변 직장인들과 주민들이 많이 찾습니다..., 번역: It is a sushi restaurant located in the corner of Noryangjin.I had to take a different picture to get in Tako, but I had to eat and drink all the empty bowls...However, even though I went on weekdays, there are many workers and residents around them...

 94%|█████████▍| 21081/22421 [06:03<03:50,  5.81it/s]

원본: 물회(1인) 주문하면서 소면 추가해서 섞어 먹었는데, 왜 물회 맛집인지 알겠더라구요. 어떤 식당은 그냥 초고추장같은 소스를 쓰는곳도 있는데 여기는 사과를 갈아넣은것 같은 새콤달콤함이 있어요. 앞으로 서울에서 물회 먹고싶으면 여기 생각날것같습니다, 번역: I ordered a water sashimi (one person) and added a noodles and mixed it.Some restaurants are just a sauce like a red pepper paste, and there's a sour and sourness that seems to have changed the apples.If you want to eat water sashimi in Seoul, I think you will think of it here.
원본: 노량진에서 수산시장에서 안먹고 항상 여기에서 먹습니다갑각류를 제외하고 여기가 짱이에요, 번역: Noryangjin is not eaten in the fish market and always eats here.

 94%|█████████▍| 21083/22421 [06:03<03:54,  5.72it/s]

원본: 광어 중자 20,000원 ㅋㅋㅋㅋㅋㅋㅋ 대박 놀랏어요 맛도 좋고 가성비 오집니다 그런만큼 사람이 많아요 ㅠㅠ, 번역: The flatfish middle 20,000 won ㅋㅋㅋ ㅋㅋㅋ I'm surprised. The taste is good and the price is good.
원본: *재방문의사80%잠실의 위치 좋은 곳에 위치한 도쿄등심.한우의 맛있음이야 말해 모하냐만도쿄등심만의 좋은 원육과숙성노하우 그리고 여러 시행착오를겪었을듯한 소스류들 까지완벽한 맛의 조화를 선사했던도쿄등심의 한우.특히 트러플오일이 들어간 소스는최고 엄지척이었음.마무리 성게미역국과 밥 한그릇 까지뭐하나 흠잡을 곳 없이 맛있었음."최상급 한우와 사이드디쉬의 조화가 매우좋음.", 번역: Tokyo sirloin is located in a good location of Jamsil 80%.It is the delicious Korean beef of Dokyo Sirloin, which provides a perfect flavor of Mohango Mando Sirloin's good sirloin and ripening no -how and sauces that seem to have experienced various trials and errors.In particular, the sauce with truffle oil was the best thumb.Finishing the sake of sogae -mi station and a bowl of rice were delicious without any flaw..The harmony between the best Korean beef and Sidedish is very good..

 94%|█████████▍| 21086/22421 [06:03<03:01,  7.37it/s]

원본: 식당 분위기는 기념일이나 데이트 장소로 적당할 정도로 깔끔합니다. 전반적으로 음식들의 가격은 비싸나 각 요리들의 맛이 상당히 퀄리티있고 맛있습니다. 코스 요리를 시키는 것이 좋아보이며 메인 요리인 소고기는 상당히 부드럽고 맛도 일품입니다. 고기는 직원이 직접 구워주는데 서비스도 좋습니다., 번역: The restaurant atmosphere is neat enough to be an anniversary or date.Overall, the price of food is expensive, but the taste of each dish is quite quality and delicious.It looks good to have a course dish, and the main dish, beef, is quite soft and tastes good.The meat is baked by the staff, but the service is also good.
원본: 고기 질이 좋습니다. 코스로 나오는 음식이 대체로 맛있지만 연어는 별로네요. 고기는 짱♡, 번역: Meat quality is good.The food from the course is usually delicious, but the salmon is not good.The meat is awesome ♡

 94%|█████████▍| 21088/22421 [06:04<03:25,  6.49it/s]

원본: 생일날 친구랑 방문한 도쿄등심 잠실점~ 인터넷에서 찾아보고 갔는데 생각보다 크고 분위기가 좋아요~ 우리가 원하는 템포로 고기도 구워주시고 ~ 처음 가보는 곳이였는데 맛집 찾은기분이에요~!!ㅋㅋ엄마,아빠 모시고 한번 더 갈려고 예약까지 하고 왔어요~ 굿굿????, 번역: I visited Tokyo Sirloin Jamsil Branch with my friend on my birthday ~ I went to the internet and it was bigger and better than I thought.!ㅋㅋ Mom and dad have been reserved to go once more ~ Good good ????
원본: 2월까지 이벤트하길래 방문함...늦은점심시간이고 일요일인데 사람이꽤있었다. 직원을은 여전히 친절하다, 번역: I visited the event until February...It's late lunch time and Sunday.The staff are still kind

 94%|█████████▍| 21089/22421 [06:04<03:32,  6.26it/s]

원본: 살치살 넘나 맛있는 것! 매우 친절해요 따로 독립적인 룸은 없지만 다른 지점보다 더 친절해서 좋았어요, 번역: It's beyond the flesh!It's very kind. There's no independent room, but it was better than other points.

 94%|█████████▍| 21090/22421 [06:05<10:06,  2.20it/s]

원본: 오랜만에 친구가 맛집 방문한우와 연어가 한자리에 모여있다는 ~위치도 역이랑 가깝고 ~젊은 직원들의 패기와 열정을 볼수있다는~마지막에 나오는차돌 된장찌개로 마무리 ~너무 잘먹고 왔어용용, 번역: It's been a long time since my friend visits the restaurant and the salmon is gathered in one place. The location is close to the station.

 94%|█████████▍| 21091/22421 [06:06<13:44,  1.61it/s]

원본: 도쿄등심 본점이라 기대했지만 실망스러웠다. 인테리어도 다른 곳보다 못했고 바닥이 미끄러웠다. 음식도 반찬은 미리 담아 두어 식당밥집보다 못해 컨셉까지 해친 것 같고 그렇다고 고기가 월등하지도 않았다., 번역: I expected it to be the headquarters of Tokyo, but I was disappointed.The interior was worse than anywhere else and the floor was slippery.The food and side dishes were put in advance, so they seemed to hurt the concept because they were less than the restaurant restaurant, and the meat was not superior.

 94%|█████████▍| 21092/22421 [06:06<11:21,  1.95it/s]

원본: 지난주말친구들과운동후에찾은도쿄등심! 소문대로친절한직원분들의서비스와훌륭한음식맛에흠뻑취하고왔습니다. 부드러운연어사시미와새우고로케는 정말일품이였어요~^^ 한우고기의육질도최상급이였어요~잠실에오시면꼭한번가봐야할맛집이였습니다!:)), 번역: Last week, Tokyo sirloin after exercise with friends!As rumors, the service of the friendly staff has been flawed in the taste and the excellent food.The soft salmon sashimi and the new rocket were really excellent.:))

 94%|█████████▍| 21093/22421 [06:06<09:32,  2.32it/s]

원본: 남자친구랑 기념일 이라서 갔었는데 창가쪽으로 좌석 지정도 해주시고 와인도 서비스로 주셨어요^^ 서버분께서 고기를 전부 알맞은 굽기로 구워주시고 직원분들이 너무 다 친절해서 기분좋은 식사하고 왔습니다:D, 번역: I went to the anniversary with my boyfriend, but I designated a seat toward the window and gave me the wine as a service.

 94%|█████████▍| 21094/22421 [06:07<08:11,  2.70it/s]

원본: 잠실맛집이라해서 가족끼리 방문한곳~맛집이란 타이틀은 역시 괜히 붙는게 아니네요사이드로 나오는 연어는신선하고 고로케는 맛나고!!메인인 한우 구이도 굿! 직원들이다들친절하게 구워주시니 더욱더 맛도 좋고 가족끼리 이야기하며 편하게 먹고왔어요~, 번역: Jamsil restaurant is a place where the family visited ~ The title of restaurant is not sticky.!The main Korean beef grilled is good!Employees are kindly baked, so it tastes better and has been eating comfortably.

 94%|█████████▍| 21095/22421 [06:07<07:21,  3.00it/s]

원본: 직원들 옷차림부터 응대, 인테리어까지 고급스러움과 깔끔함을 지향하는 듯한 느낌을 받았습니다.고기의 질은 물론 직접 구워주기까지 하시니 고기 태워서 욕먹을 걱정없이 편하게 먹고 왔네요ㅎㅎ, 번역: I felt like I was aiming for luxury and neatness from employees to responding to the interior.I even grilled the meat as well as the quality of the meat.

 94%|█████████▍| 21096/22421 [06:07<06:50,  3.22it/s]

원본: 웨이팅이 긴 이유는 점원 한분 한분들이 직접 구워주시기 때문인듯합니다! 고급스럽고 점원들도 친절했어요맛은 있지만 이선 서비스 때문에 가격이 센편이라고 생각합니다!, 번역: The reason for the long waiting seems to be because each clerk bakes it myself!Luxurious and the clerks were kind, but I think the price is strong because of the two -line service!

 94%|█████████▍| 21097/22421 [06:07<06:25,  3.43it/s]

원본: 디너세트로 스키야키를 주문했는데 약간 국물이 많아 샤브샤브 느낌이다. 세트로 먹기에 적당하고 맛도 괜찮음연령관계없이 즐기기 좋음, 번역: I ordered Sukiyaki with a dinner set, and it has a little broth and it feels like a shabu -shabu.It is suitable for eating with a set and good taste. It is good to enjoy regardless of age

 94%|█████████▍| 21098/22421 [06:08<06:12,  3.55it/s]

원본: 매장분위기가 너무좋아요 딱제스타일ㅎ 한우라서 그런지 너무부드럽고 연어또한 완전 맛있었어요고로케도 나왔는데 그냥 한입 먹는순간 새우와 크림이 입안에서 너무 살살녹았어요~잘먹고 갑니다, 번역: The atmosphere of the store is so good.

 94%|█████████▍| 21099/22421 [06:08<05:48,  3.79it/s]

원본: 데이트 모임 다 적합한듯 캐주얼함일단 친절해서좋음 구워주니편하고접근성만족 주차도 롯데캐슬안이라 편했음콜키지프리라와인들고가면 딱임판매하는와인들도 저렴하긴함, 번역: Date meetings are suitable for casual.

 94%|█████████▍| 21100/22421 [06:08<05:47,  3.81it/s]

원본: 한우 꽃등심이랑 연어를 같이 파는집인데, 제가 두가지 다 엄청 좋아해요 ㅎㅎ 재료가 너무 신선해서 그냥 별조리없이 맛있는것같아요, 번역: It's a house that sells Korean beef sirloin and salmon together, and I really like both things ㅎㅎ The ingredients are so fresh that I think it's delicious

 94%|█████████▍| 21101/22421 [06:08<05:33,  3.96it/s]

원본: 가족들이랑 먹으러 왔는데 너무 맛있고 좋네요! 음식도 예쁘게 잘 나와서 보는 맛도 쏠쏠하네요 ㅎㅎ직원분들도 다 굉장히 친절하게 서비스해주시고 고기도 직접 구워주셔서 좋았어요! 재방문 의사100%입니다! 안가보신분 계시다면 완전 추천드립니다!, 번역: I came to eat with my family and it's so delicious and good!The food came out so well that it tastes so good.100%doctor!If you haven't been there, I recommend it!

 94%|█████████▍| 21102/22421 [06:09<05:40,  3.88it/s]

원본: 고기가 진짜 맛있어요. 비싼 값하는듯! 또 오고 싶어요., 번역: The meat is really delicious.It seems expensive!I want to come again.

 94%|█████████▍| 21103/22421 [06:09<05:21,  4.10it/s]

원본: 예전부터 가야지가야지 하다 못갔던 도쿄등심을 드디어!!여자친구와 함께 방문했어요점심시간이라 사람들이 많더군요.근데도 주문한것도 금방나오고 직원들이 친절하고 고기까지 직접구워주시니 맘편하게 먹다 갑니다!역시 기대했던만큼 만족스러웠습니다!다음에 또방문하여 불고기전골도 먹어보고싶네요^^, 번역: I have to go to Tokyo sirloin that I have to go to before!!I visited with my girlfriend.But the order comes out soon, and the staff are friendly and bake the meat.I was as satisfied as expected!Next time, I want to try bulgogi hotpot next time.

 94%|█████████▍| 21104/22421 [06:09<05:17,  4.15it/s]

원본: 룸이 없는게 아주 조금 아쉽지만 조용한 자리가 있기에 걱정할 필요는 없을듯가격에 비해 양이 적다고 생각 할 사람도 있겠으나 1등급 꽃등심을 이 가격으로 먹을 수 있다면 다른 곳 볼 것 없이 여기만 이용해도 충분~!, 번역: It's a bit unfortunate that there is no room, but there is a quiet place, so you don't have to worry about it, but some people may think that the amount is small compared to the price, but if you can eat the first -class sirloin at this price, you can use it here without seeing it elsewhere!

 94%|█████████▍| 21105/22421 [06:09<05:14,  4.18it/s]

원본: 음식 맛은 보통. 가격은 조금 높은 듯. 서비스는 좋은편. 친절함.. 그러나 먹는중에도 둔촌동의 정육식당이 자꾸 머리속에 떠오름, 번역: Food taste is usually.The price seems to be a little higher.The service is good.kindness..However, even while eating, the meat restaurant in Dunchon -dong keeps coming up in the head

 94%|█████████▍| 21107/22421 [06:10<04:41,  4.67it/s]

원본: 완전 대박맛집이네요~^^ 고기도 적당히 잘 구워주시구음식 플레이팅도 이쁘게 해주시니 대충 찍어도 작품ㅎㅎ너무 맛있어요~~~~정말 한우와 연어의 만남이네요ㅎㅎ별다섯게 안아깝네요!!!, 번역: It's a great restaurant ~ Bake the meat well and the food plate is also pretty.!!
원본: 직접 구워주고 자세한설명도 해주는 서비스가 참 마음에 들엇습니다, 번역: I really liked the service that baked and provided detailed explanations.

 94%|█████████▍| 21109/22421 [06:10<04:20,  5.04it/s]

원본: 한우 고기집 중에서 최고인듯!! 바쁘면 밀리는 감도 있긴하지만 그래도 친철하면서 웃음이 있는 음식점은 유일무이하지 않을까 생각이 들어요^^, 번역: It seems to be the best in Hanwoo meat house!!If you are busy, you can be pushed, but I think it's the only restaurant with a friendly and laughter.
원본: 가게도 이쁘구 맛도 있음 ㅋㅋ 생각보다 이것저것 많이 나와서 배도부르고    친절해서 좋앗던듯 ㅋㅋ 고기질이 굿, 번역: The shop is also pretty and tastes.

 94%|█████████▍| 21110/22421 [06:10<04:11,  5.21it/s]

원본: 직원들이 친절해서 너무 좋았고고기도 주방보니까 직접 작업하시는거 같더라구요 그래서 안심하고 먹을수잇어요~, 번역: The staff were so nice and it was so good and the meat was also looking at the kitchen.

 94%|█████████▍| 21112/22421 [06:12<08:58,  2.43it/s]

원본: 맛도있고분위기도 정말좋고. 그중에 고기질이 상당히 좋더군요 가족과 즐거운시간보내고 기분좋게 나와서 너무 좋았습니다!, 번역: It tastes good and the atmosphere is really good.Among them, the meat was quite good.
원본: #잠실맛집 #도쿄등심입에서 살살 녹는  우연동점심식사로는  쵝오~^^!!, 번역: #Jamsil restaurant #Tokyo, etc.!

 94%|█████████▍| 21114/22421 [06:12<06:31,  3.34it/s]

원본: 특별한 날 약속잡기 좋은 곳이에요. 비싸긴 비싸지만ㅠㅠ, 번역: It's a good place to catch an appointment on a special day.It's expensive, but it's expensive.
원본: 잠실맛집 도쿄등심 고기도 맛있고 무엇보다 직원들이 엄청 친절하네요, 번역: Jamsil restaurant Tokyo sirloin meat is also delicious, and most of all, the staff are very kind.

 94%|█████████▍| 21116/22421 [06:12<05:07,  4.24it/s]

원본: 친구가 맛집이라고 해서 가봤는데 너무 맛있었고 직원분들이 너무 친절해서 감동이었습니다!! 번창하세요 ^^, 번역: I went to a friend because it was a restaurant, and it was so delicious and the staff was so kind!!Prosperously
원본: 부모님과 점심에 샤브샤브먹으로갔는데 완전 입에서 녹아요완전안가보신분들 점심 샤브샤브추천이욧!!, 번역: I went to the shabu -shabu for lunch with my parents, but I melted out of my mouth and did not go to Yoanjeon.!

 94%|█████████▍| 21120/22421 [06:13<02:41,  8.04it/s]

원본: 너무맛있는 도쿄등심  연어사시미^^, 번역: Tokyo sirloin salmon sashimi is so delicious
원본: 종로에서는 손가락에 꼽히는 집이다점심식사를 위해 여러번 가봤지만저녁시간에 꼬리찜과 뼈다귀는 처음이다물론 훌륭한 집이지만명성에 맞는 기대에는 조금 아쉬움이 있다..앞으로도 계속 가게 될 집이다, 번역: In Jongno, I have been to the finger's house for a house, but in the evening, the tail steamed and bones are the first to be a great house..It will continue to go in the future

 94%|█████████▍| 21122/22421 [06:13<03:07,  6.92it/s]

원본: 피카디리극장 바로옆에 위치한 70년전통 해장국 뼈다귀맛집이에요최근 가격인상이 있었지만 여전히 뼈다귀는 푸짐해요, 번역: This is a 70 -year -old Haejangguk bone daddy restaurant located right next to Piccadiri Theater.
원본: 재방률78%. 적당히 맛있다. 가끔 일부로 찾아도 갈 정도는 되는 것 같다. 특히 꼬리찜은 다른 곳과는 다르게 뚝베기 그릇에 쌓여서 나오는게 인상깊다. 먹오보지는 못 했지만.. 다음에 먹어볼 예정. 깍두기와 매우 잘 어울리는 탕이라 소주 안주로 더할 나위없이 좋다. 최근 가격이 오른 모양이라 아쉽지만 동네에서 곰탕이나 편육 땡길 때 한번씩 가볼만한 70년 전통의 집이다., 번역: Return rate 78%.Moderately delicious.Sometimes it seems to be enough to go.In particular, the tail steamed is impressive that it is piled up in a bowl of cutting unlike other places.I couldn't eat it..I will try next time.It's a very good match with Kakdugi, so it's good to add to the soju snacks.It's a pity that the price has risen recently, but it's a 70 -year -old house that you can visit once when you go to Gomtang or Cleans.

 94%|█████████▍| 21124/22421 [06:13<03:18,  6.54it/s]

원본: 인간적으로 정말 맛있습니다.해장국이 선지들어가고 그냥 그런 평범한건데김치가 맛있어서인지 양념장이 맛있는건지음식 자체가 맛있는건지만선호프에서 한잔하고 해장하러갔다가 소주 마시고 왔네요.국물이 뽀얘서 깔끔하구요,또 가려구요., 번역: Human is really delicious.Haejangguk went into the prophet, and it's just that ordinary, but the kimchi is delicious.The soup is neat because it is so neat.
원본: 오래전부터 이야기 많이 들었던 영춘옥에 방문했습니다. 꼬리찜 사만원에 네 덩이. 아껴먹는데 옆에서 취미 등산하시는 듯한 아줌마 아저씨 커플 들어오시더니 메뉴에 없던 뼈다귀찜 시키셔서 싸게 푸짐하게 드시네요., 번역: I visited Yeongchun Ok, which I had heard a lot for a long time.Four lumps of tail steamed.I came in with a couple who seemed to be climbing a hobby next to me, and I steamed the bones that were not on the menu and enjoyed it cheaply.

 94%|█████████▍| 21126/22421 [06:14<03:31,  6.13it/s]

원본: 70년 전통의 내공이 느껴지는 곰탕집! 진하게 우려낸 국물이 묵직하고 시원하고 개운하다, 번역: Gomtang house with 70 years of tradition!Dark broth is heavy, cool and refreshing
원본: 곰탕으로 유명한 오래된 맛집.뼈따귀 메뉴가 맛있네요 정말.꼬리찜은 가성비가 좋지 않았습니다4만원에 뼈4개 ㅠㅠ뼈따귀에 술한잔 하기 좋은 집이네요, 번역: Old restaurant famous for Gomtang.The bones are delicious.The tailed steamed was not good for the price.

 94%|█████████▍| 21128/22421 [06:14<03:38,  5.92it/s]

원본: 처음 들어가자마자 주방 직원분들 옷차림이 모두 깔끔해서 신뢰가 갔습니다. 곰탕은 진한맛이 났는데 소주 참기 힘든 맛이였습니다. 양은 그냥저냥 보통이구 계속 생각나는건 국물이 진했다 정도, 번역: As soon as I first entered, the kitchen staff had all the clothes, so I was trusted.Gomtang had a rich taste, but it was hard to endure soju.The sheep is just a good thing.
원본: 뼈다귀 하나에 둘이 술먹다가 설렁탕 하나더 시킴맛은 있는데...비싸고 불친절하다.!뼈다귀 시키면 4개 들어있고뭐 좀 달라고 불러도 못들은척 있다가 카톡할꺼하고 갖다줌...김두한의 단골집이였다던데...그 사람은 참을성이 보살이였나?, 번역: There is a taste of one more Seolleongtang while drinking in one bone...Expensive and unkind.!If you have bones, there are 4 pieces, and you can't call you something...It was Kim Doo -han's regular house...Was that person patient?

 94%|█████████▍| 21130/22421 [06:15<03:36,  5.96it/s]

원본: 사실 큰 기대 없이 갔는데 너무 맛있어서 놀랬습니다. 사장님, 직원분들도 너무 친절하셨고요. 맛은 정말 별거 없는데 외할머니가 해주신 맛이 나서 너무 놀랬습니다. 그렇게 많이 먹는 편이 아닌데 배불러도 거의 남기지 않고 먹었어요.....다음에 무조건 갈거고요. 해장구 곰탕 둘 다 주문했는데 곰탕은 곰탕대로, 해장국은 해장국대로 정말 진한 국물맛이 예술이었습니다. 한식 좋아하시는 분들께 강력 추천 드릴게요!!, 번역: In fact, I went without much expectation and was so delicious.The boss and the staff were so kind.The taste was really big, but I was so surprised that my grandmother tasted.I didn't eat so much, but I ate almost no full.....I'll go unconditionally next time.I ordered both Haejang -gu Gomtang.I would like to recommend it to those who like Korean!!
원본: 이집 음식에 안주해서 술먹으면 맨정신에 나오기 힘듬. 진짜 맛있음..., 번역: It is hard to come out of the spirit when you drink in this house.Really delicious...

 94%|█████████▍| 21131/22421 [06:15<03:56,  5.45it/s]

원본: 내공잇는 맛집 ^^ 식사시간엔 술마시며 노닥거리고 잇으면 안됨을 감안한다면 아주머니들도 친절하시고 무엇보다도 음식맛의 내공이 후덜덜 ㅋㅋㅋ, 번역: Given that you can't drink and drink during the restaurant meal time, the aunts are kind and most of all, the food flavor

 94%|█████████▍| 21133/22421 [06:16<07:10,  2.99it/s]

원본: 5년전 부터 알기 시작해서 종로에서 고깃국으로 2차하긴 괜찮은 집개인적으로 이 집의 시그니처는 뼈다귀라고 생각함.녹진한 소기름과 뼈에 붙은 고기가 맛있는 고기라는 것을 제대로 보여주며 고기를 야금야금 먹다가 보이는 고기가 담긴 뚝빼기안에 국물은 소고깃국물의 정수를 보여주지 않나 생각할 정도로 맛이 아주 진해서 숟가락이 멈추질 않음.오래가는 집은 그만한 이유가 있다는걸 알 수 있는 집인거 같음.가격은 싸진 않지만 이정도 가격에 돈주고 먹을만 하다고 생각되는 집.이 집에서 선지 해장국도 먹어봤는데 나쁘지 않음참고로 뼈다귀는 늦게가면 떨어져서 못먹을때도 있음., 번역: I started to know five years ago, and I personally think that the signature of this house is a bone ghost.The meat on the greenish oil and the bones is a delicious meat, and the soup is so tasty that the soup does not show the essence of the soup in the takyan containing the meat that is seen while eating metallurgical metallurgy.I think it's a house that knows that there's a good reason.The price is not cheap, but the house is thought to be eaten at this price.I also ate Haejangguk in this house, but it's not bad, and sometimes the bone is late and I can't eat it.
원본: 2만원을 가치있게 쓰는 법1. 영춘옥 꼬리곰탕2. 치킨, 번역: How to spend 20,000 won valuable 1.Yeongchun Ok Tail Gomtang 2.chicken

 94%|█████████▍| 21135/22421 [06:16<05:30,  3.89it/s]

원본: 꼬리찜 4만원에 딸랑 4조각 나옵니다..미리 사진이라도 보여줬으면 시키지 않았을 텐데..다들 따귀 시키려다 다 떨어졌다는 말에 비슷한 꼬리찜 권해서 시켜먹고 어이 없어 합니다. 퍽퍽하고 양이 매우 적어 혼자 먹기에도 적습니다. 항의하면 사장으로 보이시는 여자분이 손님이 잘 모른다는 식으로 꼬리찜은 비싼 음식이다라고만 강요합니다. 왜 불만을 갖는지 들을 생각도 안하고 안 좋은 추억만 있어서 다신 안가려고 합니다. 따귀가 유명한 집인데 따귀없다고 절대 다른 메뉴 시키지 마세요!, 번역: The tail is 40,000 won for 4 pieces..I wouldn't have been able to show me a picture in advance..It's ridiculous to eat similar tail steamed to say that everyone has fallen.It is very small and very small, so it is small to eat alone.In protest, the girl who looks like a boss is that the guests don't know well.I don't even think about why I'm dissatisfied and I don't want to go again because I have only bad memories.It's a famous house, but don't have any other menu!
원본: 따귀찜 최고!, 번역: The best steamed!

 94%|█████████▍| 21137/22421 [06:17<04:32,  4.71it/s]

원본: 회사일로 주변에 갔다가 소개를 받아 방문가격은 저렴하지 않지만 말씀 들은대로 깔끔하고 맛있습니다 맑은 국물이고 담백해요, 번역: I went to the company and went around and was introduced to the price of the visit, but it is clean and delicious as I heard.
원본: 보통 맛집으로 소문 나면 불친절한 경우가 많은데 이 집은 친절이 과하네요부족한거 없냐길레 밥이라니 바로 한공기공짜로 주시네요당연 맛도 좋았구요종로 가는 경우 꼭 제방문할겁니다, 번역: It's unkind when it's rumored to be a restaurant.

 94%|█████████▍| 21139/22421 [06:17<04:05,  5.23it/s]

원본: 필자가 군인일때 많이 들리던 국밥집.그당시 부담되는 가격이였지만 맛을 포기할수는없었다., 번역: Gukbap restaurant I heard a lot when I was a soldier.It was a burden at that time, but I couldn't give up the taste.
원본: 서울에서도 오래된 해장국집이라서 가봤는데, 해장국은 그냥 그랬어요.. 맛있는것도 아니고 맛이 없는 것도 아닌 특징이 없는 맛.. 다음에 따귀를 한번 먹어봐야 겠어요.., 번역: I went to Seoul because it was an old Haejangguk house, but Haejangguk was just like that..It is not delicious and no taste..I'll have to try it next time..

 94%|█████████▍| 21141/22421 [06:17<03:53,  5.48it/s]

원본: 국물맛 끝내줌주차장은 옆에 피카디리 공용주차장 이용, 번역: The soup tasted parking lot is used next to Piccadiri public parking lot
원본: 깊은 곰탕 국물~ 맛있어요 ㅎㅎ 다음에 다른 것도 먹어봐야겠습니다, 번역: Deep Gomtang Soup ~ It's delicious ㅎㅎ I'll try something else next time

 94%|█████████▍| 21143/22421 [06:18<04:14,  5.01it/s]

원본: 직장 동료들과 점심식사하기 좋은 곳 입니다가격은 좀 높아요, 번역: It's a good place to have lunch with my colleagues.
원본: 곰탕이 별도로 간을 하지않아도 맛납니다, 번역: Gomtang is delicious even if it doesn't have to be seasoned

 94%|█████████▍| 21149/22421 [06:18<01:47, 11.79it/s]

원본: 따귀찜, 곰탕 그리고 서비스 해장국까지!배터질거 같아요, 번역: Steaming, Gomtang and Service Haejangguk!I think it's going to batter
원본: 부모님 모시고도 간적 있었는데 그냥 간장게장 먹으러만 가기에는 가성비 아까울수 있음.간장게장 자체만으로는 살 엄청 많고 비린내도 안났으며 너무 짠맛도 안났음. 껍데기에 밥 비벼먹을때 참기름 달라하면 엄청고소한 향의 참기름 가져다줌.갈비찜은 진짜 부드러워서 전혀 안질김. 한방냄새도 격하게 안나서 무난무난함.다시한번 말하지만 가성비 찾으러 가는 집은 아님.음식 그자체는 만족스러웠음. 기타 밑반찬도 정갈하니 좋았음.외국인이 많은 지역인지라 특히 중국인이 많음., 번역: I went to my parents, but it can be a waste to go to eat soy crab.The soy crab itself alone was a lot of flesh, no fishy, and the taste was not too salty.When you eat sesame oil when you eat rice on the shell, it will bring a very savory sesame oil.The ribs are really soft, so it's not at all.The smell of herbal medicine is not strong.Again, it's not a house to find a price.The food was satisfactory.The other side dishes were also neat.There are many foreigners, especially Chinese.

 94%|█████████▍| 21151/22421 [06:18<02:17,  9.24it/s]

원본: 비교적 삼삼한 맛의 간장게장. 게살맛을 오롯이 느낄수 있어 좋았고 찬이 정갈하고 맛이 좋아 대접하기 좋은 곳이라는 생각이 들었습니다. 때에 따라 대기를 할 수도 있어요. 전 처음 갔을땐 대기없이 들어갔고 이 후 방문에는 한 20여분 기다렸습니다. 맛에도 놀라고 가격에도 놀라는, 놀라운 맛집입니다 ^^, 번역: Soy crab with a relatively three -sam -sam taste.It was good to feel the crab flavor, and I thought it was a good place to serve.You can wait sometimes.When I first went, I went in without a waiting, and I waited for about 20 minutes.It is an amazing restaurant that is surprised at the taste and is surprised at the price.
원본: 가격은 좀 세지만 그 값어치를 해요~ 그릇도 다 놋그릇이라 씻기도 힘드실텐데 대단!! 맛은 많이 짜지도 않고 간이 적당히 맛있어요! 저는 갈비찜도 같이 시켰는데 정말 야들야들하고 맛났어요~~ 근데 양이 좀 적으니 놀라지 마세요~ 저는 일본분들 대접하러 갔었는데 정말 좋아하셨어요! 밥 안드시고 맥주에 게장만 드시더라구요... 너무 맛있으시다며... 매운거 못드시는 외국분들 대접할 때 좋은 것 같아요! 서비스도 좋고 너무 친절한 집이에요, 번역: The price is a bit strong, but it's worth it ~ It's hard to wash because it's a brass bowl.!The taste is not so salty and the liver is moderately delicious!I also steamed ribs, but it was really good and delicious ~~ But don't be surprised because the amount is a little small ~ I went to the Japanese people and I really liked it!I didn't eat rice and only crab in beer...It's so delicious...I think it's good to treat foreigners who can't spicy!The service is also good and so kind.
원본: 중랑역 바로 옆에 위치한 돼지곱창볶음 전문점.이 지역에서 평이 좋고 항상 손님이 많은 집이길래 큰 기대를 갖고 방문~하지만 기대와 달리 개인적으로 너무 실망이 커서 후회 많았던 곳...일단 맛을 떠나서 돼지 곱창의 역한 냄새가 너무 심하다. 나름 맛과 냄새를 잡으러 양념을 잘 첨가하여 볶아냈지만 한계가 있는 듯...또한 바빠서 그런지 친절성도 조금 결여되어 있고...이집의 장점은 저렴한 가격에 푸짐한 양이 최고 장점. 곱창볶음 자체도 양이 많지만 다양한 토핑 또는 볶음밥 추가도 가능해서 저렴한 가격에 푸짐한 식사를 원하는 분들께는 만족스러운 곳이라 생각한다.하지만 생각 외로 냄새가 심해 개인적으로는 조금 더 비싸더라도 다른 곱창볶음 집을 선택하기로..., 번역: Pork giblet stir -fried restaurant located right next to Jungnang Station.In this area, there is a good flat and always a lot of guests, so I visited with great expectations...Once you have a taste, the smell of pork giblets is too bad.I added the seasoning well to catch the taste and smell, but it seems to be limited...Also, I'm busy, so I lack kindness...The advantage of this house is the highest advantage of a low price.The giblet stir -fry itself is also large, but it is also possible to add various toppings or fried rice, so it is satisfactory for those who want to have a lot of meals at a low price.However, it smells unexpectedly and personally, even if it is a little more expensive, I will choose another giblet fried house...

 94%|█████████▍| 21154/22421 [06:20<04:26,  4.76it/s]

원본: 예전 시장에서 먹는 돼지 곱창을 좋아한다면 추천!돼지기름 향이 강해서 호불호가 강한맛개인적으로 기름기가 많아 식감이 좋고 익혀나와서 맛있었음!, 번역: Recommended if you like the pork giblets you eat in the old market!It has a strong pork oil, so it tastes like a strong taste.
원본: 골목식당보고 야채곱창 먹고싶던 차에 방문한 집!양이 진짜진짜 푸짐하다. 3명이 2인분시켜도 넉넉할 정도!! 돼지곱창 누린내가 약간 나긴하지만 개인적으로 돼지곱창의 맛이라고 생각해서 아쥬 맛나게 먹음!!🥳소주가 훌훌 들어감!, 번역: I visited the car that I wanted to eat vegetables!The sheep are really rich.Even if 3 people are two servings, it's enough!!I'm a little bit of pork giblets, but I personally think it's the taste of pork giblets.!🥳 Soju enters!

 94%|█████████▍| 21155/22421 [06:20<04:20,  4.86it/s]

원본: 자극적이고 매콤한 곱창! 양이 푸짐해요. 중국당면으로 바꿔 먹어도 맛있어요. 치즈곱창에 치즈도 듬뿍 뿌려주시는데 개인적으론 그냥 곱창이 더 맛있는 것 같아요, 번역: Irritating and spicy giblets!The amount is plenty.It's delicious even if you change it to Chinese vermicelli.Sprinkle plenty of cheese on the cheese giblets, but personally, the giblets are more delicious.

 94%|█████████▍| 21156/22421 [06:20<04:28,  4.72it/s]

원본: 딱 인기 많을 맛. 치즈 굿.. 그리고 사장님 친절하시다., 번역: It's just popular.Cheese Good..And the boss is kind.

 94%|█████████▍| 21157/22421 [06:20<04:29,  4.68it/s]

원본: 맛집으로 유명해서 가봤는데 좋습니다~~ 먹으면 술생각나는 맛 !, 번역: It's famous as a restaurant, but it's good ~~

 94%|█████████▍| 21158/22421 [06:20<04:41,  4.49it/s]

원본: 중랑역 곱창 맛집으로 유명한 이유를 알겠어요 가격도싸고 맛있습니다!!, 번역: I know why it is famous for Jungnang Station Gopchang restaurant. The price is cheap and delicious!!

 94%|█████████▍| 21159/22421 [06:21<04:53,  4.29it/s]

원본: 지역주민들은 다 아는 가성비좋은 정말 맛있는 돼지곱창이있는곳!! 특히나 치즈곱창의 치즈양은 상당하다, 번역: The local residents know that the price is good and there is a really delicious pork giblet!!Especially the cheese of cheese giblets is considerable

 94%|█████████▍| 21161/22421 [06:21<03:50,  5.46it/s]

원본: 북해도식 스프카레를 취급하는 곳입니다. 재료가 알맞게 구워져 나와서 야채가 전부 맛있었고, 특히 브로콜리가 훌륭했습니다. 스프 국물은 풍미가 좋았고 묽기도 적당했습니다. 맵기는 중간맵기로 주문했는데 생각보다 매운 편이라 매운걸 잘 못드시는 분들은 순한맛을 드시는게 좋을것 같습니다. 밥에 치즈도 추가해서 먹었는데 스프카레와 잘 어울려서 만족스러웠습니다. 자리는 많지 않은 편이라 붐볐지만 제가 갔을때는 웨이팅은 없었습니다. 쌀쌀해지면 재방문하고 싶습니다., 번역: It is a place to handle North Korean soup curry.The ingredients were baked and the vegetables were all delicious, especially broccoli.The soup broth was good and thin.I ordered it as a medium spicy, but it's spicy than I thought, so if you can't do it well, it's a good idea to have a gentle taste.I also added cheese to the rice, but I was satisfied with the soup curry.It was crowded because there were not many seats, but when I went, there was no weighting.I would like to return when it gets chilly.

 94%|█████████▍| 21162/22421 [06:21<04:05,  5.13it/s]

원본: 깔끔하고 조용한 공간. 단촐한 메뉴지만 이정도로 충분하다. 아주 저렴한 가격은 아니나 다양한 야채를 감안하면 만족. 돼지고기는 다시 먹고싶을 수준은 아니었으니 다음에 가게 된다면 닭고기도 나쁘지 않을 듯., 번역: Clean and quiet space.It's a simple menu, but it's enough.It's not a very affordable price, but it's satisfied considering a variety of vegetables.The pork weren't the level you want to eat again, so if you go next time, chicken will not be bad.

 94%|█████████▍| 21163/22421 [06:21<04:23,  4.77it/s]

원본: 스프카레가 먹고 싶어서 찾아봤어요. 삿포로에서 먹었던 사무라이카레보다 조금 떨어지지만 그래도 맛있었어요., 번역: I wanted to eat soup curry.It's a little lower than the samurai curry I ate in Sapporo, but it was delicious.

 94%|█████████▍| 21164/22421 [06:22<04:41,  4.47it/s]

원본: 오랫만에 맛있는 마라샹궈를 먹었습니다 매운단계는 2단계로 하니 적당히 맵고 맛있었습니다 전체적으로 매우 만족스러운 저녁이였네요, 번역: After a long time, I ate delicious Mara Xiang Guo.

 94%|█████████▍| 21165/22421 [06:22<04:56,  4.24it/s]

원본: 샹궈맛집~! 셀프로 담아서 드시는거 추천~!추가적으로 꿔바로우도 맛져요~~, 번역: Shang Guo Restaurant ~!It is recommended to put it as a self ~!In addition, it tastes good too ~~

 94%|█████████▍| 21166/22421 [06:22<05:01,  4.16it/s]

원본: 가격도 괜찮고 맛도 괜찮아요. ㅎㅎ개인적으로 꿔바로우가 맛있는것같아요!, 번역: The price is good and the taste is good.ㅎㅎ personally, I think Baro is delicious!

 94%|█████████▍| 21167/22421 [06:22<05:05,  4.11it/s]

원본: 마라탕보단 마라상궈가 훨씬 맛있음 가격도 쌈 점심에 가면 점심특선있는듯, 번역: The price is much more delicious than Maratang.

 94%|█████████▍| 21168/22421 [06:23<05:02,  4.14it/s]

원본: 마라샹궈가 괜찮은집 점심에오면 세트 있어서 가성비가 좋은것같다, 번역: Marashang Guo is a good house for lunch, so it's good to have a good price.

 94%|█████████▍| 21169/22421 [06:23<05:05,  4.10it/s]

원본: 음식은 퓨전 치킨 요리로 보시면될꺼 같습니다. 양이 생각보다 많지 않았고 서비스는 손님도 없는 시간대였는데 기본적으로 나오는 물도 시켜야주더라구요. 맛은 보통이였습니다. 우와 맛있다 이건아니였어요(엄청배고플때 갔었는데) 그리고 가게 내부는 깨끗합니다. 건물 지하에있구요 에스컬레이터 내려가서 왼쪽입니다. 직장인들이 많이 가기 좋은 장소? 인듯합니다., 번역: The food will be seen as a fusion chicken dish.The amount was not as much as I thought, and the service was a time zone without guests.The taste was normal.Wow, it's not delicious (I went when I was so hungry) and the inside of the store is clean.It is in the basement of the building.A good place for office workers?It seems to be.

 94%|█████████▍| 21170/22421 [06:23<05:15,  3.97it/s]

원본: 까르보나라 치킨세트:치킨은 원조가 최고라는생각이 들게함. 맛이 나쁘지 않지만 사람에 따라 호불호가 갈릴듯. 색다른치킨맛을 즐기고싶다면 추천, 번역: Carbonara Chicken Set: Chicken makes you think the aid is the best.The taste is not bad, but it seems to be different depending on the person.Recommended if you want to enjoy a different chicken taste

 94%|█████████▍| 21171/22421 [06:23<05:07,  4.06it/s]

원본: 웨이팅 없던 적이 없네요. 치킨, 맥주 맛있습니다. 추천합니다, 번역: I haven't had a weighting.Chicken, beer is delicious.I recommend it

 94%|█████████▍| 21172/22421 [06:24<07:57,  2.62it/s]

원본: 색다른 느낌의 치킨요리. 그저 치킨만을 위한 시끌벅적한 느낌이 아니라 요리로서 치킨을 즐기고 맥주한잔 마시면 즐거운 담소가 가능한 곳., 번역: Chicken dishes with different feelings.It's not just a noisy feeling for chicken, but it's a dish that can be enjoyed by enjoying chicken and drinking a beer.

 94%|█████████▍| 21173/22421 [06:24<07:16,  2.86it/s]

원본: 맥주도 맛있고 치킨도 맛있어요ㅋㅋ 슬러쉬맥주먹으러 한번 더 갈 것 같아요 사천치킨은 엄청 매우니까 주의, 번역: The beer is delicious and the chicken is delicious.

 94%|█████████▍| 21174/22421 [06:25<06:33,  3.17it/s]

원본: 분위기 갑. 음식도 맛있고, 술마시기 최고! 그리구 이쁨. 친절하게 칵테일 설명도 잘 해주시고, 추천도 잘해주셔서 즐겁게 마시다 올 수 있는 곳. 그래고 역시 칵테일은 만드는 걸 보는 맛! 칵테일바는 메뉴판이 의미가 없어서 없음.., 번역: Mood.The food is delicious, the best time to drink!And pretty.Kindly explain the cocktail, and you can enjoy it because you are good at recommendation.And too, it's a taste of making cocktails!The cocktail bar is not meaningful because the menu is meaningless..

 94%|█████████▍| 21175/22421 [06:25<06:15,  3.32it/s]

원본: 파스타도 맛있지만 스테이크가 예술이에요. 분위기도 좋고 접시도 퀄이 좋아요., 번역: Pasta is also delicious, but steaks are art.The atmosphere is good and the plate is good.

 94%|█████████▍| 21176/22421 [06:25<05:52,  3.53it/s]

원본: 너무 너무 만족한 방문이었습니다! 스테이크도 맛있었고, 크림파스타도 맛있었어요!! 일하시는 분들의 서비스도 넘 좋았습니다, 번역: It was so satisfactory!The steak was delicious, and the cream pasta was also delicious!!The service of those who work was also good.

 94%|█████████▍| 21178/22421 [06:25<04:10,  4.95it/s]

원본: 경양식 돈가스 땡기는 날 주변검색으로 찾아간 곳 선거날 점심에 찾아갔는데 사람이들이 매장을 가득 채우고 뒤에 오신분들은 약간의 웨이팅 있었음 경양식 돈가스 맛이 땡겼는데 딱 기대만큼의 맛을 느끼게 해준곳, 번역: I went to lunch on the day of the election day by searching the surrounding surroundings, but the people who came to the store filled the store and the backs there were some weights.

 94%|█████████▍| 21179/22421 [06:26<05:03,  4.09it/s]

원본: 양이 진짜 많은 돈까스 집입니다. 외부매체에서도 방영한 가게입니다., 번역: The amount is a lot of pork cutlet.It is a shop that was also aired on external media.

 94%|█████████▍| 21180/22421 [06:26<05:08,  4.02it/s]

원본: 뭘먹을지 고민이 되어 방문한곳입니다.메뉴가 다양하게 많아서 좋았습니다.음식맛은 보통입니다., 번역: I was worried about what to eat.It was good because there were a lot of menus.The food taste is normal.

 94%|█████████▍| 21182/22421 [06:26<04:36,  4.48it/s]

원본: 1층은 좌식이고 2층은 방으로 되어있다.은평구 역촌역에 위치한 오래된 돈까스집이다.  초저녁이라 가족단위로 많이들 오는거 같다. 첫째주, 넷째주 일요일은 휴일이다. 양은 푸짐하다. 가격은 기본 돈까스가 만원이다. 식전 스프는 땅콩맛이 나는거 같아 약간 호불호가 갈릴듯한 개인적인 생각이다. 돈까스의 느끼함을 잘 익은 깍두기 김치가 잡아준다. 전체적으로 괜찮았다., 번역: The first floor is seated and the second floor is made of room.It is an old pork cutlet located in Yeokchon Station, Eunpyeong -gu.It's early evening, so it seems to come a lot by family.The first and fourth Sundays are holidays.The amount is rich.The price is 10,000 won.The soup is a peanut, so it's a personal idea that seems to be a bit disagreement.Kimchi kimchi is ripe.Overall it was fine.
원본: • 돈가스와 역촌정식을 주문했습니다.• 돈가스로 주문했을때 돈가스의 크기가 꽤 큼직했습니다. (정식으로 주문하면 생선가스와 함바그가 나오지만 돈가스에 비해 돈가스 크기가 절반정도 크기)• 분위기는 가볍게 한끼식사 할수 있는정도 였습니다.• 무엇보다 돈가스만 먹으면 조금 느끼한 감이 없지 않아 있는데, 여기는 깍두기도 함께 줘서 느끼한 부분을 잘 잡아주는 느낌이었습니다., 번역: • I ordered pork cutlet and stationary village.• When ordered with pork cutlet, the pork cutlet was quite large.(If you order it formally, you can see the fish gas and the hackbag, but the pork cutlet size is about half the size compared to the pork cutlet.) • The atmosphere was lightly eaten.• Above all, if you eat pork cutlet, there is no feeling a little bit of feeling, but it was a feeling of grabbing the parts you felt by giving them together.

 94%|█████████▍| 21184/22421 [06:27<04:53,  4.22it/s]

원본: 돈까스가 진짜 큽니다만원이란 가격이 조금 부담스럽지만 가격대비로는 충분한 듯 하네요깍두기가 달달해서 아이들도 먹기 좋아요소스가 쎈편이라 소주 한잔 곁들이기도 좋습니다, 번역: The pork cutlet is really big, but the price is a bit burdensome, but it seems enough for the price.
원본: 추억의 돈까스 맛입니다. 특별하진 않지만 가끔 먹을 것 같네요, 번역: It is a pork cutlet of memories.It's not special, but I think it's going to eat sometimes

 94%|█████████▍| 21186/22421 [06:27<04:13,  4.87it/s]

원본: 돈까스 자체를 워낙 좋아해서 자주 갔어요~추억의 돈까스 경양식집?을 떠올리시면ㅋㅋ 기사식당에 가깝나..여튼 기본적인 맛이어요~, 번역: I loved the pork cutlet itself so often..Anyway, it is the basic taste ~
원본: 저렴한 가격.평범한 맛.가성비 좋은 점심.6, 번역: affordable price.Ordinary taste.Good value for lunch.6

 95%|█████████▍| 21192/22421 [06:28<02:31,  8.11it/s]

원본: 그저 그래요 재방문의사 X짜조 그릇 안 먹으니까 중간에 챙겨가던데 재사용 하는건지?, 번역: It's just that.
원본: 가지튀김으로 유명한 연남동 하하.만두부터 가지튀김, 멘보샤까지 제대로된 '요리'를 대접받은 느낌.전체적으로 간이 삼삼하고 자극적인 맛이 없이 깊은맛이다.군만두는 속이 꽉 차고 피가 쫄깃하면서 바삭하다.대망의 가지튀김. 튀김옷은 양념으로 매콤달콤짭조름하며 가지의 식감도 최고.멘보샤는 새우살이 푸짐하며, 찐만두에서 충격을 받은건 극심한 버섯향. 큼직큼직하게 다져진 만두소.나는 버섯 특유의 향을 굉장히 좋아하는 편이라 극호였으나, 분명 호불호가 뚜렷할 듯 하다.간단하게 맥주 즐기기에도 굉장히 좋은 곳이다. 가지튀김은 여운이 상당히 오래 남는다., 번역: Yeonnam -dong is famous for its eggplant.From dumplings to tempura and Menbosha, they are treated properly.Overall, it is a deep taste without a liver and irritating taste.The military dumplings are full, bloody and crispy.Tempura of the long -awaited eggplant.Tempura is spicy with seasoning, and the texture of the eggplant is the best.Menbosha has a lot of shrimp meat, and it is shocked by steamed dumplings.Dumplings are greater.I really liked the mushroom's unique aroma, so it was a polarization, but it seems to be clear.It's a very good place to enjoy beer.The eggplant fries remain quite long.

 95%|█████████▍| 21194/22421 [06:28<02:50,  7.20it/s]

원본: 가지튀김이랑 찐만두랑 완자탕 먹어봄가지튀김은 튀김옷이 얇고 매우 바삭하며속은 아주 부드럽고 가지의 즙이 살아있다겉바속촉의 식감이 맛을 끌어올려줌완자탕은 가지튀김과 궁합이 좋다는 지인의 추천 때문에 시킨 건데고기국물과 버섯, 청경채 등의 야채가 담백하게 어우러짐가성비도 좋은 편가지튀김과 완자탕은 맛있긴 한데 어느정도 예상했던 맛이라면찐만두는 의외로 정말 맛있었음이렇다할 개성이 있다기보단 기본에 충실한 만두내부는 협소한 편이며 테이블 간 거리 역시 좁음평일 낮임에도 불구하고 칭따오와 곁들여 먹는 사람들 많았음재방문 의사 있음, 번역: The eggplant fried and steamed dumplings and the rice soup are eaten by the fried rice and very crispy, the inside is very soft and the eggplant juice is alive.The vegetables such as broth, mushrooms, and bok choy are also delicious, but the price is also delicious, but if it tastes to some extent, steamed dumplings were surprisingly delicious.On the side, the distance between the tables was also narrow, despite the low peace of peace.
원본: 작년에도 몇 번 온 곳인데 가지튀김 맛이변한듯ㅜ 사실 가지튀김빼곤 볼거없는곳인데ㅠ 이번에 먹었을땐 간도 밍밍하고 그냥 먹고나서 이런걸로 배채우다니 기분이나빴음.. 게살스프는 크레미찢어서 물에 전분 풀어 소금넣고 끓인거같음..크래미스프로 이름바꿔야함. 반찬에 쯔란은 소금에 절여진 소태같아서 먹고뱉어버림.. 이제 가지튀김파는데가 많아서 재방문하지 않을것같음. 짜이찌엔.., 번역: Last year, it was a few times, but the eggplant flavored..The crab meat soup seems to have been boiled in water and boiled in water..You have to change your name to CrALS.Tsuran is a salt -picked tailla for the side dishes, so they eat and spit out..Now I don't think I can return it because I have a lot of fried frying.Zaichien..

 95%|█████████▍| 21196/22421 [06:28<03:07,  6.55it/s]

원본: 낮인데 사람이 많아서 불친절하긴 한데 가지튀김은 맛있네요. 만두 먹으러 왔는데 찐만두는 속이 적어서 맛이 없어요.라고 쓰고 먹고 있는데 먹는데 갑자기 끝났다고 나가라고 함. 들어오기 전에 말 한 것도 아니고 어이가 없어서 다시 안 옴. 서비스가 하나하나 최악이다....., 번역: It's daytime, but it's unkind because there are a lot of people, but the eggplant is delicious.I came to eat dumplings, but steamed dumplings are small and tasteless.I'm eating and eating, but I'm going to go out suddenly.I didn't say it before I came in, and it was ridiculous.The service is the worst one.....
원본: 여전히 맛있어요 가지튀김이 바삭하고 맛있습니다멘보샤도 퀄리티있어요다만 좀 느끼해서 짬뽕같은게 있었으면 좋겠어요, 번역: It's still delicious. The eggplant is crispy and delicious.

 95%|█████████▍| 21198/22421 [06:29<03:14,  6.29it/s]

원본: 가지튀김을 엄청 기대하고 갔었는데 막 특별한 맛은 아니었어요 멘보샤도 맛있긴한데 그냥 보통..? 서비스도 그저 그랬어요 친절하다는 느낌은 못받은.. 굳이 재방문 할 것 같지는 않네욥, 번역: I was looking forward to the fried eggplant, but it wasn't just a special taste..?The service was just like that. I didn't feel kind..I don't think I'm going to return.
원본: 이따금씩 생각나는 가지튀김, 저렴하게 먹을 수 있는 멘보샤. 특히 맥주 안주로서의 기능을 톡톡히 하기 때문에 더욱 매력적이다., 번역: Occasionally, the tempura that comes to mind, Menbosha, who can eat cheaply.In particular, it is more attractive because it is a beer snack.

 95%|█████████▍| 21200/22421 [06:29<03:19,  6.12it/s]

원본: 하하의 시그니쳐 메뉴인 가지튀김이 2년 전 방문했을 때와 달라보였다. 맛도 좀 달라진 듯. 주방장이 바뀐 것 같다. 고량주와 칭따오를 음식들과 함께 신나게 먹고 즐겁게 떠들고 나왔다., 번역: Haha's signature menu was different from when I visited two years ago.The taste seems to be a little different.The chef seems to have changed.I had fun with the foods with the foods, and I enjoyed it.
원본: 가끔 가지요리가 떠오르면 빠른 시일내에 찿아가 먹어주어야하는 맛집. 기름에 요리한 짭조름한 가지볶음을 새콤한 해파리 냉채와 함께 먹으면 좋다., 번역: Sometimes when you come to mind, you should find it as soon as possible.It is good to eat one stir -fried stir -fry with oil with sour jellyfish.

 95%|█████████▍| 21202/22421 [06:30<03:28,  5.84it/s]

원본: 가격은 저렴한듯멘보샤나 동파육 특별한 맛은 아님.술한잔하기에는 괜춘, 번역: The price is cheaper, it is not a special taste of Menbosha or Dongpa.It's okay to have a drink
원본: 만두도 맜있는데 가지볶음 무지 맛있었어요 2개시켜 둘이 먹었는데 둘이 먹기에는 양이 많고 남자 3명이나 여자는 4명도 먹을 양이네요, 번역: Dumplings are also good, but branch stir -fry was very delicious. I ate two, but they had a lot to eat, and 3 men and women were eaten.

 95%|█████████▍| 21204/22421 [06:30<03:27,  5.86it/s]

원본: 가지튀김이 맛있다고해서 가봤는데 여기가 최고다하는 감동은 못 느꼈지만 일행은 맛있다고 함 맛은 평균 이상 분위기는 서민적인 분위기, 번역: I went to the eggplant because the eggplant was delicious, but I didn't feel the best thing here, but the group is delicious.
원본: 가지볶음은 정말 맛있네요! 군만두는 굳이 여기서 먹지 않아도 되는 것 같구요. 완자탕은 버섯향이 진해서 버섯 좋아하시는 분들은 가지볶음과 같이 드시면 좋을 것 같아요. 음식 이외의 것은 셀프 수준입니다., 번역: The eggplant fried is really delicious!The military dumplings don't have to eat here.Wanja -tang has a lot of mushrooms, so if you like mushrooms, you should eat it with eggplant.Other than food is self -level.

 95%|█████████▍| 21206/22421 [06:30<03:32,  5.73it/s]

원본: 웨이팅값 하는 가지볶음 맛맛잇는 볶음밥이 복병이엇음 버섯맛이 일품인 완자탕도 추천, 번역: Wangja -tang, which is a stir -fried rice fried rice, is also recommended for mushrooms.
원본: 가지볶음은 기대이상으로 맛있었습니다.군만두는 나쁘진 않았고 볶음밥은 다른 곳에서 먹는게 더 나을 것 같네요. 화장실이 불편했고요., 번역: The eggplant stir -fry was more than expected.The military dumplings were not bad, and the fried rice would be better to eat elsewhere.The bathroom was uncomfortable.

 95%|█████████▍| 21209/22421 [06:31<02:42,  7.47it/s]

원본: 생각보다는 그저 그랬다! 가지볶음 갓나왔을때는 맛있는데 엄청 뜨거워서 입안 헐지 않게 주의하기를ㅠ 그러나 금방 식어서 아쉬움., 번역: I just did it than I thought!It's delicious when you come out of eggplant, but it's so hot that you should be careful not in your mouth.
원본: 군만두;육즙이 풍부하고 바삭한게 맛나요가지튀김;처음 먹어보는 맛으로 맛있어요 양이 많아 둘이서 먹자니 양이 많아요 다먹고 나면 조금은 느끼한 마무리네요, 번역: Dumplings;

 95%|█████████▍| 21211/22421 [06:31<03:05,  6.52it/s]

원본: 가지튀김의 가지는 고기향이 가득하고 바삭한 튀김옷을 입었다, 번역: The branches of tempura are full of meat and crispy tempura.
원본: 인생 가지튀김!!! 아직도 생각나는 그맛이네요. 군만두는 솔직히 그저그랬어요. 다음번에 가면 가지튀김만 먹을듯, 번역: Living eggplant fried!!!It's still the taste.The military dumplings were honestly like that.If you go next time, just eat branches

 95%|█████████▍| 21215/22421 [06:31<02:20,  8.60it/s]

원본: 가지튀김은 홍콩서 먹던거랑 진배없이 맛나요대신 이거랑 짬뽕을 드셔야 느끼하지 않아요, 번역: The eggplant fries are delicious without eating and eating in Hong Kong.
원본: 맛있음, 번역: Delicious

 95%|█████████▍| 21221/22421 [06:32<01:26, 13.83it/s]

원본: 가지볶음 겉과 속이 다른 식감을 느낄수 있음, 번역: You can feel the texture that is different from the outside of eggplant stir -fry
원본: 생각지도 않았던 맛집~카레는 역시 인도 커~리! 자주 올꺼 갔아요, 번역: Restaurant that I never thought of ~ Curry is India Kerr ~ Lee!I went often

 95%|█████████▍| 21223/22421 [06:32<01:53, 10.59it/s]

원본: 음식은 대체로 맛있었으며, 네이버 예약을 하면 난 하나를 무료로준다, 번역: The food was usually delicious, and if you make a reservation, I give you one free.
원본: 인도인은 그냥 쇼윈도 서비스는 기대하지 말길 손님 없었는데  여사장덕에 기분나빠서 나옴 맛집이면 이해라도 할라는데 걍 롯데몰가서 인도음식드시길, 번역: The Indians didn't expect the show window service.

 95%|█████████▍| 21225/22421 [06:32<02:14,  8.88it/s]

원본: 동네 인도요리 전문점보다 높은 수준. 난, 커리 등이 프랜차이즈들보다 수준이 높음, 번역: It is higher than the local Indian cuisine specialty store.I, Curry, etc. are higher than franchises
원본: 냉짬뽕이랑 해물짬뽕 먹었는데 해물짬뽕 먹다보니 가리비가 상했네요.... 상했다고 하니까 바꿔 준다길래 짬뽕 먹기 그래서 자장면으로 달라고 했는데 계산할 때 보니 ... 해물짬뽕으로 계산 되어 있네요 ㅎㅎ;; 나와서 조금 아닌거 같아서 다시 가서 여쭤보니 짜장면 대신 드린거라고 하네요 .... 식품상태 서비스 다 안좋았습니다. 집근처인데 다시는 안가고 싶네요, 번역: I ate cold champon and seafood champon, but I ate seafood champon....I changed it because it was damaged...Seafood champon is calculated ㅎㅎ ;;I didn't think it was a little out of it, so I went back and asked me....Food state service was bad.I'm near my house, but I don't want to go again

 95%|█████████▍| 21227/22421 [06:33<02:32,  7.83it/s]

원본: 워낙 유명한 곳이라 사람들이 항상 끊이지 않는 곳이에요~  자장면도 엄청 저렴하고 맛있답니다 :), 번역: It's a famous place, so it's always a place where people are always ceased ~ Jajangmyeon is very cheap and delicious :)
원본: 조용하고 2층까지있어서 좋은듯 테이블수도 많고 플러그도 많아서 공부하기좋은 카페, 번역: It's quiet and the second floor, so it's good to have a lot of tables and plugs.

 95%|█████████▍| 21229/22421 [06:33<02:49,  7.03it/s]

원본: 공부하기 좋은 카페. 아이스티를 진짜 티백 아이스티로 내주는 건 좋았지만 맛은 별로였습니다. 가격은 좀 비싼 편이지만 무난하게 있기 좋고 카페 내부가 넓어 오래 있어도 부담이 없습니다. 영업시간이 긴 것도 장점. 단 청소가 안 되는 건지 미묘한 악취가 있어요. 심한 건 아닌데 이따금 커피 냄새에 섞여 바닥에서 올라오는 느낌? 민감하지 않으면 못 느낄 정도니 괜찮지만 깔끔한 인상은 아닙니다., 번역: A good cafe to study.It was good to give the iced tea a real tea bag iced tea, but the taste was not good.The price is a bit expensive, but it's good to be good and the inside of the cafe is wide.It is also an advantage that the business hours are long.However, there is a subtle odor if it is not cleaned.It's not severe, but sometimes it's mixed with the smell of coffee?If you don't feel sensitive, you can't feel it, but it's not a neat impression.
원본: 깔끔하고 기본에 충실한 카페입니다. 하지만 시끄럽고 직원이 불친절해요., 번역: It is a clean and faithful cafe.But it's noisy and the staff are unkind.

 95%|█████████▍| 21232/22421 [06:33<02:27,  8.07it/s]

원본: 성신여대 골목에 숨어있는 예쁜 카페 카페온더플랜! 걷보기보다 매장이 넓어서 좋아요!, 번역: Pretty Cafe Cafe On the Plan hidden in Sungshin Women's Alley!It's good because the store is wider than the appearance!
원본: 아이때문에 정신없어서 음식사진을 못찍음..ㅎ..일단 물냉면은 육수에서 고기비린맛이 확올라옴. 육수도 미지근...비빔은 괜찮은맛.5천원쯤이면 먹을만할거 같은데 가격대비 창렬.아이가 먹을만한 메뉴도 없음., 번역: I can't take a picture of the food because of my child..he..First of all, the water cold noodles have a fishy fishy taste in the broth.The broth is also lukewarm...Bibim is a good taste.I think it's going to be eaten for about 5,000 won.There is no menu for a child to eat.

 95%|█████████▍| 21234/22421 [06:34<02:50,  6.98it/s]

원본: 3대를 이어온 냉면집,  그 전통은 맛으로 승부한다. 가격은 올라 11000원 이고 사리는 5000원이다, 번역: Cold noodles, which have continued three generations, the tradition is played with taste.The price is up to 11,000 won and the sar is 5,000 won
원본: 불친절함이 극치를 달리네요. 냉면 맛있고 만원 내고 먹는 것도 어디까지나 인정합니다. 근데 서빙 직원 교육 좀 시키시던지 하셔야겠네요. 뭐 좀 물어봤다고 짜증내면서 눈길을 주는 여직원 때문에 맛있는 냉면 맛없게 먹었습니다., 번역: Unkindness is extreme.It is delicious and delicious to eat.But you should do some training staff.I asked you a little bit annoyed and ate a delicious cold noodle because of the annoying female staff.

 95%|█████████▍| 21236/22421 [06:34<03:10,  6.22it/s]

원본: 제가 사진을 잘 찍지 못해서 아쉽네요.서울 여행을 갔는데 숙소가 이 근처였어요. 주말이기도 했지만 가게 앞에 줄이 끝없이 늘어져 있는 것을 보고 이 곳이 엄청난 맛집임을 예감할 수 있었습니다. 저희는 월요일까지 서울에 일정이 있어서 다행히 평일 정오 쯤에 가봤더니 거의 웨이팅 없이 바로 자리에 앉아 냉면을 먹을 수가 있었어요. 건물 전체가 냉면 집이라던데 그래도 손님들이 가득했습니다. 계산은 선불이며, 처음에 육수를 한 주전자 내어주시는데, 모든 이들이 입을 모아 말하는 것처럼 그 맛이 정말 좋습니다. 저희는 비빔만 두 개 주문했는데 물냉면도 많이들 드시더라구요. 담백하면서 깔끔한 맛이었습니다. 양이 적다는 분들도 있던데 저는 배가 불러서 조금 남겼습니다(아무래도 육수 때문인 것 같아요. 제가 거의 다 마셨거든요^^;). 그리고 고기나 회 무침의 양도 넉넉합니다. 비린내 없이 냉면과 잘 어울리구요. 게다가 참기름, 식초 등이 테이블마다 구비되어 있어서 취향대로 냉면을 먹을 수 있다는 점도 인상적이었어요. 특히 참기름을 내어주는 집은 처음 가봤습니다ㅎㅎ 아직도 생각나는 그런 깊은 맛이었네요. 집 근처에 이런 냉면 집 있다면 저도 뻔질나게 드나들 것 같습니다., 번역: I'm sorry that I didn't take a picture well.I traveled to Seoul and the hostel was near here.It was a weekend, but I could see that this place was a huge restaurant after seeing the string in front of the store.We had a schedule in Seoul until Monday, so we went to noon on weekdays and could sit right without waiting and eat cold noodles.The whole building was a cold noodle house, but it was full of guests.The calculation is prepaid, and the broth is initially served as a kettle, and the taste is really good as everyone gathers.We ordered only two bibimbs and had a lot of water noodles.It was light and clean.Some people have a small amount, but I have a boat and left a little (because of the broth. I almost drank;).And there are plenty of meat or sashimi.It goes well with cold noodles without fishy.In addition, it was also impressive that sesame oil and vinegar are available for each table, so you can eat cold noodles as you like.Especially for the first time, I have been to the house that offers sesame oil.If you have such a cold noodles near your house, I think I will come and go.
원본: 냉면 맛은 보장합니다. 다만 너무 사람이 많다보니까 정신없어요 가격은 선불이고 주차는 30분 지원해줍니다, 번역: The taste of cold noodles is guaranteed.However, because there are so many people, the price is prepaid and the parking is supported for 30 minutes.

 95%|█████████▍| 21239/22421 [06:34<02:41,  7.32it/s]

원본: 명성대로 맛은 좋다. 다만 가격대가 착하지는 않다. 직원들 서비스는 보통 수준, 번역: The taste is good as well.The price is not good.Employees service is normal
원본: 주차공간이 불편하지만..아직까지 냉면은오장동흥남집!, 번역: The parking space is inconvenient..So far, cold noodles Eunojang Dongheungnam House!

 95%|█████████▍| 21243/22421 [06:35<02:04,  9.46it/s]

원본: 육향나는 물냉면 너무 좋음!육수 열심히 마시다가 다대기 넣고 비빔처럼 먹음 꿀맛, 번역: The water cold noodles are so good!Drink hard broth and put a lot of rice and eat it like bibim
원본: 오장동의 함흥냉면 중 최고의 맛집, 번역: The best restaurant among Hamheung cold noodles in Ojang -dong

 95%|█████████▍| 21249/22421 [06:35<01:22, 14.20it/s]

원본: 말들 많아도 성지는 성지 양 좀 늘었을려나, 번역: Even if there are a lot of words, the holy place will increase the sheep.
원본: 지점은 허름하고 본점은 새로지은 3층 건물입니다. 이번에 방문한 곳은 지점입니다. 느낌은 여느 중국 도시의 동네 식당 분위기랄까요? 자리 좁고 뭐 물어보거나 부탁하면 친절하지 않은 느낌으로 응대해주고. 바쁘고. 그렇습니다. 그나저나. 잘익은 양꼬치를 쯔란에 찍어서 입에 넣으면.. 이 맛에 양꼬치 먹나 ? 하게 됩니다. 양갈비는 굽기가 어렵고 고기도 잘라야해서 번거롭긴 했지만 위태위태하게 잡내를 비껴가면서 고소한 맛을 느낍니다. 금요일 저녁 때처럼 붐비는 시간에 가면 대기가 있고 특히 차를 가져가게되면 가게앞에 주차하기가 어렵기때문에 공영주차장을 이용해야 합니다. 주차장도 줄서게 되어서 차는 안가져 가는게 낫습니다., 번역: The branch is shabby and the main store is a new three -story building.This time I visited is the branch.Is it feelings of a local restaurant in any Chinese city?If you ask or ask for something narrow, you will be kind.I'm busy.That's right.by the way.If you put a good lamb skewer in Tsuran and put it in your mouth..Do you eat lamb skewers in this taste?You will.Lamb ribs were difficult to bake and the meat had to be cut, but it was cumbersome, but it tasted in jeopardy.If you go to a crowded time as in Friday evening, there is a waiting, especially when you take a car, so you need to use the public parking lot.The parking lot is also lined up so it is better not to take the car.
원본: 양꼬치로 유명한 건대 매화반점에서 양꼬치랑 꿔바로우 먹었습니다. 1인분만 시키면 양꼬치는 따로 구워먹는 시스템이 아니라 주방에서 구워서 가져다 주더라구요. 구워서 먹는것도 재미는 있는데 냄새 안배서 이것도 좋은거 같아요.꿔바로우는 식초향이 좀 있긴 했지만 바삭하니 맛있었어요. 근데 양꼬치 10개에 14000원이라는게 조금 비싸게 느껴집니다. 가격이 좀더 합리적이면 좋을거 같아요. 양꼬치만으로 배채우려고 하면 돈 엄청 나올거 같아요.자리가 많은 편이라서 단체로 와서 회식하고 술모임하기에도 좋고 둘이와도 좋은 곳입니다 시끌벅적한 분위기입니다. 음식도 빨리나와서 좋아요., 번역: I ate lamb skewers at Konkuk Maehwa spots famous for his skewers.If you have one person, the skewer is not baked separately, but it is grilled from the kitchen.It's fun to bake and eat, but I think this is also good.It was a bit of vinegar, but it was crispy.But it's a bit expensive to have 14,000 won for 10 skewers.It would be nice if the price was more reasonable.I think it's going to be a lot of money if I try to put it with a lamb skewer.There are many seats, so it's a good place to come to a group and drink and drink.The food is also good.

 95%|█████████▍| 21251/22421 [06:35<02:01,  9.61it/s]

원본: I will never visit again.It's changed a lot. The meat is not fresh!In 탕수육, it seems they put tomato source, taste is strange.The price is cheaper than other restaurants, but the quantity is smaller.Some dishes are not traditional Chinese taste., 번역: I will Never Visit Again.It's Changed a lot.The Meat is not fresh!In sweet and sour pork, it seems they put Tomato source, Taste is Strange.The Price is Cheaper Than other restaurants, but the quantity is smaller.SOME DISHES Are Not Traditional China Taste.
원본: 건대 유명 양꼬치집매화반점 1호점 2호점이 있으며, 언제나 사람이 많습니다. 양꼬치는 금방 나오며 기본적인 맛입니다. 딱히 특별하지는 않네요. 온면은 고추잔치국수 같은 맛이고. 훈둔은 중국만두라기보다는 한국식인 것 같고요. 기본적이지만 분위기에 먹는 것 같습니다., 번역: Konkuk University's famous lamb is the number one store in the first store, and there are always a lot of people.The lamb is coming out quickly and the basic taste.It's not special.The hot surface is like red pepper noodles.Hundun seems to be Korean rather than Chinese dumplings.It's basic, but it seems to eat in the atmosphere.

 95%|█████████▍| 21254/22421 [06:36<02:31,  7.68it/s]

원본: 여름인데 너무 벽걸이에어컨만으로는 너무 더웠어요. 양꼬치를 먹기엔 너무 더운곳이었네요. 추천메뉴도 맛이 별로였고요, 번역: It's summer, but it was too hot for the wall -mounted air conditioner.It was too hot to eat lamb skewers.The recommended menu also had a good taste
원본: 술한잔 할겸 평일 저녁에 방문했습니다.꿔바로우 가지해물만두 주문했습니다.꿔바로우 최악이였습니다. 해물만두는 그럭저럭 먹을만했습니다..서비스 최악입니다. 첫 주문하려고 벨을 다섯번 이상 눌렀는데도 홀에서 일하시는 분들 서로 미루면서 아무도 테이블로 오지 않았습니다. 자기들끼리 중국말로 얘기하며 서로 떠미는듯?  특히 눈썹문신한 남자 직원 그렇게 일하시면 안됩니다. 손님들이 필요로 벨누르는데 신경질적인 말투와 표정으로 손님응대하고 여직원은 음식 서빙할때 거의 집어던지듯이.. 집게나 가위도 더럽고 .. 최악입니다 왜 사람이많은지 정말 이해가 안되는 식당이었습니다., 번역: I visited a drink and a weekday evening.I ordered seafood dumplings.It was the worst.Seafood dumplings managed to eat..Service is the worst.Even though I pressed the bell more than five times to order the first order, no one came to the table while delaying each other in the hall.It seems that they talk to each other in Chinese and speak in Chinese?In particular, you should not work like that.The guests are nervous, and the guests respond with a nervous tone and expression, and the female employee almost picks up when serving the food..The clauses and scissors are dirty..This is the worst, it was a restaurant that I really don't understand why there are a lot of people.

 95%|█████████▍| 21255/22421 [06:36<02:40,  7.28it/s]

원본: 아시죠? 건대 양꼬치 골목의 핫플레이스^^구관이 명관이라고 주변에 맛있는 양꼬치집, 마라탕집이 쭉 생겼는데도 가끔 이 곳의 양꼬치랑 꿔바로우가 땡기더라구요~양꼬치도 쫄깃쫄깃 맛있지만 무엇보다도 바삭하게 갓 튀겨낸 꿔바로우가 정말 명품입니다. 새콤달콤한 소스에 볶아나온 찹쌀 튀김옷을 살짝 깨물으면 입에 화아악~ 퍼지는 기름진 감칠맛과 함께 쫄깃쫀득바삭한 식감이 이어지죠^^거기다가 고기는 얼마나 두텁고 육즙이 쭉쭉 나오는지~ 흑흑 또 먹고싶네요ㅠ.ㅠ, 번역: Do you know?The hot place pavilion in the alley of Konkuk Skewers is a famous pavilion, but even though there are delicious lamb skewers and mara -tang houses around, sometimes the lamb skewers and the lamb are soaked..If you bite the fried glutinous rice fried in a sweet and sour sauce, it will be angry in the mouth.ㅠ

 95%|█████████▍| 21256/22421 [06:36<02:56,  6.61it/s]

원본: 2층 규모의 넓은 본점도 모자라 근처에 2호점도 생긴, 건대의 유명 양꼬치집. 방송도 몇 번 탔던 걸로 알고 있는데 그렇게까지 기대하고 가면 실망만 큽니다. 근처 왔다가 들리기에 좋은 정도예요. 내부 인테리어는 중국스타일이고 좀 서민적인 분위기입니다.양꼬치는 살짝 매운 양념에 묻혀서 나와서 살짝 매콤한 편이에요. 1인당 10개에 13000원이고, 두명이서 오면 무조건 2인분 시켜야 합니다. 양꼬치 1인분에 다른 요리 1인분 이렇게 못 시킨다는게 좀 아쉬워요. 꿔바로우와 옥수수 울면, 가지튀김 추천합니다.상당히 시끄럽고 정신없는 분위기예요. 식당 앞에 주차할 수 있는 공간이 조금 있고, 화장실은 남녀 구분되어 생각보다 깨끗합니다., 번역: There is also a large headquarters on a two -story floor, so there is a second shop nearby.I know that I have also rode the broadcast a few times, but if you look forward to it, you are disappointed.It's good to come and hear nearby.The interior is a Chinese style and a common atmosphere.The lamb is slightly spicy and spicy.It is 13,000 won per person per person, and two people must be 2 people.It's a bit unfortunate that I can't do it like this for 1 serving of lamb skewers.If you cry and corn, it is recommended.It's quite noisy and crazy.There is a little space to park in front of the restaurant, and the bathroom is divided into men and women and is cleaner than you think.

 95%|█████████▍| 21257/22421 [06:37<03:15,  5.94it/s]

원본: 꿔바로우에 양념이 특이했고 레몬새우는 상큼하고 껍질이 쫄깃쫄깃해서 좋았어요 새우도 엄청 살도많고 탱글탱글 했구요 양꼬치도 잡내가 없고 맛있긴했는데 살이 많은 편이 아니라 금방 타서 딱딱해졌어요ㅠ, 번역: The seasoning was unusual in the boulevard, and the lemon shrimp was refreshing and chewy. The shrimp was a lot of flesh and tangle.

 95%|█████████▍| 21258/22421 [06:37<03:42,  5.22it/s]

원본: 가지튀김, 탕수육과 함께 칭따오 맥주 마셨는데 맛있네요 ㅎㅎ 밑반찬으로 나오는 땅콩도 좋아요, 번역: I drank 오 beer with eggplant fries and sweet and sour pork, but it's delicious

 95%|█████████▍| 21259/22421 [06:37<04:04,  4.75it/s]

원본: 꿔바로우나 양꼬치는 그냥 그랬다여긴 가지볶음이 진짜 맛있다다른건 몰라도 가지볶음은 꼭먹어야한다, 번역: It's just like that, but it's just like that.

 95%|█████████▍| 21260/22421 [06:38<05:35,  3.46it/s]

원본: 건대 양꼬치거리 가게들 중 유명해서 웨이팅이 있는 곳이에요, 번역: It is famous among Konkuk University skewers, so there is a waiting place.

 95%|█████████▍| 21261/22421 [06:38<05:24,  3.57it/s]

원본: 음식은 전반적으로 맛있었는데 사람이 너무 많아 주문이 밀리고 소통이 안됐습니다. 온면은 너무 인그턴트맛이났어요, 번역: The food was delicious overall, but there were so many people that the order was pushed and not communicated.The hot side tastes so ingret

 95%|█████████▍| 21262/22421 [06:38<05:09,  3.74it/s]

원본: 만원대의 가격을 형성하고 있음. 서비스가 약간 불친절한 편...요리들 전반적으로 맛은 괜찮음, 번역: The price of 10,000 won is formed.The service is a bit unkind...The taste is good overall

 95%|█████████▍| 21263/22421 [06:38<04:54,  3.93it/s]

원본: 건대  학생들은  다 안다는 유명한  양꼬치집 그래서 한번  먹으러 가봄. 맛 가격 괜찮습니다. 다만 한국말 하는 중국인이  많아 시끄러운 편, 번역: Konkuk University students know that all of them are famous lamb skewers.Taste price is fine.However, there are a lot of Koreans speaking Korean

 95%|█████████▍| 21264/22421 [06:39<04:48,  4.01it/s]

원본: 가지튀김 맛집이였으나 최근 주방장이 바뀐듯 본점 분점 모두 맛이 없음2019.06, 번역: It was a branch of eggplant, but as the chef has changed recently, the headquarters branch is not good 2019.06

 95%|█████████▍| 21265/22421 [06:39<08:25,  2.29it/s]

원본: 지주가는 양꼬치집먹어본 집 중에 제일 괜찮음어향가지는 처음먹었는데 달짝지근 매콤맛나다, 번역: The landown price is the best of the house I have eaten.

 95%|█████████▍| 21266/22421 [06:40<07:16,  2.65it/s]

원본: 양꼬치 맛집이라던데, 다른 요리들도 꽤나 맛이 좋아요. 건두부 볶음도 맛있습니다., 번역: It's a lamb skewer restaurant, but the other dishes are quite good.Stir -fry is also delicious.

 95%|█████████▍| 21267/22421 [06:40<06:26,  2.99it/s]

원본: 양꼬치 자체는 다른 가게에 비해 맛있지는 않습니다. 다른 요리들이 맛있습니다., 번역: The lamb skewer itself is not delicious compared to other shops.Other dishes are delicious.

 95%|█████████▍| 21268/22421 [06:40<05:49,  3.30it/s]

원본: 듣던대로 무난해요 ㅎㅎ 갈때마다 사람이 많은데 굳이 줄서서 먹을 정도는 아닌것 같은.., 번역: It's okay as I heard..

 95%|█████████▍| 21269/22421 [06:40<05:27,  3.52it/s]

원본: 전반적으로 무난히 맛있고 가지튀김 맛이 인상적이었습니다. 가격도 다른분이 계산했었는데 지금보니 가성비도 괜찮네요.다만 짜장면은 없습니다.서비스는 그냥그냥이에요., 번역: Overall, it was so delicious and the tempura taste was impressive.The price was also calculated by other people, but now it is okay.There is no jjajangmyeon.The service is just.

 95%|█████████▍| 21270/22421 [06:41<05:04,  3.78it/s]

원본: 양꼬치 골목에서 제일 맛있다!일인분만시키면 미리 구워져서 나와서 먹다보면 식기땨문에 항상 2인분을 시킴ㅋㅋ양꼬치외에도 가지튀김 레몬새우 깐풍기 다 맛잇다!ㅎ, 번역: It is the most delicious in lamb skewers!If you have a single person, you can get baked in advance and eat it.he

 95%|█████████▍| 21271/22421 [06:41<04:55,  3.89it/s]

원본: 양꼬치를 미리 구워서 주기 때문에 편하게 술을 마시기 좋은곳 입니다. 이곳은 토마토계란이 가장 맛이 좋습니다., 번역: It is a good place to drink comfortably because it is grilled in advance.This is the most delicious tomato eggs.

 95%|█████████▍| 21272/22421 [06:41<04:44,  4.04it/s]

원본: 평일 주말 가릴꺼없이 예약을 안하면 기본 대기시간 1시간 이상인곳중국인이 관리한는 곳이라 그리 친절하진않음 1층은 매우 북적거리며정신없음 한적한곳을 원한다면 2층으로 예약하길 바람음식은 양꼬치는 뭐 거기서 거기고 다른 서브메뉴가많고 나름 맛있음허나 양꼬치의 메인메뉴 꿔바로우는 정말 맛없는곳, 번역: If you don't make a reservation on weekdays, it's not very kind because the Chinese man managed more than 1 hour of the basic waiting time.There are many other submenus and deliciously, the main menu of lamb skewers

 95%|█████████▍| 21273/22421 [06:41<04:41,  4.08it/s]

원본: 그냥 그래요 일부러 찾아갈 맛집은 아니니 사시는곳 동네에 가까운 양꼬치집 가세요, 번역: It's just that. It's not a restaurant to visit.

 95%|█████████▍| 21274/22421 [06:42<04:47,  3.98it/s]

원본: 이곳이 좋다는건 옛말이 되버림맛ㄹ이나 서비스, 특히 양곡기 신선도가 말이 아니게 나빠짐..강하게 비추.. 후회하지 마시고..., 번역: The good thing is that the old words or services, especially lamb freshness, gets worse..Strongly shine..Don't regret it...

 95%|█████████▍| 21275/22421 [06:42<04:52,  3.92it/s]

원본: 맛있었어요! 너무핫한장소라 가게2곳모두 웨이팅.리스트에이름걸고 10분정도기다린거같네요!재방문의사!, 번역: It was delicious!It's so hot, so two shops are waiting.I think it's about 10 minutes for the list!Return doctor!

 95%|█████████▍| 21276/22421 [06:42<04:44,  4.03it/s]

원본: 양꼬치는 그저그렇고 탕수육은 시키지말것 서비스도 최악인곳 다시는 안간다, 번역: The lamb is just like that, and don't let sweet and sour pork.

 95%|█████████▍| 21277/22421 [06:42<04:35,  4.16it/s]

원본: 맛도 그닥 서비스는 최악, 번역: The taste is also the worst

 95%|█████████▍| 21279/22421 [06:43<04:14,  4.48it/s]

원본: 중국식탕수육 여자친구는 괜춘하다는데 내입맛에별로, 번역: Chinese sweet and sour pork girlfriend is okay, but
원본: 정신없어요작은 중국거리, 번역: The crazy story is China Street

 95%|█████████▍| 21283/22421 [06:43<02:42,  7.02it/s]

원본: 아주오래된 단골집. 30년??맛은 변함없이 최고에 가격도 적당양이 많아도 항상 두그릇씩 먹음, 번역: Very old regular house.30 years?
원본: 까치산의 맛집중 하나.처음에 웹툰을 보고 가게 된 집.전엔 술국달라고 하면 뻐다귀를 더 많이 주셨는데 최근에 가서 주문하니 제 발음이 이상했는지 이모님이 못알아 들으시더라.이집에서 뼈해장국을 시키면 다른곳에선 보기 어려운 통뼈를 가로로 자른것이 나온다.그 사이에 있는 골을 젓가락으로 쑤셔서 쪽쪽빨아 먹으면 여태 감자탕에서 느껴보지 못한 극강의 꼬소함을느낄 수 있다. 개인적으론 이런 육고기에서 오는 꼬소함을 여기서 처음 느껴봤다.이곳은 아마 얼마 만나지 않은 연인이나 썸남썸녀와 함께 가면 먹기 좀 민망 할 수 있을지 모르겠다.개인적으로 이곳은 막걸리 한탁배기에 감자탕이 참 잘어울린다., 번역: One taste of Mt. Kachi.I first went to the webtoon.I asked for a drink soup, but I gave me more crumples, but I recently ordered and ordered me.If you make a bone soup from this house, you will be cut off the bones that are hard to see elsewhere.If you pick up the goal in the meantime with chopsticks and eat it, you can feel the extremes of the extremes that you have never felt in the potato soup.Personally, I first felt the twist from these meat meat here.I don't know if I can eat it with a lover or a thumbnish woman who has never met.Personally, this place goes well with makgeolli.

 95%|█████████▍| 21285/22421 [06:43<02:54,  6.51it/s]

원본: 어렸을 때부터 동네에서 유명한 맛집입니다. 실한 고깃덩이가 올라가요, 번역: It is a famous restaurant in the neighborhood since I was young.The real meat is going up
원본: 그냥저냥 오래된 집이라는 거 말고 음식은 깔끔하지 않은 편, 번역: It's just an old house, and the food is not neat

 95%|█████████▍| 21289/22421 [06:44<02:11,  8.63it/s]

원본: 음식: 맛남. 가격 대비 양은 적음. 서비스: 친절함. 분위기: 패밀리 레스토랑 느낌.위생상태: 깔끔함., 번역: Food: Taste.The price is small.Service: Kind.Mood: Family Restaurant.Hygiene: Neat.
원본: 2회 방문. 건강한 레시피로 요리하지만 아주 맛있게 잘 만든다. 특히 단호박스프는 종종 생각나는 맛이다. 최근에 알았는데 배달도 된다., 번역: Two visit.Cook with healthy recipes, but make it very delicious.In particular, sweets are often remembered.I know it recently, but it can be delivered.

 95%|█████████▍| 21291/22421 [06:44<02:46,  6.78it/s]

원본: 가격은 있지만 좌석이 많고 깔끔한 곳이에요. 조미료를 많이 쓰지 않아 건강한 맛이라 좋아합니다., 번역: There is a price, but there are many seats and clean places.I don't use a lot of seasonings, so I like it because it is a healthy taste.
원본: 단호박 스프 존맛여친이 가고싶다고 해서 왔는데 생각이상으로 조용하고 여친이 추천한 단호박 스프 진짜 존맛!!!, 번역: Sweet pumpkin soup zone taste girlfriend wants to go, but it's quieter than I thought.!!

 95%|█████████▍| 21293/22421 [06:45<03:03,  6.15it/s]

원본: 건강한 파스타를 찾는다면 강추!딱히 좋아하는 메뉴가 없다면... 달달하고 찐~~한 단호박스프와 살짝 매콤한 게살크림파스타를 추천합니다., 번역: If you are looking for a healthy pasta!If there is no favorite menu...Sweet and steamed ~~ I recommend a sweet box and a slightly spicy crab cream pasta.
원본: 빠네파스타가 유명합니다. 빠네파스타는 크림파스타가 빵에 담겨있는 형태로 나옵니다. 소스가 면에도 잘 어울리고 빵과도 잘 어울려서 빵도 반이나 먹었어요. 직원분들이 친절합니다. 사진찍으니 옆 테이블 조명도 켜주시는 등 센스있게 손님에 대한 배려를 잘 해준다고 느꼈습니다., 번역: Panepasta is famous.Pane Pasta comes in the form of cream pasta in bread.The sauce goes well with the noodles and it goes well with bread, so I ate half bread.The staff are kind.When I took a picture, I felt that I was good at caring for the guests, such as turning on the table next to it.

 95%|█████████▍| 21295/22421 [06:45<03:14,  5.80it/s]

원본: 빠네 파는곳 요즘 많이 없죠여긴 '빠네' 맛집입니다. 빠네 먹고 싶으면 여기 오세요.토마토 파스타는 '아마트리치아나' 인데베이컨, 버섯, 매운고추로 맛을낸 매콤한 파스타입니다점심 떄 먹으면 저녁까지 매워요 .'마르게리따 피자' 토마토, 바질, 모짜렐라 치즈로 맛을 낸 이태리 전통피자 입니다다른 곳에 비해 저렴한게 먹을 수 있어서 좋았습니당분위기도 좋았습니다, 번역: There aren't many places these days. This is 'Pane' restaurant.If you want to eat it, please come here.Tomato pasta is 'Amatrich Ana', but it is a spicy pasta that flavored with bacon, mushrooms and spicy peppers.'Margherita Pizza' Tomato, basil and mozzarella cheese. It was a traditional Italian pizza.
원본: 완맛!!! 가성비, 가심비 다 강추에요~메뉴판을 못찍어서 아쉽네요이동네 주차는 그냥 길에 대면 주차관리인이 와서 표 끊어주고 저렴하게 일자주차하는 곳입니다, 번역: Wang!!!It's a good price and a lot of money ~ It's a pity that I can't shoot the menu.

 95%|█████████▍| 21297/22421 [06:45<03:14,  5.79it/s]

원본: 음식은 매우 맛있었어요 분위기도 캐쥬얼하고 크리스마스장식도 예쁘게해놨고 가격도 무난한거같고 But...자리에 앉았을때 새 컵이 놓여저있었는데 립스틱자국이.... 손톱으로 문지르니까 지워지는걸로봐서 설거지는 대충했는듯.. 가시면 컵 확인하고 식사하세요, 번역: The food was very delicious. The atmosphere was casual and the Christmas decoration was beautiful and the price was safe...When I sat down, there was a new cup....I was rubbing it with my nails, so I was washed away..If you go, check the cup and eat
원본: 요즘은 아는 사람이 많아졌지만그래도 나만의 숨겨진 맛집 라치오빠네를 정말 잘하는 곳이다그외에 디아블로,모듬치즈피자도 즐겨먹는다이곳은 내가 가끔 새로운 직장을 다닐때 친해진 직장동료나 여자상사를 데려온다100이면 100 만족 안한 사람은 없었다이사한 뒤로는자주자주 이곳이 생각나도  멀어서 가끔 방문하는데  어느동네어디에서도 이맛을 찾을수가 없다..사장님 장사 잘돼서 부자 되셨으면 좋겠지만 한편으론 나만 알고싶은 맛집이기도 하다, 번역: Nowadays, there are a lot of people who know, but I'm really good at my hidden restaurant Lazi brother. In addition, Diablo and Assorted cheese pizza also enjoyed Daiji.There was no person who was not satisfied, so I often remember it often, so I often visit, but I can't find this taste in any neighborhood..I hope you will be rich because you are good at business, but on the other hand, it is also a restaurant that you want to know.

 95%|█████████▍| 21299/22421 [06:46<03:08,  5.94it/s]

원본: 일단 집에서 가까워서 방문하게 되었고, 빠네 파스타는 살짝느끼하긴 하지만 맛은 좋은 편이었고 디아블로와 같이 먹으니 느끼한 맛을 잡아주어서 좋았습니다., 번역: I was close to the house, and I visited, and the Pane Pasta was a bit feeling, but the taste was good and I ate it with Diablo.
원본: 우연히 문정동 지나다가 파스타가 먹고 싶어 가게 되었는데 생각보다 사람이 많아서 놀랐어요빠네가 유명한 것 같은데 살짝 매콤하고 맛있었어요, 번역: I accidentally passed by Munjeong -dong and I wanted to eat pasta, but I was surprised that there were more people than I thought.

 95%|█████████▌| 21301/22421 [06:46<03:05,  6.02it/s]

원본: 가성비 갑 파스타집 ㅇㅈ 회기에 사는데도 여자친구랑 먹으러 여기까지 자주옴, 번역: Even though I live at the session of the price of the price, I often come to eat with my girlfriend.
원본: -초보자도 도전가능한 깔끔한 마라탕-마라탕집이 집중적으로 모여있는 건대 골목중 가장 평점이 높아 방문한 곳. 보울에 먹고싶은 재료담고 마라탕과 마라샹궈중 선택하면 된다. 마라의 화~한 느낌이 강한편이 아니라, 마라탕 초보자도 거부감없이 도전 가능한 맛-지삼선은 생각보다 그저그랬음. 꿔바로우를 많이 시키던데 그거 시킬걸 그랬다., 번역: It is the highest rating of the Konkuk alleys where the neat Maratang Maratang House is concentrated.You want to eat in the bowl and choose between Mara -tang and Marashang Guo.Mara's anger is not strong, but Maratang beginners can challenge without rejection.I was going to do it a lot, but I was going to do that.

 95%|█████████▌| 21303/22421 [06:46<03:12,  5.81it/s]

원본: 건대 마라샹궈 맛집 웨이팅이 매우 긴편이다먼저 재료를 고르고 주문한뒤 웨이팅하면된다 얼얼한 마라맛과 재료들이 조화롭게 어우러져서 굉장히 맛있다꿔바로우나 가지볶음도 수준급인 편이다, 번역: Konkuk Mara Xiang Guo Restaurant is very long. First, choose the ingredients, order, and wait.
원본: 건대 양꼬치거리에 위치한 마라샹궈 전문점. 다른 업소보다 마라탕 대신 마라샹궈를 상호명으로 내걸고 있고, 입소문타면서 유명해진 곳입니다. 한때는 웨이팅이 길었다고 들었는데 최근 방문했을 때에는 웨이팅없이 들어갈 수 있었어요. (물론 다른 식당에 비해 유독 사람이 많습니다.) 테이블간 간격이 좁은 편이고 테이블이 보통 4인용 이상으로 큰 편이에요.샹궈와 꿔바로우를 시켜 먹었는데, 개인적으로는 가성비 때문에 유명해진 곳이라는 생각이 들어요. 샹궈와 탕도 가성비 좋은 편인데 전체적으로 요리 가격도 저렴한 편입니다. 2-3명이 와서 먹기에 좋은 메뉴 구성이나 가격대가 준비되어 있어 학생들이 많이 찾는 것 같아요.마라샹궈는 맵기 조절에 따라 향 차이가 있겠지만 처음에는 매운줄 몰랐다가 서서히 마라 향이 올라오는 편이에요. 마라샹궈 좋아하시는 분들은 불호로 갈릴 맛은 아니고, 처음 접하시는 분들도 무리없이 드실 만 합니다.꿔바로우는 조금 매콤한 편인데, 마라샹궈나 탕을 먹다가 또 매콤한 음식을 먹으려니 조금 물렸어요. 차라리 담백한 편으로 갔으면 더 반응 좋았을 것 같습니다.• 근처 주차 불가합니다., 번역: Mara Xiango specialty store located on Konkuk University Skewers.It is a place where Mara Xiang Guo is committed to the name of the mara -tang rather than other businesses.I once heard that the weight was long, but when I recently visited, I was able to enter without waiting.(Of course, there are more toxic people than other restaurants.) The intervals are narrow and the tables are usually larger than four people.I ate it with Shang Guo, but I personally think it's famous because of the price.Shang Guo and Tang are also good for money, but the price of cooking is low.2 3 people are ready to eat and have a good menu or price.Mara Xiang Guo may have a difference depending on the spicy control, but at first, I didn't know it was spicy, but then I gradually rises.If you like Mara Xiang Guo, it is not a good taste, and even those who are new to the first time will eat.It's a bit spicy, but it's a little bit bitten by eating a spicy food.I'd rather have been better if I went to a plain side.• It is not possible to park nearby.

 95%|█████████▌| 21305/22421 [06:47<03:03,  6.09it/s]

원본: 지금껏 먹어본 마라샹궈 중 가장 마라향이 센 중국 본토의 맛. 얼얼함이 묘한 중독성을 일으킨다.꿔바로우는 맛있지만 살짝 기름진편. 어쨌든 다소 불친절하고, 주말에는 사람이 많아 식당 안에 멀뚱히 서서 대기 30분을 감수해야하는 점이 마이너스 요인이다., 번역: The taste of the mainland of China, the most mara -shanggual that has been eaten so far.Talance causes strange addictive.It's delicious but slightly oily.Anyway, it's a bit unkind, and there are a lot of people on weekends, so you have to stand in the restaurant and take 30 minutes of waiting.
원본: 3단계여서 코 흘려가며.. 습-하!를 반복해가며 먹었지만 못먹을정도로 맵진않았어요 샹궈는 좀 짠편이어서 마라샹궈 맛집에 빠지지않는다는 명성에 기대를 하고 간거 치고는 사알짝 기대에 못미쳤어요 그래두 맛있었습니다 !, 번역: It's three stages, so I'm shedding my nose..Wet!I ate it repeatedly, but it wasn't so hot that I couldn't eat. Shang Guo was a bit salty, so I was looking forward to the reputation that I wouldn't fall into the Mara Shango restaurant.

 95%|█████████▌| 21307/22421 [06:47<03:14,  5.73it/s]

원본: 2번 갔는데 마라탕 온면 절대 먹지 마세용개 맛없음 마라샹궈는 존맛 ㅠㅠㅠㅠㅠㅠㅠㅠㅠ 근데 기름기가 너무 많구.. 솔직히 좀 비쌈바로 맞은편에 유료 주차장 있는데 거기 할아버지 진짜 양애취임 ㅠ, 번역: I went 2 times, but I never eat Maratang hot noodles..Honestly, there is a paid parking lot opposite the expensive samba.
원본: 마라샹궈와 꿔바로우 맛집이래서 딱 시켰는데 크으><~~~~~ 짱 맛있었어요><!!!! 특히 쫄깃하면서도 세상 바삭한 꿔바로우 꺄><~~~~, 번역: I had to do it because I was a restaurant with Mara Xiang Guo, but it was big> <~~~~~!!!Especially chewy and crispy in the world> <~~~~

 95%|█████████▌| 21309/22421 [06:48<05:29,  3.38it/s]

원본: 한국에서 먹을 수 있는 마라샹궈 가게 중에 가장 본토의 맛이 아닐까 싶습니다. 다만 마라샹궈와 다르게 탕은 단품메뉴로만 시킬 수 있었네요. 중간없이 시큼한 꿔바로우와 매운 가지볶음은 그저 그랬지만 마라샹궈만으로도 다시찾을 집입니다, 번역: I think it's the main taste of the mainland among the Mara Xiang Guo shops that can be eaten in Korea.However, unlike the Mara Shang Guo, the bath was only a single menu.The sour and spicy eggplant stir -fry without the middle was just the same, but Mara Xianggu alone is a house to be found again.
원본: 중국 본토보다 맛있다는 그 집... 저는 한번 방문하고 맛있어서 혼자 또 갔었어요. 밥 시켜먹으면 정말 한그릇 뚝딱 다 먹을 수 있는 밥도둑입니다. 꼭 드세요., 번역: The house is better than mainland China...I visited once and went alone.If you eat it, you can really eat a bowl.Be sure to eat.

 95%|█████████▌| 21311/22421 [06:48<04:15,  4.34it/s]

원본: 불금에 방문해서 시끄러웠지만 맛은 여전히 최고에요. 마라샹궈는 아주 순한맛도 조금 매콤합니다. 벌써 5번째 방문이고 갈때마다 웨이팅은 있어요ㅠ.ㅠ, 번역: It was noisy to visit Bulgeum, but the taste is still the best.Mara Xiang Guo is a bit spicy in a very gentle taste.It's already the fifth visit and there's a waiting every time I go.ㅠ
원본: 건대에서 엄청 유명한 곳이라 기대를 많이 했는데 생각보다 특별하지는 않았습니다., 번역: It was so famous in Konkuk University, so I was looking forward to it, but it was not as special as I thought.

 95%|█████████▌| 21313/22421 [06:49<03:40,  5.02it/s]

원본: 중국맛 그대로임.꿔바로우 훌륭하고 마라샹궈도 훌륭중국유학때 먹은 맛 그대로, 번역: Chinese taste.It's excellent and Marashang Guo
원본: 셋이서 마라샹궈, 꿔바로우 먹었습니당꿔바로우는 양념이 잘 베지 않아 아쉬웠습니다마라샹궈는 좀 짰어요 ㅠㅠ, 번역: The three were Mara Xiang Guo, I ate it.

 95%|█████████▌| 21315/22421 [06:49<03:22,  5.47it/s]

원본: 차이나타운 중심가답게 중식 전반을 취급하지만 단연 시그니처는 마라샹궈! 셀프바에서 재료를 스뎅 그릇(?)에 담으면 그대로 볶아준다. 재료 선도도 좋고 집기도 깔끔한 편.향신료에 민감한 편이라 걱정했는데 마라 특유의 얼얼하고 자극적인 맛보다는 깔끔하게 산뜻한 향미가 강하다. 꿔바로우는 지나치게 산미가 강하고 가지볶음은 짠기가 많은게 흠이라면 흠., 번역: As a center of Chinatown, it handles the entire Chinese food, but by far the signature is Mara Xiang Guo!If you put the ingredients in the self -bar, fry it as it is.The ingredients are good and the pickles are clean.I was worried about the spices, but I had a cleanly flavorful flavor rather than the unique and irritating taste of Mara.If you have too much acidity, and eggplant stir -fry is a lot of flaws.
원본: 정말 맛있게 먹었어요. 양 조절 잘하면 될 것 같아요. 신라면 맛이 생각보다 안맵네여. 근데 전체적으로 너무 짬 ㅠ, 번역: I really ate it.I think you can adjust the quantity well.Shin Ramyun Taste is more spicy than I thought.But overall too much

 95%|█████████▌| 21317/22421 [06:49<03:11,  5.77it/s]

원본: 이미 너무 유명한 곳이지만.. 분기별로 찾아가는 곳입니다. 서울 시내 샹궈 식당 여러 곳 다녀봤지만 불편함, 불친절함 감수하고도 계속 생각나는 집이에요.., 번역: It's already too famous..This is a quarterly place.I've been to the Shang Guo Restaurant in Seoul, but it's inconvenient and unkindly..
원본: 마라샹궈집중에 제일 맛있는 거 같다 건대 다녔으면 자주 갔을 거 같다, 번역: It seems to be the most delicious in Mara Xianggu.

 95%|█████████▌| 21319/22421 [06:50<03:52,  4.74it/s]

원본: 처음먹어본음식인데향같은게강하지않고 맛있네요또방문하고싶어요, 번역: It's the first food I've eaten, but it's delicious without any crab. I want to visit again.
원본: 한국인이 먹기에도 거부감 없는 마라샹궈입니다.먹고 싶은 재료를 고를 수 있어서 좋습니다.꿔바로우도 맛있습니다!, 번역: It is a Marashang Guo that Koreans are not reluctant to eat.It is good to be able to choose the ingredients you want to eat.It's also delicious!

 95%|█████████▌| 21321/22421 [06:50<03:39,  5.01it/s]

원본: 건대 마라샹궈 맛집이래서 갔는데 내 입맛에는 좀 짰으나 과연 맛있는 집, 번역: I went to the restaurant of Konkuk Mara Xiango, but it was a little small in my taste, but it is really delicious
원본: 최애 마라집. 마라탕은 다른데랑 비슷하고 마라샹궈가 간이 아주 세고 맛있음, 번역: Choi Ae Mara House.Maratang is similar to other, and Mara Shang Guo is very strong and delicious

 95%|█████████▌| 21323/22421 [06:51<05:28,  3.34it/s]

원본: 그냥 저냥 맛이나 서비스 보통. 소문만큼 대단한것은 없었음. 다시 갈 의향 없음, 번역: Just taste or service usually.Nothing was as great as rumors.No intention to go again
원본: This is popular Chinese restaurant in China town of 건대.The 마라샹궈 is tasty!Every time if I want to eat 마라샹궈, I choose this restaurant.Now they have second floor, u can order 양꼬치, too., 번역: This is Popular Chinae Restaurant in China Town of Konkuk.The Mara Xiang Guo is tasty!Every TIME IF I Want to Eat Mara Shang Guo, I Choose this Restaurant.NOW The HAVE SECOND Floor, U Can Order Skewers, Too.

 95%|█████████▌| 21325/22421 [06:51<04:17,  4.25it/s]

원본: 명불허전 마라샹궈 맛집! 다녀본 마라샹궈 집 중에서 최고라고 생각합니다., 번역: Myeongbul Heojeon Mara Xiang Guo Restaurant!I think it is the best of the Mara Xianggu house.
원본: 한명당 6천원정도 추가하면 꽤 괜찮은 질의 양고기를 무한리필로 먹을 수 있음. 하지만 마라탕과 온면은 기대이하(특유의 확 땡기는 맛이 없음)., 번역: If you add about 6,000 won per person, you can eat a pretty good quality lamb with infinite refills.However, Maratang and on -surface are below expectations (the distinctive tastes are tasteless).

 95%|█████████▌| 21327/22421 [06:52<03:35,  5.09it/s]

원본: 골라먹는 재미가있는 마라샹궈!! 술안주하기에 적당히 짜고 칼칼해서좋다, 번역: Mara Xiang Guo is fun to choose!!It is good to squeeze it in moderation to snack
원본: 간단한 점심, 저녁식사가 가능한 곳입니다. 체인점 같긴하지만, 다른데서는 딱히 본적이 없네요. 맛은 상당히 괜찮습니다. 마라탕은 매콤하며 고소하지만 우육면이 괜찮습니다. 저한테는 너무 매웠거든요. 멘보샤는 별미. 다른곳에서는 몇만원 줘야하만 여기서 간단하게 즐길수 있는 가격이라 괜찮았습니다, 번역: Simple lunch and dinner are available.It's like a chain store, but I've never seen it elsewhere.The taste is quite good.Maratang is spicy and savory, but the beef noodles are fine.It was too spicy for me.Menbosha is a delicacy.It was okay because it was a simple price that can be enjoyed here.

 95%|█████████▌| 21329/22421 [06:52<03:14,  5.62it/s]

원본: 면발이 굉장히 쫄깃탱탱하고 고기도 듬뿍 들어가서 좋아요.마라우삼겹탕면은 순한맛 중간맛 매운맛 조절이 가능합니다. 마라가 맛이 강렬하다보니 우육면과 같이 먹으려면 우육면 먼저 드시는걸 추천해요.멘보샤도 바삭하고 속은 촉촉탱탱하니 맛있어요., 번역: The noodles are very chewy and the meat is plenty.The marausamgoktang noodles can be adjusted with the mild flavor.Since Mara tastes intense, it is recommended that you eat it first to eat it with the beef noodles.Menbosha is crispy and the inside is moist.
원본: 마라에 면말아 먹고 싶을때 가면좋다. 안맵게하면 맵찔이도 충분히 먹을 수 있음. 마라의 약한버전. 곱창탕면은 곱 냄새 너무 나서 별로였고 우육탕면을 추천., 번역: If you want to eat Mara, you can go.If you don't spicy, you can eat enough map.Mara's weak version.The giblet noodles were so good that it was not so good and recommended the noodles.

 95%|█████████▌| 21331/22421 [06:52<03:06,  5.85it/s]

원본: 홍콩 느낌 물씬 나는 네온사인이 매력있는 라라면가! 향신료 맛이 많이 나고 고수도 더 달라고 하니 넉넉히 주셨어요~ 딴딴면은 매콤하고 우육탕면은 시원하고,양도 푸짐했어요! 멘보샤도 맛있었어요! 군데군데 맛집이 많던데 성신여대 가시면 꼭 들러서 드셔보세요! 추천!!, 번역: Hong Kong feels attractive Lara.It tasted like the spice and asked for more masters.Menbosha was also delicious!There are many restaurants in many places, but if you go to Sungshin Women's University, please stop by!suggestion!!
원본: 새로 생겼는데 멘보샤가 맛있어요 중국식 향 좋아하시는분은 좋아하실것같아요 저는 개인적으로 마라탕을 더 좋아해서.. 꿔바로우는 맛있는 탕수육 느낌이에요, 번역: It's new, but Menbosha is delicious..It's a delicious sweet and sour pork.

 95%|█████████▌| 21333/22421 [06:53<03:09,  5.74it/s]

원본: sns홍보를 많이하길래 다녀옴!워낙 마라를 좋아하기도하고 확실히 마라는 향신료맛이 우리가 일반적으로 먹는 것보다 있음!친구랑 같이먹느라 기본맛먹었는데 안 매움꿔바로우 사이드로 가격나쁘지않고 맛있음멘보샤도 바삭하고 맛있었지만 기름을 많이 머금고있음 먹으면 기름이나옴!전체적으로는 만족한편!, 번역: I'm going to promote SNS a lot!I like Mara so much, and it's definitely a spice taste that we usually eat!I ate the basic taste with my friend, but it's not bad and it's not bad and it's delicious.Overall satisfaction!
원본: 대만에서 먹었던 우육면 보다아아ㅏ 맛있다ㅏㅏㅏㅏㅏ국물이 자꾸 생각나..., 번역: It's more delicious than the beef noodles I ate in Taiwan...

 95%|█████████▌| 21334/22421 [06:53<03:42,  4.88it/s]

원본: 간판부터 맛집포스!! 일반 중국집이랑 다른 맛이에요!!간짜장소스가 다른데보다 덜 기름진 느낌...??난자완스는 호불호가 갈릴 것 같았어요~~, 번역: From the signboard, the restaurant force!!It's different from a regular Chinese house!!It's less oily than elsewhere...?

 95%|█████████▌| 21337/22421 [06:53<02:23,  7.55it/s]

원본: -합리적인 가격대로 즐기는 횟집-키오스크로 주문을 하고 기본적인 세팅을 셀프로 해야하는 곳. 뭘 먹을지 고민하다 추천사시미 + 야채추가-예전에는 술도 근처 편의점에서 사와서 마셨다는데 이젠 술도 판매중. 단, 매장에서 판매하는 소주나 맥주를 제외하면 다른 술종류는 가져올수 있다고 한다. 어쩐지 다른 테이블에선 양주 드시고 있더라..-주문후 금방 회가 나왔다. 연어+참돔+참치+광어 구성.사실 회를 크게 즐기는 편이아니라 비싼건지 안비싼건지 정확하게는 모르지만 나쁘지 않아보였음. 회가 되게 찰지고 신선한 느낌맛있었다!!-배민으로 배달도 되는곳인듯 하다. 이미 동네에선 유명한 곳인듯. 다만, 회같은 메인메뉴만 집중해서 나오기때문에 푸짐한 스끼다시를 좋아하는 분들은 아쉬울수도 있을거 같다., 번역: A place to order with a sushi kiosk that enjoys a reasonable price and self -set.I worry about what to eat. Recommended Sashimi + Vegetables In the past, I bought it at a nearby convenience store.However, except for shochu or beer sold in stores, other types of alcohol can be imported.Somehow, I was eating Yangju in another table..After ordering, the sashimi came out soon.Salmon+red snapper+tuna+flatfish configuration.In fact, I don't know exactly whether it's not expensive or not expensive, but it didn't look bad.It was delicious and fresh!!It seems to be a place where you can deliver it to Baemin.It seems to be a famous place in the neighborhood.However, because only the main menu of the sashimi comes out, it may be a pity for those who like to be rich.

 95%|█████████▌| 21338/22421 [06:53<02:46,  6.49it/s]

원본: 추천사시미랑 매운탕거리 해서 4명이서 배부르게 먹엇어요. 소문만큼 엄청 맛잇는건 아니지만 가성비 좋아요, 번역: Recommended Sashimi and Maeuntang were eaten by 4 people.It's not as so delicious as rumors, but it's good for price

 95%|█████████▌| 21339/22421 [06:54<03:08,  5.74it/s]

원본: 술을 사와서 먹을 수 있는 곳이에요 40분 정도 기다려서 먹었는데 광어는 맛있었는데 연어회가 조금 비렸네요. 시끌벅적한 분위기, 번역: It's a place where you can buy alcohol and eat it for about 40 minutes, but the flatfish was delicious, but the salmon sashimi was a little bity.Loud atmosphere

 95%|█████████▌| 21340/22421 [06:54<03:22,  5.33it/s]

원본: 콜키지 프리인 횟집.일반횟집과다르게 숙성회를 사용하며 모듬회 시스템이 잘 정착돼있다.맛있어요.그러나 서비스가 많이 안좋고  가끔 기분나쁘게하는 응대가 있습니다.요새는 어떻게 변했는지 모르겠네요., 번역: Colkiji Free Sashimi Restaurant.Unlike ordinary sashimi restaurants, assorted sashimi systems are well established.it is delicious.However, the service is not very good and sometimes feels bad.I don't know how the fort has changed.

 95%|█████████▌| 21341/22421 [06:54<03:35,  5.02it/s]

원본: 참다랑어 뱃살(2만7천원)와 연어(1만원)가격 대비 매우 훌륭한 횟집!술과 밥은 팔지 않으니 외부에서 공수해 와서준비된 종이컵에 드셔야 합니다.손님이 많아 번잡하고 화장실이 깨끗하지 않으니 참고 하시구요~, 번역: Very good sushi restaurant compared to the price of tuna belly (27,000 won) and salmon (10,000 won)!You don't sell alcohol and rice, so you have to come from the outside and eat it in the prepared paper cup.There are a lot of guests, and the bathroom is not clean.

 95%|█████████▌| 21342/22421 [06:54<03:41,  4.87it/s]

원본: 황제물회 20,000원, 추천사시미 38,000원사실 황제물회만으로도 충분할 정도의 양에 퀄리티는 정말 대박이다. 이정도의 양과 퀄리티를 제공하는게 가능하다는 것이 말이다.추천 사시미는 입에 들어가자마자 녹아버린다.맛은 당연히 있다. 바다의 내음을 코 끝까지 저렴한 가격에 맛보고 싶다면 최우영수산은 아주 나이스한 선택이 될 것 이다., 번역: The quality of the emperor's sashimi 20,000 won and the recommended sashimi 38,000 yarn emperor sashimi alone is enough and the quality is amazing.It is possible to provide this amount and quality.Recommended sashimi melts as soon as you enter your mouth.Of course it has a taste.If you want to taste the smell of the sea at an affordable price to the end of your nose, Choi Woo Young -suk will be a very natural choice.

 95%|█████████▌| 21343/22421 [06:55<03:50,  4.67it/s]

원본: 맛있습니다 회가진짜싱싱하고 사장님이친절하십니다 꼭오세요 마싯음, 번역: It's delicious.

 95%|█████████▌| 21344/22421 [06:55<04:27,  4.02it/s]

원본: 카운터 대신 자동발매기를 최근 설치. 예전보다 양도 많이 줄은거 같고 더 시끄러워짐. 맛은 여전하지만 그 외 다른부분들은 너무 아쉬운 집. 그래도 가깝다면 한번쯤 들러볼만한 횟집으로 추천함., 번역: Install automatic vending machines instead of counter.It seems to have reduced the amount more than ever before and it becomes noisy.The taste is still still, but the other parts are too sad.Still, it is recommended as a sushi restaurant to visit at least once.

 95%|█████████▌| 21345/22421 [06:55<04:56,  3.63it/s]

원본: 가성비 맛이 베스트입니다.싼 가격에 셀프여서그것마저 최우영수산을 가는 이유가 된다고 할까요?엄밀히 말하면 회가 최상급 맛은 아니지만 싼 가격에 (10점만점에)8점정도의 맛을 느낄 수 있다는 점. 단점이 있다면 차가 없거나 동네 사람이 아니면 교통이 좀.. 최우영일식이랑 햇갈리지 마시길.., 번역: The price is the best.Is it a reason to go to Choi Woo -susan because it's self -priced? Strictly speaking, the sashimi is not the best taste, but it can taste about 8 points at a low price (10 points).The downside is that there is no car or a neighborhood..Don't be sunny with Choi Woo -young..

 95%|█████████▌| 21346/22421 [06:55<04:40,  3.83it/s]

원본: 복불복 웨이팅 있습니다.일단 가격이 쌉니다.(보통 2명이서 회랑 술이랑 3-5만원 정도 소비하고 나옵니다)회 가격이 싸거나 한건 아닌데 외부에서 주류를 구입해서 마시는게 가능해서 회만 사다가 먹기도 좋고, 소주도 싸게 팔아요.대부분이 셀프서비스라 서비스 같은거 기대하시고 가면 실망하실듯.가성비는 좋다고 생각해요., 번역: There is a bokbulbok waisting.The price is cheap.(Usually two people spend about 3 50,000 won.) The price is not cheap or one is not cheap.Most of them are self -service, so if you look forward to the service, you will be disappointed.I think the price is good.

 95%|█████████▌| 21347/22421 [06:56<04:30,  3.97it/s]

원본: 물회 포장으로 자주 사다먹는데요이번거는 낙지가 와사비에 절여져서 못 먹겠더라고요그래서 전화드렸더니 이번에 와사비가 너무 많이 들어갔다고 죄송하다고 하더라고요 그럼 알면서도 파셨다는 건데..미리 얘기도 안해주시고..너무 써서 먹다 말았네요, 번역: I buy it frequently with water sashimi packaging..Don't talk about it in advance..I used it so much that I

 95%|█████████▌| 21348/22421 [06:56<04:52,  3.67it/s]

원본: 모듬회 4만원짜리 먹었는데요, 뭐 딱히 가성비가 좋다는 느낌은.. , 번역: I ate 40,000 won for assorted sashimi..

 95%|█████████▌| 21349/22421 [06:56<04:43,  3.78it/s]

원본: 회 품질이나 맛 좋고, 가격도 좋은데 정신없이 시끄럽고 직원들이 친절하진 않은듯 해요, 번역: The quality, the taste, the price is good, the price is loud, and the staff are not kind.

 95%|█████████▌| 21350/22421 [06:57<04:39,  3.83it/s]

원본: 싸고 맛있네요, 번역: It's cheap and delicious

 95%|█████████▌| 21351/22421 [06:57<04:26,  4.01it/s]

원본: 이젠 무조건포장입니다, 번역: Now it is unconditionally packaged

 95%|█████████▌| 21352/22421 [06:57<04:48,  3.71it/s]

원본: 숟가락 없는 일본식 돈까스 전문점입니다. 방송에도 나왔군요.^^특이한게 샐러드 소스가 2개 있는데 하얀색 요거트 같은 이상한? 소스가 입에 맞더라구요. 같이 가신 분은 안좋아하시는 걸 보니 개인 취향입니다.^^테이블 간격이 좁고 매장 조명이 약간 어두침침한 분위기라 애매한 관계인 분들과 식사하기 좋아요.돈까스나 튀김은 수준급으로 맛있습니다.주차권 보여주면 2시간 지원해줍니다., 번역: This is a Japanese pork cutlet specialty store without a spoon.It was also on the air.There are two salad sauces, but it's like a white yogurt?The sauce fits my mouth.If you go with you, you don't like it.The table is narrow and the store's lighting is a bit dark, so it's great to eat with the ambiguous relationships.The pork cutlet and fried tempura are delicious.If you show the parking ticket, it will support it for 2 hours.

 95%|█████████▌| 21353/22421 [06:57<04:40,  3.81it/s]

원본: 저녁식사끝물에 갔는데도 30분 기다려서 먹었어요. 현장에서 대기해야 하는 맛집!이고 일본 감성의 인테리어는 제 취향에 맞았어요ㅎㅎ너무 기대하고 가면 안되지만(...) 객관적으로 고기가 두툼하고 맛있습니다. 다들 지방이 많이 들어간 로스까츠 선호한다고 하는데 쫄깃쫄깃하고 부드러운 식감이 좋긴했지만 다 먹어갈 즈음에는 조금 느끼했어요. 개인적으로 히레까츠가 더 맛있었고 고기가 살살 녹아요. 샐러드도 엄청 양이 많았고 신선하고 소스도 맛있었습니다. 새콤한 소스가 더 저에게 더 맞았어요.재방문하고 싶은 곳이고 돈가스 좋아하시는 분들에겐 추천합니다!주차는 2시간 주차권주십니다., 번역: Even though I went to the end of dinner, I waited for 30 minutes.Restaurant to wait in the field!And the interior of the Japanese sensitivity was suitable for my taste.Everyone prefers a lot of fat, but the chewy and soft texture was good, but I felt a little at around.Personally, the Hireca was more delicious and the meat melts.The salad was so large, and the fresh and sauce was delicious.The sour sauce was more suitable for me.It is recommended for those who want to return to visit and those who like pork cutlet!Parking is recommended for 2 hours.

 95%|█████████▌| 21354/22421 [06:58<04:43,  3.77it/s]

원본: 머리카락나옴, 직원 태도 부적절한 식당18.04.05(금) 점심 값 지불하고 먹은 후기입니다. 주문한 안즈 정식에서 “머리카락? 눈썹?”이 나와서 클레임을 제기하였으나, 직원의 최초 사과는 없었고, 한참 지나서 사과하는 태도가 매우 불량하였습니다. 또한 사과 하지 않음에 대응이 부족해서 아쉽다는 컴프레인제기에 안즈는 줄서서 먹는 맛집 부심으로 건성건성 오기 싫으면 오지마라는 느낌을 받았습니다.돈까스가 맛있어 점심에 자주 갔었지만, 이젠 돈내고 먹든, 누가 사줘서 먹든 가지 않을 것 같네요!문제가 있으면, 사과부터 하는게 순서인듯한데 태도도 별로고 기분도 좋지 않았습니다.음식값은 지불하고 먹고왔고, 후기 적을 권리는 있는거 같아 참고하시라고 남깁니다!직원 서비스 정신은 필요 없고 돈까스만 맛있게 드시고 싶으시면 방문해도 괜찮을 것 같습니다!안즈가 먹고싶으면 다른 안즈 가는게 나을듯 합니다! 후기는 실제 방문 경험에 대한 것이며, 후기에 대한 문제제기가 있다해도 자삭 하지 않고, 관련 법에 근거하여 삭제 또는 문제 제기 받겠습니다., 번역: Hair comes out, staff attitude inappropriate restaurant 18.04. 05 (Fri) This is a review of paying lunch.“Hair?Eyebrows? ”I filed a claim, but there was no first apology from the staff, and after a long time, I was very bad.In addition, the compression system, which is unfortunate that there is not enough response to not apologizing, I felt that I would not come if I didn't want to come to dry health.The pork cutlet was delicious, so I went to lunch often, but now I don't think I'll go to eat it or buy it!If there is a problem, it seems to be the order of apples, but the attitude was not very good.I have eaten the food price, and I think I have the right to pay for the reviews!If you don't need the spirit of employee service and you want to eat only pork cutlet, you will be able to visit!If Anzu wants to eat, it's better to go another Anzu!The reviews are about actual experience experience, and even if there is a question about the reviews, we will not be self -determined, and we will be deleted or raised based on the relevant laws.

 95%|█████████▌| 21355/22421 [06:58<04:32,  3.91it/s]

원본: 로스까스가 유명하다해서 먹었는데 맛있었음그 가격에 맛없기도 힘들긴 하지만 어쨌거나 육질 부드럽고 튀김옷도 ㄱㅊ안심의 경우는 정돈보다 좀 더 질감이 살면서 촉촉한 느낌돈까스 소스는 맛없음시그니처인 특등심은 가격이 3만원대던데 돈까스를 이 돈 주고 먹는 건 너무 에바같아서 굳이 재방문할까 싶음그리고 음악소리가 커서 그런건지 지하라 울려서 그런건지 엄청 시끄럽고 말하는거 하나도 안들림, 번역: I ate it because it was famous because it was famous, but it was hard to taste it, but it was hard to taste it, but anyway, the meat is soft and the fried clothes are soft.It's too Eva to eat this money.

 95%|█████████▌| 21356/22421 [06:58<04:22,  4.05it/s]

원본: 전반적으로 단맛이 적은 점이 장점으로 느꼈습니다. 메인과 사이드가 잘 어울러져 만족스러웠습니다. 고기 부위가 비싼 카츠와 보통 둘 다 각각의 맛이 있어 돈이 아깝다는 느낌은 아니었습니다만 비싸다는 느낌은 있었습니다., 번역: Overall, I felt the advantage of the low sweetness.The main and the side were good and satisfactory.Katsu, which is expensive in the meat, usually had its own taste, so I didn't feel it was a waste of money, but I felt expensive.

 95%|█████████▌| 21357/22421 [06:58<04:18,  4.12it/s]

원본: 비싸다하지만 맛있다적절하게 지방이 씹히는 히레까스꼭 히레까스를 먹어야하고, 늦게가면 품절도 된다, 번역: It's expensive, but it's delicious. You must eat Hireca, which is chewy in the fat, and if you go late, it can be sold out late.

 95%|█████████▌| 21358/22421 [06:59<04:14,  4.18it/s]

원본: 종로에 위치한 일본식 돈카츠맛집 안즈! 가격이 비싸지만 맛은 있음, 번역: Anzu, a Japanese -style Donkatsu restaurant located in Jongno!The price is expensive but it tastes

 95%|█████████▌| 21360/22421 [06:59<03:09,  5.61it/s]

원본: 가격도 적당하고 돈까스도 맛있어서 평가가 좋은 곳. 언제 가도 먹을 만 하다., 번역: The price is reasonable and the pork cutlet is delicious.It is worth eating anytime.

 95%|█████████▌| 21361/22421 [06:59<03:20,  5.29it/s]

원본: 넘넘 맛있었어용 ~~~가지 가지 했어용............, 번역: It was so delicious............

 95%|█████████▌| 21362/22421 [06:59<03:30,  5.03it/s]

원본: 맛있다 맛있다요   가지 카츠 맛있다     또간다, 번역: It's delicious, it's delicious.

 95%|█████████▌| 21364/22421 [07:00<03:27,  5.08it/s]

원본: 얼큰 물 냉면은 고추가루 맛이 진하게 나고 매운맛이 뒤늦게 올라옵니다. 유명한 집인지 웨이팅이 있었습니다., 번역: Eolken water cold noodles are rich in red pepper powder and spicy tastes late.There was a waiting for a famous house.
원본: 줄서서먹어야합니다 맛집인듯사람마다다르겠지만 저는 쫄깃한식감이 싫어서 딱히.., 번역: I have to eat in line, but it will be different as it is a restaurant, but I don't like chewy Korean food..

 95%|█████████▌| 21366/22421 [07:00<03:14,  5.44it/s]

원본: 응암시장 속으로 가야 있는 집입니다계산하고 음식만드는곳과 손님들이 앉아서 먹는 곳이 다름..개그맨도 많이 다녀간 집인데 가격대비하면 맛있고 매우 먹을만한 곳이나 굳이 멀리서 찾아올 정도인지는 모르겠음매운 냉면은 3단계까지 있는데 1단계도 생각보다 많이 매우므로 주의, 번역: This is a house that goes to Ngam Market..I have a lot of gagmen, but I don't know if it's a delicious and very good place to eat, but I don't know if it's a distant place.
원본: 불광천을 앞에둔 응암에 보기드문 힙한 카페. 인테리어도 예쁘고  창이 커서 날씨좋은날 방문하면좋다. 커피맛은 무난했다., 번역: A rare cafe in Ngam, which is ahead of Bulgwangcheon.The interior is pretty and the window is large, so you can visit the day.The coffee taste was okay.

 95%|█████████▌| 21367/22421 [07:00<03:08,  5.60it/s]

원본: 카페분위기는 깔끔하고 바로앞에 불광천이 이쁘긴한데 티라미수는 너무 가벼운 맛이었음. 커피는 평범하게 오케이. 플랫치노는 약간 산미,쓴맛이 강했음. 산미가 강해 호불호 갈릴 듯. 풍경보면서 얘기하고 먹기는 좋을 듯. 공간이 넓진 않아서 각 테이블 대화소리가 너무 정확히 들렸음. 그리고 2층은 와이파이가 잘 안터짐ㅠ., 번역: The cafe atmosphere is clean and the Bulgwangcheon is pretty in front of it, but the tiramisu was too light.Coffee is usually OK.The flatcino was a bit acidic and bitter.The acidity is so strong that I think it's going to be dislike.It would be nice to talk and eat while looking at the landscape.The space was not spacious, so each table conversation sounded too accurately.And on the second floor, Wi -Fi doesn't open well.

 95%|█████████▌| 21369/22421 [07:01<04:49,  3.63it/s]

원본: 커피맛 너무 좋아요, 우연히 지나가다 들렸는데 한잔 사서 산책하면 좋을 것 같아요, 실내는 좀 좁아서 이미 사람들로 꽉찼더라구요, 하지만 실외 테라스도 있어서 앉을자린 있어요! 인테리어도 감각적이었어요! 친절도 하심, 번역: The coffee tastes so good, I heard it by chance, but I think it would be nice to buy a drink and walk.The interior was also sensational!Kindness
원본: 유명한 곳이라서 기대를 했는데 플랫화이트는 탄 맛이 많이 났고 케이크 종류는 너무 가벼워서 제 스타일은 아니었습니다. 다만 가격은 합리적이었고 2층 창가에 앉으면 불광천이 내려다보여서 날 좋은 날 친구랑 가면 좋을 것 같아요. 노래 선곡은 그냥 그렇습니다. 그런데 왜 매장 내에서 먹어도 케이크 종이상자+일회용 커피용기를 주시는지는 잘 모르겠네요. 낭비같고 환경에 도움안 될 것 같아서 조금 찝찝했어요., 번역: I was looking forward to it because it was famous, but the flat white tasted a lot and the cake was so light that it wasn't my style.However, the price was reasonable, and when I sat by the window on the second floor, I would look down at Bulgwangcheon, so I would like to go with a good day with a good day.The song selection is just like that.But I don't know why I eat cake paper box+disposable coffee container.It was a waste and it didn't seem to help the environment.

 95%|█████████▌| 21371/22421 [07:01<03:52,  4.51it/s]

원본: 카페 인테리어가 깔끔해서 좋았어요. 밀크티는 무난했고, 레몬 파운드 상큼하고 맛있어요., 번역: The cafe interior was neat.Milk tea was okay and lemon pound is fresh and delicious.
원본: 지나가다가 들린 카페분위기가 좋다. 내부는 협소하나 작은 공간을 예쁘게 꾸며 논 느낌여름엔 외부에 앉을 수 있게 되어 있어서 좋다.맛은 훌륭하다. 메뉴가 많진 않지만 가볍게 앉아서 담소 나누기 좋다.이 동네에서 갈만한 카페는 이 곳인 듯, 번역: The atmosphere of the cafe was good while passing by.The interior is narrow, but it is good to be able to sit outside in the summer.The taste is great.There aren't many menus, but it's good to sit lightly and chat.The cafe worth going in this neighborhood is like this place

 95%|█████████▌| 21373/22421 [07:02<03:23,  5.16it/s]

원본: 매장에 식물이 많고 깔끔하고 예뻐요:-) 밀크티도 달고 맛있었습니다!, 번역: There are plenty of plants in the store and clean and pretty :) Milk tea is sweet and delicious!
원본: 여의도 직장인이라면 대부분 알고 있는 맛집. 재료도 메뉴도 단순하기 때문에 서빙이 엄청 빠르다. 회전이 빠르기 때문에 버섯과 미나리가 신선하고 무한 리필이 가능하다. 칼칼한 국물은 해장에 좋고 두툼한 칼국수 면이 식감이 정말 좋다. 남은 국물에 볶아먹는 볶음밥은 당연히 맛있다. 지금은 여의도를 떠났지만 종종 생각나는 음식점 중에 하나이다., 번역: Most of Yeouido office workers know.The serving is very fast because the ingredients and menus are simple.Because the rotation is fast, mushrooms and buttercups are fresh and infinite refilled.The broth is good for haejang and the thick kalguksu noodles are really good.The fried rice, which is fried in the rest of the broth, is of course delicious.Now I have left Yeouido, but it is one of the restaurants that I often think of.

 95%|█████████▌| 21375/22421 [07:02<03:06,  5.61it/s]

원본: 우선 버섯 매운탕이라니, 너무 깔끔하고 맛났습니다. 무한리필된다는 점이 아주 매력적인데 맛도있어요.  맛집 답지 않게 친절하신 이모님들도 인상깊었구요, 번역: First of all, mushroom spicy soup was so clean and delicious.It's very attractive to be infinite, but it's also delicious.I was also impressed with the kind aunt who was not like a restaurant.
원본: 여의도에서 분기마다 한번 이상은 꼭 먹는 버칼. 양도 많고 무한리필이니 싫어할 수가 없다. 얼큰해서 술 안주로도 많이 먹나보다. 식당 자체가 커서 회식으로 오는 팀도 많아보이고 한국인이라면 좋아할 정도의 얼큰매콤이라 호불호 안갈리고 다들 좋아한다. 다 먹고 죽 까지 먹어야되는데 보통 여기 다녀온 날은 탄수화물 폭탄 맞고 오후에 엄청 졸리다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 맛있고 쌈!, 번역: A ruckal that eats more than once in Yeouido.There is a lot of amount and infinite refills, so I can't hate it.It's so spicy and eaten as a snack.The restaurant itself is so big that there are many teams coming to the dinner, and if you are Koreans, they don't like it.I have to eat it all, but I usually go here.

 95%|█████████▌| 21377/22421 [07:02<03:04,  5.66it/s]

원본: 1. 여의도에서 가성비로 따라갈 집이 있을까...?2. 버섯, 미나리, 칼국수, 죽까지 무료 리필이라는 극강의 장점3. 육수가 좀 자극적이긴한데 내 입맛엔 딱, 번역: 1. Is there a house to follow in Yeouido?..?2.Mushrooms, buttercups, kalguksu, and porridge to the extreme advantage of free refills 3.The broth is a bit irritating, but it's perfect for my taste
원본: 여의도에 숨어있는 샤브샤브맛집 가양칼국수버섯매운탕! 고기추가가 좀 비싸용, 번역: Shabu -shabu gourmet restaurant Gayang Kalguksu mushroom spicy soup hidden in Yeouido!The addition of meat is a little expensive

 95%|█████████▌| 21378/22421 [07:02<03:08,  5.53it/s]

원본: 맛있고 양도 푸짐하다ㅎㅎ 만천원에 밥까지 볶아먹을 수 있는 혜자맛집, 번역: It's delicious and the amount is also rich ㅎㅎ Huge restaurant that can be fried with rice in all thousand won

 95%|█████████▌| 21382/22421 [07:03<02:59,  5.79it/s]

원본: 여의도에서 이만한 가성비 맛집 찾기는 정말 힘든듯. 다만 가게가 지하에 있어서 처음 가는 사람은 찾아가기 힘들 것으로 보임. 일단 메뉴를 시키면 칼국수, 버섯, 미나리 등이 모두 무제한 리필이 가능하다는 점이 매우 매력적임., 번역: It is really hard to find such a good value for restaurants in Yeouido.However, the first person to go to the basement seems to be difficult to visit.Once you have a menu, you can refill unlimited refills for kalguksu, mushrooms, and buttercups.
원본: 양이많고 같이 친구나 데이트음식으로 부담없이 좋은것 같아요 맛은 다른지점이랑 비슷해요, 번역: I think it's a lot of amount and it's easy for friends or dating foods. The taste is similar to other branches.

 95%|█████████▌| 21384/22421 [07:04<02:51,  6.05it/s]

원본: 둘이서 하나 시키면 배부르게 잘먹을 수 있어요 어떤 메뉴든 무난하게 맛있네요, 번역: If you do one, you can eat well.
원본: 양도 많고 맛도 좋아요 공간도 좋고 가격도 좋고 여럿이 가기 좋아요., 번역: The amount is good and the taste is good.

 95%|█████████▌| 21386/22421 [07:04<02:48,  6.15it/s]

원본: 후토마끼가 인상적인 곳. 초밥은 맛있었지만, 가게배치가 타이트한데 옆테이블이 너무 시끄러워서.. 복불복이었겠지만 제가 간날은 그랬습니다. 주차는 가게 앞 1~2대 가능한 듯 합니다., 번역: Futomagi is impressive.The sushi was delicious, but the shop was tight, but the side table was so noisy..It must have been a bokbulbok, but I did it.Parking seems to be one or two in front of the store.
원본: 비싸지 않은 가격에 퀄리티 높은 스시를 맛 볼 수 있습니다., 번역: You can taste high quality sushi at an expensive price.

 95%|█████████▌| 21391/22421 [07:04<01:36, 10.70it/s]

원본: 자주 가는 식당은 아니지만(생선회보단 고기를 좋아해서) 어쩌다 보니 철중행사 하듯 가게 된 식당입니다.-좋은 점처음 갔을 때도 두번째 갔을 때도,항상 맛있고 다른 집과는 확실히 질이 다르다고 느끼게 되는 회와 초밥입니다.저렴하다고 할 수 있는 가격대는 아니어도 우니(성게알), 고등어회 뭐 여러가지 맛보면 재료가 진짜 좋고 음식에 손이 많이 갔다고 보여집니다.-아쉬웠던 점단품대신 줄곧 세트 메뉴만 먹었었는데코스식으로 한 접시에 초밥 여러개 나오고, 또 한 접시 나오고 그런식입니다.초밥 5개가 나오면 다섯가지 종류가 다 다른데 이게 알고보니 왼쪽에서 오른쪽순으로 먹는다던지, 흰살생선이 먼저인지 붉은살이 나중인지 그런 순서같은 게 있더라고요.코스요리로 나오는 만큼 먹는 순서가 있다면 미리 알려주시는 것도 좋을 것 같아요꼭...먹고 있으면 오셔서 저것부터 먼저 먹는거라고 나중에 말씀해주실 때 있어요.테이블이 좁아서 빈 그릇 금방금방 치워주시는 거 좋은데 제발 다 먹은접시만 치워주셨으면 해요.메인메뉴에 비해 사이드식으로 나오는 거라도 천천히 먹는 거일수도 있는데 물어보지도 않고 치워준다면서 바로 가져가니 넋놓고 있다가 주방에 들어가시는 거 보고 아...치우셨구나 하고 알았어요테이블에 단무지같은 거 접시 수 줄인다고 저랑 제 맞은편에 있던 사람 꺼 물어보지도 않고 상치우듯 덜어합치는데 기분 좀 나빴네요.단점을 많이 쓰게 됐지만 서비스가 별로라는 건 절대 아닙니다!! 계속 홀 보시면서 부족한 거 자꾸 채워주려고 하시고 다만 급하셔서 그랬는지 조금 더 신경써주셨으면 하는 마음으로 후기 남깁니다.저렴한 가격은 아니지만 그만큼의 맛과신선함이 있으니 꼭 가보셨으면 하는 식당이에요.진짜진짜 맛있고 초밥 별로 안 좋아하는데 여기서는 다먹어요ㅠㅠ사진첨부한 거는 후토마끼라는 것인데 왕 큰게 역시 왕 맛있습니다.다른분들도 가보시고 후기 많이 올려주세요!!, 번역: It's not a restaurant that goes often (I like meat rather than fish), but it is a restaurant that goes like an iron event.It is sashimi and sushi that is always delicious and always feels different from other homes when you go to the second time.Even if it's not a price range that can be said to be cheap (sea urchin) and mackerel sashimi, the ingredients are really good and the food is a lot of hands.I had only a set menu instead of the unfortunate steaming product.When five sushi comes out, there are five different types of sushi, but it turns out that I eat it from the left to right, or whether the white meat is first or red flesh.If you have the order to eat as much as it comes out as a course dish, it would be good to let me know in advance...If you are eating, come and eat that first.The table is narrow, so it's good to get rid of the empty bowl quickly.Compared to the main menu, even if it comes out in the side type, it can be eaten slowly...I knew you were cleared, I felt a little bad to combine it as if it were soaked without asking me to reduce the number of dishes like a radish.I have a lot of disadvantages, but it's not that the service is not good!!I keep looking at the hole and keep trying to fill what is lacking, but I want you to pay more attention to if you were in a hurry.It's not an affordable price, but it has the taste and freshness, so I want you to go.It's really delicious and I don't like sushi, but I eat it all here.Please visit others and post a lot of reviews!!
원본: 근처에 볼일이 있어 들렸는데 오픈전부터 대기 손님이 있었습니다. 다행히 오픈하자마자 들어갈수 있었지만 오픈 시간에 맞춰 오신분들은 대기했던것 같습니다. 맛은 솔직히 기다리면서까지 먹고 싶다거나 하진 않고 평범했습니다. 호기심에 시킨 츠루우메유즈슈가 정말 맛있었습니다., 번역: There was something to see nearby, but I had a waiting guest before the opening.Fortunately, I could go in as soon as I opened it, but I think people who came to the opening time waited.The taste was honestly waiting and I didn't want to eat it.The curious Tsuru Meuzu was really delicious.

 95%|█████████▌| 21393/22421 [07:05<02:01,  8.49it/s]

원본: 비주얼은 좋은데 맛이 비주얼을 못 따라간다. 한 번쯤 가볼 만한 곳., 번역: The visuals are good, but the taste can't follow the visuals.At least once.
원본: 근래에 갓던 곳중 가장 음식다운 음식이엇다 흔히 조합해서 만드는 프렌차이즈가 아니다 줄을 서야한다는 단점은 잇지만 감수할만할 정도의 맛이다, 번역: It was the most food -like food that I have been in recent years, but it is not a franchise that is commonly combined, but the disadvantage is that it should be lined up, but it tastes good enough.

 95%|█████████▌| 21394/22421 [07:05<02:10,  7.90it/s]

원본: 말해 무엇하리. 내 최애 이자카야.오마카세를 즐기는 편인데 숙성된 회를 먹으면 어느정도 오마카세 사시미의 맛이 난다. 사장님은 워커힐 쉐프 출신이며 최근엔 MBC 생활의 달인에도 방영 됐다. 군자 주민이라면 이이요가 유명해 지는게 싫을 정도. 안그래도 웨이팅이 많은데 더 많아져서 요샌 잘 못 간다....힝, 번역: What do you do?My favorite Izaka.I enjoy Omakase, but when I eat aged sashimi, it tastes like Omakase sashimi.The boss is from Walkerhill Chef and recently aired as a master of MBC life.If you are a soldier, you don't want to be famous.I don't have a lot of weight, but I'm not good at it....Hing

 95%|█████████▌| 21396/22421 [07:06<05:23,  3.17it/s]

원본: 가격은 좀 비싸고 그에 비해 양이 적기는 함.. 하지만 맛은 정말 끝내준다. 한번만 가지는 않을 이 곳, 가끔만 간다면 내 지갑도 그렇고 여러모로 괜찮다., 번역: The price is a bit expensive and the amount is small..But the taste is really awesome.This place will not be once, and if you go sometimes, my wallet is fine in many ways.
원본: 너무 맛있다. 술을 좋아하는 사람들에게는 깔끔한 안주로서, 미식가들에게는 풍성한 재료의 맛을 그대로 느낄 수 있는 곳이다., 번역: Too delicious.For those who like alcohol, it is a clean snack, and for gourmets, it is a place where you can feel the taste of rich ingredients.

 95%|█████████▌| 21398/22421 [07:07<04:24,  3.87it/s]

원본: 1회 방문. 연어 뱃살이 아주 기름지고 부드럽다. 치즈 계란말이도 꼭 드셔보세요. 마끼는 서비스로 받음., 번역: One visit.Salmon belly fat is very oily and soft.Be sure to eat cheese egg rolls.Maki receives as a service.
원본: 맛있게 잘 먹었네요~밥양이 적은건 어쩔수 없지만서비스 우동이 배를 채워주니 좋네요~, 번역: I ate it well ~ I can't help it with a small amount of rice, but it's good to fill my stomach.

 95%|█████████▌| 21400/22421 [07:07<03:47,  4.48it/s]

원본: 생활의 달인에 나온 군자역 맛집이라고해서 찾아감. 후기대로 오픈시간 30분전쯤에 갔는데 우리 다음부터 웨이팅 길어짐.맛은 다 맛있었음., 번역: It is said that it is a restaurant in Gunja Station in the master of life.I went around 30 minutes before the opening time, but since we have longer we have longer.The taste was all delicious.
원본: 진짜 맛있었어요 제가 살면서 먹은 돈부리중 최고였어요 마끼도 맛있었구요 그런데 분명 다른 후기에는 사이드에 작게 우동이 나온다고 되어있었는데 혹시 몰라 물어보니 안나온다 해서 튀김우동을 따로 시킨거였는데 알고보니 원래 주는거였고 알바생의 실수로 다른 음식을 먹을수 있었던걸 튀김우동으로 시킨거라 당황했어요 그래도 튀김우동에 튀김들 정말 푸짐하게 들어가있었어요 다음에는 연어덮밥을 먹어보려구요 그리고 12시 오픈인데 11:20분 부터 사람들 줄 기다리고 있습니다 그래서 첫번째에 못들어가시면 40~1시간은 기다리셔야해요 그러니 일찍 가서 기다리고 계신거 추천드려요, 번역: It was really delicious. It was the best of the money I ate in my life. Maki was also delicious.I was embarrassed because I was able to eat food, but I was embarrassed.I have to wait an hour, so I recommend you to go early and wait.

 95%|█████████▌| 21402/22421 [07:07<03:22,  5.04it/s]

원본: 친구동네여서 함께 방문한 이이요손님이 온다면 무조건 데려간다고 했다기본적으로 다 맛있다, 번역: If you are a friend's neighborhood, if you visit together, you will take it unconditionally.
원본: 분위기도 딱 좋고 맛도 깔끔했어요 소문난 맛집 답습니다, 번역: The atmosphere was just good and the taste was clean.

 95%|█████████▌| 21404/22421 [07:08<03:09,  5.36it/s]

원본: 일본식 덮밥이랑 마끼가 유명한곳인데덮밥도 맛있지만 마끼가 정말정말 맛있음!!마끼에 꼭 연어추가해서 먹기를!, 번역: Japanese rice bowls and maki are famous, but the rice bowls are delicious, but the maki is really delicious!!Make sure to add salmon to maki!
원본: 크기도 크고 긴 좌석이 있어서 모임, 회식으로 좋은 강남역의 서가앤쿡입니다.둘이서오면 가격이 저렴하다고는 못느끼는데, 여럿이 올때 정말 가성비가 괜찮다고 느끼는 것 같아요. 전부 다 배부르게 먹었습니다! 별로인 메뉴 없이 무난하게 다 평균 이상이었다고 생각해요. 직원분들도 역시 친절하셨어요, 번역: There is a large and long seat, so it is a good Gangnam station in Gangnam Station with a meeting and a dinner.If you come, the price is cheap, but when you come, I think the price is really good.I ate everything full!I think it was more than average without the menu.The staff were also friendly

 95%|█████████▌| 21406/22421 [07:08<03:04,  5.49it/s]

원본: 깔끔하고 당연히 맛있었습니다 모듬 한상에 새우 필라프 먹는데 맛있었어요 필라프 먹고 싶을 때 꼭 오는 곳이에요, 번역: It was clean and of course delicious.
원본: 7-8년 전에 인기있던 식당인데 오랜만에 갔습니다. 세트를 주문하면 나오는 가니쉬 때문에 양이 많습니다., 번역: 7 8 years ago, it was a popular restaurant.If you order a set, there is a lot of sheep because of the garnish.

 95%|█████████▌| 21408/22421 [07:08<03:05,  5.47it/s]

원본: 목살스테이크랑 감자튀김이 넘 맛있어요 새우 필라프는 매워서 많이 못먹었네오ㅜㅜ, 번역: The neck steak and fried potatoes are so delicious.
원본: 일단 개인접시부터 내가 양식당에 온건지 병영식당에 온건지 햇갈릴정도로 흠집, 파손되있는 접시를 그대로 줌.토마토 해산물 리조또를 시켰는데 내가 오뚜기 케챺밥을 시킨건지 햇갈릴정도로 존나달고 캐챺맛 밖에안남. 심지어 조개에서 비린내 오지게남. 오리엔탈 샐러드는 그냥 시키지마셈. 답이없음집 뒤뜰 고사리캐다가 오리엔탈소스 뿌려먹는게 더 좋을듯왠만하면 돈주고 먹는 밥 안남기고 다 먹는편인데서가앤쿡 강남점은 정말 최악요즘 장사가안되는 이유가 충분히 있다.여기서 여자친구와 식사를 같이할 생각이면 차라리 근처에있는 신의주 찹쌀순대집가서 오징어순대에 순대국밥을 먹는게 정신건강에 좋으니 참고하세요., 번역: From a private plate, I was aquisitive and destroyed as I came to the aquaculture or a barracks restaurant.I made a tomato seafood risotto, but I only had Ottogi Kekongbab.Even the fishy smell from the shellfish.Don't just let the oriental salad.There is no answer. It would be better to eat the oriental sauce after digging the house of the house.If you are going to have a meal with your girlfriend, it's good for mental health to go to Sinuiju Glutinous Sundae House and eat Sundae Gukbap in Squid Sundae.

 95%|█████████▌| 21409/22421 [07:09<03:10,  5.31it/s]

원본: 무난한 채인점. 둘이서 먹기 좋은 목살한상은 언제나 가서 먹을만 하다, 번역: Good place.Hansang, which is good to eat, is always good to go and eat

 95%|█████████▌| 21410/22421 [07:09<06:31,  2.58it/s]

원본: 양이 푸짐해서 여럿이서 가면 딱 좋은 곳이에요. 맛에 기복이 없어서 한번도 실망한 적 없어요., 번역: It's just a good place to go to many people.I have never been disappointed because there is no ups and downs.

 95%|█████████▌| 21411/22421 [07:10<05:40,  2.96it/s]

원본: 목살스테이크 맛 굳굳!!게살 파스타도 맛있었습니다직원들도 친절하시고!, 번역: The neck steak taste good!!The crab pasta was also delicious.

 95%|█████████▌| 21412/22421 [07:10<05:06,  3.29it/s]

원본: 새우와 고기를 좋아하는 나에겐 최고의 맛집다만 여러개를 한번에 먹기 좋아하는 나에겐 둘이가든 혼자가든 애매한 양..셋넷이 가야 어러개를 제대로 맛보기 좋아 아쉬워요, 번역: For me who likes shrimp and meat, the best restaurant is the best way to eat several at once..It's a shame that Setet Net must go to taste it properly.

 96%|█████████▌| 21413/22421 [07:10<04:41,  3.58it/s]

원본: 위생, 서비스 둘다 넘 별로임. 음식은 그냥저냥 평타인데 강남역에 널린게 파스타 피자집인데 굳이 여기올 필요 없음. 특히 요리를 쟁반에 담아 서빙해야 하는데 그릇을 알바들이 하나하나 손으로 날라서 알바생들 손가락이 음식에 담궈짐. 대기도 길고 음식이 나오는데까지 기다리는 시간도 김. 손님에 비해 주방및 홀에 직원이 넘 적고 매니저도 없는듯. 주방이 오픈형이던데 썩 위생적인 환경으로 보이지도 않았다, 번역: Hygiene, both services are not good.The food is just a flat hit, but it's a pasta pizza restaurant in Gangnam Station.In particular, the dishes must be served in a tray, but the bowls are flying one by one, so the Alba lives are soaked in food.Long waiting for food and waiting for food.Compared to the guests, there are fewer employees in the kitchen and hall and no manager.The kitchen was open, but it didn't look like a very hygienic environment.

 96%|█████████▌| 21414/22421 [07:10<04:29,  3.73it/s]

원본: 두명이서 14일 숙성 삼겹살 2인분에 밥두개 된장찌게 구성으로 점심 식사를 하였는데 역시나 삼겹살의 맛은 굿!!!! 서비스도 집접 온도 체크하고 구워주시니 편하고 좋네요!!반찬들도 깔끔하게 잘나오네요. 한가지 아쉬운거는 역시나 가격... 요즘 전반적으로 비싸지긴했지만 150g 16000원은 살짝 높은 감이 없지 않네요~ 가격만 빼고는 추천!!, 번역: On the 14th, I had lunch with two rice pork belly for 2 servings on the 14th.!!!It is comfortable and good to check the service temperature and bake the service!!The side dishes come out neatly.One thing that's unfortunate is the price...It's expensive overall these days, but the 150g 16000 won is not slightly high.!

 96%|█████████▌| 21415/22421 [07:11<04:22,  3.84it/s]

원본: 결론부터 말하자면 보통이다. 2명 가서 삼겹살만 총 4인분 시켜 본 결과 칼집 삼겹살 느낌으로 가격대비에는 맛은 있으나 오히려 살짝 비싸다는 느낌이고 숙성이라는데 별 차이 없어보였다. 그리고 파채가 없고 콩나물 무침인데 개인적으로는 별로 였다. 돼지고기가 제법 들어간 기름진 김치찌개는 이집에서 먹은것 중 제일 맛이 좋은 편이었다. 맛없는 집은 절대 아니고 보통 이상 정도는 될듯함., 번역: The bottom line is usually.After two people, only four servings of pork belly, and as a result of the feeling of cutting pork belly, the price was tasted, but it was a bit expensive and it was ripening.And there was no green onion and bean sprouts, but personally, it was not good.The oily kimchi stew with pork was quite tasted in this house.It is never a tasteless house, but it seems to be abnormal.

 96%|█████████▌| 21416/22421 [07:11<04:17,  3.91it/s]

원본: 고기도 잘 구워주고 질도 좋은 동네 맛집이라 자주 갔는데 최근에 좀 변한 느낌... 가격은 올랐는데 고기 잘 못 굽는 알바가 구워주기도 하고 밑반찬도 줄어든 느낌이고 직원들이 다소 불친절함., 번역: I baked the meat well and I often go to a good neighborhood restaurant...The price has risen, but Alba, which is not baked well, feels that the side dishes are reduced, and the staff are somewhat unkind.

 96%|█████████▌| 21417/22421 [07:11<04:07,  4.06it/s]

원본: 삼겹살을 숯불에 구워 먹는 곳인데 넓은 홀도 있고 3층엔 룸으로 된 모임 과 술 모두 가능한 곳입니다. 물론 삼겹살의 맛은 굉장히 맛있는 곳이구요... 사이드 반찬은 별로 없지만 딱 고기와 곁들일 반찬들로 구성되서 아주 맛있게 잘 먹고 왔습니다. 다음에 또 가보고 싶은 곳이네요..., 번역: It is a place where pork belly is grilled on charcoal fire.Of course, the taste of pork belly is very delicious...There aren't many side dishes, but it is composed of side dishes and side dishes.It's a place I want to go next time...

 96%|█████████▌| 21418/22421 [07:11<04:04,  4.11it/s]

원본: 14일 숙성 삼겹살 먹었는데 처음은 괜찮은데 먹을 수록 짠 거 같아요, 번역: I ate aged pork belly for 14 days, but the first time I eat it, the more I eat it, the more it looks.

 96%|█████████▌| 21419/22421 [07:12<07:25,  2.25it/s]

원본: 손님보다 종업원이 더 많은곳고기건드렸다가는 종업원에게 혼날수도 있다. 고기는 쏘쏘한데 약간 오바하는 느낌을 주는 장소.광고 및 많은 종업원을 감안하면 비싼 가격은 필연적, 번역: There are more employees than customers, and they may be scolded by employees.The meat is a shot, but it feels a bit overwhelming.Considering advertising and many employees, expensive prices are inevitable.

 96%|█████████▌| 21422/22421 [07:12<03:59,  4.17it/s]

원본: 닭갈비집입니다. 맛있습니다. 양념이 색다르진 않고 일반적인 양념을 맛있게 만든 것 같습니다. 조리하는데 20분정도 걸립니다. 미리 전화하고 오시면 바로 먹을 수 있습니다. 전화하고 오시길 추천드립니다. 자리는 입식과 좌식 둘 다 있습니다., 번역: Chicken ribs.Delicious.The seasoning is not different and the general seasoning seems to be delicious.It takes about 20 minutes to cook.If you call in advance, you can eat it right away.I recommend you to call.There are both seats and seats.

 96%|█████████▌| 21423/22421 [07:13<03:58,  4.19it/s]

원본: 들어가면 향긋한 닭갈비 냄새가 나기 시작하는 집입니다.맛은 더할나위 없구요. 이 근처 사는 동안 많은 음식을 먹어봤는데 산골닭갈비는 이 근방 닭갈비중에 최고에요😚일단 미리 전화하면 사장님께서 닭갈비를 미리 조리해주셔서 가자마자 바로 먹을 수 있는 점이 좋아요! 꼭 드셔보세요!, 번역: It is a house that starts to smell fragrant chicken ribs.The taste is so great.I've eaten a lot of food while living here, but the mountain chicken ribs are the best in this nearby chicken ribs.Please try it!

 96%|█████████▌| 21424/22421 [07:13<04:14,  3.92it/s]

원본: 클래식 닭갈비 좋아하시는 분이라면 찾아오셔도 될집. 그런데 직원분들 쏘 시크하십니다., 번역: If you like classic chicken ribs, you can come.But the staff are chic.

 96%|█████████▌| 21425/22421 [07:13<04:06,  4.03it/s]

원본: 강변 최고 맛집;;너무 맛있고 양도 많고거기전에 미리 전화해서 준비부탁드리면 요리 시작해놓으셔서 가자마자 딱 시간맞춰서 음식 먹을수 있어요라면사리 우동사리 다 맛있습니다, 번역: The best restaurant in the riverside ;; It's so delicious and very delicious, and if you call me beforehand, please start cooking and you can eat it as soon as you go.

 96%|█████████▌| 21426/22421 [07:13<04:02,  4.10it/s]

원본: 2호점도 1호점 못지않게 맛있어요 가격도 저렴하고 맛도 있고 밥볶아먹으니 넘나리 맛나요  콜라서비스받았답니당, 번역: The second store is as delicious as the first store.

 96%|█████████▌| 21427/22421 [07:14<04:01,  4.11it/s]

원본: 오래된 집인지 깔끔하진 않지만 담백하니 괜찮았어요. 금욜저녁에 갔는데 대기가 있었어요, 번역: It's an old house, but it's okay because it's light.I went to the evening of Friday and there was a waiting

 96%|█████████▌| 21430/22421 [07:14<02:30,  6.60it/s]

원본: 여기는 파이가 고급진 맛인데단거안좋아하시는분은 펌킨파이추천!!!초코케이크는 꾸덕이에 브라우니인데 초코케이크는 맛에 비해 가격이 높아용 그래도 케이크짱♡선물용으로도 추천, 번역: This is the pie's luxurious taste, but if you don't like it, Pumpkin Pi is recommended!!!Chococake is a brownie in a cake, but the chocolate cake is high compared to the taste.

 96%|█████████▌| 21431/22421 [07:14<02:53,  5.70it/s]

원본: 반지하? 느낌나는 곳에 위치해서 이색적이었어요 카페도 이뿌고 가격은 조금 쎄지만 맛도 좋아용, 번역: Ring?It was unusual because it was located in a place where it was located.

 96%|█████████▌| 21432/22421 [07:14<03:04,  5.37it/s]

원본: 크림모카 여전히 역대급이지만, 처음 도전해보는 블루지도 맛있었다. 라떼랑 뭐가 다를까 했는데, 엄청 가벼우면서도 커피 맛은 진해서 정말 신기햇다! 거기에 달달해서 당이 당길 때 좋다#홍대 홍대카페, 번역: Cream mocha is still in history, but the first blue map was also delicious.I thought it was different from the latte, but it's so light and the coffee tastes so amazing!It is good when the party is sweet because it is sweet#Hongdae cafe

 96%|█████████▌| 21433/22421 [07:15<03:18,  4.98it/s]

원본: 원두를 구매하는데 직원분의 친절하고 상세한 설명에 기분이 좋았어요! 시그니처메뉴중 블루지를 마셔봤는데 얼음이 들어가지 않은 시원한 음료였어요! 달달한 맛이 나는데 물리지 않고 아주 부드러웠어요. 친구는 바닐라라떼 마셨는데 블루지 한입 마셔보더니 너무 맛있다고 했어요 ㅎㅎ, 번역: I felt good about the staff's friendly and detailed explanation to buy beans!I tried to drink blue from the signature menu and it was a cool drink without ice!It tastes sweet, but it was very soft.My friend drank vanilla latte, but I drank a bite of blue and said it was so delicious.

 96%|█████████▌| 21434/22421 [07:15<03:26,  4.78it/s]

원본: 테일러카페 대표메뉴인 크림모카랑 아인스페너를 주문했다크림이 달달해서 꿀맛ㅠㅠ 크림모카는 마시면 차가운크림 아래로 따뜻한 커피가 같이 들어와서 신기하다아인스페너도 마셔봤는데 아메리카노랑 크림의 조화가 good!!같이 간 친구들은 더위사냥같다고도ㅋㅋㅋㅋ가격이 좀 비싸긴 하지만 가끔 이런 커피도 마실만 할 듯!, 번역: I ordered Cream Mocha and Einspenner, the representative menu of Taylor Cafe.!The friends who went with me are like a heat hunting.

 96%|█████████▌| 21435/22421 [07:15<03:36,  4.55it/s]

원본: 펌킨파이 맛있습니다커피는 너무 맛있어서 이야기하는동안 두번이나 주문해서 마셨습니다, 번역: Pumpkin Pi is delicious. The coffee is so delicious that I ordered twice while talking.

 96%|█████████▌| 21436/22421 [07:15<03:41,  4.44it/s]

원본: 크림모카가 유명한 곳입니다. 내부가 좀 좁지만 야외좌석이 있습니다., 번역: Crimean mocha is famous.The interior is a bit narrow, but there is an outdoor seat.

 96%|█████████▌| 21437/22421 [07:16<03:40,  4.45it/s]

원본: 조용하고 굉장히차분했습니다. 소개팅하기에 매우 적합했습니다.1호점의 경우 좁을수도있습니다.3호점이 2층이라 넓고좋습니다.햇빛도 이쁘게 잘들어왔고...혼자 계신분들 친구랑오신분들연인이 오신분들항상 자리를 꽉채우기보단 80~ 40퍼를 유지합니다. , 번역: It was quiet and very calm.It was very suitable for a blind date.In the first store, it may be narrow.The third store is on the second floor, so it is wide and good.The sunlight came in pretty well...Those who are alone and those who come with friends come to 80-40 fur rather than filling their seats.

 96%|█████████▌| 21438/22421 [07:16<03:40,  4.45it/s]

원본: 매장이 작고 사람이 많아서 분위기는 아쉬웠지만 커피맛은 좋았다, 번역: The atmosphere was unfortunate because the store was small and there were a lot of people, but the coffee taste was good.

 96%|█████████▌| 21440/22421 [07:17<05:09,  3.17it/s]

원본: 크림모카, 플랫화이트맛은 있다 비싸다 오래 앉아있을곳은 아니다  정신없다 테이크아웃 하면 2000원 할인, 번역: Cream mocha, flat white taste is expensive. It's not a place to sit for a long time.
원본: 구석에 있어서 찾기가 어렵지만 또 찾아가는 재미가 있음. 맛있어서 이태원 어디가지 목록 중 하나. 하지만 준비할 수 있는 양이 정해져 있어서 잘 나가는 날은 안되는 메뉴가 많음 ㅠ 그래두 좋아요~, 번역: It's hard to find in the corner, but it's fun to visit again.It's delicious, so one of the lists of Itaewon.However, there are many menus that are not good because there is a fixed amount to prepare.

 96%|█████████▌| 21442/22421 [07:18<05:23,  3.02it/s]

원본: 립맛집입니다. 립이란 요리 자체가 단순하기 때문에 미국식 립보다는 한국 고깃집을 선호합니다. 그러다가도 가끔 엄청난 화력의 장작불에 겉을 태우듯이 바베큐해서 달달한 소스에 찍어 손으로 잡아 뜯어 먹는 미국식의 립이 생각날 때가 있습니다. 여기서 고기 뜯고 있으면 식당 이름처럼 내재된 원시인의 본능이 살아나는 느낌입니다. 사이드 메뉴들도 맛있습니다. 가격대가 좀 있지만 음식들이 해비해서 어차피 많이 먹기는 무리가 있습니다., 번역: Lip restaurant.Because the cooking itself is simple, I prefer Korean pork houses rather than American lip.Then, sometimes, sometimes I think of an American lip that is burned on a barbecue on a huge firewood fire and dip it in a sweet sauce and eat it by hand.If you are tearing the meat here, the instinct of the inherent primitive man is alive as the restaurant name.The side menus are also delicious.There's a little price range, but the foods are harvested, so it's hard to eat a lot anyway.
원본: 엄청 좁다. 테이블 간격이 가까워서 좀 시끄럽다. 그러나 특유의 이태원스타일 가게 분위기가 나쁘지 않아서 연인과 가기 괜찮다. 가격은 적당한편이고 고기가 맛있었다., 번역: Very narrow.It's a bit noisy because the table interval is close.However, the unique Itaewon style shop is not bad, so it's okay to go with a lover.The price was appropriate and the meat was delicious.

 96%|█████████▌| 21444/22421 [07:18<04:03,  4.01it/s]

원본: 바베큐에서 립은 매니멀스모크하우스가 최고라고 생각합니다, 번역: In the barbecue, I think the lip is the best manimals mok house.
원본: 보통 짜기마련인데 간이 좋음육질도부드럽고 매우맛있음, 번역: It is usually weaved, but the liver is good, the quality of the meat is soft and very delicious

 96%|█████████▌| 21446/22421 [07:18<03:27,  4.70it/s]

원본: 간이생각보다 세지만맛은잇어요 가격대비 비싼듯한ㅠ메인도 시켰지만 피클부족시 추가해서먹어야해요, 번역: It's stronger than I thought, but it tastes good. It's expensive for the price.
원본: 식당 위쪽으로 좀 더 올라가면 슬라이스 파는 매장이 따로 있는데 메뉴가 메인 식당보단 다양하지 않고, 판이 아니라 슬라이스로 판매합니다. 간단히 먹을 때는 여기도 좋을 것 같아요. 개인적으로는 더 맛있어서 슬라이스 집을 더 선호합니다., 번역: If you go further up the restaurant, there is a separate slice of slices, but the menu is not more diverse than the main restaurant, but it is sold as a slice, not a plate.I think it would be nice to eat simply.Personally, I prefer the slice house more because it is more delicious.

 96%|█████████▌| 21448/22421 [07:20<07:02,  2.30it/s]

원본: 친척동생과의 데이트!! 2차로 피맥을 할까하여 들르게 된 곳, 분위기가 정말 베리 굿 이였다.창쪽에는 외국인 분들도 있으셨고, 수제 피자라 그런지 맛깔나게 보여서 하프로 2가지 맛 시키고, 맥주도 1잔씩!!자리가 문 바로 옆이라서 조금 어수선하긴 했으나 그래도 생맥주의 너무 시원한 맛과 기름진 피자의 어울림이 그만이였던 곳이다. 다시 한 번 더 가야겠다., 번역: Date with your relative!!The atmosphere was really berry good.There are also foreigners on the window, and it's a homemade pizza, so it's delicious.!It was a little cluttered because it was right next to the door, but it was a place where the draft beer was so cool and the oily pizza.I have to go again.
원본: 조각피자만 파는 매장이 있고 판으로 피자를 파는 매장이 있으니 구분해서 가셔야합니다. 미국식 피자를 잘 구현해냈고 Margherita 에 토마토 소스를 충분히 발라서 맛있습니다., 번역: There is a store selling only a piece of pizza and a store that sells pizza with a plate.It is a good implementation of American pizza and is delicious because it has enough tomato sauce to Margherita.

 96%|█████████▌| 21450/22421 [07:21<06:23,  2.53it/s]

원본: 수요미식회에서 극찬해 찾은 이태원길 서쪽 끝자락에 위치한 Pizzeria!음식 후기 보다 우선 이태원을 차로 갈 때 중요한 주차에 대해서...우선 강남쪽에서 간다면 한남대교로 가기 보다는 반포대교로 가는 걸 극추천. 주차/발레 제공 안하며 Gino''''s의 친절한 매니저/오너? 말씀이 앞길에 세우면 8만원짜리 티켓이 연중 부과된다고!Tip: Gino''''s 빌딩을 오른쪽으로 끼고 한 30미터 가다 GS25를 끼고 왼쪽으로 약 40미터? 가면 유료주차장 보임. 30분당 2천원의 매우 저렴한 금액으로 주차가능.Gino''''s,  역시 방송을 타서 그런지 기다리는 사람들이 한 10명 정도 있었음. 우리 2인이라 운좋게 바로 착석. 뭘 시킬줄 몰라 추천하는 윙과  반반(half&half) 피자로  주문하고 드링크는 진저애일. 기대를 가지고 기다리던 피자가 나옴. 스피내치 알프레도와  이탈리언 소시지를 올린 토마토 소스베이스 반반피자가 나옴. 레드소스 피자는 소스의 물이 토마토소스와 물이 분리되서 도우가 흥건히 젖었음. 서버가 잠깐 왔길래 살짝 언급했더니 매니저?가 바로옴. 매니저가 즉시 미안하다 하고 주방장?까지 호출. 주방장 "%$%^&*&^% "라며 설명. 갑자기 우리 둘은 영어로 왜 이 피자가 흥건할수 있는지 아니면 왜 안되는지에 대해서 공방. 끝에 미안하다며 다시 내올수 있다함. 우린 공손히 거절. food: 개인적으로 향 좋은 치즈를 써 굿. 하지만 결코 NY스타일은 아닌 좀 딱딱하고 두꺼운 도우임. 도우에 지방성분의 오일이나 라드를 많이 넣어서 크로쌍정도로 도우가 반짝임.  윙은 간이 좀 짰지만 만족할만한 수준. 알프레도 피자가 더 맛있었음 service: 서버및 매니저 매우 매우 친절했음ambience: 바짝 붙인 테이블에  꽉차인 분주한 분위기에 벽돌 인테리어는 전형적인 피자펍을 연상시킴.price: 피자+윙+1드링크=4만천원결론: NY Pizza를 기대한다면 비추천.  Gino''''s만의 꽤 괜찮은 피자집임., 번역: Pizzeria is located at the west end of Itaewon -gil!First of all, when I go to Itaewon, more important parking...First of all, if you go from Gangnam, you are going to Banpo Bridge rather than going to Hannam Bridge.GINO '' '' S's friendly manager/owner does not provide parking/ballet?If the Word is set in front of the road, the 80,000 won ticket will be charged throughout the year!TIP: GINO '' '' 30 meters to the right with the S Building to the right, wearing GS25 about 40 meters to the left?If you go to a mask, you can see the parking lot.Parking can be parked at a very low price of 2,000 won per 30 minutes.GINO '' 'S, and there were about 10 people waiting for the broadcast.We are lucky to be seated right away.I don't know what to do, and I order with the recommended wing and half and half pizza.The pizza that was waiting for expectations came out.Half -half pizza of Tomato Source Base with Spinnari Alfredo and Italian sausages.Red source pizza is soaked in the water of the sauce and the water is separated from the tomato sauce.The server came for a while, so I mentioned a bit.The manager is immediately sorry and calls the chef.chef .%$%&&%.Explain.Suddenly, we both of us why this pizza can be excited or why it is not.I'm sorry at the end and I can come back again.We refuse politely.Food: Personally, I use the fragrant cheese.But it's never NY style, but it's a bit hard and thick.Put a lot of oil or rads of fat in the dough, so the dough is sparkling.Wing is a little bit of a liver but satisfactory level.Alfredo pizza was more delicious: server and manager was very friendly Ambience: The brick interior reminiscent of a typical pizza pub.PRICE: Pizza+Wing +1 Drink = 40,000 won Conclusion: Ny Pizza If you look forward to non -recommended.GINO '' 'S is a pretty good pizza.
원본: 정말 미국스러운 피자맛이예요 분위기도 힙하고,진짜 맛있어요ㅠㅠ 진짜 강추, 번역: It's really American pizza. The atmosphere is hip and it's really delicious.

 96%|█████████▌| 21455/22421 [07:21<02:23,  6.71it/s]

원본: 다른 갈비탕에 비해 깊은맛을 느낄 수 있었음.  고기는 연하고 국물은 진하다, 번역: I could feel deeper than other ribs.The meat is light and the broth is thick

 96%|█████████▌| 21457/22421 [07:21<03:01,  5.31it/s]

원본: 서빙이나 주문받을때는 괜찮은데, 계산할때 총얼마인지도 말을안해주고 감사합니다 말도안하고 카드만 휙가져가고 정말 계산만 틱틱합니다. 한두번이 아니라서 기분이 나쁘네요. 좀 잘되니 초심을 잃은것같기도하고요. 계산할 때는 좀 친절하게 해줬으면 합니다., 번역: It's okay when serving or ordering, but when you calculate it, you don't even tell you that you don't even know that you are. Thank you.I feel bad because it's not once or twice.It's a little good, so I think I lost my initial.I want you to be kind when you calculate.
원본: 갈비탕드셈. 포장도하셈. 벗뜨 격식있는식사아님 한정식은 생략.  소갈비는 비쌈. 맛도 좋음. 서비스 나쁘다고생각안함. 주말 웨이팅있음. 한정식은 두어달전에 예약해야함., 번역: Galbi Tang.Packaging.The formal meal is omitted.Beef ribs are expensive.Good taste.The service is bad.Weekend waiting.Hansik should be booked a couple of months ago.

 96%|█████████▌| 21459/22421 [07:22<02:58,  5.39it/s]

원본: 무난한 갈비탕 맛인데 유명세만큼 맛있지는 않아요.. 가격에 비해선 별로인듯, 번역: It's good, but it's not as delicious as it is famous..It seems to be as good as compared to the price
원본: 갈비탕의 육수가 진하지만 가격이 비싼걸 감안한다면..., 번역: Galbi -tang's broth is strong, but the price is expensive...

 96%|█████████▌| 21463/22421 [07:22<01:54,  8.34it/s]

원본: 갈비탕 맛있는데 비싸요., 번역: It's delicious, but it's expensive.
원본: 소세지가 들어있는 빵이랑 올리브 치아바타 먹었는데 너무 맛있게 먹었어요! 크고 분위기도 너무 좋아서 또 빵문하고 싶어요, 번역: I ate bread with sausage and olive ciabata and I ate it so delicious!I want to do it again because it is so big and the atmosphere is so good

 96%|█████████▌| 21465/22421 [07:22<02:10,  7.31it/s]

원본: 빵이 정말 맛있고 음료는 별로였습니다. 겨울이라 야외에 못앉아봐서 아쉽습니다., 번역: The bread was really delicious and the drink was not good.It's a pity that I can't sit outdoors because it's winter.
원본: 카페 규모도 크고 빵도 넘 맛있었던 은평한옥마을 카페예요~~ 가격이 좀 비싸서 자주는 못 갈거같은데, 풍경도 좋고 널찍해서 한번쯤 가기 좋습니다 ㅎㅎ 도심 속 힐링 플레이스예요, 번역: It's a big cafe and a delicious bread.

 96%|█████████▌| 21467/22421 [07:23<02:25,  6.55it/s]

원본: 찾기 어렵고 지하에다, 입구부터 이국적인 커다란 그림이 설치되어있어 장벽이 높아보이나 들어가고나선 전반적으로 아주 만족스러웠습니다.저는 2인 세트를 주문했는데 메뉴 구성이 아주 좋았고 모두 잘 나왔습니다.초심자가 즐기기 좋은 메뉴들부터(2인 세트의 구성) 인도, 네팔 현지식까지 메뉴가 다양한 점도 좋은것 같아요.가게는 다양한 그림들과 현지 뮤직비디오가 나옵니다.점원분들도 모두 외국분들인데 의사소통이 충분히 잘되고 친절하셔서 전혀 불편함이 없었어요.금색 식기들에서 쇠맛이 나는 점은 아쉬웠어요.가격이 좀 오르긴 했지만 그럼에도 아직 타 체인점보다 저렴한 편이라 재방문할 예정입니다., 번역: It was difficult to find, and in the basement, the exotic large paintings were installed from the entrance, so the barriers seemed to be high, but they were very satisfied overall.I ordered a set of two people, but the menu was very good and all came out well.I think there are a variety of menus ranging from menus for beginners (composition of two sets) to India and Nepal.The store offers a variety of pictures and local music videos.All of the clerks are foreigners, but they are well communicated and friendly, so there was no inconvenience.It was a pity that it tasted in gold dishes.Although the price has risen a bit, it is still cheaper than other chain stores, so I will return to visit.
원본: 인도음식치고는 향이 강하지 않아서 누구나 쉽게 즐길수 있는 곳이구요 익숙하지 않는 메뉴들이라 주문이 어려울수도 있는데 직원분이 친절하게 설명해주시지 걱정하지 않고 방문하셔도 됩니다세트메뉴가 광장히 가성비 좋은 편이에요 !, 번역: It is a place that anyone can enjoy easily because it is not strong for Indian food. It may be difficult to order because it is unfamiliar.

 96%|█████████▌| 21469/22421 [07:23<02:31,  6.27it/s]

원본: 이국적인 느낌을 경험하고싶다면 근처에 찾아가도 괜찮을듯하다 탄두리치킨이 생각보단 덜퍽퍽하고 양념도 먹을만했다 치킨 머커니 커리는 순하고 부담없이 괜찮았다, 번역: If you want to experience an exotic feeling, it's okay to go nearby.
원본: 입구가 다소 허름하고 지하에 위치해있어 첫인상은 별로였으나, 들어가보니 이국적인 분위기에 손님도 많은 편이었습니다.치킨마크니는 맛있었고 머턴커리는 매웠어요(맵기 표시가 안되어있어서 아쉬웠습니다)매장 분위기는 다소 시끌벅적하고 네팔 아이돌?같은 뮤비와 노래가 연속재생되었습니다다른 커리집보다 가격이 저렴한 점이 매리트 같아요, 번역: The entrance was somewhat shabby and located in the basement, so the first impression was not good, but when I went in, I had a lot of customers in an exotic atmosphere.Chicken Macney was delicious and Mutton Curry was spicy (I was unfortunate because it was not a spicy).

 96%|█████████▌| 21471/22421 [07:23<02:50,  5.58it/s]

원본: 인도커리 먹어본적이 없었는데 처음 접해봤던 집이에요! 한국인들 입맛에도 잘 맞고 외국인들도 많이 찾는 집입니다!, 번역: I haven't eaten Indian Curry, but it's my first time!It is a house that fits well with Korean tastes and foreigners are looking for a lot!
원본: 3명이서 3인세트 시켰는데, 배부르게 먹었어요~ 치킨도 맛있고 음료가 생각보다 엄청 맛있었어요! 가게 분위기가 이색적이어서 좋았고 직원분들 친절하셨어요, 번역: I had a three -person set for three people, but I ate it with a full ~ Chicken was delicious and the drink was so delicious!It was good because the atmosphere was exotic and the staff were kind.

 96%|█████████▌| 21473/22421 [07:24<02:44,  5.77it/s]

원본: 다양하고 맛있는 네팔요리를 저렴한 가격에 먹을 수 있어서 좋아요!특히 양고기 커리가 만족입니당, 번역: It's great because you can eat a variety of delicious Nepal cuisine at an affordable price!Especially lamb curry is satisfied
원본: 가격도 저렴하고 맛있어요~일부러 찾아가서 먹을정도네요~분위기도 이국적이고 점원들도 외국인이라 인도에 온 기분이나요, 번역: The price is cheap and delicious ~ I go to and eat on purpose ~ The atmosphere is exotic and the clerks are foreigners.

 96%|█████████▌| 21475/22421 [07:24<02:39,  5.93it/s]

원본: 커리: 맛있습니다. 개인적으로 난과 함께 드시는 걸 추천합니다. 난은 기본을 비롯해서 마늘 등 다른 맛을 추가하여 즐길 수 있습니다.탄두리 치킨: 퍽퍽합니다.음료: 밀크 쉐이크 느낌이 듭니다. 굉장히 맛있습니다., 번역: Curry: It's delicious.Personally, I recommend eating with me.I can enjoy it by adding other flavors such as the basics and garlic.Tandoori Chicken: It's puck.Drinks: It feels like a milk shake.Very delicious.
원본: 직원분들이 굉장히 친절하고 우선 맛있음. 난 2000원-3000원대에 배부름. 커리 8000원-1만원대, 인별 세트 메뉴도 있음. 라씨까지 시키면 맛있고 엄청 배부르게 먹을수 있음. 강추., 번역: The staff are very kind and delicious first.I am full for 2000 won 3000 won.Curry 8,000 won 10,000 won, and a set menu for each person.If you do it, you can eat it and eat it very full.Recommended.

 96%|█████████▌| 21477/22421 [07:24<02:47,  5.62it/s]

원본: 평일 저녁에 갔는데도 사람들이 꽤 있었어요. 동대문에 있는 에베레스트에서 맛있게 먹은 기억이 있어서 롯데백화점에 차 세우고 찾아 갔는데, 갈릭난이 생각보다 그냥 그랬어요. 지점마다 맛 차이가 있나봐요.  그래도 이국적 분위기 추천합니다., 번역: Even though I went on a weekday evening, there were quite a few people.I remember eating deliciously at Everest in Dongdaemun, so I kicked up at Lotte Department Store and went to Garlican.There is a taste difference at each branch.Still, I recommend exotic atmosphere.
원본: 입구가 조금 허름해서 들어갈 때 거부감이 들 뻔했지만 들어가보니 나름 이국적인 분위기가 있었습니다. 커리 맛있었고 가성비도 좋은 편입니다. 영등포 말고도 다른 지점들도 많은 편이니 맛은 보장됐다고 생각하도 드셔도 좋습니다., 번역: The entrance was a bit shabby, but when I went in, I had a sense of rejection, but when I went in, there was an exotic atmosphere.Curry was delicious and price was good.There are many other points besides Yeongdeungpo, so you can think that the taste is guaranteed.

 96%|█████████▌| 21479/22421 [07:25<02:49,  5.57it/s]

원본: 가격대비 맛이  상당히 괜찮습니다2인세트에 음료 난 커리 치킨조금 수프 주는데배부르게 먹었네요, 번역: The taste is quite good for the price.
원본: 이색적인 느낌이 가득함2인세트는 밥과 탄두리치킨 반마리가에 음료,커리 및 난이 선택메뉴로 구성, 번역: The two -person set is full of unusual feelings.

 96%|█████████▌| 21480/22421 [07:25<02:50,  5.52it/s]

원본: 음식이 네팔가서 먹었던 느낌 그대로 정갈했어요. 난도 맛있고 서빙하시는 외국분도 친절했어요., 번역: The food was neatly eaten by Nepal.I was also delicious and the foreigner who served was kind.

 96%|█████████▌| 21484/22421 [07:26<03:27,  4.52it/s]

원본: 압구정 3번 출구에서 도산대로 쪽 방향에 위치한 국수집이다. 점심 때는 웨이팅이 워낙 길어서 11시 조금 넘어 도착하면 수월하게 식사를 할 수 있다. 직장인들 뿐만 아니라 예전에는 일본관광객들도 많이 찾곤 했다. 맛도 좋고 양도 많고 그리고 무엇보다 부담 없는 가격이 오랫동안 사랑 받는 이유이다. 비빔밥이 다 똑같은 비빔밥 아니냐는 분들도 계시겠지만 작은 차이가 큰 차이를 만든다는 말처럼 이 집 비빔밥에는 계란 후라이 2개가 들어간다. 이게 이 집의 후한 인심과 차별화를 반영한듯 하다. 국수 육수는 깔끔하고 면발도 쫄깃 해 맛있다. 저녁에는 곱창전골에 소주 한 잔까지 할 수 있는 압구정 직장인들에게 팔방미인이라고 본다., 번역: It is a noodle house located in the direction of Dosan -daero at exit 3 of Apgujeong.At lunch, the weight is so long that you can eat easily after arriving a little over 11 o'clock.In addition to office workers, Japanese tourists used to visit a lot.This is why it tastes good, has a lot of amount, and most of all, the price is loved for a long time.Some people may say that bibimbap is the same bibimbap, but the small difference makes a big difference in this house bibimbap.This seems to reflect the generousness and differentiation of this house.Noodles are clean and noodles are chewy.In the evening, I think it is an army beauty for Apgujeong office workers who can have a glass of shochu in the giblet hotpot.
원본: 곱창전골로 유명한 집인데 점심메뉴 중에 고기국수와 비빔면도 괜찮다고 해요. 고기국수는 쑥갓이 있어서 그런지 맑고 깔끔한 멸치국물베이스의 잔치국수 느낌이었어요. 점심시간에 약간의 웨이팅이 있지만 십분정도면 먹을 수 있더라구요., 번역: It is famous for giblet hotpot, but meat noodles and bibim noodles are good during the lunch menu.The meat noodles had a wormwood, so it was a feast of the clear and clean anchovy broth.There's a little weighting at lunch, but I can eat it for about 10 minutes.

 96%|█████████▌| 21485/22421 [07:26<03:24,  4.58it/s]

원본: 먹은 거: 두레국수(8,000원)맛 보통.가격 보통.친절함.매장 청결함.자극적이지 않은 맛이다. 김치와 잘 어울린다.밥도 1/3공기 정도 같이 나온다. 평소 국물을 다 먹는 편인 나도 국물을 남겼을 정도로 푸짐하다.1,2인 테이블은 거의 없어서 피크타임에 혼밥은 힘들 듯 싶다., 번역: I ate: Douré Noodles (8,000 won) Taste.Price normal.kindness.Store cleanliness.It is not irritating.It goes well with kimchi.The rice also comes with about 1/3 air.I usually eat all the soup, so I left the broth.There are few tables for 1 or 2 people, so it's hard to have a peak time.

 96%|█████████▌| 21486/22421 [07:26<03:23,  4.60it/s]

원본: 주말에 영업을 안하기 때문에 먹을수 있는 기회가 많지 않습니다. 점심시간에는 웨이팅도 꽤 있습니다. 곱창전골, 국수 모두 괜찮지만 명성에 비해 특별함은 없었습니다., 번역: There is not much opportunity to eat because it doesn't open on weekends.There are quite a few ways for lunch.Gopchang hotpot and noodles were all fine, but there was no specialty compared to reputation.

 96%|█████████▌| 21487/22421 [07:27<04:28,  3.48it/s]

원본: 두레국수주차 - 공간 확보가 여유 있지 않아 불편함가격 - 두레국수(7.0) 곱창전골(15.0)으로 평균적임맛 - 맛있는 편이지만 엄청나게 맛있어서 꼭 먹어야 해! 까지의 느낌은 아님. 두레국수는 양도 적지 않고 고기 육수에 호주산 육우와 쑥갓으로 담백하면서 깔끔함. 곱창전골은 매콤하면서 곱이 꽉 찬 편이라 든든히 먹을 수 있음. 2000원 추가 시 볶음밥도 먹을 수 있어요! 두레국수는 오후 4시까지만 주문 받으니 참고하세요., 번역: Durae Noodles is not enough to secure parking spaces.It's not a feeling.Duret Noodles are not transferred and meat broth is light and clean with Australian beef and wormwood.The giblet hotpot is spicy and full, so you can eat it.If you add 2000 won, you can also eat fried rice!Please note that Duret Noodles will only be ordered until 4 pm.

 96%|█████████▌| 21488/22421 [07:27<04:18,  3.61it/s]

원본: 워낙 유명한 곳이라 기대했는데 기대 만큼은 아니지만 술안주로짱이에영, 번역: I was looking forward to it because it was so famous, but it's not as expected.

 96%|█████████▌| 21489/22421 [07:27<04:12,  3.70it/s]

원본: 국수는 고기나 미나리 버섯 등 든게 많았는데 면에 맛이 베지는 않았던거 같아 아쉬웠습니다. 국물은 좋았는데 맛있기보다 건강한맛에 더 가까웠던거 같아요. 아주머니 소문보다는 친절하셨어요. 다음엔 비빔밥이나 전골 먹어봐야겠어요., 번역: The noodles were a lot of meat and buttercups, but it was a pity that the noodles didn't taste.The broth was good, but it was closer to healthy taste than it was delicious.You were kinder than the rumor.Next time, I need to try bibimbap or hotpot.

 96%|█████████▌| 21490/22421 [07:28<03:59,  3.89it/s]

원본: 맛있고 친절했습니다. 압구정에서 먹을 수 있는 가성비 맛집., 번역: It was delicious and friendly.A restaurant that can be eaten in Apgujeong.

 96%|█████████▌| 21491/22421 [07:28<03:52,  4.00it/s]

원본: 여기 연예인들 수시로 드나듬 ㅡ갈때마다 주조연 배우들 마니 봤음 ㅡ국수는 맛있는 맛이라기보단 깔끔한 맛인데 ㅡ압구정 골목지리를 잘 모르는 사람이면 ㅡ찾기 좀 힘듬 ㅎ, 번역: Here, celebrities often see the main actors every time you go ㅡ Noodle is a clean taste rather than a delicious taste ㅡ If you don't know the alley ㅡ to find it.

 96%|█████████▌| 21492/22421 [07:28<03:50,  4.03it/s]

원본: 두레국수 : 시원, 건강, 깔끔한맛. 얇게 썬 소고기, 쑥과 면을 집어 먹으면 충만해진다. *곱창전골이 겁나 맛있어보였다..., 번역: Noodles: Spring, Health, Neat taste.Thinly sliced beef, wormwood and noodles are filled.The giblet hotpot looked scary and delicious...

 96%|█████████▌| 21493/22421 [07:28<03:49,  4.04it/s]

원본: 서비스는 그저 그렇고, 맛은 너무 달다. 참고로 에어컨 안 틀어주니 여름엔 절대 가지 말 것. 이열치열 제대로 했다., 번역: The service is just so sweet.Note that you don't turn on the air conditioner.I did the fever.

 96%|█████████▌| 21494/22421 [07:29<03:46,  4.09it/s]

원본: 기다리다 추워서 죽는줄 ㅋ, 번역: I think I'm dying because it's cold

 96%|█████████▌| 21496/22421 [07:29<02:48,  5.48it/s]

원본: 혼자서 조용하게 가성비 좋은 커피 마시러 오기 좋은거같아요, 번역: I think it's good to come to drink quietly.

 96%|█████████▌| 21497/22421 [07:29<02:58,  5.18it/s]

원본: 바지락칼국수 주문했는데요. 국물은 담백하고 깔끔 했어요. 바지락은 해감이 잘되어 있고 신선했어요. 동네분들이 포장도 끊임없이 해갑니다. 주변에 오면 한번 들러보세요., 번역: I ordered the clam kalguksu.The broth was light and clean.The clam was well -made and fresh.The neighborhoods are constantly packing.If you come around, please stop by.

 96%|█████████▌| 21498/22421 [07:29<03:02,  5.06it/s]

원본: 비빔만두 팥칼국수 등등 메뉴 골고루 맛있어요 콩국수 쥬뮨했는데 서리태 콩국수 국물은 설탕 소금 간하지 않고 먹었는데 김치가 맛있어서 끝까지 맛있고 고소하게 먹었어요, 번역: Bibim dumplings, red beans, kalguksu, etc. are so delicious.

 96%|█████████▌| 21499/22421 [07:30<03:12,  4.80it/s]

원본: 건물 공사로 조금 더 깨끗한 곳으로 이전. 새알팥죽, 바지락칼국수, 칡냉면 어느 하나 부족함 없이 전부 맛있다. 특히 국산 팥을 직접 쑤어 만드는 진하고 걸쭉한 팥죽이 진짜배기.. 비빔만두에서 시판맛이 강하게 나는 것은 조금 아쉽다. 일요일은 운영 없습니다!, 번역: Relocated to a cleaner place to build a building.New altitude, clam kalguksu, cold noodles are all delicious without lack.In particular, the rich and thick red bean porridge that makes domestic red beans directly..It's a bit unfortunate to have a strong commercial taste in Bibim dumplings.There is no operation on Sunday!

 96%|█████████▌| 21500/22421 [07:30<03:19,  4.62it/s]

원본: ✔️모듬구이 (21,000원)✔️황소곱창 (23,000원)✔️대창구이 (23,000원)✔️김치말이국수 (5,000원)✔️볶음밥 은 플러스채널 친구 맺으면 공짜-오랜만에 먹은 곱창! 역시 너무 맛있었습니다. 이영자맛집 으로 유명한 [곱]! 저는 문래본점이 가장 맛있더라고요.웨이팅이 있었지만, 기다릴만해... 맛있으니까.곱창이랑 대파김치 같이 볶아서 먹으면 느끼함없이 아주 맛있어요..갈때마다 맛이 다른거같기도 한데, 맛있어요. 곱창맛집으로 추천드립니다. 시원매콤달달한 [김치말이국수]도 별미. 곱창의 느끼함따위 없다. 마무리 볶음밥은 [플친 맺으면 공짜] 공짜 볶음밥 꼭 드세요 먹느라 볶음밥 사진을 못찍었네요.가격이 쪼꼼 비싸지만 맛있으니 먹기.주차가능 입니다., 번역: ✔️ Assorted Grill (21,000 won) ✔️ Big Geam (23,000 won) ✔️ Daechang -ro (23,000 won) ✔️Kimchi horse is noodle (5,000 won)It was so delicious.Lee Young -ja is famous as a restaurant!I have the most delicious Munrae headquarters.There was a weight, but I can wait...It's delicious.If you fry it like giblets and leek kimchi, it is very delicious without feeling..Every time I go, it tastes different, but it's delicious.Recommended as a giblet restaurant.The cool [kimchi horse noodles] is also delicacies.There is no feeling of giblets.The finish fried rice is free to eat free fried rice.The price is expensive, but it's delicious.Parking is possible.

 96%|█████████▌| 21501/22421 [07:31<07:39,  2.00it/s]

원본: 요즘 영자언니 맛집으로 유명한 곱창집이라 그래서 방문햇어요!! 역시 영자언니 맛집이라 그런지 사람이 엄청 많아서 조금 대기햇구여 아마 주말이라서 사람들이 더 많앗던거 같아요! 들어가서 모듬주문하고 보니까 당일 도축된 고기만 사용한다고 엄청 큰 현수막이 잇더라구요ㅋㅋㅋ사장님이 고기부심잇으신 분 같아요 ㅋㅋ 곱창은 다 구워져서 나오느라 시간이 좀 걸리니 라면이나 국수 에피타이저로 먹는거 추천!! 저는 너무 배고파서 주문할때 라면 같이 주문햇엇는데 라면이 칼칼하니 곱창이랑 먹기도 좋겟더라구여! 그리고 꼭 곱창나오면 파김치 같이 올려놧다가 드세요 훨씬맛잇어요 ㅠㅠ말하면서 또 먹고 싶은 맛 ㅠㅠㅠ 당일도축된 아이들이라서 그런지 잡냄새가 안나서 더 맛잇게 먹은거 같아요ㅠㅠ 그리고 개인적으로 대창이 너무 기름져서 별로 안 좋아하는데 대존맛 너무 맛잇엇어요ㅠㅠ, 번역: It's a famous giblet restaurant these days, so I visited!!It's a young sister restaurant, so there are so many people, so it's a little waiting.When I went in and ordered the assorted meat, I used only the meat that was slaughtered on the day.!When I was so hungry, I ordered it together, but it would be nice to eat with the giblets.And when you come out of the giblet, it's a lot more delicious.It was so delicious

 96%|█████████▌| 21502/22421 [07:31<06:33,  2.34it/s]

원본: 서울온김에 이영자 맛집이라기에 한번 와봤어요소문나서 그런가 역시 사람이 바글바글ㅋㅋ웨이팅하는데 배고파죽는줄..그치만 맛있어서 기다린 보람이 있었어요ㅋㅋㅋ특히 저는 소곱창이 맛있더라구요곱도 가득하고 꼬소해서 아직두 기억나요다음에도 서울갈일 있으면 가려구요 ㅋㅋㅋㅋ, 번역: It's been a restaurant in Seoul, so I've come to the restaurant..But it was delicious, so I waited for it.

 96%|█████████▌| 21503/22421 [07:31<05:34,  2.75it/s]

원본: 이영자 맛집리스트에도 있던 곳이라고 검색하다 나와서 방문해봤어용 친구랑 곱창 되게 자주 먹으러 다니는데 평이 좋았습니당! 모듬이랑 제가 특히 좋아하는 염통구이 추가로 시켜서 배터지게 먹었어요. 여기는 부추를 많이줘서 느끼함을 싹 잡아줘서 좋아요. 충분히 넉넉하게 주는데 워낙 좋아해서 더 달라고 해서 깔끔히 먹었습니다 :) 추천추천, 번역: I searched for a place in Lee Young -ja's restaurant. I came out and visited.I ate assorted and my favorite salted tongs.It's good to give me a lot of leek.I gave it enough enough, but I liked it so much that I ate neatly because I asked for more :) Recommended

 96%|█████████▌| 21504/22421 [07:32<04:56,  3.09it/s]

원본: 매장은 깔끔했구요곱창 맛있었어요ㅎㅎ 비린맛 안나고제 입에 잘 맞아요대파김치 처음먹어봤는데  새콤한게 잘어울리네요~ 볶음밥이 정말 맛있어요!!!!직원분은 친절하셨어요, 번역: The store was clean. Gopchang was delicious.!!!The staff were kind

 96%|█████████▌| 21505/22421 [07:32<04:29,  3.40it/s]

원본: 여기 절대 안가요너무 화가 나네요본인들끼리 웃고 떠들면서 한눈팔다가곱창 타서 나오고양도 너무 작아요사진을 찍어왔어야 했는데 그게 너무 아쉽네요곱도 다빠지고 진짜 조각내 놓듯이 잘라서양도 진짜 2인분 시켰는데 완젼 1인분임 ㅡㅡ, 번역: Here, I'm never getting angry, and I have been smiling and talking with each other.ㅡ ㅡ

 96%|█████████▌| 21506/22421 [07:32<04:08,  3.68it/s]

원본: 맛있음. 다만 주문 후 인내의 시간이 긴 편. 가끔 주문을 패스하기도 함. 주의필요., 번역: Delicious.However, after ordering, it has a long time of patience.Sometimes I pass an order.Necessary.

 96%|█████████▌| 21508/22421 [07:32<03:30,  4.33it/s]

원본: 인생곱창(대창 곱창 카스 후레시), 번역: Life Gopchang (Daechang Gopchang Cass Fresh)
원본: 가격이 너무 비쌈, 번역: The price is too expensive

 96%|█████████▌| 21510/22421 [07:33<03:08,  4.84it/s]

원본: 식후 음료 하기좋은곳 가산동은 점심시간에 항상 북적거려요, 번역: Gasan -dong, a good place to drink after meals, is always crowded at lunchtime.
원본: 퇴근후에 간단하게 한잔 마시는게 좋은거 같네요 가격도 착한거 같고요, 번역: I think it's good to have a cup of drink after work after work.

 96%|█████████▌| 21511/22421 [07:33<03:02,  4.98it/s]

원본: 도봉산 근처에 있는 장어맛집이에요. 장어가 두툼하고 맛있어요. 매장도 넓고요. 주차 가능합니다., 번역: It is an eel restaurant near Dobongsan Mountain.The eel is thick and delicious.The store is also spacious.Parking is possible.

 96%|█████████▌| 21513/22421 [07:35<06:54,  2.19it/s]

원본: 장어가 진짜 두툼하고 살아있는 장어를 직접 잡아줘요. 주차장 매장 앞에 있어요., 번역: The eel is a real thick and living eel.It's in front of the parking store.
원본: 장어가 비리지도 않고 맛있어요 ~ 1kg에 3마리 나오는데 6.9만원이에요. 김치말이국수는 4.0천원!! 두명이서 먹기에 딱 좋은 양이었어요. 직원분들이 막 친절하시거나 하진 않은데 음식이 맛있어서 가는 집이에요. 월요일 저녁에 갔는데도 손님이 많았어요!, 번역: The eel is delicious and delicious.Kimchi horse Lee Kuk -su is 4.0,000 won!!It was just a good amount to eat.The staff are not kind or kind, but the food is delicious.Even though I went on Monday evening, I had a lot of customers!

 96%|█████████▌| 21515/22421 [07:35<05:45,  2.62it/s]

원본: 런치로만 먹다가 디너로 왔어요. 가격차이는 있긴하지만 여전히 맛있어요. 디너 메뉴 가격이 비싸서 2인세트로 시켰어요. 후식까지 쭉 나와서 오랜시간동안 맛있게 먹었습니다. 음식 전체적으로 맛있고, 이번에 못시켰지만 새우완탕인가... 그거 아이가 잘먹어요. 몽골리안비프는 제입맛에 너무 맛있었어요. 이거 먹으러 여기 옵니다!, 번역: I came to dinner only with lunch.There's a price difference, but it's still delicious.The dinner menu is expensive, so I made a two -person set.I came out to dessert and ate it for a long time.It's delicious throughout the food, and I couldn't do it this time, but is it a shrimp wan -tang?..That's what the child eats well.Mongolian Beef was so delicious.This is here to eat!
원본: 아시안 키친 캐주얼한 맛과 세트메뉴 가성비가 괜찮은편 입니다. 몽골리안 비비큐 젤 맛남, 번역: Asian kitchen casual flavors and set menus are good.Mongolian BBQ Gel Taste

 96%|█████████▌| 21517/22421 [07:36<04:07,  3.65it/s]

원본: 미국식 중국음식이라길래 궁금해서 가봤다. 인테리어가 고급지고 깔끔해서 데이트족이 꽤 많았다. 쌀국수는 베트남과는 또 다른 중국스러운 맛이었다. 양배추에 싸먹는 치킨 요리가 일품이었다. 몽골리안비프가 추천이던데  다음에 먹는 걸로 했다., 번역: I was curious because it was American food.The interior was luxurious and clean, so there were quite a lot of date.Rice noodles were different from Vietnam.Chicken dishes wrapped in cabbage were excellent.Mongolian beef was recommended, but I decided to eat it next time.
원본: 은평구 롯데몰 안에 위치해 있는데 메뉴가 꽤 많더라구요. 밥메뉴는 물론이고 디저트류도 생각보다 많아요. 래터스 랩 좊아해서 다시 간 건데 역시 맛있습니다. 메뉴가 많은데 음식 자체는 전체적으로 간이 좀 강한 것 같아요. 그래도 맛있습니다, 번역: It's located in Lotte Mall, Eunpyeong -gu, but there are quite a lot of menus.There are more desserts as well as the rice menu.I went back to the Leaders Lab, but it is also delicious.There are many menus, but the food itself is a bit strong.Still delicious

 96%|█████████▌| 21519/22421 [07:36<03:15,  4.63it/s]

원본: 음식은 전반적으로 맛있어요. 다만 카운터에서 테이블까지 안내하는데 직원들이 신경을 덜 쓰는 것 같아 밖에서 멀뚱멀뚱 기다리는 시간이 길었어요🍴, 번역: The food is generally delicious.However, it was a long time to wait outside because the staff seemed less attention to guide the table at the counter.
원본: 아 진짜 별로예요 좌석 완전 불편하고 좁고 시끄럽고 음식 나오는 속도 완전 느리고 음식도 너무 짜고 비쌈점수가 이렇게 높을 이유 없음다이닝코드 보고 갔는데 속은 느낌기념일 이럴 때 완전 비추예요공간 진짜 별로임 완전 별로재방문XXXXX, 번역: Oh, it's not really good. It's completely uncomfortable, narrow, noisy, and the food is completely slow, the food is too salty and the expensive score is so high. I went to the dining code.

 96%|█████████▌| 21521/22421 [07:36<02:47,  5.36it/s]

원본: 드디어 예약이 돼서 다녀온 쿠촐로맛있다 기본적으로 다만 가격 사악..저 시그니쳐인 카르파치오보단 파스타 종류가 훨씬 맛남 생면으로 만들어서!와인바틀하나랑 메뉴두개해서 먹었더니지갑털림,,ㅋㅎ 배는 좀 안불러,,,,,,분위기좋고 맛있으나 자리가 진짜 불편쓰한시간도 안돼 13만원쓰고 나오는 기적! 그래두 면은 넘 맛나서 또 가고픈, 번역: Finally, I have been reserving Kumulo..That signature Karpachi Ovosan Pasta is a much better man!I ate two menus and two menus.Yes, the noodles are so delicious that I want to go again
원본: 생면파스타로 만든 화이트라구와 비프 카르파쵸는 넘나 맛있었다. 식전빵(?)이라고 나온 치즈과자+트러플 꿀도 진심 레알 환상적!!!! 그러나 자리 선정 실패... ㅠㅠ 창가보고 앉는 좌석이었눈데 밑에가 구멍이 뽕뽕 뚫려있어서 다리 시려 죽을뻔.. 겨울에 가시려거든 자리는 무조건 안쪽으로!, 번역: White Ragu and Beef Carpacho made of raw noodles were delicious.Cheese sweets+truffle honey that says before meals (?) Is sincere fantastic!!!!But the seat failure failed...ㅠㅠ It was a seat to sit at the window, but the hole was pierced at the bottom, so I almost died..If you want to go in winter, the seat is inward!

 96%|█████████▌| 21523/22421 [07:37<02:41,  5.55it/s]

원본: 음식은 나쁘지 않지만 볼피노가 더 나아요. 파스타보다는 부라타치즈가 더 맛있었어요., 번역: The food is not bad, but Volino is better.Burata cheese was more delicious than pasta.
원본: 기대하고 방문했던 이탈리안 주점. 와인과 곁들일 수 있는 가벼운 메뉴들도 많아서 식사 후 와인마시러 가기도 좋을 닥. 개인적으로 소고기 카르파치오 좋아하는데 맛있게 먹었음.다만 이탈리안 주점을 표방한다고하나 자리가 너무 불편해서 오래 앉아 술마시긴 힘듬., 번역: Italian tavern I expected and visited.There are many light menus that can be served with wine, so you can go to drink after meals.Personally, I like beef carpache, but I ate it.However, it is said that it is an Italian pub, but the seat is so uncomfortable that it is hard to sit for a long time.

 96%|█████████▌| 21525/22421 [07:37<02:34,  5.80it/s]

원본: 계란 노른자로 만든 생 파스타면으로 만들어 트러플 향도 진하고 맛있었다.화이트라구 파스타도 토마토 소스가 아니지만 익숙한 맛이면서 트러플 파스타와 맛이 완전 달라서 나쁘지 않았다기본으로 주는 에피타이저에 트러플 오일 한방울 떨어져 있는것도 나쁘지않았음맥주 한잔과 잘 어울리는 파스타, 번역: It was made of raw pasta noodles made of egg yolk, the truffle flavor was rich and delicious.White Ra and Pasta is not a tomato sauce, but it's not bad because it's a familiar taste and a very different taste from the truffle pasta.
원본: 해방촌에 갈때 한번씩 들러보시면 좋아요. 파스타는 대체적으로 꾸덕하고 고소합니다, 번역: If you go to Liberation Village, you can stop by.Pasta is generally thorough and sued

 96%|█████████▌| 21527/22421 [07:39<07:06,  2.09it/s]

원본: 트러플파스타 강력 추천! 트러플 향이 과하지 않으면서도 풍부해서 한입 한입 먹을때마다 너무 만족스러웠습니다. 서비스도 친절하고, 꼭 다시 방문하고 싶은 곳., 번역: Truffle pasta is highly recommended!It was rich without the truffle fragrance, so I was so satisfied every time I had a bite.The service is kind and I want to visit again.
원본: 맛은있는데 비쌉니다. 비싼것에 비해 좌석이 불편해서 오래 있기에는 안좋습니다., 번역: It tastes expensive.Compared to expensive, the seats are uncomfortable, so it's not good to stay long.

 96%|█████████▌| 21531/22421 [07:39<02:57,  5.02it/s]

원본: 생각보다 가게가 아담해요.레시피가 약간 독특한데 맛있습니다~!, 번역: The shop is smaller than I thought.The recipe is a bit unique, but it's delicious ~!
원본: 갈만하다. 정말 맛있다., 번역: It's worth going.Really delicious.

 96%|█████████▌| 21533/22421 [07:40<04:05,  3.61it/s]

원본: 식사용 초밥을 많이 먹는 집입니다. 초밥이 15000원 중반으로 가격은 보통이지만 다른 반찬이나 서비스를 많이 주는 편이어서 가성비 맛집으로 알려져 있어요. 이번에 방문해서는 식사용 초밥이 아니라 술상으로 한번 시켜 봤어요. 로얄스시와 참돔광어회 두가지 7만원 근처로 주문. 서비스로 산낙지. 한우돌판구이. 메로구이 등 많이 나와서 다 먹지 못했어요. 술상으로 가성비 좋아요. 일반 횟집보다 푸짐합니다. 하지만 회가 숙성회 스타일로 쫀득하긴 하지만 최상은 아닙니다. 참치 뱃살도 비게가 많아서 잘라 먹었어요. 결론:  푸짐한 회에 한잔한다? 좋습니다. 회 품질에 민감하다? 좀 고민하셔야 합니다. 복잡함을 참을 수 있다면 식사가 아닌 술상도 가능한 호야초밥입니다., 번역: It is a house that eats a lot of meals.The sushi is in the middle of 15,000 won, but the price is normal, but it is known as a cost -effective restaurant because it offers a lot of other side dishes or services.This time, I visited it with a drink, not a meal.Ordered near 70,000 won, Royals City and Red Dome Flounder Society.Mountain octopus as a service.Grilled Korean beef.I couldn't eat it all because it came out a lot.It's good for alcohol.It is more than a regular sashimi restaurant.But the sashimi is chewy in the styles of aging, but not the best.The tuna belly was also high, so I cut it.Conclusion: Do you have a drink?great.Are you sensitive to the quality?You have to worry about it.If you can endure complexity, it is Hoya Sushi that can be alcohol, not meals.
원본: 다닌지 5녅닝도 되었내요...사장님이 바뀐건가? 아닌것같은데....초밥은 만드는 사람에따라 달라지니..직원이 바꼈나봅니다..원래 밥사이 간격이 좀있어서 잘 부서지는건 알고있는데이건 스시용밥이라고하기에 말라 비트러졌고..튀김은 냉동이었던건지 안에도 튀김파우더맛?기름맛이 나고...서비스로주는 한치 샐러드? 인가하는건 초장맛뿐..모밀은 미리 면을 그릇에 넣어서 쌓아둔듯 다 뭉쳐서 굳어 있었습니다.결국 연어초밥이랑 특호야시켜서전부 반 남기고 나왔내요..그냥 연어서시미랑 초밥용 연어가 다른건가요?소스로가린것같기도하고저녁늦은시간이라 그런지 냉동인지 말라비트러져있었어요...그래도 항상가던 호야인데 1년사이..ㅜㅜ, 번역: I have been there...Did you change the boss?I don't think....Sushi depends on the creator..The staff seems to have changed..Originally, there was a little gap between rice, so I knew it was a sushi rice..Tempura was frozen in frozen, even in fried powder...Hanchi salad given as a service?It's only a super taste..Mumil was hardened by putting it in a bowl in advance.In the end, it was special with salmon sushi, leaving everything left..Is it just a different salmon for sushi and sushi?..It's always Hoya, but it's a year..ㅜㅜ

 96%|█████████▌| 21535/22421 [07:40<03:23,  4.35it/s]

원본: 초밥 맛과 가격을 사로잡은 곳이죠 단점은 북쩍이고 사람많다는거 하지만 감수할만 합니다 두번갔어요 가까우면 자주갈만한 집이에요, 번역: It is a place that captures sushi taste and price. The disadvantage is that there are many people, but there are a lot of people, but it is worth it.
원본: 조금 정신없고 시끄럽지만 두툼한 회와 초밥의 회는 식감을 살려줍니다 건대주민으로써는 자주가게 되는 가성비 좋은 초밥집입니다, 번역: It's a bit crazy and noisy, but the thick sashimi and sushi sashimi are saved.

 96%|█████████▌| 21537/22421 [07:41<03:08,  4.69it/s]

원본: 초밥의 회가 큼직하니 맛있었습니다. 기대 이상위 맛과 가격이었습니다., 번역: It was delicious because the sushi sashimi was big.Expected taste and price.
원본: 이런게 초밥이구나를 느꼈던곳! 건대까지갔던 보람이 있을만큼 맛있었던곳! 월급털고 싶을만큼 맛있음, 번역: This is where I felt sushi!It was so delicious that I went to Konkuk University!It is delicious enough to want to pay salary

 96%|█████████▌| 21539/22421 [07:42<06:18,  2.33it/s]

원본: 한가할때 여자친구랑 들어가서 웨이팅은 없었구 신관에서 먹었습니당가격이 다이닝코드랑은 조금 다르네요둘이가서 호야세트 ,특호야세트 시켜서 먹었는데호야세트는 12500원이구 특호야는 16000원입니다음료는 2000원에 환타 콜라 사이다 있구요주문은 앉아서 (주문 받는 서비스가 별로였네요 홀에 아무도 없어서 셀프인줄..)둘이가서 호야세트 특호야세트로 둘다 배부르게 먹고 왔어요 가성비는 좋은데 서비스는 별로인 듯호야세트를 시키면 서비스로 메밀이랑 새우튀김이 나오는데 기대는 하지마시고 드세요 연두부?같은게 나오는데 치즈맛이(?) 나서 서로 놀랐어요초밥은 전체적으로 맛있구 이게 이가격이야? 싶을정도로 괜찮으니까 부담없이 드셔도 될거에요대망의 서비스..저희는 건대 호야를 처음가서 웨이팅이 길다길래 일부러 3시쯤 입장했는데 구관에는 사람이 너무 많아서 신관으로 갔습니당들어가서 맘에 드는 자리에 앉고 미리 메뉴를 알고와서 호야세트랑 특호야세트를 시키려는데 홀에 아무도 없더라구요? 왼쪽 벽에 계산기만 달랑있고.. 그래서 셀프 계산인줄 알았어요; 다른손님 주문하는거 보니 홀 말고 공간이 있는데 거기서 한분이 나와서 주문 받더라고요 그래서 불러서 호야세트랑 특호야세트 시키고 미리 검색해서 나온다던 서비스를 기다리는데 한참 기다려도 안나오더라고요 혹시 옛날꺼를 봐서 이제 서비스가 안나오나? 했는데 호야세트랑 같이 뒤늦게 주시더군여 그래서 호야세트랑 같이 먹었습니다;다 먹고나서 계산하려는데 네 역시나 홀에는 아무도 없었고 저희는 소화를 충분히 시키고 계산했습니다 ^^영화시간 늦어서 좋았네요 감사합니다, 번역: When I was leisurely, I went to my girlfriend and didn't have a weight. I ate it at the new building. The price is a little different from the dining code.There's a cider, and the order is sitting (I didn't have a good order. There's no one in the hall, so it's self.) Two people have eaten both Hoya sets.Don't expect shrimp fried, don't expect it.It's okay to have a long -awaited service because it's okay..We went to Konkuk Hoya for the first time, so we were deliberately entered around 3 o'clock, but we went to the new building because there were so many people in the old building.There was no?There is only a calculator on the left wall..So I thought it was a self -calculation;There is a space other than the hole, but one person came out there and received an order.I was late with Hoya Set, so I ate it with Hoya Set; I was going to calculate after eating, but there was no one in the hall, and we made enough digestion and calculated it.
원본: 가성비로 퀄리티 좋은 초밥먹을수 있어용 연어가 툭히 싱싱해서 생각나는 맛이에요 초밥도 맛있지만 사시미도 짱입니당, 번역: You can eat good sushi with price, so the salmon is fresh.

 96%|█████████▌| 21540/22421 [07:43<05:25,  2.71it/s]

원본: 맛있었어요!연어 초밥은 다른 곳 보다 연어가 두껍게 올라가서 좋았습니다. 계란 초밥은 어딜 가든 항상 먹는데 여기 계란초밥 정말 맛있었어요!!! 계란이 위에 올라간게 아니라 밑에 깔린게 특이했어요. 날치알이 들어가서 씹을 때 꼬도독 꼬도독 톡톡 터지는 식감도 좋았어요. 너무 달지 않으면서 폭신폭신 맛있었습니다!장어초밥도 맛있었어요! 달짝지근하고 너무 좋았습니다.간장을 찍어 먹는게 아니라 실리콘 브러쉬로 발라 먹는 방식입니다. 같이 나오는 마랑 새우튀김, 우동, 생선요리도 맛있었습니다. 오징어 샐러드?는 그냥그랬어요. 직원분들도 싹싹합니다. 공간이 다소 협소합니다. 한번 쯤 가볼만한 집이라고 생각합니다., 번역: It was delicious!Salmon sushi was good because the salmon rose thicker than anywhere else.Egg sushi is always eaten everywhere, but the egg sushi was really delicious!!!It was unusual that the eggs were not on the top, but the bottom.When the flying eggs went in and chewed, the texture of the twisted pores was also good.It wasn't too sweet and fluffy was delicious!The eel sushi was also delicious!It was sweet and so good.It is not to eat soy sauce, but to eat with a silicone brush.The marshes, fried shrimp, udon and fish dishes were also delicious.Squid salad?Employees are also sprouting.The space is somewhat narrow.I think it's a good house.

 96%|█████████▌| 21541/22421 [07:43<04:45,  3.08it/s]

원본: 초밥에 올라가는 회의 두께가 상당합니다.동 가격 대비 이 정도의 초밥을 즐길 수 있는 곳이 마땅히 떠오르지 않아요.또한 상차림 구성도 푸짐한게 적당히 와서 초밥에 술 한병 시키면 질껏 양껏 누릴 수 있는 것이 가장 큰 장점 같습니다.다만 매장이 협소하고, 그로 인해 타 고객과의 물리적인 거리가 가까워 식사 시 독립감을 느끼기 쉽지 않은 것은 분명 아쉬운 부분입니다., 번역: The thickness of the meeting to go up to sushi is significant.I don't have to come up with a place where I can enjoy this price for this price.In addition, the composition of the table is also appropriate, and if you drink a bottle of sushi, you can enjoy it as much as you can.However, it is a pity that the store is narrow and the physical distance from other customers is not easy to feel independence.

 96%|█████████▌| 21542/22421 [07:43<04:22,  3.35it/s]

원본: 초밥을 별로 안좋아하는데 맛있게 먹었다 초딩입맛이여서 생선보다는 참소라 장어 새우 문어가 더 맛있었다 밑반찬도 잘 나오는편! 여름에는 냉모밀 겨울에는 우동이 나오고 새우튀김 샐러드 모찌도후리 등이 나온다, 번역: I don't like sushi, but I ate it deliciously.In the summer, cold hair is a udon in the winter, and the shrimp tempura salad Mochidohuri comes out.

 96%|█████████▌| 21543/22421 [07:43<04:01,  3.64it/s]

원본: 항상 맛있어요 양도 많고 초밥의 질도 괜찮아용근데 서비스가 조금 줄었더라구요ㅠㅠ이전에는 연어구이랑 롤도 주시고 했는뎅 ㅠㅠ그래도 서비스 우동이 맛잇네요식사시간이 지나 웨이팅 오분 정도였습니당~, 번역: It is always delicious. The quality of sushi is fine, but the service was a little reduced.

 96%|█████████▌| 21544/22421 [07:43<03:53,  3.75it/s]

원본: 초밥 정말 신선하고 맛있는데 식사분위기는 반드시 개선해야 할 점. 또 가고싶은데 엄두가 안난다.ㅜㅜ, 번역: Sushi is really fresh and delicious, but the atmosphere of meals must be improved.I want to go again, but I can't.ㅜㅜ

 96%|█████████▌| 21545/22421 [07:44<03:49,  3.82it/s]

원본: 웨이팅 길엇지만 맛있었어요 ! 내부 협소하고 많이 시끄러워요 점심 저녁식사로 친구들끼리 가면 좋을것 같아요 ^^!, 번역: Waying was long but delicious!I'm narrow and noisy inside.

 96%|█████████▌| 21546/22421 [07:44<03:43,  3.92it/s]

원본: 하도 맛있다고 여기저기 난리길래 줄서서 먹었는데 진짜 실망했어요. 매장은 좁아서 직원분이 옷에 간장 쏟고 이건 뭐 실수니까 그렇다 쳐도.. 음식이 죄다 비리고 신선함1도 없고 뷔페초밥 보다 맛없어요. 두번 다시 안갈거예요., 번역: I was really disappointed because it was delicious.The store is narrow, so the staff pours soy sauce on the clothes..The food is all good and there is no freshness 1, and it is not as delicious as the buffet sushi.I won't go again.

 96%|█████████▌| 21547/22421 [07:44<03:36,  4.04it/s]

원본: 6명이서 저녁식사를 하러 갔습니다. 외부에서 번호표 받고 기다려야 하는 부분이 좀 귀찮았지만 음식은 정말 맛있었어요. 서비스로 탕이랑 샐러드, 새우머리튀김을 주셨습니다., 번역: 6 people went to have dinner.It was a little bothersome to wait for the number from the outside, but the food was really delicious.The service gave you the bath, salad, and shrimp head.

 96%|█████████▌| 21548/22421 [07:44<03:35,  4.05it/s]

원본: 테이블 몇 개 없는 아주 작은 일식당. 좁은 가게 안에 테이블 배치를 나름 잘해놔서 간격이 너무 좁거나 시끄럽지는 않아요. 혼밥하기에 괜찮은 자리도 잘 만들어놔서 혼밥하는 사람들도 꽤 많아요.로얄스시를 시켰는데 확실히 회가 두툼하고 큼직했습니다. 장어, 전복, 연어뱃살 등 좋은 부위가 포함되어 있어요. 가격대에 따라 서비스가 다르게 제공된다고 써있었는데 로얄스시를 시켜서 그런가 서비스가 어마어마했습니다. 샐러드, 우동, 새우튀김, 장어구이? 등등 테이블 진짜 꽉 차도록 계속 주셔서 배부르더라구요.. 서비스도 퀄리티 괜찮았습니다.직접 초밥 만들어주시는 분들 외에 서빙해주시는 아주머니가 한분 계시는데 말을 잘 못 알아 들으시더라고요. 나이드셔서 그런건지 다른 이유인지 모르겠지만 "이 부위 이름이 뭐예요?"하고 물어보면 뻥 진 표정으로 "생선" 이렇게만 대답하시고 휭 가시고(…) 조금 당황했습니다.따로 주차장 지원해주는 곳은 없고 신관 구관 나뉘어져 있다고 들었습니다. 화장실도 밖에 위치해 있다고 합니다., 번역: A very small one restaurant without a few tables.It's not too narrow or noisy because you have a good table in a narrow shop.There are quite a lot of people who are good at making a good place to eat.I had a Royals City, but it was definitely a thick and big sashimi.It contains good areas such as eel, abalone and salmon belly fat.It was written that the service was provided differently depending on the price range, but the service was huge because of the Royals City.Salad, udon, shrimp tempura, grilled eel?Etc. I was full of the table..The service was also fine.There is a woman who serves except for those who make sushi.I don't know if it's old or something else.What is the name of this area ?.If you ask, you look with your expression.fish.I only answered this and went to (…) I was a little embarrassed.I have heard that there is no place to support the parking lot, and it is divided into the new building.The bathroom is also outside.

 96%|█████████▌| 21549/22421 [07:45<03:36,  4.03it/s]

원본: 호야때문에 초밥입맛이 고급스러워짐...한 4년째 가고있는데 항상 맛있어요...ㅎ 서비스로 주시는것들도 다 맛있구! 특히 치즈같은 탱글탱글한...그건 따로 팔아주셔도 사먹을수있어요ㅠㅠㅠ 아 테이블말고 바쪽자리는 좀 불편하긴한데 감수하고 먹을수 있을 정도에요ㅎㅎㅎ, 번역: Hoya makes sushi taste luxurious...I've been going for 4 years and it's always delicious...ㅎ Everything you give as a service is delicious!Especially tangle like cheese...Even if you sell it separately, you can buy it.

 96%|█████████▌| 21550/22421 [07:45<03:29,  4.16it/s]

원본: 유명해서 가봤는데 생각보단 그저그래요자리도 너무 좁고 불편해요 요즘같은 외투 두꺼운거 입는 날씨에는 옷 둘데도없고 문이랑 테이블이 가까워서 추워서 옷 입고먹었어요특초밥 2인분 먹었는데 우동이랑 회샐러드 치즈맛나는 무언가 주더라구요. 우동은 정말 밍밍한 우동맛, 회샐러드는 초장에 양배추랑 회먹는맛이었습니다.남친이 그러던데 스시 만드시는 분이 만드는 손 그그대로 포스기 찍고 다시만든다더라구요위생에 신경써주세요왜 유명한지 모르겠어요 스시는 맛있긴 해요, 번역: I've been famous, but it's just too narrow and uncomfortable than I thought. In these days, there are no clothes in the thicker of the coat, and the door and table are close because of the cold.It's.The udon was really mingleed, and the salad was eaten with a chicky cheat.My boyfriend said, but the hand made by the sushi, I took a force and made it again. I don't know why it's famous.

 96%|█████████▌| 21551/22421 [07:45<03:24,  4.25it/s]

원본: 맛있고 가성비 좋아요~ 좋아했던 사람들과 먹었던 좋은기억~, 번역: Delicious and good value for money.

 96%|█████████▌| 21552/22421 [07:45<03:19,  4.36it/s]

원본: 가장 좋은것은 아무래도 대학가 주변이다 보니 가성비가 뛰어난것을 꼽을수가 있으며  초밥의 재료선택도 좋은편이며 여러가지 레벨로 시켜먹을수가 있습니다.초밥 말고도 일본식 회덮밥인 지라시덮밥(카이센동의 일종)도 아주 괜찮음.단점이라면 웨이팅 시간이 길고 비좁은 가게에서 먹는게 불편함, 번역: The best thing is that it is around the university, so you can say that the price is excellent.In addition to sushi, Jirashi rice bowl, a Japanese sashimi rice bowl, is also very good.The disadvantage is that it is inconvenient to eat in a long and cramped shop.

 96%|█████████▌| 21553/22421 [07:46<03:19,  4.36it/s]

원본: 여기는 교ㅓㅇ비 좋은 맛집 초밥!! 스끼다시로 생선조림 샐러드 등등 나오는데 사실 엄청 깨끗한 집이라고 볼순 없음!! 가성비좋으나 청결에서 별하나를 뺐다., 번역: Here is a good restaurant sushi!!Subsequently, the fish stewed salad comes out.!It is good for price, but I have a star from the cleanliness.

 96%|█████████▌| 21554/22421 [07:46<03:17,  4.40it/s]

원본: 웨이팅이 항상있지만 순환이 빠른편이고 맛있어서 추천하는 곳!, 번역: There is always a weight, but the circulation is fast and delicious!

 96%|█████████▌| 21555/22421 [07:47<05:45,  2.51it/s]

원본: 분위기 :  건대에서 가장 유명한 초밥집. 시끌벅적...가성비로 유명해졌다고 하는데ㅋㅋㅋ사실 잘 모르겠습니다. 맛 = 각종 서비스를 무장했는데. 사실 이 가격이면 다른 데서 얼마 추가하면 훨씬 괜찮은 음식이 나옵니다. 맛은 흠...신입생만 갈 듯합니다.  총평 = 왜 가는지 잘 모르겠습니다., 번역: Mood: The most famous sushi restaurant in Konkuk University.Noisy...It is said that it became famous for its cost -effectiveness.Taste = I armed various services.In fact, this price will be much better if you add some elsewhere.The taste is hmm...Only freshmen seem to go.I don't know why.

 96%|█████████▌| 21556/22421 [07:47<05:06,  2.82it/s]

원본: 매번 대기해서 방문하는 맛집이예요 공간이 너무 비좁은거 빼곤 좋아요, 번역: It's a restaurant where you can wait every time.

 96%|█████████▌| 21557/22421 [07:47<04:30,  3.19it/s]

원본: 초밥은 신선하고 두껍고 상큼하고 맛있어요.초밥 재료 넘 중요하게 생각해서 이 초밥집을 강추여!!!연어 샐러드맛있어요., 번역: Sushi is fresh, thick, fresh and delicious.I think this sushi restaurant is important!!!Salmon salad is delicious.

 96%|█████████▌| 21558/22421 [07:47<04:08,  3.47it/s]

원본: 왜 유명한지 모르겠음..너무 좁고 불친절하고 시끄럽고..무엇보다 불결함.. 그릇에 설거지가 덜되어있어 그릇을 계속 바꾸어도 더러움.스시가 맛있기는 하지만 이런 불결함을 감수하고 가고싶지 않음., 번역: I don't know why it is famous..Too narrow, unkind and noisy..Above all, unclean..The dishes are less, so it's dirty even if you keep changing the bowl.Sushi is delicious, but I don't want to take this unclean.

 96%|█████████▌| 21559/22421 [07:48<03:55,  3.66it/s]

원본: 초밥 가성비 짱이구 초밥 먹고간장새우 꼭 먹어줘야죵사진에 없지만 소고기초밥도 먹어줘야합니다호야 본관(?)신관(?) 이렇게 나눠져 있구요, 번역: Sushi is so good that you have to eat sushi and soy sauce shrimp.

 96%|█████████▌| 21560/22421 [07:48<03:50,  3.73it/s]

원본: 예전 좋은 기억을 갖고 방문했는데, 점원도 친절하지 않고, 서비스우동도 한참 후에 나오고, 초밥도 특출나게 맛있지는 않아서 실망했어요., 번역: I visited with a good memory, but the clerk was not kind, and the service udon came out for a while, and the sushi was not exceptionally delicious.

 96%|█████████▌| 21561/22421 [07:48<03:42,  3.87it/s]

원본: 호야네  회 두툼하고 맛있어서 간다 바쁜건 알지만 서비스 정신은 부족하다, 번역: Hoyane sashimi is thick and delicious.

 96%|█████████▌| 21562/22421 [07:48<03:36,  3.97it/s]

원본: 주말엔 줄이 길어요. 가성비 좋은 횟집입니다. 회가 너무 두꺼운게 흠., 번역: The line is long on the weekend.It is a good sushi restaurant.The sashimi is too thick.

 96%|█████████▌| 21563/22421 [07:48<03:27,  4.13it/s]

원본: 샤리라고 할 수 없는 끈덕진 무언가. 설익은 밥 엉성하게 잘린 평평한 네타. 정말 최악으로 변했습니다. 예전에는 퀄리티가 꽤 괜찮은 연어와 멋지게 숙성된 간장새우가 있었는데 무슨일이 있었던거죠? 와사비도 싸구려 중에 싸구려로 바꼈네요. 몇 년만에 가봤는데 예전 전성기 호야를 기억하신다면 절대 가지마세요., 번역: Something that can't be called Shari.A flat netta that is crumbly cut.It really changed to the worst.In the past, there was a pretty good salmon and a nicely aged soy shrimp. What happened?Wasabi also turned cheap in cheap.If you have been there in a few years and remember the old heyday Hoya, never go.

 96%|█████████▌| 21564/22421 [07:49<03:31,  4.05it/s]

원본: 특호야초밥이랑 회덮밥 시켰는데 중간쯤 먹어가는데 특호야의 사이드 메뉴들이 나와서 당황했고 중간에 맥주 시켰는데 주문 까먹으셔서 계속 기다리다가 결국 다시 시켰어요..맛있다고 유명하대서 갔는데 날도 덥기도 더웠고 힘들었네여 ㅠ, 번역: I had a special rice and sashimi rice bowl, but I ate it in the middle, and the side menu of the specialty came out and I was embarrassed and made it in the middle..It was delicious because it was delicious, but it was hot and hot and hard.

 96%|█████████▌| 21566/22421 [07:50<06:12,  2.29it/s]

원본: 빠른 테이블 회전 덕분에 재료는 신선하고 맛이 좋았다. 하지만 광어지느러미와 같은 빠른 회전이 안되는 식재료에 대한 관리는? 매우 질겼다. 식전에 나오는 튀김과 소바는 미리 대량으로 준비하는 듯 미지근하고 불은 맛이었으며 두 명이라는 적은 인원이었음에도 인원수 계산미스로 나의 소바는 식후에 나왔다., 번역: Thanks to the fast table rotation, the ingredients were fresh and delicious.But what is the management of ingredients that don't rotate quickly like flatfish fins?Very tough.The tempura and soba from the ceremony were as lukewarm and lukewarm as if they were prepared in large quantities.
원본: 2호점에 방문했었는데 체격좋으신분이라면 모르는사람 어깨가 닿을정도의 좁은 자리를 경험하실거에요붐비는 금요일 여섯시에 방문한터라 시끌벅적했었고 맛은 아슬아슬하게 가격값을 했다는 느낌을 받았습니다, 번역: I visited the second store, but if you are a good physique, you will experience a narrow place where you don't know the shoulders.

 96%|█████████▌| 21568/22421 [07:50<04:15,  3.34it/s]

원본: 음 일단 맛은 솔직히 초밥 매니아로써는 아쉬웠어요! 비린맛이 조금 강하다고해야하나...사람은 되게 많던데 테이블 안치우고 안쪽비좁은 벽보고앉는자리 주더라구여... 거기앉고나서야 테이블을 서서히치우더라는...ㅜ 덕분에 진짜 한뼘되는공간에 둘이서 힘들게먹었네여...초밥솔직히안남기는데 3피스정도남겼어요ㅜ 두툼한건 좋은데 신선도는 살짝 아쉽구요 우동이랑 치즈나오는데 그건 참 맛나더라구여..., 번역: Well, the taste was honest, and it was a pity as a sushi enthusiast!The fishy taste should be a bit strong...There were a lot of people, but I didn't have a table and sat down in the narrow wall...It wasn't until I sat there...Thanks to you, I ate hard in a real space...Sushi is not left, but I left 3 pieces...
원본: 초밥 회는 두툼하고 길어 맛있습니다.다만 장어 초밥은 좀 식어 있었고간장새우초밥도 만들어 둔지 시간이 지난 식감이더군요.저렴한 가격(?)에 적당히 배부르게 먹을때 좋아요.서빙은 불친절하게 느껴질 수 있고 좁아서 여유롭게 식사하긴 힘든게 단점이죠., 번역: Sushi sashimi is thick and long and delicious.However, the eel sushi was a little cool and it was a time after the time it was made.It's good to eat at a reasonable price (?).Serving can feel unkind and narrow, so it's hard to eat relaxedly.

 96%|█████████▌| 21570/22421 [07:51<03:23,  4.18it/s]

원본: 결론부터 말하자면 가본 음식점 중에서 가장 비위생적이고, 서비스질이 정말 낮은 집.뚝섬유원지에 있다가 여자친구가 초밥매니아라 호야초밥 예전부터 들어봤다고 가보자고 해서 왔는데 들어가서 수저 세팅하려고 보니 이물질 심하게 묻어있음. 이거 좀 닦아서 가져와달라고 말하니 알바생은 한국말을 잘 못하셔서 이해를 하시지 못함. 그리고 물을 마시려고 컵을 보니 컵에도 때가 끼어있음. 기분나쁜상태에서 간장소스 종지에 뿌리려고 하는데 간장소스통도 끈적끈적거림. 정작 시킨 초밥 나와서 간장 발라먹으라고 준 고무브러쉬도 세척이 안되어있던 상태.정말 이런 더러운 집은 살면서 본 적이 없음.더 가관인건 원래 여기는 쯔끼다시로 새우튀김 2개가 나옵니다. 물론 우리도 받았고요. 근데 우리 먹는 도중에 여자 두명이 들어와서 새우튀김2개 달라고 했다가 부족할거같다고 4개로 주문 바꿨는데, 원래 새우튀김 2개 나가는건 언급조차 안하고 POS기에 바로 4개 찍음. 나아가 주방장이 "아 그럼 기본2개에 4개 추가해서 나가면 되나요?"라고 주문받는 사람한테 물어봤는데, "아 그냥 4개만" 이라고 대답함. 이런 서비스가!그리고 이 모든것에 조미료를 더해주는 불친절함. 정말 정말 불친절함. 새로 손님 2명 왔는데 바(bar) 자리가 애매한거 같으니까 갑자기 사람들한테 무슨 군대 유격훈련 온것마냥 '저기 여기 앞에 계신 분 6명 옆으로 조금씩 옮겨주셔야되요!' 라고 명령하셔서 나도 같이 움직일뻔했네. 유격 조교인줄. 아무튼 여기 왜이렇게 사람들이 많이 몰리는지 모르겠지만, 다이닝코드를 보신다면 무조건 피하시길. 진짜 마지막으로 말하지만, 그래 불친절 뭐시기 다 견딜 수 있어, 근데 너무 더럽잖아 이건. 너무 더러워. 너무., 번역: In conclusion, the most unsanitary and low -service house among the restaurants I've been to.When I was at Ttukseom Amusement Park, my girlfriend was told that she had heard that she had heard of sushi enthusiasts, Hoya sushi.I told you to breathe and brought it.And when I saw the cup to drink water, the cup was also stuck.I try to sprinkle it on the end of the soy sauce in a bad state, but the soy sauce can also be sticky.The rubber brush, which was made to eat soy sauce, was not washed.I haven't seen such a dirty house in my life.More spectacular is the original Takki again, two shrimp tempura.Of course we received it too.But while we were eating, two women came in and asked for two fried shrimp fried shrimp, but I changed order to four, but I didn't even mention two fried shrimp fried shrimp.Furthermore, the chef.Oh, can I add four to two basics?I asked the person who ordered.Oh, only four.Reply.This service!And unkindness to add seasonings to all of this.It's really unkind.I have come two new guests, so I think the bar is ambiguous, so I suddenly have a military play training to people.'I almost moved together.A play assistant.Anyway, I don't know why there are so many people here, but if you see the dining code, avoid it.It's really the last time, so I can withstand all the time, but it's too dirty.Too dirty.too.
원본: 10000원에 다양한 초밥이 나오고 서비스로 우동도 나옵니다. 우동맛은 담백하고 좋습니다. 초밥이 12개 나오는데 비린맛이 전혀 안나고 맛있습니다. 만원에 배부르고 맛있게 먹고나올수있고 술먹기에도 딱 좋은 안주입니다. 하지만 좌석이 좁고 사람많은 저녁시간에는 웨이팅이 깁니다., 번역: Various sushi comes out at 10000 won and udon comes out as a service.The udon taste is light and good.There are 12 sushi, but the fishy taste is not good at all.It is a good snack to eat and eat and eat it for 10,000 won.But the seats are narrow and we have long weights in the evening.

 96%|█████████▌| 21571/22421 [07:51<03:11,  4.44it/s]

원본: 평이 좋아서 갔는데 전 완전 실망했어요1호점은 자리없어서 2호점으로 갔구요특호야랑 참돔연어회를 먹었는데 일단 생선들에게서는 특유의 맛이 전혀 없었구요, 가성비를 논할수가 없었습니다 무슨 맛이 나야 가성비를 따지죠..게다가 그게 왜 가격이 싼건지도 모르겠구요서비스로 매운탕이나 가리비에 치즈올린거? 등등 줬는데 동태매운탕 맛에다가 머리도 없구, 치즈는 다 녹지도 않고메뉴판도 물에 젖은 종이고 자리도 좁고 시끄럽고왜 사람들이 많이 가는지 전혀 이해할수 없던..., 번역: I went to the first place, but I was completely disappointed. I went to the second store because I had no seats.I'm looking for it..Besides, I don't know why it's cheap.I gave it to me, but I didn't have any hair and had no hair, but the cheese was not green and the menu was wet, the seats were narrow, noisy, and I couldn't understand why there were a lot of people...

 96%|█████████▌| 21573/22421 [07:53<06:06,  2.31it/s]

원본: 2호점 다녀옴.  가성비 라지만 동의 불가. 기다림 심하고, 자리는 비좁고, 연어는 무한리필 연어 수준이라 아무 맛도 안남.  . 게다가 실장이라고 있는 사람 포함 서비스 마인드 레벨이 딱 조선족 양꼬치 집 수준이거나 그 이하라 갔다오면 기분만 나빠짐. 오랜만에 돈주고 해본 최악의 경험이었음 밖에서 장시간 서서 기다리다 비좁은 자리에서 분식집만도 못한 서비스 받으며 맛을 알 수 없는 생선살 먹는 게 취미라면 말리지 않겠지만 그냥 돈좀 더 주고 쾌적하고 맛있는 거 드시길. 사실 이정도 돈이면 이 동네 먹을만한 거 널림., 번역: I went to the second store.It is a cost -effectiveness, but I can't agree.Waiting, the seat is cramped, and the salmon is unlimited, so it doesn't taste anything..In addition, the service mind level, including the manager, is just as good as the Korean -Chinese skewers or that he goes.It's been a long time since I have been paying for it for a long time. I wait for a long time outside.In fact, if it's this money, it's worth eating this neighborhood.
원본: 기다리지 않고 바로 착석 초밥말고 많이나와서 좋아영 연어랑 장어 맛나요, 번역: I don't wait and come out a lot without sitting sushi.

 96%|█████████▌| 21575/22421 [07:53<04:08,  3.40it/s]

원본: 가성비 좋은 초밥집이라 자주 가요 장소는 너무나 협소하고 짐 둘 데가 없어요 빨리 먹고 나가고 싶은 집이에요 건대 근처 살면 테이크아웃하고 싶은 집임, 번역: It's a good sushi restaurant, so it's too narrow and there's no luggage. It's a house I want to eat quickly.
원본: 초밥 크기가 제각각이며 어떤건 와사비가 너무 많이 들어있었음. 심지어 밥도 설익었고 가격도 더 비쌌고 플레이팅도 플라스틱 접시,, 거기다가 불친절한 직원 두명,, 다이닝코드의 신뢰성에 의문이갈 정도, 번역: The size of the sushi is different and some of the wasabi was too much.Even the rice was not absolutely, the price was more expensive, and the plasting was plastic dishes, and two unkind employees, and the dining cord's reliability.

 96%|█████████▌| 21577/22421 [07:53<03:19,  4.22it/s]

원본: 2016년 마지막날 오픈시간을 맞추어서가도 웨이팅이 걸림전채적으로 가격이 싸지않음 연어및 광어 참치는 맛이나나선어는 정말 별로 직원들이 정신이없고 표정에서 웃음을 찾을수없는그냥 초밥을 찍어내는 공장같음 서비스정신 이런거 필요없다 하는사람들만 가길, 번역: Even if we open the last day of 2016, we do not have to wait for the price. Salmon and flatfish tuna, but the tuna, but the fishing language is really insane and the factory that does not find a smile in the expression.Only those who do not need this mentality
원본: 방문객이 많다보니 네타의 신선함이 괜찮은 편 입니다. 하지만 광진구를 방문하는 타지인들에게 추천하진 않을 예정입니다., 번역: Since there are a lot of visitors, Netta's freshness is decent.However, it is not recommended for other people visiting Gwangjin -gu.

 96%|█████████▌| 21579/22421 [07:54<02:56,  4.76it/s]

원본: 초밥도 맛있지만 연어사사미, 참치회 등 회가 엄청 맛있고 가격대에 따라 나오는 스끼다시가 엄청 맛있어요~~, 번역: The sushi is also delicious, but the sashimi, such as salmon sasami and tuna sashimi, is so delicious and the sashimi that comes out according to the price is very delicious ~~
원본: 가격대비 맛도 좋고 양도 푸짐해요 대신 대기가 길어서 포장해서 먹었어요 맛은 언제나 일정하고 좋아요!!, 번역: It tastes good for the price and the amount is full.!

 96%|█████████▋| 21581/22421 [07:54<02:41,  5.20it/s]

원본: 진짜 살면서 먹은 초밥등에 제일맛있었습니다다음에 친구 부모님 데리고 가고싶네요, 번역: It was the best in sushi, etc. I really lived.
원본: 웨이팅 있고 자리가 좀 협소해서 별로였지만 연어 넘나 맛있는 것...❤️, 번역: There was a way and a little narrow seat, but it was delicious beyond salmon...❤️

 96%|█████████▋| 21583/22421 [07:54<02:39,  5.26it/s]

원본: 진짜 초밥 위에 생선 큼지막하고 엄청 맛있음... 리얼 맛있어요, 번역: The fish is big and very delicious on the real sushi...Real is delicious
원본: 좌석이 좁지만 양이 푸짐하고 초밥의 회도 싱싱하고 밥도 맛있었다, 번역: The seats are narrow, but the amount is rich, the sushi sashimi was fresh and the rice was delicious.

 96%|█████████▋| 21585/22421 [07:55<02:33,  5.44it/s]

원본: 호야..원래 되게 자주가던 초밥집이였어요. 가성비 최고봉이였는데며칠전에 갔는데 뭔가 비린맛이... 약간 달라진 거 같아서 좀 아쉬웠네요ㅠㅠ, 번역: Hoya..It was originally a sushi restaurant.It was the highest price of money, but I went to seven times...It was a little unfortunate that it seemed a little different.
원본: 회가 엄청 두툼해요!!테이블턴도 빨라서 좋았구요, 번역: The sashimi is very thick!!It was good because the tableton was also fast

 96%|█████████▋| 21588/22421 [07:55<01:53,  7.31it/s]

원본: 서비스가 너무 너무 너무 좋습니당, 번역: The service is so good
원본: 한입에 먹기 힘들만큼 생선도 큼직큼직하고 맛도 최강!!, 번역: The fish is big and the tastes are strong enough to be difficult to eat in a bite!!

 96%|█████████▋| 21589/22421 [07:55<02:04,  6.68it/s]

원본: 가격대비 성능인 듯, 번역: It seems to be the price for the price

 96%|█████████▋| 21591/22421 [07:57<04:57,  2.79it/s]

원본: 가성비최고에 맛까지상당한 초밥집!! 조금은 협소하지만 건대주민들에게 오래사랑 받는데에는 그만한 이유가있다, 번역: The best sushi restaurant to the best price!!It's a bit narrow, but there's a good reason to be loved by Konkuk residents for a long time.
원본: 불친절의 대표맛집 ~~~~~들어가면 기분 꽝입니다, 번역: The representative restaurant of unkindness ~~~~~

 96%|█████████▋| 21599/22421 [07:57<01:20, 10.15it/s]

원본: 싸고 맛있고, 메뉴도 다양해 좋긴 한데,학교앞이라 시끄럽고 분위기가 어수선하다.웨이팅도 많은 편., 번역: It's cheap and delicious, and the menu is so diverse, but it's noisy in front of the school and the atmosphere is cluttered.There are also a lot of weighting.
원본: 베리굳, 번역: Berry

 96%|█████████▋| 21609/22421 [07:57<00:40, 19.85it/s]

원본: 꽈배기가 쫀득하고 달달해서 간식으로 좋아요 팥도넛도 안에 팥이 많이 들어 있네요사장님도 친절하세요ㅎㅎ간식으로 먹기 좋습니다, 번역: The pretzel is chewy and sweet.
원본: 꽈배기, 팥도너츠 다 맛있음가격 싼편아는사람은 아는곳노원역 근처인데 다코에는 수락산점으로 나와있음. 주소는 같은 곳 맞아서 여기다 올림., 번역: Pretty and red bean donuts are delicious.The address is right here.

 96%|█████████▋| 21612/22421 [07:58<01:16, 10.54it/s]

원본: -사당역 돼지갈비 맛집---역에서 가까운곳에 있는 허름한 돼지갈비집. 겉에서 보기엔 뭐 별거있나싶었는데 안에 들어가니 평일 저녁인데도 사람이 바글바글하다. 돼지갈비가 300g에 14,000원인데 서울치곤 가격도 꽤 합리적인듯. 완전 갈비살은 아니고 목전지부위가 섞여서 나오는데 뭐 맛만 좋으면 괜찮지.-후식으로 나오는 무료 동치미냉면으로 깔끔하게 마무리~~!, 번역: A shabby pork rib house near Sadang Station Pork Ribs Restaurant Station.I wanted to see something on the outside, but I went inside, but even though it was a weekday evening.Pork ribs are 14,000 won for 300g, but the price of Seoul is quite reasonable.It's not completely ribs, but it's a mixture of wood.Free Dongchimi cold noodles from desserts neatly finish!
원본: 사당역 살짝 외곽에 위치해있는데 찾기쉽고 역에서 가깝습니다.고기 좋았고 너무달지않고 딱 맛있었습니다 정말! 열무냉면 서비스 주시는거에 돼지갈비 돌돌 말아 먹으니 정~~말 맛납니다!!, 번역: Located slightly outside Sadang Station, it is easy to find and close to the station.The meat was good and it wasn't too sweet and it was just delicious!It's a pork ribs to give you a ribs to give you a hot radish cold noodle service.!

 96%|█████████▋| 21615/22421 [07:58<01:29,  8.99it/s]

원본: 번화가랑 떨어져있고 조금은 허름해 보이지만 반찬이랑 된장국도 맛있고, 고기도 괜찮아요. 가격도 괜찮고...전체적으로 만족한 집입니다., 번역: It looks a bit shabby and it looks a bit shabby, but the side dishes and miso soup are delicious and the meat is fine.The price is fine...It is a satisfying house as a whole.
원본: 유명한 태극당 모나카 먹어보러 방문 저렴한 가격이라 한번쯤 먹어볼만 하다.(맛은 크게 인상깊지는 않음)부모님 향수를 자극하는 다양한 종류의 빵들이 많아 다음엔 부모님 모시고 오려고 한다!, 번역: It's a low price to visit Monaka, a famous Taegeukdang.(The taste is not very impressive) There are many different kinds of bread that stimulates their parents' nostalgia.

 96%|█████████▋| 21617/22421 [07:59<01:37,  8.29it/s]

원본: 이런 전통적인 카페가 아직 남아있다는 사실이 뿌듯하다! 다행히 맛도 좋다!!, 번역: I am proud that this traditional cafe still remains!Fortunately, it tastes good!!
원본: 동대입구 역에서 바로 나오면 보이는 서울에서 제일 오래 된 배이커리입니다.모나카는 계산대에서 따로 요청하면 바로바로 주고 그 외 다른 빵들은 전부 풀로 진열되서 너무 늦은 시간에 방문하는게 아니면 빵 못살 일은 없는 곳 입니다.커피류는 라떼류가 인기가 있고 조용한 자리를 찾는다면 일층보다는 이층이 좀 더 조용합니다., 번역: It is the oldest pear eunry in Seoul, which appears right from Dongdae Entrance Station.Monaka is given a separate request from the cashier, and all the other breads are displayed on the pool, so you can't live too late.Coffee is more popular with latte, and if you look for a quiet place, the second floor is more quiet than the first floor.

 96%|█████████▋| 21619/22421 [07:59<01:46,  7.55it/s]

원본: 동대입구 갈일있어 들렀는데 모나카 원래 좋아하는데 아이스크림이래서 더 맛나게 먹음. 찹쌀과 그냥 밀이 있는데 찹쌀은 덜 부서지는 느낌 약간 찹쌀모나카 그맛인데 아이스크림과는 덜 어우러짐 밀 모나카가 아주 바삭바삭하고 맛있는데 먹다보면 어디서 먹은 익숙한 그 맛은 아이스크림 콘이었음 ㅋㅋㅋㅋ 야채사라다 생각보다 비싸서 놀램 빠바는 3천원대에 작지만 요긴 5천원에 크기도 큰데 집에와서 냉장했다가 남날 먹었는데 담엔 안사먹을듯.. 내용물이 양배추....랑 머 들어있는데 내기준엔 이미 빠바에 익숙해져서 밍숭맹숭한 맛은 의미가 없음... 어르신들은 좋아할듯... 난 이미 할배입맛인데 모지..네이버 블로그 보지말고 다이닝코드볼껄 후회함.. 다른 유명한건 카스테라라는데 그 작은게 그 가격... 어디서 먹어본듯한 맛일거같아 안사먹음 아이스모나카는 개당 포장 안됨.. 20분내 녹는다고 10개 사가면 냉장포장가능 하다함, 번역: I stopped by the Dongdae entrance, but I like Monaka.There is a glutinous rice and a wheat, but the glutinous rice is a bit less broken, but the glutinous rice Monaka tastes less with the ice cream. It is very crispy and delicious.Pava is small for 3,000 won, but it is 5,000 won for 5,000 won..The contents are cabbage....It contains a little bit, but my standards are already used to Paba, so the ming sung taste is meaningless...The elderly will like it...I'm already a grandpa..Don't look at the Naver blog, but regret it..The other famous is Castella, but that small price...It will taste like where you have eaten..If you buy 10 in 20 minutes, it can be refrigerated.
원본: 유명한 빵집이라 찾아가봤습니다.사람도 엄청많았고 빵종류도 많았는데사진에서 보듯 단가가 넘 비싸네요~ 기능장들이하는 빵집 비교했을때 맛과 가격에 있어 어떤 메리트가있는진 모르겠어요~ 빵집 기본빵인 팥빵에 앙금 저만큼 들어가고2100원은 쫌 너무했다며~!, 번역: I visited it because it was a famous bakery.There were a lot of people and a lot of bread, but the unit price is so expensive as in the picture.I said it ~!
원본: 너무나 오래된 추억의 빵집. 이런 저런 빵들 참 많이도 먹어봤지만 개인적인 원픽은 사라다빵 입니다. 내용물이 실하기도 엄청 실하거니와 양배추가 많이 들어있어 식감이 좋아요. 게다가 빵도 부드럽고 한가운데 노란줄로 버터향이 진한부분이 있어 전체적인 풍미도 살려줍니다. 양이 많아 식사대용으로도 충분하고 배부릅니다. 만약 혼자 국물라면 한개가 모자르는 정도의 양인 분들은 부족할 수도 있습니다. 대복떡은 안에 팥소가 실하고 견과류가 중간중간 들어있어 씹는 맛이 좋습니다. 겉에 있는 찹쌀에도 통팥이 있어 좋았습니다. 이것도 양이 상당해서 먹고나면 배불러요., 번역: Too old bakery.I've eaten a lot of these breads, but my personal one is Sarah.The contents are very good, and the cabbage is so good that the texture is good.In addition, the bread is soft, and in the middle of the yellow line, there is a deep butter flavor, which also makes it an overall flavor.The amount is large and full of meals.If you are alone, you may not have enough people who are short.Daedaebok Tteok has red beans inside and nuts in the middle, so it tastes good.It was good to have whole beans on the outside glutinous rice.This is also a lot of amount, so it's full.

 96%|█████████▋| 21621/22421 [08:00<02:04,  6.44it/s]

원본: 전통의 제과점.. 요즘 빵과 달리 담백하다.. 다만 가격이 퀄리티에 비해서 비싼 듯, 번역: Traditional bakery..Unlike bread these days, it's light..However, the price seems to be more expensive than the quality

 96%|█████████▋| 21622/22421 [08:00<02:12,  6.02it/s]

원본: 사라다빵말고 계란샌드위치 사봤는데 생각보다 맛있었어요 흥국롤케익도 촉촉하고 맛있는데 크림이 적어서 좀 아쉬웠어요ㅎㅎ 어르신들이 늘 많아요ㅋㅋ, 번역: I bought an egg sandwich without Sarada bread, but it was more delicious than I thought.

 96%|█████████▋| 21623/22421 [08:00<02:21,  5.62it/s]

원본: 사라다빵은 퍽퍽하고 싱거웠으며 버터프레첼은 아무맛도 안나면서 느끼했다. 모나카 아이스크림은 그나마 먹을만 했지만 두번 다시 올 일은 없을것이다. 70년이나 유지됐다는 게 신기할 따름, 번역: Sarada bread was full and fresh, and Butter Prethel felt without any taste.Monaka ice cream was at least eat, but it wouldn't come again.It is amazing that it has been maintained for 70 years

 96%|█████████▋| 21624/22421 [08:01<03:16,  4.07it/s]

원본: 맛은 그냥 그랬어요..! 오래된 빵집에서 이거한번 먹어봤으니 됐다! 만족감으로 끝남또 빵을 먹겠다고 갈 것 같진않아요인테리어는 이뻐용 근처 갈 일 있으면 한번 들리세용, 번역: The taste was just like that..!I've eaten this in an old bakery!I don't think I'm going to eat bread with satisfaction.

 96%|█████████▋| 21625/22421 [08:01<03:30,  3.79it/s]

원본: 맛에서 특별함은 모르겠지만 오래된 곳이니 특별한 것 같네요., 번역: I don't know the taste in the taste, but it's an old place.

 96%|█████████▋| 21626/22421 [08:01<03:41,  3.58it/s]

원본: 빵집으로 유명한 집이지만, 판매중인 빙수도 굳굳단 주차가 안됨.. 알아서 길에 세우던지, 각자 알아서 찾아서 해야함.. 가게에서 책임지지 않음.., 번역: It is famous for its bakery, but the shaved ice that is being sold is also not parked..You have to find it on the road, or you have to find yourself..Not responsible in the store..

 96%|█████████▋| 21627/22421 [08:01<03:33,  3.72it/s]

원본: 한국의 빵집 전설을 방문하는 느낌으로 두어번 가봤음. 분위기는 중장년층이 많아서 그런지 종류도 그 취향에 맞춰진 느낌이었다., 번역: I went a couple of times with the feeling of visiting a Korean bakery legend.The atmosphere was a lot of middle -aged people, so the kind was likely to be suitable for its taste.

 96%|█████████▋| 21628/22421 [08:02<03:25,  3.86it/s]

원본: 부모님의 부탁으로 근처를 지나갈일이 있어서 잠시 들려서 빵들을 샀다 몇일의 아침은 걱정 없다, 번역: At the request of my parents, I had to pass by, so I stopped by and bought breads.

 96%|█████████▋| 21629/22421 [08:02<03:18,  4.00it/s]

원본: 옛날 빵집 느낌이라 이색적이고 좋았다.모나카빙수도 모니카 아이스크림의 다른버전같아 색달랐다., 번역: It was exotic and good because it felt like an old bakery.Monaka Bingsu was also different from other versions of Monica ice cream.

 96%|█████████▋| 21630/22421 [08:02<03:21,  3.92it/s]

원본: 모나카 아이스크림이랑 단팥빵이 맛있고요. 사라다빵이 유명하다는데 갈때마다 품절이라 못 먹어봤어요. 주차 안되니 대중교통을 추천합니다., 번역: Monaka ice cream and red bean bread are delicious.Sarada bread is famous, so I couldn't eat it every time I went.It is not parked, so public transportation is recommended.

 96%|█████████▋| 21631/22421 [08:02<03:27,  3.81it/s]

원본: 야채사라다빵은 사라다가 조금 짯음모나카 아이스크림은 옛날 와플아이스크림 딱 요거임진저자몽티는 진저향이 강하고 꿀 첨가하지 않는듯, 번역: Vegetable Sarada Bread is Sarada, but Monaka Ice Cream is a bit of an old waffle ice cream.

 96%|█████████▋| 21632/22421 [08:03<03:25,  3.83it/s]

원본: 빵에서 비닐 조각이 나왔습니다.가서 따졌고 구매한 내역 전부 취소 조치 해줬지만 이렇게 큰 브랜드 빵집 빵이 제대로 관리 안된다니 실망 엄청 했습니다.다시는 안 감, 번역: There is a piece of plastic from the bread.I went and made all the purchases of the purchases, but I was disappointed that such a big brand bakery bread was not properly managed.I will never go again

 96%|█████████▋| 21633/22421 [08:03<03:21,  3.92it/s]

원본: 역사적인 빵집에 점슈를 주고싶고 난 모나카가 빵보다 맛있더라 ㅎㅎ 시식빵 없는게 아쉽다 모나카는 본점만 판다, 번역: I want to give Jumsu to the historical bakery.

 96%|█████████▋| 21634/22421 [08:03<03:14,  4.05it/s]

원본: 오래된 빵집답게 다른곳에서 멸종?된 빵들을 찾아볼 수 있다맛은 대부분 보통인편, 다만 마늘빵 종류는 꼭 먹어보길 바람유명세를 타는 건 사라다빵, 카스테라, 아이스크림 정도인데 사라다빵은 개인적으로 무맛이었고 카스테라는 요즘 찾아보기 힘든 빵실한 별립법 카스테라로, 맛이 없진 않지만 옆에 있는 시본케익이 비슷한 계열로 더 맛있으니 웬만하면 그걸로 먹길 추천. 모나카아이스크림은 그냥과 찹쌀이 있는데 아이스크림 자체가 맛있진 않으므로 찹쌀을 추천한다(겉에 과자가 더 맛있음). 맛은 얇은 뻥튀기에 아이스크림 먹는 맛.쿠키 종류는 매우매우 비추한다. 차라리 건너편 신라호텔 아띠제 쿠키를 사가라.., 번역: As an old bakery, you can find extinct breads in other places. Most of the taste is normal, but the kind of garlic bread must be eaten.It is a non -finding narcissus that is hard to find these days.Monaka -ASS Cream has just and glutinous rice, but the ice cream itself is not delicious, so I recommend glutinous rice (the sweets are more delicious).The taste of ice cream is thin.Cookies are very visible.Rather, buy the Shilla Hotel Attige cookie across from..

 96%|█████████▋| 21635/22421 [08:03<03:11,  4.10it/s]

원본: 늦게 가서 그런지 남아있는 빵이 얼마 없어서 맛은 못봤는데  모나카는 맛있었어요, 번역: I didn't taste it because there was not much bread that left me late, but Monaka was delicious.

 96%|█████████▋| 21636/22421 [08:04<03:09,  4.14it/s]

원본: 아이스크림  맛특별하진 않음찾아갈만큼은 아님무난함, 번역: Ice cream flavor is not special.

 97%|█████████▋| 21637/22421 [08:04<03:18,  3.95it/s]

원본: 복고풍 컨셉과 맛의 베이커리추억을 되새기기에  좋고 이색적인 장소, 번역: Good and exotic places to reflect on the retro concept and the taste of bakery

 97%|█████████▋| 21638/22421 [08:04<03:15,  4.01it/s]

원본: 이미 많은 사람들이 아는 유명한 제과점. 다양한 메뉴가 있어 고르는 재미가 있고 평균 이상의 맛을 하지만 가성비가 좋지는 않은 것 같다., 번역: A famous bakery already knows.There are a variety of menus, so it's fun to choose and tastes more than average, but the price is not good.

 97%|█████████▋| 21643/22421 [08:06<03:03,  4.25it/s]

원본: 샐러드빵, 모나카 등이 유명한데 어떤 것이든 어른의 맛이 난다. 그 맛이 좋으면 굉장히 즐거운 곳이고 그 맛이 심심하면 뭘 먹어도 마음에 들지 않을 것이다., 번역: Salad bread and Monaka are famous, but anything tastes like adults.If it tastes good, it is a very pleasant place, and if it tastes boring, you won't like anything.
원본: 외진곳인데도 사람 많구요모임도 많이 하는것같아요주말 웨이팅 있습니다. 스테이크 불쇼도 해줍니다세트메뉴로 가성비 있게 먹을수 있습니다연말모임장소 추천입니다, 번역: Even though it's a remote place, there are a lot of people.Steak Fire Show will also be done with a set menu.

 97%|█████████▋| 21645/22421 [08:06<02:42,  4.79it/s]

원본: 갑작스럽게 급방문한곳! 기대를 일도 안하고 가서 그런가 넘 맛있게 잘 먹었다 ♥️♥️ 여긴 스텔라피자는 꼭 먹어야된다, 번역: Suddenly visited place!I didn't even expect it, so I ate it so much ♥ ️ ♥ ️ Stella pizza must be eaten.
원본: 강남역 데이트 맛집삼겹살스테이크 : ★ ★ ★ ★ ★(진짜 맛있음, 불쇼도 굳)매우치킨크림파스타: ★ ★ ★ ★ ★(매콤하고 맛있음, 여자친구는 맵다함), 번역: Gangnam Station Date Restaurant Restaurant: ★ ★ ★ ★ ★ (Really delicious, fire shows) Very chicken cream pasta: ★ ★ ★ ★ (spicy and delicious, girlfriend is spicy)

 97%|█████████▋| 21647/22421 [08:06<02:28,  5.22it/s]

원본: 주말에방문해서 대기가 길었지만 맛도괜찮고 양도괜찮네요~~, 번역: The atmosphere was long on the weekend, but the taste is good and the amount is good ~~
원본: 음식의 맛은 보통적인 맛이였습니다. 맛이없는건 아닙니다. 맛있습니다. 아래층은 가보지 않았지만 윗층의 창문으로 보이는 뷰가 참 좋습니다. 2층의 경우 벨이 없어서 직원분과 소통이 다소 조금어려운게 아쉽고전체적으로 좋은 식당입니다., 번역: The taste of food was usually tasted.It's not tasteless.Delicious.I haven't been to the lower floor, but the view that appears to be the window upstairs is great.In the case of the second floor, there is no bell, so it is a pity that it is a bit difficult to communicate with the staff.

 97%|█████████▋| 21649/22421 [08:07<02:18,  5.58it/s]

원본: 친절하고 맛도 좋고 음식 빨리나와요. 파스타 오일인데 허브향나고 특이했어요. 고기는 스테이크 삼겹살은 불쇼해줘요. 프렌치프라이 두툼하니 괜찮구요., 번역: It is kind, tastes good and food is fast.It's pasta oil, but it was unusual for herbs.Steak pork belly is a fire.It's okay because it's French frying.
원본: 피자와 스테이크가 맛있었던 기억이 있다 가게 내부가 넓어서 좋았다, 번역: I remember that the pizza and steak were delicious.

 97%|█████████▋| 21650/22421 [08:07<02:16,  5.64it/s]

원본: 주말이라 굉장히 대기했는데 서있을 자리도 없어서 사람들 계단까지 대기. 들어가서도 대기. 그런건 강남역이라 당연하고, 별로였던점은 음악도 시끄러운데 손님들 들어올때마다 엄청큰소리로 인사해서 진짜 조폭집에 온것같았음. 너무 시끄러워서 말소리도 안들리고 스트레스받음. 음식은 별 맛 없지만 못먹을정도는 아니고 그냥저냥. 분위기가 너무 시끄럽고 과한 게 별로임, 번역: It's a weekend, so I waited a lot, but there is no place to stand.Waiting even when you go in.It was natural because it was Gangnam Station, and the music was noisy.It's so noisy that I can't hear the words and get stressed.The food doesn't taste much, but it's not enough to eat.The atmosphere is so noisy and not too much

 97%|█████████▋| 21652/22421 [08:07<02:19,  5.51it/s]

원본: 마초삼겹스테이크 시키면 불쇼를 해주는데 사이드 감자튀김에 뿌려진 알콜이 제대로 안날라갔던지 감자 한입 먹는 순간 쓴맛+알콜맛 가득 남ㅠㅠㅠㅠㅠㅠㅠㅠ 흐 두번 다시 생각하고 싶지 않은 맛.. 그리고 물티슈 티슈 피클 핫소스 등등 다 셀프여서 불편, 번역: If you have a steak of macho pork belly, you can do a fire show..And wet tissue tissue pickle hot sauce, etc.
원본: 여기 맛있었어요 삼겹살피잔가 뭐 맛있었는데계산할때 알바생이 실수인지 기계잘못인지, 다른분 불렀는데  설명 제대로 듣지 못하고 화내고 엄청 뭐라하는게ㄹㅇ마초 스러워서 다시 가고 싶지는 않네요 , 번역: It was delicious here. The pork belly was delicious.

 97%|█████████▋| 21654/22421 [08:08<02:14,  5.70it/s]

원본: 부채살 스테이크 맛있게 잘 먹었어요. 매콤한 파스타 먹었는데 참 맛있었어요. 피자도 식으면서 맛이 덜해졌지만 뜨거울때는 참 맛있었어요! 분위기는 어느정도 시끌한 편이라서 편하게 일행과 이야기할 수 있어서 좋았어요. 다음에도 방문할 생각이에요., 번역: I ate a lot of debt steak.I ate spicy pasta and it was delicious.The pizza also tasted less, but it was very good when it was hot!The atmosphere was somewhat noisy, so it was good to be able to talk to the party comfortably.I'm going to visit next time.
원본: 맛과 서비스는 훌륭한편입니다. 가격이비싼편이라 데이트용, 번역: The taste and service are great.The price is expensive, so for date

 97%|█████████▋| 21657/22421 [08:08<01:46,  7.17it/s]

원본: 맛은 다 무난했고 가격은 맛에 비해 비싸요. 크게 별로인 건 아니지만 이보다 더 나은 곳이 많아서 다시 갈 생각은 없습니다., 번역: The taste was good and the price was expensive.It's not very much, but there are more places that are better than this, so I don't want to go back.
원본: 마초쉐프 삼겹살 스테이크는 진짜 너무너무 맛나여ㅠ!!음식 대체적으루 다 맛있구 음료도 리필되공ㅎ인테리어도 이쁘고 화장실두 사소한것까지 다 준비되어 있어 너무 조아영근데 2인이 가야 배불리 먹을수 있는것같아요2인끼리만 가다가 4인이 갔었을때 더 양을 넉넉히 시켰지만그리 양이 푸짐하다는 느낌이 아니여서 조금 아쉬웠어요ㅠ, 번역: Macho chef pork belly steak is so delicious ㅠ!!The food is all delicious, the drink is also refilled.It was a little unfortunate because it didn't feel like this.

 97%|█████████▋| 21663/22421 [08:08<00:59, 12.68it/s]

원본: 삼겹살스테이크 맛잇어요~~~, 번역: Pork belly steak tastes ~~~
원본: 여기 설렁탕 정말 맛있음맛있는 설렁탕에서 한번 더 업그레이드 된 맛이라고 해야할까담백하면서도 진하고 그러면서도 깔끔한, 내공이 느껴지는 그런 국물임당면도 듬뿍 들어있고 고기도 맛있고매일 먹어도 질리지 않을 것 같은 맛국물 남기면 후회할 것 같아서 배부른데도 끝까지 다 먹었음김치와 깍두기는 둘다 달달한 편꽤 구석에 숨어있는 가게인데도 노인 손님들이 많고내부는 넓은 편이며 테이블 간 거리는 그다지 넉넉하지 않음근처 유명 설렁탕집들이 줄서서 먹는데에 비해 인파가 붐비는 곳은 아니지만개인적으로는 먹어본 설렁탕 중에 최고였음, 번역: Here, Seolleongtang is really delicious in Seolleongtang.Eum Kimchi and Kakdugi are both hidden in the corner, but there are many older guests, the interior is wide, and the tables are not so large that famous Seolleongtang restaurant is not crowded compared to the famous Seolleongtang restaurant.It was the best of this Seolleongtang

 97%|█████████▋| 21665/22421 [08:09<01:23,  9.08it/s]

원본: 김치가 정말 끝내준다! 깍두기도 좋고 배추김치도 좋다! 그들과 함께라면 무슨 메뉴든 다 어울린다, 번역: Kimchi is really awesome!Kakdu is good and cabbage kimchi is good!If you are with them, everything suits you
원본: 설렁탕 집! 구석에 있어서 담배피는 사람 뚫고 들어가야해요! ㅋㅋ 할아버지들 되게 많으시고 소면도 있는 설렁탕이에요! 보통 고기양 좀 적어서 특 시키길 추천!, 번역: Seolleongtang House!In the corner, cigarettes have to go through people!ㅋㅋ It's a Seolleongtang with a lot of grandfathers and noodles!It is usually recommended to make a special meat!

 97%|█████████▋| 21667/22421 [08:09<01:37,  7.72it/s]

원본: 근처 위치 및 홍보로 과포장된 하동관에 비해 고기 및 가격 현실적이고 무난함., 번역: Compared to the Hadonggwan, which is wrapped in nearby location and promotion, it is realistic and price realistic.
원본: 필자는 술을 못하지만 자꾸 술이 당긴다...어르신들이 자주오셔서 그만큼 맛이 보장된 집, 번역: I can't drink, but I keep pulling...Seniors come often and the tastes are guaranteed

 97%|█████████▋| 21668/22421 [08:09<01:41,  7.40it/s]

원본: 기본적인 설렁탕입니다. 들어간 고기의 상태는 정말 좋아요. 밥과 함께 퍼서 한입에 넣고 씹을때 전혀 부담스럽지 않게 먹을 수 있어서 너무 좋았어요., 번역: It is a basic Seolleongtang.The state of the meat is really good.It was so nice to be able to eat it with rice and eat it in a bite.

 97%|█████████▋| 21673/22421 [08:09<01:03, 11.71it/s]

원본: 평일 점심시간에 만원으로 짬뽕에 탕수육이랑 샐러드까지 먹을 수 있는 건 좋은데 탕수육이 달랑 4개 나와서 좀 아쉽습니다간짜장은 밍밍한 맛이 나서 춘장을 더 넣고 싶은 맛이였습니다. 그래도 들어간 재료들이 싱싱해서 맛있게 먹었습니다., 번역: It is good to have 10,000 won for lunch on weekdays, but it is good to eat sweet and sour pork and salad.Still, the ingredients in Korea were fresh and ate deliciously.

 97%|█████████▋| 21675/22421 [08:10<01:10, 10.62it/s]

원본: 여타 중국음식점과는 다른 서래향만의 맛이 있음. 다 맛있음. 다시 생각나는 맛, 번역: It has a taste of Seorae scent that is different from other Chinese restaurants.It's all delicious.The taste that comes to mind again
원본: 떡볶이 떡은 쌀떡인데 굉장히 쫄깃쫄깃 하고 맛있습니다. 국물은 고춧가루 맛이 매콤하게 나고 걸레만두가 정말 맛있어요!, 번역: Tteokbokki rice cake is rice cake, very chewy and delicious.The broth is spicy in red pepper powder and the mop dumplings are really delicious!

 97%|█████████▋| 21678/22421 [08:10<01:30,  8.23it/s]

원본: 시흥동에서 유명한 분식점 이라 방문했는데 생각보다 별로였어요 ㅜㅜ 메인 음식인 걸레만두도 제입맛에 안맞고 솔직히 냉동식품 만두가 더 맛있어요.... 그냥 추억을 느끼고 싶으면 한번가볼만한 정도, 번역: I visited it because it was a famous snack shop in Siheung -dong....If you just want to feel memories,
원본: 시장속 떡볶이집이다신기한맛  유명한 맛에 한번먹을만함, 번역: It's a tteokbokki restaurant in the market.

 97%|█████████▋| 21681/22421 [08:10<01:11, 10.42it/s]

원본: 1층과 2층으로 나뉘어져있고 2층은 다다미 스타일의 좌식이 인상적입니다밥알이 즉석에서 비벼져서인지 따듯하고젓가락으로 먹기는 다소 불편하긴하지만,안내된내용을 참고하여 숟가락을 이용하니큰 불편함없이 맛있게 먹고갑니다겨울한정메뉴인 방어랑 고등어 초밥 강추!, 번역: It is divided into the first and second floors, and the second floor has a tatami -style seating.I eat it deliciously.
원본: 회덮밥이 없고.. 롤이없습니다...세트가 있으면 좋겠습니다 초밥은 맛있었으나 박용석스시가 더 생각났습니다, 번역: There is no sashimi rice bowl..There is no roll...I wish there was a set. Sushi was delicious, but I remembered Park Yong -seok

 97%|█████████▋| 21684/22421 [08:11<01:32,  7.96it/s]

원본: 웨이팅 없이 바로 입장, 젓가락으로 집어 먹기 조금 불편할정도로 밥이 잘풀린다. 생선 자체는 전체적으로 다 신선해서 특이하단 느낌으로 잘먹었던 집! 아 밥간이 쎔, 번역: The rice is solved so much that it is a little uncomfortable to eat with chopsticks without waiting.The fish itself is fresh and eaten well.Oh, rice is 쎔
원본: 서비스면에서 최악광어회는 가성비 너무 떨어짐 보고 실망알바생들 교육을 잘 시켜야 할듯대기하다가 우리 뒤에 여섯팀들어가느라우리차례 뒤에도 한시간정도 기다리다가알바한테 말해서 들어갔는데그전에 테이블이 안나서 뒷팀부터들어간다는 안내도 없고 죄송하단 말도 없고시간 남아 도시는 분들만 가야하는 곳인듯가게 블로그에는 최고의 맛과 서비스라는데최고의 서비스???? 잘모르겠음..차라리 돈 더 주고 다른곳 가겠음뭐 맛만있음 되는 분들은 좋아할듯최소한의 서비스를 원한다면차라리 다른곳 가시길..., 번역: In terms of service, the worst flatfish sashimi was so low that the price was too low and the disappointing Albanians were to be able to educate the students, but I waited for an hour after the six teams behind us, and then told Alba.It's the best taste and service in the blog.I'm not sure..I'd rather give me more money and go elsewhere...

 97%|█████████▋| 21686/22421 [08:11<01:44,  7.03it/s]

원본: 저렴하긴 한데..밥알이 흩어져서 젓가락으로 집어 먹기 힘들고 국물은 숙주 비린맛이 강력해요., 번역: It's cheap..The rice is scattered and it is difficult to eat with chopsticks, and the broth is powerful.
원본: 밥이풀어지고식초맛설탕맛이났던것을제외하고는 맛있게 먹었습니다., 번역: It was delicious except for the rice and the taste of vinegar.

 97%|█████████▋| 21688/22421 [08:11<01:53,  6.47it/s]

원본: 맛이있어요 초밥이 신선해요 사람이 많아요 줄이있어요 .., 번역: It tastes good. Sushi is fresh. There are a lot of people..
원본: 건대 호야를 평소에 가다가 천호가 더 맛나다는 평을 보고 갔다 왔어요 ~ 다행히 웨이팅은 없었고 모듬초밥 두개 시켰어요 . 밥알이 뭉쳐져 있지않고 젓가락으로 초밥 집으면 밥알이 떨어져요 ... 그리고 밥 맛이 설탕이 들어간 느낌?? 그리고 직원들 불친절합니다 ....웨이팅까지 하면서 먹을 맛집은 ......글쎄요, 번역: I usually went to Konkuk Hoya and saw the comment that Cheonho tastes better. Fortunately, there was no weight and two assorted sushi.The rice eggs are not clumped, and the rice eggs will fall when you pick it up with chopsticks...And the taste of rice is in sugar ??And employees are unkind....The restaurant to eat while weighing......well

 97%|█████████▋| 21690/22421 [08:12<02:00,  6.05it/s]

원본: 지금까지먹은 스시중에 최악입니다 맛집이라고해서 갔는데 밥알에 섞는 식초 설탕맛이 넘쎄서 회의 맛을 전혀느낄수없고 식초물이 넘 많이섞어서 밥알은 젓가락으로 집는순간 완전 풀어져서 수저로 퍼먹었네요 가게홍보물에는 갓지은 밥이라서 풀어질수있다고하는데 전 밥이 문제가 아니라 식초물의 문제라고 생각합니다 추천 절대할수없는곳이네요, 번역: It's the worst in the sushi that I've eaten so far. I went to the restaurant.It is said that it can be released because it is rice, but I think rice is not a problem, but a problem of vinegar.
원본: 천호에서 초밥집 찾다가 가보았는데 맛있었어요. 특히 회가 신선한거 같았어요, 번역: I went to Cheonho while looking for a sushi restaurant and it was delicious.Especially the sashimi seemed fresh

 97%|█████████▋| 21693/22421 [08:12<01:41,  7.14it/s]

원본: 맛은 초밥체인점 은행골과 매우유사하다은행골과 비교해봤을때 장어초밥은 다소 평범한반면우동의 맛은 더 낫다 추천추천, 번역: The taste is very similar to the sushi chain bank goal.
원본: 천호동 냉면거리 첫집이다 내가 좋아하는 메밀면은 아니지만 육수 얼큰하고 많이 달지않고 양푸짐 친절하고 가성비 좋은 음식점이다, 번역: Cheonho -dong Cold Noodle Street The first house is not my favorite buckwheat noodle, but it's a good place to be sweet and sweet.

 97%|█████████▋| 21695/22421 [08:13<01:57,  6.16it/s]

원본: 워낙 오랫동안 간곳이라 맛은 언제나 맛있구요 ㅎㅎ 가격이 좀 오르긴했으나 양이많아서 늘 만족합니다 최근 공영주차장이 없어졌네요 ㅜㅜ, 번역: It's been a long time, so it's always delicious.
원본: 식사시간만 피하면 빠르게 편하게 푸짐하게 먹을 수 있는 곳. 4년전 처음 갔던 때에 비해 가격은 조금 올랐고 사람은 많아졌으나 맛은...조금 옅어졌다. 가격인상이야 그간 워낙 저렴했으니까 뭐 적당하다고 보지만... 맛이 떨어진건...아쉽다과거라면 별 4.5개는 줬을 집., 번역: If you avoid meals, you can eat quickly and comfortably.Compared to the first time I first went four years ago, the price was a bit rising and the people were increasing, but it tastes...A little faded.It's a price increase, so it's so cheap...The taste has fallen...It's a pity.

 97%|█████████▋| 21697/22421 [08:13<02:03,  5.89it/s]

원본: 여기만 사람이 많아요 !! 다른 집은 파리 날림....맛있긴한데 ....양도 많고 ..근데 먹고 나면 속이 더부룩합니다 ... 저뿐만이 아니고 같이 먹은 사람들까지요 ..... 왜 그런지 ....ㅜㅜ, 번역: There are only a lot of people here!!The other house is flies....It's delicious....There is a lot..But after eating, the inside is bloated...Not only me, but also people who ate together.....Why is it?...ㅜㅜ
원본: 어제는 친구로부터 점심 경에 곱창 번개 제안을 받았다. 당산역에서 요즘 제법 유명한 곱창집이 있다면서, 같이 낮술을 한 잔 하자는 제안이었다. 귀가 솔깃해진 나는 약속 시간에 맞춰 친구가 오라고 한 '당산옛날곱창'으로 갔다.전체적인 가게 분위기는 제법 넓은 실내가 답답함이들게 하지 않았고, 창가 쪽에 앉았는데, 창문을 여니 시원한 봄바람이 제법 잘 들어왔다. 무엇보다 테이블의 청결 상태가 꽤 좋았다. 요즘 같이 코로나바이러스로 조심해야 할 때는 이렇게 위생상태가 좋은 식당이 뭔가 믿음직스럽다 할까, 그런 느낌이다. 주문한 모듬곱창의 맛은 특별히 좋다 나쁘다로 구분지울 필요 없이 딱 곱창 맛이구나 하는 정도였다. 특별히 대단한 맛은 아니었다. 양이 특별히 많아 보여서 처음에는 놀랐는데, 곱창을 굽는 팬이 위로 솟은 팬이라 시각적 착각을 들게 한 것이었다. 그리고, 생간을 좋아하는 친구는 세 번 리필을 해서 먹었는데, 재차 요청드릴 때마다 단 한 번도 불평하지 않으시고 채워 주신 일하시는 분의 친절함에 감사했다. 사실, 생간을 한 번만 주고 안 주는 곱창집도 꽤 많기 때문이다.무난하게 곱창을 즐길만 한 식당임에는 분명하니, 당산역 근처에서 곱창을 드시고 싶은 분은 들려 맛보시길..., 번역: Yesterday I received a giblet lightning proposal from my friend for lunch.There is a famous giblet house at Dangsan Station, and it was a proposal to have a drink.I went to Dangsan Old Gopchang, where my friend asked me to come to the appointment.The overall atmosphere of the shop did not make the large interior made it frustrating, and sat on the window.Above all, the cleanliness of the table was pretty good.When you need to be careful with the corona virus these days, it feels like a restaurant with a good hygiene.The taste of the assorted giblets ordered was especially good.It was not particularly great.I was surprised at first because it looked especially a lot, and a fan of grilling giblets rises up.And a friend who likes life was refilled three times, and I was grateful for the kindness of the worker who did not complain every time I asked again.In fact, there are quite a lot of giblets that do not give only once.It is clear that it is a restaurant where you can enjoy the giblets, so if you want to eat giblets near Dangsan Station...

 97%|█████████▋| 21698/22421 [08:13<02:04,  5.81it/s]

원본: 웨이팅있음. 넓어서 회전율 빠른편. 손님이 많아서 시끌시끌함, 번역: Waying.The turnover is fast because it is wide.Noisy because there are many customers

 97%|█████████▋| 21700/22421 [08:14<02:11,  5.48it/s]

원본: 모듬곱창 2인분 주문해서 먹었습니다..곱창과 부추가 잘 어울립니다..같이 내주는 배추국도 맛나요.저녁 6시30분부터 줄서네요.., 번역: I ordered two servings of assorted ghosts..Gopchang and leek go well together..The cabbage soup that gives you together is also delicious.I'm lining from 6:30 pm..
원본: 1회 방문. 곱창도 맛있고 볶음밥은 더 맛있고. 줄이 길다., 번역: One visit.The giblets are delicious and the fried rice is more delicious.The line is long.

 97%|█████████▋| 21702/22421 [08:14<02:09,  5.57it/s]

원본: ㅠㅠ곱창진짜 인생살이 먹어본 곱창중 제일 맛있어요! 신촌보다 낫네요 ㅎㅎ 간도 싱싱하고 이모님들도 다 친절하고 짱짱입니다, 번역: ㅠㅠ Gopchang is the most delicious giblet!It's better than Sinchon.
원본: 웨이팅이 엄청 긴만큼 기다려야하지만 맛은 정말 보장될만큼 맛있어요! 가격은 보통 소곱창가격정도? 돈은 부담되도 맛때문에 자꾸가게되요ㅜ 몇번이나 가도가도 질리지않아요 진짜진짜 맛있습니다 존맛탱 아 기다리는거 싫으시면 5시정도에 가면 바로 들어가거나 조금만 기다려도 들어가실수있어용 6시후에는 좀 기다리셔야합니당..ㅎㅎ, 번역: We have to wait as long as the weight is so long, but the taste is so delicious!The price is usually the price of a small giblet?I don't get tired even if I go to the money, but I don't get tired of it. I'm really delicious..lol

 97%|█████████▋| 21704/22421 [08:15<02:46,  4.30it/s]

원본: 원조랑 당산의 곱창집 쌍두마차격이라 방문해봤는데, 개인적으로는 조금..., 번역: I visited the original and Dangsan's giblet house...
원본: 웨이팅잇지만 맛잇어요 기다려서 먹어도 되요 맛잇오요 ~, 번역: There is a weight, but it's delicious. You can wait and eat it.

 97%|█████████▋| 21706/22421 [08:15<01:58,  6.03it/s]

원본: 이 동네 유명한 맛집 봉이돈까스!소스는 기본으로 선택하고 매운맛과 양념치킨맛도 조금 받아서 먹어보았어요매운맛은 좀 많이 매웠고 기본 보다는 양념치킨이 달짝지근 하고 맛있었어요! 다음에 먹는다면 양념치킨 맛을 먹으려구요!맛도 맛인데 무엇보다 사장님이 너~~~~~무 친절하셔서 위로 받고 가네요 ㅎㅎ 추천해요!, 번역: This is a famous restaurant in this neighborhood!I chose the sauce as a default, and I took a little spicy and seasoned chicken taste.If you eat it next time, I'll eat seasoned chicken!The taste is also tasted, but most of all, the boss is so friendly and I go to it.

 97%|█████████▋| 21708/22421 [08:15<02:35,  4.59it/s]

원본: 가격이 저렴하고 맛있는 돈가스집이에요! 모밀 세트가 8500원인데 양도 많고 맛있어요! 양념치킨 좋아하시는 분들은 양념돈가스 추천합니다 ㅎㅎ, 번역: It's cheap and delicious money cutlet!The set is 8,500 won, but it is a lot and delicious!If you like seasoning chicken, seasoned pork cutlet is recommended haha
원본: 디진다돈까스로 유명했던 곳입니다. 지금도 물론 판매하고 있습니다. 우리나라에서 가장 매운 음식을 파는 곳이라고 생각합니다ㅋㅋ, 번역: It was famous for its pork cutlet.Of course it is still sold.I think it's the place to sell the most spicy foods in our country.

 97%|█████████▋| 21709/22421 [08:16<04:37,  2.56it/s]

원본: 맛있고 양많고 싸고 만족스러운 돈까스집입니다.6500원 메뉴 하나 먹기만 해도 양은 충분합니다. 밥도 리필됩니다.매운맛은 저한텐 좀 맵군요 허헣, 번역: It is a delicious, cheap and satisfactory pork cutlet house.It is enough to eat a menu of 6500 won.The rice is also refilled.The spicy taste is a bit spicy for me

 97%|█████████▋| 21710/22421 [08:16<04:13,  2.81it/s]

원본: 돈까스만 시키면 남자기준 양이 모자랄거 같고1000원만 추가하면 모밀이나 우동 추가되는데이게 양이 어마무시합니다. 맛도 있어요., 번역: If you just cut the pork cutlet, the amount of male standards will be short, and if you add 1,000 won, the amount of day will be added.It tastes.

 97%|█████████▋| 21711/22421 [08:17<03:44,  3.16it/s]

원본: 오마카세지만 가족모임인 만큼 룸으로 잡았더니 오마카세의 재미는 좀 덜했네요ㅠ새로운 종류의 초밥들이 신기하고 맛있었고마지막 디저트가 상큼하게 입을 씻어줘서 좋았어요가성비 있는 오마카세로 즐길 수 있지만서비스는 좀 아쉬웠어요종업원 분이 좀 급해보이셔서…같이 마음이 급해졌네요, 번역: Omakase is a family gathering, so I took it as a room, but Omakase's fun was less fun ㅠ New kind of sushi was amazing and delicious, and the last dessert was good to wash my mouth freshly.After that, the employee seems to be a bit urgent…My heart is in a hurry together

 97%|█████████▋| 21712/22421 [08:17<03:33,  3.33it/s]

원본: 아주 만족스러웠습니다. 바에 앉아서 스시가 준비되는 과정을 보는 재미가 있으며, 맛도 아주 좋습니다. 셰프의 전문성은 말할 것도 없이 훌륭하며, 서빙을 하는 스태프들도 부족함이 없었습니다. 가성비도 아주 훌륭하며 언제든 재방문을 해도 좋은 곳입니다., 번역: I was very satisfied.It's fun to sit at the bar and see the sushi preparation, and the taste is very good.Not to mention the chef's expertise, there was no shortage of staff to serve.The price is also very good and it is a good place to return anytime.

 97%|█████████▋| 21713/22421 [08:17<03:15,  3.62it/s]

원본: 인생 초밥!, 번역: Life sushi!

 97%|█████████▋| 21714/22421 [08:17<03:03,  3.86it/s]

원본: 먹어본 초밥중 최고였다 인생초밥, 번역: It was the best sushi I had eaten life sushi

 97%|█████████▋| 21717/22421 [08:18<01:47,  6.52it/s]

원본: 진짜 찐맛집 베트남 현지맛이랑 비슷해요 사장님도 현지인이신것 같은데 너무 친절해요다른가게에서 없는 테파를 추가해서 먹을 수 있어서 좋아요 쌀국수도 맛있는데 면은 소면같아서 아쉬워요, 번역: It's similar to the local flavor of Vietnam. The boss is a local, but it's so kind that it's good to add a tefa in a different shop.

 97%|█████████▋| 21718/22421 [08:18<01:57,  5.96it/s]

원본: 상당히 좁은 가게입니다. 좌석도 상당히 좁고 음료 가격이 비쌉니다. 하지만 반미의 맛은 꽤 좋았습니다. 고수향을 싫어하는 분들은 고수를 뺄 수 있으니 빼서 드셔보세요., 번역: It is a very narrow shop.The seats are quite narrow and the price of drinks is expensive.But the taste of anti -American was pretty good.If you do not like the high scent, you can remove the coriander.

 97%|█████████▋| 21719/22421 [08:18<02:10,  5.38it/s]

원본: 어느 순간부터 가격이 오르긴 했지만, 진짜 너무 맛있다. 이대 갈때마다 꼭 집에 사들고 가는 반미., 번역: At some point, the price has risen, but it's really delicious.Banmi who buy home every time they go.

 97%|█████████▋| 21720/22421 [08:18<02:18,  5.07it/s]

원본: 아담한 분위기의.가게가 좋았구요, 직원분들도 상냥해서 좋았습니다. 돼지고기 반미를 시켰는데 생각보다 맛있어서 놀랐어요. 원래 빵을 싫어하는 편인데두 소스랑 빵, 고기랑 먹으니 최고더라구요. 근처에 살아서 일주일에 한두번은 저녁먹으러 가려구요, 번역: In small atmosphere.The store was good, and the staff were kind.I had half a pork, but I was surprised that it was better than I thought.I don't like bread, but it's best to eat with sauce, bread and meat.I live nearby and go to dinner once or twice a week

 97%|█████████▋| 21721/22421 [08:19<02:22,  4.90it/s]

원본: 중국이다 마라탕과 고기만두 간장에서 알수 없는 산미가 느껴진다. 한국음식에 길들여져서 먹는데 약간의 거부감이 있었다  고기만두는 간장을 안찍어먹으니 맛있었다. 마라탕은 고기완자와 소고기를 추가해서 먹는것을 추천한다. 맛도 선택할수있다. 보통맛으로 먹었더니 마라탕의 시원함은 느끼지못했다 매운맛으로 도전해보고 싶다 중국식-인지는 모르겠으나 이국적-향신료를 좋아하시는 분이라면 추천하는집 3.5 / 5.0, 번역: In China, Ida Maratang and Meat Dumplings are unknown.I was tamed by Korean food and had some rejection to eat it.Maratang is recommended to add meat and beef.You can also choose the taste.I didn't feel the coolness of Maratang.

 97%|█████████▋| 21722/22421 [08:19<02:24,  4.83it/s]

원본: 자리는 좁고 불편하지만 사람은 많다. 꿔바로우는 조금 신맛이 많이 났다. 그외 마라탕은 조금 얼얼한 맛이 많이 나서 싫어하는 사람은 빼달라고 할 수 있다, 번역: The seats are narrow and uncomfortable, but there are many people.Barou was a bit sour.In addition, Maratang tastes a lot of taste, so you can ask you to remove people who don't like it.

 97%|█████████▋| 21723/22421 [08:20<05:51,  1.99it/s]

원본: <마라탕>매운 맛을 좋아해서 마라 종류는 부담없이 먹는 편이에요. 이 날은 초심자 일행이 있어서 덜 매운 맛으로 주문했는데도 얼얼함이 살아있어서 만족스러웠습니다. (다만 마라를 못 드시는 분은 마라 정도를 참고하셔야 할듯 합니다. ) 개인적으로 국내에서 먹어본 마라탕 중에 가장 현지의 맛에 가까운 편인 것 같아요.<셩젠바오>셩젠바오도 육즙이 조금 아쉽지만..! 반은 굽고 반은 찐 듯한 모양이 제대로에요. 고기 향이나 식감이 현지의 느낌과 비슷해요!, 번역: <Maratang> I like the spicy taste, so I feel free to eat.On this day, I had a novice group, so I ordered it with a less spicy taste, but I was satisfied with the alive.(But if you can't eat Mara, you should refer to Mara.) I personally think it's the closest to the local taste.<Shengzen Bao> Schengzenbao is also a little juicy..!Half is baked and half steamed.The flavor or texture is similar to the local feeling!

 97%|█████████▋| 21724/22421 [08:20<04:56,  2.35it/s]

원본: 마라탕의 얼얼한 맛이 강한게 특징입니다. 근처 마라탕집 중에서는 국물이 제일 진한 편이라 선호합니다. 셩젠바오는 육즙이 가득해서 만족스러웠습니다., 번역: It is characterized by a strong taste of Maratang.Among the nearby Maratang houses, the broth is the strongest.Schengzenbao was satisfied with the juicy juice.

 97%|█████████▋| 21725/22421 [08:20<04:22,  2.65it/s]

원본: 맛은 정말 좋아요. 깔끔한 마라탕 찾으시면 괜찮은데 바쁠 때 가서 그런지 음식이 전체적으로 다 식어서 나와서 너무 아쉬웠어요. 그치만 마라탕은 텁텁함 없이 깔끔해서 아주 만족했습니다., 번역: The taste is really good.It's okay to find a neat Maratang.But Maratang was very satisfied because it was neat.

 97%|█████████▋| 21726/22421 [08:21<03:53,  2.98it/s]

원본: 호탕마라탕은 맵기 조절 가능해서 약간매움으로 하고 야채 다양하게 듬뿍, 두꺼운 면인 콴펀이랑 푸주랑 포두부 듬뿍 담아 소고기와 양고기 완자 추가하고 고수 추가해서 먹으니 짱맛 ㅠㅠ!!! 소스바도 있어서 원하는 소스 만들어서 먹을 수 있는데 깨소스 즈마장에 파 넣어서 먹으니 굿이었당. 성젠바오(만두)도 유명하던데 다음번엔 마라샹궈랑 만두 먹어봐야지*_*, 번역: Hotangmaratang can be controlled, so it's a bit spicy, and a lot of vegetables, and a lot of thick noodles, Kwanfun, Puju, and Pogu tofu, add beef and lamb fabrication and eat it.!!There is also a sauce bar, so you can make the source you want.Seongjil Bao (dumpling) is also famous, but next time I have to eat Mara Shanggoo and Dumplings _

 97%|█████████▋| 21727/22421 [08:21<03:30,  3.29it/s]

원본: 샤브샤브랑 비슷한데 샤브샤브보다 훨씬 진한 맛좋아하는 사람들은 엄청 좋아하는 것 같음가성비 좋은 편같이 시킨 만두는 평범했고, 번역: It's similar to shabu -shabu, but people who like much darker than shabu -shabu seem to like it.

 97%|█████████▋| 21728/22421 [08:21<03:23,  3.41it/s]

원본: 위생상태가 안 좋아보이기는 한데 맛은 있습니다. 근데 마라샹궈가 약간 축축하고 마라탕은 좀 시큼해요, 번역: The hygiene is not good, but it tastes good.But Marashang Guo is a bit wet and Maratang is a bit sour.

 97%|█████████▋| 21730/22421 [08:22<02:45,  4.19it/s]

원본: 연세로 부근의 마라탕 식당 중에서 제일 추천하는 곳. 성젠바오 또한 추천., 번역: The most recommended place among the Maratang restaurants near Yonsei.Seongjil Bao is also recommended.
원본: 사골 국물이 베이스고 땅콩 맛이 거의 나지 않는 국물입니다 감칠맛은 없고 마라 맛이 강하게 나서 맛있다는 느낌은 못 받았습니다 제 취향이 아니어서요 신촌 구석진 곳의 2층에 위치했는데도 사람도 많고 웨이팅도 길었습니다 가게 내부가 어두워서 깔끔하다는 인상은 못 받았네요, 번역: It is a soup that is bass and rarely tastes peanuts. It has no rich taste, and it tastes so good that it is not delicious. It is not my taste.I couldn't get the impression that it was dark because it was dark

 97%|█████████▋| 21732/22421 [08:22<02:24,  4.76it/s]

원본: 한번 먹어보라고 추천해주신 고기만두는 한참 뒤에야 나와서 마라샹궈를 다 먹고 나서야 먹음. 중국에서 먹던 맛과 비교하면 안되지만 구운 부분이 너무나 딱딱했음마라샹궈는 먹을만 했는데 기억에 남지는 않음, 번역: The meat dumplings, which I recommended to eat once, came out after a while and eaten Marashang Guo.You shouldn't compare it with the taste you ate in China, but the baked part was too hard.
원본: 이시국에 텐동이라니! 하는 불편러들이 있을지도 모르지만 한국분이 만드고 정말 맛있고 서비스가 친절하고 좋습니다. 분위기가 은은하고 깔끔하며음식 자체가 방금 만든게 딱 보일정도로 튀김 색이 노랗고 바삭한 식감이 일품입니다. 또 한 샐러드로 나오는 양상추가 전이 된게 전혀 없이 굉장히 신선함이 그대로 그릇에 담겨 있습니다.제가 짠걸 못 먹어서 소스를 따로 담아달라 요청을 드리자 종기에 담아 따로 주셨구요. 덮밥에 1500원을 추가 하면 달걀 밥으로 해주시는데요. 아 돈이 안 아까울 정도입니다. 꼭 오시면 계란 밥으로 해 드세요. 후회 안하실정도로 부드럽고 촉촉합니다. 하이볼도 레몬이 냉동이 아닌 생과일로 상큼함과 시원함이 입가심에 최고 입니다.홍대에 텐동이나 튀김 바삭한 음식을 드시고 싶을때 강추 입니다.인생 텐동 Top 2, 번역: Ten -dong in Lee Si -guk!There may be some inconvenience, but Korean is made and really delicious and good.The atmosphere is soft and tidy, and the food itself has just been made, so the color is yellow and crispy.In addition, the letters of the letters in the salad are so freshly contained in the bowl.I couldn't eat salty, so I asked for a separate sauce.If you add 1,500 won to the rice bowl, it will be egg rice.Oh, the money is not a waste.Please come with egg rice.It is soft and moist enough to regret.Highball is also the best for the mouth of freshness and coolness, not frozen.It is recommended when you want to eat Ten -dong or crispy food in Hongdae.Life Ten -dong TOP 2

 97%|█████████▋| 21733/22421 [08:22<02:18,  4.96it/s]

원본: 합정에 있는 텐동집내부가 넓지는 않아서 웨이팅이 있을수도 있습니다우선 기본텐동과 오야꼬텐동을 주문해봤는데 개인적으로는 기본텐동이 나았고전체적으로 아주맛있는정도는 아니지만 나쁘지않은 맛이었어요근처라면 또 갈수도 있을것같네요, 번역: The interior of the Ten -dong house in Hapjeong is not wide, so there may be a waiting.

 97%|█████████▋| 21735/22421 [08:23<02:49,  4.05it/s]

원본: 일식당답게 일본의 작은 가게에 온 것 같은 분위기의 식당. 작고 아담한 규모에 테이블은 제법 있어서 테이블간 간격은 조금 좁은 편이에요. 의자가 원목으로 되어 있어 오래 앉아있기에 편한 편은 아닙니다.야사이텐동, 카레 텐동을 먹어봤고 처음 딱 먹자마자 튀김이 바삭하면서 튀김옷이 두껍지 않아서 좋았어요. 텐동 먹을 때는 항상 밥을 다 먹을 때까지 튀김이 눅눅하지 않거나 튀김에 질리지 않는게 중요한데, 그 부분을 만족시켜 주지는 못 했습니다.2층에 위치해 있는데 2층 베란다에 테이블을 올려놓아서 야외에서 식사하는 기분을 내실 수 있어요. (근처 전망이 좋은 편은 아닙니다.) 화장실은 식당 바로 문앞으로 나오면 건물 안에 위치해 있어요.식당 내부가 좁은 만큼 가방 등의 물건을 둘 곳이 없어 보이는데 자리마자 작은 바스켓이 올려져 있어 물건을 내려놓을 수 있도록 배려한 부분은 좋았습니다., 번역: A restaurant that looks like a Japanese restaurant.The table is quite small and the table is quite narrow.The chair is made of solid wood, so it's not comfortable to sit for a long time.I ate Yasai Tendon and Curry Ten -dong, and as soon as I ate it, it was nice to be crispy and the tempura was not thick.When you eat Tendon, it's important not to be fried until you eat all the rice, but it is important not to be tired of fried.Located on the second floor, you can put a table on the veranda on the second floor to make you feel like eating outdoors.(The nearby outlook is not good.) The bathroom is located in the building right in front of the restaurant.As the inside of the restaurant is narrow, there is no place to place things such as bags, but as soon as the seat is raised, the small basket is uploaded, so it was good to be considerate to let go of the goods.
원본: 맛있습니다.텐동의 튀김을 잘튀기셨습니다.나중에 재방문의사 있습니다., 번역: Delicious.You've fried Tendon's tempura.I have a re -examination later.

 97%|█████████▋| 21737/22421 [08:23<02:21,  4.84it/s]

원본: 합정에 위치한 튀김덮밥 맛집.가게 안에 들어와서 보니 생활의 달인이라는 tv에도 나왔던 곳이었습니다. 메뉴는 다양한 종류의 튀김덮밥류가 있고, 위에 올라가는 토핑 종류는 각자의 입맛에 맞게 추가도 할 수 있습니다. (추가비용 발생) 제가 주문해서 먹었던 텐동은 새우2+야채 조합으로, 바삭바삭한 왕큰새우 2마리가 우뚝 솟아서 플레이팅된게 인상깊었고, 사이드로 나온 샐러드도 유자소스가 상큼하니 맛있었습니다. 튀김덮밥의 특성상 느끼한 부분을 샐러드가 살짝 잡아준다는 느낌을 받았습니다. 퇴근 뒤에 맥주와 함께 바삭한 튀김이 먹고싶다면 다시 방문하고 싶은 곳입니다., 번역: Tempura rice bowl located in Hapjeong.When I entered the store, it was a place that appeared on TV as a master of life.The menu has a variety of tempura rice bowls, and the toppings on top can be added to your taste.(Additional costs) Tendon, which I ordered and ate, was a combination of shrimp 2+ vegetable combinations, and it was impressive that two crispy king shrimps were so towering.Due to the nature of the tempura rice bowl, I felt that the salad was slightly grabbed.If you want to eat crispy tempura with beer after work, you want to visit again.
원본: 튀김옷이 바삭바삭해서 식감이 좋았고 치킨 텐동은 육질이 부드러워서 먹기 좋았다. 새우 텐동은 새우를 추가해서 먹었는데 양이 꽤나 많아 매우 만족. 연근 튀김도 맛있었고 재방문할 예정!, 번역: The tempura was crispy, so the texture was good, and the chicken tendon was soft because it was soft.Shrimp Ten -dong was eaten by adding shrimp, but there are quite a lot of amount.The lotus root tempura was also delicious and I will return!

 97%|█████████▋| 21739/22421 [08:23<02:07,  5.35it/s]

원본: 주인장 두 분이 친절하고 직원도 친절하다 하이볼도 다른 곳보다 싸고 ㅡ밥은 특별하다는 생각은 안 들지만 ㅡ튀김과 샐러드는 맛이 느끼하지않고 맛있었다, 번역: The two owners are kind and the staff are friendly. The highball is cheaper than anywhere else, and I don't think it's special.
원본: 텐동치고 저렴한 가격에 아주 맛있었음. 혼밥해도 괜찮을까 걱정하는 마음이 있었는데 나말고디 많아서 안심함, 번역: It was very delicious at a low price.I was worried that it would be okay to be good, but I was relieved because I had a lot of me

 97%|█████████▋| 21741/22421 [08:24<02:09,  5.24it/s]

원본: 냉모밀을 먹으러 갔지만 냉모밀은 없었던 텐동집! 첫 텐동이었는데 맛있엇어오, 번역: I went to eat cold hair, but there was no cold wheat!It was the first Ten -dong, but it was delicious
원본: 텐동을 처음 먹었습니다. 맛있습니다. 튀김 생각날 때 또 와야겠네요. 튀김이라 느끼할 수 있습니다. 담엔 콜라와 먹어봐야겠네요., 번역: I first ate Tendon.Delicious.I have to come again when I think of tempura.You can feel it because it is tempura.I have to eat it with cola.

 97%|█████████▋| 21743/22421 [08:24<02:02,  5.54it/s]

원본: 텐동은 이 곳에서 처음 먹었는데 바삭해서 아주 좋았습니다. 계속 먹다보면 느끼해서 물린는 느낌이 좀 있는데 그때 가게내의 조미료를 추가해 먹우면 괜찮습니다. 생맥주가 없는 점은 조금 아쉬웠습니다., 번역: I ate Ten -dong for the first time here, but it was very crispy.If you keep eating, there is a feeling of biting, but it is okay to add seasonings in the store.It was a bit unfortunate that there was no draft beer.
원본: 기본텐동에 계란 추가. 느끼할것 같았는데 아주 바삭하고 맛있음., 번역: Add eggs to the basic Tendon.It seemed to feel, but it is very crispy and delicious.

 97%|█████████▋| 21745/22421 [08:25<01:55,  5.88it/s]

원본: 일요일 저녁이라 그런지 대기 손님이 좀 있었습니다. 주문 후 나오기까지 상당히 오래 걸렸습니다. 그래도 다른 텐동집 보다 월등한 맛 덕분에 괜찮습니다. 음식 준비가 조금만 더 빠르게 된다면 더욱 만족스러울 것 같습니다., 번역: It was Sunday evening, so I had some waiting guests.It took a long time to come out after ordering.Still, it's okay thanks to the superior taste of other Tendon homes.If the food is prepared a little faster, it will be more satisfactory.
원본: 전체적으로 건강한 맛을 지향합니다. 자극적이지 않고 단백합니다. 집에서 어머니, 할머니가 해주는 맛. 수육에 먹는 김치가 두가지 나와요. 숙성도가 달라 고르는 재미가 있어요. 맛있습니다., 번역: Overall, it aims for a healthy taste.It is not irritating and protein.Mother and grandmother's taste at home.There are two kimchi eaten in meat.It's fun to pick up the aging.Delicious.

 97%|█████████▋| 21747/22421 [08:25<01:53,  5.95it/s]

원본: 만두맛도 나쁘지 않고 특별한 불편함도 없지만,. 문을 열고 들어설때 코끝을 자극하는 불편한 냄새ㅡ돼지고기의.ㅡ와 어수선하고 불결한 느낌의 가게 분위기가 많이 아쉽네요. 음식점은 맛만으로만 가는건 아닙니다.., 번역: The dumplings are not bad and there is no special inconvenience.When you open the door and stimulate the tip of the nose ㅡ pork.ㅡ And the atmosphere of the shop is cluttered and unclean.The restaurant is not just a taste..
원본: 만두 보쌈 빈대떡 모두 굿!, 번역: Dumpling Bossam Buddha Buddha rice cake is good!

 97%|█████████▋| 21750/22421 [08:25<01:10,  9.47it/s]

원본: 곰탕 맛집👍다코 참고해서 찾아간 식당인데 진짜 맛있었음!평일 점심시간에 갔었는데 조금 일찍 갔음에도 불구하고 딱 한 자리니 남아 있었음.식탁마다 배추김치랑 깍두기가 덜어 먹을 수 있게 돼있는데 배추김치가 맵고 자극적인데 너무 맛있고 감칠맛이 나서 계속 먹게 되는 맛임. 그래서 밥 다 먹고 김치 한통 사옴😅왕갈비탕 시켰는데 국물 진해서 좋았음. 갈비탕에 큰 갈빗대 두개가 들어 있었는데 고기가 뼈에 많이 붙어 있었고 부드러웠음. 다만 갈빗대 하나는 냉장고기? 같은 맛이 나서 좀 그랬음... 갈비탕 안에 갈빗대 말고도 양지도 들어 있어서 고기 양이 진짜 많았음👍기본으로 제공되는 면 사리도 쫄깃하고 국물과 잘 어울렸음!집만 근처면 일주일에 3번 이상 방문할 것 같은 식당임!!, 번역: Gomtang restaurant 👍 Dako, I visited it and it was really delicious!I went to lunchtime on weekdays, but even though I went a little early, it was only one place.The cabbage kimchi and kakdugi can be eaten on each table, but the cabbage kimchi is spicy and irritating.So I ate all the rice and bought a kimchi 😅 I made a ribs.There were two big ribs in the ribs, and the meat was attached to the bones and soft.Just one rib is refrigerator?It tasted like the same...In addition to the ribs in the ribs, there are many meats, so the amount of meat was really high.If you are near your house, you will visit more than three times a week!!

 97%|█████████▋| 21752/22421 [08:25<01:38,  6.76it/s]

원본: 만두국이 주력이 아니라 기대를 안했는데 깔끔한게 너무 좋다 다른메뉴들도 기대되어 또 방문할예정, 번역: Mandu soup is not the flagship, but I didn't expect it, but it's so nice to be neat. Other menus are expected.
원본: 항상 웨이팅이 기본임 요새 겨울이라 사람 더많을듯 비빔국수를꼭서비스로먹길바람.. 꼭!!, 번역: We always want to eat bibim noodles with the service as we will always be a basic fortress winter..please!!

 97%|█████████▋| 21753/22421 [08:26<01:46,  6.25it/s]

원본: 곰탕을 시키면 사리를 주시는데 꼭 비빔사리 그냥사리 둘다 시켜야한다. 비빔사리가 존맛이니까~, 번역: If you have a gomtang, you will be given a saree.Because bibimbari tastes John ~

 97%|█████████▋| 21755/22421 [08:27<02:55,  3.79it/s]

원본: 가격대비 푸짐한양하고 맛도 좋고 저녁에 술한잔하면서 든든하게 배를 채울수 있어요, 번역: It's a lot of Hanyang and tastes for the price, and you can fill your stomach with a drink in the evening.
원본: 사리곰탕처럼 먹을 수 있어요. 면을 무제한으로 주는 서비스. 역에서 가까움, 번역: You can eat it like a sari gomtang.Service that is unlimited to face.Close to the station

 97%|█████████▋| 21757/22421 [08:27<02:39,  4.16it/s]

원본: 갈비탕...냉동고기에서 나는 특유의 냉장고 냉동 냄새가 심하게남먹는데 오래된건가 하는 생각을 하게됨진짜 심했음그외엔..포장시 김치는 추가비용주차는 1시간이상 할인권 더이상 안들어감갈비찜과같이 먹는데 시간이 오래걸리는음식은 먹으면 음식값내고주차비 따로 더 내야함탕 종류도 뜨거워도 급하게 원샷2분 더나왔고 친절하게 할인권도더 주셨으나주차시스템이 주차비 받고 싶어서 안달남..예전엔 주말엔 편히 여유롭게 식사 했는데밥값도내고 주차비도 내기 싫고쫓기면서 먹고 싶지도 않음여로 모로 실망에..다시 안가게될것같음.., 번역: Galbi -tang...In frozen meat, I think it's old to have a distinctive refrigerator frozen smell..Packaging kimchi for additional costs for more than an hour or more for more than an hour, but when it takes a long time to eat food, it costs food and pay more for parking costs.However, the parking system wants to get a parking fee..In the past, I ate comfortably on weekends, but I didn't want to eat while paying for rice and paying for parking costs..I don't think I will go again..
원본: 동남집은 고기도 맛이 있긴 한데 아무래도 갈비탕이 제맛인거 같네요갈비탕 추천 합니다 또한 만두도 맛이 있어요, 번역: The Southeast restaurant is also tasted in meat, but the ribs are good.

 97%|█████████▋| 21759/22421 [08:27<02:14,  4.91it/s]

원본: 여기 맛잇어요 강츄, 번역: It tastes good here
원본: 명불허전 홍대의 오래된 딸기케이크 맛집원래 이층에 있었던 걸로 기억하는데 앉아서 마실수 있는 장소로 옮겼다.케이크는 역시 명물답게 부드럽고 맛있다. 인기가 많아 금방 매진되니 마감시간엔 확인하고 방문해야 허탕 안칠듯 너무 부드럽고 부담이 없어서 1인 1조각 가능 (원래 홀케이크 사려고 했는데 매진ㅠ)토요일 8시쯤 방문 했는데 10분 정도 웨이팅 했고 웨이팅부터 착석까지 직원분도 친절허고 시스템이 잘 갖춰진 느낌 딸기 생크림 케이크가 먹고 싶다면 추천하고 싶은 선택지다., 번역: I remember that I was on the second floor of the old strawberry cake restaurant of Myeongbul Heojeon Hongdae.The cake is also soft and delicious like a specialty.It is so popular that it is sold out quickly, so it is so soft that you have to check and visit the deadline.If you want to eat strawberry fresh cream cake with a good system and well -equipped system, you want to recommend.

 97%|█████████▋| 21761/22421 [08:28<02:11,  5.02it/s]

원본: 오랜만에 가보니 확장해있었음생크림딸기케이크로 유명한 곳케이크 괜찮음딸기주스는 많이 달았음한번은 먹어볼만함사람 많아서 대화하기는 별로임, 번역: It's been a while since I've been expanding.
원본: 케익 검색할때마다 피오니피오니해서 와봄.별거 아니구만, 나는 더 맛있는 딸기케이크집을 알고있다! 음하하오히려 라떼가 활약했다 :)가게 앞 공터는 포장주문시에만 잠깐 주차할 수 있다. 주차불가, 번역: Every time I search for cakes, I come to Pioni Pioni.It's no big deal, but I know more delicious strawberry cake!The latte was active :) The vacant lot in front of the store can only be parked for a while when ordering.Parking

 97%|█████████▋| 21763/22421 [08:28<02:00,  5.47it/s]

원본: 딸기생크림케이크 괜찮아요빵부분은 거칠어요말차라떼는 보통요, 번역: Strawberry Cream Cake is okay. The bread is rough.
원본: 나에게는 추억이 있는 장소. 예전에 친구랑 갔다가 전화로 갑자기 좋은 소식을 듣고 케이크 한판을 사서 집에 갔던 기억이 난다. 그 기억 뿐이 아니더라도 빙수 맛있어서 가끔 홍대가게되면 가는 곳!, 번역: A place with memories for me.I remember going with a friend and suddenly heard good news on the phone and bought a cake and went home.Even if it's not just that memory, it's delicious, so if you go to Hongdae sometimes!

 97%|█████████▋| 21765/22421 [08:28<01:58,  5.55it/s]

원본: 여기 딸기케이크 진짜 맛있는데 그에 비해서 가격이 저렴한편인거같아요 딴데는 6-7처넌도 하는데 4,100원이라니 ㅎ 맛있어서 두조각 먹고왓어영, 번역: Strawberry cake is really delicious, but the price is cheaper than that.
원본: 여기는 딸기케이크가 유명한데 저는 여기 딸기케이크보다 저 초코케이크랑 치즈케이크가 정말 맛있어요ㅠㅠ완전 꾸덕꾸덕하고 특히 치즈케이크가 정말 최고..한번만 드셔보세요 사진에는 남기지 못한 케이쿠에요ㅠㅠ치즈케이크.., 번역: The strawberry cake is famous here, but I have a chocolate cake and cheese cake than the strawberry cake here..Please try it once in the picture..

 97%|█████████▋| 21767/22421 [08:29<01:50,  5.90it/s]

원본: 케이크 맛있음 강추!! 유명한이유가있음 살짝비싸지만 맛있음, 번역: Cake delicious!!There is a famous reason.
원본: 다시는 안먹을거임 진짜 이걸 먹고 어떻게 맛있다고 할 수 있는지 의문이 생김 나도 나름 내로라하는 돼지인데 케이크를 먹고 행복해지긴 커녕 분노가 가슴속에 차오름, 번역: I'm not going to eat it again, and I have a question about how it can be delicious and I can say that it is delicious.

 97%|█████████▋| 21769/22421 [08:29<01:47,  6.04it/s]

원본: 사람이 많아서 줄을 서야했지만 난로가 있어서 기다리기 좋았습니다. 케이크는 신선한 느낌이엇는데 빵이 조금 건조한 느낌이라 아쉬웠습니다. 딸기는 달고 맛잇었어요. 분위기는 조용하진 않고 대화하는데 지장이 없을 정도에요, 번역: I had to line up because there were so many people, but there was a stove so it was good to wait.The cake was fresh, but the bread was a bit dry.The strawberry was sweet and delicious.The atmosphere is not quiet and there is no problem in talking
원본: 더운 낮에 갔는데 보냉백도 천원, 비닐도 천원, 다 따로 돈을 받더군요. 케익 가격만 몇만원이 되는데도 보냉백을 돈 내고 사야 하는 곳이라니. 카운터 직원은 겉멋 들어 불친절하고, 유료 보냉백으로 케익 포장하는 스킬은 어설프고... 맛은 있지만 서비스 기본이 부족한 곳., 번역: I went during the hot day, but I got a thousand won, a thousand won, and all the money.It's a place where you have to pay for your cold back even though you only have a cake price.The counter staff is unkind and unkind, and the skill of packing cakes with paid cold bags is clumsy...It tastes good but lacks the basics of service.

 97%|█████████▋| 21771/22421 [08:29<01:49,  5.93it/s]

원본: 매장은 깔끔하고 예뻤습니다. 케이크도 너무 부드럽고 달달해서 맛있게 먹었네요. 딸기 좋아하시는 분이면 데이트하러 오셔도 좋을 것 같습니다., 번역: The store was clean and pretty.The cake was so soft and sweet that it was delicious.If you like strawberries, you can come to date.
원본: 친구 생일이라 초코케이크를 샀는데 생크림이 너무 달거나 느끼하지않고 맛있다!위에 올라가있는 과일말고도 케이크속에 시트사이사이에도 바나나가 들어가있다 굿!!개인적으로 그냥 생크림은 생각보다 평범하고 초코생크림이 더 맛있었다카페 안에서 먹으려면 대기를 걸어놔야 할 정도로 인기가 많은 케이크집, 번역: I bought a chocolate cake because it was a friend's birthday, but the fresh cream is not too sweet or felt!In addition to the fruit that is on top, there is a banana between the sheets in the cake!!Personally, the fresh cream is more common than I thought, and the chocolate cream is more delicious.

 97%|█████████▋| 21773/22421 [08:30<01:52,  5.78it/s]

원본: 케이크 예쁘고 생크림 맛있다. 그 근처에 있으면 들러서 먹을 만한 곳. 찾아갈 정도는 아님, 번역: Cake is pretty and fresh cream is delicious.If you are near it, you can stop by.Not enough to go
원본: 사람이 너무 많아서 웨이팅이 길어요 딸기빙수와 케이크는 보이는대로 맛있습니다, 번역: There are so many people, so the weight is long. Strawberry shaved ice and cake are delicious as you see.

 97%|█████████▋| 21775/22421 [08:30<01:50,  5.87it/s]

원본: 예전에는 정말 맛있었는데 사람이 많아지면서 맛이 변한것같아요ㅠㅠ딸기케이크 너무 퍽퍽해졌어요ㅠㅠ요즘에는 케이크 맛집이 너무 많아져서 굳이 줄서서 먹을정도는 아닌듯!, 번역: In the past, it was really delicious, but I think it has changed as a lot of people.
원본: 너무맛잇어요 주차는 안됏던것같아요 치즈보단생크림이맛잇어요, 번역: It's so delicious. I don't think it was parked.

 97%|█████████▋| 21777/22421 [08:30<01:50,  5.84it/s]

원본: 아 잔짜 역대급 맛없음 이 가격에 이따위 맛이라니... 아래 다른 1점 준 분이랑 완전 개공감 나도 디저트라면 한 디저트 하는 매니안데 여긴 진짜 디저트가 성의가 없다.... 시판 생크림 케잌도 이거보단 맛날듯., 번역: Oh, it's a taste of all time...If you are a dessert, even if it's a dessert, the other one point below and the completely open feeling....The commercial fresh cream cake seems to be better than this.
원본: 매장 작을때 입소문으로 바글바글하던 딸기케익맛집인데 돈벌고 홍대 메인거리에 크게 냈더라고요 아니뭐 이정도까지 사람이 많나 싶을정도이긴합니다. 인생딸기케익을 꼽자면 여기보다 신사역 김록훈베이커리 딸기케익 추천합니다. 피오니는 홍대 놀러온친구가 디저트 타령할때 데리고 가기 좋은곳으로 추천드립니다, 번역: When it was small, it was a strawberry cake restaurant that was crowded with word of mouth.His life daughter, Ki -cake, is recommended here.Fioni is recommended as a good place to take when a friend who came to Hongdae is dessert.

 97%|█████████▋| 21779/22421 [08:31<03:28,  3.08it/s]

원본: 딸기생크림 케이크 제가 먹어본것중에 최고에요. 하지만, 초콜릿 바나나 케이크와 딸기빙수는 정말 실망이였습니다. 딸기생크림 케이크만 먹는거 추천해 드려요. 매일 갈때마다 몇팀씩 기다리고 있어서 대기 타야해요 ㅠㅠ. 글구, 카페가 살짝 좁은편이라 불편하기도 했어요., 번역: Strawberry Cream Cake is the best I have eaten.However, chocolate banana cakes and strawberry shaved ice were really disappointing.I recommend eating only strawberry cream cakes.I wait a few teams every day, so I have to wait.It was uncomfortable because the cafe was a bit narrow.
원본: 친구들과 소문듣고 일부러 찾아서 갔네요딸기빙수, 딸기 생크림케잌,아이스 아메리카노 를 먹어봤어요아메리카노는 진하고 씁쓰름하니 맛있었습니다딸기 케잌은 부드러운 빵을기대했으니 빵은 좀 퍽퍽한 느낌이 있었지만 부드러운 크림과 딸기가 듬뿍있어서  좋았습니다빙수도 맛있었지만 옆에 곁들여진 딸기 절임??어떻게 먹는것이 맛이 있는건지 설명이 있었으면 합니다저희는 빙수위에 부어 먹었는데...그리 먹는건 아닌듯하네요^^우유빙수라..녹은 빙수를 빨대로 마셔봤는데~~맛있네요^^, 번역: I heard rumors with my friends and I went to find it on purpose.The shaved ice was also delicious, but the strawberry pickled with the side was the tasty of how to eat it...I don't think it's going to eat..I tried to drink melted shaved ice with a straw ~~

 97%|█████████▋| 21780/22421 [08:32<03:04,  3.47it/s]

원본: 무난한 딸기 생크림 케이크를 파는 카페에요. 카페 분위기는 그냥 그래요. 사람이 많아서 여유롭게 디저트를 먹고 커피를 마실만한 곳은 아닌것 같아요., 번역: It is a cafe selling strawberry cream cake.The cafe is just like that.There are so many people that I don't think it's a place where you can eat desserts and drink coffee.

 97%|█████████▋| 21781/22421 [08:32<03:00,  3.54it/s]

원본: 케이크 달지않고 촉촉해요 맛나긴해용  정말여기 오래되엇어요, 번역: It is not sweet and moist. It tastes good.

 97%|█████████▋| 21782/22421 [08:32<02:52,  3.70it/s]

원본: 여기 진짜 처음갔을때 신세계!!!아마 생크림맛이 달라서 그랬는데요즘은 피오니따라서 생크림이맛있는 케이크가많이생긴것같아요!!!그치만 피오니가 원조!!!, 번역: Shinsegae when it was the first time here!!!Maybe it's because the fresh cream flavor is different, but nowadays, I think there are a lot of cakes with delicious creams!!!But Fioni is the original!!!

 97%|█████████▋| 21783/22421 [08:32<02:44,  3.87it/s]

원본: 맛있어요 가격이 좀 나가긴하는데 다른 케이크집 이곳 저곳 가봤는데 여기가 제일맛있음 근데 가격이 좀 나감 가족들 생일때마다 항상 여기와서 사가지고감, 번역: It's delicious. It's a bit out of the price, but I've been to another cake house, but it's the most delicious here, but every time the price is a little, I always come here and buy it here.

 97%|█████████▋| 21784/22421 [08:33<02:42,  3.92it/s]

원본: 여긴 1인 1메뉴 시켜야하고 ㅡ매장도 좁고 ㅡ매번 대기타야함 딸빙은 양이 너무 작아 ㅡ.ㅜ 그냥 클마스 딸케 포장용으로 정도가 좋을듯 ㅎㅎ, 번역: This is a one -person menu, and the store is also narrow.ㅜ It's just good for packaging Classmas daughter.

 97%|█████████▋| 21785/22421 [08:33<02:40,  3.97it/s]

원본: 생크림이 담백하여 케이크는 확실한 상위권딸기 숏케이크가 끌리는 날 가서 먹으면 만족할만한 맛이 나온다.음료는 케이크에비해 아쉽지만 딸기케이크 하나로 뜬 카페기때문에 후회는 없을 것전체적으로 화이트톤의 카페여서 사진도 잘 나오는 편임, 번역: The fresh cream is light, so the cake is a satisfying taste when you go to the day when the top strawberry short cake is attracted.The drink is unfortunate compared to the cake, but because it is a cafe with a strawberry cake, there is no regret.

 97%|█████████▋| 21786/22421 [08:33<02:37,  4.03it/s]

원본: 웨이팅 있었엉요. 생크림 잘 안 먹은 편인데 맛있게 먹었어요., 번역: There was a waiting.I didn't eat fresh cream well, but I ate it deliciously.

 97%|█████████▋| 21787/22421 [08:33<02:36,  4.06it/s]

원본: 맛없어요 생크림이 맛있다고해도 시트가 넘 별로라씹는 식감이 넘 별로였어요 예쁘긴한데 진짜 저는 별로입니다, 번역: It's not good.

 97%|█████████▋| 21788/22421 [08:34<02:31,  4.19it/s]

원본: 한번쯤 가볼만 합니다 웨이팅할 정도는 아닙니다 맛있어요 ㅎㅎ, 번역: It's worth a visit. It's not enough to wait. It's delicious.

 97%|█████████▋| 21789/22421 [08:34<02:31,  4.16it/s]

원본: 손님들 많은 날에 딸기케이크 포장해가기에 무난함.뭐, 그거 하나때문에 일부러 갈 필요까지는 없음, 번역: Many guests are safe to pack strawberry cakes on a day.Well, there is no need to go on purpose because of that

 97%|█████████▋| 21790/22421 [08:34<02:32,  4.15it/s]

원본: 진리의 딸기케이크 맛집... 생일 케이크로 이걸 사오는 친구가 있다면 평생 친구 예약...💕, 번역: Strawberry cake restaurant of truth...If you have a friend who buys this with a birthday cake, you can make a reservation for a lifetime...💕

 97%|█████████▋| 21791/22421 [08:34<02:32,  4.13it/s]

원본: 케잌을 싫어하던 내 취향을 바꾼 가게.케잌이 이리도 촉촉하면서 상큼하고, 부드러우면서 달콤하구나 하는 걸 깨달았다. 그 동안 먹었던 건 케잌이 아니었구나...하고 울면서 먹었다. 특히 샴페인과 먹으면 최고의 궁합.피오니 이후로 이 정도의 케잌을 하는 집이 요즘엔 꽤 생기긴 했지만, 여전히 내게는 최고의 가게다., 번역: The store that changed my taste that I didn't like cakes.I realized that the cake was moist, fresh, soft and sweet.It wasn't a cake that I had eaten in the meantime...I ate while crying.Especially the best match with champagne.Since Fioni has been a lot of cakes such as a cake, it's still the best shop for me.

 97%|█████████▋| 21792/22421 [08:35<02:30,  4.19it/s]

원본: 사람이 많고 맛은 보통 케이크 맛인 거 같아요 분위기 좋았습니다, 번역: There are a lot of people and the taste is usually tasted.

 97%|█████████▋| 21793/22421 [08:35<02:30,  4.16it/s]

원본: 케익 맛있어요! 단점이라면 남자끼리 가긴 힘든 분위기가..; 남자 혼자 가기도 뭔가 좀 눈치보이는 그런게 있어요, 번역: Cake is delicious!The downside is that it's hard to go to men..;There is something that you can see something a little bit of a man.

 97%|█████████▋| 21795/22421 [08:35<01:56,  5.36it/s]

원본: 맛은 최고당, 번역: The taste is the best

 97%|█████████▋| 21797/22421 [08:35<01:41,  6.13it/s]

원본: 피오니 딸기케이크는 몇년전부터 팬이었기에... 미니사이즈 한판쯤 혼자 먹습니다, 번역: Fioni Strawberry Cake has been a fan for a few years...I eat mini size alone

 97%|█████████▋| 21798/22421 [08:36<01:51,  5.57it/s]

원본: 케잌은 맛잇는편이지만 음료는 최악이네요...음료수보다 못해요...., 번역: The cake is delicious, but the drink is the worst...It's not as drinking....

 97%|█████████▋| 21799/22421 [08:36<02:41,  3.85it/s]

원본: 딸기 생크림을 좋아한다면 꼭 먹어볼 것!, 번역: If you like strawberry cream, you should definitely try it!

 97%|█████████▋| 21803/22421 [08:36<01:33,  6.62it/s]

원본: 케이크 한조각에 9500원 할정도로 가격은 비싼편입니다케익이 유명해서 그런지 매장은 작은데 사람이 많으니 정신 없더라고요...케익은 맛이 괜찮았습니다, 번역: The price is expensive enough for a piece of cake. The cake is famous...The cake tasted good

 97%|█████████▋| 21804/22421 [08:37<01:58,  5.22it/s]

원본: 이태원역에서 꽤 가까운 편이에요가게는 작은편이고 3명 이상은 입장할 수 없다고 해요저는 평일 3시쯤 방문했더니 웨이팅이 없었지만 그 뒤로는 1-2팀 정도 있었어요그리고 웨이팅 때문에 1시간 반 정도 시간제한이 있어요입장시간을 영수증에 써주시더라구요 참고하고 가시는게 좋을 것 같아요!노버터 노오일로 만든 케이크고, 총 12종류 정도가 있어요매일 케이크 종류는 조금씩 바뀌는 것 같아요키에리 인스타에 매일 스페셜케이크가 올라오니 확인하면 좋을 것 같아요크게 쌀케이크, 치즈케이크, 스콘을 판매하고 있어요쌀케이크는 포슬포슬한 식감이고, 치즈케이크는 말 그대로 꾸덕꾸덕한 식감이에요그렇지만 느끼하지 않아서 한 개를 다 먹어도 물리지 않아요대체로 맛이 강한편이 아니라, 단걸 좋아하시는 분들은 호불호가 갈릴 수 있지만 음미해서 먹다보면 훨씬 매력있어요그리고 스콘이 의외로 정말 맛있었어요!, 번역: It's quite close to Itaewon Station. The shop is small and three or more people can't enter.I wrote it on it.There are about 12 kinds of cakes made of no -butter no oil, so the daily cake seems to change little by little.Rice cake is a porous texture, and cheesecake is literally a virtuous texture, but I don't feel it.It's much more attractive and the scone was surprisingly delicious!

 97%|█████████▋| 21805/22421 [08:37<02:04,  4.94it/s]

원본: 건강에 좋을 것 같은 담백한 케이크를 원한다면, 테이크아웃을 목표로 들르길 추천. 4명 이상은 가게 안에 못들인다고 입구에 붙인 안내문이 이색적. 조용하고 아담한 카페 상황을 고려한듯하다. 테이크아웃하는 사람이 많은데, 먼 거리 이동예정이라고 하면 케이크를 랩핑해서 원래 담아주는 곳인 종이상자에 조심스럽게 담아준다. 요즘같이 쌀쌀할 때는 상관없지만 애매한 날씨일때는 당황스러울듯. 맛이 없는 것은 아니지만 가격을 생각하면 갸우뚱하게 된다. 허술한 포장도. 유명한 파티쉐의 시그니처 케이크를 대할 때처럼 시각적으로 미각적으로 황홀감을 느끼기는 어렵지만, 다 먹고 속은 편한게 장점이랄까. 제일 신상인 인진쑥할머니케이크는 이름 그대로 담백한 건강한 쑥떡 맛., 번역: If you want a light cake that seems to be good for your health, you should stop by the takeout.More than four people are not in the entrance because they can't be in the store.It seems to consider the quiet and small cafe situation.Many people take out, but if you are planning to travel a long distance, you can wrap the cake and put it carefully in the paper box, which is the original place.It doesn't matter when it's chilly these days, but it's embarrassing when it's ambiguous.It's not tasteless, but when you think about the price, you get stupid.Lax packaging.It is difficult to feel visually visual and visually eccentric as when dealing with a famous patissier signature cake, but it is easy to eat and feel comfortable.Injin Mugwort Grandmother Cake, the most new, is as its name suggests.

 97%|█████████▋| 21806/22421 [08:37<02:12,  4.65it/s]

원본: 명성에 비해서는 그렇게까지 맛있는지는 모르겠지만 맛있긴 합니다. 조용한 분위기를 지향한다고 하지만 시장통에 가까워요., 번역: I don't know if it's so delicious compared to fame, but it's delicious.It's a quiet atmosphere, but it's close to the market.

 97%|█████████▋| 21807/22421 [08:38<02:14,  4.56it/s]

원본: 카페에 가면 사람이 많아요.  케이크랑 커피 먹는곳이 따로있고 스콘,푸딩을 파는 곳이 따로 있어요~^^, 번역: If you go to the cafe, there are a lot of people.There is a separate place to eat cakes and coffee, and there is a separate place to sell scones and pudding ~

 97%|█████████▋| 21808/22421 [08:38<03:09,  3.24it/s]

원본: 수요미식회에 나왔다는 케익집. 독특하고 맛보지 못했던 케익들이 많아요. 웨이팅있고 주말엔 이용시간 제한 있습니다. 편한 자리는 아니고 어수선하긴 하지만, 케익은 인정., 번역: A cake restaurant that came out at the demand gourmet.There are a lot of cakes that have been unique and have not been tasted.There is a waiting time limit on weekends.It's not comfortable, but it's cluttered, but cake is recognized.

 97%|█████████▋| 21810/22421 [08:39<02:43,  3.73it/s]

원본: 케이크 맛 정말 좋아요근데 매장에서 먹고가는데 왜 테이크아웃 잔에 주신지 모르겠어요매장 사람이 늘 많아서 오붓하게 앉아 먹을 수 있는 분위기는 아니에요 제한 시간도 있고... 그래도 케이크가 맛나요, 번역: I really like the cake, but I eat it at the store...Still, the cake tastes good
원본: 조용한 구석에 위치. 유명하고 작은 카페라 1시간 반 정도 시간제한 있음. 사람 많으면 대기할 수 있고 항상 바빠보이는 곳. 화장실은 실내에 있고 이용하기 괜찮음. 핸드폰 충전 어려움. 케이크 종류 많고 비싸고 맛있음. 공장에서 찍어낸 설탕맛 가득한 케이크가 아니라 건강하고 담백한 맛이 있어서 좋았음. 아이스음료는 스텐컵에 담아줌. 남은 거 포장가능., 번역: Located in a quiet corner.Famous and small cafes are limited for an hour and a half.If you have a lot of people, you can wait and always look busy.The toilet is indoors and it's okay to use.Difficult to charge mobile phone.A lot of cakes, expensive and delicious.It was not a cake filled with sugar from the factory, but a healthy and light taste.Ice drink is put in a stainless cup.The remaining one is available.

 97%|█████████▋| 21811/22421 [08:39<02:27,  4.13it/s]

원본: 평소에 자주 방문하는 곳입니다 케이크가 부담스럽지 않고 진짜 맛있어요 단호박 진짜 추천합니다 진짜 너무 비싸긴한데 포만감이 엄청 커서 밥먹은것처럼 배불러요, 번역: I usually visit often. The cake is not burdensome and it is really delicious. It is really recommended.

 97%|█████████▋| 21813/22421 [08:40<03:17,  3.09it/s]

원본: ★재료본연의맛을 살린 케이크★키에리케이크는 정말 한번먹으면다른케이크들은 느끼해서 못먹을정도로깔끔하고 건강한맛집좀비싼감없지않아있지만 그만큼 무지무지 건강하고몸에좋은 재료들을 듬뿍 넣어 만드는 디저트들.호불호가 갈리는 시트지만, 내가 경험한바로는 한번 호를 외친사람은 반드시 재방문을 하게 되곤 한다.모든케이크를먹어봤는데, 모든케이크가 재료 본연의맛을 최대한 살렸다."얼그레이"는 진한 홍차의 향이 듬뿍나고,"다크초코"는 달지않은 카카오시트와 75%다크초콜릿의 깊은맛,"콩크림은" 그야말로 인절미같은 콩의 고소함,"할머니케이크"는 호두가씹히는 고소한 현미시트와 캐슈넛크림이 정말 조화롭다고 해야하나.그치만 모두 건강한 달콤함이라 정말 놀랄만하다., 번역: ★ Cake cake that tastes the ingredients ★ Kiieri cake is really clean and healthy that you can't eat cakes.It's a sheet where a dislike, but I have experienced a person who once shouted.I tried all the cakes, and all the cakes made the maximum taste of the ingredients..Earl Gray.Is a lot of rich black tea.Dark chocolate.The deep taste of the sweet cacao sheet and the 75%dark chocolate.Bean cream.Indeed, the savory of beans like Injeolmi.Grandmother cake.Is that the walnuts are chewy brown rice sheets and cashew nut creams really harmonious.But it's all surprised because it's all healthy.
원본: 건강에 좋은 케이크라더니 엄청 달지않고 슴슴한게 맛있어요ㅎㅎ 역시 시크니처인 할머니케익이 제일 맛있네요ㅎㅎ, 번역: It's a healthy cake, but it's not very sweet and it's delicious.

 97%|█████████▋| 21815/22421 [08:40<02:27,  4.10it/s]

원본: 케이크 맛이 특이하고 맛있어요초코라떼도 달콤하고 좋았습니다., 번역: The cake taste is unusual and delicious.
원본: 손님은 많은데 내부가 좁아 시끄럽고 자리가 협소한게 아쉬움쌀케이크를 테이크아웃해서 먹었는데 느끼하지도 달지도 않고 고소한게 맛 괜찮았음부드럽고 자극적이지 않아서 연세 있으신 어른들도 좋아하실 것 같음, 번역: There are a lot of guests, but the interior is narrow, so it's noisy and narrow.

 97%|█████████▋| 21817/22421 [08:40<02:12,  4.55it/s]

원본: 이름그대로 맛이 느껴지는 케이크였어요 가격은 조금 있는 편이지만 먹어볼만했어요 포장해서 화이트초코가 굳어서 아쉬웠어요 바로먹으면 더맛있을꺼같아요!, 번역: As the name suggests, it was a tasty cake. The price was a little bit, but it was worth eating.
원본: 음식: 인상적인 맛의 케이크. 과일들어간 케익과 초코케이크를 먹었었는데, 그렇게 부담스럽지 않고 매력적이라 느껴졌습니다. 주문했던 차 종류도 매력적인 맛이네요. 가격이 약간 비쌌던 걸로 기억하지만.... 이정도의 맛이라면. 내가 사는 동네라면 종종 방문했을 것 같다고 느꼈지만...서비스: 일단 별점을 크게 깎는 부분은 서비스입니다. 직원분들은 충분히 친절하시지만.... 직원이 정해놓은 시간 동안만 카페에 있을 수 있다는 건 카페로서의 매력을 크게 반감시킵니다. 또한 추가주문해도 정해져있던 시간 안에 나가야 하니 '시간 제공'의 기준이 무엇인지도 잘 모르겠네요.그리고 노키즈존입니다. 차별적 발상에 대해 지나치게 무심한 노키즈존들은 아무리 훌륭하다 해도 굳이 두 번 이상 방문하고 싶지 않습니다.분위기: 아기자기하고 귀여워요.위생상태: 준수합니다., 번역: Food: A cake of impressive taste.I ate cakes and chocolate cakes from fruits, and it felt so burdensome and attractive.The type of tea I ordered is also attractive.I remember that the price was a bit expensive....If this tastes.I felt that I would often visit if I lived...Service: Once you have a big cutting part, the service is the service.The staff are kind enough....Only in the café that can only be in the cafe for the time it is set by the employee greatly reduces the charm as a cafe.Also, even if you order an additional order, you have to go within the time that was set, so I'm not sure what the criteria for 'time provision' are.And Nokids Zone.Non -Kids, who are too indifferent to discriminatory ideas, do not want to visit more than once.Mood: It's cute and cute.Hygiene: Compliance.

 97%|█████████▋| 21819/22421 [08:41<02:02,  4.93it/s]

원본: 건강한 케이크와 스콘를 맛볼수있어서 좋았다 하지만 내부 공간이 작은게 단점, 번역: It was good to be able to taste healthy cakes and scones, but the interior space is small
원본: 일단 들아가자마자 분위기가 좋고 점원들이 매우 친절했다. 내가 갔을 때는 사람이 복작복작 많았다. 돌아다니다가 들어간 거라 케이크랑 음료만 시켰는데 나중에 스콘이 유명하다는 걸 알게되었다. (그리고 나중에 노키즈존인 것도 알게되었다. 아이를 동반하신분은 스콘을 사간다 거나 할 수는 있지만 먹고 가는 건 안 된다고 하니 주의!) 나는 뭐였지.. 바나나케이크였나 그런 걸 시키고 음료는 에이드를 마셨다. 일행이 시킨 메뉴까지는 기억이 안 남... 막 존맛탱!까지는 아니었는데 맛이 깔끔하고 여타 먹어보았던 건강컨셉 푸드보다 맛있는 편이었다. 만족스러웠으나 재방문의사는 딱히?, 번역: As soon as I listened, the atmosphere was good and the clerks were very friendly.When I went, there were a lot of people.I went around, so I only had a cake and a drink, but later I found out that the scone was famous.(And later I learned that it's Nokids John. If you are accompanied by a child, you can buy scones, but you can't eat it!).It was a banana cake, and the drink drank aid.I don't remember until the menu made by the party...John Tangtang!It wasn't until, but it tasted clean and more delicious than the health concept food I had eaten.I was satisfactory, but the doctor is just a return doctor?

 97%|█████████▋| 21820/22421 [08:41<01:57,  5.12it/s]

원본: 매장내부가 시끌벅적한거 빼면 좋습니다. 치즈케이크가 맛있어요., 번역: It is good to take out the inside of the store.The cheesecake is delicious.

 97%|█████████▋| 21822/22421 [08:42<02:58,  3.36it/s]

원본: 흑미 콩케이크 엄청 고소하네요. 케잌인데 별로 달지않고 고소한 맛이 강해요 딸기 케이크도 많이 달지 않아요. 건강하게 맛있는 느낌. 몇개라도 먹을 수 있겠어요 ㅋㅋㅋ 매장이 넓지는 않아서 웨이팅이 있어요., 번역: I'm so sued for black bean cakes.It's a cake, but it's not very sweet and tastes strong.It feels healthy and delicious.I can eat even a few lol.
원본: 전이 맛있당 자리 잘 못잡으면 담배연기 마시면서 술마셔야함, 번역: I have to drink while drinking cigarette smoke if I can't get a good seat.

 97%|█████████▋| 21824/22421 [08:42<02:17,  4.35it/s]

원본: 해물파전 맛집!! 비오는 날 막걸리에다가 전 먹기 좋음!! 다만 가게 바로 앞이 담배존..., 번역: Seafood Pajeon Restaurant!!On a rainy day, it's good to eat for makgeolli!!Just in front of the store cigarette zone...
원본: 9시넘어서가면주방마감돼요 그건 좀아쉽지만 맛잇어요 소스를뿌리지말고 찍어먹는걸로먹어도바삭하니 맛잇을거같아요, 번역: If you go beyond 9 o'clock, it's easy to finish. It's a little easy, but it's delicious.

 97%|█████████▋| 21826/22421 [08:43<02:03,  4.83it/s]

원본: 깔끔한분위기에음식또한 캐주얼 하니입이 즐거운 시간이였내요, 번역: The food is also casual in a neat atmosphere, so it was a fun time.
원본: 저기 대왕돈까스는 먹을수있는 시간이 있는가봐요.오후 6시정도에 갔는데 도전못한다고 하네요그게 저기 처음 가보는 이유아닌가 생각하는데 안되는게 어딨어!!!!! 그리고 주차공간이 쓰레기임차끌고 가지말아요, 번역: I think there's time to eat.I went to 6 pm but I can't challenge it.!!!!And don't go on the parking space.

 97%|█████████▋| 21827/22421 [08:43<01:56,  5.10it/s]

원본: 2차로 맥주 마시며 이야기 하는 손님들이 많아 회전율이 빠르지 않아요 약간의 웨이팅은 생각하고 오셔야 할것 같아요!안주들은 그냥 무난무난 해서 기본안주로 나오는 칩만 먹어도 충분할 것 같아요. 맥주가 종류가 많고 맛있네요! 이색 맥주도 많아서 시도해보면 좋은데 무턱대고 따르면 비싸니 ㅎㅎ 주의하세요!, 번역: There are a lot of guests who are talking about beer for the second time, so the turnover is not fast.The snacks are just so good that it is enough to eat the chip that comes out as a basic snack.There are many kinds of beer and delicious!There's a lot of unique beer, so it's good to try it.

 97%|█████████▋| 21828/22421 [08:43<02:47,  3.55it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다양한 맥주를 조금씩 맛볼 수 있어서 좋다! 맥주 많이 안 마시는 사람도 여러가지 마셔보게됨 ㅎㅎ 술맛 별로 안나는 과일 맛 나는 맥주가 특히 내스타일이고 안주는 무난한둣 감바스보단 치킨이 맛났당, 번역:

 97%|█████████▋| 21829/22421 [08:44<03:11,  3.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 원하는 맥주를 원하는만큼 먹을 수 있어서 간편하고 좋았습니다 따른만큼 가격도 보이구여, 번역:

 97%|█████████▋| 21830/22421 [08:44<04:07,  2.39it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔하고 분위기도 좋고 맛있는 수제맥주 마실 수 있어서 좋아요. 맥주 많이 마시면 가격대가 좀 있어요., 번역:

 97%|█████████▋| 21831/22421 [08:45<04:23,  2.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기본안주 나쵸칩과 음식들이 맛있고, 원하는 종류의 맥주를 원하는 만큼 먹을 수 있어서 좋아요., 번역:

 97%|█████████▋| 21832/22421 [08:45<04:46,  2.06it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 모임하러 방문했는데 분위기도 좋고 다양한 맥주를 맛볼 수 있어서 좋았습니다!, 번역:

 97%|█████████▋| 21833/22421 [08:46<04:42,  2.08it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맥주 따를 때 거품이 너무 많이 나와서 마신 것 치고 가격 너무 많이 나와요. 안주는 괜찮네요, 번역:

 97%|█████████▋| 21834/22421 [08:46<04:26,  2.20it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다양한 맥주를 맛볼 수 있어 좋았어요. ml당 단가도 착하네요. ㅎㅎ, 번역:

 97%|█████████▋| 21835/22421 [08:47<04:26,  2.20it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다양한 맥주를 직접 골라 따라 먹는 것은 여러모로 장점이 많은 듯. 다만 안주들의 경우손님이 몰릴 때는 일부 메뉴들의 퀄리티가 너무 떨어지는데 뭐 이를테면 윙에 간이 안되어 있다던지.. 훈제삼겹이 다소 식은듯한 상태로 서빙이 된다든지 등등...대표들은 이 부분에 대하여 음식맛을 평준화 시킬 수 있는 방안에 대해 고민해 볼 필요가 있겠다., 번역:

 97%|█████████▋| 21836/22421 [08:47<04:55,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깨끗하고 맛있고 에어컨 빵빵합니다, 번역:

 97%|█████████▋| 21837/22421 [08:48<04:37,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 넓고 깔끔한 분위기에, 맥주 종류가 정말 많아서 골라먹는 재미가있다. 음식이 특히 맛있어서 식사만 하고싶을때도 올만한 장소임., 번역:

 97%|█████████▋| 21838/22421 [08:48<05:02,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 출출할때. 늦은 저녁 가볍게 먹기 좋은 곳! 잔치국수 집 많고 많지만, 이 집 국수가 엄청 특별한것도 아니지만. 이상하게 여기가 제일 맛나요. :), 번역:

 97%|█████████▋| 21839/22421 [08:49<04:46,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 경기도 가는 버스정류장 바로 앞에 있어서 처음 생겼을때는 저녁 걸렀을때 간단하게 먹기 좋겠다 생각했는데 의외로 너무 맛있어서 일부러 가기도 해요. 별거 없는거 같은데 이런 국수 먹을 집이 의외로 잘 없다는.. 간장국수도 맛나는데 멸치국물이 너무 맛있어서 항상 멸치국수만 시키게 된다는. (다른 메뉴 시켜도 국수국물 따로 주긴해요), 번역:

 97%|█████████▋| 21840/22421 [08:49<05:05,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주문하는곳 앞에 서있어도 자기들끼리 이야기할거 다 하다가 한참 뒤 주문 받음. 그렇게 해서 받은 음식도 가성비가 떨어짐. 조용한 카페라길래 갔는데 전혀 조용하지 않음., 번역:

 97%|█████████▋| 21842/22421 [08:50<04:05,  2.36it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저렴한 가격대에비해 구성이 실합니다.비록 부족하지만 오마카세를 지향하는 업장 중 가성비로는 최강인것 같아요., 번역:

 97%|█████████▋| 21843/22421 [08:50<04:12,  2.29it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 좋아하는 맛집입니다, 점심은 15000원이고 11시반에서 2시반까지 점심입니다. 가성비가 훌륭하고, 주차는 가게앞에 1-2대정도 주차할수 있을거같습니다. 예약은 필수입니다/02-822-3455 상남스시. 재료가 떨어지면 못먹습니다! 만오천원에 죽,샐러드를 시작으로 소면,디저트까지 훌륭합니다👍 그날그날 제공되는 스시는 달라집니다~~특히 콜키지프리이며, 다찌에서 먹는걸 추천드립니다❤, 번역:

 97%|█████████▋| 21844/22421 [08:51<04:42,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 팀 회식으로 다섯명이 다찌로 예약해저녁코스를 먹었습니다.저녁시간이라 바빴지만 잘 챙겨주시고단골을 알아봐두시고 서비스까지가성비 최고라고 생각합니다., 번역:

 97%|█████████▋| 21845/22421 [08:52<04:57,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마곡나루역 근처에 있구요내부도 깔끔한편이고쌈 좋아하시는 분들이 가면 좋을것같아요세트를 시키면 밥 찌개 두루치기가 나오고찌개는 김치와 된장 중에 선택할수있어요쌈채소가 종류도 다양하고 셀프로 가져오면 되기때문에먹고싶은 것을 원하는 양만큼 먹을수 있어서 좋네요된장찌개가 괜찮았고밑반찬과 두루치기도 나쁘지않네요마곡근처 밥집을 찾으신다면 추천드려요, 번역:

 97%|█████████▋| 21846/22421 [08:52<04:56,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마곡에 있는 가게.확실히 가성비가 좋습니다. 야채도 리필할 수 있고요. 눈치 안보고요.그리고 된장찌개도 훌륭합니다. 무엇보다 기본 고기도 제법이어스 여러모로 대식가들한테는 적당할 것 같습니다., 번역:

 97%|█████████▋| 21847/22421 [08:53<04:53,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 무한리필이 가능한 쌈채소가 있어서 건강해지는 기분이에요. 메뉴도 주문하면 금방나오고 가격도 적당한 편입니다., 번역:

 97%|█████████▋| 21848/22421 [08:53<05:01,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 쌈채소가 셀프바로 무한리필됨.. 눈치안보고 먹어서 좋음.. 고기도 찌개도 맛남.., 번역:

 97%|█████████▋| 21849/22421 [08:54<04:34,  2.08it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저염식으로 건강한 밥을 맛있게 먹을 수 있었어요!! 평소 자극적인 음식 좋아하신다면 패쓰하시길, 번역:

 97%|█████████▋| 21850/22421 [08:54<04:26,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 나물좋아하는 사람에게 딱 좋음! 인기있는 메뉴는 시간이 걸릴 수 있음. 공연 할인도 가능하고 현대 포인트 연결 되어 있음, 번역:

 97%|█████████▋| 21851/22421 [08:54<04:19,  2.20it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 블로그에 많이 떠서 건강한 밥을 먹고자 들렀는데 초딩입맛인 저에게는 그저그럭 먹을만 했습니다.  계란말이가 먹고싶었는데 된장찌개 시켜야지만 준데요..., 번역:

 97%|█████████▋| 21852/22421 [08:55<04:12,  2.25it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 어린이 메뉴. 양 적은 성인이 시키기에 괜찮음.생각보다 양이 적진 않은데 일단 밥 공기 가득 밥이 서빙되고 사이드 메뉴가 많다. 많아서 남김. 슴슴한 맛. 독특하지만 매력적이진 않았다.명란비빔밥은 살짝 비린 맛이나지만 전체적으로 두 메뉴 모두 삼삼했다., 번역:

 97%|█████████▋| 21853/22421 [08:55<04:16,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 정갈하고 깔끔하고 짜지않고 오히려 싱거운 음식 좋아하시는 분들은 자주 찾으실 듯 해요! 조미료나 자극적인 맛이 들어가지 않아 그런데로 저는 좋았습니다. 반찬은 더 달라고 하면 더 주시고, 주방 상황이 여의치 않을때 미리 양해를 구하셔서 좋았어요., 번역:

 97%|█████████▋| 21854/22421 [08:56<04:23,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 원래 수육 위에 고추냉이 소스와 고추절임이 올려져서 나오는데, 따로 해줄 수도 있다길래 저렇게 플레이팅 되었어요. 맛은 심심하게 느껴질 수 있는데, 가볍게 먹기 괜찮아요., 번역:

 97%|█████████▋| 21855/22421 [08:56<04:44,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 전체적으로 깔끔한 한식집기본 산나물밥은 간장양념으로 맛있음찬들도 깔끔하나 맛이 심심함간이 싱겁다기 보다 제육 코다리조림등 맛이 밍밍함건강한 맛? 된장국도 재료의맛이 많이 나는 씁쓸함, 번역:

 97%|█████████▋| 21856/22421 [08:57<04:27,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 보기는 좋은데 맛이없다 메인이랑 반찬이랑 중복되고 맛노, 번역:

 97%|█████████▋| 21857/22421 [08:57<04:30,  2.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛집이래서 찾아갔는데 들어가면서부터 비린내인지 찌린내인지 불쾌한 냄새가 진하게 났습니다. 그리고, 음식도 냄새가 나더라구요.. 설렁탕은 좀 덜났지만 그래도 찝찝했어요. 김치는 맛있긴 했는데, 자르는 가위랑 집게도 안씻고 테이블마다 다 돌려쓰더군요.. 나왔는데도 냄새나는 느낌이예요 ㅠ, 번역:

 97%|█████████▋| 21858/22421 [08:58<04:50,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 도가니탕 진합니다!어르신들 반주하시는 분위기의 노포이며가격이 참 착했는데 좀 올랐어요그래도 양은 푸짐.. 김치도 맛남.., 번역:

 97%|█████████▋| 21859/22421 [08:58<05:00,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 오래된 지역 내 맛집으로 알려져 있음. 도가탕 맛과 품질은 소소. 김치와 깍뚜기는 시큼하고 달고 맛있음. 덜어먹는 파와 다대기, 소금은 테이블에 오픈되어 있고 오래되어 비위생적임. 가게 전체 위생 불량임., 번역:

 97%|█████████▋| 21860/22421 [08:59<04:53,  1.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있음깍두기 맛있음 더 달라고 하면 더 줌밥 추가비용 받음 1천원소금이랑 고기만 먹었는데도 냄새 안남국물 끝에 누린 맛이 살짝 나지만 전체적으로 안나는 편, 번역:

 98%|█████████▊| 21861/22421 [08:59<04:29,  2.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 약각 꼬릿한 진한 육수가 땡길 때 해장으로도 좋음 기본은 고기는 많지 않으나 그래도 가격은 좋은 편, 번역:

 98%|█████████▊| 21862/22421 [09:00<04:54,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛부터 평가하면 노맛. 물에 기름만 떠다니는 맛 김치도 노맛 위생상태 바라고 가는 곳은 아니지만 벌레 날라다니고 테이블에 비치되어있는 가위랑 집게에는 고추가루가 말라붙어있었음. 다시는 안감, 번역:

 98%|█████████▊| 21863/22421 [09:00<04:43,  1.97it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저녁에 남자들끼리소주한잔 부딫히기 좋은밥집.냄새가 조금 날 수 있으나맛집이라 생각하면 ok, 번역:

 98%|█████████▊| 21864/22421 [09:01<04:57,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 오래된 집임에는 분명하다. 주변에 사는 분의 소개로 몇 번 가보았다.  하지만 실망스러운 점은 오랜 역사에도 불구하고 설렁탕의 #누린내#가 심하다. 과연 이 식당은 #누린내#도 잡지 못하는 설렁탕으로 오늘까지 내려온 듯 하다. 반면 제공되는 김치는 맛있다.  김치때문에 갈 수는 있어도 설렁탕때문에 가고 싶지는 않다., 번역:

 98%|█████████▊| 21865/22421 [09:01<04:36,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 대체 여기가 왜 맛집인지.....도저히 이해할수가 없음. 내 인생 최악의 설렁탕., 번역:

 98%|█████████▊| 21866/22421 [09:02<04:13,  2.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 조미료없는 순수한 맛. 김치. 깍두기 잘 익혀져서 설렁탕 맛을 보완해요., 번역:

 98%|█████████▊| 21867/22421 [09:02<04:20,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 누린내가 나서 불쾌 하다는 평이 많지만, 여긴 그 맛에 먹는 곳임, 번역:

 98%|█████████▊| 21868/22421 [09:03<04:40,  1.97it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 그저 그런 설렁탕집. 역사, 전통 이런게 느껴진다고? 글쎄요..., 번역:

 98%|█████████▊| 21869/22421 [09:04<04:58,  1.85it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔한 국물맛 일반 프렌차이즈 음식점이랑 차이점을 느낀 곳, 번역:

 98%|█████████▊| 21870/22421 [09:04<04:51,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 보통은 줄서서 기다려야 하지만 맛은 좋아요 깔끔하지만 고소한 국물이 끝내줘요~, 번역:

 98%|█████████▊| 21871/22421 [09:05<05:05,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 도가니탕 깔끔한맛 맛있다탕안에 도가니든 건더기 넘 적다, 번역:

 98%|█████████▊| 21872/22421 [09:05<05:23,  1.70it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기대치에 못 미칩니다., 번역:

 98%|█████████▊| 21876/22421 [09:06<02:56,  3.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 외곽에 있어서 찾아가기 힘들지만 조용한 카페 입니다! 다만 주차공간이 협소해서 주차를 못할경우 난감합니다!공간도 크고 2층으로 되어있어서 여유있는 시간 보내기 좋아요, 번역:

 98%|█████████▊| 21877/22421 [09:07<03:34,  2.53it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주차도되고 카공족 많아요 조용한편이에요기프티콘 쓰러 갔어요~ 스타벅스 원정중 ㅋ, 번역:

 98%|█████████▊| 21878/22421 [09:07<03:59,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 프랜차이즈의 장점은 무난한 분위기 속에서 무난한 가격의 무난한 맛을 지닌 무난한 음식을 즐길 수 있다는 것이지요.조금 일찍 도착해서 아침을 먹어야 할 때, 점심 후에 가볍게 한 잔 커피가 땡길 때, 가끔 당분이 필요할 때, 고민없이 바로 들어갈 수 있는 그 곳 스타벅스^^, 번역:

 98%|█████████▊| 21879/22421 [09:08<04:13,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 별다방 커피가 맛이 나요 그렇나 가격이 좀 높다는게 단점인거 같습니다, 번역:

 98%|█████████▊| 21880/22421 [09:08<04:07,  2.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 싸고 맛은 평범. 식전 스프와 식후 요구르트가 나온다. 생맥시키면 생고구마 새우깡 김 달달한땅콩이 나와서 좋다, 번역:

 98%|█████████▊| 21881/22421 [09:09<04:14,  2.12it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: '나를 찌운건 팔할이 온달이었다.'고등학생때 야자 째고 쟁반노래방 가기 전에 거의 매일 먹었는데 아직도 질리지 않아 기회가 될 때마다 먹으러 갑니다. 값이 많이 올랐지만 물가 생각하면 아직도 저렴한 편입니다.얇게 펴서 밑간 한 고기에 빈티지한 튀김옷을 입혀 빠삭하게 튀겨내고 그 위에 달고 짭짤한 브라운 소스를 흥건히 부어내는 아주 기본적인 경양식 돈까스입니다. 고대법대후문에 유명한 오박사네 돈까스와 같은 형태지만 좀 다른 느낌으로 소스의 존재감이 훨씬 강하고 자극적입니다. 그래서 잘게 썰어 밥, 야채와 함께 먹으면 정말 맛있습니다. 돈까스 곱빼기에 밥, 야채 추가해서 실컷 먹고나면 세상 행복한 돼지가 될 수 있습니다.별 기대 없이 시켜본 전기구이 통닭도 참 맛있었습니다. 기름을 잘 빼서 느끼하지 않아 돈까스에 통닭을 곁들여 먹는데도 별로 부담스럽지 않은 신기한 경험을 할 수 있습니다., 번역:

 98%|█████████▊| 21882/22421 [09:09<04:04,  2.20it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 초심을 잃었다. 10년 전에 성신에서 돈까스를 찾으면 누구나 온달로 알아들을 정도의 맛, 저렴한 가격, 인지도가 있었으나 남은 것은 인지도 뿐. 맛도 떨어지고 가격도 너무 올랐다. 성신에서 돈까스가 먹고 싶다면 다른 곳을 찾아보자., 번역:

 98%|█████████▊| 21883/22421 [09:10<04:16,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 5,500원의 가격으로 푸짐한 돈까스를 즐길 수 있었습니다., 번역:

 98%|█████████▊| 21884/22421 [09:10<03:56,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 식사로 하기보단 맥주 한잔먹고 싶을때 돈까스 안주로 맥주 마시면 최고임. 돈까스만 먹으면 그닥 맛있진 않음 무조껀 맥주, 번역:

 98%|█████████▊| 21887/22421 [09:11<02:32,  3.50it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 까만봉다리에 신발을 담고 입장하라는 요상한 식당이용방식에 입장부터 당황.포장손님도 보통많은게아닌지포장용 쭈꾸미를 분배하시느라 분주합니다.메뉴는단일메뉴고시키면 2인분에 새송이한조각들어간쭈꾸미가 나옵니다.옆면 쇠뚜껑열어서 마늘 잔뜩올리면 맛있는쭈꾸미 익힐준비..양념은 후추매운맛이 듬~~뿍 나는게흡사 대구 윤옥련할매떡볶이같습니다.깻잎에싸먹을때 천사채올리면 중화가 좀 되고..같이나온 찌개가 참맛있어요 :)볶음밥볶아먹을때쯤 되니까 쭈꾸미가 질겨졌어용, 뜨거우니까 호호 불어드시되 후다닥 드시고 밥볶아드세요오, 번역:

 98%|█████████▊| 21888/22421 [09:11<02:48,  3.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛녀석에서 방송을 본 이후부터 자주찾는 가게.이때까지만해도 1만원이였는데 1만2천원이됐음.가게는 본관이 좌식테이블이라 비닐봉투에 직접신발을 챙겨야하고 바로옆 별관은 입식테이블이라 선태가능함.비록 수입산쭈꾸미이지만 크기와 양은 여느 식당보다 많이 줌 1인분에 350g.3인분이상 주문하면 쭈꾸미 양이 많아철판위에 두세번 나누어 구우게되는데 처음엔 매콤했다가 밥볶을때는 양념장이 진해져서 엄청 매워짐.이곳은 가게 손님도 많지만 포장도 많이해가는데 1인분, 2인분 양으로 각개포장을 검정비닐에 담아줌.1인분 포장을해서 캠핑갈때 대패삼겹살에 숙주나물을 넣고 구워먹으면 2명이서 충분히배불리 먹을수있도록 양이 많음.주차장은 따로 없고 주변 빌딩에 유로주차가능한데 현재 기본30분 천원에 10분당 천원 추가됨.참고로 검색하면 동일상호가 많이나오는데 사장할머님말씀으로는 체인점을 내신적없다고 함., 번역:

 98%|█████████▊| 21889/22421 [09:12<03:24,  2.60it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 지금까지 가 본 쭈꾸미 집 중에 젤 맛있어요!!! 그리고 쭈꾸미 양도 많고 실해요~ 보통 쭈꾸미집 가면 쭈꾸미외에 부가적인 야채같은게 훨 많기도 하고 쭈꾸미가 짜잘하기도 하고 그런데 여긴 양이 압도적이네요양념이 정말 맛있어서 매우면서도 넘 좋습니다마지막 볶음밥은 화룡점정~본관으로 갔더니 좌식이고 신발을 개인 닐봉투에 챙겨야해서 좀 불편했어요 바로 옆에 별관이 있는지 몰랐네요 ㅎㅎㅎ 포장해서 집에 가져와서 먹어도 좋을거같아요, 번역:

 98%|█████████▊| 21890/22421 [09:12<03:32,  2.50it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 제 쭈꾸미 최애 맛집이에요!한두달에 한번씩은 꼭 가요쭈꾸미가 정말 실하고 양도 많고 매운데 너무너무 맛있어요!!, 번역:

 98%|█████████▊| 21891/22421 [09:13<03:48,  2.32it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있어용!!단짠 한식을 좋아한다고 햇더니 아는 언니가 추천해준 곳입니당쭈꾸미집이 이렇게 크고 바로 옆에 이호점이 붙어있는 게 신기했어용 장사가 정말 잘되는 것 같아요들어가자마자 인원을 보고 자동으로 주문해주십니당음식이 엄청 빨리 나옵니다한 이분만에 음식을 받은 것 같아요치즈같은게 없어서 쭈꾸미 본연의 맛을 느낄 수 있습니당 정말 단짠인데 너무 맛있어요 천사채랑 같이 싸먹으면 꼬돌하면서도 매콤느끼가 함께 있어서 맛나요!!마지막에는 살짝 짯지만 볶음밥을 해서 먹으니 딱 맞았어요좀 미리 밥을 볶아서 같이 먹는 것을 추천합니다식사시간과 겹치면 대기가 많은 것 같더라구요애매할때 가서 드신다면 조용하게 맛있게 드실 수 있습니당, 번역:

 98%|█████████▊| 21892/22421 [09:13<03:37,  2.43it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저녁 웨이팅 있음/사람 많은 시간에 일행이 다 안오면 아무리 일찍와도 못 들어감/맵고 맛있음, 번역:

 98%|█████████▊| 21893/22421 [09:13<03:38,  2.42it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 개 맛집이였는데 이제 할머니가 안계신다... 왜 그럴까... 맛도 바뀐기분이다... 일년만에 왔는데 참말루...실맹쓰..., 번역:

 98%|█████████▊| 21894/22421 [09:14<04:14,  2.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 탱글탱글한 쭈꾸미를 매콤하게 먹을 수 잇어요. 다른 메뉴는 없으니 매운걸 잘 드셔야 해요, 번역:

 98%|█████████▊| 21895/22421 [09:14<03:58,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있는 매운 음식임. 볶음밥도 맛있고 깻잎과 먹는 맛도 일품, 번역:

 98%|█████████▊| 21896/22421 [09:15<04:03,  2.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 오후 7시만 넘어가도 앞다리는 매진되는 경우가 허다함. 그러나 뒷다리도 부드럽게 맛있고, 사장님이나 직원 알바 모두 친절하고 기합이 들어가있어보여서 좋다. 소주와 함께라면 거의 끝판왕, 번역:

 98%|█████████▊| 21897/22421 [09:16<04:27,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있습니다., 번역:

 98%|█████████▊| 21898/22421 [09:16<04:42,  1.85it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이벤트 기간으로 저렴한 가격에 육개장과 칼국수를 한번에 해결할 수 있었습니다., 번역:

 98%|█████████▊| 21899/22421 [09:17<04:19,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 전날 술 때려먹고 아침에 간단히 해장하러 들르기 좋은 곳24시간 영업하는지라 아침식사 장소로 적합주차장은 따로 없으므로 인근에 눈치껏 야비하게 대던가 인근 호텔들의 지하주차장을 유료로 이용할 것육개장 또는 육칼 모두 기본은 함, 번역:

 98%|█████████▊| 21900/22421 [09:17<04:31,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 육개장은 집마다 레시피가 달라서 입맛에 맞는 집 찾기가 어려웠는데, 국이 진하고 내용도 푸짐해 항상 맛있게 먹음. 집 근처 놀러 오는 지인들도 한번씩 데려가면 다들 맛있다며 좋아함., 번역:

 98%|█████████▊| 21901/22421 [09:18<04:44,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛 평타 이상의 메뉴들로 실패는 없는 곳. 다만 가격대가 조금 있어 마냥 여러 메뉴를 막 시키긴 애매할 듯하다.(그래도 타임스퀘어 내에서는 일반적인 가격대.) 세트 메뉴나 음료 이벤트가 종종 있어 합리적으로 느껴지긴 한다.우육탕면은 뭔가 2퍼센트 살짝 부족한 맛, 계란볶음밥은 삼삼한 맛. 근데 의외로  그린빈소고기볶음이 진짜 맛있어서 계속 들어간다. 술안주로도 나쁘지 않을 듯한 맛이다. 세트로 시키면 양이 꽤 되기 때문에 2인이서는 많을 수도 있다. 다먹어도 기름진 니글니글한 톤은 아님! 초콜릿샤오룽바오는...음 초코호빵 맛인데 궁금하면 먹어봐도 괜찮겠지만 추천은 안함, 번역:

 98%|█████████▊| 21902/22421 [09:18<04:22,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 대만여행 다녀온 뒤, 30프로 할인권이 있고 대만에서 먹었던게 그리워 가게 된 딘타이펑. 굴소스청경채볶음이 가장 먼저 맛봤는데 밥이 필요한 짭짤함이 있었다. 대만이랑 다른 점은 샤오롱바오가 대만에 비해 작다는것.. 맛은 한국인에게 맞춰진 듯 대만보단 더 맛있었고, 우육면도 시먼쪽에서 먹어본 우육면 그대로였다.시먼에 딘타이펑 우육면은 아니고.. 시먼에 있는 우육면 맛집에서 먹은 맛!대만의 음식을 달래기 좋았다.새우볶음밥은 양이 좀 적고..ㅠ 전체적으로 짜긴하지만 못먹을 정도는 아니었다.대만 또 가고 싶어라~~, 번역:

 98%|█████████▊| 21903/22421 [09:19<04:16,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 탄탄면이 없어진게 아쉽지만 그래도 한국에서 샤오롱바오랑 샤오마이 먹고 싶으면 항상 찾게 되는 딘타이펑! 대만이나 중국처럼 가격좀.. 저렴하게 맞춰주면 더욱 좋을것 같다, 번역:

 98%|█████████▊| 21904/22421 [09:19<04:47,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 대만에서 먹었던 샤오롱바오가 생각나서 다녀온 타임스퀘어점 인타이펑. 맛은 평타!!, 번역:

 98%|█████████▊| 21905/22421 [09:20<04:42,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 대만에서 먹었던 샤오롱바오가 그리워서 친구들과 방문 샤오롱바오나 계란볶음밥이 대만에 딘타이펑에 비해서 좀 작은 감이 없지 않아 있지만 맛은 그래도 좋았습니다 우육탕은 대만에서보다 한국 패치가 되어서 그런지 맛있더라고요 ㅎㅎㅎ 또 갈 만한 식당인 거 같습니다, 번역:

 98%|█████████▊| 21906/22421 [09:20<04:32,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주중에가지않고 주말에가면 대기1시간해야함  주중이 조용하고 좋음 맛은 그냥그랬음 김포점이맛있음, 번역:

 98%|█████████▊| 21907/22421 [09:21<04:40,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 우육면은 신맛이 약간 났는데 거슬릴정도는 아니였어요. 샤오롱바오가 제일 맛있었고 새우볶음밥은 예상보다 맛있어서 기분좋게 식사하고 나왔습니당. 주말에 오후 4시반쯤 방문했는데 사람이 없어서 대기안하고 바로 들어갔어요!, 번역:

 98%|█████████▊| 21908/22421 [09:22<04:51,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 특별할 것 없는 식당이지만 깔끔하고 친절해서 편안하게 식사할 수 있어요. 샤오롱바오는 별 네개, 자장면과 XO게살볶음밥은 별 세개입니다., 번역:

 98%|█████████▊| 21909/22421 [09:22<04:44,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 회사 회식으로 잡은 장소인만큼 맛잇고 적당히 고급스러워요, 번역:

 98%|█████████▊| 21910/22421 [09:23<05:01,  1.70it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 처음 먹어본 딘타이펑. 맛없음. 살라면은 엄청 심. 나머지는 먹을만함, 번역:

 98%|█████████▊| 21911/22421 [09:23<04:41,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 식당에 들어가 메뉴를 시키고 기다렸다.메뉴 나올때까지 10~15분정도 걸렸다.사람이 많지도 않았음. 5테이블 정도?음식점에서 늦게 나올수도 있다고 생각함근데 메뉴 나오고 나서도물컵, 앞접시, 물수건, 짜사이, 생강등기본 세팅도 없었음.그냥 어이가 없어서 빨리 갖다달라고 했음.갖다달라는데 불친절하고 마인드 교육이 안되어있는듯.알바하시는분들도 교육이 필요함.샘플러 시켰는데 뭐가 무슨딤섬인지는 알려줘야되는데아무런 설명이 없음. 귀찮으니 알아서 먹으라는건지.원래 그런건지.일하시는분 불러서 설명요청메뉴판 갖다주고 보라함.이때 많이 화났지만 그냥 참았음홍콩에서 먹은 육즙 가득한 딤섬과 차이가 많이남처음 드시는 분들은 청담동 몽중헌을 추천(회사에서 갔었는데 맛은 현지와 비슷, 하지만 가격은 비쌈)여자친구네서 멀리가기 싫어서 가봤는데 딤섬이 무슨 그냥 만두임. 안에 마실 육즙도 없음..감귤주스?잘나간다고 메뉴판에 써놨는데빽다방 레몬에이드보다 맛없음. 비추볶음밥 그냥 동네 중국집 볶음밥.만 사천원?(소스는 또 따로 돈받음 3~4천원돈)돈 내고 먹기 아까움비싼돈내도 짜장면집 볶음밥 먹은기분. 비추매운새우 완탕이건좀 맛이 괜찮았음.많이 맵지는 않고, 적당히 칼칼하니 먹을만 했음하지만 8천원에 먹기엔 아까움(6개 들어있음)우육탕육개장 국물에 면 넣어서 먹는맛딱히 특별한점 모르겠음향신료 맛도 약하고, 대표메뉴인데 너무 신경 안쓴듯계산할때 카운터에 점장도 불친절함, 주말 피크시간(7시)에 사람이 별로 없는 이유를 알겠음그점장에 그 알바임.6만원 정도에 만족할만한 식사 아니였음그정도 값어치를 할만한 음식과 서비스가 아니였음(무엇보다 서비스 엉망, 딤섬 엉망)6만원쓰고 기분이 안좋았음.다른지점은 어떨지 모르겠지만타임스퀘어는 이제 안갈것 같음.별 1점도 아까움.다른분들도 괜히 갔다가 기분 안나빴으면 좋겠음., 번역:

 98%|█████████▊| 21912/22421 [09:24<04:49,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 입장 대기20분음식주문후 20분음식은 노맛.별하나도 아깝네요, 번역:

 98%|█████████▊| 21913/22421 [09:24<04:50,  1.75it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 전 스파돈스라는 세트메뉴 시켰는데요 스파게티, 돈까스가 같이 나오는 혁신적인 메뉴입니다. 우동돈스도 맛있을것같네요. 요즘 입맛이 별로 없어서 막 맛있게 먹진 않았는데 우동돈스 먹으러 재방문할 의사 있습니다. 또 요구르트도 줘요. 약간 어릴때 감성을 느낄수있고좋은것 같습니다., 번역:

 98%|█████████▊| 21914/22421 [09:25<04:48,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 패티돈까쓰 항상 5900원 할인행사 중이라서 가끔먹어요. (포장도 됩니다) 식전스프& 요구르트 서비스가 기분 좋은 곳인 것 같아요., 번역:

 98%|█████████▊| 21915/22421 [09:25<04:29,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 영롱한 치즈돈까스..☆가 나오기전에 스프도 제공됩니다 맛있어요, 번역:

 98%|█████████▊| 21916/22421 [09:26<04:04,  2.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 그냥그럼... 왕돈까스는 진짜 크긴함... 맛은 매우 평범.., 번역:

 98%|█████████▊| 21917/22421 [09:26<04:07,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 안주도 맛있고 맥주도 맛있어요! 재방문해서 다른 메뉴도 먹어보려구요, 번역:

 98%|█████████▊| 21918/22421 [09:27<03:45,  2.23it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 사당역4번출구바로앞 맥주맛집입니다. 현금3만원이상시맥주1잔무료~, 번역:

 98%|█████████▊| 21920/22421 [09:27<02:48,  2.97it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 사이즈는 일반사이즈 고기굽기는 미디움으로 먹었습니다.부르클린웍스는 한입베어물기 어려울정도로 커서 조금씩 잘라먹었습니다.시킨음식은 전체적으로 맛있었고 저는특히 칠리프라이와 코울슬로가 기억에 남네요.맥주와 너무 잘어울리는 맛이어서 밀크셰이크를 시켯지만 머릿속은 맥주생각이 많이 났습니다. ..저는 개인적으로 쉑쉑버거를 더 맛있게 먹었던것 같습니다., 번역:

 98%|█████████▊| 21921/22421 [09:27<02:58,  2.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가로수길 골목에 위치해 삐까번쩍한 미국식 조명이 눈에 확 들어오는 수제버거 전문점. 외관도 미국식 감성으로 꾸며져 있지만 내부 인테리어는 더더욱 미국에 온 듯합니다. 바(bar) 테이블도 있고 공간활용도 상당히 미국식이에요. 4인용 테이블은 몇개 없으니 여러 사람과 갈수록 웨이팅 시간이 길 것 으로 예상됩니다.브루클린 웍스는 기본에 충실한 맛인데, 이게 기본중의 기본이고 가장 베스트 메뉴예요. 패티가 워낙 퀄리티 좋고 안에 내용물도 신선합니다.뉴 멕시코는 겉보기에는 평범해 보이지만 안에 할라피뇨가 들어가 있어서 살짝 매콤해요. 패티 맛 보다 색다른 식감을 원하시는 분들에게 추천합니다.치즈 스커트는 겉만 화려할 줄 알았는데 치즈를 뜯어먹으니 고소하고 맛있네요. 치즈를 좋아하시는 분들은 좋아하실 맛이고, 살짝 치즈에 물릴 수도 있어요.* 저희는 2명이 가서 한 명은 세트, 한 명은 단품으로 시키는 편이었습니다. 세트에서 감자튀김 종류를 선택하시면 됩니다. 개인적으로 쉐이크는 사진 찍기에는 좋아도 맛은 별로였어요. (너무 걸쭉해서 시원한 맛을 원하는 분들에게는 조금 비추해요.) 차라리 다양한 탄산음료 또는 맥주와 함께 드시는 것을 추천합니다.• 식당 바로 앞에 주차공간이 있는데, 발렛주차를 해주십니다. 2시간에 3천원 이었던 걸로 기억하고 있어요.• 식당 내부에 화장실이 있는데 남녀공용 1칸입니다. 좁지만 깨끗한 편이에요., 번역:

 98%|█████████▊| 21922/22421 [09:28<03:12,  2.60it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 수요미식회에 나왔던 수제버거집이에요가로수길 중간 골목쯤에 있고점심시간 웨이팅 20분 정도 했어요 ㅠ수제버거 안짜고 맛있었어요감자튀김도 맛있고 기호에따라 소스 뿌려먹으라고테이블에 있어서 그게 젤 좋았어요, 번역:

 98%|█████████▊| 21923/22421 [09:29<03:45,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: “지금 껏 먹어본 수제버거 중 일등”후기 중 쉑쉑버거를 먹느니 브루클린을 가겠다는 걸 본 적 있다. 이태원에 유명한 수제버거집도 가 보고 다 가봤지만... 이 곳 수제버거는 패티가 남다르다. 압도적인 밀크쉐이크 메뉴에 눈이 돌아갔는데... 사실 쉐이크나 다른 음료는 맛이 그저 그렇다... 하지만 버거만큼은 완전 강추!!!, 번역:

 98%|█████████▊| 21924/22421 [09:29<03:53,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 들어가자마자 풍기는 향긋한고기냄새에 구미가 확당겼고 친절하게 오더를 받아주시고 음식도 짭짤한게 입맛에 아주 딱맞았다 고기가 향이 좋았고 치즈 스커트는 바삭바삭해서 버거의 맛을 더 좋게 해줬다 홀그레인 머스터드 핫소스 등이 셀프서비스로 구비되어 취향에 맞게 먹을수있었다, 번역:

 98%|█████████▊| 21925/22421 [09:30<04:15,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여긴 비싸긴 한데 맛있긴 겁나 맛있다 ㅠㅠ 그래서 계속 가게 됨.. 고기는 미디움까지가 딱 좋다. 예전에 실수로 굽기 얘기 안해서 미디움웰던으로 먹은적 있는데 그땐 진짜 별로였음, 번역:

 98%|█████████▊| 21926/22421 [09:30<03:54,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 나는 그냥 먹을만 한데, 아이들은 버거킹이 더 좋다고 한다.패티가 레어로 덜 익혀서 나오는데 아이들 먹이기 꺼림직스럽네, 번역:

 98%|█████████▊| 21927/22421 [09:31<04:09,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격과 서비스에 비하면 실망스러운 맛입니다. 분위기때문에 손님이 많은 건지... 웨이팅 없이 먹어야 먹을만한 맛이네요, 번역:

 98%|█████████▊| 21928/22421 [09:31<04:25,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 먹은 거: 더치즈버거(7,800원) 프렌치프라이세트(6,000원)맛 좋음.가격 좀비쌈.친절함.청결함.맛있다. 제일 기본 버거라 패티+치즈 뿐인데도 맛있다.수제버거 치고는 보통 가격이지만 자주 먹기에는 비싼 가격, 이라는 점만 아쉽다., 번역:

 98%|█████████▊| 21929/22421 [09:32<04:07,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 수제 햄버거 맛집 이번이 두번째 방문인데 서울에서 제일 맛있는 집 중 하나인 것은 사실이다!, 번역:

 98%|█████████▊| 21930/22421 [09:32<04:21,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 한입 물었을 때 적당히 육즙이 묻어나고 부드러운 식감이 느껴지네요. 기본에 충실한 버거라고 생각.   Over your shoulder 가 매장에 들리고는 있었는데 워낙이 사람도 많고 시끌시끌하고 힙한 분위기여서 음악은 묻혀버린다는.   발레파킹 3000원, 번역:

 98%|█████████▊| 21931/22421 [09:33<04:20,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 짭짤하고 느끼한 거 좋아하시면 좋아하실 거에요. 진짜 미국식 버거라 외국인들이 더 많더라구요! 밀크셰이크에 감튀 찍어먹음 더 맛있답니다!, 번역:

 98%|█████████▊| 21932/22421 [09:33<04:15,  1.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 버거 패티가 맛있네욤 분위기가 완전 힙합니당 식사시간엔 사람이 많아 대기가 길어요, 번역:

 98%|█████████▊| 21933/22421 [09:34<04:11,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 치즈스커트로 유명한 수제버거집. 치즈프라이도 맛있음. 브루클린맥주도 맛남, 번역:

 98%|█████████▊| 21934/22421 [09:34<03:58,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 현지 팝레스토랑 느낌 .  시끌벅적. 고기냄새가  식욕을 돋군다.  24시간이라 더 좋은 맛. 분위기. 젊음  굿, 번역:

 98%|█████████▊| 21935/22421 [09:35<04:28,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식 맛있고 안내해주시는 직원분이 너무너무 친절했어요 ㅋㅋㅋ 들어갈 때부터 기분 좋았습니당😘맛이 강하지 않아서 좋았어요!! 생긴건 되게 짤 줄 알았는데... 패티는 육즙 팡팡 빵은 부드러운 수제버거 맛이고 개인적으로 단맛이 조금 더 들어가면 좋았을 것 같습니당!  그리고 치즈감튀가 정말 맛있어요!!쉐이크와 함께하는게 더 맛있을 것 같아요!!  데이트 인원 기준 세트 하나에 단품하나 하시면 딱 좋은 것 같아요. 가격도 3만원 내외로 그냥저냥 괜찮은 편인데 퀄에비해 조금 비싼느낌이... ㅠㅠ, 번역:

 98%|█████████▊| 21936/22421 [09:35<04:16,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 너무 맛있어서 수제버거 먹으러 가로수길까지 와요! 존맛, 번역:

 98%|█████████▊| 21937/22421 [09:36<04:41,  1.72it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 유명한 버거집이라고 해서 웨이팅 해서 먹어보고 왔어요. 여러가지 소스랑 특이해서 좋았어요. 먹고 왔는데 가격이 너무 비싸서 조금 내린다면 좋을듯해요., 번역:

 98%|█████████▊| 21938/22421 [09:37<04:24,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 유명세를 타선, 미국분위기 내려는지 약간의 불친절을 느낌.맛있지만 전체적으로 짠맛입니다., 번역:

 98%|█████████▊| 21939/22421 [09:37<04:38,  1.73it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음악이 너무시끄러워서 코로들어가는지입으로들어가는지모름 테이블간격너무좁아서 옆테이블이랑 친구느낌으로 먹을수있음 진짜 시끄러워서 대화하기도 힘듦 정신없긴하지만 맛있긴 함 하지만 가게가 너무나도 어수선하고 정신없어서 가게내부에서 먹고갈일은 없을듯.. 다음엔 포장해서 먹고싶어요, 번역:

 98%|█████████▊| 21941/22421 [09:38<03:20,  2.40it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 포장해가서 음식사진은 없지만 내부 인테리어가 정말 마음에 들었고 마멜누텔라 쉐이크 진짜 맛있었어요 당 1000%충전되는 느낌이에요 그리고 음악소리는 조금 크다 거슬리네 정도였어요 그래도 메뉴 추천도 해주시고 음식도 생각보다 빨리나오고 음식도 맛있었어요!, 번역:

 98%|█████████▊| 21942/22421 [09:38<03:27,  2.31it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 치즈스커트 버거 맛있다고 해서 시켰는데 치즈가 너무 짰어요...그 맛으로 먹는거겠죠...? 웨이팅은 생각보다 길더라구요 굳이 줄 기다리며 먹을 정도는 아닌 것 같아요!, 번역:

 98%|█████████▊| 21943/22421 [09:39<03:35,  2.22it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 인생수제버거 대박맛있음 쉐이크도 짱 어니언링은 그저그럼, 번역:

 98%|█████████▊| 21944/22421 [09:39<03:40,  2.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 진짜 맛있음 햄버거 하나만 먹어도 배불러서 소중한 감튀를 남기게 됨ㅠㅠㅠ, 번역:

 98%|█████████▊| 21945/22421 [09:40<03:41,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛도 괜찮고 웨이팅도 회전이 빨라서 십분이면 차례 돌아옴 괜찮은점이 버거를 나이프로 썰때 예쁘게 흘리지않고 잘 짤리게 적당량의 야채 패티 치즈등이 들어있음 맛도좋고 담에는 다른 버거 먹어봐야지, 번역:

 98%|█████████▊| 21946/22421 [09:40<03:59,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 웨이팅으로 인해 많은 기대를 안고 간 곳이었으나 토종한국인인 나의 입맛에는 감자튀김과 구운 치즈가 너무 짰다. 캔콜라하나에2500원이라는 괴랄스런가격도 별로였고, 과도한 나트륨으로 인해 맛을 느끼기 어려웠으나 육즙이 흐르는 패티는 먹을만 했다. 미국맛을 원하시는분에게 추천, 번역:

 98%|█████████▊| 21947/22421 [09:41<04:03,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 엄청 맛있다!!! 까진 아니구 햄버거가 안짜서 좋아여!! 무난한 햄버거 맛인데 안짜서 별4개드립니당 ㅎㅎ, 번역:

 98%|█████████▊| 21948/22421 [09:41<03:51,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 언제나 어느지점가나 맛잇어요 치즈스커트에는 피클없어서 좋아해요~, 번역:

 98%|█████████▊| 21949/22421 [09:42<04:11,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 전반적으로 느끼하지 않고 매우 담백하고 맛있어요 가격이 조금만 더 착하면 좋을 것 같아요, 번역:

 98%|█████████▊| 21950/22421 [09:42<04:20,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 먹자마자 미국본토인줄 알았다. 미국에서 7년생활하고 한국와서 생활하지만 치즈프라이를 이렇게 비슷하게 만드는 곳 처음봤다. 맛 인테리어 분위기 모든게 합이 잘 이뤄져있다. 다시 또 올 예정이다., 번역:

 98%|█████████▊| 21951/22421 [09:43<04:16,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 치즈프라이에서 눈썹? 머리카락? 나옴. 더치즈버거도 먹었는데 맛도 그닥..., 번역:

 98%|█████████▊| 21952/22421 [09:44<04:20,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있다ㅜㅜ쥬시한 패티에 번의 겉바삭 느낌도 좋고 소스도 튀지않고 어우러짐. 다운타우너와 함께 버거의 양대산맥. 쉐이크도 상당해서 버거와 같이 먹으면 극강의 행복과 희열로 우주뿌심#서비스좋다고는안했어요 #버거만보세요, 번역:

 98%|█████████▊| 21953/22421 [09:44<04:18,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 솔직한 맛평가로 햄버거는 맥날이앗고 이집은 쉐이크 맛집이라고 보시면됩니다. 쉐이크 국내지잡쉐이크 비교불가 꿀맛탱입니다. 버거는 대충 아무거나시키고 쉐이크를 신중히 골라서 드시면 만족스러운 맛집으로 기억에남으실거예요, 번역:

 98%|█████████▊| 21954/22421 [09:44<03:54,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 치즈버거 기본을 먹어봤다! 역시 맛있더라. 여기에 칠리치즈후라이!!!, 번역:

 98%|█████████▊| 21955/22421 [09:45<03:43,  2.08it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: Good burger Very gourmet almost and not like fastfood, 번역:

 98%|█████████▊| 21956/22421 [09:45<03:33,  2.18it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 육향이 진한 수제버거가격은 불만이나 맛은 좋다양고기 패티도 괜찮았다, 번역:

 98%|█████████▊| 21957/22421 [09:46<04:02,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 좋음. 미국분위기 엄청남. 유학갔다온분들, 미국 좋아하는분들에게 최고, 번역:

 98%|█████████▊| 21958/22421 [09:46<03:43,  2.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 하, 여기는 제 인생버거집. 너무 만족해요. 짭쪼름하고 고기고기한게 진짜 정통아메리칸!신사에서 가야할 곳을 추천한다면 전 무조건 여기., 번역:

 98%|█████████▊| 21959/22421 [09:47<04:00,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 할라파뇨 좋아하신다면 뉴멕시코 버거 꼭 드셔보세요. 너무 맛있어요, 번역:

 98%|█████████▊| 21960/22421 [09:48<04:12,  1.82it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 미국식 햄버거와 프라이 그리고 밀크쉐이크헤비하지만 그래도 맛있는 맛, 번역:

 98%|█████████▊| 21961/22421 [09:48<04:14,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다른메뉴 먹어보고싶었는데 치즈버거를 시켰어요ㅠ 하지만 존맛탱, 번역:

 98%|█████████▊| 21962/22421 [09:49<04:02,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 치즈스커트버거 비쥬얼 쫌 명품이죠! 오랜만에 갔더니 제 입맛에는 조금 짜게 느껴졌어요. 하지만 여전히 맛있는 수제버거집!  (별로였던 점) 칠리프라이를 시키고 싶었는데 치즈프라이 또는 칠리치즈프라이밖에 없다고... 웨이트리스가 그럼 칠리치즈프라이 시켜서 치즈 빼달라고 하면 된다해서 -_- 왜 나보고 더 비싼걸 시키고 빼라하는지 이해가 좀 안갔어요... 칠리프라이 메뉴 하나 추가 하기가 어려운가봐요..., 번역:

 98%|█████████▊| 21963/22421 [09:49<04:21,  1.75it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 치즈스커트버거는 브루클린 버거 더 조인트의 알파이자 오메가입니다., 번역:

 98%|█████████▊| 21964/22421 [09:50<04:24,  1.73it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 뉴욕에서 수제버거 먹던 기억에 가봤는데, 맛이 전혀 뒤지지 않아요!! 가격대는 조금 있어도 돈 쓸만 합니다!! 쉑쉑보다 훨씬 나아요!!, 번역:

 98%|█████████▊| 21965/22421 [09:50<04:09,  1.82it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 메뉴판에 적힌 햄버거 번호 2,4,8, 번역:

 98%|█████████▊| 21966/22421 [09:51<04:06,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 진짜 미국식 버거를 충실히 재현하고 있으나 굳이 인테리어까지 불편하게 해야 했을까는 의문., 번역:

 98%|█████████▊| 21968/22421 [09:51<03:04,  2.45it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기국수 두 개 시켜서 먹고 왔어요 ㅎㅎ 실내도 시원한 편이고, 국수는 곱배기를, 국밥은 밥을 무료로 제공하니 가성비도 좋고요. 무엇보다 고기국수가 맛있네요 ㅎㅎ, 번역:

 98%|█████████▊| 21969/22421 [09:52<03:18,  2.28it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 사골국물이 적당히 간이 되어있어 따로 간할필요도 없고 추운 겨울에 먹기 딱 좋은 국밥집이에요 고기가 넉넉히 들어가 있어 김치랑 먹으면 딱이고 밥은 원한다면 더 준다고 하더라구요 근데 기본으로 주는 밥도 많아서 남겼습니다., 번역:

 98%|█████████▊| 21970/22421 [09:53<03:43,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 제주도에서 먹었던 고기국수와 똑같은 맛입니다. 대단한 맛은 아니지만 7000원이고 고기가 적지 않게 들어있어서 가격 대비 만족합니다., 번역:

 98%|█████████▊| 21971/22421 [09:53<03:40,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 제주도에서 먹었던 고기국수가 생각나서 방문했던 곳입니다. 제주도에서 먹었던 고기국수의 깊은 맛은 나지 않지만, 국물이 깔끔한 편이었고, 비빔국수의 비빔장 맛도 전체적으로 무난했습니다. 그리고 이 집의 장점은 가성비 같습니다. 양도 충분히 많고, 면추가가 무료로 가능하며, 가격도 싼 편에 속합니다., 번역:

 98%|█████████▊| 21972/22421 [09:54<03:41,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 국물이 진한 제주 고기국수 집이에요.개인적으로 고기국수는 평범했는데 동행한 여자친구는 고기국밥이 맛있다고 하더라구요. 다음번엔 고기국밥을 먹어볼 생각입니다., 번역:

 98%|█████████▊| 21973/22421 [09:54<03:49,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기껍질에서 누린네 남껍질제거해주시면 좋을듯그리고 인간적으로 반찬나온거는 너무 다네요. 그리고  면도 미리 삶아두시는건지 국물과 따로놀고요.고추가루만 4번 후추만 3번 넣었고 겨우 먹었습니다. ( 두번다시는 갈일은 없을듯 하네요), 번역:

 98%|█████████▊| 21974/22421 [09:55<03:51,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기국수 꼭 드세요. 육수가 이제껏 먹었던 고기국수 육수랑은 다르게 깔끔하고 담백합니다. 고소한 맛도 느껴지구요. 고기도 질이 좋은 게 느껴졌고 맛있었어요. 면류는 금방 꺼지는 편인데 정말 맛있게 한그릇 먹었고 적당히 배부른 느낌이 오래 남아있어서 더 기억에 남네요.반찬은 셀프바에서 제공되고 너무 시끌벅적하지 않은 분위기라 마음에 들었어요. 위치가 위치인만큼 주차공간은 없어요., 번역:

 98%|█████████▊| 21975/22421 [09:55<03:44,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기국수 평이 좋아서 고기국수 먹으러 갔다가 반했어요. 아쉽게도 이건 사진이 없네요.다른 메뉴도 궁금해서 고기국밥을 시켰는데 이거 역시 맛있고 고기도 푸짐하게 있어요.고기국수가 진짜 너무 맛있어요. 또먹으러 갈거고 다른사람들에게도 강추하고 싶은 맛입니다., 번역:

 98%|█████████▊| 21976/22421 [09:56<03:41,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기국수가 너무 맛있었어요~~ 수육과 함께 먹었는데 수육이 아니어도 굉장히 배부를 정도의 양이였습니다~!!, 번역:

 98%|█████████▊| 21977/22421 [09:56<03:31,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 서비스도 좋고 양도 많이 주시네요 제주도가 생각나는 맛이에요, 번역:

 98%|█████████▊| 21978/22421 [09:57<03:47,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기국수는 따듯한 국물에 고기가 매우 잘 어울리고 맛있다.비빔국수는 이와 반대로 시원하고 깔끔해서 함께 먹는 걸 추천해요., 번역:

 98%|█████████▊| 21979/22421 [09:57<03:43,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저렴하고 푸짐하게 맛있는것같음.점심때 싸고 배부르게 먹을만한듯., 번역:

 98%|█████████▊| 21981/22421 [09:58<03:01,  2.42it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 🦁5만원대의 가성비 넘치는 호텔뷔페주차 3시간 무료 도장은 찍어주나 발렛비 4천원은 무조건 드는 점 꼭 참고 하시구요 네이버페이에서 이벤트해서 15퍼 할인해서 1인 51000원에 갔어요. 전반적으로 사시미도 그렇고 무난히 맛난 편인데 LA갈비가 좀 질겼어요ㅠ 마카롱이나 베이커리쪽은 맛있네요, 번역:

 98%|█████████▊| 21982/22421 [09:58<03:08,  2.33it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가성비 좋은 호텔 뷔페예요~ 음식 종류 많고 맛있지만 분위기 내러 가기엔 조금 번잡한 느낌이 나요^^;; 하지만 음식 다 맛있고 정말 가성비 좋으니 가볍게 갔다 오기 좋아요~ 주차는 식사 시 3시간 무료, 발렛비 4,000원 발생하오니 참고 바랍니다., 번역:

 98%|█████████▊| 21983/22421 [09:59<03:31,  2.08it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저녁식사가 약 6만원인데 네이버 예약하면 좀 싸게 즐길 수 있고 덤으로 네이버 포인트까지 준다 일단 중가의 부페답게 가격대비 적정수준의 다양한 음식이 준비 되어 있다. 1인당 반쪽씩 주는 랍스터도 맛이 좋은 편이나 역시나 매우 외소한 녀석이다. ㅎㅎ매우 많은 다양한 음식이 준비 되어 있는데 그 많은 종류를 준비 한것 치곤 나름 잘 준비한 것으로 느껴지는데 대체적으로 어쩔 수 없겠지만 육류는 살짝 잡내가 난다. 즉 냉동육을 사용하는것 같다. 가격 대비 모든것을 준비하는 법이니 이해해줘야 할듯 하다.커피맛과 향은 비교적 훌륭하다. 게다가 준비된 게익과 마카롱도 훌륭하다. 전반적으로 돈 아깝단 생각은 안드는 정도..., 번역:

 98%|█████████▊| 21984/22421 [09:59<03:38,  2.00it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 리버사이드 호텔은 무척 재밌는 곳입니다. 80년대에는 성인 나이트 및 유흥 시설로 발길이 끊이지 않는 곳이었고 90년대에도 물나이트로 이름을 날렸습니다. 2000년 들어서야 카바레 등이 사라지고 가성비로 유명한 따뚱이 들어서는 등 대대적인 리노베이션을 마치고 여지껏 그 인기를 이어가고 있습니다. 어찌보면 시류의 변화를 잘 따라가는 것 같습니다.  결혼식, 돌잔치 등이 많은데 강남 중심부라는 상징적 의미에 가성비 나쁘지 않다는 평 때문에 주말 주차는 매우 혼잡스럽습니다. 음식은 3성급 호텔 치고는 괜찮은 편이고 가짓수도 많습니다. 기대하지 않고 저렴한 가격에 여러가지 음식을 맛보러 간다고 생각하시면 될듯 합니다. 가족 연회가 많고 화요등의 주류를 판매하므로 매우 시끌벅적한 편입니다. 일하시는 분 중에 서빙 매니저로 보이시는 분이 세심하게 배려를 잘해주셔서 자칫 기분이 별로였을 법한 식사의 마무리를 괜찮게 할 수 있었습니다., 번역:

 98%|█████████▊| 21985/22421 [10:00<03:21,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: -가성비 좋은 런치가 있는 호텔뷔페-고기류와 디저트류가 잘 되있는 곳입니다. 10월한달간 30% 할인이 되어 3만원대에 저렴하게 이용할 수 있는 런치를 추천합니다., 번역:

 98%|█████████▊| 21986/22421 [10:00<03:42,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 신사역 리버사이드호텔 회사 송년회로 갔는데 동남아 시장통 같아요먹고싶은 음식은 거의 포기하고 보이는대로 그냥 먹어야 하는 수준 ㅠㅠ오는 예약 다 막지 않은 느낌음식은 보통입니다12월 연말만 피해서 가면 그냥 가성비 좋게 먹을 수 있을거 같아요, 번역:

 98%|█████████▊| 21987/22421 [10:01<03:39,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식은 항상 느끼지만 왠만한 호텔 뷔페 비교했을 때 가격대비 괜찮다고 생각합니다. 주말 저녁 와인2종과 맥주 무제한이니 참고하세요^^, 번역:

 98%|█████████▊| 21988/22421 [10:01<03:43,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 시끄럽고 시끄럽고 시끄러워요시장통,,,음식은 무난┗|｀O´|┛, 번역:

 98%|█████████▊| 21989/22421 [10:02<03:44,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 사람이 너무 많아서 음식뜨기 힘들어요 중간에 끼어들 수 없어서 한줄기차 해야함.. 맛은 괜찮아요 디너 와인 맥주는 무제한입니당, 번역:

 98%|█████████▊| 21990/22421 [10:02<03:39,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식 종류가 정말 많고 다 맛있어요. 가성비 좋아요~ 주차는 발렛주차 해줍니다., 번역:

 98%|█████████▊| 21991/22421 [10:03<03:40,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 메인메뉴뿐 아니라 디저뜨까지 종류가 다양하나 딱히 기억나는 음식은 없었음탄산음료가 없는것도 아쉬움, 번역:

 98%|█████████▊| 21992/22421 [10:04<03:49,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식종류 많습니다. 죽, 스프는 맛있습니다. 근데 중식은 종류많은데 비해 질은 부실합니다., 번역:

 98%|█████████▊| 21993/22421 [10:04<03:41,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다양한 메뉴도 많고 음식도 맛있고 위치도 좋아서 재방문의사 있습니다 ~, 번역:

 98%|█████████▊| 21994/22421 [10:05<03:58,  1.79it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 큰이모 팔순잔치를 리버사이드호텔 뷔페에서 한다고 해서 지난 주말에 가보았어요.회사동료들하고 회식때문에 가본 경험이 있어서 찾아가는데는 어려움이 없었어요.술을 마실 수 있어 지하철 타고 갔는데 3호선 신사역에서도 가까워서 참 좋더라구여.세상에나~~~ 먹을게 얼마나 많고 맛나던지, 전 뷔페가면 평소 못먹어 본 음식을 먹는데따뚱에서 먹어 본 고급 북경오리부터 스페셜코너에 있는 알본디가스살사,  스피니치플렛브레드는제가 먹어 본 음식 중 단연 TOP5 안에 들어갈 정도로 맛있엇어요... ㅎㅎㅎ지금도 또 먹고 싶네요.님들도 리버사이드호텔 뷔페가보시면 스페셜코너에 있는 음식들은 꼭 드셔야만 합니다.강추 강추....음식도 넘 맛있고 직원들도 너무나도 친절해서 모든게 참 좋았어요.차들이 많아서 차빼는데 시간이 걸리는게 아쉽지만 전 그럴줄 알고 지하철을 타고와서..ㅎㅎ큰이모 팔순 때문에 정말 맛있는 저녁을 먹고 기분좋은 주말을 보냈습니다., 번역:

 98%|█████████▊| 21995/22421 [10:05<03:41,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 친구랑 갔는데 신사역에서도 가까워서 편함일단 식당이 깔끔해서 마음에들고음식종류가 다양하고 맛있음.특히 디저트 종류가 다양하고 진짜 맛있음.이번에 친구랑 갔는데 가족행사할때 또갈마음이있음., 번역:

 98%|█████████▊| 21996/22421 [10:06<04:00,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가족들또는 친구들과 부담없는 가격에 세계 각지의 요리들과 다양한 주류를 즐길 수 있는 뷔페싱싱한 해산물과 스테이크 정갈한 한식과 깔끔한 디져트류특급호텔 뷔페에 어울리는 서비스를 경험하게 해 줍니다., 번역:

 98%|█████████▊| 21997/22421 [10:06<03:58,  1.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 모처럼 만에 사촌동생들과 함께 갔는데 음식도 깔끔하고 디저트 코너와 음식들이 다양해서 동생들도 너무 좋아서 어깨가 완전 올라가내요 ~~ 미리 예약을 하고 가니 손님이 많은데도 입장해서 맛있게 잘먹고 왔습니다 더리버사이드 번창하시길 ~~!!, 번역:

 98%|█████████▊| 21998/22421 [10:07<03:52,  1.82it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 모든것이 다 좋습니다.위치도 좋고시설도 좋고음식도 좋습니다.가격도 비싸지도 않고 많은 음식의 종류가 있는데LA갈비, 즉석에서 해주는 파스타싱싱한 회 등도 있네요.한번가보이면 또 가고 싶어지실걸요.^^, 번역:

 98%|█████████▊| 21999/22421 [10:07<03:48,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격대비최고의부페~~ 지난주말가족들과식사자리로가보게되었는데정말만족스러웠어요~~가족모임은물론여러개의크고작은룸들이많아서회사회식이나각종모임을하기에정말좋더라고요, 번역:

 98%|█████████▊| 22000/22421 [10:08<03:42,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가족모임으로더가든키친이용햇습니다.가격도괜찮고음식맛도좋고시설도깨끗하고직원분들도친철하게대해주셔서너무좋앗습니다.위치도신사역근처라서편하게이용햇습니다^^, 번역:

 98%|█████████▊| 22001/22421 [10:08<03:37,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 친구랑 같이갔었는데 가성비 좋고 맛도 좋아서 정말 만족하고왔습니다. 특히 디저트 종류가 많아서 좋았습니다., 번역:

 98%|█████████▊| 22002/22421 [10:09<03:35,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격대비 좋습니다. 유명하다는 수플레는 그냥 그래요 저녁보다는 런치 추천, 번역:

 98%|█████████▊| 22003/22421 [10:09<03:13,  2.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이거 짱입니다 ^^베이징덕, 번역:

 98%|█████████▊| 22004/22421 [10:10<03:34,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격대비 종류도 많고 맛있습니다, 번역:

 98%|█████████▊| 22005/22421 [10:10<03:11,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 티팟에다가 티 내려먹는 카페입니다~~가게 내부는 약간 오래되보이지만 티가 맛있어서 만족합니다 스콘도 맛있어요!, 번역:

 98%|█████████▊| 22006/22421 [10:11<03:06,  2.22it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있긴한데 특별한 맛있음은 아니다홍차 아포카토를 먹었는데 홍차아이스크림에서 홍차맛이 진하게 나진 않았다좀 더 향이 진하면 더 좋았을듯친구가 먹은 그린티도 그냥 무난무난한 그린티?여기에 올라간 아이스크림또한 진한 녹차맛은 아니다가장 클로리스다웠던건 마살라차이티!홍차향이 괜찮았고 맛도 괜춘했다맛은 무난한데 비해 가격은 무난하지않아서 자주올만한 카페는 아니다ㅠ하지만 인기는 정말 많아서 자리가 없어 돌아가는 팀도 꽤 많은 곳, 번역:

 98%|█████████▊| 22007/22421 [10:11<03:16,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 에... 한번으로 족하다... 왜 유명한거죠... 화장실도 너무 좁고 일단 의자와 쿠션 너무 오래되보여 앉아있는 내내 너무 찝찝했다ㅠ 다시는 가고싶지 않아, 번역:

 98%|█████████▊| 22008/22421 [10:11<03:00,  2.29it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주말에가서 웨이팅이 조금 있었지만 카페가 예쁘고 음료,케이크가 맛있어요, 번역:

 98%|█████████▊| 22009/22421 [10:12<03:16,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 내부가 조용하고 아늑함. 소파가 아주 편안해서 좋았음. 다양한 종류의 티가 준비돼 있는데 블랙티보단 허브티류가 더 맛있는 듯. 블랙티는 조금 기름진 맛이 났음. 얼그레이 크레페는 그냥 무난한 맛이었고 하바네라 티는 처음 먹어보는 거였는데 상큼하고 은은하게 달달해서 아주 맛있었음. 가격대 좀 있음., 번역:

 98%|█████████▊| 22010/22421 [10:13<03:35,  1.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 홍차 종류가 그렇게 많진 않지만 시중 프랜차이크 커피전문점보다는 확실히 낫습니다, 번역:

 98%|█████████▊| 22011/22421 [10:13<03:16,  2.08it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 굉장히 고풍스러운 느낌이 예쁘고 이색적인 카페. 통으로 이어져있는 소파 의자. 오래 있기엔 편한 듯. 하지만 카페가 그렇게 크거나 천장이 높지는 않고 사람들이 계속 들어오고 안에서 좌석 간 거리, 카운터와의 거리가 넓은편은 아니므로 이야기소리가 잘 들려 오래있기 편할정도의 분위기는 아님. 데이트 중 들르거나 친구들과 가기 좋을 듯. 차 종류가 많아서 좋았고 식기도 다 예뻐서 좋음. 가격대가 좀 비싼 편이지만 차를 좋아하는 사람이라면 좋아할 것 같음., 번역:

 98%|█████████▊| 22012/22421 [10:14<03:22,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 신촌의 카페중에 가장 특색있다고 생각합니다.네임벨류도 있고 메뉴자체도 퀄리티가 좋습니다.가격은 좀 부담된다고 생각할 수 있겠으나특색있는 장소로써 가볼가치가 있다고 생각됩니다., 번역:

 98%|█████████▊| 22013/22421 [10:14<03:30,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격대 있는편.. 신촌이라 그런듯 그래도 메뉴가 다양하고 자리가 편함, 번역:

 98%|█████████▊| 22014/22421 [10:15<03:14,  2.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 밀크티가 맛있었어요! 조용하고 분위기도 좋아서 재방문 의사 있습니당, 번역:

 98%|█████████▊| 22015/22421 [10:15<03:07,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 앤틱한 분위기가 좋은 카페입니다~ㅎㅎ 정말 오래된 카페에요, 번역:

 98%|█████████▊| 22016/22421 [10:16<03:16,  2.06it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 매장이 분위기 있는 편이고 의자가 편해요. 빙수같은 메뉴도 맛있고 일단 홍차 카페라 좋음. 공부하는 카페는 아니고 친구들끼리 얘기 나누러 혹은 데이트하러 많이들 옴, 번역:

 98%|█████████▊| 22017/22421 [10:16<03:10,  2.12it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 유명한 티룸. 다기가 예쁘고 아름답고 차도 좋지만 마니아가 아니면 잘 안 게 되더라고요., 번역:

 98%|█████████▊| 22018/22421 [10:17<03:22,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격대가 조금 있는 편이지만, 차의 향이나 맛이 괜찮습니다. 그릇도 좋은 거 쓰시고 인테리어도 은은하여 데이트하기 딱입니다., 번역:

 98%|█████████▊| 22019/22421 [10:17<03:05,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 몇년전 자주갔던 티 전문점. 커피도 좋지만 이런 홍차카페가 좀더 여기저기 많이 생겼으면.. 분위기 좋고 화장실 깔끔하고 차에 곁들여 나오는 테게백 쿠키가 참 맛났는데 아직도 주나 모르겠네요.디저트는 안먹어봐서 모르겠고 스콘과 브런치(프렌치토스트)는 맛있다고 친구에게 추천받았는데 담에 갈일있음 먹어봐야지요, 번역:

 98%|█████████▊| 22020/22421 [10:17<03:05,  2.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저녁에 방문했을때 웨이팅이 길어 포기했었는데 오후에 오니 저녁보다 한산 하네요 따뜻한 글뤼바인이 추운 몸을 녹여주었어요. 고즈넉한 한옥의 분위기와 와인은 다음에도 다시방문하기 충분했어요! 추천, 번역:

 98%|█████████▊| 22021/22421 [10:18<03:01,  2.20it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 일단 맥주 맛이 좋음. 기성 맥주에서는 절대 느낄 수 없는 맥주의 맛이 신기하고, 색다름.좁은 골목길 사이로 한옥으로 들어가면 마당과 안채 별채로 나뉘어진 공간 곳곳에 모두 테이블이 깔려있음. 구성이나 배치가 굉장히 좋음. 사람들이 항상 많음에도 막상 자리에 앉으면 빽빽하다는 느낌이 안 듦.안채에는 바 테이블이 있어서 직원들과 교감을 느낄 수도 있음.인테리어는 엔틱한 느낌으로 한옥과 잘 어울리고, 조명이 약간 어두운 느낌이라서 그런가 사람들이 많음에도 테이블마다의 몰입도가 좋음.서울 도심 그것도 대학로 한복판에서 한옥의 정취와 여유를 느낄 수 있는 곳.직원들은 맥주에 대한 이해도가 별로 없고, 알려준 대로 말하는 편. 그래도 능숙하진 않으나 꽤나 친절한 편.1차 보다는 2차에 간단히 입가심 용으로 먹는 걸 추천하고, 여자들끼리나 데이트 용으로 가기에 알맞는 곳.단점은 9시 이전에는 대기가 필수이며, 6~8시 사이는 사람이 왕창왕창 몰림. 두어번 정도 대기자 수 보고 그냥 포기한 적도 있음.가격도 비쌈. 수제 맥주 치고도 비싼 편임. 맥주 네병 먹고 6만 8천원 나옴.안주류 또한 겁나 비쌈. 기본으로 주는 과자도 맥주와 잘 어울리니 차라리 그 돈으로 맥주 한병 더 사먹길...Ps. 골목 초입부에서 대기자들을 볼 수 있으니, 많으면 포기하고 나오면 됨. 들어 간 사람들 잘 안나옴.대부분 웨이팅 포기자들은 골목을 나와 봉구비어로 감., 번역:

 98%|█████████▊| 22022/22421 [10:18<03:05,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 한 여름밤에 운치있어 좋은데 ... 강력한 모기향과 뜨거움이 반겨줍니다. 화장실도 좀 컨디션이 열악합니다. 실내는 그나마 에어컨이 있어 다행입니다. 맥주와 와인리스트 등 주류는 매우 괜찮았으나 안주류가 조금 아쉬워요. 생맥주에 어울리는 안주가 딱히 없어요. 안주류를 보강하고 날이 조금만 더 시원하다면 되게 자주 찾을거 같은 장소입니다., 번역:

 98%|█████████▊| 22023/22421 [10:19<03:03,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 처음 왔을때도 느꼈지만 진심 실내 인테리어는 어마어마하다☺️, 번역:

 98%|█████████▊| 22024/22421 [10:19<03:23,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 갬성이 느껴지는 술집어정쩡한 시간에 가면 줄이 너무 길다. 수제맥주가 맛있다. 플레이트는 기분이 좋아지는 느낌이다. 술.맛.난.다., 번역:

 98%|█████████▊| 22025/22421 [10:20<03:19,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 골목 안 조용히 찾아와서 누리고 싶은 아지트 같은 곳. 커피맛이 좋아서 낮에 카페로 찾아와도 좋지만, 그보다는 저녁에 조용히 맥주와 칵테일을 마시러 오고 싶은 곳이다. 맥주나 와인, 칵테일 라인업이 꽤  다양하고, 치즈 플레이트 등 술에 어울리는 간단한 안주도 준비되어 있다., 번역:

 98%|█████████▊| 22026/22421 [10:21<03:41,  1.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맥주 종류가 많고 맛도 좋습니다. 안주도 맛있고요! 가격이 조금 있는 편이지만 서비스도 친절하시고 무엇보다 가게 분위기가 너무 좋아요. 실내도 좋지만 날 좋으면 마당에서 하늘 보고 마시는게 정말..👍🏼 여자친구가 정말정말 좋아했어요, 번역:

 98%|█████████▊| 22027/22421 [10:21<03:31,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 수제맥주집이라 그런지 맥주도 엄청 맛있고 칵테일도 맛있네요 기본안주도 맛있었습니다, 번역:

 98%|█████████▊| 22028/22421 [10:22<03:36,  1.82it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 웨이팅의 이유를 나는 모르겟습니다. 맥주맛은 좋습니다. 조용하게 즐기고싶을때라면 추천, 번역:

 98%|█████████▊| 22029/22421 [10:22<03:46,  1.73it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분위기가 좋고 가정집에 간 느낌이예요. 야외자리도 예뻤는데 아직 추워서 사용못했습니다, 번역:

 98%|█████████▊| 22030/22421 [10:23<04:00,  1.62it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 정말 고급스럽고 술도 종류가 많아서 외국인 친구 데려가기에 정말 좋았어요. 그렇게 부담스러운 가격은 아니지만 일반적인 맥주집 생각하고 가면 조금 놀랄수도!, 번역:

 98%|█████████▊| 22031/22421 [10:23<03:49,  1.70it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 대낮에 한옥에서 즐기는 맥주~~ 요즘엔 사람이 너무 많다, 번역:

 98%|█████████▊| 22032/22421 [10:24<03:54,  1.66it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 조용히 얘기하며 데이트하기 좋아요. 가격은 좀 비싸지만 분위기 좋은 곳, 번역:

 98%|█████████▊| 22033/22421 [10:24<03:26,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 소박한 분위기와 맥주를 다양하게 먹을 수 있어 행복했습니다. 안주는 추천하지 않으니 간단하면서 가벼운 음식으로 즐기세요., 번역:

 98%|█████████▊| 22035/22421 [10:25<02:22,  2.71it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 굿 분위기., 번역:

 98%|█████████▊| 22036/22421 [10:25<02:23,  2.68it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분위기 좋음, 번역:

 98%|█████████▊| 22040/22421 [10:26<01:22,  4.61it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가성비좋다는 말은 못하겠다 비싼만큼 양이나온다. 돈가스가 상당히 부드럽다 돈가스자체는 정말 괜찮다.비싼걸 감수할 수 있을 정도다. 돈가스가 먹고싶을때 다시 올  것같다 식전스프는 오뚜기스럽다 파스타도 무난4.0/5.0, 번역:

 98%|█████████▊| 22041/22421 [10:26<01:38,  3.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격이 싼편은 아니지만, 그만큼 맛도 양도 보장되는 것 같아요!데이트를 하면서 꽤 자주갔었어요. 2년동안 다녀봤는데 정말 모든 메뉴가 맛있더라구요!♡그치만 가게가 좁아서 조금 불편하긴 합니다., 번역:

 98%|█████████▊| 22042/22421 [10:27<01:53,  3.34it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 친구들과 함께가기 좋은 음식집입니다. 메뉴가 다양하며 맛도있고 분위기도 좋고 부담도 덜됩니다., 번역:

 98%|█████████▊| 22043/22421 [10:27<02:16,  2.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 돈까스에 치즈소스라니. 둘다 넘나 좋아하는 음식이지만 ‘느끼하지 않을까?’라는 고민이 드는 조합. 평소에 느끼한 걸 정말 잘 먹고 좋아하는데 거의 다 먹을 즈음엔 피클을 마구 집어먹음.콰트로치즈파스타는 예상보다 깊지 않고 고구마맛치즈가 있어서 향을 다 잡아먹음.돈까스 좋아하면 가볼만 하지만 치즈가 좋아서 갈 곳은 아님, 번역:

 98%|█████████▊| 22044/22421 [10:28<02:31,  2.50it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 좁은데 사람이 많아서 시끄럽다. 알바생 분들께서 주문을 자주 잊어버리신다.장점은 이쁘고 맛도 괜찮다. 가성비도 좋은편이다. 학생들끼리 데이트하기 좋겠다. 하지만 난 돈을 몇천원 더 주고 조금 더 넓은(최소한 가방은 놓을 수있는) 곳에서 양손 자유롭고 조용하게 식사하고 싶다., 번역:

 98%|█████████▊| 22045/22421 [10:28<02:40,  2.34it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛은 그럭저럭 괜찮은데 양이 좀 적다고 생각함항상 사람들이 많아서 줄서서 먹어야하는게 불편함맛은 진짜 그럭저럭 보통맛인데 왜이리 줄서서 먹는지 잘 모르겠음, 번역:

 98%|█████████▊| 22046/22421 [10:29<02:32,  2.46it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 우선 가게가 번화가에 있지 않고 골목 안쪽에 너무 예쁘게 자리잡고 있어요. 소문만 듣고 먹으러 갔는데 대만족입니다, 번역:

 98%|█████████▊| 22047/22421 [10:29<02:29,  2.51it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분위기가 좋고 음식도 적당히 맛있었어요 데이트코스로 괜찮을것같아요, 번역:

 98%|█████████▊| 22049/22421 [10:29<01:57,  3.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기와지붕에  부엉이가 나무에 앉았어요~돈까스도 두툼해서 대만족~^^ 맛있었습니다., 번역:

 98%|█████████▊| 22050/22421 [10:30<02:08,  2.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔!캐쥬얼하게먹기좋아요, 번역:

 98%|█████████▊| 22056/22421 [10:30<00:58,  6.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭곰탕 시원 깔끔한맛의 극치 가성비 좋고 자꾸 먹고싶을것같은 맛 마늘쫑 깍뚜기 맛도 좋음 식탁에 가득놓인 마늘 찧은것과 양념도 인상적 친절하심 닭찜은 두시부터 다음기회에 ㅉ 드뎌 시그니쳐 닭찜 먹어봄 잡내없고 부드럽고 이보다 더 맛있는 닭찜은없다 ㅋ, 번역:

 98%|█████████▊| 22057/22421 [10:31<01:13,  4.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 알려진 맛집이라 굉장히 사람이 많았고 한 20분정도 웨이팅 후 들어갔습니다사실 맛은 평범했던거 같아요 ~~ 저는 닭껍질 안 좋아하는데 좋아하시는 분은 더 맛있게 드실수 있을듯 합니다, 번역:

 98%|█████████▊| 22058/22421 [10:31<01:36,  3.77it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: * 닭곰탕을 드시려면 점심 일찍 가시는 게 좋을 거 같습니다.닭 관련 요리로 유명한 황평집입니다. 충무로역 인근에 위치하고 있습니다만, 현재 주변이 공사중이라 좀 어수선합니다. 원래는 하나의 가게였던 거 같지만 옆에 있던 가게를 터서 입구가 두 개 입니다. 가서 보니 별채 격인 옆쪽에 있는 점포는 식사시간에 손님이 몰리기 시작하면 그때부터 여는 거 같았습니다. 가게는 안에서 하나로 이어집니다. 정말 옛날식 가게구나 싶은 분위기고, 식자재 보관 등 모든 면에서 위생상태가 별로일 거 같은데, 서빙되어 나오는 음식은 놀라울 정도로 깨끗해 보여서 좋은 의미에서 언밸런스함을 느낄 수 있습니다. 식사메뉴로 많이 나가는 닭곰탕을 시켜보았는데, 서빙되는 상태에서는 심심한 편이지만 같이 나오는 간마늘과 양념장과 소금을 넣으면 맛이 확 살아납니다. 고기도 쫄깃쫄깃하고 노계를 쓴건지 껍질도 두터워서 맛있습니다. 깍뚜기는 직접 담그는 거 같지만 마늘쫑 장아찌는 단 맛이 좀 강해서 마치 기성품 같았으며 부추무침은 양념이 강하지 않고 맛이 심심한 편입니다. 셋 다 맛있습니다. 종업원 분들은 손님을 살갑게 맞아주는 편이지만 식사시간에는 테이블 회전수를 올리기 위해 합석이나 밀어내기도 일어나는 편이니 감안하시는 편이 좋겠습니다. 특히 술손님이 들기 시작하는 저녁에 닭곰탕을 드시려다가 자칫하면 유쾌하지 못한 경험을 하시게 될 수 있습니다.가게 자체 주차장은 없으며, 주변에 유료주차장이 있습니다., 번역:

 98%|█████████▊| 22059/22421 [10:32<01:57,  3.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭무침은 소주 안주로 짱이다닭곰탕 국물은 기본으로 나와서 추가로 시키지 않아도 되지만 마무리로 하나 시켜서 나눠먹어도 좋다, 번역:

 98%|█████████▊| 22060/22421 [10:32<02:11,  2.75it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭곰탕은 최고! 닭무침은 독특해요, 쫀뜩하면서 설탕이 깔깔하고 매콤합니다. 노포의 분위기를 즐길겸 좋아요, 번역:

 98%|█████████▊| 22061/22421 [10:33<02:18,  2.60it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 심심한듯 담백하고 찔긴듯 쫄깃한 오래씹을수록 달고기의 단맛이 느껴지는 맛있는집, 번역:

 98%|█████████▊| 22062/22421 [10:33<02:22,  2.53it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 6시 칼퇴하고 식당 도착했더니 6시 30분.. 빨리 도착했다고 생각했는데 자리가 꽉차 있어서 웨이팅했다.5명이서 갔는데 2~4명 자리는 빨리빨리 나는데 5명은 자리가 잘 안나니 가실 분들은 참고요..이곳은 소주가들에게는 성지다..국물도 달라는데로 주고 전골은 사리나 칼국수를 넣어서 계속 먹을 수 있다.같이 곁들어 먹는 부추와 마늘쫑도 넘나리 맛있다아쉬운점은,오래된 맛집의 고질적인 부분인데(아닌 곳도 있지만)직원분들께서 해달라는건 다해주시는데 별로 친절하진 않다., 번역:

 98%|█████████▊| 22063/22421 [10:34<02:30,  2.38it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음... 맛은 있었지만! 닭무침이 특히! 겨자맛이 정말 좋았지만 전체적인 위생이 안좋았고( 다른테이블에서 먹고 남은 물 주기, 반찬에서 머리카락) 저녁에 가면 술 드시는 분들이 많아서 시끄럽습니다.내가 진심으러 닭무침 너무 좋아해서 꼭 먹어보고싶다! 하시는 분은 추천~~, 번역:

 98%|█████████▊| 22064/22421 [10:34<02:25,  2.45it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭곰탕! 특으로 시키면 더운날 몸보신하기 좋을듯. 저녁에 와서 닭무침 먹어보고싶어요. 위치는 쏘쏘 세운상가 뜯느라 주변이 황폐함, 번역:

 98%|█████████▊| 22065/22421 [10:35<02:38,  2.25it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭찜도 좋지만 닭무침에 못미친다. 서비스로 주는 닭곰탕 국물도 좋다! 술술술 들어간다, 번역:

 98%|█████████▊| 22066/22421 [10:35<02:43,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭찜이 먹고 싶어서 오래 전부터 찜해놓았는데 방문해 보았습니다. 15000 원 닭찜을 주문하면 수북하게 나옵니다. 착한가격이고요. 술한잔 하기 좋은 안주이지요. 닭이 좀 질기다고 느낄수 있지만 먹을 만 합니다. 닭곰탕 국물도 좋아하는 스타일이었어요. 다음에는 식사로 닭곰탕을 먹어보고 싶네요. 어둠이 내린 을지로 뒷골목은 으슥하지만 몇몇 노포들은 어르신과 직장인들로 북적이고 있네요., 번역:

 98%|█████████▊| 22067/22421 [10:36<03:09,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭무침 먹으러 갔다가 닭찜시켰어요! 노계를 사용한다는데 쫄깃쫄깃 식감이 좋았어요. 찜시키면 탕도 주시는데 리필도 되고 맛있어요!, 번역:

 98%|█████████▊| 22068/22421 [10:36<03:20,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있고 친절하다.닭찜에 껍질이 특유의 향긋한 나무향과 쫄깃한 식감이 좋았고,닭무침은 미친 술안주였다., 번역:

 98%|█████████▊| 22069/22421 [10:37<03:21,  1.74it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 닭무침 맛있습니다. 4명이서 닭전골 대자 국수사리2개 닭무침 1개, 번역:

 98%|█████████▊| 22070/22421 [10:38<03:07,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 진정한 팔천원의 행복. 이 가격에 이 퀄리티는 불가능하다. 김치 맛도 개쩜., 번역:

 98%|█████████▊| 22071/22421 [10:38<03:25,  1.70it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 국물에 잡다한거넣지않고 기본에 충실한 맛이 좋아 자주 가는집.마늘과 다대기를 듬뿍넣고 한그릇 먹으면... 쩝~...일대 닭곰탕중 최고 괜찮다고 본다., 번역:

 98%|█████████▊| 22072/22421 [10:39<03:15,  1.79it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 자리가 있지만 2인은 앉을수 없다며 못앉게함.모든 테이블이 2명씩 앉아있던 상황이지만 못앉고 기다리라고만 함.다른 손님 나가야 자리 내준다고하며 빈자리는 계속 비워둠.반말 응대를 포함해서 매우 불친절.재방문의사 전혀 생기지 않음, 번역:

 98%|█████████▊| 22073/22421 [10:39<03:13,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 리뉴얼 후 첫 방문20년 고기맛 변치않음!예쁜 인테리어 깔끔해짐!최애고기집 변치않을 듯!고기가 더 맛있어진 듯 해용^^#신촌고기창고 #고기창고 #신촌맛집 #신촌삼겹살 #인생삼겹 #신촌데이트  #신촌술집 #신촌힙플 #신촌힙합 #신촌 #신촌카페 #신촌술집 #신촌역맛집 #신촌맛집추천 #신촌역 #신촌세브란스병원 #신촌회식 #신촌핫플 #신촌회식장소 #신촌, 번역:

 98%|█████████▊| 22074/22421 [10:40<03:06,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 외부에서 느낀 디자인요소가 매장안에서도 느낄수있었다. 카페같은 분위기 아주 좋아요. 명품삼겹을 먹었는데, 육즙이 살아 있어요 이렇게 변화된  모습에 박수를 보냅니다., 번역:

 98%|█████████▊| 22075/22421 [10:40<03:02,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 삼겹살 냉면 된장찌개 볶음밥 먹음.고기 & 된장찌개 맛있음.볶음밥은 질은 밥으로 해주는데 고기기름에 볶아주지는 않는 듯. 냉면은 그냥 고깃집 냉면., 번역:

 98%|█████████▊| 22077/22421 [10:41<02:29,  2.31it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔하고 맛있어요. 구워주셔서 편한데 꼼꼼하게 보시진 않아서 조금 타는 경우 있으니 봐서 적당히 뒤집으시길.., 번역:

 98%|█████████▊| 22079/22421 [10:41<01:58,  2.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 서비스 때문에 매우 불쾌히 나왔습니다. 연기가 너무너무 심해서 어쩔 수 없이 나오는데 싸가지 없다며 욕하네요., 번역:

 98%|█████████▊| 22080/22421 [10:42<02:17,  2.48it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 신촌지역 대학생이 싼 맛에 가는 고깃집임그 이상 이하도 아님시설도 그리 좋지 않음, 번역:

 98%|█████████▊| 22081/22421 [10:42<02:29,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: -가성비-친구들과 한잔 기울이는 고기집(허름한느낌)-환풍시설이필요(환기문제), 번역:

 99%|█████████▊| 22086/22421 [10:43<01:12,  4.61it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 초마는 뭐 믿고먹기에 딱 좋은 것 같습니다.적당한 불맛에 적당한 가격에 그냥 괜찮네요.불맛이 쫌 따로놀긴하는데 국물 깔끔하고 좋습니다.먹을거 없을때 먹기 좋은 것 같습니다, 번역:

 99%|█████████▊| 22087/22421 [10:43<01:25,  3.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 명성에 못 미치는 느낌. 짬뽕에서 불맛이 나긴 하는데 그렇다고 인상적인 맛은 아니다. 특히 백짬뽕은 밍밍할 정도- 완전 비추다. 탕수육도 바삭하니 먹을만은 했으나 맛있는 탕수육은 아니다. 굳이 찾아올 정도는 아닌., 번역:

 99%|█████████▊| 22088/22421 [10:44<01:36,  3.45it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 불 맛 나는 짬뽕입니다~ 엄청 맛있지는 않지만 짬뽕에서 깔끔하고 정갈한 느낌이 들었어요(제 입맛에는 빨간 짬뽕보다 하얀 짬뽕이 더 담백하고 얼큰한 점에서 마음에 들었습니다), 번역:

 99%|█████████▊| 22089/22421 [10:44<01:44,  3.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 큰 기대를 하고 갔다. 짬뽕집은 그간 이곳저곳 돌아다녀본 편이고, 초마의 유명세는 익히 알고 있었으니 말이다. 그런데 그 기대는 실망으로 되돌아왔다. 불맛이 나긴 하지만 그 뿐이라 해도 과언이 아니었다.칼칼한 느낌이 떨어지는 것을 넘어서 느끼했다. 심지어 같이 간 친구는 거북하다고 할 수준이었다.신기할 정도로 매운맛이 전혀 없다. 어떻게 그 새빨간 국물에서 매운맛이 전혀 없을 수가 있는지 궁금할 정도였다. 난 매운맛을 좋아하는 편이 아닌데도 매운맛이 그리워졌다. 과장이 아니라 집에서 끓인 라면이 더 매콤할 것이다.그 동안 초마를 먹어보려고 언제갈까 고민하던 나날이 무색해졌다. 먹으면서 여러 생각이 들었다. 옛날보다 맛이 많이 떨어졌다는 소문은 들었지만 이 정도였나? 분점을 내서 이런걸까? 혹시 금요일 오후 2시라는 애매한 시간에 와서 그런게 아닐까? 과연 맛집이란 무엇일까?분명 동네 배달 짬뽕보단 나은 맛이다. 하지만 짬뽕 맛집이라 하면 가장 먼저 떠오르는 집 중 하나인 초마의 명성을 크게 져버리는 수준이었다., 번역:

 99%|█████████▊| 22090/22421 [10:45<02:04,  2.67it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 짬뽕맛집인데 짜장도 괜찮고 깔끔합니다. 탕수육도 깨끗하게 튀겨나와서 좋다, 번역:

 99%|█████████▊| 22091/22421 [10:45<02:02,  2.70it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛도 별로 서비스는보통 가격은 별로최악이네욤더운데 에어컨도 안틀어주고 땀 뻘뻘 흘리면서 먹었어요 이 돈주고 먹은 내 뺨을 후려치고싶을뿐, 번역:

 99%|█████████▊| 22092/22421 [10:46<02:05,  2.62it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 더할 나위 없는 짬뽕.칼칼하면서도 기름지고..무엇보다도 딱 떨어지게 깔끔한 맛이 최고., 번역:

 99%|█████████▊| 22093/22421 [10:46<02:10,  2.52it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 짬뽕이 유명한 초마. 짬뽕 외 어떠한 매뉴를 주문해도 평균 이상의 맛과 양을 보장함., 번역:

 99%|█████████▊| 22099/22421 [10:47<01:01,  5.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 원래 칼칼하고 얼큰한 국물을 더 좋아해서 사실 별 큰 기대없이 가 본 멘야산다이메카라구치말고 그냥 라멘으로 시켜봤는데 워... 진짜 맛있었다! 이전에 가봤던 라멘트럭이랑은 비교도 안되게 국물이 진국이다 라멘트럭은 살짝 밍밍?한 느낌이었는데 여긴 진하고 살짝 짭짤한 국물이 아주 굿굿굿 면은 다른 라멘보다 살짝 더 얇은 것 같았고, 생각보다 양이 많다  계란 반 개가 기본으로 나오는 것도 맘에 드는 점 반숙 계란과 챠슈도 괜찮았지만 이것들은 개인적으로 라멘트럭이 더 맛있고, 국물로만 승부를 보면 멘야산다이메가 압승인 것 같다교자만두도 괜찮았는데 라멘에 비해선 특별한 맛은 아니다다른 라멘들도 먹어보고 싶은 곳, 번역:

 99%|█████████▊| 22100/22421 [10:47<01:14,  4.30it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 일본에서 진짜 맛있는 라멘 먹고 오면 이 음식점은 정말 평범하다고 생각하게 돼요..국물이 걸쭉해서 좋은데 그냥 무난무난한 맛에 양은 가격에 비해 다소 적은 편입니다환기는 잘 안되서 먹다가 덥고 정말 답답해요테이블 간격도 좁고 화장실도 진짜 작습니다흠.. 다시는 안 갈 것 같네요, 번역:

 99%|█████████▊| 22101/22421 [10:48<01:22,  3.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 칼칼한 매운맛이라하여 카라구치 라멘 시켰는데 그낭 돈코츠라멘 맛인거 같아 물어봐도 카라구치가 맞다고 하네요..주문 오더 실수 인지 다시 여쭤도 맞다고 하고 제 입맛이 변한걸수도.., 번역:

 99%|█████████▊| 22102/22421 [10:48<01:45,  3.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 남자 친구는 카라쿠치 라멘을, 저는 냉라멘(탄탄멘 종류였는데 정확한 이름이 뭐였는지는 기억이 안 나요)을 먹었어요.일단 제 메뉴는 간은 맞았지만 약간 오이냉국 같은 맛? 그런 맛이 났고, 저도 남자 친구도 실망이라고 평가할 정도로... 딱히 맛있지는 않더라구요.카라쿠치 라멘은 너무 짜서 국물에 도저히 손댈 수 없을 정도였어요. 라멘이 원래 짠 음식이기는 하지만 전 좀 심하게 느껴졌네요. 남자 친구는 원래 짜게 먹는 편이라 맛있다고 했어요. 엄청 진하대요. 그래도 짜긴 짜다고 덧붙이긴 했지만요.그리고 개인적으로 메뉴판이 일어로 적혀 있는데, 메뉴 읽는 법은 영어로, 메뉴 설명은 한국어로 적혀져 있어서 좀 불편하다고 느꼈어요. 게다가 좁은 편이라 주방 열기가 그대로 전해져서 엄청 더워요.다시 방문하고 싶진 않아요.-망고 플레이트에도 기록했습니다.-, 번역:

 99%|█████████▊| 22103/22421 [10:49<01:56,  2.74it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 라멘 성애자는 웁니다 여러 라멘집 중에 꼽는 집 중 하나 국물 맛이 정말 특이하고 진한 것이 정말 좋음 꼭 한 번 가보시길, 번역:

 99%|█████████▊| 22104/22421 [10:49<02:08,  2.47it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 현지인들이 만드는 라멘! 진하면서도 느끼하지않은 스프가 깔끔하게 맛남. 메뉴는 많이 없음. 회전빠른편. 가게는 비좁아용, 번역:

 99%|█████████▊| 22105/22421 [10:50<02:25,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마제소바 추천해주셔서 먹었었는데 맛있었어요!!밥도 말하면 조금 주셔서 소스에 마지막에 비벼먹을수 있었네요, 번역:

 99%|█████████▊| 22106/22421 [10:50<02:24,  2.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 홍대에서 나름 유명한 라멘 맛집으로 알고있는데 어째 갈수록 맛이 떨어진다 주문해서 기다리는데 누락해서 음식만 30분 넘게 기다림 우리보다 늦게 온 사람들이 다 먹고 나갈때까지 음식을 못받음 홍대에서 좀 괜찮은 위치에서 라멘 장사하면 솔직히 개나소나 라멘 맛집 되는듯싶다 ^^ 다신 안갈듯, 번역:

 99%|█████████▊| 22107/22421 [10:51<02:42,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 예상 못한 매운맛에 당황계란 없어서 아쉬웠음사이드로 나온 부추김치 맛있었다., 번역:

 99%|█████████▊| 22108/22421 [10:52<02:48,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 양 적음, 번역:

 99%|█████████▊| 22110/22421 [10:52<02:10,  2.37it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 5년째 꾸준히 방문중 해장으로 카라쿠치라멘 겨울에 라멘과교자 여름엔 쯔게멘, 번역:

 99%|█████████▊| 22115/22421 [10:53<01:13,  4.18it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 일본풍 분위기와 아담하고 조용한 느낌이 딱 혼술혼밥하기도 나쁘지 않으며 벽에도 일본풍느낌으로 데코해서 일본맛집 방문한 느낌이 납니다 탄탄멘이랑 연어덮밥시켰는데 가격대비 양도 푸짐하며 음식맛도 너무맛잇어요 또 재방문의사잇습니다!, 번역:

 99%|█████████▊| 22116/22421 [10:53<01:32,  3.30it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 라멘 국물을 한 숟갈 떠 먹는 순간 대박.  너무 진하지 않은 깔끔 시원한 국물 맛.  자칫 느끼할 수 있는 돈까스류 역시 기름을 쫙 빼 깔끔하다., 번역:

 99%|█████████▊| 22117/22421 [10:54<01:38,  3.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 한 7,8년째 가는 집인데 꾸준히 맛있고 양도 많음특히 라멘종류가 정말 맛있음돈까스는 양이 너무 많아서 한 번도 다 먹은 적이 없음내부가 좁은 편이라 몰리는 시간대에는 웨이팅 있음, 번역:

 99%|█████████▊| 22118/22421 [10:55<02:02,  2.48it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 양도 많고 가격도 적당하다고 생각합니다!! 돈까쮸 두껍고 진짜 맛잇어오 근데 너무 바삭해서 입천장 까질 준비해야됨 ㅜ ㅜ ㅋㅋ 라멘도 맛잇는데 차슈가 좀 아쉬워요!!! 탄탄멘 외에 매콤국물 선택할수 잇어서 좋앗어요~~ 다른분 후기처럼 라면 큰거 시켯으면 큰일날뻔 햇어요 가게는 크지않아서 운나쁘면 기다려야되는데 저는 운좋게 바로 들어갓네요!!! 옆테이블에서 연어덮밥 먹던데 진짜 맛잇어보엿어요 다음엔 연어덮밥 입니다!! 저는 교육잇어서 우연히 갓는제 동네주민들도 많이오는거 같아요~~!!, 번역:

 99%|█████████▊| 22119/22421 [10:55<01:57,  2.56it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 진짜 맛있어요. 가츠동도 맛있고 라멘두 정말 맛있어요!!, 번역:

 99%|█████████▊| 22120/22421 [10:55<02:05,  2.39it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격은 있는 편이지만 분위기와 친절함 그리고 맛으로 보장되는 것 같습니다예약하고가면 좋은자리해주시고 중간에 음식이 괜찮은지여부 등 체크해주시고 편하고 맛있게 먹었습니다모임장소로도 제격이네요^^, 번역:

 99%|█████████▊| 22121/22421 [10:56<01:59,  2.52it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여기 진짜 존맛 작년부터? 5월초 10일간 10만원이상 구매시 5만원 할인하던데 매년 갔으면... 스테이크피자는 올때마다 시킨다, 번역:

 99%|█████████▊| 22122/22421 [10:56<01:54,  2.61it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔하고 캐주얼하고 환한 느낌이라 좋아요.바운스에서  신나게 놀고  스트로베리피자랑 리조또로 아이들과 맛있는 외식~ 룸도 있어 가족모임,친구모임 할때도 좋겠어요~~, 번역:

 99%|█████████▊| 22123/22421 [10:57<02:04,  2.40it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 매우 맛이좋고 분위기도 좋아요딸기맛도 신선한데 피자와 함께 하니 더욱 맛이 좋고요행복한 데이트를 하기 좋은 곳이더라고요친구들 모임때도 좋고요자주 가고푼 곳이어요, 번역:

 99%|█████████▊| 22124/22421 [10:57<02:00,  2.46it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 잠실 마노디셰프 이탈리안레스토랑인데 분위기며 음식 맛 모두 여심저격이네요^^ 피자 파스타 모두 맛있고 한우스테이크도 고소하고 맛있어요 음식 식재료도 좋은걸 흐고 손님 엄청 많네요~~~ 연인들 데이트 하기에도 좋아요, 번역:

 99%|█████████▊| 22125/22421 [10:57<02:10,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 5만원 코스요리에 파스타, 스테이크, 디저트까지 맛있게 먹고 왔습니다. 무엇보다 디저트 티라미슈가 참 맛있음. 커피는 테이크 아웃 요청하면 가능합니다., 번역:

 99%|█████████▊| 22126/22421 [10:58<02:05,  2.34it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여자라면 넘나 사랑하는 딸기!딸아이랑 잠실 롯데월드 갔다가 저녁은 마노디셰프에서! 요즘 호텔 애프터눈티부터 시작해서 딸기뷔페 시즌인데요.마노디셰프 잠실에서도 시즌메뉴로 스트로베리 피자가 출시 되었더라구요.지난 연말모임을 마노디셰프에서 하고, 메뉴와 퀄리티에 완전 반함! 딸기와 크렌베리 그리고 크림치즈는 정말 넘나 궁합이 잘 맞고, 입에서 상큼함이 터짐! 크림파스타도 넘나 맛있고요. 아이랑 같이 먹기 두루 좋은 메뉴들만 있어요. 그에 비하면 가격은 넘나 합리적이고요. 여자들끼리 모임도 넘 좋고, 기념일에도 오븟하게 즐길 수 있는 분위기와 메뉴 구성이 매우 맘에 들었다는!직원분들도 넘 친절하구요.재방문의사 100!!, 번역:

 99%|█████████▊| 22127/22421 [10:58<02:17,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 흑임자 리조또는 맛있지만 호불호가 갈릴 수 있음. 로제파스타는 보통~, 번역:

 99%|█████████▊| 22128/22421 [10:59<02:27,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마노디셰프 잠실점에서 모임했어요. 스트로베리피자랑 스테이크, 파스타 골고루 주문해서 먹었는데 음식이 다 맛있었어요. 특히 토핑이 푸짐하고 오징어 먹물 도우로 나온 스트로베리피자는 완전 굿! 상콤 터저요!!, 번역:

 99%|█████████▊| 22129/22421 [10:59<02:24,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다 맛있는 마노디셰프~~ 특히 여기 빠네는 인생 최고의 맛.. 가격이 비싸긴 하지만 이벤트가 꽤 많음!!, 번역:

 99%|█████████▊| 22130/22421 [11:00<02:12,  2.20it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 피자 스파게티 다 맛있습니다.가격이 비싸서 쿠폰 있으면 한번씩 가는데 맛은 최고, 번역:

 99%|█████████▊| 22131/22421 [11:00<02:17,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여러분 기억하세요 스시래는 회덮밥입니다!스시래에서 다양한 메뉴를 먹어봤지만 여기같은 회덮밥 진짜 없고 회가 너무 많아서 회를 남길 정도입니다ㅋㅋㅋ가성비 갑은 무조건 회덮밥입니다!사시미정식은 물론 양 매우 많고 예쁘고 맛도 괜찮습니다만 회덮밥을 드시라구욧!전반적으로 양이 많고 사시미 정식은 잘 모르겠지만 가성비가 좋습니다.팁: 기억하세요 회덮밥, 번역:

 99%|█████████▊| 22132/22421 [11:01<02:30,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 개인적으로 회기에서 가장 맛있다고 생각하는 스시집이었는데... 이제는 사시미래로 바뀌어서 숙성사시미만 팔아요 ㅠㅠ 하지만 사시미도 겁나 맛있으니 꼭 한 번 가보세요!, 번역:

 99%|█████████▊| 22133/22421 [11:02<02:31,  1.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛이...너무... 부드러운맛도 없고 다 너무.... 뭐랄까 광어지느러미 비슷한 식감인데 그 고소함은 없는느낌이랄까...서비스도 주시고 하셨는데..  그날만그런건지 모르겠지만 다시 가진않을듯, 번역:

 99%|█████████▊| 22134/22421 [11:02<02:33,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격대는 저렴한 편에 양은 적지 않게 나와 가성비는 좋은 편., 번역:

 99%|█████████▊| 22135/22421 [11:03<02:28,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 스시 먹고싶을때 무조건 여기가요ㅋㅋ 양도 맛도 맛도 좋고ㅎ 우동은 별로지만ㅋ, 번역:

 99%|█████████▊| 22138/22421 [11:03<01:37,  2.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 학생때 먹던 치즈밥이 생각나서 가봤는데 맛이 그때 먹던 그대로다... 너무 맛있다ㅠㅠ💕처음드시는분은 이게무슨 맛인가 할수도 있겠다ㅎ 소자로 시켰는데도 양도 많고 치즈도 듬뿍! 주인아주머니들도 너무 친절하시다.여기와서 배불리 먹어도 2만원이 안넘는다.⭐️카드결제 안되고 현금결제랑 계좌이체만 가능해요!! 현금꼭 뽑아가세용, 번역:

 99%|█████████▊| 22139/22421 [11:04<01:39,  2.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛은괜찮다ㅜㅜ근데 나는여기별로안좋아한다 고등학교학생들주요메뉴인치주밥이 근처분식집들보다는제일맛잇기는한데 주인이현금만받으며절대신용카드안받아서 싫다, 번역:

 99%|█████████▊| 22140/22421 [11:04<01:46,  2.64it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식은괜찮다 치즈넣으면맛없는음식이어디있을까 만원이상 사먹었는데 카드가안된다고해선배한테내가사주러갔는데 미안하게 카드만잇어 결국선배가샀다 짜증이났다, 번역:

 99%|█████████▉| 22141/22421 [11:05<01:57,  2.39it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저렴하고 맛있어요 지역주민들이라면 모두 아는 맛집이라고 생각되네요, 번역:

 99%|█████████▉| 22142/22421 [11:05<01:58,  2.35it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여고 앞 분식집인데 꽤 오래 되었네요. 치즈밥이 유명하고 맛있습니다. 가격이 매우 싸서 정말 푸짐하게 먹을 수 있어요., 번역:

 99%|█████████▉| 22143/22421 [11:05<02:02,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이태원 쌀국수집.꽤 괜찮은 집입니다. 최근 7월에 리모델링 완료해서, 깔끔함니다. 이태원이라 기본적으로 가격대가 있지만, 충분히 바삭한 반쎄오와 새우버거 같은 반미가 있습니다. 개인적으로 고수를 많이 주셔서 감사합니다. 그리고 지역 주문들도 많이 오시는 것 같습니다.그런데-!!반미세트가 가성비가..참 안 좋아요. 굳이 드셔야 한다면 반미는 빼는걸로총평 : 이태원는 다 비싸ㅡㅡ, 번역:

 99%|█████████▉| 22144/22421 [11:06<02:17,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 찾아가기가 너무 불편하지만 맛있다. 반미가 맛있다고 해서 갔었는데 쌀국수가 정말 맛있었음, 번역:

 99%|█████████▉| 22145/22421 [11:07<02:32,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 한적한 공간에 위치 발렛파킹 가능하다. 쌀국수는 일반적이고 분짜는 한그릇에 나온다. 이집은 반미가 가장 좋았다.가격 비싼편, 번역:

 99%|█████████▉| 22146/22421 [11:08<02:45,  1.66it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 다 먹고 각자 반미 두개씩 포장해서 헤어졌어요... 말해 뭐해요.. 🧡위치가 좀 언덕이고 웨이팅한거 다 감안해도 꿀맛탱입니다!!!!!! 반미 꼭 하세용 !!!!, 번역:

 99%|█████████▉| 22147/22421 [11:08<02:31,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 반미가 특히맛있음 빵이 바삭하면서 부드럽고 소스가 맛남 ㅠㅠ 분짜랑 쌀국수도 내 입맛엔 딱이었음!! 분짜는 새콤달콤한 맛, 쌀국수는 숙주 없는 하노이식 쌀국수로 담백하고 진한 맛!, 번역:

 99%|█████████▉| 22148/22421 [11:09<02:33,  1.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 쌀국수와 튀김쌈을 시켜 먹음. 쌀국수 국물은 담백한 편으로, 고깃국물스러움은 덜해서 남자보단 여자들이 좋아할 스타일. 안그래도 오픈 전에 가서 기다렸는데 기다리는 20여명중 80%는 여자.튀김쌈은 포포유 것을 더 선호한다. 여긴 너무 단백하기만해서 좀 심심한 맛., 번역:

 99%|█████████▉| 22149/22421 [11:09<02:34,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 배달만 먹어봄! 두번 먹었음!맛좋아욤~~^^반미는 다른곳에서도 먹어봣지만 이곳이더 맛좋아요!응원합니다~, 번역:

 99%|█████████▉| 22150/22421 [11:10<02:34,  1.75it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저녁 먹으러 방문했는데 시킨것과 다른 메뉴가 나왔음. 여직원이 "제가 주문 받았다구요?" 하고 잘못나온 음식을 들고 가 버리고는 설명 혹은 사과 한마디도 없음. 몇번이나 눈 마주쳐도 모른척 함. 분명 내돈 내고 사먹으러 온건데 무슨 반찬투정하는 진상한테 적선하는 느낌. * 화장실은 외부 공중화장실 사용해야함* 음식은 맛있음, 번역:

 99%|█████████▉| 22151/22421 [11:10<02:16,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 수요미식회 맛집은 역시 배반하지 않았다실제 베트남 사람이 서빙하고사십대인 내가 지금껏 느끼지 못했던 새로운 맛을 보았다국물쌀국수와 비빔쌀국수를 먹었는데비빔이 더 맛있었고다음에는 다른 메뉴도 도전해보고싶다이태원에서는 쟈니덤플링과 함께다시가고픈 식당이다발레파킹으로 생각했는데 3천원을 따로 받는 것은 아쉬운 점이다, 번역:

 99%|█████████▉| 22152/22421 [11:10<02:06,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있다 고기의 짭조름한 단맛과 국물과 면의 조화 바삭한 빵과 계란의 부드러운 조화가 좋다, 번역:

 99%|█████████▉| 22153/22421 [11:11<01:59,  2.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 베트남 정통 반미는 아닙니다. 하지만 이곳은 반미 맛집입니다. 초밥집에서 식사 후 가장 맛있고 기억에 남는게 캘리포니아롤인 경우와 같은 느낌입니다., 번역:

 99%|█████████▉| 22154/22421 [11:11<02:13,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분명 발렛파킹이라고 되있었는데 내가 방문한 월요일은 안된단다..주차로 인해서 우리포함 다른손님들의 대혼란이 있었다 식당앞에 잠깐 세워놓고 쫒기듯 먹고 나와서 아쉬웠다 음식은 반미 국물쌀국수 분짜를 먹었는데 참 맛있었다, 번역:

 99%|█████████▉| 22155/22421 [11:12<02:11,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 전반적으로 회전이 느린 편이라 좀 기다려야하고 좌석이 불편합니다그래도 쌀국수 외에는 맛이 좋고, 양이 많아서 갈만합니다, 번역:

 99%|█████████▉| 22156/22421 [11:12<02:12,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 반미샌드위치맛잇어요 또방문하고싶네요 한번가보세요~~^^, 번역:

 99%|█████████▉| 22157/22421 [11:13<02:23,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분식집같은 분위기   스테이크 와인 파스타 분위기 소규모 레스토랑기대하고갔는데 ㅠㅠ  26000에 이정도면 가성비는good치즈퐁듀는   보통 하얀치즈가나오는데슬라이스노란치즈가나와서당황스테이크소스는  스테이크소스랑   돈까스소스나옴반찬으로  무길게 절인거나  피클이아닌해장국집에서나오는깍두기랑고추절임이 나오는건 스테이크랑 안어울림, 번역:

 99%|█████████▉| 22158/22421 [11:14<02:11,  2.00it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저렴한 가격에 고기가 먹고싶다면 가기 좋은 곳이에요. 체인이 워낙 많은 곳이기도 하고, 어디 맛집 쳤을때 은근히 자주 따라오는 곳이라 한번 가봤습니다. 가격은 8~9천원대로, 고기메뉴 치고는 저렴하다 할 수 있는 가격입니다. 맛은 그냥 보통이고 고기 질도 많이 좋다고는 생각 안되지만 나쁘진 않았어요!그런데 정말 고기가 먹고싶다면 이천원정도 더 들고 가서 무한리필 가는것도 나쁘진 않을거같아요ㅎㅎ 사실 재방문의사는 그닥 없습니다, 번역:

 99%|█████████▉| 22159/22421 [11:14<02:04,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 밥도 같이 나오는 점이 좋았습니다. 가성비 높은 메뉴인 것 같네요., 번역:

 99%|█████████▉| 22160/22421 [11:15<02:14,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격은 착하고, 먹을 수 있는 만큼 선택할 수 있어요. 깔끔하고 맛있어요.개인적으로 소고기 맛있고 목살 조금 달아요., 번역:

 99%|█████████▉| 22161/22421 [11:15<02:18,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가게 내부가 좀 많이 어두웠음 조명 자체도 어두웠음음식은 보통 엄청 맛있는정도는 아니었음, 번역:

 99%|█████████▉| 22162/22421 [11:16<02:09,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마르고 질긴 소고기. 이런 퀄리티라도 상관 없을 정도로 소고기 섭취를 원하는 통학러에게 추천합니다., 번역:

 99%|█████████▉| 22164/22421 [11:16<01:39,  2.59it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 3명이 뼈다귀전골(중) 수제비 주문 했어요! 맛은 무난해요 구지 맛집으로 찾아오기 보다 근처에서 뼈다귀 해장국 먹고싶을때 오면 좋을 것 같아요! 다만 주차를 식당앞에 하는데 거의 길거리에 하는거라.. 좀 불편했어요ㅠㅠ, 번역:

 99%|█████████▉| 22165/22421 [11:17<01:46,  2.41it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 목동 현대백화점 바로 길건편에 위치.점심시간에는 백화점직원과 지역주민들로 꽉차는 식당.해장국은 등뼈가 큼지막한게 두덩어리 들어가있고 뼈사이에 고기가 많이붙어있어서 다른식당에 비해 매우 만족스러움.가게를 방문했을때 혼밥을 드시는 분들도 많았고 4인 테이블을 혼자식사를해도 사장이나 직원들은 전혀 눈치주지를 않음.주차는 가게 바로 옆에 가능하며 24시 운영됨., 번역:

 99%|█████████▉| 22166/22421 [11:17<01:54,  2.23it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저녁때 갔는데 사람 되게 많음. 요새는 뼈 2개 주는지 뼈2개에 우거지가 많이 들어가있음. 살이 많아서 충분했음. 깍두기 맛있음 서빙해주시는 분들이 친절함 약간 민망하지만 혼자가도 됨, 번역:

 99%|█████████▉| 22167/22421 [11:18<01:51,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 뼈해장국이랑 감자탕이 먹을만함. 뼈찜은 그냥저냥. 술 한잔 기울이기 좋아요, 번역:

 99%|█████████▉| 22168/22421 [11:18<01:52,  2.26it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 곰돌이 아이스가 유명한 커피집.합리적인 가격과 맛이 매력있는 카페입니다.인테리어도 감각있고 무엇보다 창밖으로보이는 꽃 핀 정원이 예뻐서 좋습니다!, 번역:

 99%|█████████▉| 22169/22421 [11:18<01:46,  2.36it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 너무 예쁜 카페예요! 넘 귀여운 곰돌이 샷 때문에 그런지 더 자주 오게돼요! 놋북 하기도 좋고 수다떨기도 좋아서 연신내 사시는 분들께 추천드려요 :), 번역:

 99%|█████████▉| 22170/22421 [11:19<02:00,  2.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 곰돌이모양의 얼음이 유명함 밖에 고양이가있음 매우 귀여워.., 번역:

 99%|█████████▉| 22171/22421 [11:19<02:03,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 뜨끈한 국물이 땡길 때 닭한마리 너무 좋죠!! 닭도 푸짐하고 다른 곳에 비해 가격도 저렴해서 좋았습니다^^, 번역:

 99%|█████████▉| 22172/22421 [11:20<02:02,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: - 20년 넘은 식당이지만 리모델링해서 깨끗하고 깔끔한 분위기- 다른 곳보다 저렴한 가격. 친절한 사장님- 국물도 깔끔하고 떡사리 쫄깃쫄깃, 소스랑 밑반찬도 다 맛있어요. - 재방문의사 O, 번역:

 99%|█████████▉| 22173/22421 [11:20<01:56,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 푸짐하고 깔끔한 국물. 추운날 생각남. 사장님 친절하심. 식사시간에 웨이팅 있음. 마무리로 칼국수에 죽까지 먹어야함!, 번역:

 99%|█████████▉| 22174/22421 [11:21<01:58,  2.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 한양닭한마리 천호점닭한마리먹고 칼국수먹고 죽먹으면 든든해요, 번역:

 99%|█████████▉| 22175/22421 [11:21<01:57,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 방학역 바로 인근에 위치한 카페라서 그런지 항상 손님이 많은 가게. 메뉴 구성이나 맛에서 특별한 점은느낄 수는 없었다. 지리적 위치가 워낙 좋고 무료 주차가 가능해서 그런지 이 근처에 갈 때마다 들리게 되는 커피숍이다., 번역:

 99%|█████████▉| 22176/22421 [11:22<02:11,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 규모가 엄청 크고 멋있어요. 앤틱한 분위기이고 카페 이용 시 90분 무료주차 가능합니다., 번역:

 99%|█████████▉| 22177/22421 [11:23<02:06,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 도봉구에 넓은 카페 가고싶을때 갈듯해요세트메뉴도 가성비좋고 맛잇네요커피는 좀 쓴맛나는편, 번역:

 99%|█████████▉| 22178/22421 [11:23<02:05,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 리모델링 하고 나니 매장에 코드가 모두 사라졌어요. 대신 2층 한 구석에 일렬로 코드 사용가능한 자리를 만들었어요. 천장이 매우 낮아서 서서 지나다닐 수 없는곳이에요. 장시간 앉아있을 분들을 위한듯 해요. 그리고 주차당에 차단막도 생기고 90분까지만 커피 마시는 손님에 한해서 무료로 가능해요. 추가 10분당 천원이라는데 받는지는 확인 안해봤어요.아인슈페너랑 아메리카노랑 이것저것 다 먹어봤는데 전부 괜찮았어요. 드립커피 먹을때 고를 수 있는 원두종류가 제법 있고 최상의 맛은 아니지만 선택지가 많기에 좋아해요. ※ 도장 이제 없어지고 도도포인트적립 해줍니다.(10개 모으면 아메리카노 or 4천원 할인) 브런치 메뉴도 새로 생겼습니다., 번역:

 99%|█████████▉| 22179/22421 [11:24<02:10,  1.85it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 줄을 오래서야하는 단점이 있으나 맛이 일품임. 라면은 필수, 번역:

 99%|█████████▉| 22180/22421 [11:24<02:05,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 숯불치킨 자체가 일단 맛있는 음식이라 맛없을 수가 없는듯... 라면이랑 같이 먹으니 너무 맛있네요, 번역:

 99%|█████████▉| 22181/22421 [11:25<02:08,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 눈치보면서 무게 측정해가며 먹는 마라탕에 아쉬웠을때!! 가서 양껏 먹을 수 있는집!야채는 물론 면사리, 고기까지 셀프 무한리필로 눈치볼 필요없이 잔뜩 먹을 수 있다!셀프로 제조해먹는 소스도 만드는 재미가 있음!!다만 시끄러운 편이고 무한리필이라 회전률이 느려서 타이밍 잘못 맞추면 대기가 길 수 있음!, 번역:

 99%|█████████▉| 22182/22421 [11:25<02:15,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 요즘 핫한 마라탕집 맞은편 2층에 있는 훠궈집입니다. 상호명이 같은데 뒤에만 'ㅇㅇ훠궈', 'ㅇㅇ마라탕'이라고 되어있는걸 보니 같은 집인듯합니다. 꽤 이른시간에 방문했는데 마라탕은 줄이 길었어요. 훠궈집도 처음엔 줄이 없었지만 금방 줄이 생겼습니다.원하는 재료를 양껏 가져다먹을 수 있는 뷔페기 때문에 넘나 좋았어요. 청경채나 각종 버섯, 당면, 육고기와 해산물 등이 많았습니다. 해산물은 아주신선한게 아니라면 선호하지 않아서 안먹었고, 주로 육고기와 야채위주로 먹었어요. 홍탕/백탕 반반 먹었는데 무난했습니다. 소스도 마음껏 제조해먹고 다 마음에 들었어요. 손님들 대부분과 직원들이 현지인이라 외국온거 같은 느낌도 들었어요. 훠궈먹으러 또 갈듯!!, 번역:

 99%|█████████▉| 22183/22421 [11:26<02:00,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 애정마라샹궈가 나의 마라탕/마라샹궈 최애 맛집이었기에 애정훠궈(바로 맞은편 건물이다.)에 갔고 매우 만족. 항상 대기가 많은 애정마라에 비해 애정훠궈는 널널한 편이라 마라만 들어가면 메뉴 상관없고, 경제적 여유가 널널하다면 가보자. 다른 훠궈집에 비해 다른점은 보통 무한리필 15000원이지만 여기는 16800원이며, 깔끔한 편이다. 끈적한 바닥이나 오래된 건물 특유의 퀴퀴함에 비위가 약하다면 1800원 더 내고 여길 가는걸 택하자. 단점은 홍탕의 마라 세기가 그때그때 좀 다르다. 좀 안매운것같다면 알바분에게 부탁드리자. 육수 새로 채워주시면서 조절 가능. 애정 프랜차이즈답게 야채가 더 깔끔싱싱. 입가심으로는 아이스크림(한그릇까지 무료라 써있었다)과 음료가 있음. 혼밥공간 있음., 번역:

 99%|█████████▉| 22184/22421 [11:26<01:55,  2.05it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 애정 마라샹궈나 훠궈나 배탈 나는건 똑같아요! 다른 마라탕집은 안그러는데 유독 여기만 오면 배가 아파요.. 근데 맛있긴함, 번역:

 99%|█████████▉| 22185/22421 [11:27<02:01,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 애정 마라샹궈에 이어 애정 훠궈는 정말 최고.. 무한리필이라 눈치 안 볼 수 있어 좋아요, 번역:

 99%|█████████▉| 22186/22421 [11:27<02:02,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 성신여대 골목에 숨어있는 맛집이에요!! 탕종류도 다양해서 중국향 싫어하시는 분들은 백탕이나 사골로 드시면 될거 같아요!! 홍탕은 향신료 향이 조금 났고 백탕은 그냥 개운한 한식육수같은 맛이에요!! 홍탕은 덜맵게 해달라고 하면 해주시니까 매운거 못드시는 분들은 주문할때 미리 말씀하시면 될거 같아요!! 무한리필치고 고기 종류3가지에 질도 괜찮아수 정말 맛있게 먹었어요 그리고 요즘 핫한 중국당면까지!! 사리 종류도 다양하고 하나하나 맛있고 소스 종류도 많이서 맛있어요!! 추천!!, 번역:

 99%|█████████▉| 22187/22421 [11:28<01:53,  2.06it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 홍탕(마라탕) 맵기를 3단계로 조절 가능함.. 홍탕은 중국향이 쎔.., 번역:

 99%|█████████▉| 22188/22421 [11:28<01:54,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 훠궈 무한리필로 바뀐후 15800원에 맛있게 즐길 수 있음 질도 좋아서 추천, 번역:

 99%|█████████▉| 22189/22421 [11:29<02:00,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 훠궈 땡길때마다 오는곳이예요~! 오로지 훠궈만이 먹고싶은날!! 고기도 소, 양, 돼지 무제한으로 먹고 싶을때, 다양한 야채들이 땡길때!! 최근에는 중국당면까지 추가되어서 멀리 있는 로운까지 안가도 되서 행복해요ㅠ 홍탕 리필 할때 마라소스를 주시는걸로 보아서 따로 부탁드린다면 좀 더 진한 맛의 홍탕도 맛 보실수 있을거같아요~ 재료도 너무 신선하구! 특히 물만두!! 정말 맛있으니까 꼭 한번 드셔보세요~, 번역:

 99%|█████████▉| 22190/22421 [11:29<01:47,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 훠궈 먹고싶을때 가기 좋아요 국물도 맛있고 역에서 접근성도 좋습니다, 번역:

 99%|█████████▉| 22191/22421 [11:30<01:47,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 신천에서 꾸준하 사랑받는 집이라고 생각합니다. 저도 비오는 날이면 진한 육수가 생각나서 종종 찾습니다. 부추에 다대기와 식초간장인가 뭔지 잘 모르겟는 국물에 적셔서 닭고기와 먹으면 아주 맛있습니다. 중자가 한마리반 대자가 두마리 입니다. 국수사리도 하나만 시켜도 맛보기엔 괜찮은 양이라 볶음밥 드실 분들은 하나만 시키셔도됩니다. 계란이 들어간 죽이 아니라 볶음밥이라 텁텁하지않고 마무리가 더 깔끔한것 같아요 동치미는 좀 너무 단 경향이 있습니다. 자리가 넓어서 좋아요! 육수리필 무제한 급으로 해주셔서 한도 끝도 없이 들어가네요(고기도 추가 주문 가능), 번역:

 99%|█████████▉| 22192/22421 [11:30<01:50,  2.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이전한곳 찾느라 좀 시간이 걸렸고 웨이팅있었습니다역시 맛은 이전과 같이 맛있고 볶음밥 너무 맛있습니다 ㅎㅎ, 번역:

 99%|█████████▉| 22193/22421 [11:31<01:53,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 몸보신에 딱 좋아요! 재방문의사 많아요! 국물 좋고 부추 소스 좋고. 근데 부추추가가 돈을 받네용 충무로 닭한마리는 안그랬는데! 7시이후부터는 웨이팅 많이 생기니 미리가길 추천해요. 주차가 안돼서 아쉽지만 근처 1시간 4천원 유료 주차장이 있어요!, 번역:

 99%|█████████▉| 22194/22421 [11:31<01:56,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔한 국물맛은 동대문에 있는 집들과 차별이 된다. 과하지 않은 단백한 맛..., 번역:

 99%|█████████▉| 22195/22421 [11:32<01:59,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 동대문 닭한마리 골목 집들 보다 국물이 좀 더 뽀얗고 마늘 베이스라 개인적으로 더 맛있게 먹었습니다. 여긴 김치도 많이 쉬지 않고, 같이 주는 오뎅볶음도 꼬득꼬득해서 별미입니다. 옆에서 닭볶음탕도 많이 드시고 계셨는데 볶음밥에 참기름 냄새가 너무 맛있게나서 다음엔 꼭 닭도리탕을 먹어보고 싶어요., 번역:

 99%|█████████▉| 22196/22421 [11:32<01:55,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 항상 기다려야 하는 집이지만 땡기는날에는 기다리면서 까지 먹어도 후회안하는집 맛있어요, 번역:

 99%|█████████▉| 22197/22421 [11:33<01:54,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격에 비해서 양이 적은 거 같아요직원분들이 많고 손님도 많았어요, 번역:

 99%|█████████▉| 22198/22421 [11:33<02:01,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 신천 먹자골목에 있는 식당 식사시간에는 웨이팅이 있습니다, 번역:

 99%|█████████▉| 22199/22421 [11:34<02:01,  1.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 미슐랭 식당으로 굉장히 유명한 집입니다. 감자탕, 족발이 전부다 맵습니다. 매콤한 정도가 아닌 매운 정도 입니다. 족발을 많이 좋아하는데 보통 수준의 맛입니다. 감자탕도 보통 정도 입니다., 번역:

 99%|█████████▉| 22200/22421 [11:34<01:49,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 노포의 정겨움. 감자탕 고기가 부드럽고 국물이 꽤 매콤함., 번역:

 99%|█████████▉| 22201/22421 [11:35<01:46,  2.07it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 직원들하고 부담없이 회식하기 좋은 곳. 족발은 제법 매콤합니다. 감자탕 국물이 다른 집과 조금 달라요. 식당 청결도는 그닥 ㅎㅎㅎ, 번역:

 99%|█████████▉| 22202/22421 [11:35<01:53,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 족발이 찐! 감자탕도 맛잇찌만 족발이 진짜임 대신 좀 매움, 번역:

 99%|█████████▉| 22203/22421 [11:36<01:51,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 콩나물과 부추를 넣어 얼큰한 매운탕 느낌의 감자탕인데 내 스타일은 아니었다... 같이 먹은 친구도 그냥 원래 감자탕 맛이 더 맛있다고함,, 그냥 한 번 먹어보기에 좋은듯.. 부추와 콩나물 양은 사진으로 보던거많큼 많지가 않아서 실망했다ㅠ 소자라서 그런가ㅠ 근데 더 주시진 않음.. 굉장히 단호하게 안주신다고 해서 당황ㅋㅋ 그리고 사람 별로 많지도 않았는데 반찬이랑 물이랑 다 너무 늦게 갖다줘서 좀 그랬다... 몇 번 말했는데 너무 느림;; 다시 안갈듯, 번역:

 99%|█████████▉| 22204/22421 [11:36<01:51,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: - 이집의 맛은 먹을때는 좋았으나, 다음날 고생 좀해야할것이라는 점과 서비스는 영 아닌것 같음.또한 음식에 대해서는 매우 야박하였음. 백종원이가  음식을 먹을때는 채소가 푸짐하여  보였으나, 직접 방문하여 먹어보니 채소도 적어서 좀 더달라고 했더니 못 준다고 하여서 이런 집이 다 있나 생각했습니다.또한 공기밥을 시켰는데 밥은 한공기가  아니라 반공기였습니다., 번역:

 99%|█████████▉| 22205/22421 [11:37<01:59,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 근처에 갔다가 맛집이라고 하여 방문했습니다.맛은 생각보다 괜찮았습니다. 2인 방문하여 감자탕 소 2.5만원에 공기밥을 두개 시켰어요.. 2인이라고 하기엔 양이 굉장히 많았습니다. 하지만 가격 생각하면 쏘쏘.서비스는 말그대로 별로였습니다. 불친절까진 아니었지만 식딩치고는 굉장히 박한 먹거리 인심을 가지고 계시더군요.  국물이 짜지는 것 같아 야채 좀 더달라고 했다가 사장님으로 보이시는 분께서 손사래를 치시며 야채는 안드려요라고 딱 잘라 얘기하시더군요. 콩나물과 부추를 추가로 제공해주지 않는 식당 정책은 이해하지만 꼭 마치 제가 뭘 잘못알고 부당한걸 요구하는 것 같이 느껴지게 말씀하시는지.. 맛이 괜찮았지만 다시 오고 싶지 않았습니다., 번역:

 99%|█████████▉| 22206/22421 [11:38<02:01,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 지금까지 먹어본 감자탕중 최고. 다른감자탕이랑은 좀 맛이 다른편임.. 콩나물국물에 뭔가 맑고 개운한 느낌임. 이런 스타일 좋아하면 만족할것임.불친절하다는 후기도 본거같은데 나 갔을때 할머니들은 먹는방법도 알려주고 결제때도 친절했음. 티비에 나온 맛집 가본곳중에 제일맛있던듯., 번역:

 99%|█████████▉| 22209/22421 [11:38<01:19,  2.66it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주차는 옆에 3-4대 가능후진해서 나와야 함안쪽에 자리 넓어요, 번역:

 99%|█████████▉| 22210/22421 [11:39<01:34,  2.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여기 정말 맛있습니다.다른 곳보다 1000~2000원 정도 더 비싸긴하지만그만큼의 이유가 있고 맛이 균일하고 변함이 없는 곳입미다! 개인적으로 추천합니다!, 번역:

 99%|█████████▉| 22211/22421 [11:39<01:39,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 재방률 90%. 맛있다. 가격은 중간가격인데 맛은 상급에 가깝다. 량도 많아 특히 저녁에 가면 1.5인분을 주는데 정말 배부르게 먹을 수 있다.특히 시카고 피자맛이 일품이다. 다만.. 알바생이 피자 불도 안 붙여주고 피클도 안 주기는 했지만... 좋았다. 물론 또 오고싶을 정도., 번역:

 99%|█████████▉| 22212/22421 [11:40<01:45,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 얇은 화덕피자 레귤러사이즈는 여자 둘이 먹기에 딱 알맞은 양입니다. 바질이 들어가 맛있고, 초를 켜주신 덕분에 피자가 식지 않고 따끈하게 먹을 수 있어서 좋았어요., 번역:

 99%|█████████▉| 22213/22421 [11:41<01:43,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 피제리아!!!! 개인적으로 서가앤쿡이랑 비슷하지만 훨씬 퀄리티가 좋은 것 같아요. 몬스터세트가 2-3인이라고 되있었는데 여자 2명이서 배터지게 먹었습니다. 3만원 정도 나왔던 것 같아요. 서가앤쿡 같은 식당을 좋아하시면 정말 만족하실 것 같아요:) 몬스터세트에서 파스타 종류 3개 중 하나로 선택할 수 있는 것도 좋은 것 같아요. (대부분 저희처럼 빠네를 드시더라구요) 친구들끼리 딱히 갈 곳 없을 때, 스파게티 먹고 싶을 때 가면 좋아요:), 번역:

 99%|█████████▉| 22214/22421 [11:41<01:47,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마약옥수수는 생각보다 별로였어요 뉴욕에서 먹는 옥수수 생각했는데 그렇진 않고 피자랑 파스타는 맛있었어요, 번역:

 99%|█████████▉| 22215/22421 [11:42<01:40,  2.05it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 강남치곤 가성비 굿굿 아메리칸 정식이구 셋이서먹을거면 세트 피자라지가 적당해요화요일 6시반에가서 자리많던데 다먹고나오니 바깥까지 줄서있더군요  추천~, 번역:

 99%|█████████▉| 22216/22421 [11:42<01:37,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가성비가 좋아요! 파스타, 음료 양이 많았고 피자를 계속 데워주셔서 좋았어요~ 저녁때보다 점심때 가면 저렴해요!, 번역:

 99%|█████████▉| 22217/22421 [11:43<01:43,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 빠네 먹었는데 느끼하지 않고 맛있었던것 같음 딸기에이드도 맛있었는데 좀 미지근?해서 좀더 쉬원했으면 좋았을듯, 번역:

 99%|█████████▉| 22218/22421 [11:43<01:48,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 언제 와도 맛있어요. 가격도 괜찮은데 뭘 시키든 실패 없는 메뉴들~, 번역:

 99%|█████████▉| 22219/22421 [11:44<01:39,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 강남역치고 가격도 저렴하고 위치도 역이랑 가까운 편이라 종종 가는 곳, 번역:

 99%|█████████▉| 22220/22421 [11:44<01:30,  2.22it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 20대 초 중반의 친구들이서 가볍게 수제 맥주와 안주로 수다떨기 좋은 집., 번역:

 99%|█████████▉| 22221/22421 [11:44<01:35,  2.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 피자가 맵다고 되어 있는데 정말 맵습니다. 감자튀김도 매우니 주문하실 때 주의하셔야 할 듯. 사진에는 주차장이 있는듯하지만 그 골목을 점령한 발렛파킹 맡겨야 하고요. 발렛파킹은 별로 안 좋은 경험이었습니다. 직접 찾으러 돌아가야 하고 불편하니 참고하시길., 번역:

 99%|█████████▉| 22222/22421 [11:45<01:37,  2.05it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 친구들이랑 맛있는 음식 먹으면서 즐거운 시간 보냈어요. 직윈은 불친절, 번역:

 99%|█████████▉| 22223/22421 [11:45<01:28,  2.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식 전체적으로 깔끔하고 맛있습니다. 음료도 비싸지만 양이 많아서 두명이서 하나 시키면 될 거 같구요, 피클은 직원에게 문의해야 줍니다., 번역:

 99%|█████████▉| 22224/22421 [11:46<01:26,  2.28it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분위기도 좋고 가격도 적당해요 가격대비 배터지게 먹을수있어요, 번역:

 99%|█████████▉| 22225/22421 [11:46<01:36,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이것도 대구꺼인가 대구꺼따라한거인거 몰겠다 그냥그냥이다 고만고만하다 1020초반에게는 괜찮을 곳 나는 무난 이하인곳, 번역:

 99%|█████████▉| 22226/22421 [11:47<01:32,  2.10it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 규모나 인테리어, 메뉴들에 비해 저렴하기도 하면서 맛도 준수하고 양도 괜찮습니다., 번역:

 99%|█████████▉| 22227/22421 [11:47<01:37,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 적절한 가격과 맛이있는곳 특히 옥수수와 음식의 조합은 정말 신선하다!!, 번역:

 99%|█████████▉| 22228/22421 [11:48<01:44,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 무난하다. 떠먹는 피자가 금방 식어 먹기 힘들다., 번역:

 99%|█████████▉| 22230/22421 [11:49<01:17,  2.45it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 압구정 스탠다드 서울식 한식집.  말도 안되지만 남녀노소 누구에게나 맛있는 식사를 낸다. 그것도 대량생산으로 필요한만큼만 깔끔하게 맛을 유지한다. 이 어려운 일을 해낸 것 만으로도 미슐랭에 오를 만 하다. 식기 및 식사 도구는 최고급은 아니지만 깨끗하고 정갈하게 유지된다.  거기에 맞춰 음식재료도 최고급은 아니지만 깨끗하게 다듬어 정갈한 맛을 보여준다. 뜨거운 음식은 아래 불판이 준비되어 있고 시원한 음식은 그에 맞는 찬식기에 담아 나온다. 일인전으로 각기 간단한 한 상차림으로 통일하고 주문음식에 따라 약간씩 기본찬이 바뀌기도 추가되기도 한다.  특별히 모난 곳이 없는 모든 음식의 현실적 모범생같은 좋은 식당이다. 표창장을 받아 마땅하고 그에 걸맞는  뛰어난 매뉴얼적 관리가 단연코 으뜸인 좋은 식당이다., 번역:

 99%|█████████▉| 22231/22421 [11:49<01:21,  2.34it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고급 깨끗점심특선과 점심메뉴는 가격이 조금 내려가 먹을만 하다강남 장년층들이 많이 찾는 집이다점심때도 예약하지 않으면대기번호 받아야 한다음식 맛은 깔끔하다, 번역:

 99%|█████████▉| 22232/22421 [11:49<01:20,  2.36it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있었던 기억을 갖고 오랜만에 찾았는데, 반찬도 불고기도 보통수준으로 전락??? 하지만 가격은 더 올랐고, 접객 마인드도 불만, 번역:

 99%|█████████▉| 22233/22421 [11:50<01:22,  2.28it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 무난하게 먹을 수 있는 맛이에요. 갈비탕보다는 된장찌개가 더 맛있었어요. 돌판을 이용해서 끝까지 뜨겁게 먹을 수 있는 그릇이 참 좋더라고요., 번역:

 99%|█████████▉| 22234/22421 [11:50<01:24,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 유명한 한식집 명성에 맞는 평양냉면 맛 면이 가늘다 두두둑 끈기는 식감좋음 육향 동치미국물맛 괜찮았음 도심속 고급 한정식집 최상급 숙성소고기 구워서 내달라고 주문하면 고기 굽는 냄새없이 적당한 온도에서 식사를 할 수 있다 두번 나누어 내준다 한정식집 답게 맡반찬도 훌륭하다 후식은 여러가지 가능한데 난 당연 평양냉면 이또한 면발 육수 고명 최상임을 인정, 번역:

 99%|█████████▉| 22235/22421 [11:51<01:38,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식: 음 역시 한일관이네요.. 불고기 너무 맛있고. 불고기에 냉면사리를 넣으면 진짜... 너무... 너무입니다. 너무 맛있어... 그게 별미구나 싶어요. 반찬도 정갈하고.. 식사로는 냉면을 먹었는데요. 냉면도 능히 맛있네요. 다만 가격이... 가격이 사악하네요.서비스: 매우 친절하십니다. 분위기: 고급스러운 느낌이에요.위생상태: 깨끗해요., 번역:

 99%|█████████▉| 22236/22421 [11:52<01:43,  1.79it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 압구정동 한일관에 들렸음~맛 정성 식감 시각 청각 다 맘에 들었는데...ㅋ개인적으로는 좀 비쌈!! 물론 한일관이라는 브랜드와 내공 신뢰 등... 생각하면 괜츈한 가격이지만... 어르신들 모시는 식사자리라든가, 한식데이트 하고 싶은 여자친구에게 알맞는 음식점?? 그정도 가격입니다.점심에 코스요리는 부담이 조금은 덜하니.. 추천드리구요!!개인적 입맛에는 식사로 깔끔한 육개장 추천합니다~^^참!! 쌀 어디지역에서 공수해 쓰시는지 모르겠지만... 밥맛 너무너무 좋습니다!! 쌀이 맛나요~^^, 번역:

 99%|█████████▉| 22237/22421 [11:52<01:37,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 정갈한 한정식을 먹고 싶을때 찾는 집!갈비탕이 맛있으나 저녁에 가면 다 떨어질 수 있음, 번역:

 99%|█████████▉| 22238/22421 [11:53<01:43,  1.76it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 한일관 음식 정갈하고 맛있어요. 비싸서 글치, 번역:

 99%|█████████▉| 22239/22421 [11:53<01:42,  1.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마라탕 국물이 매콤하고 땅콩맛이 많이 나서 맛있다 마라탕 최애집, 번역:

 99%|█████████▉| 22240/22421 [11:54<01:49,  1.65it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 마라탕처돌이로 만들어버린 곳 가산에서 일하면서 남은건 여기마라탕뿐 전성기시절엔 점심시간에 한시간도 기다리고 주 3회 먹어도 질리지않았음 땅콩소스가 강하고 향신료도 쎄지않은 현지화된맛집 별점오점!, 번역:

 99%|█████████▉| 22241/22421 [11:55<01:40,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 향신료가 강하지 않고 땅콩소스 맛이 강해 누구나 쉽게 도전할 수 있음! 국물 최고!! 재방문 의사 매우 있음, 번역:

 99%|█████████▉| 22242/22421 [11:55<01:39,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이 가게에서 마라탕 입문~! 땅콩소스 덕분에고소하고 향이 쎄지 않아서 맛있어요~! 가디맛집~! 추천추천, 번역:

 99%|█████████▉| 22243/22421 [11:56<01:36,  1.85it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 땅코소스맛이 많이 나서 매우 만족점심시간은 많이 붐벼서 저녁에 먹는게 편할듯, 번역:

 99%|█████████▉| 22244/22421 [11:56<01:32,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격도 하나에 3900원밖에 안 하는데 양도 푸짐한데다가 맛있음 혼밥러는 그저 찬양합니다 강추추 강추, 번역:

 99%|█████████▉| 22245/22421 [11:56<01:22,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 미스사이공 망우점 쌀국수🍜두말할거없이 엄청 맛있는, 그래서 자주 방문하는 곳입니다. 쌀국수 양도 푸짐하고 매콤한 칠리소스가 일품입니다. 여러점 방문해 보았지만 육수가 간간하고 숙주도 엄청 많이들어가있어요. 가끔 육수가 싱거운 매장이있는데 망우점은 정말 간간하고 맛납니다^^ 엄청 친절하세요!, 번역:

 99%|█████████▉| 22247/22421 [11:57<01:00,  2.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분짜로는 우리나라 최고의 맛집이 아닐까 싶다당근을 싫어하는 사람도 이곳의 새콤달콤한 당근 소소를 듬뿍 담궈서 먹게 된다는마성의 분짜 맛집게다가 베트남식 만두 짜조는 어찌나 맛있던지 최고임조금 아쉬운 점은 쌀국수 국물이 엄청 진하지는 않다는 것하지만 인테리어며 소품이 주는 이국적인 풍경은맛을 한껏 더 살리는 요소로 손색이 없다점심시간에 가려면 11시 30분 전에 가서 먹어야 함웨이팅이 엄청남, 번역:

 99%|█████████▉| 22248/22421 [11:57<01:08,  2.53it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 연휴에 조용하게 먹을 수 있는 곳이었어요. 음식이 상각보다 빨리 나와요. 넓고 좋아요., 번역:

 99%|█████████▉| 22249/22421 [11:58<01:14,  2.31it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 쌀국수 처음먹어보는데 진짜 엄청 맛있음 양지쌀국수 국물이 진짜 진국, 번역:

 99%|█████████▉| 22250/22421 [11:58<01:10,  2.44it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분짜가 엄청 맛있다는 후기들을 보고 찾아갔는데 그냥 일반적인 베트남 음식점과 별반 다르지 않고 가격이 비싸며 양이 많이 적었음, 번역:

 99%|█████████▉| 22251/22421 [11:59<01:10,  2.42it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 쌀국수는 국물도 엄청 진하고 맛이 좋은데 에머이가 분짜로 유명한것과는 달리 분짜가 기대 이하였음 고기도 부실하고, 번역:

 99%|█████████▉| 22252/22421 [11:59<01:20,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 차돌쌀국수 국물맛 미쳤음여 그리고 생각보다 고기 많아서 놀랏음, 번역:

 99%|█████████▉| 22255/22421 [12:00<00:49,  3.39it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: "비교적 저렴한 가격으로 고급 오마카세를 즐길수있는 식당"유명한 오마카세집은 많이 비싸고 항상 풀북킹이기 때문에 쉽게 접하지못하지만 이곳은 유명한 식당의 1/4 가격으로 비슷한 느낌의 오마카세를 맛볼수있는것이 큰장점입니다. 음식 하나하나 섬세한 디테일들이 있어 정성을 맛볼수있고 다찌에서 식사를 하시면 세프님의 친절한 설명이 맛을 더해주는것 같네요.근처에 방송국이 있어서 그런지 연예인들 자주 볼수있을만큼 지역에서 나름 인지도 있는 식당입니다.주차장은 따로 없기때문에 근처 목동공영주차장을 이용하셔야 합니다., 번역:

 99%|█████████▉| 22256/22421 [12:00<00:53,  3.08it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 회사에서 사준다고 해서 먹어본 오마카세. 10명정도 단체로 가서 그런지 음식들이 늦게 나왔고, 같은 접시인데 구성이 몇 개 빠져있기도 했다(물론 말씀드리면 다시 가져다 주시긴함) 참치가 아주 미쳤음 아주 존맛임., 번역:

 99%|█████████▉| 22258/22421 [12:01<00:52,  3.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 식당 앞에 주차 한 대 가능. 매운돈가스가 유명한데 매운돈가스는 눈물 쏙 나올 정도로 매워서 매운걸 못먹는 사람에겐 비추! 양념돈가스는 맛있게 맵고 소스를 따로 달라고 하는게 좋음! 돈가스 튀김옷은 쏘쏘. 사진은 곱배기 시켰는데 세덩이나 나옴 ㅎ 가성비 좋고 4시쯤 가니까 손님이 별로 없어서 좋았어요, 번역:

 99%|█████████▉| 22259/22421 [12:01<01:00,  2.69it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기본돈까스는 기본에 충실한 맛이었습니다. 정말 맛있는 돈까스! 그렇지만 생각보다 금방 눅눅해져서 빨리 먹어야 좋을 것 같아요. 하지만 가격이 6500원이니 만족! 매운돈까스(디진다돈까스)는 나름 매운거 잘 먹는다고해서 시도해봤는네 조각도 3조각이나 나오고(ㅠㅠ 가격은 2만원) 식도부터 따갑고 속쓰려서 화장실에만 있었습니당... 공복X 우유500ml 필수이지만 별 소용 없었고ㅠㅠ 드시기 전후에 꼭 위장 보호제 필수..! 꿀차가 속 진정에 더 좋더라구요, 번역:

 99%|█████████▉| 22260/22421 [12:02<01:07,  2.40it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 매체에 저주 나오는 돈까스집. 도전하기 위해 방문하는 것 외에 식사를 위해 갈만한 곳은 아니다 싳다 ㅠ 너무 느끼함, 번역:

 99%|█████████▉| 22261/22421 [12:03<01:13,  2.17it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 양이 엄청 많아서 가성비 좋아요. 맛있구요. 먹을만 했습니다., 번역:

 99%|█████████▉| 22262/22421 [12:03<01:15,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 줄서서 기다려서 먹은 맛집이에요~ 돈가스가 너무 바삭바삭하고 양념도 맛있어요! 디진다 돈가스를 맛보기로 하나씩 주시는데, 조금 잘라먹었다가 매워죽는줄 알았어요 ㅠㅠㅋㅋ, 번역:

 99%|█████████▉| 22263/22421 [12:04<01:21,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 싸구려 돈까스 맛이다 다만 저렴한 가격에 양많은 돈까스를 원한다면 추천. 그냥 대왕돈까스나 디진다 돈까스 시간 내에 먹는 사람들 구경하러 갈만한 곳.. 깍두기 항아리 비위생적, 온갖 손님들 침 튀었을 듯한 느낌, 번역:

 99%|█████████▉| 22264/22421 [12:04<01:21,  1.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 대왕돈까스와 디진다돈까스로 유명한 온정돈까스다. 이 두가지 명물을 제외하고도 상당히 괜찮은 집이다. 돈까스 자체가 꽤 맛있고, 양도 많은데 가격도 착하다. 기본적인 돈까스를 시키면 돈까스 2개에 6천원인데 천원 더 내고 곱배기 시키면 3개가 나온다. 사장님과 직원분들도 친절하고 좋았다., 번역:

 99%|█████████▉| 22265/22421 [12:05<01:23,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛과 가성비 좋아용 매운거 못드시는 분은 매운돈까스 드시지마세요, 번역:

 99%|█████████▉| 22266/22421 [12:05<01:29,  1.74it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 매운돈까스 등으로 아주 유명한 집이라서 그런지 2시에 가도 대기줄이 있었습니다. 주차공간은... 가게앞 딱 한자리니 차가 있다면 주변 빈곳을 잘 공략하셔야 합니다.돈까스 양은 밥을 포함해서 무지 많이 나옵니다. 매운 돈까스를 만드는 집이라서 그런건지 소스에서 은은하게 매운맛이 나는 느낌이었습니다. 소스는 맛있는 편이지만 맛이 너무 강해서 치즈향이나 맛 자체가 묻혀 치즈돈까스에는 살짝 안어울리는 소스가 아닐까 생각이 들었습니다.이 가게에서 치즈돈까스를 시키는 것은 디진다를 먹으면서 나죽네를 외치는 사람들과 곱빼기 시키고 배터져 죽는다는 사람들 옆에서 적당히 배부른 식사를 하며 여유로움을 즐기는 것이 아닐까 생각합니다., 번역:

 99%|█████████▉| 22267/22421 [12:06<01:24,  1.82it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 전형적인 sns가만들어낸 맛집.옛날경양식돈가스 와 돈카츠의  가운데에서 맴도는 고기두께와 부어진소스탓에 금방눅눅해버리는 튀김옷, 호불호 가리겠지만 테이블 앞에올려져서 약간은 비위생 적일수있는 항아리 김치와 깍두기 여러모로 아쉬운 곳. 가게안에서 무모한도전하는 테이블이 한테이블씩은있으니 구경하는기분으로 먹으러가는것도..., 번역:

 99%|█████████▉| 22268/22421 [12:06<01:17,  1.97it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기본 돈가스자체는 어딜가나 흔히 먹을 수 있는 맛. 튀김, 고기는 특별한 것이 전혀 없다.그래도 양념돈가스에 들어가는 소스와 돈가스의 조화는 나쁘지 않은정도?, 번역:

 99%|█████████▉| 22269/22421 [12:07<01:17,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 위생은 깨끗하고 서비스는 친절했습니다. 모듬 곱빼기로 먹었는데  생선 치킨까스는 적당한 맛이었고 돈까스는 꽤 맛있었네요. 무엇보다 저렴한 가격이 좋았습니다., 번역:

 99%|█████████▉| 22271/22421 [12:07<00:56,  2.64it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 아주 오래된 생고기 집입니다. 대부분 삼겹살을 드시는데 아주 고소하니 맛있어요 김치도 묵은지라서 구워드시면 굉장히 맛있습니다. 가게밖에 간이테이블을 설치해서 날좋은 날 드시면 나름 운치도 있습니다. 실내는 좌식인데 바닥에 기름기가 많아 미끌거리면서 느낌이 별루에요 위생상태가 좋지는 않아요. 아무래도 오래된 집이고 24시간 영업을 하다보니 그런듯 합니다. 점심시간에만 파는 제육볶음과 김치찌개가 예술이라고 하는데 전 아직 먹어보진 못했네요~ 삼겹살만큼은 여타 프렌차이즈 숙성삼겹살보다 훨씬 훌륭하니 한번쯤 방문해보시는것도 좋을듯 합니다. 단! 실내외 에어컨이 없고 선풍기로만 냉방을 하니 굉장히 더워요~ 시원한 날 가세요 그리고 주차도 외부에 몇대 안되구요 지하주차장으로 엘베타고 내려가야해서 번잡스럽습니다! 감안하세요~, 번역:

 99%|█████████▉| 22272/22421 [12:08<01:06,  2.25it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 반려견때문에 고민했는데 전화로 문의하니 야외좌석에 반려견과 식사가능한자리로 마련해주셨습니다., 번역:

 99%|█████████▉| 22273/22421 [12:09<01:09,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고기 질은 매우 훌륭오래 된 가게다 보니 기름떼로 인한 조금의 찝찝함은 있음, 번역:

 99%|█████████▉| 22274/22421 [12:09<01:18,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 건강한 맛이라 좋았고, 먹은 후에도 뭔가 깔끔하게 먹은 느낌이라 좋았어요! 김치찌개도 맛있었고, 직원분들이 친절하게 설명해주셔서 좋았어요!, 번역:

 99%|█████████▉| 22275/22421 [12:10<01:25,  1.71it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 야채를 따로 추가해야되는지 몰라서 숙주랑만 먹었네욤 고기는 나쁘지않아요, 번역:

 99%|█████████▉| 22276/22421 [12:10<01:17,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 1. 서비스 좋음2. 위생상태 좋음3. 오래 기다려도 되지 않음4. 색다른 맛5. 주차 불가 절대 불가6. 가성비 좋음7. 맛도 좋음맛은 가격대비 아주 좋다고 평하고 싶음. 자주 가고 싶은 맛은 아님.맛이 없다는 것이 아니라 밋밋한 편백찜 특유의 자극적이지 않은 맛 때문이라고 말하고 싶음., 번역:

 99%|█████████▉| 22277/22421 [12:11<01:19,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔하고 맛있었어요. 남녀노소 좋아할 메뉴입니다. 다 먹어도 느끼하지 않았고 건강한 맛이라 좋았어요. 재방문의사 있어요., 번역:

 99%|█████████▉| 22278/22421 [12:11<01:11,  2.00it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식 맛이 깔끔하고 가게 내부도 꽤 커서 여러명이 와도 좋을듯싶어요. 이곳은 감자탕도 맛있지만 뼈해장국도 꽤 괜찮아요!, 번역:

 99%|█████████▉| 22279/22421 [12:12<01:10,  2.03it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식이 맛있음. 뼈는 2개 넣어줌다먹고 아이스크림은 초코맛이 없어서 아쉬움, 번역:

 99%|█████████▉| 22281/22421 [12:12<00:49,  2.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 뼈 두개줌맛있고 친절함다 먹고 아이스크림도 후식으로 먹을 수 있어서 짱 좋음, 번역:

 99%|█████████▉| 22282/22421 [12:13<00:49,  2.83it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있고 가성비좋은집! 먹을만한 식당이 별로없는 이 지역에서 롱런할 자격은 충분한듯, 번역:

 99%|█████████▉| 22283/22421 [12:13<00:48,  2.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 밖에서부터 냄새가 엄청좋아요 맛있어요, 번역:

 99%|█████████▉| 22284/22421 [12:13<00:52,  2.59it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 애정하는곳이에요 맛도좋고 가성비좋습니다곧 이전하는데 새로운곳도 기대되어요, 번역:

 99%|█████████▉| 22285/22421 [12:14<00:59,  2.30it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 오마카세입니다. 미들급인데도 가성비 좋고 정말 강추합니다~~^^ 재방문의사 100%%, 번역:

 99%|█████████▉| 22286/22421 [12:15<01:06,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가성비 좋고 맛있어요! 군더더기없이 깔끔해요. 설명도 해주셔서 좋았어요!, 번역:

 99%|█████████▉| 22287/22421 [12:15<01:02,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 학생이 기념일에 가기 좋은 느낌인 것 같아요! 정말 맛있고 분위기도 조용 깔끔해서 좋았습니다, 번역:

 99%|█████████▉| 22288/22421 [12:15<01:00,  2.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 단언컨대 서울에서 손 꼽히는 가성비의 오마카세집이라고 말할 수 있습니다. 타 오마카세와 비교해 가격은 매우 싸지만 퀄리티는 크게 뒤지지 않습니다. 메뉴에 대한 좋은 설명은 물론 손님의 요청에 매우 잘 응답하시고 재방문 시 바로 얼굴을 알아보시는등 서비스적인 측면에서도 매우 만족했습니다. 가격을 떠나서도 추천해드릴 수 있고 가격 고려 시, 한 번쯤은 방문해보시길 바랍니다., 번역:

 99%|█████████▉| 22289/22421 [12:16<00:56,  2.34it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 점심 오마카세 가성비 너무 좋았습니다제가 데려간 사람들은 모두 너무 괜찮다고 따로 친구들 데려 간다고 했습니다. 관악구에서 스시초밥집 이만한 데 없습니다., 번역:

 99%|█████████▉| 22290/22421 [12:16<00:58,  2.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 도저히 이가격이라 볼수없음. 미들급스시 말도안됨.. 재료들이 신선한느낌이 전혀없고 몇몇생선 비려서 먹기가힘들정도.. 비린거 잘먹는대도, 번역:

 99%|█████████▉| 22291/22421 [12:17<01:04,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가성비로는 최고급 아닐까?, 번역:

 99%|█████████▉| 22292/22421 [12:17<01:06,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가성비 좋은 스시야하지만 매우 시끄럽다, 번역:

 99%|█████████▉| 22293/22421 [12:18<01:05,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 서울 도심속에서 싱싱한 랍스터, 킹크렙, 대게를 드시고싶을때 고민하지말고 대운정으로 고고. 수년간 최고의 생물을 직접 선별하여 받아오기때문에 좋은 재료를 적당한 가격에 맛볼수있는 곳입니다. 오픈 주방으로 청결함은 보장되있습니다., 번역:

 99%|█████████▉| 22295/22421 [12:18<00:48,  2.58it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 그냥 평범한 버섯칼국수 맛입니다 얼큰하지 않은 맛이며 겉절이도 그냥 특색 있지 않은 평범한 맛이었습니다  동네 가까운 곳에 있는 등촌 샤부샤부 칼국수(프랜차이즈)가 더 괜찮을 수 있다는 개인적인 생각입니다, 번역:

 99%|█████████▉| 22296/22421 [12:19<00:51,  2.44it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 얼큰한 맛이어서 만족했고, 특히 볶음밥이 맛있어요. 메뉴도 빨리 나와요., 번역:

 99%|█████████▉| 22297/22421 [12:19<00:53,  2.33it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 몇년동안 꾸준히 가는 맛집이전하고 더 깔끔해진듯볶음밥 필수, 번역:

 99%|█████████▉| 22298/22421 [12:20<00:57,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 보통의 식당이에요~공항 근처라 공항 손님이 많은듯해요.맛도 괜찮고 저렴해서공항 안의 푸드코트들보단 나은 것 같아요., 번역:

 99%|█████████▉| 22299/22421 [12:21<01:03,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 겉절이가 맛나고 내장칼국수 버섯칼국수 둘다 맛나요김포공항 근무일 때 퇴근 후 종종 가는 곳인데 칼국수 다음엔 꼭 볶음밥 필수 입니다, 번역:

 99%|█████████▉| 22300/22421 [12:21<01:04,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 넓은 지하로 이전한 공항칼국수. 등촌칼국수가 이곳을 따라한솟이라고 하는데.. 좀 짜지만 맛이좋다., 번역:

 99%|█████████▉| 22301/22421 [12:22<01:09,  1.72it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 별점을 줄 수 없는 곳 오히려 마이너스인 곳사장이 완전 불친절한 곳 이다.주말에 먹으러 갔다가 2층으로 올라가라해서 올라갔더니 계단 끝에서 사장이 다리 한쪽 박스에 올려놓고 술처먹은 목소리와 말투로 고개 까딱까딱 거리면서 말로만 자리 안내하는데....사장이란 남자가지말 못알아 듣는다고 짜증내는 신비스러운 곳 맛도 별루고 조미료 맛만 나는 신비스러운 곳임 두번다시 가고 싶지 않고!주변인들에게도 다 이야기 하고 다니는 중!!절대 가지 말라고!!!!불친절함과 조미료의 맛을 원하신다면 가세요~ㅋ, 번역:

 99%|█████████▉| 22302/22421 [12:22<01:04,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 조금 옆으로 자리를 옮겼고 주차는 1시간 무료. 양이 많이 줄었다는 느낌은 받았지만 맛은 여전합니다. 가게를 옮기면서 더 깔끔해졌네요., 번역:

 99%|█████████▉| 22303/22421 [12:23<01:04,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 강서구 나고 자란 입장에서 말씀드리면 저는 공항칼국수가 등촌칼국수를 배낀걸로 알고있는데 아닐수도 있으니 이건 넘어가고 지역 주민들은 등마루놀이터에 있는 등칼을 가지 공칼은 안갑니다;전 다이닝코드 첨 알았을때 등칼먼저 검색해봤는데 매일같이 사람 미어터져서 밥 시간때면 항상 기다리는곳이 평가도 없고 그러길래 의아했습니다ㅋㅋ공칼이 방송에 나오고나서 지인들이 강서구 맛집하면 공칼 아니냐고 말을 꺼내던데 아이러니 하네요 허허공칼이나 등칼이나 주차 불편한건 똑같으니 감안하세용ㅎㅎ, 번역:

 99%|█████████▉| 22304/22421 [12:23<01:02,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기계식 주차 및 RV를 위한 지상 주차장 보유. 식당은 지하1층에 있으며 넓은 공간에 테이블 많음. 8천원에 이정도면 돈 아깝다는 생각은 안드네요, 번역:

 99%|█████████▉| 22305/22421 [12:24<01:04,  1.81it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 명성도 10년전에 떨어졌음 다시가보니 서비스 완전 손님한테 갑질하는 듯 행동함 암만 맛이 좋아도 이딴 행동 보이는데 어떤 손님이 가려고 하겠음 맛집찾는 손님은 떠났으니 홍보 계속해서 새로운 손님들이나 맞이하세요, 번역:

 99%|█████████▉| 22306/22421 [12:25<01:09,  1.66it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 허름한집. 허나 유명세를 많이 탄 곳. 그렇게 맛있는지는 모르겠다. 볶음밥은 그래도 쪼금~괜찮았지만.. 기대치에 못미치는 집., 번역:

 99%|█████████▉| 22307/22421 [12:25<01:10,  1.63it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 집 앞에 있어서 어릴 적 부터 먹었는데 진짜 맛있어요 버섯칼국수 볶음밥 일인분씩 사이좋고 먹으면 진리 ! 가격도 저렴하고 맛도 좋은데 백종원의 3대천왕 나온 후로 갑자기 사람이 넘 많아져서 못가고있다능 ㅠㅅㅠ 주차공간도 넉넉하게 있어요 !, 번역:

 99%|█████████▉| 22308/22421 [12:26<01:07,  1.69it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 백종원 나왔을때도 양적고 불친절하고 맛없고 비싸다고 나왔는데 뭘 믿고 가는건지 모르겠다., 번역:

100%|█████████▉| 22309/22421 [12:26<01:05,  1.71it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 유명하지만 평범한 칼국수입니다. 2번은 안 갈 것 같아요.먹고 속이 안 좋았어요 ㅠㅠ 둘다..., 번역:

100%|█████████▉| 22310/22421 [12:27<00:59,  1.86it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 유명하대서 찾아가서 먹어봤는데 버섯냄새도 냄새도 심하고, 개인적으로는 별로였음., 번역:

100%|█████████▉| 22311/22421 [12:27<00:56,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 불친절함. 칼국수치고 비싼 가격. 맛없음. 유명세만 남은 껍데기., 번역:

100%|█████████▉| 22312/22421 [12:28<00:51,  2.12it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 평점에 비해서 맛도 그런데일하는 아주머니 잘못걸리면 완전불친절, 번역:

100%|█████████▉| 22313/22421 [12:28<00:50,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주차장 협소서비스 엉망칼국수 평범볶음밥 평범그냥 그래요, 번역:

100%|█████████▉| 22317/22421 [12:29<00:26,  3.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기대하지 마요. 그냥 분식집 같아요 .아주머니들이 너무 조선족이신지 쎄요, 번역:

100%|█████████▉| 22320/22421 [12:29<00:22,  4.45it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 일반돈까스 자체도 맛있음 튀김가루가 바삭함냉면은 그냥저냥디진다는 디짐..., 번역:

100%|█████████▉| 22321/22421 [12:30<00:25,  3.92it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 동네에 있어서 가끔 가는데 저렴한가격에 양도 괜찮아요. 디진다, 대왕 같은 도전메뉴 말고 돈가스 먹으러 멀리서오는건 비추식사시간에가면 엄청기다려야함, 번역:

100%|█████████▉| 22322/22421 [12:30<00:27,  3.62it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 고구마치즈돈까스는 인간적으로 너무 느끼했다... 디진다돈까스로 유명한데 시식을 권하셔서 한입을 먹었다가 죽을 고비를 넘겼다., 번역:

100%|█████████▉| 22323/22421 [12:30<00:31,  3.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분명 맛은 있는데....ㅠㅜ양도 많고요. 근데 느끼해서 다 못먹어요ㅜ, 번역:

100%|█████████▉| 22325/22421 [12:31<00:25,  3.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 어릴때 먹었던기억이 예전엔 저렴한데 맛있는 느낌인데 지금은 저렴한것 같지는 않음ㅋㅋ물론 맛은 그냥그럼, 번역:

100%|█████████▉| 22326/22421 [12:31<00:29,  3.25it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 가격 대비 돈까스는 크다. 맛은 동네 분식과 같다. 매운돈까스는 죽도록 맵다. 그러나 비빔냉면은 엄청나게 맛없다. 일부러 맛없게 해도 이것 보단 낫겠다. 뭘 빼먹으셨나...  총점 : 내 생각엔 궂이 맛보러 찾아가기엔 NG다., 번역:

100%|█████████▉| 22327/22421 [12:32<00:33,  2.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 정말 매워요 ㅜㅜ, 번역:

100%|█████████▉| 22328/22421 [12:32<00:39,  2.33it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있습니다. 양이 엄청 많습니다. 사장님이 너무너무 친절하십니다. 매운돈까스는 도전하다 죽을 수도 있습니다., 번역:

100%|█████████▉| 22329/22421 [12:33<00:42,  2.15it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있어요. 굳이 유명한 디진다돈까스 같은 것을 도전하지 않더라도 모든 메뉴가 맛있어요., 번역:

100%|█████████▉| 22330/22421 [12:33<00:40,  2.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛도 있고 양도 많고 좋네요, 번역:

100%|█████████▉| 22337/22421 [12:34<00:13,  6.45it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 주변 유명돈까스집 문닫아서 찾아간건데 그 돈까스집들 닫길 잘했다며 좋아할정도로 맛있었어요ㅜㅜ오로시까스는 무랑 같이 먹는 촉촉한맛이 일품이고 로스까스는 겨자랑 달달돈까스소스랑 먹으니 진짜진짜 너무맛있더라구요!!!!!!제거 돈까스 잘 안먹는데 남자친구가 좋아해서 따라갔는데...앞으론 제가 더 많이갈듯합니다 이집에서 돈까스에 반해습니다, 번역:

100%|█████████▉| 22338/22421 [12:34<00:16,  4.97it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 오로시까스라는 특이한 메뉴가 있습니다. 처음보는 메뉴여서 시켜먹어봤는데 나쁘지 않더군요. 그렇다고 해서 다시 생각날 것 같지는 않습니다., 번역:

100%|█████████▉| 22339/22421 [12:35<00:20,  3.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 노량진 돈까스집이 망했다면 솔직히 여기때문이다가격도 싼데 맛도 좋아 양도 많구.. 뭐 일식 돈까스를 싫어하는 사람도 있긴 있겠다만 솔직히.. 넘볼 수가 없는듯, 번역:

100%|█████████▉| 22340/22421 [12:35<00:23,  3.44it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 노량진에서 그나마 사람다운 음식 노량진에서 뭘 먹어야된다면 컵밥같은거 주서먹지말고 여기 돈가스 드시길. 고기도 두툼하고 가격도 짱착함, 번역:

100%|█████████▉| 22341/22421 [12:36<00:26,  3.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이든 돈카츠와 비교우위를 가리기 힘든 곳. 이곳의 특징은 느끼한 맛을 잡아주는 매운소스 ,조금 강한 밑간, 두툼한 두께 메뉴중 개인적  추천은 로스까스. 회전율도빠른편인데 굳이 단점을 뽑자면 가게가 좁은 곳에 많은 인원을 수용하다보니 복잡한게 흠., 번역:

100%|█████████▉| 22342/22421 [12:36<00:31,  2.53it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 허수아비는 매번가도 질리지않는다. 깔끔한 샐러드, 국, 밥 과 어울리는 이 가격으로는 불가능항것같은 퀄리티의 돈까스가 나를 반긴다., 번역:

100%|█████████▉| 22345/22421 [12:37<00:23,  3.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 숭실대앞에 유일한 큰 카페이네요자몽허니블랙티 맛잇어요, 번역:

100%|█████████▉| 22346/22421 [12:38<00:28,  2.61it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 스타벅스 리코타 멜팅치즈 케이크..지금까지 먹은 스벅 케이크 중에 제일 맛있다꼭 먹어보길 바랍니다...ㅠㅠ치즈케이크 좋아하는 분들한테 적극추천, 번역:

100%|█████████▉| 22347/22421 [12:38<00:33,  2.23it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 스타벅스니 역시 깨끗하고 친절해요 아메리카노 맛있는데 말 더 할 게 없네요 집앞이라 자주가요, 번역:

100%|█████████▉| 22348/22421 [12:39<00:34,  2.12it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 리뉴얼후 공간이넓어졌고 소소한 분위기와 다양한 커피종류가 괜찮다 근처에 스타벅스가 꽉차서 와봤는데 조용하고 무척 만족~~, 번역:

100%|█████████▉| 22349/22421 [12:40<00:36,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 라떼 엄청 고소해요. 친구들도 커피가 맛있다고 칭찬했어요! 케익도 촉촉하고 당근이 많이 들어서 맛있었어요!, 번역:

100%|█████████▉| 22350/22421 [12:40<00:37,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 서울에서 보기 생소한 다슬기 해장국인데 오랜만에 시원하게 먹었습니다. 주변에 술집이 많아서 해장하시는 분들이 많이 오실 것 같습니다🥄, 번역:

100%|█████████▉| 22351/22421 [12:41<00:35,  1.98it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 남자친구랑 술먹고 다음날 거의 여기서 해장하는데 다슬기칼국수 국물 대박이에요ㅠㅠ 글구 다슬기냉면도 꼭 먹어보세여!!, 번역:

100%|█████████▉| 22352/22421 [12:41<00:35,  1.93it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 해장으로도 술안주로도 탁월한 메뉴들입니다. 칼칼한 다슬기 해장국이 대표 메뉴., 번역:

100%|█████████▉| 22353/22421 [12:42<00:36,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 인생 햄버거, 우선 번이 정말 맛있고 패티가 두툼하고 육즙이 살아 있습니다. 야채나 토마토도 신선하고 마요네즈 소스와 나머지재료가 조화롭습니다., 번역:

100%|█████████▉| 22354/22421 [12:42<00:33,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있다 짱맛있다또간다 치즈버거 하와이안버거 좔좔스프 샐러드 준다, 번역:

100%|█████████▉| 22355/22421 [12:43<00:35,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 1회 방문. 패티에서 고기 비린내가 안나는 깔끔한 수제 버거였다., 번역:

100%|█████████▉| 22356/22421 [12:43<00:36,  1.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 얇은 크러스트의 큼지막한 피자가 나와요. 피자맛은 그저 그런데 레드락 생맥이 맛있어요!, 번역:

100%|█████████▉| 22357/22421 [12:44<00:31,  2.01it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 안암의 분위기있는 피맥집입니다. 맥주 종류도 다양하게있어서 좋습니다., 번역:

100%|█████████▉| 22358/22421 [12:44<00:29,  2.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있고 내부도 넓은 편입니다:-) 상추 셀프 리필가능한게 좋았어요ㅋㅋㅋㅋㅋ, 번역:

100%|█████████▉| 22359/22421 [12:45<00:29,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 골고루 다양한 반찬에 저렴한 가격과 맛이 한끼 해결에 아주 탁월해요1인석 2인석 4인석등 다양 사진은 뚝불된장백반.아주 보글보글 뚝배기 안에 두툼한 두부, 나머지 재료도 푸욱 익혀서 나옴. 고춧가루 조금 포함됨, 번역:

100%|█████████▉| 22360/22421 [12:45<00:27,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔하고 알맞은양으로 나오는 식사된장찌개보단 제육이 낫고 두루치기추천평이 많다, 번역:

100%|█████████▉| 22361/22421 [12:46<00:30,  1.97it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 음식이 대단히 맛있는 것은 아니다. 그러나 내가 이 가게 만족하는 이유는 다음과 같다. 1. 기존의 백반집과 달리 깔끔하다. 2. 가격이 합리적이다. 3. 서빙하는 분들의 서비스가 좋다. 실수로 상에 막걸리 쏟았는데 부탁을 하기 전에 먼저 와서 처리를 해주었음. 연신내에 식당은 많지만 갈만한 곳은 없다. 고만고만한 음식 내지는 특색도 없고 그냥 잡다한 퓨전 음식 또는 인테리어빨로 밀고 나가는 편이 많은 요즘인데 이 가게는 무난하면서 가격도 좋다. 다시갈 용의가 있다., 번역:

100%|█████████▉| 22362/22421 [12:46<00:27,  2.16it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 저렴하고 푸짐하고 맛있어요. 반찬 구성도 많고 고기도 양 많아요. 밥 다먹고도 고기가 좀 남을 지경이에요., 번역:

100%|█████████▉| 22363/22421 [12:46<00:25,  2.25it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 특제 소스가 맛있습니다. 밑반찬이 탄탄해서 좋습니다. 직원이 친절합니다., 번역:

100%|█████████▉| 22364/22421 [12:47<00:27,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 식당 분위기는 단정하고 차분했습니다. 백반은 한 끼 식사로는 양도 괜찮고 구성도 좋았습니다. 고기와 반찬이 모두 맛있었고, 특히 미역국이 좋았습니다., 번역:

100%|█████████▉| 22365/22421 [12:47<00:26,  2.11it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맨날 혼자 밥먹기 힘들었는데 ;;;; 눈치 안보고 혼자먹기 좋은곳을 발견 ㅋㅋ 근데 내가 먹은건 뚝불 + 된장찌개 였는데 ;; 신기한 맛임 ㅋ 중독성있음 ㅋ, 번역:

100%|█████████▉| 22366/22421 [12:48<00:25,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 최근 가본 밥집중 최고 편하게 즐길 수있어 좋았어요, 번역:

100%|█████████▉| 22367/22421 [12:48<00:24,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깔끔한밥집 좋아요, 번역:

100%|█████████▉| 22368/22421 [12:49<00:23,  2.24it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: #삼전동 #이자카야 #부엌일본 요리와 술을 파는곳 주점이라고 표현하기엔기본적인 메뉴도 있지만 매일매일 메뉴가 바뀐다.사장님 혼자 ㄷ자 형태의 다찌 안에서 요리도 하시고 서빙하신다. 모듬회를 시켰는데 플레이팅 하시는 모습에 놀라고 회 위에 추가로 올려주시는 재료에 놀랐다. 캐비어, 연어알이 올라가고 우니가 모듬회의 구성이라니 !!! 제가 남는게 있으시냐고 물어볼정도 회의 신선함뿐만 아니라 숙성도 역시 좋았다. 간만에 좋은 집을 찾았다. 아싸!!, 번역:

100%|█████████▉| 22369/22421 [12:49<00:23,  2.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 정말 개인적으로 강력추천하는 캐주얼느낌의 일본식 오마카세 식 제패니스 PUB입니다..기본적으로 준비된 안주 종류도 있지만, 그날그날 정해둔 요리들도 너무 좋습니다...일단 일반 이자카야식 안주들과는 다릅니다.그런 일본식 이자카야를 생각하고 가시면 당연히 제가 쓰고 있는 이 글을 욕하실거구요~일본식 안주 종류들을 캐주얼하게 재해석한 요리들입니다.주방장님이 아주 센스가 좋으십니다...예를들어... 토마토 나베같은 경우에 매컴한 해물나베 같지만, 먹어보면 토마토와 야채의 신선함이 단순히 매운 맛을 상큼하게 만드는 느낌과 맛을 보여주신답니다...솔직히 사장님 나이를 개인적으로 알고는 있지만... 젊은 친구들 입맛과 나이가 좀 있으신 분들 감각에 모두 어울립니다..다시한번 얘기하지만, 전통 오마카세나 이자카야 생각하시면 안되구요.~~삼전동에 오시면 꼭꼭꼭 한번 들려보실 수 있으면 좋겠습니다...정말 강추하는 제 개인적으로 숨겨진 맛집입니다~, 번역:

100%|█████████▉| 22370/22421 [12:50<00:22,  2.32it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: *재방문의사80%​덕수궁에 가신다면 하나쯤은 드셔보시길 추천.​덕수궁 돌담길 초입에 위치해 있는 생활의달인 서울3대 간식 선정된 덕수궁에 왔다면 한번은 먹어봐야하는 광화문맛집 덕수궁 리에제와플​매일 반죽하고 숙성하는 생지에 주문 즉시 구워주는 와플 거기에 좋은 재료의 토핑까지 맛과 식감 그리고 건강까지 챙겨주는 맛있는 간식.​블루베리크림치즈, 벨지운초코가 특히나 맛있었음.​"덕수궁에 가보면 꼭 한 번 먹어봐야 할 간식 리에제와플", 번역:

100%|█████████▉| 22371/22421 [12:50<00:20,  2.42it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 덕수궁 돌담길 초입에 있는 테이크아웃 전문 와플집으로 이동내 터줏대감 와플집이다.고급스러운 와플집으로 서울에서 제일 유명했던 집인데 거의 10년만에 방문했지만 여전히 늦은 시간까지 문전성시를 이루고 있다.와플 반죽 쫀득하면서 겉은 바삭하여 식감도 좋고 시나몬슈가가 녹아서 와플 겉표면을 반짝거리게 만들어 준다.달지 않은 와플을 좋아하는 사람들에게 추천한다.아 커피는 맛있는 곳에서 사서 함께 먹는게 좋을 것이다.콜드브루 따뜻하게 먹었더니 니맛도 내맛도 아니였다., 번역:

100%|█████████▉| 22372/22421 [12:51<00:23,  2.09it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 테이크아웃전문!! 와플하나 먹고 반해서 박스로 포장!! 집에와서 먹어도 맛있네요~~생크림딸기!!요거 완전 강추!!!, 번역:

100%|█████████▉| 22373/22421 [12:51<00:22,  2.13it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 두꺼운 와플과 달콤한 메이플 시럽이 잘 어울리메요. 많이 기다려야하는건 함정, 번역:

100%|█████████▉| 22374/22421 [12:52<00:22,  2.06it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 덕수궁 바로 옆 와플맛집. 와플은 평범하게 맛있습니다. 웨이팅 15분 이상 기다릴 만한 곳은 아니니 줄 없을 때 이용하세요., 번역:

100%|█████████▉| 22375/22421 [12:52<00:22,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 길거리 음식 치고 퀄리티 괜찮은 곳. 덕수궁 들어가기전에 허기 달래기 좋다!겉바속촉 최고! + 개인적으로 생크림 토핑은 느끼했어요😥, 번역:

100%|█████████▉| 22376/22421 [12:53<00:23,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 시청근처 맛집이라고 얘기 들음. 맛있긴 하지만 뭔가 더 특별한 느낌은 잘 모르겠음. 하지만 간식먹고 싶을 때 재방문할 의사있음, 번역:

100%|█████████▉| 22377/22421 [12:53<00:21,  2.05it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 블루베리 와플도 맛있고 초코 와플은 약간 뻑뻑하긴 한데 많이 달지 않고 맛있어요. 무조건 테이크아웃이라 그 자리에서 서서 먹는 사람도 많아요. 커피는 소소.., 번역:

100%|█████████▉| 22378/22421 [12:54<00:22,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 덕수궁 바로 옆에 언제나 사람들이 끊이지않는 와플집입니다. 쌀쌀한 날씨에 커피와함께 하는 따뜻한 와플맛 좋네요!, 번역:

100%|█████████▉| 22379/22421 [12:54<00:23,  1.78it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 딱딱하고 느끼함. 딸기 먹기도 불편하고 무엇보다 가격이 비쌈, 번역:

100%|█████████▉| 22380/22421 [12:55<00:21,  1.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 덕수궁근처 맛집을 검색해서 찾아간 곳.기대가 컸던 탓인지 가격에 비해 맛있지 않았음. 디저트라는 특성상 다소 높은 가격을 받는다고 해도 테이크아웃을 해야한다는 점에서 줄까지 서서 꼭 먹어야할 음식은 아니라고 생각함., 번역:

100%|█████████▉| 22381/22421 [12:55<00:21,  1.89it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛있어요. 초코코팅이 양면으로 되어있어요. 덕수궁 갈 때 들릴 만해요., 번역:

100%|█████████▉| 22382/22421 [12:56<00:21,  1.82it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 생활의 달인 서울3대 맛집. 덕수궁 바로 옆에 위치해있다. 웨이팅이 있는 편이다., 번역:

100%|█████████▉| 22383/22421 [12:56<00:18,  2.02it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 초코와플은 초코가 진하다보니 와플맛을 잘 못느껴서 아쉬웠어요 플레인추천!, 번역:

100%|█████████▉| 22384/22421 [12:57<00:17,  2.12it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 테이크아웃 전문점. 가격이 좀 비싸다는 생각이 들 수도 있지만 한 입 먹는 순간 수긍하게 되는 맛이다. 여기서 와플 사먹은 후 다른 곳에서는 와플을 먹지 못할 정도., 번역:

100%|█████████▉| 22385/22421 [12:57<00:16,  2.19it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛 좋음. 웨이팅..., 번역:

100%|█████████▉| 22387/22421 [12:58<00:12,  2.80it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 덕수궁 지나다가 사람들 많아서 줄서서 먹어봤는데 가격이 조금 비싼데 맛있어요, 번역:

100%|█████████▉| 22388/22421 [12:58<00:13,  2.47it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 먹어본 와플 중에 제일 맛있었음단점은 가격? 좀 비쌈, 번역:

100%|█████████▉| 22389/22421 [12:59<00:14,  2.21it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 먹골역근방에서 5년정도 일을 했었던 곳이라 묵동주변의 식당들을 거의 섭렵하고 있는데 이곳이 처음에는 지금 크기에 절반크기에 정말 작은 가게 였었는데 슬슬 소문나면서 옆집을 터서 사용하더군요.막 대단한 맛집까지는 아니지만 국물맛이 깔끔하면서도 깊은 맛이 납니다.한마디로 거의 누구나 불호가 없는 그런맛이고 칼국수면도 적당한 찰기로 손색이 없고, 만두는 예전에 할머니, 어머니가 만들어 주시던 가정식 만두 바로 그 맛입니다.처음에 조그만 그릇에 보리밥을 조금 주는데 열무김치 잘라서 넣고 참기름 넣고 고추장 넣어 비벼먹으면 요것도별미! 가게앞에 주차라인이 2개가 있으나 자리잡기 쉽지 않고 발렛도 따로 없어서 그냥 주차는 못한다 생각하는게 편할듯 합니다., 번역:

100%|█████████▉| 22390/22421 [12:59<00:13,  2.22it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: "황해칼국수" 서울시 중량구 묵동에 위치한 30년 전통의 칼국수 전문점. 깔금하고 깊이 있는 멸치베이스 육수를 기반으로 하고 있으며 숙성된 반죽으로 만든 식감 좋은 칼국수와 얇게 띄워 끓여 낸 수제비가 맛있는 집이다.또한 자체 빚어 만든 김치만두와 보리비빔밥도 취급한다. 여름에는 계절 한정으로 콩국수와 김치말이도 선보인다.이곳에서는 단순 각각의 메뉴만이 아닌 칼국수, 수제비, 만두를 조합해서 섞어 두가지 맛을 볼 수 있는 메뉴도 있다.겻들어 함께 먹을 수 있는 보리밥을 무상 제공하고 있으며 보리밥에 열무김치, 겉절이, 고추장, 참기름을 넣어 쓱쓱 비벼먹고 나서 주문한 메뉴를 먹고 나면 더이상 먹을 수 없을 정도로 푸짐한 한끼를 채울 수 있다.최근에는 신메뉴로 어탕국수를 새롭게 선보이고 있으며 개인적으로는 칼제비를 추천~영업시간은 항상 am 11:30 오픈해서 CLOSE 시간은 평일 am 02:00까지고 금요일과 토요일은 am 05:00 까지며 일요일은 22:00까지만 영업하니 참고하시길..., 번역:

100%|█████████▉| 22391/22421 [13:00<00:14,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 그냥 동네에있는 평범칼국수집처럼 보이지만 자극적이지않고 손맛이 느껴지는 이북식 칼국수맛집, 번역:

100%|█████████▉| 22392/22421 [13:00<00:14,  2.04it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 보통 동네 식당 / 생각보다 맛있고 양도 많음 / 김치가 진짜 맛있음 !!, 번역:

100%|█████████▉| 22393/22421 [13:01<00:13,  2.00it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 수유시장 입구에 평양냉면을 하는 음식점이 있다는 정보에 방문 곰탕 냉면 모두 착한가격 주인장은 이보다 진국이 없다며 자랑을 늘어놓는다 젊은부부가 살아가는 모습이 정겹다 냉면 면은 메밀이 아니라 함흥식 면이다 육수는 곰탕을 식혀 만든듯하다, 번역:

100%|█████████▉| 22394/22421 [13:01<00:13,  1.95it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 메뉴는 곰탕,냉면(비빔,물냉면) 2가지임1.곰탕 6000원(곱배기7000원) - 조미료 사용않는 맑은육수 - 국물 및 곁들여진 소고기는 명동 하동관 혹은 서초역 신선옥 곰탕과 견주어 손색없슴 - 전통시장골목 서민적 분위기의 국밥집2.평양식 물냉면 5000원(곱배기6000원) - 물냉면 육수에도 조미료 사용않는 육수를 사용하여 매우 단백함, 번역:

100%|█████████▉| 22395/22421 [13:02<00:13,  1.96it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛 친절 모두 최고, 번역:

100%|█████████▉| 22397/22421 [13:02<00:08,  2.68it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 제대로 된 분위기를 내는 이탈리안 코스를 드시고 싶으실 때 추천!여기 스테이크가 싸고 맛있어요~ 디너세트를 시키면 수프부터 식전빵~ 샐러드랑 본 메뉴, 그리고 와인이랑 디저트까지 쭉 코스요리가 나오는데 고풍스러운 가게 분위기랑 합해서 완전 고급진 기분 들구^^맛도 괜찮아요, 등심 스테이크가 개인적으론 입에서 녹습니다.. 하 또먹고싶다ㅠ.ㅠ, 번역:

100%|█████████▉| 22398/22421 [13:03<00:08,  2.68it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 좀 비싸긴 하지만 피자랑 파스타가 진짜 맛있어요. 까르보나라가 정통식이어서 살짝 짭짤한데 고소하고 계속 손이 가는 맛이에요. 그리고 프로슈토 피자 진짜 맛있음..!!, 번역:

100%|█████████▉| 22399/22421 [13:03<00:08,  2.69it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 정통 이탈리안 레스토랑을 보여주려는 노력이 엿보였어요.토핑이 간단하지만 고소하고 쫄깃한 도우와 치즈의 맛이 살아있어요. 화덕피자라 느끼함이 전혀 없어 한 판 다 비울 수 있었네요. 다만 할리피뇨만 주고 피클이 없어서 조금 아쉽.., 번역:

100%|█████████▉| 22400/22421 [13:04<00:08,  2.34it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 토르텔리 라구(라비올리) 정말 맛있음! 그리고 쫄깃한 화덕피자가 매우 훌륭한 집. 다만 음식이 너무 짜다... 전반적으로 다 짬., 번역:

100%|█████████▉| 22401/22421 [13:04<00:08,  2.25it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 이탈리아식 화덕 피자집으로 부라타피자위에 피자, 루꼴라, 프로슈토, 체리토마토 조합이 좋으나 가격이 비쌈 (3.5만원). 파스타는 별로라는 후기를 봤는데 정말로 피자대비 파스타는 별로였음., 번역:

100%|█████████▉| 22402/22421 [13:05<00:09,  2.05it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 분위기 좋아서 가족 기념일이나 데이트할 때 오기 매우 좋음. 정통 이태리의 맛을 내려고 노력하는 느낌 굳, 번역:

100%|█████████▉| 22403/22421 [13:05<00:09,  1.94it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 판체타와 치즈로 만든 정통 까르보나라를 맛볼 수 있는 리스토란테. 가격이 좀 있지만 맛이 보장됩니다. 다음엔 피자를 맛보고 싶어요., 번역:

100%|█████████▉| 22404/22421 [13:06<00:08,  2.05it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 여기서 소개팅 2번 했습니다. 어디서나 분위기 조용조용하고 인테리어도 적절하게 톤다운 되어있어서 서로에게 집중하기 좋더라구요. 음식은 피자, 파스타, 샐러드 다 먹어봤는데 피자, 샐러드 맛있습니다. 파스타는 면 알단테라도 하시는데 스파게티마다 다른건지 아니면 숙련도따라 다른건지 좀 편차가 있는 편입니다. 그 외에 서비스는 물 바로바로 가져다 주시고 좋았어요., 번역:

100%|█████████▉| 22405/22421 [13:06<00:08,  1.85it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 많이 추천받았던 합정-상수 맛집.따뜻한 분위기, 깔끔한 매장, 부드러운 서비스맛있는 T본 스테이크와 좋은 오일을 쓰는 "빠넬로"정말 재료에 충실한 요리를 한다.좋은 재료를 정갈하게 요리해 주셔서본질적인 맛을 느낄 수 있음!특히 봉골레의 경우, "유화"가 잘 돼있는데,기름과 면, 재료가 함께 살아 움직인다 ㅎㅎ게다가 1인 1메뉴 주문시 콜키지 무료에간단한 와인 핸들링까지.가격이 쪼금 비싸서 -1 별직장인 기념일 데이트 용으로 매우 추천, 번역:

100%|█████████▉| 22406/22421 [13:07<00:07,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 확실히 이전에 알던 까르보나라와는 다른 이탈리안 정통. 문제는 면의 삶기였다. 딱딱한 면의 식감에 아쉬움만이..., 번역:

100%|█████████▉| 22407/22421 [13:07<00:07,  1.79it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 일반적인 한국의 이탈리안 음식점과는 조금 다르다. 과격한 소스와 토핑으로 범벅된 파스타 피자가 아닌, 제대로 된 알단테 면의 파스타와 도우의 맛을 살린 피자를 맛볼 수 있다.스테이크는 가격에 비하면 양이 조금 부족하지만, 맛은 왠만한 파인 다이닝 레스토랑과 견주어도 손색이 없다.전반적으로 올리브 오일을 많이 사용하고, 조금 짭쪼름한것이 대다수의 한국인에게는 생소하고, 느끼하거나 짜게 느껴질 수 있는데, 적절한 와인을 곁들여 식사를 한다면 제대로 이탈리아를 느낄 수 있을 것이다.상수, 함정 근방의 이탈리안 음식점중 이만한곳은 찾기 힘들듯., 번역:

100%|█████████▉| 22409/22421 [13:08<00:05,  2.14it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 양고 많고 맛도 괜찮음 .  개인적으로 왕돈까스 ,볶음 우동 추천~ 돈까스 소스가 약간 달달하니 맛있다~ 가끔 생각나는 동네 맛집, 번역:

100%|█████████▉| 22410/22421 [13:09<00:05,  1.90it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 기름이 깨끗하고 또 갈 의향 있어요 맛있고 가격도 저렴해요, 번역:

100%|█████████▉| 22411/22421 [13:09<00:05,  1.88it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 맛도 괜찮고 무엇보다 양이 푸짐해서 좋아요! 가끔씩 생각나는 식당., 번역:

100%|█████████▉| 22412/22421 [13:10<00:04,  1.87it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 괜찮은 돈까스가격도 적당 맛도 적당하고 아주 무난하게 먹을만함매장은 넓은 편이며 그럼에도 약간의 웨이팅 있음, 번역:

100%|█████████▉| 22413/22421 [13:10<00:04,  1.91it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 점심시간에 시간부족한데 저보다 늦게 온분들부터 음식나오고, 애인이 체할것같이 빨리먹어서 맘이 안좋았어요. 그리고 기다린보람 없게 크림파스타는 진짜 역대 역대 최악의 음식이였습니다... 진심 먹지마세요. 돈까스는 보통., 번역:

100%|█████████▉| 22414/22421 [13:11<00:03,  1.77it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 왕돈까스 진짜 크기 엄청 크고 가성비갑이다!! 크기 크다고해서 얇은게 아니라 두께도 두껍당. 그리고 무엇보다 맛있다 ㅎ 샐러드는 안시키는게 나을듯, 번역:

100%|█████████▉| 22415/22421 [13:12<00:03,  1.84it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 깨끗하고좋음 맛도 그럭저럭있음가성비가 좋은편은 아닌듯 대신양많고 셀프포장대 있음, 번역:

100%|█████████▉| 22416/22421 [13:12<00:02,  1.99it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 돈까스 고기가 많이 얇고 튀김옷맛이 강합니다.다른 부분은 soso 합니다., 번역:

100%|██████████| 22421/22421 [13:12<00:00, 28.27it/s]

번역 오류: 'Translator' object has no attribute 'raise_Exception'
원본: 돈까스 품질은 중상.  세트메뉴의 국물우동과 볶음우동의 퀄러티는 중하. 돈까스만 먹는걸 추천합니다., 번역:

In [ ]:
# 각 레스토랑에 대한 번역된 리뷰 수집
for id in eat_info['p_id']:
    review_all = ''

    for review in eat_review[eat_review['p_id'] == id]['review_eng']:
        if isinstance(review, str):
            review_all += review + '. '
        elif isinstance(review, float):
            review_all += str(review) + '. '

    eat_info.loc[eat_info['p_id'] == id, 'reviews'] = review_all

In [ ]:
# CSV로 저장
eat_info.to_csv('/content/drive/MyDrive/ML_data/translated_eat_info.csv', index=False)
eat_review.to_csv('/content/drive/MyDrive/ML_data/translated_eat_review.csv', index=False)

음식 정보와 사용자 리뷰 데이터

태그 기반으로 KMeans 클러스터링

->  res_matrix와 user_matrix 데이터프레임을 생성

In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from gensim import models
from gensim.models import KeyedVectors
from sklearn.cluster import KMeans
from tqdm.notebook import tqdm

from collections import Counter

In [ ]:
def delete_punctuation_marks_tag(word):
    word = word.replace(",","")
    word = word.replace(".","")
    word = word.replace(",","")
    word = word.replace("!","")
    word = word.replace(":","")
    word = word.replace("?","")
    word = word.replace("~","")
    word = word.replace("\\","")
    word = word.replace("\"","")
    word = word.replace(";","")
    return word.lower()

In [ ]:
eat_info = pd.read_csv('/content/drive/MyDrive/ML_data/translated_eat_info.csv')
eat_review = pd.read_csv('/content/drive/MyDrive/ML_data/translated_eat_review.csv')

In [ ]:
eat_review_by_user = pd.DataFrame(index = eat_review['u_id'].unique(), columns=['reviews'])

for id in tqdm(eat_review['u_id'].unique()):
    review_all = ''
    for review in eat_review.loc[eat_review['u_id']==id,'review_eng']:
        if type(review) != float:
            review_all += review+'. '
    eat_review_by_user.loc[id,'reviews'] = review_all

  0%|          | 0/6181 [00:00<?, ?it/s]

In [ ]:
eat_info['tags']=''
eat_review_by_user['tags']=''

In [ ]:
eat_info.head()

,name,address,category,main_mn,price,opng_tm,rating,rvw_cnt,tags,p_id,reviews
0,놀부만두,서울특별시 동대문구 휘경2동 276-33,NaN,냉모밀,6000.0,"{'월-금,일': '오전 11시 - 오후 8시 30분 '}",NaN,NaN,,304,"Like a local restaurant, it was moderately sha..."
1,호반,서울특별시 종로구 낙원동 85-7,NaN,순대국,8000.0,{'매일': '오전 11시 30분 - 오후 10시 (준비시간 15:00~16:30)...,NaN,NaN,,2234,It is a Korean restaurant located at the edge ...
2,민벅 건대점,서울특별시 광진구 화양동 10-1,NaN,알리오올리오,9900.0,{'매일': '오전 11시 30분 - 오후 10시 (구정 추석 당일 3시 오픈)'},NaN,NaN,,770,"If you have 1 menu per person, it will give yo..."
3,뉴델리,서울시 동대문구 회기동 3-182,NaN,치킨 탄두리 (한마리),15000.0,{'매일': '오전 11시 - 오후 10시 '},NaN,NaN,,311,You can enjoy delicious Indian curry at an old...
4,강릉스낵,서울특별시 양천구 목동 406-65,NaN,직송 모듬 회,60000.0,"{'월-금': '오후 5시 - 오전 1시 ', '토/일': '오후 4시 - 오전 1...",NaN,NaN,,81,"Tteokbokki is spicy, so it's delicious.The fri..."

In [ ]:
eat_review_by_user.head()

                                                reviews tags
1616  Like a local restaurant, it was moderately sha...
905   I went to Pyongyang cold noodles and turned on...
1817  Bibim Mumil Onmemin Kimchi Band only eat bumen...
3911  Kimchi -man dumplings and cold hair combinatio...
2151

In [ ]:
with open('/content/drive/MyDrive/ML_data/stop_words.txt','r',-1,'utf-8') as f:
    stop_words = set(f.read().split('/'))

stop_words

{'',
 '*',
 '+',
 '+0',
 '+_+',
 '0th',
 '1',
 '1st',
 '2',
 '2nd',
 '3',
 '3rd',
 '4',
 '4b',
 '4th',
 '5th',
 '6',
 '6th',
 '7th',
 '8th',
 '9',
 '=',
 '>',
 '@',
 '__',
 '___________________________________',
 'a',
 'a4',
 'about',
 'above',
 'accumulated',
 'acrostic',
 'ade',
 'admirable',
 'adzuki',
 'after',
 'again',
 'against',
 'ago',
 'agre',
 'ah',
 'ahead',
 'ai',
 'ain',
 'ajumma',
 'aka',
 'al',
 'albert',
 'all',
 'alla',
 'alle',
 'alli',
 'allthe',
 'alma',
 'alongthe',
 'altro',
 'am',
 'amazing',
 'ame',
 'americano',
 'amo',
 'an',
 'anam',
 'ancestral',
 'ancient',
 'and',
 'anniversary',
 'annual',
 'ant',
 'anticipated',
 'any',
 'apo',
 'arabian',
 'archa',
 'are',
 'aren',
 "aren't",
 'argent',
 'arti',
 'as',
 'asu',
 'at',
 'attempted',
 'austrian',
 'avai',
 'average',
 'avo',
 'awesome',
 'b',
 'baby',
 'badam',
 'badi',
 'bahn',
 'bal',
 'baltic',
 'bam',
 'bb',
 'be',
 'bean',
 'beans',
 'because',
 'been',
 'beep',
 'bef',
 'before',
 'beforethe',
 'beginning',
 'being',
 'belgian',
 'below',
 'between',
 'bible',
 'billiard',
 'birthday',
 'bismarck',
 'bok',
 'bon',
 'both',
 'boththe',
 'bottom',
 'boyfriend',
 'breaktime',
 'breast',
 'brilliant',
 'bts',
 'buchu',
 'buckwheat',
 'bul',
 'burmese',
 'busi',
 'but',
 'by',
 'calabrese',
 'californian',
 'can',
 'canoli',
 'carious',
 'carnivorous',
 'carper',
 'central',
 'ceo',
 'cesar',
 'cha',
 'chae',
 'cham',
 'char',
 'cheek',
 'cheong',
 'chi',
 'chickpea',
 'chicory',
 'chilean',
 'chinatown',
 'chirashi',
 'chocolat',
 'chok',
 'chou',
 'choy',
 'chu',
 'chun',
 'chupa',
 'cj',
 'close',
 'closed',
 'coastal',
 'coco',
 'coeducational',
 'colombian',
 'combi',
 'combined',
 'combo',
 'comme',
 'commendable',
 'complete',
 'consecutive',
 'continued',
 'costal',
 'couldn',
 "couldn't",
 'couple',
 'cro',
 'crown',
 'cu',
 'd',
 'da',
 'dae',
 'dak',
 'dalia',
 'dan',
 'darth',
 'dary',
 'de',
 'decade',
 'deducted',
 'deng',
 'di',
 'did',
 'didn',
 "didn't",
 'din',
 'dina',
 'dinosaur',
 'divine',
 'do',
 'doenjang',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'dong',
 'dora',
 'double',
 'doubled',
 'down',
 'draft',
 'driving',
 'due',
 'dul',
 'dum',
 'during',
 'e',
 'each',
 'earlier',
 'early',
 'east',
 'eastern',
 'edible',
 'eg',
 'egyptian',
 'eight',
 'eighth',
 'eighty',
 'el',
 'eleven',
 'embankment',
 'emi',
 'emmental',
 'emoji',
 'end',
 'ending',
 'ends',
 'enjoy',
 'enjoyable',
 'enjoyed',
 'entering',
 'entire',
 'equivalent',
 'eran',
 'error',
 'etc',
 'ethiopian',
 'eul',
 'eurasian',
 'evian',
 'excelent',
 'excellent',
 'exceptional',
 'exciting',
 'exemplary',
 'expected',
 'expects',
 'experienced',
 'extended',
 'extramarital',
 'extraordinary',
 'failed',
 'failing',
 'fairy',
 'famous',
 'fantastic',
 'fav',
 'favorite',
 'feng',
 'few',
 'fifteen',
 'fifteenth',
 'fifth',
 'fifty',
 'filial',
 'final',
 'finish',
 'finished',
 'finishing',
 'finnish',
 'first',
 'five',
 'flat',
 'flawless',
 'flesh',
 'fm',
 'following',
 'for',
 'forced',
 'formaggi',
 'forthe',
 'forty',
 'foul',
 'four',
 'fourth',
 'franchise',
 'frau',
 'from',
 'ft',
 'fucking',
 'full',
 'fun',
 'further',
 'galat',
 'gallic',
 'gam',
 'ganja',
 'gat',
 'genius',
 'gente',
 'ginseng',
 'girlfriend',
 'gis',
 'gmo',
 'gon',
 'gong',
 'good',
 'goodby',
 'gram',
 'grana',
 'grandma',
 'granny',
 'great',
 'gross',
 'guan',
 'guaranteed',
 'h',
 'h2',
 'ha',
 'had',
 'hadi',
 'hadn',
 "hadn't",
 'hagwon',
 'hahm',
 'half',
 'hamburg',
 'han',
 'hanji',
 'hanok',
 'hanwoo',
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'hawaiian',
 'he',
 'heartwarming',
 'hehehe',
 'hehehehe',
 'her',
 'here',
 'hereafter',
 'hereto',
 'hers',
 'herself',
 'him',
 'himalayan',
 'himself',
 'hinoki',
 'his',
 'ho',
 'hoe',
 'holy',
 'hoo',
 'hooray',
 'hoti',
 'how',
 'however',
 'https',
 'hua',
 'hundred',
 'hungarian',
 'i',
 'id',
 'if',
 'ifc',
 'impeccable',
 'importanti',
 'impressive',
 'in',
 'ina',
 'incomparable',
 'incredible',
 'indescribable',
 'indic',
 'indonesian',
 'ini',
 'init',
 'initial',
 'interesting',
 'inthe',
 'into',
 'ipa',
 'irreplaceable',
 'irresistible',
 'is',
 'isit',
 'isn',
 "isn't",
 'it',
 "it's",
 'ita',
 'itas',
 'itd',
 'ited',
 'ithe',
 'iti',
 'itin',
 'its',
 'itself',
 'j',
 'jamaican',
 'jang',
 'jeon',
 'jeong',
 'ji',
 'jin',
 'jjigae',
 'jmt',
 'jo',
 'js',
 'jumbo',
 'just',
 'kai',
 'kami',
 'kao',
 'kaya',
 'khao',
 'ki',
 'kim',
 'kimbap',
 'kis',
 'kiss',
 'kochi',
 'kona',
 'kong',
 'ku',
 'kua',
 'kumo',
 'kun',
 'kung',
 'kya',
 'l',
 'la',
 'lady',
 'lang',
 'laos',
 'last',
 'late',
 'later',
 'latin',
 'leading',
 'least',
 'legendary',
 'lentil',
 'level',
 'lfe',
 'liked',
 'lin',
 'll',
 'located',
 'lola',
 'longa',
 'lorraine',
 'losing',
 'loss',
 'lost',
 'lotus',
 'love',
 'lp',
 'lt',
 'm',
 'ma',
 "ma'am",
 'magic',
 'magical',
 'mal',
 'mala',
 'maltese',
 'managed',
 'manchurian',
 'manimal',
 'mano',
 'manu',
 'mapa',
 'mapo',
 'mara',
 'maras',
 'marco',
 'marshy',
 'maximum',
 'me',
 'median',
 'mediterranean',
 'mei',
 'memorable',
 'meno',
 'metropolitan',
 'mi',
 'mid',
 'middle',
 'mightn',
 "mightn't",
 'mille',
 'mimi',
 'ming',
 'minimum',
 'minus',
 'missed',
 'missing',
 'mixi',
 'mona',
 'mongolian',
 'monkey',
 'monte',
 'monthly',
 'more',
 'most',
 'mountainous',
 'mouth',
 'msg',
 'muk',
 'mul',
 'mung',
 'mushroom',
 'mushrooms',
 'mustn',
 "mustn't",
 'my',
 'mys',
 'myself',
 'mysterious',
 'n',
 'na',
 'nabi',
 'naked',
 'name',
 'nameless',
 'nami',
 'namo',
 'nan',
 'nashi',
 'near',
 'neat',
 'needn',
 "needn't",
 'neer',
 'neighboring',
 'nem',
 'nepal',
 'neta',
 'next',
 'ni',
 'nice',
 'nicky',
 'nightingale',
 'nine',
 'ninth',
 'nish',
 'no',
 'no2',
 'noa',
 'nomi',
 'nong',
 'nor',
 'north',
 'northeastern',
 'northern',
 'northwestern',
 'nos',
 'not',
 'notched',
 'noti',
 'now',
 'nox',
 'nth',
 'num',
 'o',
 'ocho',
 'odo',
 'of',
 'off',
 'offre',
 'ok',
 'olio',
 'ome',
 'omi',
 'omo',
 'on',
 'once',
 'one',
 'oni',
 'only',
 'oo',
 'oolong',
 'open',
 'opened',
 'openi',
 'opening',
 'or',
 'orginal',
 'oriental',
 'other',
 'ou',
 'our',
 'ours',
 'ourselves',
 'out',
 'outstanding',
 'ova',
 'over',
 'overall',
 'overcame',
 'overthe',
 'own',
 'ox',
 'ozzy',
 'p',
 'panna',
 'panne',
 'pao',
 'pea',
 'peak',
 'pean',
 'pen',
 'per',
 'pera',
 'percent',
 'perfect',
 'perfecta',
 'perilla',
 'persian',
 'peruvian',
 'petit',
 'pi',
 'piggy',
 'place',
 'plate',
 'plated',
 'plating',
 'please',
 'plus',
 'pong',
 'poop',
 'potato',
 'pounds',
 'ppa',
 'pratt',
 'prefix',
 'preliminary',
 'presbyterian',
 'previous',
 'priceless',
 'princess',
 'prior',
 'pronounced',
 'provisional',
 'puli',
 'putts',
 'pyeong',
 'qr',
 'quatro',
 'quattro',
 'queen',
 'ranked',
 'rave',
 're',
 'receive',
 'recorded',
 'refreshing',
 'regular',
 'remaining',
 'remote',
 'reopened',
 'reviewable',
 'ripe',
 'ripened',
 'rised',
 'ritual',
 'roro',
 'ros',
 'rose',
 'round',
 'row',
 'royal',
 'rucola',
 'rural',
 'rye',
 's',
 'sabal',
 'sabi',
 'sacred',
 'sak',
 'salary',
 'sam',
 'same',
 'samgyetang',
 'san',
 'sando',
 'sarira',
 'scandinavian',
 'scheduled',
 'sebastian',
 'second',
 'sensational',
 'seoul',
 'servant',
 'sesame',
 'set',
 'seven',
 'seventeen',
 'seventh',
 'sfc',
 'shabu',
 'shan',
 "shan't",
 'shanghai',
 'shao',
 'shari',
 'she',
 "she's",
 'shiitake',
 'shiro',
 'short',
 'shortened',
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'shui',
 'siam',
 'sickle',
 'signi',
 'silla',
 'simi',
 'since',
 'single',
 'sister',
 'situated',
 'siu',
 'six',
 'sixth',
 'slogan',
 'smelled',
 'smellin',
 'sns',
 'so',
 'sofa',
 'soju',
 'some',
 'soo',
 'sora',
 'soul',
 'sous',
 'south',
 'southeast',
 'southern',
 'southwestern',
 'spam',
 'spent',
 'squash',
 'sr',
 'ss',
 'star',
 'starting',
 'straight',
 'subsequent',
 'suburban',
 'suburbs',
 'successive',
 'such',
 'sult',
 'sumo',
 'superlative',
 'syllable',
 't',
 'ta',
 'taek',
 'taiwanese',
 'talian',
 'tama',
 'tapioca',
 'tara',
 'tare',
 'taro',
 'tat',
 'ted',
 'teddy',
 'ten',
 'tender',
 'teo',
 'terra',
 'terro',
 'text',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 'third',
 'thirty',
 'this',
 'those',
 'thousand',
 'three',
 'threesome',
 'through',
 'tic',
 'tipi',
 'titian',
 'to',
 'to5',
 'toi',
 'tomo',
 'tomy',
 'tongue',
 'tonkotsu',
 'too',
 'top',
 'topping',
 'tori',
 'tory',
 'total',
 'tous',
 'tribute',
 'tricolor',
 'trident',
 'triple',
 'tteok',
 'turnip',
 'tuscan',
 'twelve',
 'twenty',
 'twice',
 'twin',
 'two',
 'u',
 'ue',
 'uh',
 'uing',
 'um',
 'umeboshi',
 'un',
 'unbelievable',
 'unboiled',
 'unchanged',
 'uncut',
 'under',
 'underwent',
 'unexpectedly',
 'unforgettable',
 'uni',
 'unique',
 'uniqueness',
 'unloose',
 'unrated',
 'unreplaceable',
 'unrivaled',
 'until',
 'up',
 'upi',
 'upload',
 'uploaded',
 'uploading',
 'uploads',
 'upp',
 'urban',
 'usi',
 'uv',
 've',
 'vegetable',
 'vera',
 'very',
 'vienna',
 'viet',
 'vietnamese',
 'vongole',
 'vs',
 'wah',
 'was',
 'wasn',
 "wasn't",
 'wasthe',
 'wata',
 'we',
 'weekly',
 'wellas',
 'were',
 'weren',
 "weren't",
 'west',
 'western',
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'whopping',
 'why',
 'will',
 'wite',
 'with',
 'won',
 "won't",
 'wonderful',
 'wonthe',
 'worst',
 'worthy',
 'wouldn',
 "wouldn't",
 'wow',
 'x',
 'x2',
 'xd',
 'xiang',
 'xiao',
 'xx',
 'y',
 'yagi',
 'yam',
 'yama',
 'yang',
 'year',
 'years',
 'yg',
 'yi',
 'yo',
 'yong',
 'yoo',
 'yorkshire',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'yoyo',
 'yu',
 'yuan',
 'yuk',
 'yul',
 'yum',
 '°',
 '»',
 '×',
 '•',
 '※',
 '₩',
 '■',
 '□',
 '▶',
 '○',
 '●',
 '★',
 '☆',
 '♡',
 '♥',
 '✓',
 '人',
 '小',
 '가',
 '과',
 '로',
 '를',
 '명',
 '미국',
 '시',
 '에',
 '와',
 '은',
 '을',
 '의',
 '이',
 '하고',
 '하는',
 '한',
 '한국'}

In [ ]:
def get_tags_to_txt(text):
    if type(text) != str:
        return ''
    text = word_tokenize(text)
    tags_dump = nltk.pos_tag(text)
    tags = []

    for word in tags_dump:
        if (word[1] == 'JJ') and (word[0] not in stop_words):
            tags.append(delete_punctuation_marks_tag(word[0]))

    tags = ','.join(tags)

    return tags

In [ ]:
import nltk
nltk.download('averaged_perceptron_tagger', quiet=True)

True

In [ ]:
for i in tqdm(eat_info.index):
    eat_info.loc[i,'tags'] = get_tags_to_txt(eat_info.loc[i,'reviews'])

for i in tqdm(eat_review_by_user.index):
    eat_review_by_user.loc[i,'tags'] = get_tags_to_txt(eat_review_by_user.loc[i,'reviews'])

  0%|          | 0/2314 [00:00<?, ?it/s]

  0%|          | 0/6181 [00:00<?, ?it/s]

word2vec model :

https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?resourcekey=0-wjGZdNAUop6WykTtMip30g

Word2Vec을 사용하여 앞선 tokenizing 단계에서 추출해낸 형용사를 300차원의 벡터로 변형한 후,

K-means 알고리즘을 사용해 클러스터링 작업을 수행

In [ ]:
import gensim
from gensim.models import KeyedVectors
import gzip

# Path to the compressed file
file_path_gz = "/content/drive/MyDrive/ML_data/GoogleNews-vectors-negative300.bin.gz"

# Path to save the extracted bin file
file_path_bin = "/content/drive/MyDrive/ML_data/GoogleNews-vectors-negative300.bin"

# Extract the compressed gzip file
with gzip.open(file_path_gz, 'rb') as f_in, open(file_path_bin, 'wb') as f_out:
    f_out.writelines(f_in)

In [ ]:
# Load the Word2Vec model
w2v = KeyedVectors.load_word2vec_format(file_path_bin, binary=True)
print("Word2Vec model loaded successfully.")

Word2Vec model loaded successfully.

In [ ]:
print("Word2Vec 모델의 어휘 크기:", len(w2v.key_to_index))
print("Word2Vec 모델의 어휘:", list(w2v.key_to_index.keys()))

Word2Vec 모델의 어휘 크기: 3000000
Word2Vec 모델의 어휘:

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
All_tags = set()
for tags in eat_info['tags']:
    All_tags.update(set(tags.split(',')))

In [ ]:
new_df = pd.DataFrame()
for word in All_tags:
    try:
        f_vec = w2v.get_vector(word)
        new_df[word] = f_vec
    except:
        pass

In [ ]:
# new_df 출력
print(new_df)

          sub  unreasonable   sausage      meat      tang   foreign  \
0   -0.208984      0.051758 -0.183594 -0.253906 -0.144531 -0.201172
1    0.223633      0.036133 -0.166992  0.137695  0.000797  0.114258
2    0.102051      0.060303  0.052002  0.084473  0.053223  0.114258
3    0.059814      0.063965  0.414062  0.221680 -0.202148  0.050537
4   -0.164062     -0.166016 -0.134766 -0.012695 -0.020752 -0.068848
..        ...           ...       ...       ...       ...       ...
295 -0.011230      0.081055 -0.261719  0.048584 -0.199219  0.050293
296 -0.171875     -0.008606  0.184570  0.165039 -0.050293  0.096191
297 -0.008911      0.159180  0.128906  0.075684 -0.148438  0.046875
298 -0.077148     -0.147461 -0.055420  0.170898 -0.067871  0.112793
299  0.094238     -0.067383 -0.012878  0.055420  0.345703  0.287109

     leisurely   musical  overwhelming      bruk  ...  residential     loose  \
0     0.014465  0.110840      0.082520  0.024536  ...    -0.094727  0.188477
1     0.152344 -0.106445      0.144531 -0.019409  ...     0.000315 -0.054688
2    -0.302734 -0.093750     -0.255859  0.080078  ...     0.093262 -0.160156
3     0.345703  0.072266      0.021484  0.115234  ...    -0.042236  0.173828
4     0.031128 -0.025391     -0.200195  0.033936  ...     0.078125 -0.283203
..         ...       ...           ...       ...  ...          ...       ...
295  -0.196289  0.144531     -0.184570  0.006317  ...     0.064453 -0.198242
296   0.102051  0.140625      0.017578 -0.015625  ...    -0.175781  0.109863
297  -0.149414 -0.020630      0.029175 -0.113770  ...    -0.004272  0.238281
298   0.095703  0.076172     -0.043457  0.030762  ...     0.320312 -0.105469
299   0.000155  0.125000      0.084473  0.064453  ...    -0.062988 -0.240234

         mall  financial  nowadays  ripening   torched  stimulating  entirely  \
0    0.200195  -0.092773  0.178711 -0.136719  0.416016    -0.141602  0.157227
1    0.123535  -0.024414 -0.009521  0.894531  0.382812     0.014282 -0.243164
2   -0.031738  -0.145508 -0.156250 -0.478516  0.306641     0.003265  0.053955
3    0.183594  -0.018433  0.186523  0.007751 -0.020142     0.125000  0.269531
4    0.058350   0.121094 -0.103516 -0.053467  0.302734    -0.215820 -0.202148
..        ...        ...       ...       ...       ...          ...       ...
295  0.083008   0.108887 -0.113770  0.209961  0.140625     0.194336 -0.155273
296  0.134766  -0.183594  0.005707 -0.171875 -0.480469    -0.242188  0.241211
297 -0.022583   0.292969 -0.067871  0.140625 -0.298828    -0.087402 -0.055664
298  0.118164  -0.046387  0.111328  0.113770  0.002289     0.275391  0.104004
299 -0.041016  -0.159180  0.232422  0.589844 -0.127930     0.128906  0.002838

        swear
0    0.034668
1   -0.141602
2    0.163086
3    0.147461
4   -0.147461
..        ...
295 -0.285156
296 -0.034912
297 -0.121094
298 -0.164062
299  0.110840

[300 rows x 1849 columns]

In [ ]:
x = new_df.T
cluster_count=120
model = KMeans(n_clusters=cluster_count)
model.fit(x)
model.predict(x)
Y=x.copy()
Y['kmeans_id'] = model.predict(x)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [ ]:
km = list(Y['kmeans_id'])
max_count = 0
max_count_id = ''
for i in range (0, cluster_count):
    if km.count(i) > max_count:
        max_count = km.count(i);
        max_count_id = i;
    print(i,': ', km.count(i))
max_count_id

0 :  19
1 :  46
2 :  14
3 :  2
4 :  2
5 :  5
6 :  27
7 :  40
8 :  7
9 :  25
10 :  6
11 :  37
12 :  21
13 :  2
14 :  20
15 :  33
16 :  4
17 :  10
18 :  15
19 :  3
20 :  1
21 :  5
22 :  8
23 :  16
24 :  157
25 :  1
26 :  8
27 :  34
28 :  24
29 :  13
30 :  6
31 :  16
32 :  26
33 :  26
34 :  5
35 :  58
36 :  20
37 :  1
38 :  12
39 :  16
40 :  1
41 :  9
42 :  7
43 :  3
44 :  5
45 :  1
46 :  6
47 :  2
48 :  6
49 :  11
50 :  30
51 :  4
52 :  4
53 :  1
54 :  16
55 :  5
56 :  10
57 :  2
58 :  11
59 :  2
60 :  20
61 :  5
62 :  8
63 :  13
64 :  22
65 :  1
66 :  24
67 :  21
68 :  45
69 :  2
70 :  5
71 :  1
72 :  10
73 :  1
74 :  79
75 :  9
76 :  22
77 :  10
78 :  2
79 :  1
80 :  43
81 :  1
82 :  103
83 :  6
84 :  2
85 :  1
86 :  16
87 :  4
88 :  7
89 :  31
90 :  24
91 :  1
92 :  38
93 :  127
94 :  1
95 :  4
96 :  1
97 :  5
98 :  13
99 :  2
100 :  1
101 :  3
102 :  2
103 :  38
104 :  1
105 :  1
106 :  13
107 :  3
108 :  7
109 :  26
110 :  7
111 :  31
112 :  2
113 :  9
114 :  20
115 :  11
116 :  8
117 :  1
118 :  4
119 :  3

24

In [ ]:
km_df = pd.DataFrame()
km_df['group_'+str(max_count_id)] = pd.Series(list(Y[Y['kmeans_id'] == max_count_id].index))
for i in range(0, cluster_count):
    col_name = 'group_'+str(i)
    words = list(Y[Y['kmeans_id'] == i].index)
    km_df[col_name] = pd.Series(words)

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
km_df.fillna(0)

<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)
<ipython-input-30-30d2f3fd091d>:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  km_df[col_name] = pd.Series(words)

,group_24,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,group_9,group_10,group_11,group_12,group_13,group_14,group_15,group_16,group_17,group_18,group_19,group_20,group_21,group_22,group_23,group_25,group_26,group_27,group_28,group_29,group_30,group_31,group_32,group_33,group_34,group_35,group_36,group_37,group_38,group_39,group_40,group_41,group_42,group_43,group_44,group_45,group_46,group_47,group_48,group_49,group_50,group_51,group_52,group_53,group_54,group_55,group_56,group_57,group_58,group_59,group_60,group_61,group_62,group_63,group_64,group_65,group_66,group_67,group_68,group_69,group_70,group_71,group_72,group_73,group_74,group_75,group_76,group_77,group_78,group_79,group_80,group_81,group_82,group_83,group_84,group_85,group_86,group_87,group_88,group_89,group_90,group_91,group_92,group_93,group_94,group_95,group_96,group_97,group_98,group_99,group_100,group_101,group_102,group_103,group_104,group_105,group_106,group_107,group_108,group_109,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,sub,messy,ignorant,flounder,mammoth,boundary,clogged,slim,overwhelming,dazzling,sluggish,sudden,packed,banana,high,bossy,sausage,playful,ok,musical,intuitive,tactile,flavorful,naturalistic,british,patty,concerned,talked,scary,humble,mascarpone,risky,tang,commonplace,hygienic,tingling,snowy,breathable,kitchen,historical,alli,walnut,aroma,nutrition,culinary,mall,ribs,abundant,fish,day,infinite,ale,protein,extinct,excited,iced,syrup,leek,magnetic,remodeled,convenient,meat,hydraulic,ginger,unnamed,servings,strong,thorough,bruk,bilateral,pulmonary,diced,feast,stainless,thirst,pearl,spacious,drank,handwritten,middleweight,spoonful,incense,foreign,physical,burnt,odor,discounted,sashimi,cuttlefish,moist,unreasonable,mart,leisurely,arethe,concise,tacos,apologized,lipstick,electric,diet,dims,sheep,refilled,elasticity,burial,suicide,tea,kindergarten,herb,chopped,noodle,purple,spreading,emu,manga,clunky,eager,mandible,sirloin,compatible
1,squeeze,difficult,forgive,mussel,giant,line,tangle,generous,definite,tidy,annoying,uncommon,hidden,peanut,low,macho,chili,gentle,i,comic,smart,0,chewy,secluded,chinese,0,afraid,know,surprising,passionate,balsamic,rotten,scones,likely,sanitary,nail,sunny,0,tavern,reminiscent,0,wooden,olfactory,digestive,cooking,0,bone,plentiful,ahi,lunchtime,passive,wine,fat,0,lucky,snow,licorice,leeks,pixel,renovated,durable,lamb,adjustable,garlic,visited,0,nucleus,adhered,thai,trilateral,abdominal,0,brunch,0,unpleasantness,sari,classy,eats,handwriting,0,cone,0,unmanned,cognitive,torched,0,upgrade,vegan,eel,acidic,absurd,0,crowded,deeper,0,nachos,0,skin,nitrogen,dietary,0,cow,refill,variable,0,0,wheat,pupil,ginkgo,dried,dumplings,fluorescent,spread,horse,teppanyaki,cluttered,willing,0,steaks,fit
2,normal,delicate,frustrated,salmon,0,0,tangled,diversified,serious,neat,sore,abnormal,accompanied,flowering,0,kicky,spaghetti,loving,hello,art,intelligent,0,crispy,sandy,spanish,0,anxious,aware,embarrassing,careful,parmesan,unsanitary,roasted,inevitable,hygiene,unsighted,rainy,0,upstairs,modern,0,acorn,tastes,nutritional,baking,0,thumb,0,anchovy,seasonal,accurate,liquor,fatty,0,confident,ice,sherbet,0,dialectical,0,cheaper,beef,rotary,basil,opposed,0,ideal,reasonable,hae,0,intestinal,0,dinner,0,habitual,handmade,luxury,ate,0,0,egg,0,parking,mental,0,0,cut,vegetarian,crayfish,elastic,invalid,0,quiet,elsewhere,0,nacho,0,moisturized,environmental,0,0,cattle,0,preferential,0,0,soybean,elementary,herbal,crushed,noodles,darker,0,cats,ramen,cumbersome,reluctant,0,tenderloin,fits
3,fresh,harsh,bored,shrimp,0,0,paralyzed,large,tremendous,colorful,frustrating,unexpected,delayed,strawberry,0,chubby,pancake,affectionate,eatin,music,0,0,crunchy,lush,french,0,worried,wish,suspicious,empathetic,risotto,dirty,delicacies,essential,neatness,bloody,hot,0,rooftop,classic,0,marble,texture,0,cooked,0,tendon,0,mackerel,daytime,unlimited,whiskey,lactose,0,pleased,skate,avocado,0,atmospheric,0,accessible,chicken,brake,cabbage,working,0,consistent,wise,taiwanese,0,vaginal,0,cafe,0,invisible,saree,lovely,bite,0,0,chilled,0,signboard,psychological,0,0,replaced,sushi,whale,textured,flimsy,0,noisy,filter,0,taco,0,hair,agricultural,0,0,0,0,strict,0,0,rice,0,hemp,flowing,vermicelli,rectangular,0,pet,tempura,costly,able,0,steak,0
4,long,rough,addicted,scallop,0,0,stuck,tiny,fatal,crisp,sloppy,unusual,piped,honey,0,smile,pepperoni,0,ur,avant,0,0,creamy,rustic,german,0,frightened,regret,curious,kindness,mozzarella,harmful,tart,impossible,cleanliness,cradle,cold,0,downstairs,historic,0,bamboo,freshness,0,oven,0,knee,0,seafood,holiday,occasional,0,0,0,disappointed,puck,lemon,0,thermal,0,reliable,pork,rotational,eggplant,serving,0,proven,recommend,ini,0,liver,0,meal,0,wealthy,tableware,luxurious,chewed,0,0,bowls,0,laptop,hormonal,0,0,depleted,0,octopus,lumpy,unnatural,0,harmonious,uniformly,0,0,0,curly,metallurgical,0,0,0,0,condensed,0,0,soy,0,antibiotic,swollen,mochi,green,0,fox,bulgogi,burdensome,ready,0,0,0
5,super,daunting,lazy,shellfish,0,0,0,proportional,tangible,remarkable,questionable,rare,greeted,fig,0,cheeky,sundae,0,hmm,horn,0,0,0,panoramic,japanese,0,nervous,quite,fascinating,thoughtful,cheddar,lax,pickled,beneficial,0,unattended,dry,0,bed,distinctive,0,pine,tasted,0,0,0,hip,0,tuna,autumn,realistic,0,0,0,satisfied,0,carbonated,0,quantum,0,inexpensive,0,manual,truffle,married,0,unique,responsible,˘,0,0,0,buffet,0,patriarchal,floral,understated,eat,0,0,tray,0,indoor,emotional,0,0,reinforced,0,squid,shallow,subjective,0,lively,advanced,0,0,0,0,solar,0,0,0,0,forbidden,0,0,oat,0,botanical,ruined,dumpling,blue,0,fur,makgeolli,expensive,prepared,0,0,0
6,grind,hard,sorry,clam,0,0,0,flat,severe,vivid,slow,0,sprinkled,watermelon,0,chunky,sauce,0,outa,classical,0,0,0,topographical,indian,0,fearful,pretty,unfortunate,honest,0,smelly,dessert,important,0,sword,tropical,0,attic,retro,0,tree,taste,0,0,0,0,0,0,daily,spontaneous,0,0,0,proud,0,cucumber,0,temporal,0,available,0,mechanical,horseradish,searched,0,superior,helpful,vietnamese,0,0,0,lunch,0,inner,crystal,sensual,eaten,0,0,dough,0,regional,0,0,0,reduced,0,flatfish,waxy,foolish,0,dull,isolated,0,0,0,0,pharmaceutical,0,0,0,0,quantitative,0,0,cacao,0,herbs,melted,tofu,black,0,mascot,yaki,unnecessary,hesitant,0,0,0
7,whole,bitter,puzzled,herring,0,0,0,sparse,systemic,0,bad,0,unleashed,pineapple,0,angelic,curry,0,lol,singing,0,0,0,scenic,european,0,scared,interested,sad,meticulous,0,caustic,flavored,unlikely,0,nostril,windy,0,apartment,legendary,0,oak,0,0,0,0,0,0,0,o'clock,positional,0,0,0,impressed,0,lime,0,polar,0,transparent,0,nozzle,turmeric,unveiled,0,coveted,adequate,ade,0,0,0,restaurant,0,fame,decorative,gorgeous,eating,0,0,salted,0,general,0,0,0,updated,0,0,thin,wrong,0,friendly,characteristic,0,0,0,0,organic,0,0,0,0,sensitive,0,0,coffee,0,0,peeled,0,pink,0,horned,shochu,clumsy,chose,0,0,0
8,fine,tough,tired,lobster,0,0,0,small,huge,0,blemish,0,left,alba,0,fluffy,pasta,0,oh,artistic,0,0,0,0,italian,0,0,understood,familiar,respectful,0,poisonous,tasty,required,0,foot,dusty,0,terrace,original,0,fern,0,0,0,0,0,0,0,regular,pure,0,0,0,glad,0,garnish,0,universe,0,cheap,0,0,dill,veteran,0,best,rational,hawaiian,0,0,0,menu,0,prophet,rosary,graceful,bitten,0,0,canned,0,army,0,0,0,upgraded,0,0,scented,inappropriate,0,healthy,limited,0,0,0,0,farming,0,0,0,0,exact,0,0,sugar,0,0,wrapped,0,shiny,0,dog,miso,pricey,0,0,0,0
9,openi,complicated,rude,crab,0,0,0,moderate,gradual,0,irritating,0,attracted,leaf,0,funny,pizzas,0,haha,sound,0,0,0,0,american,0,0,felt,cryptic,considerate,0,disgusting,sweet,enable,0,hole,muddy,0,suite,signature,0,0,0,0,0,0,0,0,0,peak,unchanging,0,0,0,grateful,0,pomegranate,0,corona,0,affordable,0,0,pepper,praised,0,unparalleled,relevant,sema,0,0,0,dining,0,geek,0,glamorous,smoked,0,0,seasoning,0,smoking,0,0,0,reset,0,0,oiled,biased,0,atmosphere,unsolicited,0,0,0,0,nuclear,0,0,0,0,different,0,0,bean,0,0,pour,0,shining,0,0,wasabi,wasteful,0,0,0,0
10,three,stubborn,indifferent,cod,0,0,0,mixed,decisive,0,rosy,0,handed,berry,0,muscular,bagel,0,0,pop,0,0,0,0,korean,0,0,definitely,heartbreaking,courteous,0,prone,tiramisu,urgent,0,unconscious,cool,0,hall,authentic,0,0,0,0,0,0,0,0,0,weekday,continuous,0,0,0,fortunate,0,0,0,chromatic,0,sophisticated,0,0,cinnamon,paid,0,finest,valid,mani,0,0,0,0,0,plain,0,chic,0,0,0,stir,0,elderly,0,0,0,changed,0,0,porous,contrary,0,pleasant,often,0,0,0,0,industrial,0,0,0,0,specific,0,0,flour,0,0,blown,0,expressionless,0,0,kimchi,inconvenient,0,0,0,0
11,worki,easy,distracted,oyster,0,0,0,wide,considerable,0,stingy,0,tailed,fungus,0,squeaky,latte,0,0,fusion,0,0,0,0,mexican,0,0,heard,weird,sincere,0,tasteless,tangy,advantageous,0,pile,wet,0,window,antique,0,0,0,0,0,0,0,0,0,0,linear,0,0,0,happy,0,0,0,0,0,competitive,0,0,rosemary,ordered,0,depth,suitable,belgian,0,0,0,0,0,fritz,0,exquisite,0,0,0,spice,0,parliamentary,0,0,0,trimmed,0,0,foamed,meaningless,0,stressful,background,0,0,0,0,automotive,0,0,0,0,unpublished,0,0,barley,0,0,torn,0,triangular,0,0,matcha,0,0,0,0,0
12,bubble,tricky,unkind,seaweed,0,0,0,weighted,significant,0,weak,0,rose,pear,0,sexy,ham,0,0,lyrical,0,0,0,0,african,0,0,shame,understandable,conscientious,0,shabby,foie,mandatory,0,knife,damp,0,0,commemorative,0,0,0,0,0,0,0,0,0,0,trivial,0,0,0,welcome,0,0,0,0,0,adaptable,0,0,radish,tried,0,successful,unsuitable,oni,0,0,0,0,0,uncle,0,exotic,0,0,0,bib,0,resident,0,0,0,increased,0,0,thick,unbalanced,0,calm,non,0,0,0,0,eco,0,0,0,0,circular,0,0,milk,0,0,chop,0,red,0,0,bibimbap,0,0,0,0,0
13,bear,fragile,disgusted,scallops,0,0,0,heterogeneous,cumulative,0,troublesome,0,sealed,tomato,0,hairy,sandwich,0,0,turntable,0,0,0,0,english,0,0,bit,plausible,0,0,toxic,gourmet,necessary,0,tail,warm,0,0,preserved,0,0,0,0,0,0,0,0,0,0,constant,0,0,0,surprised,0,0,0,0,0,customized,0,0,0,worked,0,excellent,proper,noti,0,0,0,0,0,life,0,tasteful,0,0,0,steamed,0,undergrounds,0,0,0,add,0,0,dense,ridiculous,0,cheerful,multiple,0,0,0,0,0,0,0,0,0,hereof,0,0,0,0,0,blew,0,marbled,0,0,udon,0,0,0,0,0
14,upthe,stiff,dislike,0,0,0,0,steep,bold,0,poor,0,masked,olive,0,plump,broth,0,0,folk,0,0,0,0,australian,0,0,speak,fishy,0,0,dangerous,croissant,insolvent,0,nose,heat,0,0,vintage,0,0,0,0,0,0,0,0,0,0,absolute,0,0,0,hopeful,0,0,0,0,0,efficient,0,0,0,dismissed,0,decent,properly,chica,0,0,0,0,0,philosophical,0,romantic,0,0,0,butter,0,internet,0,0,0,impacted,0,0,glutinous,discriminatory,0,cramped,thrive,0,0,0,0,0,0,0,0,0,unknown,0,0,0,0,0,squeezed,0,bright,0,0,tonkatsu,0,0,0,0,0
15,isthe,awkward,embarrassed,0,0,0,0,balanced,big,0,bothersome,0,filled,fruit,0,clicky,ketchup,0,0,0,0,0,0,0,asian,0,0,think,terrible,0,0,unclean,savory,disadvantage,0,brush,raining,0,0,famous,0,0,0,0,0,0,0,0,0,0,instantaneous,0,0,0,relieved,0,0,0,0,0,compact,0,0,0,discharged,0,solid,safe,bada,0,0,0,0,0,young,0,fashionable,0,0,0,cake,0,old,0,0,0,refresh,0,0,fluid,irrelevant,0,stuffy,guide,0,0,0,0,0,0,0,0,0,origin,0,0,0,0,0,sweat,0,gray,0,0,soba,0,0,0,0,0
16,live,slippery,ashamed,0,0,0,0,lean,positive,0,uneven,0,chattered,mango,0,accent,pizza,0,0,0,0,0,0,0,0,0,0,like,peculiar,0,0,0,souffle,dependent,0,outhalf,cooler,0,0,0,0,0,0,0,0,0,0,0,0,0,endless,0,0,0,0,0,0,0,0,0,flexible,0,0,0,floated,0,powerful,correct,saman,0,0,0,0,0,cousin,0,elegant,0,0,0,boiled,0,outsidethe,0,0,0,0,0,0,synthetic,false,0,energetic,disposable,0,0,0,0,0,0,0,0,0,unfavorable,0,0,0,0,0,watered,0,light,0,0,gyoza,0,0,0,0,0
17,wait,fierce,cheat,0,0,0,0,narrower,negative,0,niggle,0,sat,blueberry,0,cute,dish,0,0,0,0,0,0,0,0,0,0,stressed,strange,0,0,0,juicy,prerequisite,0,shoe,colder,0,0,0,0,0,0,0,0,0,0,0,0,0,predictable,0,0,0,0,0,0,0,0,0,stable,0,0,0,sued,0,cohesive,sensible,halloween,0,0,0,0,0,urchin,0,trendy,0,0,0,eatable,0,concrete,0,0,0,0,0,0,residue,exaggerated,0,awake,refined,0,0,0,0,0,0,0,0,0,ambiguous,0,0,0,0,0,soaked,0,neon,0,0,xiao,0,0,0,0,0
18,added,painful,dissatisfied,0,0,0,0,tight,dramatic,0,doubtful,0,reserved,vegetable,0,busty,soup,0,0,0,0,0,0,0,0,0,0,express,regrettable,0,0,0,fragrant,valuable,0,sniper,cloudy,0,0,0,0,0,0,0,0,0,0,0,0,0,visual,0,0,0,0,0,0,0,0,0,profitable,0,0,0,ex,0,premium,appropriate,iti,0,0,0,0,0,omnivorous,0,beautiful,0,0,0,cream,0,open,0,0,0,0,0,0,concave,inaccurate,0,boring,additional,0,0,0,0,0,0,0,0,0,disagreement,0,0,0,0,0,broken,0,dim,0,0,tatami,0,0,0,0,0
19,unconditionally,0,messed,0,0,0,0,diverse,unprecedented,0,disappointment,0,finished,pumpkin,0,tall,salad,0,0,0,0,0,0,0,0,0,0,want,unfamiliar,0,0,0,crepe,lacking,0,front,steamy,0,0,0,0,0,0,0,0,0,0,0,0,0,universal,0,0,0,0,0,0,0,0,0,attractive,0,0,0,former,0,good,satisfactory,visita,0,0,0,0,0,nonsense,0,handsome,0,0,0,baked,0,firm,0,0,0,0,0,0,oily,unfair,0,peaceful,certified,0,0,0,0,0,0,0,0,0,alphabetical,0,0,0,0,0,soak,0,greenish,0,0,nabe,0,0,0,0,0
20,offthe,0,envious,0,0,0,0,lighter,sharp,0,unlucky,0,caught,ripening,0,0,waffle,0,0,0,0,0,0,0,0,0,0,admired,unpleasant,0,0,0,yummy,indispensable,0,inward,0,0,0,0,0,0,0,0,0,0,0,0,0,0,instant,0,0,0,0,0,0,0,0,0,0,0,0,0,suspected,0,seasoned,recommended,pang,0,0,0,0,0,precious,0,interior,0,0,0,ingredient,0,downtown,0,0,0,0,0,0,salty,inferior,0,mingling,dedicated,0,0,0,0,0,0,0,0,0,vague,0,0,0,0,0,wiped,0,dark,0,0,0,0,0,0,0,0
21,backin,0,drunk,0,0,0,0,steady,obvious,0,lukewarm,0,built,0,0,0,bacon,0,0,0,0,0,0,0,0,0,0,realized,shocking,0,0,0,delicious,insufficient,0,stationary,0,0,0,0,0,0,0,0,0,0,0,0,0,0,real,0,0,0,0,0,0,0,0,0,0,0,0,0,rumored,0,strongest,0,tong,0,0,0,0,0,hungry,0,stylish,0,0,0,homemade,0,representative,0,0,0,0,0,0,addictive,inconsistent,0,smooth,separate,0,0,0,0,0,0,0,0,0,detailed,0,0,0,0,0,filtered,0,shaped,0,0,0,0,0,0,0,0
22,advantage,0,forgiven,0,0,0,0,muted,repeated,0,sour,0,rang,0,0,0,hamburger,0,0,0,0,0,0,0,0,0,0,okay,ironic,0,0,0,macaroons,vulnerable,0,dead,0,0,0,0,0,0,0,0,0,0,0,0,0,0,zero,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,talented,0,concubine,0,0,0,0,0,righteous,0,0,0,0,0,charcoal,0,visit,0,0,0,0,0,0,drip,excessive,0,nocturnal,subsequent,0,0,0,0,0,0,0,0,0,geographical,0,0,0,0,0,sliced,0,colorless,0,0,0,0,0,0,0,0
23,cloud,0,scolded,0,0,0,0,conservative,subtle,0,disappointing,0,lined,0,0,0,espresso,0,0,0,0,0,0,0,0,0,0,feeling,disturbing,0,0,0,fried,sufficient,0,gun,0,0,0,0,0,0,0,0,0,0,0,0,0,0,quick,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,quality,0,cleanin,0,0,0,0,0,sneaky,0,0,0,0,0,bread,0,location,0,0,0,0,0,0,plastic,dubious,0,satisfying,commercial,0,0,0,0,0,0,0,0,0,certain,0,0,0,0,0,shaving,0,brown,0,0,0,0,0,0,0,0
24,notin,0,shocked,0,0,0,0,heavy,minimal,0,distracting,0,avoided,0,0,0,stew,0,0,0,0,0,0,0,0,0,0,feel,0,0,0,0,spicy,unavoidable,0,bleeding,0,0,0,0,0,0,0,0,0,0,0,0,0,0,static,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,turkish,0,0,0,0,0,fortress,0,0,0,0,0,raw,0,corridor,0,0,0,0,0,0,unrefined,0,0,loud,primary,0,0,0,0,0,0,0,0,0,precise,0,0,0,0,0,shaved,0,exterior,0,0,0,0,0,0,0,0
25,livered,0,unhappy,0,0,0,0,concentrated,intense,0,0,0,seated,0,0,0,cheese,0,0,0,0,0,0,0,0,0,0,thought,0,0,0,0,broiled,eligible,0,defensive,0,0,0,0,0,0,0,0,0,0,0,0,0,0,actual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,tanga,0,0,0,0,0,presbyterian,0,0,0,0,0,oden,0,appointment,0,0,0,0,0,0,soft,0,0,cozy,localized,0,0,0,0,0,0,0,0,0,unclear,0,0,0,0,0,mop,0,white,0,0,0,0,0,0,0,0
26,sum,0,sick,0,0,0,0,narrow,insignificant,0,0,0,guided,0,0,0,grilled,0,0,0,0,0,0,0,0,0,0,sure,0,0,0,0,0,0,0,wrench,0,0,0,0,0,0,0,0,0,0,0,0,0,0,simple,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,norwegian,0,0,0,0,0,orthodoxy,0,0,0,0,0,pickle,0,wireless,0,0,0,0,0,0,sticky,0,0,welcoming,prime,0,0,0,0,0,0,0,0,0,summary,0,0,0,0,0,0,0,yellow,0,0,0,0,0,0,0,0
27,onthe,0,uncomfortable,0,0,0,0,0,unimaginable,0,0,0,unpacked,0,0,0,casserole,0,0,0,0,0,0,0,0,0,0,recognized,0,0,0,0,0,0,0,twisted,0,0,0,0,0,0,0,0,0,0,0,0,0,0,schematic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,hoti,0,0,0,0,0,die,0,0,0,0,0,candy,0,retail,0,0,0,0,0,0,deformed,0,0,busy,personal,0,0,0,0,0,0,0,0,0,sample,0,0,0,0,0,0,0,colored,0,0,0,0,0,0,0,0
28,last,0,sympathetic,0,0,0,0,0,meaningful,0,0,0,scattered,0,0,0,lasagna,0,0,0,0,0,0,0,0,0,0,sadi,0,0,0,0,0,0,0,chest,0,0,0,0,0,0,0,0,0,0,0,0,0,0,automatic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,greek,0,0,0,0,0,alcoholic,0,0,0,0,0,eggs,0,pyeong,0,0,0,0,0,0,acid,0,0,fruitful,profile,0,0,0,0,0,0,0,0,0,weighting,0,0,0,0,0,0,0,inconspicuous,0,0,0,0,0,0,0,0
29,free,0,immature,0,0,0,0,0,blunt,0,0,0,waited,0,0,0,cutlet,0,0,0,0,0,0,0,0,0,0,loved,0,0,0,0,0,0,0,squat,0,0,0,0,0,0,0,0,0,0,0,0,0,0,intentional,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,arti,0,0,0,0,0,primitive,0,0,0,0,0,nut,0,private,0,0,0,0,0,0,smoky,0,0,comfortable,respond,0,0,0,0,0,0,0,0,0,artificial,0,0,0,0,0,0,0,pale,0,0,0,0,0,0,0,0
30,fixed,0,greedy,0,0,0,0,0,radical,0,0,0,sneak,0,0,0,chocolate,0,0,0,0,0,0,0,0,0,0,else,0,0,0,0,0,0,0,table,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,fes,0,0,0,0,0,martial,0,0,0,0,0,salt,0,people,0,0,0,0,0,0,greasy,0,0,mood,collective,0,0,0,0,0,0,0,0,0,varied,0,0,0,0,0,0,0,sky,0,0,0,0,0,0,0,0
31,purpose,0,rue,0,0,0,0,0,slight,0,0,0,answered,0,0,0,porridge,0,0,0,0,0,0,0,0,0,0,remembered,0,0,0,0,0,0,0,upright,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,badi,0,0,0,0,0,beloved,0,0,0,0,0,duck,0,amateur,0,0,0,0,0,0,0,0,0,heated,individual,0,0,0,0,0,0,0,0,0,unspecified,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
32,flows,0,dizzy,0,0,0,0,0,visible,0,0,0,empty,0,0,0,fondue,0,0,0,0,0,0,0,0,0,0,remember,0,0,0,0,0,0,0,head,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,myeong,0,0,0,0,0,faint,0,0,0,0,0,powdered,0,park,0,0,0,0,0,0,0,0,0,relaxed,macro,0,0,0,0,0,0,0,0,0,attached,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,beforethe,0,repentant,0,0,0,0,0,noticeable,0,0,0,rounded,0,0,0,0,0,0,0,0,0,0,0,0,0,0,noticed,0,0,0,0,0,0,0,upper,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,wella,0,0,0,0,0,faithful,0,0,0,0,0,fry,0,nearby,0,0,0,0,0,0,0,0,0,sedentary,potential,0,0,0,0,0,0,0,0,0,equal,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
34,second,0,disturbed,0,0,0,0,0,enormous,0,0,0,waiting,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,bent,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,poori,0,0,0,0,0,golden,0,0,0,0,0,giblet,0,annex,0,0,0,0,0,0,0,0,0,casual,specialized,0,0,0,0,0,0,0,0,0,particular,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35,the,0,stupid,0,0,0,0,0,clear,0,0,0,brought,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,sideways,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,temple,0,0,0,0,0,truth,0,0,0,0,0,straw,0,visitthe,0,0,0,0,0,0,0,0,0,solemn,present,0,0,0,0,0,0,0,0,0,desired,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
36,only,0,crazy,0,0,0,0,0,apparent,0,0,0,leveled,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,lip,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,nepal,0,0,0,0,0,stamina,0,0,0,0,0,hash,0,tent,0,0,0,0,0,0,0,0,0,relaxing,popular,0,0,0,0,0,0,0,0,0,obscure,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
37,but,0,tearful,0,0,0,0,0,major,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,object,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,maltese,0,0,0,0,0,scorn,0,0,0,0,0,freshly,0,public,0,0,0,0,0,0,0,0,0,stimulating,key,0,0,0,0,0,0,0,0,0,distinct,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
38,crude,0,confused,0,0,0,0,0,extreme,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,tee,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,chicky,0,0,0,0,0,eccentric,0,0,0,0,0,carrot,0,international,0,0,0,0,0,0,0,0,0,0,use,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
39,re,0,upset,0,0,0,0,0,mild,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,thump,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,toi,0,0,0,0,0,heavenly,0,0,0,0,0,pot,0,outside,0,0,0,0,0,0,0,0,0,0,ordinary,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,ofthe,0,mad,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,bare,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mei,0,0,0,0,0,virtuous,0,0,0,0,0,frozen,0,vacant,0,0,0,0,0,0,0,0,0,0,comparable,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# remove groups we don't need
# rm_groups = [17, 26, 50, 63]
# for i in rm_groups:
#     group_name = 'group_'+str(i);
#     stop_words.update(set(km_df[group_name].dropna()))
# with open('../data/stop_words.txt','w',-1,'utf-8') as f:
#     f.write('/'.join(stop_words))
eat_info.set_index(eat_info['p_id'],inplace=True,drop=True)
del eat_info['p_id']
eat_info.head()

,name,address,category,main_mn,price,opng_tm,rating,rvw_cnt,tags,reviews
p_id,,,,,,,,,,
304,놀부만두,서울특별시 동대문구 휘경2동 276-33,NaN,냉모밀,6000.0,"{'월-금,일': '오전 11시 - 오후 8시 30분 '}",NaN,NaN,"local,shabby,small,fullthe,cold,deep,thin,bite...","Like a local restaurant, it was moderately sha..."
2234,호반,서울특별시 종로구 낙원동 85-7,NaN,순대국,8000.0,{'매일': '오전 11시 30분 - 오후 10시 (준비시간 15:00~16:30)...,NaN,NaN,"korean,delicious,greatchan,delicioustelephone,...",It is a Korean restaurant located at the edge ...
770,민벅 건대점,서울특별시 광진구 화양동 10-1,NaN,알리오올리오,9900.0,{'매일': '오전 11시 30분 - 오후 10시 (구정 추석 당일 3시 오픈)'},NaN,NaN,"fresh,texture,high,common,cheese,frozen,delici...","If you have 1 menu per person, it will give yo..."
311,뉴델리,서울시 동대문구 회기동 3-182,NaN,치킨 탄두리 (한마리),15000.0,{'매일': '오전 11시 - 오후 10시 '},NaN,NaN,"delicious,indian,old,indian,systemic,long,exot...",You can enjoy delicious Indian curry at an old...
81,강릉스낵,서울특별시 양천구 목동 406-65,NaN,직송 모듬 회,60000.0,"{'월-금': '오후 5시 - 오전 1시 ', '토/일': '오후 4시 - 오전 1...",NaN,NaN,"deliciousthe,fried,crispy,light,delicious,ligh...","Tteokbokki is spicy, so it's delicious.The fri..."

In [ ]:
res_matrix = pd.DataFrame(index=eat_info.index,columns=list(km_df.columns))
user_matrix = pd.DataFrame(index=eat_review_by_user.index,columns=list(km_df.columns))
res_matrix = res_matrix.fillna(0)
user_matrix = user_matrix.fillna(0)

In [ ]:
res_matrix.head()

,group_24,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,group_9,group_10,group_11,group_12,group_13,group_14,group_15,group_16,group_17,group_18,group_19,group_20,group_21,group_22,group_23,group_25,group_26,group_27,group_28,group_29,group_30,group_31,group_32,group_33,group_34,group_35,group_36,group_37,group_38,group_39,group_40,group_41,group_42,group_43,group_44,group_45,group_46,group_47,group_48,group_49,group_50,group_51,group_52,group_53,group_54,group_55,group_56,group_57,group_58,group_59,group_60,group_61,group_62,group_63,group_64,group_65,group_66,group_67,group_68,group_69,group_70,group_71,group_72,group_73,group_74,group_75,group_76,group_77,group_78,group_79,group_80,group_81,group_82,group_83,group_84,group_85,group_86,group_87,group_88,group_89,group_90,group_91,group_92,group_93,group_94,group_95,group_96,group_97,group_98,group_99,group_100,group_101,group_102,group_103,group_104,group_105,group_106,group_107,group_108,group_109,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
304,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2234,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
770,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
311,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
user_matrix.head()

,group_24,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,group_9,group_10,group_11,group_12,group_13,group_14,group_15,group_16,group_17,group_18,group_19,group_20,group_21,group_22,group_23,group_25,group_26,group_27,group_28,group_29,group_30,group_31,group_32,group_33,group_34,group_35,group_36,group_37,group_38,group_39,group_40,group_41,group_42,group_43,group_44,group_45,group_46,group_47,group_48,group_49,group_50,group_51,group_52,group_53,group_54,group_55,group_56,group_57,group_58,group_59,group_60,group_61,group_62,group_63,group_64,group_65,group_66,group_67,group_68,group_69,group_70,group_71,group_72,group_73,group_74,group_75,group_76,group_77,group_78,group_79,group_80,group_81,group_82,group_83,group_84,group_85,group_86,group_87,group_88,group_89,group_90,group_91,group_92,group_93,group_94,group_95,group_96,group_97,group_98,group_99,group_100,group_101,group_102,group_103,group_104,group_105,group_106,group_107,group_108,group_109,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
1616,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
905,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1817,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3911,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
for id in tqdm(res_matrix.index):
    tags = Counter(eat_info.loc[id,'tags'].split(','))
    for tag in tags.keys():
        for num in range(0,cluster_count):
            if tag in set(km_df['group_'+str(num)]):
                res_matrix.loc[id,'group_'+str(num)] += tags[tag]

  0%|          | 0/2314 [00:00<?, ?it/s]

In [ ]:
res_matrix.head()

,group_24,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,group_9,group_10,group_11,group_12,group_13,group_14,group_15,group_16,group_17,group_18,group_19,group_20,group_21,group_22,group_23,group_25,group_26,group_27,group_28,group_29,group_30,group_31,group_32,group_33,group_34,group_35,group_36,group_37,group_38,group_39,group_40,group_41,group_42,group_43,group_44,group_45,group_46,group_47,group_48,group_49,group_50,group_51,group_52,group_53,group_54,group_55,group_56,group_57,group_58,group_59,group_60,group_61,group_62,group_63,group_64,group_65,group_66,group_67,group_68,group_69,group_70,group_71,group_72,group_73,group_74,group_75,group_76,group_77,group_78,group_79,group_80,group_81,group_82,group_83,group_84,group_85,group_86,group_87,group_88,group_89,group_90,group_91,group_92,group_93,group_94,group_95,group_96,group_97,group_98,group_99,group_100,group_101,group_102,group_103,group_104,group_105,group_106,group_107,group_108,group_109,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
304,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2234,1,1,0,0,0,0,0,3,0,0,0,0,1,0,0,0,3,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,5,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,3,0,0,0,0,0,2,0,2,0,0,0,0,0,0,3,0,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
770,4,0,0,0,0,0,0,2,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,3,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
311,3,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2,0,0,0,1,0,2,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
81,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0

In [ ]:
for id in tqdm(user_matrix.index):
    tags = Counter(eat_review_by_user.loc[id,'tags'].split(','))
    for tag in tags.keys():
        for num in range(0,cluster_count):
            if tag in set(km_df['group_'+str(num)]):
                user_matrix.loc[id,'group_'+str(num)] += tags[tag]

  0%|          | 0/6181 [00:00<?, ?it/s]

In [ ]:
user_matrix.head()

,group_24,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,group_9,group_10,group_11,group_12,group_13,group_14,group_15,group_16,group_17,group_18,group_19,group_20,group_21,group_22,group_23,group_25,group_26,group_27,group_28,group_29,group_30,group_31,group_32,group_33,group_34,group_35,group_36,group_37,group_38,group_39,group_40,group_41,group_42,group_43,group_44,group_45,group_46,group_47,group_48,group_49,group_50,group_51,group_52,group_53,group_54,group_55,group_56,group_57,group_58,group_59,group_60,group_61,group_62,group_63,group_64,group_65,group_66,group_67,group_68,group_69,group_70,group_71,group_72,group_73,group_74,group_75,group_76,group_77,group_78,group_79,group_80,group_81,group_82,group_83,group_84,group_85,group_86,group_87,group_88,group_89,group_90,group_91,group_92,group_93,group_94,group_95,group_96,group_97,group_98,group_99,group_100,group_101,group_102,group_103,group_104,group_105,group_106,group_107,group_108,group_109,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
1616,5,0,2,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,4,0,0,0,0,0,0,4,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0
905,18,4,1,0,0,0,0,4,1,0,0,2,0,0,0,0,1,0,0,0,0,0,2,0,2,0,0,0,0,0,0,0,20,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,4,0,1,0,0,0,2,0,0,2,1,0,3,2,0,0,0,0,1,0,3,0,3,0,0,0,0,0,4,0,0,0,0,2,0,5,0,0,1,9,0,0,0,0,1,0,0,0,0,3,0,0,0,0,0,0,5,3,0,0,1,5,3,0,0,0
1817,11,5,3,1,0,0,0,23,4,0,12,0,1,0,1,0,0,0,0,0,0,0,3,0,0,0,0,2,2,0,0,4,68,0,0,0,9,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,3,0,0,0,0,0,0,1,0,5,0,0,4,2,0,0,0,0,0,0,5,0,1,0,0,0,1,0,3,0,0,0,0,1,1,15,1,0,4,20,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,3,7,0,0,1,12,1,0,0,1
3911,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,0,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
user_matrix.head()

,group_24,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,group_9,group_10,group_11,group_12,group_13,group_14,group_15,group_16,group_17,group_18,group_19,group_20,group_21,group_22,group_23,group_25,group_26,group_27,group_28,group_29,group_30,group_31,group_32,group_33,group_34,group_35,group_36,group_37,group_38,group_39,group_40,group_41,group_42,group_43,group_44,group_45,group_46,group_47,group_48,group_49,group_50,group_51,group_52,group_53,group_54,group_55,group_56,group_57,group_58,group_59,group_60,group_61,group_62,group_63,group_64,group_65,group_66,group_67,group_68,group_69,group_70,group_71,group_72,group_73,group_74,group_75,group_76,group_77,group_78,group_79,group_80,group_81,group_82,group_83,group_84,group_85,group_86,group_87,group_88,group_89,group_90,group_91,group_92,group_93,group_94,group_95,group_96,group_97,group_98,group_99,group_100,group_101,group_102,group_103,group_104,group_105,group_106,group_107,group_108,group_109,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
1616,5,0,2,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,5,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,4,0,0,0,0,0,0,4,0,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0
905,18,4,1,0,0,0,0,4,1,0,0,2,0,0,0,0,1,0,0,0,0,0,2,0,2,0,0,0,0,0,0,0,20,0,0,0,24,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,4,0,1,0,0,0,2,0,0,2,1,0,3,2,0,0,0,0,1,0,3,0,3,0,0,0,0,0,4,0,0,0,0,2,0,5,0,0,1,9,0,0,0,0,1,0,0,0,0,3,0,0,0,0,0,0,5,3,0,0,1,5,3,0,0,0
1817,11,5,3,1,0,0,0,23,4,0,12,0,1,0,1,0,0,0,0,0,0,0,3,0,0,0,0,2,2,0,0,4,68,0,0,0,9,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,3,0,0,0,0,0,0,1,0,5,0,0,4,2,0,0,0,0,0,0,5,0,1,0,0,0,1,0,3,0,0,0,0,1,1,15,1,0,4,20,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,3,7,0,0,1,12,1,0,0,1
3911,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,2,0,0,0,0,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
km_df.count()

group_24     157
group_0       19
group_1       46
group_2       14
group_3        2
group_4        2
group_5        5
group_6       27
group_7       40
group_8        7
group_9       25
group_10       6
group_11      37
group_12      21
group_13       2
group_14      20
group_15      33
group_16       4
group_17      10
group_18      15
group_19       3
group_20       1
group_21       5
group_22       8
group_23      16
group_25       1
group_26       8
group_27      34
group_28      24
group_29      13
group_30       6
group_31      16
group_32      26
group_33      26
group_34       5
group_35      58
group_36      20
group_37       1
group_38      12
group_39      16
group_40       1
group_41       9
group_42       7
group_43       3
group_44       5
group_45       1
group_46       6
group_47       2
group_48       6
group_49      11
group_50      30
group_51       4
group_52       4
group_53       1
group_54      16
group_55       5
group_56      10
group_57       2
group_58      11
group_59       2
group_60      20
group_61       5
group_62       8
group_63      13
group_64      22
group_65       1
group_66      24
group_67      21
group_68      45
group_69       2
group_70       5
group_71       1
group_72      10
group_73       1
group_74      79
group_75       9
group_76      22
group_77      10
group_78       2
group_79       1
group_80      43
group_81       1
group_82     103
group_83       6
group_84       2
group_85       1
group_86      16
group_87       4
group_88       7
group_89      31
group_90      24
group_91       1
group_92      38
group_93     127
group_94       1
group_95       4
group_96       1
group_97       5
group_98      13
group_99       2
group_100      1
group_101      3
group_102      2
group_103     38
group_104      1
group_105      1
group_106     13
group_107      3
group_108      7
group_109     26
group_110      7
group_111     31
group_112      2
group_113      9
group_114     20
group_115     11
group_116      8
group_117      1
group_118      4
group_119      3
dtype: int64

In [ ]:
eat_review_score = pd.DataFrame(eat_review, columns=['u_id','p_id','rating'])
eat_review_score.sort_values(by=['u_id'], axis=0,inplace=True)
eat_review_score.reset_index(drop = True, inplace=True)
eat_review_score.head()

   u_id  p_id  rating
0     0   720       4
1     0   360       4
2     1  1656       5
3     1   749       5
4     2  2032       3

In [ ]:
res_matrix.to_csv('/content/drive/MyDrive/ML_data/res_matrix.csv')
user_matrix.to_csv('/content/drive/MyDrive/ML_data/user_matrix.csv')

eat_review_score.to_csv('/content/drive/MyDrive/ML_data/score_board.csv',index=False)

# 클러스터링 결과
km_df.to_csv('/content/drive/MyDrive/ML_data/eat_cluster.csv',index=False)

km_df.count().to_csv('/content/drive/MyDrive/ML_data/group_count.csv')

NCF 모델

In [ ]:
!pip install cornac

Collecting cornac
  Downloading cornac-1.17.0-cp310-cp310-manylinux1_x86_64.whl (21.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.9/21.9 MB 38.7 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from cornac) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from cornac) (1.11.3)
Requirement already satisfied: tqdm>=4.19 in /usr/local/lib/python3.10/dist-packages (from cornac) (4.66.1)
Collecting powerlaw (from cornac)
  Downloading powerlaw-1.5-py3-none-any.whl (24 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from powerlaw->cornac) (3.7.1)
Requirement already satisfied: mpmath in /usr/local/lib/python3.10/dist-packages (from powerlaw->cornac) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (4.44.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->powerlaw->cornac) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->powerlaw->cornac) (1.16.0)
Installing collected packages: powerlaw, cornac
Successfully installed cornac-1.17.0 powerlaw-1.5

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import cornac
import cornac.eval_methods
from cornac.eval_methods import RatioSplit, base_method
from cornac.hyperopt import Continuous, Discrete, RandomSearch
from tqdm import tqdm

import warnings
warnings.filterwarnings(action='ignore')
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)

In [ ]:
# 추천할 top k개의 장소
TOP_K = 10
data_df = pd.read_csv('/content/drive/MyDrive/ML_data/score_board (1).csv', index_col =0)
data_df['rating'] =data_df['rating'].astype('float')

In [ ]:
# # 'u_id'를 열로 변환
# data_df.reset_index(inplace=True)

# 데이터가 잘 처리되었는지 확인
print(data_df)

       u_id  p_id  rating
0         0  3375     3.0
1         0  2778     5.0
2         0   612     5.0
3         0  3949     5.0
4         0  1679     1.0
...     ...   ...     ...
105198    쥬  1679     NaN
105199    쥬  3848     NaN
105200    쥬  1547     NaN
105201    쥬  4080     NaN
105202    쥬  3754     NaN

[105203 rows x 3 columns]

In [ ]:
data_df = data_df.rename({'u_id': 'userID', 'p_id': 'itemID'}, axis=1)

In [ ]:
print(data_df.head())

  userID  itemID  rating
0      0    3375     3.0
1      0    2778     5.0
2      0     612     5.0
3      0    3949     5.0
4      0    1679     1.0

In [ ]:
data = [tuple(x) for x in data_df.values]
data

[('0', 3375, 3.0),
 ('0', 2778, 5.0),
 ('0', 612, 5.0),
 ('0', 3949, 5.0),
 ('0', 1679, 1.0),
 ('0', 4805, 5.0),
 ('0', 287, 3.0),
 ('0', 3601, 5.0),
 ('0', 3526, 5.0),
 ('0', 3601, 5.0),
 ('0', 3357, 5.0),
 ('0', 104, 5.0),
 ('0', 2307, 5.0),
 ('0', 4345, 5.0),
 ('0', 3075, 5.0),
 ('0', 1269, 5.0),
 ('0', 1714, 5.0),
 ('0', 479, 5.0),
 ('0', 1186, 5.0),
 ('0', 3388, 5.0),
 ('0', 5068, 5.0),
 ('0', 5264, 3.0),
 ('0', 1123, 5.0),
 ('0', 3734, 5.0),
 ('0', 1904, 3.0),
 ('0', 4843, 5.0),
 ('0', 616, 5.0),
 ('0', 1092, 5.0),
 ('0', 3529, 5.0),
 ('0', 1254, 5.0),
 ('0', 3118, 5.0),
 ('1', 3612, 5.0),
 ('2', 3441, 5.0),
 ('2', 1737, 5.0),
 ('3', 5334, 5.0),
 ('4', 1127, 5.0),
 ('4', 1846, 5.0),
 ('4', 3415, 5.0),
 ('4', 1666, 5.0),
 ('4', 208, 5.0),
 ('4', 1846, 5.0),
 ('4', 709, 3.0),
 ('4', 177, 5.0),
 ('4', 3415, 5.0),
 ('4', 1846, 5.0),
 ('4', 1368, 5.0),
 ('4', 2382, 5.0),
 ('4', 5153, 5.0),
 ('4', 3761, 5.0),
 ('4', 3761, 5.0),
 ('4', 2910, 5.0),
 ('4', 2091, 5.0),
 ('4', 177, 5.0),
 ('4', 1602, 5.0),
 ('4', 3319, 3.0),
 ('4', 2702, 5.0),
 ('4', 3319, 3.0),
 ('4', 1666, 5.0),
 ('5', 5298, 5.0),
 ('5', 1180, 3.0),
 ('5', 4338, 5.0),
 ('5', 4836, 3.0),
 ('5', 5374, 5.0),
 ('6', 5310, 3.0),
 ('6', 4870, 5.0),
 ('6', 613, 5.0),
 ('6', 4783, 3.0),
 ('6', 4662, 5.0),
 ('6', 5153, 5.0),
 ('6', 5026, 5.0),
 ('6', 177, 5.0),
 ('6', 5163, 3.0),
 ('6', 211, 3.0),
 ('6', 5058, 5.0),
 ('6', 4153, 5.0),
 ('6', 1134, 3.0),
 ('6', 4153, 5.0),
 ('6', 3830, 3.0),
 ('6', 1863, 5.0),
 ('6', 3308, 3.0),
 ('6', 5153, 5.0),
 ('6', 3379, 5.0),
 ('6', 1169, 5.0),
 ('6', 3912, 5.0),
 ('6', 1846, 5.0),
 ('6', 1679, 5.0),
 ('6', 1169, 5.0),
 ('6', 4651, 5.0),
 ('6', 5251, 5.0),
 ('7', 1036, 3.0),
 ('8', 1891, 5.0),
 ('9', 3383, 5.0),
 ('9', 2307, 5.0),
 ('9', 4662, 5.0),
 ('10', 5277, 5.0),
 ('11', 4143, 5.0),
 ('11', 4163, 3.0),
 ('12', 2013, 3.0),
 ('12', 1685, 3.0),
 ('12', 4843, 5.0),
 ('12', 4152, 5.0),
 ('12', 1036, 5.0),
 ('13', 4283, 3.0),
 ('13', 39, 1.0),
 ('14', 643, 1.0),
 ('15', 4843, 5.0),
 ('15', 1012, 3.0),
 ('16', 3249, 5.0),
 ('17', 502, 1.0),
 ('17', 1293, 5.0),
 ('17', 5445, 5.0),
 ('17', 2468, 5.0),
 ('17', 1793, 5.0),
 ('17', 1410, 5.0),
 ('17', 1780, 5.0),
 ('17', 1393, 5.0),
 ('17', 158, 5.0),
 ('17', 3541, 3.0),
 ('18', 930, 5.0),
 ('18', 2160, 5.0),
 ('18', 1696, 5.0),
 ('18', 4843, 5.0),
 ('18', 4931, 5.0),
 ('19', 1979, 5.0),
 ('20', 3848, 5.0),
 ('20', 1036, 5.0),
 ('20', 802, 5.0),
 ('20', 2231, 3.0),
 ('21', 4758, 5.0),
 ('21', 4962, 5.0),
 ('21', 3811, 5.0),
 ('21', 3379, 1.0),
 ('21', 3253, 3.0),
 ('21', 5327, 1.0),
 ('21', 3216, 5.0),
 ('21', 1621, 1.0),
 ('22', 4245, 5.0),
 ('22', 3848, 5.0),
 ('23', 1371, 5.0),
 ('23', 192, 5.0),
 ('23', 2483, 5.0),
 ('23', 2177, 5.0),
 ('23', 1226, 5.0),
 ('23', 4163, 5.0),
 ('23', 765, 5.0),
 ('24', 4529, 3.0),
 ('25', 2307, 5.0),
 ('25', 3083, 3.0),
 ('25', 1724, 5.0),
 ('25', 3601, 1.0),
 ('25', 4213, 1.0),
 ('25', 3501, 1.0),
 ('25', 3375, 5.0),
 ('26', 2165, 3.0),
 ('27', 3690, 5.0),
 ('28', 1050, 5.0),
 ('28', 2531, 5.0),
 ('28', 2008, 5.0),
 ('28', 4255, 5.0),
 ('28', 2073, 1.0),
 ('28', 3255, 3.0),
 ('28', 4812, 1.0),
 ('28', 2088, 5.0),
 ('28', 5218, 3.0),
 ('28', 5415, 5.0),
 ('28', 922, 3.0),
 ('28', 297, 1.0),
 ('28', 1246, 5.0),
 ('28', 2253, 3.0),
 ('28', 3861, 3.0),
 ('28', 412, 5.0),
 ('28', 782, 1.0),
 ('28', 3274, 3.0),
 ('28', 5043, 3.0),
 ('28', 3156, 5.0),
 ('28', 2035, 3.0),
 ('28', 4080, 5.0),
 ('28', 922, 3.0),
 ('28', 1859, 5.0),
 ('28', 1467, 1.0),
 ('28', 2052, 3.0),
 ('28', 1618, 3.0),
 ('28', 4995, 3.0),
 ('28', 4900, 5.0),
 ('28', 3277, 3.0),
 ('28', 3171, 1.0),
 ('28', 2402, 5.0),
 ('28', 5201, 3.0),
 ('28', 1368, 3.0),
 ('28', 403, 5.0),
 ('28', 4331, 3.0),
 ('28', 5283, 3.0),
 ('28', 3156, 5.0),
 ('28', 4804, 1.0),
 ('28', 1499, 3.0),
 ('28', 375, 1.0),
 ('28', 4255, 3.0),
 ('28', 4484, 3.0),
 ('28', 4980, 3.0),
 ('28', 3673, 5.0),
 ('28', 3770, 1.0),
 ('28', 1406, 3.0),
 ('28', 1537, 3.0),
 ('28', 565, 5.0),
 ('28', 3886, 1.0),
 ('28', 4013, 5.0),
 ('28', 2301, 3.0),
 ('28', 920, 3.0),
 ('28', 5162, 5.0),
 ('28', 4777, 3.0),
 ('28', 1866, 3.0),
 ('28', 1206, 5.0),
 ('28', 3714, 3.0),
 ('28', 229, 3.0),
 ('28', 1780, 3.0),
 ('28', 3789, 3.0),
 ('28', 5298, 5.0),
 ('28', 2052, 1.0),
 ('28', 4067, 3.0),
 ('28', 4557, 3.0),
 ('28', 3784, 3.0),
 ('28', 1755, 5.0),
 ('28', 1496, 3.0),
 ('28', 3848, 3.0),
 ('28', 813, 5.0),
 ('28', 2035, 3.0),
 ('28', 2708, 5.0),
 ('28', 3297, 5.0),
 ('28', 1496, 5.0),
 ('28', 1194, 1.0),
 ('28', 3651, 3.0),
 ('28', 1866, 3.0),
 ('28', 3991, 3.0),
 ('28', 2889, 3.0),
 ('28', 2901, 3.0),
 ('28', 2527, 5.0),
 ('28', 995, 1.0),
 ('28', 1955, 1.0),
 ('28', 5251, 3.0),
 ('28', 962, 3.0),
 ('28', 2468, 3.0),
 ('28', 5158, 5.0),
 ('28', 3811, 3.0),
 ('28', 5146, 5.0),
 ('28', 4309, 5.0),
 ('28', 3830, 3.0),
 ('28', 3531, 3.0),
 ('28', 3600, 3.0),
 ('28', 5038, 3.0),
 ('28', 412, 3.0),
 ('28', 2045, 1.0),
 ('28', 4781, 3.0),
 ('28', 3830, 3.0),
 ('28', 5174, 3.0),
 ('28', 332, 5.0),
 ('28', 1335, 3.0),
 ('28', 2177, 3.0),
 ('28', 4309, 3.0),
 ('28', 851, 3.0),
 ('28', 4904, 3.0),
 ('28', 2831, 1.0),
 ('28', 4107, 3.0),
 ('28', 451, 5.0),
 ('28', 4309, 3.0),
 ('28', 1496, 3.0),
 ('28', 2614, 5.0),
 ('28', 2270, 5.0),
 ('28', 4184, 1.0),
 ('28', 4130, 3.0),
 ('28', 1699, 5.0),
 ('28', 121, 3.0),
 ('28', 514, 5.0),
 ('28', 3608, 5.0),
 ('28', 2916, 5.0),
 ('28', 853, 3.0),
 ('28', 3851, 3.0),
 ('28', 2750, 5.0),
 ('28', 825, 3.0),
 ('28', 2270, 3.0),
 ('28', 3830, 3.0),
 ('28', 4558, 1.0),
 ('28', 412, 3.0),
 ('28', 3209, 3.0),
 ('28', 1204, 3.0),
 ('28', 2586, 5.0),
 ('28', 851, 5.0),
 ('28', 582, 3.0),
 ('28', 1269, 3.0),
 ('28', 418, 3.0),
 ('28', 2781, 1.0),
 ('28', 3805, 3.0),
 ('28', 5137, 3.0),
 ('28', 4758, 5.0),
 ('28', 3156, 5.0),
 ('28', 3243, 3.0),
 ('28', 4574, 5.0),
 ('28', 4309, 3.0),
 ('28', 2903, 3.0),
 ('28', 3029, 5.0),
 ('28', 2238, 1.0),
 ('28', 1246, 3.0),
 ('28', 3886, 5.0),
 ('28', 2781, 1.0),
 ('28', 2577, 3.0),
 ('28', 3817, 3.0),
 ('28', 2211, 5.0),
 ('28', 2466, 3.0),
 ('28', 1402, 3.0),
 ('28', 4184, 3.0),
 ('28', 4149, 5.0),
 ('28', 3751, 3.0),
 ('28', 4650, 3.0),
 ('28', 148, 3.0),
 ('28', 1246, 3.0),
 ('28', 3835, 5.0),
 ('28', 4728, 3.0),
 ('28', 5273, 3.0),
 ('28', 3136, 5.0),
 ('28', 2201, 3.0),
 ('28', 1847, 3.0),
 ('28', 805, 5.0),
 ('28', 4551, 3.0),
 ('28', 1720, 3.0),
 ('28', 2414, 3.0),
 ('29', 99, 3.0),
 ('29', 3598, 3.0),
 ('29', 1361, 3.0),
 ('29', 1755, 5.0),
 ('29', 3035, 5.0),
 ('29', 4385, 3.0),
 ('29', 2588, 5.0),
 ('29', 950, 5.0),
 ('29', 1903, 5.0),
 ('29', 4758, 5.0),
 ('29', 856, 5.0),
 ('29', 2576, 3.0),
 ('29', 529, 5.0),
 ('29', 5114, 3.0),
 ('29', 3933, 5.0),
 ('29', 1252, 5.0),
 ('29', 4549, 5.0),
 ('29', 1368, 5.0),
 ('29', 2820, 3.0),
 ('29', 1901, 3.0),
 ('29', 2846, 5.0),
 ('29', 1393, 5.0),
 ('29', 3542, 5.0),
 ('29', 3894, 5.0),
 ('29', 2002, 5.0),
 ('29', 2820, 1.0),
 ('29', 3292, 3.0),
 ('29', 2270, 5.0),
 ('29', 3053, 3.0),
 ('29', 2546, 1.0),
 ('29', 4353, 5.0),
 ('29', 4899, 3.0),
 ('29', 5120, 3.0),
 ('29', 4169, 5.0),
 ('29', 2160, 3.0),
 ('29', 2238, 5.0),
 ('29', 4417, 5.0),
 ('29', 4005, 5.0),
 ('29', 1366, 3.0),
 ('29', 637, 3.0),
 ('29', 3539, 3.0),
 ('29', 2685, 3.0),
 ('29', 847, 5.0),
 ('29', 1164, 3.0),
 ('29', 5127, 5.0),
 ('29', 5127, 1.0),
 ('29', 5114, 3.0),
 ('29', 704, 5.0),
 ('29', 4565, 3.0),
 ('29', 1504, 3.0),
 ('29', 4393, 1.0),
 ('29', 832, 5.0),
 ('29', 3549, 3.0),
 ('29', 3626, 3.0),
 ('29', 4950, 3.0),
 ('29', 4694, 5.0),
 ('29', 3320, 5.0),
 ('29', 969, 5.0),
 ('29', 5094, 5.0),
 ('29', 4364, 3.0),
 ('29', 1978, 5.0),
 ('29', 71, 5.0),
 ('29', 2052, 3.0),
 ('29', 916, 3.0),
 ('29', 4066, 5.0),
 ('29', 509, 3.0),
 ('29', 4645, 3.0),
 ('29', 2665, 3.0),
 ('29', 4758, 5.0),
 ('29', 1468, 5.0),
 ('29', 1494, 3.0),
 ('29', 3115, 5.0),
 ('29', 1036, 5.0),
 ('29', 509, 1.0),
 ('29', 509, 5.0),
 ('29', 1331, 5.0),
 ('29', 3005, 3.0),
 ('29', 3423, 5.0),
 ('29', 1398, 5.0),
 ('29', 3908, 5.0),
 ('29', 674, 5.0),
 ('29', 1448, 5.0),
 ('29', 848, 3.0),
 ('29', 4646, 3.0),
 ('29', 2850, 3.0),
 ('29', 2909, 5.0),
 ('29', 1675, 1.0),
 ('29', 9, 3.0),
 ('29', 2560, 5.0),
 ('29', 1251, 3.0),
 ('29', 2233, 3.0),
 ('29', 612, 3.0),
 ('29', 2489, 3.0),
 ('29', 4066, 1.0),
 ('29', 674, 3.0),
 ('29', 3233, 5.0),
 ('29', 1961, 3.0),
 ('29', 9, 5.0),
 ('29', 3186, 5.0),
 ('29', 3501, 3.0),
 ('29', 17, 5.0),
 ('29', 3889, 5.0),
 ('29', 1504, 5.0),
 ('29', 925, 5.0),
 ('29', 2897, 3.0),
 ('29', 154, 3.0),
 ('29', 616, 5.0),
 ('29', 4827, 5.0),
 ('29', 4184, 5.0),
 ('29', 4946, 5.0),
 ('29', 1125, 1.0),
 ('29', 854, 1.0),
 ('29', 1256, 3.0),
 ('29', 2433, 3.0),
 ('29', 606, 5.0),
 ('29', 2505, 3.0),
 ('29', 848, 5.0),
 ('29', 4908, 5.0),
 ('29', 970, 5.0),
 ('29', 5264, 3.0),
 ('29', 2416, 5.0),
 ('29', 1697, 3.0),
 ('29', 1399, 5.0),
 ('29', 948, 3.0),
 ('29', 4831, 3.0),
 ('29', 3022, 1.0),
 ('29', 4662, 3.0),
 ('29', 4758, 5.0),
 ('29', 1351, 5.0),
 ('29', 1699, 5.0),
 ('29', 4152, 3.0),
 ('29', 1685, 1.0),
 ('29', 4728, 5.0),
 ('29', 624, 3.0),
 ('29', 1289, 5.0),
 ('29', 5013, 1.0),
 ('29', 4758, 5.0),
 ('29', 2199, 5.0),
 ('29', 832, 5.0),
 ('29', 1648, 3.0),
 ('29', 1685, 3.0),
 ('29', 1770, 5.0),
 ('29', 4066, 5.0),
 ('29', 4915, 5.0),
 ('29', 183, 5.0),
 ('29', 1344, 3.0),
 ('29', 3669, 1.0),
 ('29', 4364, 1.0),
 ('29', 3767, 3.0),
 ('29', 3006, 3.0),
 ('29', 1582, 3.0),
 ('29', 2449, 5.0),
 ('29', 4944, 5.0),
 ('29', 4758, 5.0),
 ('29', 745, 5.0),
 ('29', 2999, 5.0),
 ('29', 3375, 3.0),
 ('29', 1724, 5.0),
 ('29', 1820, 3.0),
 ('30', 2592, 5.0),
 ('30', 3526, 5.0),
 ('30', 362, 5.0),
 ('31', 2776, 5.0),
 ('31', 523, 5.0),
 ('32', 4523, 1.0),
 ('33', 3934, 3.0),
 ('34', 1047, 5.0),
 ('35', 2013, 5.0),
 ('35', 2523, 5.0),
 ('35', 4936, 5.0),
 ('36', 4866, 3.0),
 ('36', 3497, 5.0),
 ('37', 4049, 1.0),
 ('37', 399, 5.0),
 ('38', 923, 5.0),
 ('38', 4586, 5.0),
 ('38', 5374, 3.0),
 ('38', 823, 1.0),
 ('38', 588, 5.0),
 ('39', 3895, 3.0),
 ('40', 1392, 5.0),
 ('41', 1070, 5.0),
 ('41', 4586, 5.0),
 ('42', 2717, 5.0),
 ('42', 2468, 5.0),
 ('42', 1501, 1.0),
 ('42', 573, 3.0),
 ('42', 4183, 5.0),
 ('42', 344, 5.0),
 ('42', 3816, 3.0),
 ('42', 513, 5.0),
 ('42', 4579, 5.0),
 ('42', 2905, 5.0),
 ('42', 2489, 5.0),
 ('42', 3448, 3.0),
 ('42', 832, 5.0),
 ('42', 2340, 3.0),
 ('42', 2292, 5.0),
 ('42', 945, 5.0),
 ('42', 2588, 5.0),
 ('42', 823, 5.0),
 ('42', 1876, 1.0),
 ('42', 5026, 5.0),
 ('42', 3269, 3.0),
 ('42', 4804, 5.0),
 ('42', 4870, 5.0),
 ('42', 4596, 1.0),
 ('42', 4987, 5.0),
 ('42', 5335, 3.0),
 ('42', 2317, 5.0),
 ('42', 3784, 5.0),
 ('42', 4936, 5.0),
 ('42', 5005, 5.0),
 ('42', 405, 3.0),
 ('42', 3848, 3.0),
 ('42', 822, 1.0),
 ('42', 2434, 5.0),
 ('42', 4640, 5.0),
 ('42', 3230, 5.0),
 ('42', 2913, 3.0),
 ('42', 3674, 3.0),
 ('42', 1499, 5.0),
 ('42', 2013, 5.0),
 ('42', 754, 5.0),
 ('42', 5416, 3.0),
 ('42', 2774, 5.0),
 ('42', 3705, 5.0),
 ('42', 4662, 5.0),
 ('42', 2610, 5.0),
 ('42', 1030, 5.0),
 ('42', 4586, 5.0),
 ('42', 782, 5.0),
 ('42', 3269, 3.0),
 ('42', 4870, 5.0),
 ('42', 3416, 5.0),
 ('42', 193, 5.0),
 ('42', 3851, 5.0),
 ('42', 2611, 5.0),
 ('42', 2916, 1.0),
 ('42', 5032, 3.0),
 ('42', 3292, 5.0),
 ('42', 4530, 1.0),
 ('42', 2701, 3.0),
 ('42', 1662, 3.0),
 ('42', 2512, 5.0),
 ('42', 1946, 5.0),
 ('42', 962, 5.0),
 ('42', 5, 5.0),
 ('42', 2580, 3.0),
 ('42', 4619, 5.0),
 ('42', 2219, 5.0),
 ('42', 1030, 1.0),
 ('42', 4962, 5.0),
 ('42', 1226, 5.0),
 ('42', 2231, 5.0),
 ('42', 1695, 5.0),
 ('42', 2509, 5.0),
 ('42', 2651, 3.0),
 ('42', 1371, 5.0),
 ('42', 4651, 5.0),
 ('42', 4361, 5.0),
 ('42', 920, 5.0),
 ('42', 4866, 5.0),
 ('42', 4342, 5.0),
 ('42', 1422, 1.0),
 ('42', 3140, 5.0),
 ('42', 612, 5.0),
 ('42', 1361, 5.0),
 ('42', 637, 5.0),
 ('42', 1771, 3.0),
 ('42', 3648, 5.0),
 ('42', 289, 5.0),
 ('42', 1757, 3.0),
 ('42', 3053, 3.0),
 ('42', 802, 5.0),
 ('42', 420, 5.0),
 ('42', 4777, 3.0),
 ('42', 2708, 5.0),
 ('42', 4884, 3.0),
 ('42', 1198, 3.0),
 ('42', 631, 5.0),
 ('42', 3663, 5.0),
 ('42', 3311, 1.0),
 ('42', 971, 5.0),
 ('42', 1398, 5.0),
 ('42', 4530, 5.0),
 ('42', 1398, 5.0),
 ('42', 3145, 5.0),
 ('42', 265, 5.0),
 ('42', 161, 5.0),
 ('42', 3816, 1.0),
 ('42', 966, 3.0),
 ('42', 1371, 5.0),
 ('42', 2913, 5.0),
 ('42', 1256, 5.0),
 ('42', 3470, 3.0),
 ('42', 3115, 5.0),
 ('42', 121, 5.0),
 ('42', 4169, 5.0),
 ('42', 4925, 3.0),
 ('42', 1780, 5.0),
 ('42', 4205, 5.0),
 ('42', 3401, 3.0),
 ('42', 1546, 5.0),
 ('42', 4647, 3.0),
 ('42', 3378, 5.0),
 ('42', 3931, 5.0),
 ('42', 714, 1.0),
 ('42', 3118, 5.0),
 ('42', 3415, 3.0),
 ('42', 714, 5.0),
 ('42', 3075, 1.0),
 ('42', 2577, 3.0),
 ('42', 2383, 5.0),
 ('42', 1808, 5.0),
 ('42', 2081, 3.0),
 ('42', 3394, 5.0),
 ('42', 1618, 5.0),
 ('42', 3057, 1.0),
 ('42', 3461, 1.0),
 ('42', 2368, 3.0),
 ('42', 1047, 1.0),
 ('42', 5195, 3.0),
 ('42', 2088, 5.0),
 ('42', 1357, 5.0),
 ('42', 2088, 5.0),
 ('42', 4931, 5.0),
 ('42', 3719, 5.0),
 ('42', 5276, 1.0),
 ('42', 130, 5.0),
 ('42', 1700, 3.0),
 ('42', 1658, 3.0),
 ('42', 1666, 5.0),
 ('42', 5276, 5.0),
 ('42', 4523, 5.0),
 ('42', 4804, 5.0),
 ('42', 1679, 5.0),
 ('42', 564, 3.0),
 ('42', 1986, 1.0),
 ('42', 4804, 5.0),
 ('42', 1789, 1.0),
 ('42', 1293, 5.0),
 ('42', 17, 5.0),
 ('42', 891, 5.0),
 ('42', 3423, 1.0),
 ('42', 3097, 1.0),
 ('42', 5283, 1.0),
 ('42', 3736, 5.0),
 ('42', 2610, 3.0),
 ('42', 538, 3.0),
 ('42', 2278, 5.0),
 ('42', 5122, 5.0),
 ('42', 9, 3.0),
 ('42', 4181, 5.0),
 ('42', 2231, 5.0),
 ('42', 3382, 5.0),
 ('42', 2541, 5.0),
 ('42', 2309, 5.0),
 ('42', 971, 3.0),
 ('42', 2577, 5.0),
 ('42', 4420, 1.0),
 ('42', 3477, 5.0),
 ('42', 2347, 3.0),
 ('42', 4018, 5.0),
 ('42', 4018, 5.0),
 ('42', 3477, 5.0),
 ('42', 899, 5.0),
 ('42', 5097, 5.0),
 ('42', 3243, 3.0),
 ('42', 1895, 5.0),
 ('42', 5026, 5.0),
 ('42', 2185, 5.0),
 ('42', 3855, 3.0),
 ('42', 4560, 3.0),
 ('42', 1284, 3.0),
 ('42', 2541, 3.0),
 ('42', 1811, 5.0),
 ('42', 4777, 5.0),
 ('42', 3912, 5.0),
 ('42', 3745, 5.0),
 ('42', 4716, 1.0),
 ('42', 3487, 3.0),
 ('42', 4642, 1.0),
 ('42', 1331, 1.0),
 ('42', 158, 5.0),
 ('42', 222, 5.0),
 ('43', 4018, 5.0),
 ('43', 2423, 5.0),
 ('43', 5027, 1.0),
 ('43', 3651, 5.0),
 ('43', 867, 4.0),
 ('43', 2608, 1.0),
 ('43', 2746, 5.0),
 ('43', 1593, 1.0),
 ('43', 5355, 3.0),
 ('43', 5337, 5.0),
 ('43', 2841, 1.0),
 ('43', 1713, 4.0),
 ('44', 4758, 5.0),
 ('44', 5389, 5.0),
 ('44', 3375, 5.0),
 ('44', 2372, 1.0),
 ('45', 5384, 5.0),
 ('46', 3018, 3.0),
 ('47', 1125, 5.0),
 ('47', 412, 5.0),
 ('47', 1675, 5.0),
 ('47', 1675, 5.0),
 ('47', 4827, 5.0),
 ('48', 4586, 3.0),
 ('48', 1148, 1.0),
 ('49', 1695, 5.0),
 ('50', 3238, 5.0),
 ('50', 3059, 3.0),
 ('50', 2885, 3.0),
 ('50', 4283, 3.0),
 ('50', 168, 3.0),
 ('50', 1212, 1.0),
 ('50', 4647, 3.0),
 ('50', 4981, 3.0),
 ('50', 3490, 5.0),
 ('50', 1847, 3.0),
 ('50', 3315, 5.0),
 ('50', 4517, 5.0),
 ('50', 5031, 5.0),
 ('50', 3430, 3.0),
 ('50', 1876, 5.0),
 ('50', 4620, 3.0),
 ('50', 825, 3.0),
 ('50', 4484, 5.0),
 ('50', 4112, 3.0),
 ('50', 1198, 5.0),
 ('50', 813, 5.0),
 ('50', 2827, 5.0),
 ('50', 3988, 3.0),
 ('50', 1847, 3.0),
 ('50', 3988, 3.0),
 ('50', 1551, 5.0),
 ('51', 4255, 3.0),
 ('51', 3136, 3.0),
 ('51', 5374, 5.0),
 ('52', 4854, 3.0),
 ('52', 3277, 5.0),
 ('53', 3839, 5.0),
 ('54', 704, 5.0),
 ('55', 1738, 5.0),
 ('55', 953, 5.0),
 ('55', 2576, 5.0),
 ('55', 2576, 5.0),
 ('55', 1222, 5.0),
 ('55', 2637, 5.0),
 ('55', 5321, 5.0),
 ('55', 4861, 3.0),
 ('55', 4843, 3.0),
 ('55', 1036, 5.0),
 ('55', 4646, 5.0),
 ('55', 3705, 5.0),
 ('55', 1631, 1.0),
 ('55', 1251, 5.0),
 ('55', 479, 5.0),
 ('55', 1360, 5.0),
 ('55', 1219, 5.0),
 ('55', 154, 5.0),
 ('55', 4583, 5.0),
 ('55', 1771, 3.0),
 ('55', 5026, 5.0),
 ('55', 2204, 5.0),
 ('55', 2768, 5.0),
 ('55', 4719, 5.0),
 ('55', 3838, 5.0),
 ('55', 4758, 5.0),
 ('55', 1705, 5.0),
 ('55', 1859, 5.0),
 ('55', 4758, 5.0),
 ('55', 463, 3.0),
 ('55', 1306, 1.0),
 ('55', 5460, 5.0),
 ('55', 5264, 5.0),
 ('55', 3569, 5.0),
 ('55', 2531, 5.0),
 ('55', 4886, 5.0),
 ('55', 4125, 5.0),
 ('55', 5460, 5.0),
 ('55', 4855, 5.0),
 ('55', 959, 3.0),
 ('55', 987, 5.0),
 ('55', 2160, 5.0),
 ('55', 4719, 5.0),
 ('56', 421, 5.0),
 ('57', 813, 5.0),
 ('58', 3487, 5.0),
 ('59', 2561, 5.0),
 ('59', 4477, 5.0),
 ('59', 1496, 5.0),
 ('59', 4825, 5.0),
 ('59', 5033, 5.0),
 ('59', 4274, 5.0),
 ('59', 4929, 5.0),
 ('60', 2670, 3.0),
 ('60', 5011, 1.0),
 ('60', 1251, 5.0),
 ('60', 4345, 5.0),
 ('60', 3701, 5.0),
 ('61', 3705, 5.0),
 ('61', 5294, 3.0),
 ('61', 1112, 3.0),
 ('61', 1963, 5.0),
 ('61', 4184, 3.0),
 ('61', 2446, 5.0),
 ('61', 3283, 3.0),
 ('61', 490, 5.0),
 ('61', 4372, 5.0),
 ('62', 5035, 5.0),
 ('62', 4183, 5.0),
 ('62', 2651, 1.0),
 ('63', 2546, 5.0),
 ('63', 4886, 5.0),
 ('63', 5380, 3.0),
 ('63', 1712, 5.0),
 ('64', 3002, 1.0),
 ('64', 1793, 5.0),
 ('64', 425, 5.0),
 ('64', 1226, 5.0),
 ('64', 2259, 5.0),
 ('64', 4650, 5.0),
 ('64', 4143, 5.0),
 ('64', 1254, 3.0),
 ('64', 3886, 5.0),
 ('64', 689, 3.0),
 ('64', 4995, 3.0),
 ('64', 4018, 5.0),
 ('64', 925, 3.0),
 ('64', 1125, 3.0),
 ('64', 514, 5.0),
 ('64', 3964, 5.0),
 ('64', 4331, 5.0),
 ('64', 3931, 5.0),
 ('64', 2340, 3.0),
 ('64', 2211, 5.0),
 ('64', 4152, 3.0),
 ('64', 4613, 3.0),
 ('64', 5442, 5.0),
 ('64', 3243, 3.0),
 ('64', 4944, 5.0),
 ('64', 3388, 3.0),
 ('64', 5392, 5.0),
 ('64', 2457, 5.0),
 ('64', 1937, 3.0),
 ('64', 1882, 3.0),
 ('64', 693, 3.0),
 ('64', 2270, 3.0),
 ('64', 1932, 3.0),
 ('64', 412, 5.0),
 ('65', 1448, 5.0),
 ('65', 3838, 3.0),
 ('66', 1818, 5.0),
 ('67', 3967, 5.0),
 ('68', 2899, 3.0),
 ('68', 5171, 3.0),
 ('68', 200, 5.0),
 ('68', 20, 3.0),
 ('68', 5139, 5.0),
 ('68', 3115, 3.0),
 ('68', 3982, 5.0),
 ('68', 542, 3.0),
 ('69', 3047, 1.0),
 ('69', 1987, 5.0),
 ('70', 1685, 5.0),
 ('70', 3446, 3.0),
 ('70', 3440, 5.0),
 ('70', 4697, 3.0),
 ('70', 3047, 3.0),
 ('70', 2632, 5.0),
 ('71', 3140, 5.0),
 ('71', 1618, 5.0),
 ('72', 2260, 1.0),
 ('72', 1793, 1.0),
 ('73', 3692, 5.0),
 ('74', 4038, 3.0),
 ('74', 3017, 5.0),
 ('75', 1448, 3.0),
 ('75', 5330, 3.0),
 ('75', 1754, 5.0),
 ('75', 3805, 5.0),
 ('76', 3811, 5.0),
 ('76', 3578, 5.0),
 ('76', 1251, 5.0),
 ('76', 3745, 5.0),
 ('76', 919, 5.0),
 ('77', 4815, 5.0),
 ('78', 4936, 3.0),
 ('79', 1658, 3.0),
 ('79', 4611, 5.0),
 ('80', 5422, 5.0),
 ('81', 1932, 5.0),
 ('82', 3895, 5.0),
 ('82', 848, 5.0),
 ('82', 2260, 5.0),
 ('82', 2177, 5.0),
 ('82', 2310, 3.0),
 ('82', 1361, 5.0),
 ('82', 1926, 5.0),
 ('82', 4107, 5.0),
 ('82', 5337, 3.0),
 ('82', 2723, 5.0),
 ('83', 200, 5.0),
 ('84', 2221, 5.0),
 ('84', 3647, 1.0),
 ('84', 2528, 5.0),
 ('84', 3839, 1.0),
 ('84', 1303, 5.0),
 ('85', 502, 5.0),
 ('85', 431, 5.0),
 ('85', 4028, 5.0),
 ('86', 1691, 5.0),
 ('86', 3525, 5.0),
 ('87', 4184, 5.0),
 ('87', 102, 5.0),
 ('87', 1499, 5.0),
 ('88', 4301, 5.0),
 ('88', 387, 3.0),
 ('89', 2538, 1.0),
 ('90', 5311, 5.0),
 ('90', 1818, 5.0),
 ('90', 917, 5.0),
 ('91', 4917, 3.0),
 ('91', 2032, 5.0),
 ('91', 2032, 5.0),
 ('91', 2737, 3.0),
 ('91', 464, 3.0),
 ('91', 4353, 5.0),
 ('91', 2144, 3.0),
 ('91', 358, 1.0),
 ('91', 1207, 1.0),
 ('91', 487, 1.0),
 ('91', 4651, 3.0),
 ('91', 3113, 3.0),
 ('91', 5375, 3.0),
 ('91', 1879, 3.0),
 ('91', 3431, 3.0),
 ('91', 2632, 3.0),
 ('91', 4169, 3.0),
 ('91', 3379, 5.0),
 ('91', 4557, 3.0),
 ('91', 3145, 3.0),
 ('91', 5062, 3.0),
 ('91', 262, 3.0),
 ('91', 1780, 5.0),
 ('91', 1216, 1.0),
 ('91', 2807, 1.0),
 ('91', 2195, 1.0),
 ('91', 537, 1.0),
 ('91', 362, 3.0),
 ('91', 2979, 5.0),
 ('91', 4586, 3.0),
 ('91', 643, 3.0),
 ('91', 3875, 3.0),
 ('91', 1669, 1.0),
 ('91', 148, 3.0),
 ('91', 3912, 1.0),
 ('92', 2606, 5.0),
 ('93', 2464, 3.0),
 ('93', 3797, 5.0),
 ('94', 148, 5.0),
 ('94', 832, 5.0),
 ('94', 2665, 5.0),
 ('94', 2032, 5.0),
 ('95', 609, 1.0),
 ('96', 916, 5.0),
 ('97', 3705, 5.0),
 ('97', 3292, 5.0),
 ('97', 3043, 3.0),
 ('97', 405, 5.0),
 ('97', 3428, 3.0),
 ('97', 570, 5.0),
 ('97', 2042, 3.0),
 ...]

In [ ]:
# Instantiate evaluation metrics
ndcg = cornac.metrics.NDCG(k=TOP_K)
pre = cornac.metrics.Precision(k=TOP_K)
rec = cornac.metrics.Recall(k=TOP_K)
fm = cornac.metrics.FMeasure(k=TOP_K)

In [ ]:
# Assuming data is a list of records
for record in data:
    print(record)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
('21159', 4599, 1.0)
('21159', 5337, 3.0)
('21159', 1811, 5.0)
('21159', 4680, 3.0)
('21160', 920, 5.0)
('21160', 4899, 5.0)
('21160', 1618, 5.0)
('21160', 4080, 5.0)
('21160', 5273, 5.0)
('21161', 1853, 4.0)
('21162', 2632, 5.0)
('21162', 2278, 5.0)
('21162', 3931, 5.0)
('21162', 4142, 5.0)
('21163', 3673, 5.0)
('21164', 2309, 1.0)
('21164', 585, 1.0)
('21165', 529, 5.0)
('21165', 1125, 3.0)
('21165', 412, 5.0)
('21165', 4558, 5.0)
('21165', 1789, 5.0)
('21165', 4576, 1.0)
('21165', 538, 5.0)
('21165', 5011, 1.0)
('21165', 4153, 5.0)
('21165', 4694, 5.0)
('21165', 4274, 1.0)
('21165', 1646, 5.0)
('21165', 3233, 5.0)
('21165', 3218, 5.0)
('21165', 4539, 5.0)
('21165', 948, 5.0)
('21165', 2278, 5.0)
('21165', 4224, 5.0)
('21165', 2283, 5.0)
('21165', 2864, 5.0)
('21165', 1860, 3.0)
('21165', 948, 5.0)
('21165', 920, 5.0)
('21165', 4734, 5.0)
('21165', 4734, 5.0)
('21165', 4525, 3.0)
('21165', 1366, 5.0)
('21165', 4734, 5.0)
('21165', 3450, 3.0)
('21165', 1366, 5.0)
('21165', 1366, 5.0)
('21165', 1331, 5.0)
('21165', 3267, 3.0)
('21165', 1036, 5.0)
('21165', 1360, 5.0)
('21165', 1036, 5.0)
('21165', 3931, 1.0)
('21165', 4268, 5.0)
('21165', 412, 5.0)
('21165', 1859, 3.0)
('21165', 4545, 5.0)
('21165', 4886, 5.0)
('21165', 1699, 5.0)
('21165', 2270, 5.0)
('21165', 2608, 1.0)
('21165', 3908, 3.0)
('21165', 4279, 5.0)
('21165', 1381, 5.0)
('21165', 358, 3.0)
('21165', 4936, 3.0)
('21165', 1547, 5.0)
('21165', 3838, 5.0)
('21165', 407, 3.0)
('21165', 4099, 5.0)
('21165', 2820, 5.0)
('21165', 154, 5.0)
('21165', 1344, 3.0)
('21165', 4651, 5.0)
('21165', 2608, 5.0)
('21165', 1724, 5.0)
('21165', 2221, 3.0)
('21166', 1533, 5.0)
('21166', 2383, 5.0)
('21166', 2460, 5.0)
('21166', 4734, 5.0)
('21166', 4758, 3.0)
('21167', 1535, 3.0)
('21167', 323, 5.0)
('21168', 1210, 5.0)
('21169', 1004, 5.0)
('21169', 262, 3.0)
('21170', 5180, 5.0)
('21171', 553, 5.0)
('21171', 553, 5.0)
('21172', 1139, 5.0)
('21173', 1702, 5.0)
('21173', 4510, 5.0)
('21173', 1602, 3.0)
('21173', 27, 3.0)
('21173', 3283, 5.0)
('21173', 3209, 5.0)
('21173', 5332, 5.0)
('21173', 5046, 3.0)
('21174', 1210, 5.0)
('21174', 1210, 5.0)
('21175', 2528, 5.0)
('21175', 2310, 3.0)
('21176', 5335, 1.0)
('21177', 3029, 5.0)
('21178', 485, 4.0)
('21178', 4211, 5.0)
('21178', 4052, 3.0)
('21178', 5405, 4.0)
('21178', 1516, 5.0)
('21178', 1988, 3.0)
('21178', 3655, 4.0)
('21178', 4402, 4.0)
('21178', 431, 4.0)
('21178', 1178, 4.0)
('21178', 530, 5.0)
('21178', 4608, 5.0)
('21178', 1433, 4.0)
('21178', 1057, 4.0)
('21178', 2245, 4.0)
('21178', 1647, 4.0)
('21179', 3988, 5.0)
('21180', 4019, 5.0)
('21181', 407, 5.0)
('21181', 3394, 5.0)
('21182', 3792, 4.0)
('21183', 5019, 5.0)
('21184', 3174, 4.0)
('21185', 4557, 5.0)
('21186', 3651, 5.0)
('21186', 369, 5.0)
('21186', 755, 3.0)
('21186', 3651, 5.0)
('21187', 1621, 3.0)
('21187', 637, 3.0)
('21187', 1571, 5.0)
('21187', 3428, 3.0)
('21187', 2541, 5.0)
('21187', 2185, 5.0)
('21187', 1275, 5.0)
('21187', 3450, 5.0)
('21187', 3084, 5.0)
('21187', 1882, 5.0)
('21188', 3470, 1.0)
('21189', 2786, 4.0)
('21190', 2250, 1.0)
('21191', 5202, 5.0)
('21192', 5459, 5.0)
('21193', 5127, 5.0)
('21193', 4023, 5.0)
('21193', 578, 1.0)
('21193', 1173, 5.0)
('21193', 5457, 5.0)
('21193', 1279, 5.0)
('21193', 4555, 3.0)
('21193', 3800, 5.0)
('21193', 2806, 5.0)
('21193', 1185, 5.0)
('21193', 1719, 3.0)
('21194', 2820, 5.0)
('21194', 4745, 1.0)
('21194', 4066, 3.0)
('21194', 1327, 5.0)
('21194', 2146, 3.0)
('21195', 1210, 3.0)
('21196', 4931, 3.0)
('21196', 1094, 3.0)
('21197', 2707, 5.0)
('21198', 1647, 1.0)
('21199', 1064, 4.0)
('21199', 5080, 5.0)
('21199', 4093, 4.0)
('21199', 780, 5.0)
('21199', 1403, 3.0)
('21199', 5429, 4.0)
('21199', 2029, 4.0)
('21199', 3947, 5.0)
('21199', 3705, 4.0)
('21199', 2678, 3.0)
('21199', 3755, 4.0)
('21199', 443, 2.0)
('21199', 4720, 1.0)
('21199', 4019, 5.0)
('21199', 3362, 4.0)
('21199', 1022, 4.0)
('21199', 2412, 5.0)
('21199', 3240, 3.0)
('21200', 2510, 5.0)
('21201', 2146, 5.0)
('21201', 2772, 5.0)
('21201', 1978, 5.0)
('21201', 643, 3.0)
('21202', 2270, 3.0)
('21203', 229, 1.0)
('21204', 1299, 4.0)
('21204', 2093, 4.0)
('21204', 4743, 4.0)
('21204', 1334, 4.0)
('21204', 367, 5.0)
('21204', 4916, 4.0)
('21205', 1342, 5.0)
('21206', 4597, 5.0)
('21206', 1496, 5.0)
('21206', 3803, 4.0)
('21206', 4183, 5.0)
('21207', 1210, 5.0)
('21207', 1716, 5.0)
('21207', 4213, 5.0)
('21207', 4758, 5.0)
('21207', 1447, 5.0)
('21208', 3580, 5.0)
('21209', 3379, 5.0)
('21210', 2960, 5.0)
('21210', 2122, 3.0)
('21210', 2329, 5.0)
('21210', 2265, 5.0)
('21210', 4080, 5.0)
('21210', 4530, 3.0)
('21211', 4692, 5.0)
('21211', 4626, 5.0)
('21212', 2807, 1.0)
('21213', 4023, 3.0)
('21214', 1455, 1.0)
('21214', 2865, 3.0)
('21215', 1170, 1.0)
('21216', 4835, 5.0)
('21217', 4799, 5.0)
('21218', 5312, 1.0)
('21219', 3667, 4.0)
('21220', 5298, 1.0)
('21220', 925, 5.0)
('21220', 515, 5.0)
('21220', 3118, 1.0)
('21220', 3542, 5.0)
('21220', 5368, 5.0)
('21220', 1331, 3.0)
('21220', 1675, 5.0)
('21220', 3527, 1.0)
('21220', 3569, 5.0)
('21220', 2363, 5.0)
('21220', 3669, 5.0)
('21220', 1295, 5.0)
('21220', 2352, 5.0)
('21221', 4962, 5.0)
('21221', 2079, 4.0)
('21221', 1210, 4.0)
('21222', 1510, 1.0)
('21223', 916, 1.0)
('21223', 3851, 1.0)
('21223', 5445, 3.0)
('21223', 161, 1.0)
('21223', 720, 5.0)
('21223', 1970, 5.0)
('21224', 5180, 5.0)
('21225', 2260, 5.0)
('21225', 430, 5.0)
('21226', 2135, 1.0)
('21227', 1381, 3.0)
('21228', 2464, 5.0)
('21228', 375, 5.0)
('21228', 3151, 3.0)
('21228', 5392, 5.0)
('21228', 1368, 3.0)
('21228', 4345, 5.0)
('21228', 789, 1.0)
('21228', 375, 5.0)
('21228', 2664, 5.0)
('21228', 3169, 5.0)
('21228', 4149, 5.0)
('21228', 4838, 5.0)
('21228', 3279, 1.0)
('21228', 3428, 5.0)
('21228', 4758, 5.0)
('21228', 1725, 5.0)
('21228', 2812, 5.0)
('21228', 3487, 3.0)
('21228', 5259, 5.0)
('21228', 4574, 5.0)
('21228', 2611, 3.0)
('21228', 5040, 5.0)
('21228', 3988, 5.0)
('21228', 3118, 3.0)
('21228', 17, 5.0)
('21229', 4130, 3.0)
('21229', 1904, 5.0)
('21230', 1535, 5.0)
('21230', 3029, 5.0)
('21231', 4556, 5.0)
('21232', 4322, 5.0)
('21233', 272, 4.0)
('21234', 2409, 3.0)
('21235', 5337, 3.0)
('21236', 1639, 1.0)
('21237', 405, 5.0)
('21238', 4997, 5.0)
('21238', 4055, 5.0)
('21239', 1036, 3.0)
('21240', 4664, 5.0)
('21241', 2106, 3.0)
('21241', 3432, 5.0)
('21241', 948, 5.0)
('21241', 1970, 3.0)
('21241', 496, 3.0)
('21241', 3053, 5.0)
('21241', 3855, 5.0)
('21241', 629, 3.0)
('21241', 2453, 5.0)
('21241', 5220, 3.0)
('21242', 3453, 4.0)
('21242', 5358, 1.0)
('21242', 3828, 5.0)
('21242', 2345, 4.0)
('21242', 3572, 4.0)
('21242', 4315, 4.0)
('21242', 5374, 5.0)
('21243', 4918, 1.0)
('21244', 175, 1.0)
('21245', 637, 5.0)
('21245', 538, 3.0)
('21246', 3705, 5.0)
('21246', 2584, 5.0)
('21246', 987, 5.0)
('21247', 2496, 5.0)
('21248', 4918, 5.0)
('21249', 5146, 4.0)
('21249', 3310, 4.0)
('21250', 1092, 1.0)
('21250', 2959, 5.0)
('21251', 1767, 5.0)
('21252', 1547, 1.0)
('21253', 3470, 3.0)
('21254', 3754, 1.0)
('21255', 759, 5.0)
('21256', 431, 5.0)
('21256', 4756, 3.0)
('21256', 4169, 5.0)
('21256', 4223, 5.0)
('21256', 4223, 5.0)
('21256', 3781, 5.0)
('21257', 4934, 3.0)
('21257', 5337, 1.0)
('21258', 3084, 4.0)
('21259', 2354, 4.0)
('21259', 3016, 4.0)
('21259', 2753, 5.0)
('21260', 823, 5.0)
('21261', 4361, 5.0)
('21261', 3705, 1.0)
('21261', 3886, 5.0)
('21262', 4812, 5.0)
('21262', 2472, 5.0)
('21263', 637, 3.0)
('21264', 1468, 1.0)
('21265', 3243, 5.0)
('21265', 3855, 1.0)
('21266', 1724, 5.0)
('21267', 3477, 1.0)
('21268', 1666, 5.0)
('21269', 1458, 3.0)
('21269', 3591, 5.0)
('21270', 3908, 5.0)
('21270', 194, 3.0)
('21271', 1536, 5.0)
('21271', 1236, 5.0)
('21271', 4175, 3.0)
('21271', 3177, 5.0)
('21271', 4142, 5.0)
('21271', 4993, 5.0)
('21271', 1619, 4.0)
('21271', 1717, 4.0)
('21271', 4019, 3.0)
('21271', 1502, 5.0)
('21271', 3925, 5.0)
('21271', 3930, 4.0)
('21271', 2162, 5.0)
('21272', 3130, 5.0)
('21272', 186, 5.0)
('21272', 3487, 5.0)
('21272', 5026, 3.0)
('21272', 2632, 5.0)
('21272', 1755, 5.0)
('21272', 1356, 5.0)
('21272', 2577, 5.0)
('21273', 316, 5.0)
('21274', 5137, 5.0)
('21274', 2804, 5.0)
('21274', 3209, 5.0)
('21275', 1605, 3.0)
('21276', 102, 5.0)
('21277', 2123, 4.0)
('21278', 1997, 1.0)
('21279', 1552, 5.0)
('21279', 3416, 5.0)
('21280', 3912, 3.0)
('21280', 2292, 5.0)
('21280', 2531, 5.0)
('21281', 1047, 5.0)
('21281', 201, 5.0)
('21281', 3053, 5.0)
('21281', 4272, 5.0)
('21281', 2437, 3.0)
('21281', 2511, 5.0)
('21281', 2404, 3.0)
('21281', 2929, 5.0)
('21281', 2496, 3.0)
('21281', 258, 5.0)
('21281', 759, 5.0)
('21282', 691, 5.0)
('21282', 3149, 5.0)
('21282', 692, 5.0)
('21282', 20, 5.0)
('21282', 5407, 5.0)
('21282', 1209, 3.0)
('21282', 1736, 1.0)
('21282', 3505, 5.0)
('21282', 2632, 5.0)
('21282', 1967, 5.0)
('21283', 3886, 5.0)
('21284', 996, 5.0)
('21284', 694, 3.0)
('21284', 2053, 3.0)
('21284', 387, 5.0)
('21284', 1547, 5.0)
('21284', 3136, 5.0)
('21284', 5302, 1.0)
('21284', 4288, 5.0)
('21284', 4742, 3.0)
('21284', 2666, 5.0)
('21284', 2416, 3.0)
('21284', 2632, 5.0)
('21284', 2129, 3.0)
('21284', 5321, 3.0)
('21284', 1258, 5.0)
('21284', 81, 5.0)
('21285', 3268, 5.0)
('21286', 2804, 5.0)
('21287', 549, 5.0)
('21288', 3642, 3.0)
('21288', 4728, 3.0)
('21288', 3991, 3.0)
('21289', 5063, 1.0)
('21290', 1970, 5.0)
('21291', 2865, 5.0)
('21291', 3591, 4.0)
('21291', 5308, 4.0)
('21291', 1781, 5.0)
('21291', 1048, 5.0)
('21291', 899, 4.0)
('21291', 1047, 5.0)
('21291', 157, 3.0)
('21292', 4742, 5.0)
('21293', 1494, 5.0)
('21293', 483, 5.0)
('21293', 4801, 5.0)
('21294', 1552, 5.0)
('21294', 3791, 5.0)
('21294', 3197, 5.0)
('21294', 3920, 5.0)
('21294', 1587, 5.0)
('21294', 3749, 5.0)
('21294', 1130, 5.0)
('21294', 2009, 5.0)
('21294', 4586, 5.0)
('21294', 3063, 5.0)
('21295', 191, 4.0)
('21296', 3750, 1.0)
('21296', 962, 5.0)
('21296', 4718, 5.0)
('21297', 3890, 3.0)
('21297', 1406, 5.0)
('21297', 4255, 5.0)
('21298', 5146, 5.0)
('21298', 1077, 5.0)
('21298', 4933, 1.0)
('21299', 5295, 5.0)
('21299', 4651, 5.0)
('21299', 4889, 5.0)
('21300', 273, 5.0)
('21300', 600, 5.0)
('21300', 3726, 5.0)
('21300', 873, 5.0)
('21300', 3441, 5.0)
('21300', 4818, 5.0)
('21300', 3726, 3.0)
('21300', 2532, 3.0)
('21300', 3323, 5.0)
('21300', 1752, 5.0)
('21301', 628, 5.0)
('21302', 3652, 4.0)
('21303', 2472, 4.0)
('21304', 3154, 5.0)
('21305', 2177, 5.0)
('21306', 1019, 5.0)
('21307', 1558, 5.0)
('21308', 4185, 4.0)
('21309', 1816, 3.0)
('21309', 1403, 3.0)
('21309', 285, 4.0)
('21309', 3548, 4.0)
('21309', 4774, 3.0)
('21310', 791, 5.0)
('21310', 614, 1.0)
('21311', 1057, 5.0)
('21312', 4107, 1.0)
('21313', 3551, 5.0)
('21314', 1424, 1.0)
('21314', 4353, 3.0)
('21314', 1780, 3.0)
('21314', 2846, 5.0)
('21315', 1535, 5.0)
('21316', 2008, 5.0)
('21317', 1543, 1.0)
('21318', 1905, 3.0)
('21318', 4152, 5.0)
('21319', 4586, 5.0)
('21319', 959, 5.0)
('21319', 27, 5.0)
('21319', 2265, 5.0)
('21319', 2809, 3.0)
('21319', 3209, 3.0)
('21319', 3920, 5.0)
('21319', 2469, 5.0)
('21319', 4557, 5.0)
('21319', 1859, 5.0)
('21319', 2002, 5.0)
('21319', 9, 5.0)
('21319', 1283, 3.0)
('21320', 130, 5.0)
('21321', 2338, 4.0)
('21322', 612, 1.0)
('21322', 496, 1.0)
('21323', 2805, 5.0)
('21323', 3151, 5.0)
('21324', 1816, 5.0)
('21325', 5198, 5.0)
('21326', 4019, 5.0)
('21326', 3580, 5.0)
('21327', 1816, 4.0)
('21328', 3517, 5.0)
('21329', 2970, 5.0)
('21330', 5268, 5.0)
('21331', 959, 5.0)
('21331', 1368, 5.0)
('21332', 640, 4.0)
('21332', 2137, 4.0)
('21333', 528, 5.0)
('21334', 3140, 5.0)
('21334', 4805, 5.0)
('21335', 4903, 5.0)
('21336', 3059, 5.0)
('21337', 431, 2.0)
('21337', 4859, 1.0)
('21337', 3673, 1.0)
('21338', 1672, 5.0)
('21339', 1978, 5.0)
('21340', 4861, 5.0)
('21340', 788, 5.0)
('21340', 3655, 5.0)
('21340', 4066, 3.0)
('21340', 4066, 5.0)
('21340', 5058, 5.0)
('21340', 4020, 5.0)
('21340', 1180, 5.0)
('21340', 4223, 5.0)
('21340', 856, 5.0)
('21340', 1215, 5.0)
('21340', 5153, 5.0)
('21340', 3194, 3.0)
('21340', 2146, 3.0)
('21340', 4785, 5.0)
('21340', 4248, 5.0)
('21340', 4248, 5.0)
('21340', 2910, 3.0)
('21340', 1169, 5.0)
('21340', 2146, 5.0)
('21340', 2576, 5.0)
('21340', 1366, 5.0)
('21340', 3379, 5.0)
('21340', 4050, 5.0)
('21340', 4642, 5.0)
('21340', 1366, 5.0)
('21340', 3995, 5.0)
('21340', 4662, 5.0)
('21340', 4861, 3.0)
('21340', 5122, 5.0)
('21340', 1631, 3.0)
('21340', 5060, 5.0)
('21340', 1169, 5.0)
('21340', 5026, 5.0)
('21340', 3432, 5.0)
('21340', 1273, 5.0)
('21340', 5460, 5.0)
('21340', 1658, 1.0)
('21340', 692, 5.0)
('21340', 4549, 5.0)
('21340', 2053, 3.0)
('21340', 4870, 3.0)
('21340', 4827, 3.0)
('21340', 5460, 5.0)
('21340', 4501, 5.0)
('21340', 3169, 5.0)
('21340', 1312, 5.0)
('21340', 28, 5.0)
('21340', 3761, 5.0)
('21340', 4080, 5.0)
('21340', 1125, 1.0)
('21340', 3170, 3.0)
('21340', 5456, 5.0)
('21340', 606, 5.0)
('21340', 130, 5.0)
('21340', 709, 5.0)
('21340', 709, 5.0)
('21340', 3838, 5.0)
('21340', 3432, 5.0)
('21340', 1946, 5.0)
('21340', 2574, 5.0)
('21340', 891, 5.0)
('21340', 2702, 5.0)
('21340', 573, 5.0)
('21340', 1068, 3.0)
('21340', 5153, 5.0)
('21340', 2588, 5.0)
('21340', 1169, 5.0)
('21340', 1443, 1.0)
('21340', 4728, 3.0)
('21340', 4646, 3.0)
('21340', 5460, 5.0)
('21340', 4646, 5.0)
('21340', 1486, 3.0)
('21340', 4646, 5.0)
('21340', 1339, 5.0)
('21340', 709, 5.0)
('21340', 237, 5.0)
('21340', 585, 5.0)
('21340', 3296, 5.0)
('21340', 1438, 5.0)
('21340', 3194, 5.0)
('21340', 765, 5.0)
('21340', 4651, 5.0)
('21340', 5432, 1.0)
('21340', 5215, 5.0)
('21340', 2820, 5.0)
('21340', 208, 5.0)
('21340', 4590, 5.0)
('21340', 2879, 5.0)
('21340', 3388, 5.0)
('21340', 1579, 3.0)
('21340', 3115, 5.0)
('21340', 509, 5.0)
('21340', 2770, 5.0)
('21340', 2770, 5.0)
('21340', 4606, 5.0)
('21340', 3501, 5.0)
('21340', 3501, 5.0)
('21340', 2859, 1.0)
('21340', 617, 5.0)
('21340', 1846, 5.0)
('21340', 1846, 5.0)
('21340', 3542, 5.0)
('21340', 1602, 5.0)
('21340', 490, 5.0)
('21340', 3319, 5.0)
('21340', 412, 5.0)
('21340', 4152, 5.0)
('21340', 2569, 5.0)
('21340', 2569, 5.0)
('21340', 3908, 5.0)
('21340', 177, 5.0)
('21340', 119, 5.0)
('21340', 119, 5.0)
('21340', 4758, 5.0)
('21340', 4984, 5.0)
('21340', 120, 3.0)
('21340', 4155, 5.0)
('21340', 1602, 5.0)
('21340', 4122, 5.0)
('21340', 3754, 5.0)
('21340', 4758, 5.0)
('21340', 3249, 5.0)
('21340', 3022, 5.0)
('21340', 177, 3.0)
('21340', 3705, 5.0)
('21340', 437, 5.0)
('21340', 1293, 5.0)
('21340', 177, 3.0)
('21340', 4811, 5.0)
('21340', 222, 3.0)
('21340', 1778, 5.0)
('21340', 2879, 5.0)
('21340', 1679, 5.0)
('21340', 3006, 5.0)
('21340', 1127, 5.0)
('21340', 3435, 3.0)
('21340', 478, 5.0)
('21340', 3863, 5.0)
('21340', 1904, 5.0)
('21340', 974, 5.0)
('21340', 3308, 5.0)
('21340', 4737, 5.0)
('21340', 2256, 5.0)
('21340', 765, 5.0)
('21340', 3006, 3.0)
('21340', 179, 5.0)
('21340', 2713, 5.0)
('21340', 1396, 5.0)
('21340', 4803, 5.0)
('21341', 2097, 4.0)
('21342', 2840, 5.0)
('21342', 1386, 3.0)
('21342', 2637, 5.0)
('21342', 4962, 5.0)
('21342', 4758, 1.0)
('21342', 689, 1.0)
('21343', 4155, 3.0)
('21344', 1434, 5.0)
('21344', 4005, 5.0)
('21344', 803, 4.0)
('21344', 3939, 4.0)
('21344', 5429, 4.0)
('21345', 493, 5.0)
('21345', 3565, 5.0)
('21345', 887, 5.0)
('21345', 3173, 5.0)
('21346', 3256, 5.0)
('21347', 1165, 4.0)
('21347', 3327, 4.0)
('21348', 2654, 5.0)
('21348', 1780, 5.0)
('21349', 5372, 5.0)
('21349', 403, 5.0)
('21349', 2764, 5.0)
('21349', 289, 5.0)
('21350', 2578, 5.0)
('21351', 4317, 5.0)
('21352', 320, 4.0)
('21352', 1733, 5.0)
('21352', 5406, 5.0)
('21353', 4908, 5.0)
('21353', 4764, 5.0)
('21353', 1331, 3.0)
('21353', 1170, 3.0)
('21353', 4613, 3.0)
('21353', 3053, 3.0)
('21354', 1780, 5.0)
('21355', 1588, 3.0)
('21355', 3434, 1.0)
('21355', 4390, 5.0)
('21356', 1619, 2.0)
('21356', 5046, 4.0)
('21356', 3572, 5.0)
('21356', 4774, 1.0)
('21356', 614, 2.0)
('21356', 4087, 3.0)
('21356', 3990, 3.0)
('21357', 5290, 5.0)
('21357', 3928, 5.0)
('21357', 1618, 5.0)
('21357', 161, 5.0)
('21357', 2901, 5.0)
('21357', 3308, 5.0)
('21357', 2665, 5.0)
('21358', 1547, 3.0)
('21358', 1193, 3.0)
('21358', 2151, 5.0)
('21359', 3786, 5.0)
('21359', 1410, 5.0)
('21359', 2185, 5.0)
('21359', 4651, 5.0)
('21359', 38, 3.0)
('21360', 3127, 3.0)
('21361', 4098, 5.0)
('21362', 1210, 5.0)
('21362', 1210, 5.0)
('21363', 663, 5.0)
('21364', 1869, 1.0)
('21365', 353, 1.0)
('21366', 5298, 1.0)
('21367', 4156, 3.0)
('21367', 3754, 1.0)
('21367', 3591, 4.0)
('21368', 570, 5.0)
('21368', 1424, 5.0)
('21369', 3877, 3.0)
('21369', 5180, 1.0)
('21369', 5371, 5.0)
('21369', 3534, 3.0)
('21369', 995, 1.0)
('21370', 4836, 5.0)
('21370', 4255, 3.0)
('21370', 4030, 3.0)
('21370', 4981, 5.0)
('21370', 3243, 3.0)
('21370', 1755, 5.0)
('21370', 3136, 5.0)
('21370', 5298, 5.0)
('21370', 851, 5.0)
('21370', 5038, 5.0)
('21370', 3010, 5.0)
('21370', 4523, 5.0)
('21370', 1765, 3.0)
('21370', 894, 5.0)
('21370', 1784, 5.0)
('21370', 4897, 5.0)
('21370', 2101, 3.0)
('21370', 1876, 5.0)
('21370', 3835, 5.0)
('21370', 3490, 3.0)
('21370', 4651, 5.0)
('21370', 4413, 3.0)
('21370', 161, 5.0)
('21370', 2999, 5.0)
('21370', 4087, 5.0)
('21370', 2392, 1.0)
('21371', 4539, 5.0)
('21372', 899, 1.0)
('21372', 2819, 3.0)
('21372', 642, 3.0)
('21372', 839, 3.0)
('21372', 4142, 3.0)
('21372', 813, 3.0)
('21373', 2211, 5.0)
('21373', 980, 3.0)
('21373', 1818, 3.0)
('21373', 5022, 3.0)
('21373', 1468, 3.0)
('21373', 5090, 1.0)
('21373', 4096, 3.0)
('21373', 5320, 5.0)
('21373', 5143, 3.0)
('21373', 1424, 3.0)
('21373', 4456, 1.0)
('21373', 4694, 1.0)
('21373', 429, 3.0)
('21373', 3177, 3.0)
('21373', 1220, 5.0)
('21373', 3053, 5.0)
('21373', 4500, 5.0)
('21373', 1438, 5.0)
('21373', 367, 3.0)
('21373', 506, 3.0)
('21373', 356, 3.0)
('21373', 4963, 3.0)
('21373', 4258, 1.0)
('21373', 4953, 5.0)
('21373', 2984, 3.0)
('21373', 1618, 5.0)
('21373', 4404, 3.0)
('21373', 300, 5.0)
('21373', 725, 5.0)
('21373', 1142, 5.0)
('21373', 2637, 3.0)
('21373', 2501, 5.0)
('21373', 2437, 3.0)
('21373', 1153, 5.0)
('21373', 805, 5.0)
('21373', 2323, 3.0)
('21373', 5375, 5.0)
('21373', 4366, 1.0)
('21373', 4866, 3.0)
('21373', 974, 3.0)
('21373', 2849, 1.0)
('21373', 5416, 5.0)
('21373', 3839, 5.0)
('21373', 1714, 3.0)
('21373', 2992, 3.0)
('21373', 1424, 3.0)
('21373', 2690, 1.0)
('21373', 4080, 1.0)
('21373', 619, 3.0)
('21373', 1383, 3.0)
('21373', 3507, 3.0)
('21373', 2962, 3.0)
('21373', 3659, 3.0)
('21373', 2865, 3.0)
('21373', 1499, 3.0)
('21373', 2573, 5.0)
('21373', 407, 3.0)
('21373', 4686, 3.0)
('21373', 1077, 3.0)
('21373', 1093, 3.0)
('21373', 2965, 5.0)
('21373', 1005, 3.0)
('21373', 4574, 1.0)
('21373', 4500, 3.0)
('21373', 4206, 3.0)
('21373', 1114, 3.0)
('21373', 899, 3.0)
('21373', 740, 3.0)
('21373', 1748, 1.0)
('21373', 987, 5.0)
('21373', 289, 5.0)
('21373', 1725, 3.0)
('21373', 4053, 5.0)
('21373', 1822, 3.0)
('21373', 2611, 3.0)
('21373', 5015, 3.0)
('21373', 3827, 5.0)
('21373', 3506, 3.0)
('21373', 3526, 3.0)
('21373', 3005, 5.0)
('21373', 3103, 3.0)
('21373', 661, 5.0)
('21373', 1342, 3.0)
('21373', 3379, 1.0)
('21373', 4822, 3.0)
('21373', 3124, 5.0)
('21373', 4035, 3.0)
('21373', 151, 1.0)
('21373', 4967, 3.0)
('21373', 1360, 5.0)
('21373', 705, 1.0)
('21373', 3382, 5.0)
('21373', 2481, 1.0)
('21373', 2966, 5.0)
('21373', 1264, 1.0)
('21373', 637, 5.0)
('21373', 1344, 5.0)
('21373', 4236, 3.0)
('21373', 4059, 1.0)
('21373', 5460, 5.0)
('21373', 3835, 3.0)
('21373', 616, 1.0)
('21374', 2425, 4.0)
('21374', 1746, 4.0)
('21374', 2902, 4.0)
('21375', 642, 3.0)
('21375', 3580, 5.0)
('21375', 2149, 3.0)
('21376', 1595, 5.0)
('21376', 4984, 5.0)
('21376', 4107, 5.0)
('21376', 5323, 5.0)
('21376', 3233, 3.0)
('21376', 3797, 5.0)
('21376', 1647, 3.0)
('21376', 456, 5.0)
('21376', 4701, 5.0)
('21376', 1448, 5.0)
('21376', 5123, 1.0)
('21376', 925, 3.0)
('21376', 4600, 1.0)
('21376', 3967, 5.0)
('21376', 2435, 3.0)
('21377', 1780, 5.0)
('21377', 1780, 5.0)
('21378', 1555, 3.0)
('21379', 4006, 5.0)
('21379', 3578, 5.0)
('21379', 323, 5.0)
('21379', 5375, 5.0)
('21379', 3388, 5.0)
('21380', 2584, 5.0)
('21380', 5418, 5.0)
('21380', 4946, 5.0)
('21380', 3388, 5.0)
('21380', 1780, 5.0)
('21380', 314, 5.0)
('21380', 4347, 5.0)

In [ ]:
#Define an evaluation method to split feedback into train and test sets
ratio_split = RatioSplit(
    data=data,
    test_size=0.1,
    val_size=0.1,
    rating_threshold=1.0,
    seed=123,
    verbose=True,
)

neumf = cornac.models.NeuMF(
    layers=[64, 32, 16, 8],
    act_fn="tanh",
    learner="adam",
    num_neg=50,
    seed=123,
    early_stopping = {'min_delta':0.0, 'patience':5}
)

# RandomSearch
rs_neumf = RandomSearch(
    model = neumf,
    space=[
        Discrete("num_epochs", [50, 100, 150, 200]),
        Discrete("num_factors", [4, 8]),
        Discrete("batch_size", [128, 256, 512]),
        Continuous("lr", 0.001, 0.01)
    ],
    metric = fm,
    eval_method = ratio_split
)

# Put everything together into an experiment and run it
cornac.Experiment(
    eval_method=ratio_split,
    models=[rs_neumf],
    metrics=[ndcg, pre, rec, fm],
).run()

rating_threshold = 1.0
exclude_unknowns = True
---
Training data:
Number of users = 19705
Number of items = 5318
Number of ratings = 81784
Max rating = nan
Min rating = nan
Global mean = nan
---
Test data:
Number of users = 4275
Number of items = 2920
Number of ratings = 9116
Number of unknown users = 0
Number of unknown items = 0
---
Validation data:
Number of users = 4285
Number of items = 2990
Number of ratings = 9114
---
Total users = 19705
Total items = 5318

[RandomSearch_NeuMF] Training started!
Evaluating: {'batch_size': 512, 'lr': 0.007416597884709045, 'num_epochs': 150, 'num_factors': 4}

  0%|          | 0/150 [00:00<?, ?it/s]

Early stopping:
- best epoch = 19, stopped epoch = 24
- best monitored value = 0.077429 (delta = -0.001048)
Evaluating: {'batch_size': 512, 'lr': 0.005961832921746022, 'num_epochs': 200, 'num_factors': 4}

  0%|          | 0/200 [00:00<?, ?it/s]

Early stopping:
- best epoch = 37, stopped epoch = 42
- best monitored value = 0.078229 (delta = -0.002393)
Evaluating: {'batch_size': 256, 'lr': 0.00982687778546154, 'num_epochs': 50, 'num_factors': 8}

  0%|          | 0/50 [00:00<?, ?it/s]

In [ ]:
print('Random search: ', rs_neumf.best_params)

In [ ]:
ratio_split = RatioSplit(
    data=data,
    test_size=0,
    rating_threshold=1.0,
    verbose=True,
)

neumf = cornac.models.NeuMF(
    num_factors = rs_neumf.best_params['num_factors'],
    layers=[64, 32, 16, 8],
    act_fn="tanh",
    learner="adam",
    num_epochs = rs_neumf.best_params['num_epochs'],
    lr=rs_neumf.best_params['lr'],
    num_neg=50,
    batch_size = rs_neumf.best_params['batch_size'],
    seed=123,
    early_stopping = {'min_delta':0.0, 'patience':5}
)

cornac.Experiment(
    eval_method=ratio_split,
    models=[neumf],
    metrics=[ndcg, pre, rec, fm],
).run()

In [ ]:
import pandas as pd
pred_user = pd.read_csv('/content/drive/MyDrive/ML_data/survey_result.csv')
pred_user = set(pred_user['u_id'])

In [ ]:
print(data_df.head())

In [ ]:
all_prediction = pd.DataFrame(columns=['u_id','p_id','ncf_score'])

for u_idx, u_id in tqdm(enumerate(data_df['userID'].unique())):
    if u_id in pred_user:
        tmp = pd.DataFrame(neumf.rank(u_idx)).T
        tmp['u_id'] = u_id
        tmp = pd.DataFrame(tmp,columns=['u_id',0,1])
        tmp.rename(columns={0:'p_id',1:'ncf_score'}, inplace=True)
        all_prediction = all_prediction.append(tmp)

In [ ]:
all_prediction

In [ ]:
all_prediction.to_csv('/content/drive/MyDrive/ML_data/predictions/ncf_scores.scv',index=False)

CBF 모델

In [ ]:
import pandas as pd
import numpy as np
import math
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))
res_matrix = pd.read_csv('/content/drive/MyDrive/ML_data/res_matrix.csv')
user_matrix = pd.read_csv('/content/drive/MyDrive/ML_data/user_adj_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/ML_data/group_count.csv',names=['group','count'])

res_matrix.set_index('p_id', drop=True, inplace=True)
user_matrix.set_index('u_id', drop=True, inplace=True)
group_count.set_index('group', drop=True, inplace=True)
user_matrix

최종